### ISSUE TITLE
Lutris does not recognize my local

### ISSUE THREAD

**Issue by datner** [lutris/lutris#1017]
After installing lutris, firing it up for the first time did not yield any results. 
booting it from the console game be the following callback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 169, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 145, in __init__
    self.update_runtime()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 388, in update_runtime
    self.runtime_updater.update(self.set_status)
  File "/usr/lib/python3/dist-packages/lutris/runtime.py", line 41, in update
    self.download_runtime(runtime)
  File "/usr/lib/python3/dist-packages/lutris/runtime.py", line 70, in download_runtime
    "%Y-%m-%dT%H:%M:%S")
  File "/usr/lib/python3.6/_strptime.py", line 280, in <module>
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python3.6/_strptime.py", line 194, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python3.6/_strptime.py", line 72, in __init__
    self.lang = _getlang()
  File "/usr/lib/python3.6/_strptime.py", line 31, in _getlang
    return locale.getlocale(locale.LC_TIME)
  File "/usr/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en_IL
```
`ValueError: unknown locale: en_IL` hints to me that the specific calibration of my system (I live in Israel and use a Hebrew keyboard but I like my OS to be entirely English) might be foreign to Lutris.
I could also be absolutely wrong

**Comment by datner** [comment]
My quick and dirty fix was to add my locale (en_il) to the `locale.py` file.
It works, but I don't think it's the appropriate thing to do
