### ISSUE TITLE
ValueError: Missing mandatory appid

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1098]
if one change a game from one runner (tried it going from linux to steam) and "forget" to add an appid it won't save but there is no feedback to the user about the error, maybe add a popup that inform the user that an appid is needed.

```
Traceback (most recent call last):
  File "/src/lutris/lutris/gui/config_dialogs.py", line 367, in on_save
    self.game.directory = runner.game_path
  File "/src/lutris/lutris/runners/steam.py", line 159, in game_path
    game_path = get_path_from_appmanifest(apps_path, self.appid)
  File "/src/lutris/lutris/services/steam.py", line 171, in get_path_from_appmanifest
    appmanifest = get_appmanifest_from_appid(steamapps_path, appid)
  File "/src/lutris/lutris/services/steam.py", line 162, in get_appmanifest_from_appid
    raise ValueError("Missing mandatory appid")
ValueError: Missing mandatory appid
```

**Comment by duhow** [comment]
Which Lutris version are you using? This should be already fixed with #998 .

**Comment by telanus** [comment]
I Normally use the NEXT branch

**Comment by strycore** [comment]
Fixed by https://github.com/lutris/lutris/pull/998

**Comment by strycore** [comment]
> I Normally use the NEXT branch

Please only report bugs in the master branch.
