### ISSUE TITLE
Lutris fails to start due to TypeError: metaclass conflict

### ISSUE THREAD

**Issue by cdm2985** [lutris/lutris#1101]
Hi everyone, Lutris was working earlier for me until I updated some packages I'm assuming. I can't tell which ones they were but here is the error if someone can help me out so I can start Lutris again:

```
[chris@GT40 ~]$ lutris 
Traceback (most recent call last):
  File "/usr/bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 28, in <module>
    from gi.repository import Gio, GLib, Gtk
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/lib/python3.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 136, in <module>
    class Widget(Gtk.Widget):
  File "/usr/lib/python3.7/site-packages/gi/module.py", line 215, in __getattr__
    wrapper = metaclass(name, bases, dict_)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```

This is on Arch Linux.

**Comment by strycore** [comment]
![screenshot from 2018-09-08 12-30-24](https://user-images.githubusercontent.com/280336/45257922-ff86ee80-b362-11e8-9aee-faaed65dac94.png)

**Comment by cdm2985** [comment]
Thanks for this, I was able to downgrade from gtk3-3.24.0-2 to gtk3-3.22.30-1 and it fixed my issue. I used the downgrade command from the AUR to do this. Sorry for the waste of time!

**Comment by elovin** [comment]
Why would you use arch testing packages?

**Comment by strycore** [comment]
Closing this for now. I now have an Arch install so I can test for those things.
