### ISSUE TITLE
Launcher exe not being set

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1249]
@strycore would it be possible to make a script to change every instance of `exe: game.exe` in an installer to: 

```
game:
  exe: game.exe
``` 

Just setting `exe:` is no longer working.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 38, in <lambda>
    GLib.idle_add(lambda: self.callback(result, error))
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 529, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 560, in _finish_install
    if launcher_value:
UnboundLocalError: local variable 'launcher_value' referenced before assignment
```
Also maybe add this to the validator so it's avoidable?

**Comment by strycore** [comment]
Fix merged
