### ISSUE TITLE
Unreal Tournament installer stack trace

### ISSUE THREAD

**Issue by dennisjj4** [lutris/lutris#126]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lutris/installer.py", line 924, in download_complete
    self.interpreter.iter_game_files()
  File "/usr/local/lib/python2.7/dist-packages/lutris/installer.py", line 168, in iter_game_files
    self._download_file(current_file)
  File "/usr/local/lib/python2.7/dist-packages/lutris/installer.py", line 228, in _download_file
    self.install_steam_game(steam.steam)
  File "/usr/local/lib/python2.7/dist-packages/lutris/installer.py", line 597, in install_steam_game
    if not steam_runner.game_path(appid):
  File "/usr/local/lib/python2.7/dist-packages/lutris/runners/steam.py", line 62, in game_path
    appid = self.config['game'].get('appid')
KeyError: 'game'

**Comment by strycore** [comment]
Adding a note about the software renderer for this script
