### ISSUE TITLE
Vulkan check fails if ldconfig is not in the PATH

### ISSUE THREAD

**Issue by dmabtrg** [lutris/lutris#1290]
Hi,

When enabling DXVK, the vulkan check fails because it can't find the ldconfig command:

```
Traceback (most recent call last):
  File "/home/user/src/lutris/lutris/gui/config_boxes.py", line 229, in checkbox_toggle_with_callback
    if callback(self.config):
  File "/home/user/src/lutris/lutris/runners/wine.py", line 182, in dxvk_vulkan_callback
    result = vulkan.vulkan_check()
  File "/home/user/src/lutris/lutris/util/vulkan.py", line 16, in vulkan_check
    for line in subprocess.check_output(["ldconfig", "-p"]).splitlines():
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig': 'ldconfig'
```

I'm using Debian unstable and ldconfig is not in the PATH by default for regular users (it's in /sbin).  Calling ldconfig using the full path (or adding /sbin to $PATH) works as expected:

``` diff
diff --git a/lutris/util/vulkan.py b/lutris/util/vulkan.py
index 79eaff70..13a0a6e5 100644
--- a/lutris/util/vulkan.py
+++ b/lutris/util/vulkan.py
@@ -13,7 +13,7 @@ class vulkan_available(Enum):
 def vulkan_check():
     has_64_bit = False
     has_32_bit = False
-    for line in subprocess.check_output(["ldconfig", "-p"]).splitlines():
+    for line in subprocess.check_output(["/sbin/ldconfig", "-p"]).splitlines():
         line = str(line)
         if 'libvulkan' in line:
             if 'x86-64' in line:
```
but I don't know if this change would work on other distros.

Thanks.

**Comment by PythonicChemist** [comment]
OpenSuse is also affected by this bug. Confirmed with the help of PyroclasticMayhem
:  on discord.

**Comment by strycore** [comment]
I provided another implementation which doesn't use ldconfig and detect if Vulkan is actually supported, not just that it exists on the system
