### ISSUE TITLE
Build problem with 

### ISSUE THREAD

**Issue by jubalh** [lutris/lutris#1298]
With 0.4.22 I get the following the compiling:
```
[   39s] + python3 setup.py build
[   39s] Traceback (most recent call last):
[   39s]   File "setup.py", line 5, in <module>
[   39s]     from lutris.settings import VERSION
[   39s]   File "/home/abuild/rpmbuild/BUILD/lutris/lutris/settings.py", line 5, in <module>
[   39s]     from lutris.util.settings import SettingsIO
[   39s]   File "/home/abuild/rpmbuild/BUILD/lutris/lutris/util/settings.py", line 2, in <module>
[   39s]     from lutris.util import system
[   39s]   File "/home/abuild/rpmbuild/BUILD/lutris/lutris/util/system.py", line 12, in <module>
[   39s]     from gi.repository import Gtk, Gdk
[   39s]   File "/usr/lib64/python3.6/site-packages/gi/importer.py", line 133, in load_module
[   39s]     'introspection typelib not found' % namespace)
[   39s] ImportError: cannot import name Gtk, introspection typelib not found
```
Didn't change any dependencies or anything.

**Comment by BunnyApocalypse** [comment]
I can confirm that this issue is also happening when trying to package for Fedora.

Reverting [this commit](https://github.com/lutris/lutris/commit/03cbc6e58db21a58819c245d94450352beea6f66) allowed it to build, however this is obviously not ideal.

**Comment by strycore** [comment]
> We could move VERSION somewhere more reasonable and skip the whole chain of imports.

The place where VERSION reside *is* reasonable, I just fixed the imports instead.

**Comment by jubalh** [comment]
Works. Thanks!
