### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: games.id

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1321]
Trying to change a game from one runner to another and it "fails" if you press apply it jus sits there doing nothing,  I get this on the terminal 

  ```
File "~/src/lutris/lutris/gui/config_dialogs.py", line 376, in on_save
    self.game.save()
  File "~/src/lutris/lutris/game.py", line 173, in save
    playtime=self.playtime,
  File "~/src/lutris/lutris/pga.py", line 262, in add_or_update
    return add_game(**params)
  File "~/src/lutris/lutris/pga.py", line 225, in add_game
    return sql.db_insert(PGA_DB, "games", game_data)
  File "~/src/lutris/lutris/util/sql.py", line 54, in db_insert
    field_values
  File "~/src/lutris/lutris/util/sql.py", line 30, in cursor_execute
    return cursor.execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: games.id

```

**Comment by fres-a** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/installer/commands.py", line 409, in _monitor_task
    self._iter_commands()
  File "/usr/lib/python3.6/site-packages/lutris/installer/interpreter.py", line 529, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3.6/site-packages/lutris/installer/interpreter.py", line 570, in _finish_install
    self._write_config()
  File "/usr/lib/python3.6/site-packages/lutris/installer/interpreter.py", line 607, in _write_config
    id=self.game_id
  File "/usr/lib/python3.6/site-packages/lutris/pga.py", line 255, in add_or_update
    return add_game(**params)
  File "/usr/lib/python3.6/site-packages/lutris/pga.py", line 224, in add_game
    return sql.db_insert(PGA_DB, "games", game_data)
  File "/usr/lib/python3.6/site-packages/lutris/util/sql.py", line 54, in db_insert
    field_values
  File "/usr/lib/python3.6/site-packages/lutris/util/sql.py", line 30, in cursor_execute
    return cursor.execute(query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: games.id

fedora 28

**Comment by BunnyApocalypse** [comment]
I got a bugreport through Fedora for this issue, maybe some useful information could be found here:
https://bugzilla.redhat.com/show_bug.cgi?id=1650627
