### ISSUE TITLE
Lutris can't open configuration if prelaunch_command contains space (but not always)

### ISSUE THREAD

**Issue by monyarm** [lutris/lutris#1332]
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 805, in on_edit_game_configuration
    dialog = EditGameConfigDialog(self, game, on_dialog_saved)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config_dialogs.py", line 476, in __init__
    self.build_tabs('game')
  File "/usr/lib/python3.7/site-packages/lutris/gui/config_dialogs.py", line 40, in build_tabs
    self._build_system_tab(config_level)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config_dialogs.py", line 248, in _build_system_tab
    self.system_box = SystemBox(self.lutris_config)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config_boxes.py", line 621, in __init__
    self.generate_widgets('system')
  File "/usr/lib/python3.7/site-packages/lutris/gui/config_boxes.py", line 89, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config_boxes.py", line 178, in call_widget_generator
    self.generate_file_chooser(option, value)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config_boxes.py", line 361, in generate_file_chooser
    path = os.path.join(self.game.directory, path)
AttributeError: 'NoneType' object has no attribute 'directory'
```

The following creates this issue `python /home/monyarm/Games/movfs4l.py`
But `/home/monyarm/Games/movfs4l.py UNVFS` doesn't

**Comment by sigmaSd** [comment]
I guess the naming is bad xD prelaunch command is used to point to a script that executes before the game, you're not supposed to write the actual command there

**Comment by vityok3000** [comment]
Same problem, can't open config window. It working in su mode

**Comment by Kustovsky** [comment]
Downgrading to v0.4.21.1 solved this problem. (At least i can use lutris until 0.5)

**Comment by strycore** [comment]
I wasn't able to reproduce the issue in next

**Comment by erkexzcx** [comment]
I am using the latest version in community repositories on Arch Linux. Yep - I am unable to start Lutris now.

Anyone dare to share a workaround on starting Lutris settings?

**Comment by monyarm** [comment]
You have to edit the file where lutris saves its configs, and remove the
offending setting
