### ISSUE TITLE
Problems with Proton wine versions

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1381]
Wine configuration fails with Proton because Proton doesn't provide winecfg so Lutris fails with file not found.

```
DEBUG    2018-11-29 15:12:10,278 [thread]:Storing environment variable WINEPREFIX to /home/cxf/Games/testetst
ERROR    2018-11-29 15:12:10,281 [thread]:Failed to execute /home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/winecfg: [Errno 2] No such file or directory: '/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/winecfg': '/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/winecfg'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/thread.py", line 201, in execute_process
    cwd=self.cwd, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/winecfg': '/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/winecfg'
```

If I open Joystick Control Panel with virtual desktop enabled:

```
DEBUG    2018-11-29 15:19:41,040 [thread]:Command env: WINEARCH="win64" WINE="/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine" WINEPREFIX="/home/cxf/Games/testetst" 
DEBUG    2018-11-29 15:19:41,041 [thread]:Running command: "/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine" "control" "joy.cpl"
DEBUG    2018-11-29 15:19:41,041 [thread]:Storing environment variable WINEARCH to win64
DEBUG    2018-11-29 15:19:41,041 [thread]:Storing environment variable WINE to /home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine
DEBUG    2018-11-29 15:19:41,041 [thread]:Storing environment variable WINEPREFIX to /home/cxf/Games/testetst
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0025:err:module:load_builtin_dll failed to load .so lib for builtin L"winebus.sys": libudev.so.0: cannot open shared object file: No such file or directory
0025:err:winedevice:async_create_driver failed to create driver L"WineBus": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 31
DEBUG    2018-11-29 15:19:42,731 [thread]:Processes excluded: control (17169:S), wineserver (17172:S), control (17169:S)
DEBUG    2018-11-29 15:19:43,191 [thread]:Processes excluded: control (17169:S), wineserver (17172:S), control (17169:S)
DEBUG    2018-11-29 15:19:44,730 [thread]:Processes monitored: none
DEBUG    2018-11-29 15:19:48,731 [thread]:Thread aborting in 3 cycle
DEBUG    2018-11-29 15:19:50,730 [thread]:Thread aborting in 2 cycle
DEBUG    2018-11-29 15:19:52,732 [thread]:Thread aborting in 1 cycle
WARNING  2018-11-29 15:19:54,731 [thread]:Thread aborting now
DEBUG    2018-11-29 15:19:54,732 [thread]:Restoring environment
DEBUG    2018-11-29 15:19:54,732 [thread]:3 processes are still active
X Error of failed request:  BadWindow (invalid Window parameter)
DEBUG    2018-11-29 15:24:21,278 [thread]:Processes excluded: control (17169:Z)
DEBUG    2018-11-29 15:24:43,284 [thread]:Thread aborting in 3 cycle
DEBUG    2018-11-29 15:24:45,278 [thread]:Thread aborting in 2 cycle
DEBUG    2018-11-29 15:24:47,277 [thread]:Thread aborting in 1 cycle
WARNING  2018-11-29 15:24:49,285 [thread]:Thread aborting now
DEBUG    2018-11-29 15:24:49,285 [thread]:Restoring environment
DEBUG    2018-11-29 15:24:49,285 [thread]:1 processes are still active
```

Wine also locks up when using regedit if I enable virtual desktop:

```
INFO     2018-11-29 15:29:33,461 [wine]:Using system wine version, not using runtime
DEBUG    2018-11-29 15:29:33,508 [thread]:Command env: WINEARCH="win64" WINE="/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine" WINEPREFIX="/home/cxf/Games/testetst" 
DEBUG    2018-11-29 15:29:33,508 [thread]:Running command: "/home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine" "regedit"
DEBUG    2018-11-29 15:29:33,508 [thread]:Storing environment variable WINEARCH to win64
DEBUG    2018-11-29 15:29:33,508 [thread]:Storing environment variable WINE to /home/cxf/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine
DEBUG    2018-11-29 15:29:33,508 [thread]:Storing environment variable WINEPREFIX to /home/cxf/Games/testetst
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0027:err:module:load_builtin_dll failed to load .so lib for builtin L"winebus.sys": libudev.so.0: cannot open shared object file: No such file or directory
0027:err:winedevice:async_create_driver failed to create driver L"WineBus": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 31
DEBUG    2018-11-29 15:29:35,651 [thread]:Start process monitoring
DEBUG    2018-11-29 15:29:35,651 [thread]:Processes monitored: regedit (19776:S), regedit (19776:S), regedit.exe (19812:S)
DEBUG    2018-11-29 15:29:35,652 [thread]:Processes excluded: wineserver (19779:S)
DEBUG    2018-11-29 15:29:37,641 [thread]:Processes monitored: regedit (19776:Z)
DEBUG    2018-11-29 15:29:41,649 [thread]:Processes monitored: none
DEBUG    2018-11-29 15:29:45,645 [thread]:Thread aborting in 3 cycle
DEBUG    2018-11-29 15:29:47,646 [thread]:Thread aborting in 2 cycle
DEBUG    2018-11-29 15:29:49,645 [thread]:Thread aborting in 1 cycle
WARNING  2018-11-29 15:29:51,646 [thread]:Thread aborting now
DEBUG    2018-11-29 15:29:51,646 [thread]:Detaching logger
DEBUG    2018-11-29 15:29:51,647 [thread]:Restoring environment
DEBUG    2018-11-29 15:29:51,647 [thread]:1 processes are still active
```
![screenshot from 2018-11-29 15-30-05](https://user-images.githubusercontent.com/15083452/49258859-cc954980-f3eb-11e8-8e03-33bd396ff6ad.png)

The last two are only a problem with Proton 3.7/3.7 Beta. With 3.16 it's able to use a virtual desktop. Both these issues aren't really a Lutris problem but something it should disable when using Proton 3.7 I think.

**Comment by strycore** [comment]
I was also able to reproduce the problem with the wine desktop + joycpl / regedit but as you say it's a problem with Proton itself.
