### ISSUE TITLE
installerwindow.py KeyError: 'filename'

### ISSUE THREAD

**Issue by swratten** [lutris/lutris#1388]
Trying to install quake champions with steam play option.
lutris-0.4.23
Installed via AUR with Wine and Wine staging options.
OS: Manjaro 18.0.0 Illyria
Kernel: x86_64 Linux 4.19.4-1-MANJARO
Intel Core i5-6500
AMD Radeon HD 7800 Series (PITCAIRN, DRM 3.27.0, 4.19.4-1-MANJARO, LLVM 7.0.0)

```
lutris lutris:quake-champions-steam-play
ERROR    2018-12-03 15:40:12,526 [system]:Couldn't find a terminal emulator.
INFO     2018-12-03 15:40:14,415 [lutriswindow]:Connected to lutris.net
INFO     2018-12-03 15:40:14,587 [lutriswindow]:Installing quake-champions-steam-play
INFO     2018-12-03 15:40:15,634 [lutriswindow]:Setting up view for first run
INFO     2018-12-03 15:40:18,410 [interpreter]:Downloading file 1 of 2
INFO     2018-12-03 15:40:20,430 [interpreter]:Downloading file 2 of 2
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/installerwindow.py", line 401, in on_download_complete
    self.interpreter.iter_game_files()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 294, in iter_game_files
    self._download_file(current_file)
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 312, in _download_file
    filename = game_file[file_id]['filename']
KeyError: 'filename'
```

**Comment by strycore** [comment]
This is fixed in the current release, please upgrade.
