### ISSUE TITLE
No error when downloading runner and not enough free space

### ISSUE THREAD

**Issue by zorael** [lutris/lutris#1393]
Manjaro/Arch x86_64, lutris 0.4.23-1 from community.

If you start downloading a runner to a drive with no space left, the progress bar will silently stop and do nothing until you abort the installation. Only terminal output gives the "disk full" Python backtrace; there is no graphical error message.

How to reproduce:
1. Fill home drive (or wherever ~/.local/share/lutris/runners points)
2. Start installation of a game (tested [Magic the Gathering Arena](https://lutris.net/games/magic-the-gathering-arena))
3. Click Continue in the dialogue window asking which version to install

Expected behaviour:
4a. Progress bar appears and rolls until disk runs out, then stops and 5.
4b. Program knows the size of the runner and can tell that there is not enough room, and so never starts downloading
5. Error message claiming the disk is full

Actual behaviour:
4. Progress bar appears and starts, but stops without word when space runs out
5. The following is invisibly output to the terminal:
```
INFO     2018-12-05 03:50:17,860 [lutriswindow]:Setting up view for first run
INFO     2018-12-05 03:50:53,375 [lutriswindow]:Installing magic-the-gathering-arena-latest
INFO     2018-12-05 03:51:06,437 [lutriswindow]:Installing magic-the-gathering-arena-latest
INFO     2018-12-05 03:51:12,404 [runner]:Getting runner information for wine(version: tkg-mtga-3.21-x86_64)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/widgets/download_progress.py", line 85, in _progress
    progress = min(self.downloader.check_progress(), 1)
  File "/usr/lib/python3.7/site-packages/lutris/util/downloader.py", line 67, in check_progress
    downloaded_size, full_size = self.write_queue()
  File "/usr/lib/python3.7/site-packages/lutris/util/downloader.py", line 122, in write_queue
    self.file_pointer.write(buffered_chunk)
OSError: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/util/jobs.py", line 38, in <lambda>
    GLib.idle_add(lambda: self.callback(result, error))
  File "/usr/lib/python3.7/site-packages/lutris/util/downloader.py", line 94, in on_done
    self.check_progress()
  File "/usr/lib/python3.7/site-packages/lutris/util/downloader.py", line 67, in check_progress
    downloaded_size, full_size = self.write_queue()
  File "/usr/lib/python3.7/site-packages/lutris/util/downloader.py", line 122, in write_queue
    self.file_pointer.write(buffered_chunk)
OSError: [Errno 28] No space left on device
```

**Comment by strycore** [comment]
Also handled the error on runner extraction.
