### ISSUE TITLE
Lutris script attempts to extract archive before completing download.

### ISSUE THREAD

**Issue by BarneyGumball** [lutris/lutris#1414]
When trying to install Path of Exile via this script: https://lutris.net/games/install/6653/view the client stops downloading part way through the first file.

I'm on Ubuntu 18.04 and `lutris -d` shows the following output after selecting the installation directory:

```
DEBUG    2018-12-15 21:48:54,984 [commands]:Install script uses Wine tkg-3.19-x86_64
DEBUG    2018-12-15 21:48:54,989 [interpreter]:Installing wine
DEBUG    2018-12-15 21:48:54,989 [commands]:Install script uses Wine tkg-3.19-x86_64
DEBUG    2018-12-15 21:48:54,989 [runner]:Installing wine (version=tkg-3.19-x86_64, downloader=<bound method InstallerWindow.start_download of <installerwindow.InstallerWindow object at 0x7f7ac7a0d120 (lutris+gui+installerwindow+InstallerWindow at 0x15099c0)>>, callback=<bound method ScriptInterpreter.install_runners of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f7ad3508908>>)
INFO     2018-12-15 21:48:54,989 [runner]:Getting runner information for wine(version: tkg-3.19-x86_64)
DEBUG    2018-12-15 21:48:54,990 [http]:GET https://lutris.net/api/runners/wine
DEBUG    2018-12-15 21:48:57,762 [runner]:Got 171 versions
DEBUG    2018-12-15 21:48:57,765 [installerwindow]:Downloading https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-tkg-3.19-x86_64.tar.gz to /home/scott/.cache/lutris/wine-tkg-3.19-x86_64.tar.gz
DEBUG    2018-12-15 21:48:57,768 [downloader]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-tkg-3.19-x86_64.tar.gz
DEBUG    2018-12-15 21:48:57,769 [http]:GET https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-tkg-3.19-x86_64.tar.gz
DEBUG    2018-12-15 22:02:16,213 [downloader]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-tkg-3.19-x86_64.tar.gz
DEBUG    2018-12-15 22:02:16,224 [extract]:Extracting /home/scott/.cache/lutris/wine-tkg-3.19-x86_64.tar.gz to /home/scott/.local/share/lutris/runners/wine/tkg-3.19-x86_64
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 347, in on_downloaded
    self.extract(**user_data)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 354, in extract
    extract_archive(archive, dest, merge_single=merge_single)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 55, in extract_archive
    _do_extract(path, temp_path, opener, mode, extractor)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 93, in _do_extract
    handler.extractall(dest)
  File "/usr/lib/python3.6/tarfile.py", line 2010, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2052, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2122, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.6/tarfile.py", line 2171, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.6/tarfile.py", line 249, in copyfileobj
    buf = src.read(bufsize)
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

![](http://i.imgur.com/uwalGMB.png)

It always seems to stop between 30-40mb downloaded.  Not sure if it's relevant, but I can't seem to get above 2MB/s for the download, likely due to living in Australia.

**Comment by BarneyGumball** [comment]
Oh and the output after I clicked cancel and proceeded to close Lutris:

```
DEBUG    2018-12-15 22:38:34,260 [interpreter]:Install cancelled
DEBUG    2018-12-15 22:38:34,261 [downloader]:Download of https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-tkg-3.19-x86_64.tar.gz cancelled
WARNING  2018-12-15 22:38:34,262 [system]:Non existent path: /home/scott/.cache/lutris/installer/path-of-exile
INFO     2018-12-15 22:38:52,331 [application]:Shutting down Lutris
DEBUG    2018-12-15 22:38:52,373 [downloader]:Download of https://lutris.nyc3.digitaloceanspaces.com/runtime/x360ce.tar.gz cancelled
DEBUG    2018-12-15 22:38:52,373 [downloader]:Download of https://lutris.nyc3.digitaloceanspaces.com/runtime/dumbxinputemu-0.3.3.tar.gz cancelled
INFO     2018-12-15 22:38:52,377 [application]:Shutting down Lutris
```

**Comment by BarneyGumball** [comment]
Woke up this morning and restarted my computer.  It works now.  Guess there was some issue between me and the server hosting the file.
