### ISSUE TITLE
[0.5.beta] TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1536]
Got this today when trying to add a game:

```
Traceback (most recent call last):
  File "/src/lutris/lutris/gui/widgets/common.py", line 92, in on_browse_clicked
    default_folder = self.get_default_folder(default_path)
  File "/src/lutris/lutris/gui/widgets/common.py", line 89, in get_default_folder
    return os.path.expanduser(default)
  File "/usr/lib/python3.6/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by romulasry** [comment]
I have this same error when I try Installing Battlerite DXVK version:

2019-02-26 14:56:34,218: Data path for SteamApp 504370 not found.
2019-02-26 14:56:34,233: Error while completing task <bound method winesteam.install_game of Winesteam runner (LutrisConfig(level=runner, game_config_id=None, runner=winesteam))>: expected str, bytes or os.PathLike object, not NoneType
<class 'TypeError'> expected str, bytes or os.PathLike object, not NoneType
  File "/usr/lib/python3.7/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/runners/winesteam.py", line 381, in install_game
    subprocess.Popen(command, env=self.get_env())
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
2019-02-26 14:56:34,234: expected str, bytes or os.PathLike object, not NoneType
None
