### ISSUE TITLE
OpenSUSE Tumbleweed: ValueError: Namespace Gdk not available for version 3.0

### ISSUE THREAD

**Issue by zilti** [lutris/lutris#1555]
Installed from the opensuse repositories. Error:

```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 27, in <module>
    gi.require_version('Gdk', '3.0')  # NOQA # isort:skip
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace Gdk not available for version 3.0
```

Reason: the spec file for the RPM is missing typelib-1_0-Gtk-3_0.

**Comment by strycore** [comment]
yes, that's been added to the current spec file and will be present in the next release.
