### ISSUE TITLE
Can't run external EXE with some games

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1569]
Only happens if I "Run EXE' inside Overwatch prefix. If I try to do it, nothing happens and I just get a traceback and a weird wine "cannot find" error:
```
./bin/lutris -d
2019-01-12 10:54:38,975: Running Lutris 0.5.0-beta
2019-01-12 10:54:38,976: Using NVIDIA drivers 415.25 for x86_64
2019-01-12 10:54:38,976: GPU: GeForce GTX 1070
2019-01-12 10:54:38,976: GPU: 10DE:1B81 1458:3772 using nvidia driver
2019-01-12 10:54:38,995: Vulkan is supported
2019-01-12 10:54:38,995: Updating DXVK versions
INFO     2019-01-12 10:54:39,750 [lutriswindow.toggle_connection:562]:Connected to lutris.net as citrusalex
DEBUG    2019-01-12 10:54:39,751 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2019-01-12 10:54:39,756 [api.get_library:54]:Fetching game library
DEBUG    2019-01-12 10:54:39,756 [http.get:65]:GET https://lutris.net/api/games/library/citrusalex
DEBUG    2019-01-12 10:54:49,746 [prefix.set_virtual_desktop:121]:Virtual desktop: None
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/system32/dxgi with DXVK version
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/system32/d3d11 with DXVK version
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/system32/d3d10core with DXVK version
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/system32/d3d10_1 with DXVK version
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/system32/d3d10 with DXVK version
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/syswow64/dxgi with DXVK version
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/syswow64/d3d11 with DXVK version
INFO     2019-01-12 10:54:49,769 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/syswow64/d3d10core with DXVK version
INFO     2019-01-12 10:54:49,770 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/syswow64/d3d10_1 with DXVK version
INFO     2019-01-12 10:54:49,770 [dxvk.enable_dxvk_dll:123]:Replacing /home/alex/Games/overwatch/drive_c/windows/syswow64/d3d10 with DXVK version
DEBUG    2019-01-12 10:54:49,770 [wine.use_lutris_runtime:104]:/home/alex/.local/share/lutris/runners/wine/tkg-3.21-x86_64/bin/wine is provided by Lutris, using runtime
DEBUG    2019-01-12 10:54:49,770 [command.start:110]:Running /home/alex/lutris/bin/lutris-wrapper 0 0 /home/alex/.local/share/lutris/runners/wine/tkg-3.21-x86_64/bin/wine /home/alex/Downloads/DebugView (1)/Dbgview.exe
DEBUG    2019-01-12 10:54:49,770 [command.start:112]:ENV: WINEARCH="win64"
DEBUG    2019-01-12 10:54:49,770 [command.start:112]:ENV: WINE="/home/alex/.local/share/lutris/runners/wine/tkg-3.21-x86_64/bin/wine"
DEBUG    2019-01-12 10:54:49,770 [command.start:112]:ENV: WINEPREFIX="/home/alex/Games/overwatch"
DEBUG    2019-01-12 10:54:49,770 [command.start:112]:ENV: LD_LIBRARY_PATH="/home/alex/.local/share/lutris/runners/wine/tkg-3.21-x86_64/lib:/home/alex/.local/share/lutris/runners/wine/tkg-3.21-x86_64/lib64:/lib:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/home/alex/.local/share/lutris/runtime/lib32:/home/alex/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/alex/.local/share/lutris/runtime/steam/i386/lib:/home/alex/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/alex/.local/share/lutris/runtime/steam/i386/usr/lib:/home/alex/.local/share/lutris/runtime/lib64:/home/alex/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/alex/.local/share/lutris/runtime/steam/amd64/lib:/home/alex/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/alex/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2019-01-12 10:54:49,770 [command.start:112]:ENV: PYTHONPATH="/home/alex/lutris:/home/alex/lutris/bin:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/lib/python3.7/site-packages"
DEBUG    2019-01-12 10:54:49,773 [signals.register_handler:27]:Registering <bound method MonitoredCommand.on_stop of <lutris.command.MonitoredCommand object at 0x7f3a88209a20>> to 29556
wine: cannot find '/home/alex/Downloads/DebugView (1)/Dbgview.exe'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gi/overrides/GLib.py", line 669, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/home/alex/lutris/lutris/command.py", line 178, in on_stdout_output
    log_handler(line)
  File "/home/alex/lutris/lutris/command.py", line 142, in log_handler_buffer
    self.log_buffer.insert(self.log_buffer.get_end_iter(), line, -1)
AttributeError: 'NoneType' object has no attribute 'insert'
DEBUG    2019-01-12 10:54:52,898 [command.on_stop:152]:The process has terminated with code 512
DEBUG    2019-01-12 10:54:52,898 [command.stop:253]:Management process looks dead already.
DEBUG    2019-01-12 10:54:52,898 [command.stop:261]:Detaching logger
/home/alex/lutris/lutris/command.py:262: Warning: Source ID 2536 was not found when attempting to remove it
  GLib.source_remove(self.stdout_monitor)
DEBUG    2019-01-12 10:54:52,898 [command.restore_environment:231]:Restoring environment
```
Might just be a borked configuration, but worth looking into.

**Comment by tannisroot** [comment]
Nvm, Z drive was just missing.
