### ISSUE TITLE
Can't activate Esync

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1624]
Traceback:
```
ERROR    2019-01-18 02:08:41,267 [jobs.target:32]:Error while completing task <function wine.__init__.<locals>.esync_limit_callback at 0x7f1d90b288c8>: local variable 'response' referenced before assignment
<class 'UnboundLocalError'> local variable 'response' referenced before assignment
  File "/home/alex/lutris/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/home/alex/lutris/lutris/runners/wine.py", line 173, in esync_limit_callback
    return widget, option, response
Traceback (most recent call last):
  File "/home/alex/lutris/lutris/gui/config_boxes.py", line 257, in _on_callback_finished
    widget, option, response = result
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by strycore** [comment]
this is now fixed
