### ISSUE TITLE
Esync toggle complains about incorrect limits even with systemd 240 and ulimits -Hn -> 524288

### ISSUE THREAD

**Issue by Nocifer** [lutris/lutris#1638]
OS: Arch Linux
Lutris version: 0.4.23

As title says. Hard limit is high enough by default due to systemd 240, but when I try to toggle Esync in the settings, Lutris says "Your limits are not set correctly. Please increase them as described here:" etc.

**Comment by Nocifer** [comment]
Glad to hear that :)

**Comment by Mar2ck** [comment]
I still have this issue on 0.5.0
[Imgur](https://i.imgur.com/XgPEOsQ.png)
I don't know if this is because my systemd version is below 240. I tried using the old, larger limit and i still get the error
[Imgur](https://i.imgur.com/yh7Nd3C.png)
I rebooted my pc both times

**Comment by robaxelsen** [comment]
> I still have this issue on 0.5.0
> [Imgur](https://i.imgur.com/XgPEOsQ.png)
> I don't know if this is because my systemd version is below 240. I tried using the old, larger limit and i still get the error
> [Imgur](https://i.imgur.com/yh7Nd3C.png)
> I rebooted my pc both times

Same issue here, even with value double the minimum.
```
rob at code in ~
$ ulimit -Hn
1048576
```

**Comment by strycore** [comment]
This issue doesn't have the necessary information to get it resolved. Please complete the bug report.

**Comment by robaxelsen** [comment]
> This issue doesn't have the necessary information to get it resolved. Please complete the bug report.

@strycore thanks for giving us feedback. Wanted to give more bug report information, but not sure what specifically is needed. Could you please clarify what is missing?

Couldn't find any guidelines when pressing "New Issue", except for a link to CONTRIBUTING.md which does not list what is expected in bug reports.

**Comment by strycore** [comment]
No reproduction steps.

**Comment by robaxelsen** [comment]
Steps to reproduce:
1. Install Lutris 0.5.2 on Ubuntu MATE 18.04.2
1. Install World Of Warcraft via [xdg-open open url from Lutris website](https://lutris.net/games/world-of-warcraft/)
1. Run World of Warcraft successfully upon install
1. Reboot
1. Run World of Warcraft again via Lutris, and  message appears"Your limits are not set correctly. Please increase them as described here: [...]", even though ulimit -Hn shows it's already set

As for further troubleshooting findings, I noticed that "esync" was set as option in the game settings, but in "Wine version management" I saw no esync packages checked. Checking esync-staging-pba-xxx for install, installing and rebooting.. did not help, however.

Disabling esync in game settings lets me run the game without esync, though.

**Comment by alindt** [comment]
I have the same problem with Lutris 0.5.2 on Linux Mint 19.1 (64bit) installed from Lutris PPA.

```
$ ulimit -Hn
524288

$ grep NOFILE /etc/systemd/{user,system}.conf
/etc/systemd/user.conf:DefaultLimitNOFILE=524288
/etc/systemd/system.conf:DefaultLimitNOFILE=524288

$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
>>> import resource
>>> resource.getrlimit(resource.RLIMIT_NOFILE)
(524288, 524288)
```
=====

Steps to reproduce:

1. Launch Lutris
2. [Add game] from menu
3. [Game info] => [Runner] => "Wine"
4. [Runner options] => [Enable Esync] => "ON"

![image](https://user-images.githubusercontent.com/1379385/58157731-9e4d4400-7c81-11e9-8283-4faecb87fcbb.png)

**Comment by boondoggle** [comment]
Also having this same problem with limits set correctly.

**Comment by ehashman** [comment]
Can confirm this also affects me on Linux Mint MATE 19 (based on Ubuntu 18.04). Running lutris version 0.5.2.2. `ulimit -Hn` is 1048576.

I can also confirm that when lutris is launched from a terminal (as opposed to the app menu), I no longer run into the problem.

**Comment by Riesi** [comment]
Have you tried to do the same as alindt? He had to edit `/etc/security/limits.conf` to fix his issue when running Lutris from outside the terminal.

https://github.com/lutris/lutris/wiki/How-to:-Esync

**Comment by Enkouyami** [comment]
Following alindt's steps didn't fix the issue for me on LM 19.

**Comment by databoose** [comment]
I seem to have gotten this issue when uninstalling my system wine, which is a problem as i use a self compiled version of wine that otherwise does not work when a wine package is installed.

The limit is fine, it's at 524288 according to the ulimit command, just for some reason lutris doesn't believe it is when i happen to have the wine packages uninstalled (even though otherwise proton/lutris-wine run completely fine without being installed packages)

**Comment by sebastianulm** [comment]
Same issue. Manjaro (basically arch)
Here is a stacktrace. Hope that helps.
```
Exception ignored in: <function InputDevice.__del__ at 0x7f8160058040>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3.8/site-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-10'.
Exception ignored in: <function InputDevice.__del__ at 0x7f8160058040>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3.8/site-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-10'.
```
