### ISSUE TITLE
TypeError: 'Game' object is not subscriptable error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1640]
trying to Add a game to lutris this morning, and it "failed" with this on the terminal:

```
Traceback (most recent call last):
  File "/src/lutris/lutris/gui/config/common.py", line 411, in on_save
    callback()
  File "/src/lutris/lutris/game_actions.py", line 205, in <lambda>
    callback=lambda: on_game_added(self.game),
  File "/src/lutris/lutris/game_actions.py", line 198, in on_game_added
    self.window.game_store.update(game)
  File "/src/lutris/lutris/gui/views/store.py", line 227, in update
    row = self.get_row_by_id(game.id)
  File "/src/lutris/lutris/gui/views/pga_game.py", line 31, in id
    return self._pga_data["id"]

```

It does save the game but the banner is left as if it's not installed, until I selected another game and selected again

How to Reproduce:
Add a game to library from website (IE https://lutris.net/games/bishojo-senshi-sailor-moon-s/) then start Lutris, go to game entry, add game via "add installed game" and it produce this error

**Comment by tannisroot** [comment]
I can't reproduce this with latest master, even with the game you linked.
