### ISSUE TITLE
[master] AttributeError: 'int' object has no attribute 'id', when clicking on launch game after installation has finished

### ISSUE THREAD

**Issue by Medath** [lutris/lutris#1641]
**Steps to reproduce:** Install a game. Click on "Launch Game" in the window that pops up after installation has finished.
**Expected Behaviour:** Game launches
**Observed Behaviour:** Game does not launch. Traceback gets printed. User is unable launch any other game afterwards. Selecting any game causes the same traceback to be printed again and the right sidebar stays entirely empty. Lutris needs to be restarted in order to function properly again.
```
Traceback (most recent call last):
  File "/home/username/Desktop/git-projects/lutris/real/lutris/gui/lutriswindow.py", line 606, in game_selection_changed
    self.game_panel = GamePanel(self.game_actions)
  File "/home/username/Desktop/git-projects/lutris/real/lutris/gui/views/game_panel.py", line 14, in __init__
    self.game = game_actions.game
  File "/home/username/Desktop/git-projects/lutris/real/lutris/game_actions.py", line 30, in game
    self._game = self.application.get_game_by_id(self.game_id)
  File "/home/username/Desktop/git-projects/lutris/real/lutris/gui/application.py", line 346, in get_game_by_id
    if game.id == game_id:
AttributeError: 'int' object has no attribute 'id'
```

**Comment by strycore** [comment]
Fixed in current master
