### ISSUE TITLE
[AttributeError] 'NoneType' object has no attribute 'iter'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1647]
Found this little bug this morning:

```
Traceback (most recent call last):
  File "/home/batapete/src/lutris/lutris/gui/config/common.py", line 444, in on_save
    callback()
  File "/home/batapete/src/lutris/lutris/game_actions.py", line 213, in on_dialog_saved
    self.window.game_store.remove_game(game_id)
  File "/home/batapete/src/lutris/lutris/gui/views/store.py", line 218, in remove_game
    self.store.remove(row.iter)
AttributeError: 'NoneType' object has no attribute 'iter'
```

When changing a game from one runner to another I get this, and it refuses to change, IE from Libretro to ppsspp, but doesn't happen when you add a new game

**Comment by telanus** [comment]
Found that when you restart Lutris, it created a few (depending on how many times you tested the bug) copies of the game

**Comment by strycore** [comment]
Please re-open if you still experience the issue but I think the latest commits solve this.
