### ISSUE TITLE
Xrandr output parsing failure

### ISSUE THREAD

**Issue by daniel-j** [lutris/lutris#165]
I installed lutris using the .deb file in Ubuntu Software Center. Running lutris from terminal:
```
ubuntu-gnome@ubuntu-gnome:~$ lutris 
Traceback (most recent call last):
  File "/usr/bin/lutris", line 48, in <module>
    from lutris.installer import InstallerDialog
  File "/usr/lib/pymodules/python2.7/lutris/installer.py", line 24, in <module>
    from lutris.gui.config_dialogs import AddGameDialog
  File "/usr/lib/pymodules/python2.7/lutris/gui/config_dialogs.py", line 11, in <module>
    from lutris.gui.config_boxes import GameBox,  RunnerBox, SystemBox
  File "/usr/lib/pymodules/python2.7/lutris/gui/config_boxes.py", line 7, in <module>
    from lutris import sysoptions
  File "/usr/lib/pymodules/python2.7/lutris/sysoptions.py", line 16, in <module>
    outputs = display.get_output_names()
  File "/usr/lib/pymodules/python2.7/lutris/util/display.py", line 29, in get_output_names
    return [output[0] for output in get_outputs()]
  File "/usr/lib/pymodules/python2.7/lutris/util/display.py", line 21, in get_outputs
    geom = parts[2] if parts[2] != 'primary' else parts[3]
IndexError: list index out of range
```

I'm using an external monitor (VGA1). DP1, VIRTUAL1 and VGA-1-2 aren't physcial connectors. xrandr output:
```
ubuntu-gnome@ubuntu-gnome:~$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
LVDS1 connected (normal left inverted right x axis y axis)
   1366x768       60.0 +
   1360x768       59.8     60.0  
   1024x768       60.0  
   800x600        60.3     56.2  
   640x480        59.9  
VGA1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080      60.0*+
   1680x1050      60.0  
   1600x900       60.0  
   1280x1024      75.0     60.0  
   1440x900       59.9  
   1280x800       59.8  
   1152x864       75.0  
   1280x720       60.0  
   1024x768       75.1     70.1     60.0  
   832x624        74.6  
   800x600        72.2     75.0     60.3     56.2  
   640x480        75.0     72.8     66.7     60.0  
   720x400        70.1  
HDMI1 disconnected (normal left inverted right x axis y axis)
DP1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
VGA-1-2 connected
   1024x768       60.0  
   800x600        60.3     56.2  
   848x480        60.0  
   640x480        59.9  
  1024x768 (0x43)   65.0MHz
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock   48.4KHz
        v: height  768 start  771 end  777 total  806           clock   60.0Hz
  800x600 (0x44)   40.0MHz
        h: width   800 start  840 end  968 total 1056 skew    0 clock   37.9KHz
        v: height  600 start  601 end  605 total  628           clock   60.3Hz
  800x600 (0x45)   36.0MHz
        h: width   800 start  824 end  896 total 1024 skew    0 clock   35.2KHz
        v: height  600 start  601 end  603 total  625           clock   56.2Hz
```

Hardware: Acer Aspire TimelineX 3830TG
Graphics driver running: nouveau
GPU: Nvidia GeForce GT540M
CPU: Intel® Core™ i5-2410M CPU @ 2.30GHz × 4 (64-bit, Sandy Bridge)

**Comment by Xodetaetl** [comment]
Thanks for providing the xrandr output before I asked. ^^
