### ISSUE TITLE
TypeError: 'ListStore' object is not iterable

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1664]
Got this when trying to select a game:

```
Traceback (most recent call last):
  File "/src/lutris/lutris/gui/lutriswindow.py", line 626, in game_selection_changed
    self.game_panel = GamePanel(self.game_actions)
  File "/src/lutris/lutris/gui/views/game_panel.py", line 15, in __init__
    self.game = game_actions.game
  File "/src/lutris/lutris/game_actions.py", line 30, in game
    self._game = self.application.get_game_by_id(self.game_id)
  File "/src/lutris/lutris/gui/application.py", line 345, in get_game_by_id
    for game in self.running_games:
TypeError: 'ListStore' object is not iterable
```

Also the game pane no longer allow to run a game

**Comment by fuulish** [comment]
Second that. It  It also appears in a couple other functions

lutris/gui/application.py:

`get_game_by_id` (the one @telanus reported)
`on_game_stop` (starting line 349)

lutris/game_actions.py:

`on_stop` (starting line 159)

The ListStore object does privde an get_item function which could be used to iterate over the ListStore:

```
def on_stop(self, caller):
    """Stops the game"""
    matched_game = None
    i = 0
    game = self.application.running_games.get_item(i)
    while game is not None:
        if game == self.game:
            matched_game = game
            break
        i += 1
        matched_game = self.application.running_games.get_item(i)
```

That's not very pythonic, though.
Alternatively one could try to create a derived class with a generator.

**Comment by strycore** [comment]
fixed
