### ISSUE TITLE
Invalid playtime value 0.0 hrs

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1665]
I think this happened because I added this game using 0.4.23 since adding a game manually with master is fucked.

```
ERROR    2019-01-24 23:53:13,118 [game.__init__:69]:Invalid playtime value 0.0 hrs
Traceback (most recent call last):
  File "/home/cxf/.lutris/lutris/gui/lutriswindow.py", line 626, in game_selection_changed
    self.game_panel = GamePanel(self.game_actions)
  File "/home/cxf/.lutris/lutris/gui/views/game_panel.py", line 16, in __init__
    super().__init__()
  File "/home/cxf/.lutris/lutris/gui/views/generic_panel.py", line 13, in __init__
    self.place_content()
  File "/home/cxf/.lutris/lutris/gui/views/game_panel.py", line 27, in place_content
    if self.game.playtime:
AttributeError: 'Game' object has no attribute 'playtime'
ERROR    2019-01-24 23:53:13,229 [game.__init__:69]:Invalid playtime value 0.0 hrs
```
```
Traceback (most recent call last):
  File "/home/cxf/.lutris/lutris/gui/config/common.py", line 432, in on_save
    self.game.save()
  File "/home/cxf/.lutris/lutris/game.py", line 212, in save
    playtime=self.playtime,
AttributeError: 'Game' object has no attribute 'playtime'
```

**Comment by strycore** [comment]
go to the lutris.conf file and downgrade the migration number so it runs the playtime fix migration again.

**Comment by AccountOneOff** [comment]
I tried that but it doesn't work. I also renamed the file, relaunched, and the game panel still doesn't show.

**Comment by Medath** [comment]
I changed `migration_version` from 5 to 4 in `~/.config/lutris/lutris.conf` and it worked fine. Are you sure there was no typo or something @AccountOneOff?
