### ISSUE TITLE
Print (better) error if no IRC client is available

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1689]
I use Fractal IRC client from Flathub:
```
Traceback (most recent call last):
  File "/home/alex/lutris/lutris/gui/views/generic_panel.py", line 193, in <lambda>
    irc_button.connect("clicked", lambda *x: open_uri(LINKS["irc"]))
  File "/home/alex/lutris/lutris/gui/widgets/utils.py", line 41, in open_uri
    Gtk.show_uri(None, uri, Gdk.CURRENT_TIME)
gi.repository.GLib.Error: g-io-error-quark: The specified location is not supported (15)
```

**Comment by TingPing** [comment]
Fractal isn't an IRC client. You need an IRC client for it to work.

It should probably print a better error though.
