### ISSUE TITLE
Lutris 0.50 updated and won't launch anymore

### ISSUE THREAD

**Issue by nicobustillos** [lutris/lutris#1695]
Kubuntu 18.04 has just prompted me to update to Lutris 0.50 and it won't launch anymore. For more details I have tried to launch it via command and get the following error:

>...:~$ lutris
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
(lutris:19353): Gtk-WARNING **: 21:00:08.002: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(lutris:19353): Gtk-WARNING **: 21:00:08.002: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(lutris:19353): Gtk-WARNING **: 21:00:08.002: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
2019-02-01 21:00:08,021: Running Lutris 0.5.0
2019-02-01 21:00:08,022: Using NVIDIA drivers 415.27 for x86_64
2019-02-01 21:00:08,023: GPU: GeForce GTX 960M
2019-02-01 21:00:08,023: GPU: 10DE:139B 103C:8257 using nvidia drivers
2019-02-01 21:00:08,023: GPU: 8086:191B 103C:8257 using i915 drivers
2019-02-01 21:00:08,042: Vulkan is supported
2019-02-01 21:00:08,043: Invalid playtime value 0.5 hrs
2019-02-01 21:00:08,045: Providing missing platorm for game mario-kart-double-dash
2019-02-01 21:00:08,045: Can't get platform for runner Dolphin
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 223, in do_command_line
    run_all_checks()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 109, in run_all_checks
    fill_missing_platforms()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 100, in fill_missing_platforms
    game.save(metadata_only=True)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 216, in save
    playtime=self.playtime,
AttributeError: 'Game' object has no attribute 'playtime'
2019-02-01 21:00:08,074: Shutting down Lutris

Any hint as to what may have changed in this version?

**Comment by PythonicChemist** [comment]
```AttributeError: 'Game' object has no attribute 'playtime'```

This error should be fixed by #1693.

**Comment by strycore** [comment]
duplicate
