### ISSUE TITLE
Can't open the Runners configuration after updating to 0.5.0 on Linux Mint 18.3

### ISSUE THREAD

**Issue by Agetian** [lutris/lutris#1697]
Clicking any Runners-related button on Linux Mint 18.3 after updating Lutris to 0.5.0 does nothing (tried the Manage Runners button and the little gear button next to the Runners tab). Tried starting Lutris from the terminal to see if any error pops up, but I don't get anything there at all.

Might be related to #858, but I'm not sure (I think Mint 18.3 is using the Ubuntu 16.04 base?), it's a supported system until 2021 and I'd rather keep it for the time being, since I'm the "don't fix it unless it's broken" kind of guy...

**Comment by Agetian** [comment]
Ok, it's definitely a duplicate of #858, I tried "lutris -d" and got the same error message:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 601, in on_manage_runners
    return RunnersDialog(transient_for=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/__init__.py", line 32, in __init__
    self.builder.add_from_file(ui_filename)
GLib.Error: gtk-builder-error-quark: /usr/share/lutris/ui/runners-dialog.ui:5:1 Required gtk+ version 3.20, current version is 3.18 (7)

In case 0.5.0 won't be supported on the 16.04 base, I'd rather downgrade to 0.4.x which was working perfectly, to be honest (but 0.5.0 is already in the 16.04 repositories, unfortunately).

**Comment by Agetian** [comment]
For the record, changing the gtk+ requirement line from 3.20 to 3.18 in all runner-related .ui files seems to do the trick, the windows start to open and so far I haven't noticed any issues after switching the requirement to 3.18. Seems to work alright.
