### ISSUE TITLE
Traceback on game launch if envar has "=" at the end

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1699]
If somebody makes a mistake a put en envar with `=` at the end (for example `DXVK_HUD=`) the game will be stuck on "Launching" with this traceback getting printed: 
```Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 489, in configure_game
    self.start_game()
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 503, in start_game
    self.game_thread.start()
  File "/usr/lib/python3.7/site-packages/lutris/command.py", line 120, in start
    env = self.apply_environment()
  File "/usr/lib/python3.7/site-packages/lutris/command.py", line 99, in apply_environment
    os.environ[key] = str(value)
  File "/usr/lib/python3.7/os.py", line 684, in __setitem__
    self.putenv(key, value)
ValueError: illegal environment variable name
```

**Comment by tannisroot** [comment]
Yeah so I am not sure if it regressed or the fix never worked but it's still an issue.

**Comment by strycore** [comment]
yeah, the previous fix was deleted
