### ISSUE TITLE
Lutris crashes on launch after 0.5.0 update (glxinfo)

### ISSUE THREAD

**Issue by rsaltrelli** [lutris/lutris#1706]
After updating to 0.5.0 today, Lutris won't run anymore.

```
$ lutris
2019-02-02 21:46:38,710: Running Lutris 0.5.0
2019-02-02 21:46:38,711: glxinfo is not available on your system, unable to detect driver version
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 223, in do_command_line
    run_all_checks()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 106, in run_all_checks
    check_driver()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 63, in check_driver
    **drivers.get_gpu_info(card)
KeyError: 'PCI_ID'
2019-02-02 21:46:38,753: Shutting down Lutris
```

```
$ glxinfo
bash: /usr/bin/glxinfo: No such file or directory
```

Found [this](https://dri.freedesktop.org/wiki/glxinfo/).  Installed mesa-utils.

```
$ glxinfo | grep render
direct rendering: Yes
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, GLX_MESA_query_renderer, 
Extended renderer info (GLX_MESA_query_renderer):
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
    GL_ARB_conditional_render_inverted, GL_ARB_conservative_depth, 
    GL_NV_conditional_render, GL_NV_depth_clamp, GL_NV_packed_depth_stencil, 
    GL_ARB_compute_shader, GL_ARB_conditional_render_inverted, 
    GL_MESA_window_pos, GL_NV_blend_square, GL_NV_conditional_render, 
    GL_OES_element_index_uint, GL_OES_fbo_render_mipmap, 
```

Tried Lutris again.

```
$ lutris
2019-02-02 21:49:50,419: Running Lutris 0.5.0
2019-02-02 21:49:50,420: Using Intel Open Source Technology Center
2019-02-02 21:49:50,420: Running Mesa driver 18.2.2 on Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  (0x5916)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 223, in do_command_line
    run_all_checks()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 106, in run_all_checks
    check_driver()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 63, in check_driver
    **drivers.get_gpu_info(card)
KeyError: 'PCI_ID'
2019-02-02 21:49:50,462: Shutting down Lutris
```

Don't know where to go from here.

**Comment by rsaltrelli** [comment]
Works now.  Thank you!
