### ISSUE TITLE
Lutris crash on Launch. Arch.KDE.

### ISSUE THREAD

**Issue by Pantar2205** [lutris/lutris#1707]
```
ger at ger-desktop in ~
$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 30, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available
```

**Comment by beardyjay** [comment]
See #1505 

You need to install gnome-desktop as its now a dependency
