### ISSUE TITLE
Litris does not start after installing the update 0.5

### ISSUE THREAD

**Issue by Degekai** [lutris/lutris#1709]
Litris does not start after installing the update 0.5
Arch linux, Gnome-shell

cabextract python-evdev python-yaml installed

```
[degekai@DPC ~]$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 34, in <module>
    from lutris.game import Game
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 14, in <module>
    from lutris.runners import import_runner, InvalidRunner, wine
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 10, in <module>
    from lutris.gui.dialogs import FileDialog
  File "/usr/lib/python3.7/site-packages/lutris/gui/dialogs/__init__.py", line 6, in <module>
    from lutris.gui.widgets.utils import open_uri
  File "/usr/lib/python3.7/site-packages/lutris/gui/widgets/utils.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by AccountOneOff** [comment]
Install [pyhton-pillow](https://www.archlinux.org/packages/community/x86_64/python-pillow/)

**Comment by Degekai** [comment]
It works

> Install [pyhton-pillow](https://www.archlinux.org/packages/community/x86_64/python-pillow/)
