### ISSUE TITLE
Saving game settings causes a traceback

### ISSUE THREAD

**Issue by KerfuffleV2** [lutris/lutris#1722]
```
Traceback (most recent call last):
  File "/mnt/extrastorage/lutris/lutris/gui/lutriswindow.py", line 666, in on_game_updated
    self.view.set_selected_game(game.id)
  File "/mnt/extrastorage/lutris/lutris/gui/views/list.py", line 123, in set_selected_game
    row = self.get_row_by_id(game_id, filtered=True)
AttributeError: 'GameListView' object has no attribute 'get_row_by_id'
```

`GameListView` does not seem to provide that method. 

After the traceback occurs, Lutris will try to update the default wine prefix (`~/.wine`) rather than the correct one and must be restarted.

**Comment by strycore** [comment]
Fixed by #1728
