### ISSUE TITLE
[GOG] The Witcher 3 GOTY won't import from library

### ISSUE THREAD

**Issue by rqnn11** [lutris/lutris#1734]
Hello!
**Problem**: The Witcher 3 GOTY won't import from GOG library
**Further information**: My GOG library contains two games: Shadow Warrior 2 and The Witcher 3 GOTY Edition. I could import Shadow Warrior 2 without any problems - The Witcher 3 GOTY however, won't import at all. My GOG account is linked correctly and displays the correct games in the import menu. I hope I'm not missing out something obvious here, but I can't really make any sense of it.
Please let me know if I need to provide any further detail.

**Comment by yacuken** [comment]
The problem is in thegamesdb. It only have regular wild hunt record but no GOTY edition. Someone should add it. Not me (my English level is worse than you can imagine).

**Comment by develroo** [comment]
Not sure it is just that. I linked to my GOG library and tried to import Her Story but I get this.

```
./bin/lutris -d 
INFO     2019-02-09 16:01:45,437 [application.do_command_line:222]:Running Lutris 0.5.0.1
INFO     2019-02-09 16:01:45,439 [startup.check_driver:43]:Using NVIDIA drivers 410.66 for x86_64
INFO     2019-02-09 16:01:45,440 [startup.check_driver:47]:GPU: GeForce GTX 980
INFO     2019-02-09 16:01:45,440 [startup.check_driver:64]:GPU: 10DE:13C0 1462:3170 using nvidia drivers
INFO     2019-02-09 16:01:45,491 [startup.check_vulkan:87]:Vulkan is supported
INFO     2019-02-09 16:01:45,493 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
INFO     2019-02-09 16:01:45,895 [lutriswindow.toggle_connection:557]:Connected to lutris.net as SteamTuxer
DEBUG    2019-02-09 16:01:45,899 [gog.get_library:157]:Returning cached GOG library
DEBUG    2019-02-09 16:01:45,909 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-02-09 16:01:45,916 [http.get:68]:GET https://lutris.net/api/games/library/SteamTuxer
DEBUG    2019-02-09 16:01:45,929 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-02-09 16:01:45,934 [store.get_missing_media:150]:Requesting missing icons from API for 28 games
DEBUG    2019-02-09 16:01:45,935 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-02-09 16:01:46,219 [api.get_game_api_page:128]:Loaded 28 games from page 1
DEBUG    2019-02-09 16:01:46,349 [api.get_game_api_page:128]:Loaded 83 games from page 1
DEBUG    2019-02-09 16:01:57,723 [gog.load_cookies:106]:Loading cookies from /home/user/.cache/lutris/.gog.auth
DEBUG    2019-02-09 16:01:57,726 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-02-09 16:01:57,959 [gog.load_cookies:106]:Loading cookies from /home/user/.cache/lutris/.gog.auth
DEBUG    2019-02-09 16:01:57,963 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-02-09 16:02:00,191 [gog.load_cookies:106]:Loading cookies from /home/user/.cache/lutris/.gog.auth
DEBUG    2019-02-09 16:02:00,195 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-02-09 16:02:00,349 [gog.get_library:157]:Returning cached GOG library
DEBUG    2019-02-09 16:02:13,700 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-02-09 16:02:14,012 [api.get_game_api_page:128]:Loaded 1 games from page 1
Traceback (most recent call last):
  File "/home/user/devel/git/lutris/lutris/gui/widgets/services.py", line 177, in on_service_synced
    (len(games), "s were" if len(games) > 1 else " was")
  File "/home/user/devel/git/lutris/lutris/gui/widgets/notifications.py", line 17, in send_notification
    notification.show()
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)


This is with the git version as the same happened in the binary. 
```

**Comment by strycore** [comment]
this is an issue with GOG, please ask them why they are blocking the witcher 3 from their API.
