### ISSUE TITLE
Can't add a browser game

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1767]
Output when I click save:
```[alex@shinji ~]$ lutris -d
INFO     2019-02-15 22:23:39,748 [application.do_command_line:222]:Running Lutris 0.5.0.1
INFO     2019-02-15 22:23:39,749 [startup.check_driver:43]:Using NVIDIA drivers 415.27 for x86_64
INFO     2019-02-15 22:23:39,749 [startup.check_driver:47]:GPU: GeForce GTX 1070
INFO     2019-02-15 22:23:39,749 [startup.check_driver:64]:GPU: 10DE:1B81 1458:3772 using nvidia drivers
INFO     2019-02-15 22:23:39,770 [startup.check_vulkan:87]:Vulkan is supported
INFO     2019-02-15 22:23:39,771 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
INFO     2019-02-15 22:23:39,935 [lutriswindow.toggle_connection:554]:Connected to lutris.net as citrusalex
DEBUG    2019-02-15 22:23:39,936 [store.get_missing_media:141]:Requesting missing icons from API for 1 games
DEBUG    2019-02-15 22:23:39,936 [http.get:64]:GET https://lutris.net/api/runtime
DEBUG    2019-02-15 22:23:39,942 [http.get:64]:GET https://lutris.net/api/games
DEBUG    2019-02-15 22:23:39,942 [http.get:64]:GET https://lutris.net/api/games/library/citrusalex
DEBUG    2019-02-15 22:23:40,307 [runtime.should_update:58]:Runtime Ubuntu-18.04-i686 locally updated on Пт 15 фев 2019 05:46:34, remote created on Пт 15 фев 2019 10:10:45)
DEBUG    2019-02-15 22:23:40,307 [downloader.start:55]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runtime/Ubuntu-18.04-i686.tar.bz2
DEBUG    2019-02-15 22:23:40,308 [runtime.should_update:58]:Runtime Ubuntu-18.04-x86_64 locally updated on Пт 15 фев 2019 05:44:10, remote created on Пт 15 фев 2019 07:07:18)
DEBUG    2019-02-15 22:23:40,308 [downloader.start:55]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runtime/Ubuntu-18.04-x86_64.tar.bz2
DEBUG    2019-02-15 22:23:40,338 [api.get_game_api_page:122]:Loaded 1 games from page 1
DEBUG    2019-02-15 22:23:40,358 [store.get_missing_media:141]:Requesting missing icons from API for 1 games
DEBUG    2019-02-15 22:23:40,358 [http.get:64]:GET https://lutris.net/api/games
DEBUG    2019-02-15 22:23:40,687 [api.get_game_api_page:122]:Loaded 1 games from page 1
DEBUG    2019-02-15 22:23:52,281 [game.save:202]:Saving Шарарарам (browser)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 440, in on_save
    self.game.save()
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 217, in save
    playtime=self.playtime,
  File "/usr/lib/python3.7/site-packages/lutris/pga.py", line 277, in add_or_update
    game_id = get_matching_game(params)
  File "/usr/lib/python3.7/site-packages/lutris/pga.py", line 295, in get_matching_game
    raise ValueError("Can't add or update without an identifier")
ValueError: Can't add or update without an identifier
```

**Comment by dino8890** [comment]
The problem is in this function:
```
def slugify(value):
    """Remove special characters from a string and slugify it.

    Normalizes string, converts to lowercase, removes non-alpha characters,
    and converts spaces to hyphens.
    """
    value = str(value)
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore")
    value = value.decode("utf-8")
    value = str(re.sub(r"[^\w\s-]", "", value)).strip().lower()
    return re.sub(r"[-\s]+", "-", value)
```
specifically,

`value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore")`

where it fails to encode Cyrillic characters using ASCII for obvious reasons and returning an empty string. Not encoding the value with ASCII works fine for this particular example. I don't know where slugs are used and therefore don't feel comfortable making any changes to it.

slugify gets called from common.py on line 454.

**Comment by aki42** [comment]
This may be correlated with the topic of this report: The steam importer successfully added "Brütal Legend" to my library in Lutris (so non-ASCII does not seem to be a showstopper in general)  whereas "Trüberbrook", part of my purchases at gog.com, does not show up in Lutris after running the importer. All the other games - plain ASCII in their titles - coming from gog.com do.
Fun fact: "Trüberbrook" ist part of the list of games shown in the gog tab of the "Import games" dialog. It just does not make it to the lutris library afterwards.

**Comment by LeXofLeviafan** [comment]
Normalization only appears to work with Latin script characters (like umlauts and other quicky characters in Latin family alphabets). For any other script, some form of transliteration is necessary. I'd suggest using some libraries for that (like [this one](https://github.com/barseghyanartur/transliterate); it even has a `slugify` function in it). Granted, one such library only has a handful of languages implemented, but having something is certainly better than nothing (and one can make it a community effort to extend such a library to work on any scripts necessary; the library I gave as example provides docs on how to do it).

**Comment by dino8890** [comment]
I agree, in fact Lutris website uses the same library in it's variant of the [slugify](https://github.com/lutris/website/blob/67d067e610f85f6b9ffedea092bdc9d78837e5b1/common/util.py#L13) function.

I've been meaning to submit PR for this issue, but I haven't had the time to properly test everything.

**Comment by strycore** [comment]
We now have a fallback to UUID if slug can't be computed
