### ISSUE TITLE
Can't use a web game installer

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1768]
Installer: https://lutris.net/games/shararam/
Log with a traceback:
```[alex@shinji ~]$ lutris -d
INFO     2019-02-15 23:27:15,981 [application.do_command_line:222]:Running Lutris 0.5.0.1
INFO     2019-02-15 23:27:15,982 [startup.check_driver:43]:Using NVIDIA drivers 415.27 for x86_64
INFO     2019-02-15 23:27:15,982 [startup.check_driver:47]:GPU: GeForce GTX 1070
INFO     2019-02-15 23:27:15,982 [startup.check_driver:64]:GPU: 10DE:1B81 1458:3772 using nvidia drivers
INFO     2019-02-15 23:27:16,002 [startup.check_vulkan:87]:Vulkan is supported
INFO     2019-02-15 23:27:16,002 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
INFO     2019-02-15 23:27:16,150 [lutriswindow.toggle_connection:554]:Connected to lutris.net as citrusalex
DEBUG    2019-02-15 23:27:16,152 [http.get:64]:GET https://lutris.net/api/games/library/citrusalex
DEBUG    2019-02-15 23:27:16,152 [store.get_missing_media:141]:Requesting missing icons from API for 1 games
DEBUG    2019-02-15 23:27:16,152 [http.get:64]:GET https://lutris.net/api/runtime
DEBUG    2019-02-15 23:27:16,162 [http.get:64]:GET https://lutris.net/api/games
DEBUG    2019-02-15 23:27:16,515 [api.get_game_api_page:122]:Loaded 1 games from page 1
DEBUG    2019-02-15 23:27:16,549 [store.get_missing_media:141]:Requesting missing icons from API for 1 games
DEBUG    2019-02-15 23:27:16,549 [http.get:64]:GET https://lutris.net/api/games
DEBUG    2019-02-15 23:27:16,831 [api.get_game_api_page:122]:Loaded 1 games from page 1
DEBUG    2019-02-15 23:27:22,174 [http.get:64]:GET https://lutris.net/api/games?search=shararam
DEBUG    2019-02-15 23:27:22,473 [store.get_missing_media:141]:Requesting missing icons from API for 1 games
DEBUG    2019-02-15 23:27:22,474 [http.get:64]:GET https://lutris.net/api/games
DEBUG    2019-02-15 23:27:22,482 [store.refresh_icon:255]:Getting icon for shararam
DEBUG    2019-02-15 23:27:22,819 [api.get_game_api_page:122]:Loaded 1 games from page 1
DEBUG    2019-02-15 23:27:22,819 [store.on_media_loaded:288]:Refreshing shararam
DEBUG    2019-02-15 23:27:22,819 [store.refresh_icon:255]:Getting icon for shararam
DEBUG    2019-02-15 23:27:22,819 [http.get:64]:GET https://lutris.net/games/banner/shararam.jpg
DEBUG    2019-02-15 23:27:23,456 [http.get:64]:GET https://lutris.net/games/icon/shararam.png
DEBUG    2019-02-15 23:27:24,992 [interpreter.fetch_script:53]:Fetching installer https://lutris.net/api/installers/shararam
DEBUG    2019-02-15 23:27:24,992 [http.get:64]:GET https://lutris.net/api/installers/shararam
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/installerwindow.py", line 302, in on_install_clicked
    self.interpreter.check_runner_install()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 438, in check_runner_install
    self.install_runners()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 445, in install_runners
    self.prepare_game_files()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 335, in prepare_game_files
    self.iter_game_files()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 368, in iter_game_files
    self._prepare_commands()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 506, in _prepare_commands
    self._iter_commands()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 535, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 570, in _finish_install
    path = os.path.join(self.target_path, path)
  File "/usr/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by tannisroot** [comment]
So instead of specifying the url like this (which works):

>main_file: https://www.shararam.ru/game

I specified it like this (this is how it was in the config file):

>game:   
>main_file: https://www.shararam.ru/game

Which resulted in a crash.
