### ISSUE TITLE
Installing games with unicode in the name does not work.

### ISSUE THREAD

**Issue by orbea** [lutris/lutris#178]
https://lutris.net/games/rudra-no-hiho/
I was trying to install Rudra no Hihō, when clicking continue after selecting the version I found it did nothing, so I checked with debug output and got:  

~~~
$ lutris -d
DEBUG    2015-04-09 14:16:41,545 [lutris]:Welcome to Lutris

(lutris:11906): Gtk-WARNING **: Unknown property: GtkLabel.lines

(lutris:11906): Gtk-WARNING **: Unknown property: GtkLabel.lines
DEBUG    2015-04-09 14:16:41,678 [lutriswindow]:Getting game list
DEBUG    2015-04-09 14:16:41,886 [lutriswindow]:Switching view
DEBUG    2015-04-09 14:16:42,207 [lutriswindow]:Connecting signals
INFO     2015-04-09 14:16:42,334 [lutriswindow]:Connected as orbea
DEBUG    2015-04-09 14:16:42,336 [jobs]:Async call: sync_all
DEBUG    2015-04-09 14:16:42,336 [sync]:Syncing game library
DEBUG    2015-04-09 14:16:42,336 [jobs]:Async call: update_runtime
DEBUG    2015-04-09 14:16:42,336 [sync]:97 games in local library
DEBUG    2015-04-09 14:16:42,338 [api]:Fetching game library
DEBUG    2015-04-09 14:16:43,747 [sync]:97 games in remote library (inc. unpublished)
DEBUG    2015-04-09 14:16:43,770 [sync]:0 games updated
DEBUG    2015-04-09 14:16:43,770 [sync]:Syncing local steam games
DEBUG    2015-04-09 14:16:43,992 [jobs]:Async call: sync_icons
DEBUG    2015-04-09 14:16:43,993 [resources]:Fetching icons
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/lutris/installer.py", line 833, in on_installer_selected
    self.launch_install(self.installer_choice)
  File "/usr/lib64/python2.7/site-packages/lutris/installer.py", line 781, in launch_install
    self.title_label.set_markup("<b>Installing {}</b>".format(game_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u014d' in position 12: ordinal not in range(128)
~~~

**Comment by Xodetaetl** [comment]
Covered with new runtime
