### ISSUE TITLE
[PATCH] TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

### ISSUE THREAD

**Issue by fuzzyTew** [lutris/lutris#1804]
```
[user@localhost lutris]$ git show-ref --heads
5dd2d37853454025a576cad37fb8398740de72a9 refs/heads/master
[user@localhost lutris]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.6 (Maipo)
[user@localhost lutris]$ bin/lutris
2019-02-23 13:38:29,705: Running Lutris 0.5.0.1
2019-02-23 13:38:29,707: Using Intel Open Source Technology Center
2019-02-23 13:38:29,707: Running Mesa driver 18.0.5 on Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  (0x5916)
2019-02-23 13:38:29,707: GPU: 10DE:134D 17AA:2246 using nouveau drivers
2019-02-23 13:38:29,707: GPU: 8086:5916 17AA:2246 using i915 drivers
2019-02-23 13:38:29,710: Vulkan is not available or your system isn't Vulkan capable
2019-02-23 13:38:29,711: Updating DXVK versions
Traceback (most recent call last):
  File "/shared/src/lutris/lutris/gui/application.py", line 175, in do_activate
    self.window = LutrisWindow(application=self)
  File "/shared/src/lutris/lutris/gui/lutriswindow.py", line 127, in __init__
    self.game_panel = GenericPanel(application=self.application)
  File "/shared/src/lutris/lutris/gui/views/generic_panel.py", line 45, in __init__
    self.set_background()
  File "/shared/src/lutris/lutris/gui/views/generic_panel.py", line 62, in set_background
    b"background-repeat: no-repeat; }" % bg_path.encode("utf-8")
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
Traceback (most recent call last):
  File "/shared/src/lutris/lutris/gui/application.py", line 333, in do_command_line
    self.window.present()
AttributeError: 'NoneType' object has no attribute 'present'
```

**Comment by fuzzyTew** [comment]
This patch makes it launch for me:
```
diff --git a/lutris/gui/views/generic_panel.py b/lutris/gui/views/generic_panel.py
index 77c8348..dd240f2 100644
--- a/lutris/gui/views/generic_panel.py
+++ b/lutris/gui/views/generic_panel.py
@@ -58,8 +58,8 @@ class GenericPanel(Gtk.Fixed):
         style.add_class(Gtk.STYLE_CLASS_VIEW)
         bg_provider = Gtk.CssProvider()
         bg_provider.load_from_data(
-            b'.game-scrolled { background-image: url("%s"); '
-            b"background-repeat: no-repeat; }" % bg_path.encode("utf-8")
+            ('.game-scrolled { background-image: url("%s"); '
+            "background-repeat: no-repeat; }" % bg_path).encode("utf-8")
         )
         Gtk.StyleContext.add_provider_for_screen(
             Gdk.Screen.get_default(),
```

**Comment by strycore** [comment]
Thanks a lot for providing a patch, saves a lot of time!
