### ISSUE TITLE
crash on startup opensuse leap 15 KDE

### ISSUE THREAD

**Issue by melvidomelv** [lutris/lutris#1833]
### I recently installed OpenSUSE Leap 15 KDE, I followed the next steps to install lutris:
`  sudo zypper addrepo https://download.opensuse.org/repositories/home:strycore/openSUSE_Leap_15.0/home:strycore.repo
;sudo zypper refresh
 ;sudo zypper install lutris
`

### And now when i try to launch it i get this output:

Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 34, in <module>
    from lutris.game import Game
  File "/usr/lib/python3.6/site-packages/lutris/game.py", line 14, in <module>
    from lutris.runners import import_runner, InvalidRunner, wine
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 11, in <module>
    from lutris.runners.runner import Runner
  File "/usr/lib/python3.6/site-packages/lutris/runners/runner.py", line 7, in <module>
    from lutris.config import LutrisConfig
  File "/usr/lib/python3.6/site-packages/lutris/config.py", line 6, in <module>
    from lutris import settings, sysoptions
  File "/usr/lib/python3.6/site-packages/lutris/sysoptions.py", line 6, in <module>
    from lutris.util import display, system
  File "/usr/lib/python3.6/site-packages/lutris/util/display.py", line 241, in <module>
    DISPLAY_MANAGER = DisplayManager()
  File "/usr/lib/python3.6/site-packages/lutris/util/display.py", line 221, in __init__
    self.rr_screen = GnomeDesktop.RRScreen.new(screen)
TypeError: Argument 0 does not allow None as a value

### THINGS I TRIED
installing `gnome-desktop` which displays that `libgnome-desktop-3-12` is already installed
manual setting of env variable `DISPLAY=:1`

### Related to this
i found this issue posted, where they talk about something happened to me, i got this problem and i ignored dependencies breaking as he did. But it didn't work for me.
https://github.com/lutris/lutris/issues/1813

**Comment by alpharde** [comment]
I guess you're missing `python3-gobject-Gdk`, try installing it from zypper.

**Comment by jatin-cbs** [comment]
Install wine.. Dont install wine dependency its in official repo  

sudo zypper install wine-staging

**Comment by melvidomelv** [comment]
> I guess you're missing `python3-gobject-Gdk`, try installing it from zypper.
Installing `python3-gobject-Gdk`solved the problem. Thanks. 

> Install wine.. Dont install wine repo its in official repo
> 
> sudo zypper install wine-staging

i already got installed from official repo, I installed wine as zypper install wine, but as you said i installed wine-staging now wich deleted some wine unneeded files.

**Comment by strycore** [comment]
ffs
