### ISSUE TITLE
lutris-git fails to build [Manjaro]

### ISSUE THREAD

**Issue by mrturcot** [lutris/lutris#1836]
Hello, [lutris-git](https://aur.archlinux.org/packages/lutris-git) fails to build with "makepkg" on Manjaro, here is the [pastebin](https://pastebin.com/HgkKddXA) of the failed build.

**Errors here**  

```
======================================================================
ERROR: test_can_add_game (test_dialogs.TestGameDialog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mrturcot/mitch/builds/lutris-git/src/lutris/tests/test_dialogs.py", line 88, in test_can_add_game
    game_box = self.get_game_box()
  File "/home/mrturcot/mitch/builds/lutris-git/src/lutris/tests/test_dialogs.py", line 52, in get_game_box
    return self.get_viewport(1)
  File "/home/mrturcot/mitch/builds/lutris-git/src/lutris/tests/test_dialogs.py", line 43, in get_viewport
    scrolled_window = children[index]
IndexError: list index out of range
-------------------- >> begin captured stdout << ---------------------
No viewport for index 1
[<Gtk.ScrolledWindow object at 0x7fd0ee989f30 (GtkScrolledWindow at 0x55e3c7dc2410)>]

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_changing_runner_sets_new_config (test_dialogs.TestGameDialog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mrturcot/mitch/builds/lutris-git/src/lutris/tests/test_dialogs.py", line 77, in test_changing_runner_sets_new_config
    game_box = self.get_game_box()
  File "/home/mrturcot/mitch/builds/lutris-git/src/lutris/tests/test_dialogs.py", line 52, in get_game_box
    return self.get_viewport(1)
  File "/home/mrturcot/mitch/builds/lutris-git/src/lutris/tests/test_dialogs.py", line 43, in get_viewport
    scrolled_window = children[index]
IndexError: list index out of range
-------------------- >> begin captured stdout << ---------------------
No viewport for index 1
[<Gtk.ScrolledWindow object at 0x7fd0ee97dab0 (GtkScrolledWindow at 0x55e3c84d0770)>]
```

Regards

**Comment by 7HEPOW** [comment]
Can confirm installing lutris-git from AUR on Manjaro too. Returns the same errors for test_dialogs.py for me.

**Comment by mrturcot** [comment]
Seems Travis is experiencing the exact same error resulting in build failure https://travis-ci.org/lutris/lutris/builds/501006860?utm_source=github_status&utm_medium=notification

**Comment by 7HEPOW** [comment]
Can you retry, @mrturcot ? Just installed it succesfully from AUR.

**Comment by mrturcot** [comment]
> Can you retry, @mrturcot ? Just installed it succesfully from AUR.

Success! Thanks for the heads up.  

Issue closed
