### ISSUE TITLE
Multiple runners: Add new game dialogue doesn't show up

### ISSUE THREAD

**Issue by 7HEPOW** [lutris/lutris#1840]
When trying to add a new game with a runner selected on the left panel, on some runners the dialogue window doesn't show up. From the runners I have installed the failing ones are:
- DOSBox
- Linux (Which is funny somehow... :D )
- ScummVM
- Wine
- Wine Steam
- ZDoom (Which is where I noticed it)

The output of 'lutris -d' for them is identical and as follows:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 723, in on_add_game_button_clicked
    AddGameDialog(self, runner=self.selected_runner)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/add_game.py", line 28, in __init__
    self.build_tabs("game")
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 66, in build_tabs
    self._build_game_tab()
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 309, in _build_game_tab
    self.game_box = GameBox(self.lutris_config, game)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 616, in __init__
    self.generate_widgets("game")
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 91, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 184, in call_widget_generator
    self.generate_directory_chooser(option, value)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 413, in generate_directory_chooser
    default_path = self.game.runner.working_dir
AttributeError: 'NoneType' object has no attribute 'working_dir'
```
Dialogues show up correctly for the rest I'm using: Atari800, Dolphin, FS-UAE, Hatari, MAME, Mednafen, PCSX2, PPSSPP, Reicast, Steam and Vice.

When selecting 'All runners' at the top on the left panel and selecting one of the failing runners, the Game/Runner/System Options tabs disappear, leaving only the initial 'Game Info' dialogue available. Here's the output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 389, in on_runner_changed
    self._rebuild_tabs()
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 395, in _rebuild_tabs
    self._build_game_tab()
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 309, in _build_game_tab
    self.game_box = GameBox(self.lutris_config, game)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 616, in __init__
    self.generate_widgets("game")
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 91, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 184, in call_widget_generator
    self.generate_directory_chooser(option, value)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/boxes.py", line 413, in generate_directory_chooser
    default_path = self.game.runner.working_dir
AttributeError: 'NoneType' object has no attribute 'working_dir'
```
The new 'empty' launcher with the initially selected runner can be edited afterwards with all options available as if adding a new game regularly. So this is also the workaround in a way. :)
I'm currently running 0.5.0.1.r72.g3f660c64
Cheers! ;)

**Comment by strycore** [comment]
fixed
