### ISSUE TITLE
master branch currently has two failing tests

### ISSUE THREAD

**Issue by AaronOpfer** [lutris/lutris#1841]
```
/home/aopfer/gits/lutris/lutris/util/display.py:7: PyGIWarning: GnomeDesktop was imported without specifying a version first. Use gi.require_version('GnomeDesktop', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, GnomeDesktop, GLib
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:571: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "title, transient_for, flags, add_buttons" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self._init(*args, **new_kwargs)
/home/aopfer/gits/lutris/lutris/gui/widgets/common.py:134: DeprecationWarning: Gtk.Misc.set_alignment is deprecated
  self.set_alignment(0, 0.5)
/home/aopfer/gits/lutris/lutris/gui/config/common.py:170: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  install_runners_btn = Gtk.Button("Install runners")
/home/aopfer/gits/lutris/lutris/gui/config/boxes.py:129: DeprecationWarning: Gtk.Widget.set_margin_left is deprecated
  hbox.set_margin_left(18)
/home/aopfer/gits/lutris/lutris/gui/widgets/common.py:172: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.add_button = Gtk.Button("Add")
/home/aopfer/gits/lutris/lutris/gui/widgets/common.py:176: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.delete_button = Gtk.Button("Delete")
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:581: DeprecationWarning: Gtk.Dialog.get_action_area is deprecated
  action_area = property(lambda dialog: dialog.get_action_area())
Traceback (most recent call last):
  File "/home/aopfer/gits/lutris/lutris/gui/config/common.py", line 389, in on_runner_changed
    self._rebuild_tabs()
  File "/home/aopfer/gits/lutris/lutris/gui/config/common.py", line 395, in _rebuild_tabs
    self._build_game_tab()
  File "/home/aopfer/gits/lutris/lutris/gui/config/common.py", line 309, in _build_game_tab
    self.game_box = GameBox(self.lutris_config, game)
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 616, in __init__
    self.generate_widgets("game")
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 91, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 184, in call_widget_generator
    self.generate_directory_chooser(option, value)
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 413, in generate_directory_chooser
    default_path = self.game.runner.working_dir
AttributeError: 'NoneType' object has no attribute 'working_dir'
E/home/aopfer/gits/lutris/lutris/gui/application.py:63: Warning: g_set_application_name() called multiple times
  GLib.set_application_name(_("Lutris"))
Traceback (most recent call last):
  File "/home/aopfer/gits/lutris/lutris/gui/config/common.py", line 389, in on_runner_changed
    self._rebuild_tabs()
  File "/home/aopfer/gits/lutris/lutris/gui/config/common.py", line 395, in _rebuild_tabs
    self._build_game_tab()
  File "/home/aopfer/gits/lutris/lutris/gui/config/common.py", line 309, in _build_game_tab
    self.game_box = GameBox(self.lutris_config, game)
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 616, in __init__
    self.generate_widgets("game")
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 91, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 184, in call_widget_generator
    self.generate_directory_chooser(option, value)
  File "/home/aopfer/gits/lutris/lutris/gui/config/boxes.py", line 413, in generate_directory_chooser
    default_path = self.game.runner.working_dir
AttributeError: 'NoneType' object has no attribute 'working_dir'
E....2019-03-07 13:08:26,506: The command "substitute" does not exist.
None
..2019-03-07 13:08:26,506: This installer doesn't have a 'script' section
None
......2019-03-07 13:08:26,562: Migrating basetable field new_field
........................./home/aopfer/gits/lutris/tests/test_registry.py:100: DeprecationWarning: Please use assertRegex instead.
  self.assertRegexpMatches(key.raw_timestamp, r'\d+\s\d+')
.............................
======================================================================
ERROR: test_can_add_game (test_dialogs.TestGameDialog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aopfer/gits/lutris/tests/test_dialogs.py", line 88, in test_can_add_game
    game_box = self.get_game_box()
  File "/home/aopfer/gits/lutris/tests/test_dialogs.py", line 52, in get_game_box
    return self.get_viewport(1)
  File "/home/aopfer/gits/lutris/tests/test_dialogs.py", line 43, in get_viewport
    scrolled_window = children[index]
IndexError: list index out of range

======================================================================
ERROR: test_changing_runner_sets_new_config (test_dialogs.TestGameDialog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aopfer/gits/lutris/tests/test_dialogs.py", line 77, in test_changing_runner_sets_new_config
    game_box = self.get_game_box()
  File "/home/aopfer/gits/lutris/tests/test_dialogs.py", line 52, in get_game_box
    return self.get_viewport(1)
  File "/home/aopfer/gits/lutris/tests/test_dialogs.py", line 43, in get_viewport
    scrolled_window = children[index]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 68 tests in 0.864s

FAILED (errors=2)
No viewport for index 1
[<Gtk.ScrolledWindow object at 0x7f4242b935e8 (GtkScrolledWindow at 0x21d04c0)>]
No viewport for index 1
[<Gtk.ScrolledWindow object at 0x7f4240422120 (GtkScrolledWindow at 0x29848a0)>]
```

**Comment by 7HEPOW** [comment]
Seems like this closed one is the same: https://github.com/lutris/lutris/issues/1836

**Comment by tannisroot** [comment]
I've had the same issue with lutris-git package from AUR and clean-building solved it somehow.

**Comment by strycore** [comment]
fixed
