### ISSUE TITLE
get_children_pids_of_thread(): process.py:57:get_children_pids_of_thread:ProcessLookupError: [Errno 3] No such process: '/proc/25892/task/25892/children'

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#1851]
Here's another Fedora report.

https://bugzilla.redhat.com/show_bug.cgi?id=1686988

cmdline:        /usr/bin/python3 -s /usr/bin/lutris-wrapper 0 0 /home/u13881/.local/share/lutris/runtime/winetricks/winetricks --unattended
crash_function: get_children_pids_of_thread
exception_type: ProcessLookupError
executable:     /usr/bin/lutris-wrapper
interpreter:    python3-3.7.2-4.fc29.x86_64
kernel:         4.20.13-200.fc29.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
process.py:57:get_children_pids_of_thread:ProcessLookupError: [Errno 3] No such process: '/proc/25892/task/25892/children'

Traceback (most recent call last):
  File "/usr/bin/lutris-wrapper", line 110, in <module>
    main()
  File "/usr/bin/lutris-wrapper", line 91, in main
    if not monitor.refresh_process_status():
  File "/usr/lib/python3.7/site-packages/lutris/util/monitor.py", line 98, in refresh_process_status
    for child in self.iter_children(Process(os.getpid())):
  File "/usr/lib/python3.7/site-packages/lutris/util/process.py", line 20, in __init__
    self.get_children()
  File "/usr/lib/python3.7/site-packages/lutris/util/process.py", line 67, in get_children
    self.children.append(Process(child_pid, parent=self))
  File "/usr/lib/python3.7/site-packages/lutris/util/process.py", line 20, in __init__
    self.get_children()
  File "/usr/lib/python3.7/site-packages/lutris/util/process.py", line 67, in get_children
    self.children.append(Process(child_pid, parent=self))
  File "/usr/lib/python3.7/site-packages/lutris/util/process.py", line 20, in __init__
    self.get_children()
  File "/usr/lib/python3.7/site-packages/lutris/util/process.py", line 66, in get_children
    for child_pid in self.get_children_pids_of_thread(tid):
  File "/usr/lib/python3.7/site-packages/lutris/util/process.py", line 57, in get_children_pids_of_thread
    with open(children_path) as children_file:
ProcessLookupError: [Errno 3] No such process: '/proc/25892/task/25892/children'

Local variables in innermost frame:
self: Process 25892
tid: '25892'
children_path: '/proc/25892/task/25892/children'

**Comment by AaronOpfer** [comment]
Hmm, looks like a race condition. The process seems to die in between learning of its existence and us trying to learn information about it. This should be pretty easy to fix.
