### ISSUE TITLE
Error in Lutris 0.5.1.1

### ISSUE THREAD

**Issue by eNuKeD** [lutris/lutris#1936]
Yesterday I was playing Overwatch without problems and today with the new update, I have a problem when starting the game:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 832, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 718, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 744, in get_runtime_env
    if entry in wine_path:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

The play button, stay stuck on "Launching".
This happend with all games from wine runner.

![gGmiPI3](https://user-images.githubusercontent.com/5289911/54913999-4cdc3f00-4ef4-11e9-9ffd-6d6c61dd512c.png)

**Comment by EzraT** [comment]
Can confirm, this also happens to me on Linux Mint 19.1.

**Comment by eNuKeD** [comment]
I also use Linux Mint 19.1

**Comment by kuchenohnegraeten** [comment]
The same happens to me on Ubuntu 18.04 with wine games / wine launchers (Epic Launcher, Battle.Net, Anno 1404 (GOG)), hanging with "Launching...". Here the error output from the command-line-started lutris:
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 832, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 718, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 744, in get_runtime_env
    if entry in wine_path:
TypeError: 'in <string>' requires string as left operand, not NoneType
`

**Comment by DoktorSeven** [comment]
Same in Arch:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 832, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 718, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3.7/site-packages/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 744, in get_runtime_env
    if entry in wine_path:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Comment by imisak** [comment]
same error happens to me after update... revert to lutris 0.5.1 and everything works again... I use battle.net and diablo 3 in lutris...

**Comment by Lrss** [comment]
I could fix it by adding quotation to 'entry' in /usr/lib/python3.7/site-packages/lutris/runners/wine.py line 744
Before:
```        
for entry in PROTON_PATH:
    if entry in wine_path:
```
After:
```        
for entry in PROTON_PATH:
    if 'entry' in wine_path:
```
(testet on kernel 5.0.4-arch1-1-ARCH)

**Comment by eNuKeD** [comment]
Fixed with temporary fix: 
https://github.com/lutris/lutris/wiki/Temporary-workaround-for-game-launching-issues-in-0.5.1.1

**Comment by leerodrigues** [comment]
Ubuntu 18.04
Fixed with temporary workaround as well.
https://github.com/lutris/lutris/wiki/Temporary-workaround-for-game-launching-issues-in-0.5.1.1

**Comment by Lrss** [comment]
The problem seems to be that the entry variable can be of the type None, so instead of just uncommenting the lines we should just check before comparing:
```
/usr/lib/python3*/*-packages/lutris/runners/wine.py
line 744: for entry in PROTON_PATH:
line 745:     if entry is not None and entry in wine_path:
```

**Comment by Lrss** [comment]
Temporary workaround:
`sudo sed -i "744 s/entry/entry is not None and entry/" /usr/lib/python3*/*-packages/lutris/runners/wine.py`
