### ISSUE TITLE
Wine games no longer launch (with solution!)

### ISSUE THREAD

**Issue by dstelzer** [lutris/lutris#1938]
When I try to launch a Wine game, I get this in the log:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 832, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 718, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 744, in get_runtime_env
    if entry in wine_path:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

Changing line 744 in `wine.py` to `if entry is not None and entry in wine_path` fixes the problem and everything works fine again. (I would submit a pull request but I'm not quite sure how those work.)

**Comment by telanus** [comment]
Same error as https://github.com/lutris/lutris/issues/1936
