### ISSUE TITLE
Namespace Gdk not available in snap

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#1943]
Tried to build a snap for lutris and currently it's stuck here when trying to run the program from snap:
```
Traceback (most recent call last):
  File "/snap/lutris/x2/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/snap/lutris/x2/lib/python3.6/site-packages/lutris/gui/application.py", line 28, in <module>
    gi.require_version("Gdk", "3.0")
  File "/snap/lutris/x2/usr/lib/python3/dist-packages/gi/__init__.py", line 127, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gdk not available
```

**Comment by TingPing** [comment]
Probably just explicitly add gir1.2-gdk-3.0 (or whatever) to the deb dependencies?

**Comment by strycore** [comment]
Yes, it's using a Ubuntu 18.04 base. Problem is that there is no such package, the closest there is, relative to Gdk is gir1.2-gdkpixbuf-2.0

**Comment by TingPing** [comment]
Ah the gtk package does have gdk in it.

Probably set `GI_TYPELIB_DIR=$SNAP/the/path/to/it`

In my experience you have to set plenty of env vars (and patch libs without env vars) to be usable in Snap.

**Comment by mikeroyal** [comment]
Hi @popey, 

If you have a quick moment could you help @strycore with the Lutris snap. He running into some issues with the build.

**Comment by Justinzobel** [comment]
Oh the internet knows.. I just started trying to build a Lutris snap and landed here while getting the same error.
