### ISSUE TITLE
Not a gzip file.

### ISSUE THREAD

**Issue by Alexander88207** [lutris/lutris#1946]
This error happends if i want to start something with dxvk because without dxvk it starts fine:

![image](https://user-images.githubusercontent.com/37543796/55035791-27952100-5019-11e9-8ab6-26c946f44231.png)

```
lutris -d
INFO     2019-03-26 22:42:28,629 [application.do_command_line:222]:Running Lutris 0.5.0.1
WARNING  2019-03-26 22:42:28,631 [startup.check_driver:57]:glxinfo is not available on your system, unable to detect driver version
INFO     2019-03-26 22:42:28,631 [startup.check_driver:64]:GPU: 1002:67DF 1458:22F7 using amdgpu drivers
INFO     2019-03-26 22:42:28,715 [startup.check_vulkan:87]:Vulkan is supported
INFO     2019-03-26 22:42:28,716 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
DEBUG    2019-03-26 22:42:28,966 [http.get:64]:GET https://lutris.net/api/runtime
DEBUG    2019-03-26 22:42:36,169 [application.launch:339]:Adding game Origin (wine) (139830245470280) to running games
DEBUG    2019-03-26 22:42:36,179 [game.play:257]:Prelaunching <lutris.runners.wine.wine object at 0x7f2cc4260ac8>
DEBUG    2019-03-26 22:42:36,223 [prefix.set_virtual_desktop:121]:Virtual desktop: None
DEBUG    2019-03-26 22:42:36,247 [downloader.start:55]:Starting download of:
 https://github.com/doitsujin/dxvk/releases/download/v1.0.1/dxvk-1.0.1.tar.gz
DEBUG    2019-03-26 22:42:36,715 [downloader.on_done:96]:Finished downloading https://github.com/doitsujin/dxvk/releases/download/v1.0.1/dxvk-1.0.1.tar.gz
DEBUG    2019-03-26 22:42:36,849 [extract.extract_archive:68]:Extracting /home/alexander/.local/share/lutris/runtime/dxvk/dxvk-1.0.1.tar.gz to /home/alexander/.local/share/lutris/runtime/dxvk/1.0.1
ERROR    2019-03-26 22:42:36,849 [jobs.target:32]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f2cc4260ac8>>: not a gzip file
<class 'tarfile.ReadError'> not a gzip file
  File "/usr/lib64/python3.6/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/lutris/runners/wine.py", line 682, in prelaunch
    version=dxvk_version,
  File "/usr/lib64/python3.6/site-packages/lutris/runners/wine.py", line 660, in toggle_dxvk
    dxvk_manager.download()
  File "/usr/lib64/python3.6/site-packages/lutris/util/wine/dxvk.py", line 114, in download
    extract_archive(dxvk_archive_path, self.dxvk_path, merge_single=True)
  File "/usr/lib64/python3.6/site-packages/lutris/util/extract.py", line 90, in extract_archive
    _do_extract(path, temp_path, opener, mode, extractor)
  File "/usr/lib64/python3.6/site-packages/lutris/util/extract.py", line 130, in _do_extract
    handler = opener(archive, mode)
  File "/usr/lib64/python3.6/tarfile.py", line 1587, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1645, in gzopen
    raise ReadError("not a gzip file")
ERROR    2019-03-26 22:42:36,851 [game.configure_game:274]:not a gzip file
ERROR    2019-03-26 22:42:39,210 [game.configure_game:277]:Game prelaunch unsuccessful
```
[System Information](https://gist.github.com/Alexander88207/72c104e4d0f59898cc4ede2fce2de25a/)

**Comment by Medath** [comment]
Does this still happen when you delete `/home/alexander/.local/share/lutris/runtime/dxvk/dxvk-1.0.1.tar.gz` and try again?

**Comment by Alexander88207** [comment]
Thanks!

**Comment by AccountOneOff** [comment]
Getting something similar with this installer:

```
files:
- client: https://download.toontownrewritten.com/launcher/linux/TTRLinux-v1.2.3.tar.gz
game:
  exe: Launcher
installer:
- extract:
    file: client
```

```
cxf@PC:~$ lutris -d
2019-03-31 19:30:11,596: Running Lutris 0.5.1.3
2019-03-31 19:30:11,596: Using NVIDIA drivers 418.56 for x86_64
2019-03-31 19:30:11,596: GPU: GeForce GTX 960
2019-03-31 19:30:11,596: GPU: 10DE:1401 19DA:2375 using nvidia drivers
2019-03-31 19:30:11,615: Vulkan is supported
2019-03-31 19:30:11,619: Fetching installer https://lutris.net/api/installers/games/toontown-rewritten/revisions/23329
2019-03-31 19:30:11,619: GET https://lutris.net/api/installers/games/toontown-rewritten/revisions/23329
2019-03-31 19:30:15,048: Required runners: [<lutris.runners.linux.linux object at 0x7f5d62143a20>]
2019-03-31 19:30:15,049: Downloading file 1 of 1
2019-03-31 19:30:15,050: Downloading [client]: https://download.toontownrewritten.com/launcher/linux/TTRLinux-v1.2.3.tar.gz to /home/cxf/.cache/lutris/installer/toontown-rewritten/client/TTRLinux-v1.2.3.tar.gz
2019-03-31 19:30:15,053: Downloading https://download.toontownrewritten.com/launcher/linux/TTRLinux-v1.2.3.tar.gz to /home/cxf/.cache/lutris/installer/toontown-rewritten/client/TTRLinux-v1.2.3.tar.gz
2019-03-31 19:30:15,055: Starting download of:
 https://download.toontownrewritten.com/launcher/linux/TTRLinux-v1.2.3.tar.gz
2019-03-31 19:30:18,580: Finished downloading https://download.toontownrewritten.com/launcher/linux/TTRLinux-v1.2.3.tar.gz
2019-03-31 19:30:19,062: Installer command: {'extract': {'file': 'client'}}
2019-03-31 19:30:19,063: Extracting TTRLinux-v1.2.3.tar.gz
2019-03-31 19:30:19,064: extracting file /home/cxf/.cache/lutris/installer/toontown-rewritten/client/TTRLinux-v1.2.3.tar.gz to /home/cxf/Games/toontown-rewritten
2019-03-31 19:30:19,073: Extracting /home/cxf/.cache/lutris/installer/toontown-rewritten/client/TTRLinux-v1.2.3.tar.gz to /home/cxf/Games/toontown-rewritten
2019-03-31 19:30:19,076: Error while completing task <bound method CommandsMixin.extract of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f5d63ec35f8>>: not a gzip file
<class 'tarfile.ReadError'> not a gzip file
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 175, in extract
    extract.extract_archive, filename, dest_path, merge_single, extractor
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 519, in _killable_process
    result = result_obj.get()  # Wait process end & reraise exceptions
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
```

**Comment by RodrigoLeiteF** [comment]
Still happens with this installer apparently. https://lutris.net/games/install/13197/view

```
INFO     2019-06-29 07:48:44,597 [application.do_command_line:225]:Running Lutris 0.5.2.1
INFO     2019-06-29 07:48:44,597 [startup.check_driver:60]:Using Intel Open Source Technology Center
INFO     2019-06-29 07:48:44,597 [startup.check_driver:65]:Running Mesa driver 19.1.0 on Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)  (0x5917)
INFO     2019-06-29 07:48:44,597 [startup.check_driver:75]:GPU: 8086:5917 1028:0829 using i915 drivers
INFO     2019-06-29 07:48:44,628 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-06-29 07:48:44,629 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
DEBUG    2019-06-29 07:48:44,791 [store.get_missing_media:182]:Requesting missing icons from API for phantasy-star-online
DEBUG    2019-06-29 07:48:44,792 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-06-29 07:48:44,797 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-06-29 07:48:45,978 [api.get_game_api_page:134]:No game found for phantasy-star-online
DEBUG    2019-06-29 07:48:47,649 [application.launch:339]:Launching Guild Wars 2 (wine) (140393464216960)
DEBUG    2019-06-29 07:48:47,673 [game.play:269]:Prelaunching <lutris.runners.wine.wine object at 0x7fafe4089b38>
DEBUG    2019-06-29 07:48:48,037 [downloader.start:55]:Starting download of:
 https://github.com/doitsujin/dxvk/releases/download/vd9vk-6b125834/dxvk-d9vk-6b125834.tar.gz
DEBUG    2019-06-29 07:48:48,713 [downloader.on_done:97]:Finished downloading https://github.com/doitsujin/dxvk/releases/download/vd9vk-6b125834/dxvk-d9vk-6b125834.tar.gz
DEBUG    2019-06-29 07:48:48,939 [extract.extract_archive:68]:Extracting /home/rodrigo/.local/share/lutris/runtime/dxvk/dxvk-d9vk-6b125834.tar.gz to /home/rodrigo/.local/share/lutris/runtime/dxvk/d9vk-6b125834
ERROR    2019-06-29 07:48:48,940 [extract.extract_archive:111]:Extraction failed: not a gzip file
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.7/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'No')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 109, in extract_archive
    _do_extract(path, temp_path, opener, mode, extractor)
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 153, in _do_extract
    handler = opener(archive, mode)
  File "/usr/lib/python3.7/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
ERROR    2019-06-29 07:48:48,942 [jobs.target:32]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7fafe4089b38>>: not a gzip file
<class 'lutris.util.extract.ExtractFailure'> not a gzip file
ERROR    2019-06-29 07:48:48,944 [game.configure_game:286]:not a gzip file
ERROR    2019-06-29 07:48:50,381 [game.configure_game:289]:Game prelaunch unsuccessful
INFO     2019-06-29 07:48:54,683 [application.do_shutdown:440]:Shutting down Lutris
```

Deleting the errored file does not fix the issue.

**Comment by keithbowes** [comment]
> Still happens with this installer apparently. https://lutris.net/games/install/13197/view
> 
&lt;snip&gt;
> 
> Deleting the errored file does not fix the issue. Apparently the url it's trying to download wine from 404s.

Yeah, I have some .tar.gz and .tar.bz2 files in my ~/.local/share/lutris/runtime directory, all of which are 186 bytes.  For example, lib32.tar.bz2 contains:
```xml
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><RequestId>tx000000000000055a5e260-005d1ede99-2f7a384-nyc3a</RequestId><HostId>2f7a384-nyc3a-nyc</HostId></Error>
```

Something seems to be wrong with the download code.

Not that it's a big deal.  The Lutris runtime causes more problems than it solves anyway.  With few exceptions (i.e. proprietary libraries), it's best to just use your distro's up-to-date packages.

**Comment by yurikoles** [comment]
In my case it was `d9vk` as `dxvk` version, which `lutris` was unable to download.
