### ISSUE TITLE
process.py:32:get_stat:FileNotFoundError: [Errno 2] No such file or directory: '/proc/25421/stat'

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#1955]
Here's a new Fedora report. Doesn't seem to be a duplicate to me, but it is on 0.5.0.1.

Version-Release number of selected component:
lutris-0.5.0.1-5.fc28

Additional info:
reporter:       libreport-2.9.5
cmdline:        /usr/bin/python3 -s /usr/bin/lutris-wrapper 0 0 /home/fresa/.local/share/lutris/runners/wine/esync-staging-pba-3.18-x86_64/bin/wine cmd /C Warframe-Launcher.bat
crash_function: get_stat
exception_type: FileNotFoundError
executable:     /usr/bin/lutris-wrapper
interpreter:    python3-3.6.8-2.fc28.x86_64
kernel:         4.20.16-100.fc28.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
process.py:32:get_stat:FileNotFoundError: [Errno 2] No such file or directory: '/proc/25421/stat'

Traceback (most recent call last):
  File "/usr/bin/lutris-wrapper", line 110, in <module>
    main()
  File "/usr/bin/lutris-wrapper", line 91, in main
    if not monitor.refresh_process_status():
  File "/usr/lib/python3.6/site-packages/lutris/util/monitor.py", line 117, in refresh_process_status
    self._log_changes('monitored', old_children, self.children)
  File "/usr/lib/python3.6/site-packages/lutris/util/monitor.py", line 89, in _log_changes
    logger.debug("New %s processes: %s", label, ', '.join(map(str, added)))
  File "/usr/lib/python3.6/site-packages/lutris/util/process.py", line 26, in __str__
    return "{} ({}:{})".format(self.name, self.pid, self.state)
  File "/usr/lib/python3.6/site-packages/lutris/util/process.py", line 72, in name
    _stat = self.get_stat(parsed=False)
  File "/usr/lib/python3.6/site-packages/lutris/util/process.py", line 32, in get_stat
    with open(stat_filename) as stat_file:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/25421/stat'

Local variables in innermost frame:
stat_filename: '/proc/25421/stat'
parsed: False
self: Process 25421

**Comment by strycore** [comment]
Fixed in https://github.com/lutris/lutris/commit/23d4a0360446a50bf97bf95c77d205b8ef6852e2
