### ISSUE TITLE
Unable to launch wine games or running installer require wine

### ISSUE THREAD

**Issue by VortexAcherontic** [lutris/lutris#1961]
Hey there I have a problem when launching wine games, wine steam or scripts using/requiring wine.

If I try to launch a game nithing happens and "Launching..." is writen in the Play-Button with this error message in the terminal:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 832, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 718, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3.6/site-packages/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 744, in get_runtime_env
    if entry in wine_path:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

If I try to run some installers requiring wine I get an empty dialog box after I hit the final "Install"Button with this in the terminal:

```
Error while completing task <bound method winesteam.install_game of Winesteam runner (LutrisConfig(level=runner, game_config_id=None, runner=winesteam))>: 'in <string>' requires string as left operand, not NoneType
<class 'TypeError'> 'in <string>' requires string as left operand, not NoneType
  File "/usr/lib/python3.6/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/lutris/runners/winesteam.py", line 381, in install_game
    env=self.get_env()
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 718, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3.6/site-packages/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 744, in get_runtime_env
    if entry in wine_path:
2019-03-28 18:35:29,043: 'in <string>' requires string as left operand, not NoneType
None
```

How ever I'm still using Lutris 0.5.1.1 because my distributions repos dose nt offer the latest version yet.
Is this already fixed in 0.5.1.2?

**Comment by strycore** [comment]
yeah, that's the issue 0.5.2 is fixing. If you're on Ubuntu, please note that we're having issue with the OBS repositories, we advise users to switch to the Launchpad PPA (the instructions are on http://lutris.net/downloads/ )

**Comment by VortexAcherontic** [comment]
Thank you very much for the fast answer.
The funny thin is that they just pushed the latest version in to the openSUSE repos :D 
Now everything works just as it should :+1:
