### ISSUE TITLE
Lutris will not start

### ISSUE THREAD

**Issue by jttheninja** [lutris/lutris#1967]
So, all of a sudden, out of the blue, Lutris no longer even starts up. Running it from the terminal gives the following output:

```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 33, in <module>
    from lutris import pga
  File "/usr/lib/python3/dist-packages/lutris/pga.py", line 11, in <module>
    from lutris import settings
  File "/usr/lib/python3/dist-packages/lutris/settings.py", line 28, in <module>
    sio = SettingsIO(CONFIG_FILE)
  File "/usr/lib/python3/dist-packages/lutris/util/settings.py", line 12, in __init__
    self.config.read([self.config_file])
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 1: invalid start byte

```

I've tried reinstalling, purging and re-installing, and re-reinstalling lutris, but nothing seems to solve it.

**Comment by jttheninja** [comment]
Think I solved it...deleted ~/.config/lutris/lutris.conf

**Comment by tannisroot** [comment]
I kind of want to reopen this because Lutris might need to be able to handle this issue.

**Comment by strycore** [comment]
![megastress](https://user-images.githubusercontent.com/280336/55412887-17031000-551d-11e9-858d-6fc8e050c1ed.png)

**Comment by strycore** [comment]
yo, don't close tickets containing a backtrace.

**Comment by strycore** [comment]
also, deleting a setting file that lutris is failing to read is not how to solve problems.
