### ISSUE TITLE
Can't launch games on master with prefer system libraries enabled

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1969]
```
DEBUG    2019-03-30 14:02:57,737 [application.launch:341]:Adding game EFMB (linux) (140618847460016) to running games
DEBUG    2019-03-30 14:02:57,742 [display._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2019-03-30 14:02:57,761 [game.configure_game:305]:Launching EFMB: {'command': ['/home/cxf/Downloads/EFMB_linux/EFMB/runner']}
DEBUG    2019-03-30 14:02:57,761 [game.configure_game:306]:Game info: {
  "command": [
    "/home/cxf/Downloads/EFMB_linux/EFMB/runner"
  ]
}
Traceback (most recent call last):
  File "/home/cxf/.lutris/lutris/game_actions.py", line 156, in on_game_run
    self.application.launch(self.game)
  File "/home/cxf/.lutris/lutris/gui/application.py", line 344, in launch
    game.play()
  File "/home/cxf/.lutris/lutris/game.py", line 277, in play
    self.configure_game(True)
  File "/home/cxf/.lutris/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/home/cxf/.lutris/lutris/game.py", line 447, in configure_game
    game_env = gameplay_info.get("env") or self.runner.get_env()
  File "/home/cxf/.lutris/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/home/cxf/.lutris/lutris/runners/runner.py", line 176, in get_runtime_env
    prefer_system_libs=self.system_config.get("prefer_system_libs", True)
  File "/home/cxf/.lutris/lutris/runtime.py", line 214, in get_env
    wine_path=wine_path
  File "/home/cxf/.lutris/lutris/runtime.py", line 291, in get_paths
    wine_path=wine_path
  File "/home/cxf/.lutris/lutris/runtime.py", line 279, in get_runtime_paths
    paths += get_system_paths()
  File "/home/cxf/.lutris/lutris/runtime.py", line 240, in get_system_paths
    paths.append(lib_paths[index])
IndexError: list index out of range
```

Git bisect:

```
4bd62c999808615a4840932af2685ddd695886c9 is the first bad commit
commit 4bd62c999808615a4840932af2685ddd695886c9
Author: aTosser <38044923+aTosser@users.noreply.github.com>
Date:   Sat Mar 30 06:25:41 2019 -0400

    Uses dynamic procedure for deducing library paths.
    
    Use ldconfig and parse results to locate all possible library paths on the system guided by the linker.

:040000 040000 e2e31e7c9a98cfe1c3e9360d33d6b860898769cd 57fae548dbcbb003d206fda2d9bc4458290622d5 M	lutris
```

@aTosser

**Comment by strycore** [comment]
called it!

**Comment by aTosser** [comment]
What distro is this on? Perhaps I can evaluate the problem in a VM.

**Comment by AccountOneOff** [comment]
Ubuntu 18.10. I'll test your revised PR.

**Comment by strycore** [comment]
It's not a distro issue, the code is buggy.

**Comment by aTosser** [comment]
The runtime just needed to be updated for the new logic.
