### ISSUE TITLE
Can't launch a game after changing Wine version

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1978]
Just changed Wine version in a game, and now I can't launch it:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 837, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 723, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3.7/site-packages/lutris/runners/runner.py", line 149, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 758, in get_runtime_env
    wine_path=wine_root
  File "/usr/lib/python3.7/site-packages/lutris/runtime.py", line 214, in get_env
    wine_path=wine_path
  File "/usr/lib/python3.7/site-packages/lutris/runtime.py", line 291, in get_paths
    wine_path=wine_path
  File "/usr/lib/python3.7/site-packages/lutris/runtime.py", line 279, in get_runtime_paths
    paths += get_system_paths()
  File "/usr/lib/python3.7/site-packages/lutris/runtime.py", line 240, in get_system_paths
    paths.append(lib_paths[index])
IndexError: list index out of range
```
This is with the latest master.

**Comment by tannisroot** [comment]
Might be caused by https://github.com/lutris/lutris/pull/1968 from @aTosser

**Comment by tannisroot** [comment]
oh wait, it's a dupe of https://github.com/lutris/lutris/issues/1969, my bad
