### ISSUE TITLE
Can't launch any games (backtrace is available)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1990]
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 501, in configure_game
    cwd=self.directory,
  File "/usr/lib/python3.7/site-packages/lutris/command.py", line 38, in __init__
    self.env = self.get_environment(env)
  File "/usr/lib/python3.7/site-packages/lutris/command.py", line 100, in get_environment
    key: value for key, value in env.iteritems() if "=" not in key
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by Riesi** [comment]
#1989 should fix this issue

**Comment by strycore** [comment]
Fixed in master
