### ISSUE TITLE
Can't remove games after just installing them on NTFS partition (backtrace is available)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2010]
How to reproduce:
1. Install the game onto an NTFS drive.
2. Launch the game
3. Click "Stop" to close it
4. Remove the game and tick both checkboxes
After that, a backtrace is printed:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/dialogs/uninstall_game.py", line 94, in on_apply_button_clicked
    remove_from_library = self.game.remove(remove_from_library, remove_contents)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 178, in remove
    self.runner.remove_game_data(game_path=self.directory)
  File "/usr/lib/python3.7/site-packages/lutris/runners/runner.py", line 358, in remove_game_data
    system.remove_folder(game_path)
  File "/usr/lib/python3.7/site-packages/lutris/util/system.py", line 200, in remove_folder
    shutil.rmtree(path)
  File "/usr/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 433, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 431, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'Battle.net.11060'
```
And the game obviously does not get removed until you restart Lutris.

**Comment by AaronOpfer** [comment]
Does this issue occur for all games or just the Battle.net game you're testing?

Does the issue still occur for the Battle.net game if, before uninstalling, you use the context menu option to force kill all wine processes?

**Comment by codeman101** [comment]
This is probably one of the reasons why it says in the instructions for games such as overwatch to not install it on NTFS.
