### ISSUE TITLE
Credential change on GOG

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2015]
When one's credential changed on GOG, and try to open the import games option it will refuse to open and dump this on the terminal:

```
Traceback (most recent call last):
  File "/src/lutris/lutris/util/http.py", line 74, in get
    request = urllib.request.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/lutris/lutris/gui/lutriswindow.py", line 187, in <lambda>
    "sync-local": Action(lambda *x: self.open_sync_dialog()),
  File "/src/lutris/lutris/gui/lutriswindow.py", line 500, in open_sync_dialog
    SyncServiceWindow(application=self.application)
  File "/src/lutris/lutris/gui/widgets/services.py", line 330, in __init__
    sync_row = ServiceSyncBox(service, self)
  File "/src/lutris/lutris/gui/widgets/services.py", line 53, in __init__
    self._connect_button_toggle()
  File "/src/lutris/lutris/gui/widgets/services.py", line 144, in _connect_button_toggle
    if self.service.is_connected():
  File "/src/lutris/lutris/services/gog.py", line 238, in is_connected
    return GOG_SERVICE.is_available()
  File "/src/lutris/lutris/services/gog.py", line 70, in is_available
    user_data = self.get_user_data()
  File "/src/lutris/lutris/services/gog.py", line 151, in get_user_data
    return self.make_api_request(url)
  File "/src/lutris/lutris/services/gog.py", line 141, in make_api_request
    self.request_token(refresh_token=token["refresh_token"])
  File "/src/lutris/lutris/services/gog.py", line 99, in request_token
    request.get()
  File "/src/lutris/lutris/util/http.py", line 79, in get
    raise HTTPError("Request to %s failed: %s" % (self.url, error))
```

Won't it be better (and more user friendly) ~~to silently delete the authorization cookie~~, one can add a confirmation box informing the user to the problem before deleting the offending cookie (or feeding the offending cookie to the Cookie Monster)

**Comment by strycore** [comment]
I've only prevented the crash for the moment but this will have to be improved so we show proper error messages to the user.

**Comment by mansakelabs** [comment]
I've written a script that moves the .gog.auth file in the ~/.cache/lutris directory into a ~/.cache/lutris/old folder. Lutris will open the Import Games menu and let you log in to GoG with your new credentials, which makes a new .gog.auth file.

https://www.dropbox.com/s/whoxen9hinkfhry/Lutris%20GoG%20fix.sh?dl=0
