### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2016]
Not sure why but getting this atm on the terminal:

```
ERROR    2019-04-09 13:57:46,802 [jobs.target:32]:Error while completing task <function sync_from_remote at 0x7f290e598f28>: database is locked
<class 'sqlite3.OperationalError'> database is locked
  File "/src/lutris/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/src/lutris/lutris/sync.py", line 94, in sync_from_remote
    updated = sync_game_details(remote_library)
  File "/src/lutris/lutris/sync.py", line 46, in sync_game_details
    local_game = pga.get_game_by_field(slug, "slug")
  File "/src/lutris/lutris/pga.py", line 238, in get_game_by_field
    game_result = sql.db_select(PGA_DB, "games", condition=(field, value))
  File "/src/lutris/lutris/util/sql.py", line 106, in db_select
    cursor_execute(cursor, query, params)
  File "/src/lutris/lutris/util/sql.py", line 30, in cursor_execute
    return cursor.execute(query, params)
ERROR    2019-04-09 13:58:07,108 [lutriswindow.on_sync_complete:308]:Sync failed: database is locked
Traceback (most recent call last):
  File "/src/lutris/lutris/gui/lutriswindow.py", line 309, in on_sync_complete
    added_games, removed_games = response
TypeError: 'NoneType' object is not iterable
```

**Comment by telanus** [comment]
OK found the culprit of this:

While I was busy fixing my credentials with GOG I inadvertently activated the sync on startup, thus each startup this happened, and rendered lutris incapable of starting

**Comment by strycore** [comment]
The fact that the database was locked is weird but the crash itself is fixed.
