### ISSUE TITLE
Unable to start or configure Linux game without a path

### ISSUE THREAD

**Issue by MinIsMin** [lutris/lutris#2019]
### Description
If adding a new game with the Linux runner and setting the executable to anything without a folder you are unable to start or configure it as there's an error.

example for executable:
`/usr/games/supertuxkart` works
`supertuxkart` doesn't work

### Steps to reproduce
- Add Game
- Select Linux runner
- set executable to anything without a path

### Console output

Create game and configure
```
DEBUG    2019-04-10 16:55:14,595 [game.save:212]:Saving S (linux)
DEBUG    2019-04-10 16:55:14,595 [config.save:208]:Saving LutrisConfig(level=game, game_config_id=s-1554908114, runner=linux) config to /home/user/.config/lutris/games/s-1554908114.yml
DEBUG    2019-04-10 16:55:14,667 [lutriswindow.on_game_updated:697]:Updating game S (linux)
DEBUG    2019-04-10 16:55:14,675 [store.get_missing_media:182]:Requesting missing icons from API for s
DEBUG    2019-04-10 16:55:14,677 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-04-10 16:55:14,829 [api.get_game_api_page:134]:No game found for s
DEBUG    2019-04-10 16:55:23,219 [game.save:212]:Saving S (linux)
DEBUG    2019-04-10 16:55:23,220 [config.save:208]:Saving LutrisConfig(level=game, game_config_id=s-1554908114, runner=linux) config to /home/user/.config/lutris/games/s-1554908114.yml
DEBUG    2019-04-10 16:55:23,280 [lutriswindow.on_game_updated:697]:Updating game S (linux)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 201, in on_edit_game_configuration
    EditGameConfigDialog(self.window, self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/edit_game.py", line 19, in __init__
    self.build_tabs("game")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 68, in build_tabs
    self._build_game_tab()
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 307, in _build_game_tab
    self.game_box = GameBox(self.lutris_config, self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 615, in __init__
    self.generate_widgets("game")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 90, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 185, in call_widget_generator
    self.generate_file_chooser(option, value)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 390, in generate_file_chooser
    path = os.path.join(self.game.directory, path)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Start game
```
DEBUG    2019-04-10 17:08:42,866 [application.launch:339]:Launching S (linux) (139894623350856)
DEBUG    2019-04-10 17:08:42,870 [display._get_vidmodes:15]:Retrieving video modes from XrandR
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 156, in on_game_run
    self.application.launch(self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 343, in launch
    game.play()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 277, in play
    self.configure_game(True)
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/linux.py", line 103, in play
    if not self.game_exe or not system.path_exists(self.game_exe):
  File "/usr/lib/python3/dist-packages/lutris/runners/linux.py", line 70, in game_exe
    exe_path = os.path.join(self.game_path, exe)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### System

Lutris version: 0.5.2

System: Ubuntu 18.10

**Comment by strycore** [comment]
It *shouldn't* work, Lutris can import system games from the import menu but is not designed to guess  executable paths from $PATH (and we don't plan making this possible).

I'll update the linux runner to handle those situations without crashes.

**Comment by MinIsMin** [comment]
Would it be possible to use something like `whereis -b supertuxkart`?
I know guessing is not the best but it works fine when just entering the executable.
