### ISSUE TITLE
Lutris 0.5.2 won't start on SuSe because ldconfig only accesible to root

### ISSUE THREAD

**Issue by kerozoli** [lutris/lutris#2025]
After 0.5.2 Lutris won't start on Suse (Thumbeweed) because it can't access ldconfig ( It's placed in /sbin/ ldconfig )

Error message:

Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 33, in <module>
    from lutris import pga
  File "/usr/lib/python3.7/site-packages/lutris/pga.py", line 10, in <module>
    from lutris.util import sql, system
  File "/usr/lib/python3.7/site-packages/lutris/util/system.py", line 10, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 371, in <module>
    LINUX_SYSTEM = LinuxSystem()
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 124, in __init__
    self.shared_libraries = self.get_shared_libraries()
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 285, in get_shared_libraries
    for lib_line in self.get_ldconfig_libs():
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 274, in get_ldconfig_libs
    output = subprocess.check_output(["ldconfig", "-p"]).decode("utf-8").split("\n")
  File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Nincs ilyen fájl vagy könyvtár: 'ldconfig': 'ldconfig'

**Comment by kerozoli** [comment]
Maybe this issue fixed with this commit :
https://github.com/lutris/lutris/commit/a4f04c5997b433ae77f78dec616886bff6d39e47

Please close if it already fixed.
Thanks

**Comment by kerozoli** [comment]
I updated the package to 0.5.2.1 and it's fixed the issue
Sorry for thee duplicated issue I didn'T check closed issues just the opened ones :)
