### ISSUE TITLE
Lutris fails to install libretro core (backtrace available)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2034]
From a user on Discord:

>Trying to get Lutris to run a Sega Master System game with libretro but I get this error output when it tries to install the core: 

```
DEBUG    2019-04-14 01:46:22,747 [application.launch:341]:Adding game Zillion (libretro) (140202294511080) to running games
DEBUG    2019-04-14 01:46:23,945 [runner.install:295]:Installing libretro (version=gearsystem, downloader=<function simple_downloader at 0x7f8377504620>, callback=None)
INFO     2019-04-14 01:46:23,945 [runner.get_runner_version:257]:Getting runner information for libretro(version: gearsystem)
DEBUG    2019-04-14 01:46:23,945 [http.get:68]:GET https://lutris.net/api/runners/libretro
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/game_actions.py", line 156, in on_game_run
    self.application.launch(self.game)
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 344, in launch
    game.play()
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 262, in play
    if not self.prelaunch():
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 235, in prelaunch
    installed = self.runner.install_dialog()
  File "/usr/lib/python3.7/site-packages/lutris/runners/runner.py", line 239, in install_dialog
    version=self.get_version(use_default=False))
  File "/usr/lib/python3.7/site-packages/lutris/runners/libretro.py", line 184, in install
    super(libretro, self).install(version, downloader, callback)
  File "/usr/lib/python3.7/site-packages/lutris/runners/runner.py", line 301, in install
    self.name, self.arch
lutris.runners.RunnerInstallationError: libretro is not available for the x86_64 architecture
```

**Comment by strycore** [comment]
Rewrote the error message and Lutris will now display an error dialog.
We should still package and ship gearsystem though.
