### ISSUE TITLE
When KWin has switched to a non-composit desktop and back to regular titles don't launch.

### ISSUE THREAD

**Issue by sankasan** [lutris/lutris#2049]
When developing in UE4 KWin switches the compositor off for performance reasons (my guess). Whenever that has happened any title I want to launch via Lutris, in this specific case Battle.net for Overwatch/Starcraft2, fails to launch.

```
#> lutris lutris:rungameid/63
2019-04-16 17:37:26,411: Running Lutris 0.5.2.1
2019-04-16 17:37:26,411: Using X.Org
2019-04-16 17:37:26,411: Running Mesa driver 19.0.2 on AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 5.0.7-arch1-1-ARCH, LLVM 8.0.0) (0x67df)
2019-04-16 17:37:26,411: GPU: 1002:67DF 1002:0B37 using amdgpu drivers
2019-04-16 17:37:26,460: Vulkan is supported
2019-04-16 17:37:26,461: Updating DXVK versions
2019-04-16 17:37:26,645: Connected to lutris.net as san
2019-04-16 17:37:27,719: Replacing /games/battle.net/drive_c/windows/system32/dxgi with DXVK version
2019-04-16 17:37:27,720: Replacing /games/battle.net/drive_c/windows/system32/d3d11 with DXVK version
2019-04-16 17:37:27,720: Replacing /games/battle.net/drive_c/windows/system32/d3d10core with DXVK version
2019-04-16 17:37:27,720: Replacing /games/battle.net/drive_c/windows/system32/d3d10_1 with DXVK version
2019-04-16 17:37:27,721: Replacing /games/battle.net/drive_c/windows/system32/d3d10 with DXVK version
2019-04-16 17:37:27,721: Replacing /games/battle.net/drive_c/windows/system32/d3d9 with DXVK version
2019-04-16 17:37:27,721: Replacing /games/battle.net/drive_c/windows/syswow64/dxgi with DXVK version
2019-04-16 17:37:27,721: Replacing /games/battle.net/drive_c/windows/syswow64/d3d11 with DXVK version
2019-04-16 17:37:27,722: Replacing /games/battle.net/drive_c/windows/syswow64/d3d10core with DXVK version
2019-04-16 17:37:27,722: Replacing /games/battle.net/drive_c/windows/syswow64/d3d10_1 with DXVK version
2019-04-16 17:37:27,722: Replacing /games/battle.net/drive_c/windows/syswow64/d3d10 with DXVK version
2019-04-16 17:37:27,723: Replacing /games/battle.net/drive_c/windows/syswow64/d3d9 with DXVK version
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 296, in configure_game
    display.get_outputs(), key=lambda e: e.name == system_config.get("display")
  File "/usr/lib/python3.7/site-packages/lutris/util/display.py", line 47, in get_outputs
    name, _, geometry, rotate, *_ = line.split()
ValueError: not enough values to unpack (expected at least 4, got 2)
```

**Comment by sankasan** [comment]
This doesn't really qualify as a fix, right? Do you want my xrandr output in order to fix it proper?
