### ISSUE TITLE
TypeError: sequence item 3: expected str instance, NoneType found

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#2068]
Issue reported via Discord. 

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/3100536/lutris-issue-report.zip)

```
DEBUG    2019-04-20 15:09:12,841 [application.launch:339]:Launching Deltarune (wine) (139673334310952)
DEBUG    2019-04-20 15:09:12,850 [game.play:269]:Prelaunching <lutris.runners.wine.wine object at 0x7f083bab1cf8>
INFO     2019-04-20 15:09:12,926 [dxvk.enable_dxvk_dll:128]:Replacing /run/media/acs/Games/Games/deltarune/drive_c/windows/system32/dxgi with DXVK version
INFO     2019-04-20 15:09:12,926 [dxvk.enable_dxvk_dll:128]:Replacing /run/media/acs/Games/Games/deltarune/drive_c/windows/system32/d3d11 with DXVK version
INFO     2019-04-20 15:09:12,926 [dxvk.enable_dxvk_dll:128]:Replacing /run/media/acs/Games/Games/deltarune/drive_c/windows/system32/d3d10core with DXVK version
INFO     2019-04-20 15:09:12,927 [dxvk.enable_dxvk_dll:128]:Replacing /run/media/acs/Games/Games/deltarune/drive_c/windows/system32/d3d10_1 with DXVK version
INFO     2019-04-20 15:09:12,927 [dxvk.enable_dxvk_dll:128]:Replacing /run/media/acs/Games/Games/deltarune/drive_c/windows/system32/d3d10 with DXVK version
INFO     2019-04-20 15:09:12,927 [dxvk.enable_dxvk_dll:128]:Replacing /run/media/acs/Games/Games/deltarune/drive_c/windows/system32/d3d9 with DXVK version
DEBUG    2019-04-20 15:09:12,928 [display._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2019-04-20 15:09:13,001 [game.configure_game:305]:Launching Deltarune: {'env': {'DRI_PRIME': '1', 'STEAM_RUNTIME': '/home/acs/.local/share/lutris/runtime/steam', 'LD_LIBRARY_PATH': '/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/lib:/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/lib64:/lib:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/home/acs/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/acs/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/i386/lib:/home/acs/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/i386/usr/lib:/home/acs/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/acs/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/amd64/lib:/home/acs/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH', 'WINEDEBUG': '-all', 'WINEARCH': 'win32', 'WINE': '/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/bin/wine', 'WINEPREFIX': '/run/media/acs/Games/Games/deltarune', 'WINEESYNC': '0', 'WINEDLLOVERRIDES': 'd3d10,d3d10_1,d3d10core,d3d11,dxgi=n'}, 'command': ['/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/bin/wine', '/run/media/acs/Games/Games/deltarune/drive_c/Program Files/SURVEY_PROGRAM/DELTARUNE.exe']}
DEBUG    2019-04-20 15:09:13,002 [game.configure_game:306]:Game info: {
  "env": {
    "DRI_PRIME": "1",
    "STEAM_RUNTIME": "/home/acs/.local/share/lutris/runtime/steam",
    "LD_LIBRARY_PATH": "/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/lib:/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/lib64:/lib:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/home/acs/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/acs/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/i386/lib:/home/acs/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/i386/usr/lib:/home/acs/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/acs/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/amd64/lib:/home/acs/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/acs/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH",
    "WINEDEBUG": "-all",
    "WINEARCH": "win32",
    "WINE": "/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/bin/wine",
    "WINEPREFIX": "/run/media/acs/Games/Games/deltarune",
    "WINEESYNC": "0",
    "WINEDLLOVERRIDES": "d3d10,d3d10_1,d3d10core,d3d11,dxgi=n"
  },
  "command": [
    "/home/acs/.local/share/lutris/runners/wine/tkg-4.0-x86_64/bin/wine",
    "/run/media/acs/Games/Games/deltarune/drive_c/Program Files/SURVEY_PROGRAM/DELTARUNE.exe"
  ]
}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/lutris/game.py", line 508, in configure_game
    self.start_game()
  File "/usr/lib/python3.6/site-packages/lutris/game.py", line 522, in start_game
    self.game_thread.start()
  File "/usr/lib/python3.6/site-packages/lutris/command.py", line 111, in start
    logger.debug("Running %s", " ".join(self.wrapper_command))
TypeError: sequence item 3: expected str instance, NoneType found
WARNING  2019-04-20 15:10:55,551 [game_actions.on_stop:169]:734 not in running game list
WARNING  2019-04-20 15:10:57,340 [game_actions.on_stop:169]:734 not in running game list
Gtk-Message: 15:10:58.597: GtkDialog mapped without a transient parent. This is discouraged.
INFO     2019-04-20 15:11:00,895 [application.do_shutdown:440]:Shutting down Lutris
```

**Comment by isugimpy** [comment]
@AccountOneOff Happen to know what Lutris version this is for?  This behavior could be expected prior to https://github.com/lutris/lutris/commit/9fd40ab97cf995b4b104bd3643ffe1b6a2c4dcc3 which is included in v0.5.2.1.

**Comment by AccountOneOff** [comment]
I don't know and I don't remember who reported it.

**Comment by isugimpy** [comment]
Found it:  https://paste.ubuntu.com/p/mxBwzgTZNd/ reported by Jocie (duke86fan)#3015.  Running v0.5.2.  Pretty sure this is a fixed issue and can be closed.

**Comment by Tarcaxoxide** [comment]
having this issue on 0.5.4
except its
"sequence item 1"
not
"sequence item 3"
