### ISSUE TITLE
Lutris won't run on ubuntu 16.04 LTS [SOLVED]

### ISSUE THREAD

**Issue by LowlyDev** [lutris/lutris#2074]
When I open lutris with a shortcut file nothing happens, but when I try in terminal I get this error message: 
`Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 33, in <module>
    from lutris import pga
  File "/usr/lib/python3/dist-packages/lutris/pga.py", line 10, in <module>
    from lutris.util import sql, system
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 10, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 371, in <module>
    LINUX_SYSTEM = LinuxSystem()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 124, in __init__
    self.shared_libraries = self.get_shared_libraries()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 285, in get_shared_libraries
    for lib_line in self.get_ldconfig_libs():
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 274, in get_ldconfig_libs
    output = subprocess.check_output(["ldconfig", "-p"]).decode("utf-8").split("\n")
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'
(xenial)micah@localhost:~$ ldconfig
bash: ldconfig: command not found
(xenial)micah@localhost:~$ sudo ldconfig
[sudo] password for micah: 
(xenial)micah@localhost:~$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 33, in <module>
    from lutris import pga
  File "/usr/lib/python3/dist-packages/lutris/pga.py", line 10, in <module>
    from lutris.util import sql, system
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 10, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 371, in <module>
    LINUX_SYSTEM = LinuxSystem()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 124, in __init__
    self.shared_libraries = self.get_shared_libraries()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 285, in get_shared_libraries
    for lib_line in self.get_ldconfig_libs():
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 274, in get_ldconfig_libs
    output = subprocess.check_output(["ldconfig", "-p"]).decode("utf-8").split("\n")
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'
`

**Comment by LowlyDev** [comment]
found a way to fix, if I open the terminal and run `sudo lutris` it works fine

**Comment by AccountOneOff** [comment]
That is not a valid solution. Lutris should never be run with sudo. I suggest you purge Lutris and reinstall. If you still get the same error reopen this ticket.

**Comment by strycore** [comment]
Still, people should have the freedom to shoot themselves in the foot if they so choose to.

(This is an old version of lutris. Current one won't crash if ldconfig isn't detected, the ticket can stay closed)

**Comment by LowlyDev** [comment]
I mean if it's working why re-install? what's wrong with using sudo to run lutris?

**Comment by strycore** [comment]
Everything is wrong with using sudo to run GUI applications. If you want to go and kill your system then do it, I'm not your mom.
