### ISSUE TITLE
Lutris Detects Flatpaked Steam Games But Does Not Launch Them

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#2086]
Lutris correctly detects all games from within the Steam Flatpak but when double click on any of them, Lutris instead asks me if I want to install the runner for these games (which is already installed as a flatpak bundle but not natively on the system) and has no mechanism of launching flatpak Steam itself.

**Comment by tannisroot** [comment]
Would you mind reproducing this issue with Lutris ran in terminal with `lutris -d`  and sharing the logs? I am curious whether this issue produces any backtraces.

**Comment by Pixeliz3d** [comment]
I'm also getting this error

logs:
```
$ lutris -d                                                                                                                                                                                                                                                                    
INFO     2020-04-20 15:51:33,398 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-04-20 15:51:33,398 [startup.check_driver:54]:Using NVIDIA drivers 440.82 for x86_64
INFO     2020-04-20 15:51:33,398 [startup.check_driver:60]:GPU: GeForce GTX 980
INFO     2020-04-20 15:51:33,399 [startup.check_driver:77]:GPU: 10DE:13C0 1458:367C using nvidia drivers
INFO     2020-04-20 15:51:33,416 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-04-20 15:51:33,416 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-04-20 15:51:33,643 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-04-20 15:51:38,555 [application.launch:379]:Launching Grand Theft Auto V (steam) (140665201372288)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/game_actions.py", line 187, in on_game_run
    self.application.launch(self.game)
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 384, in launch
    game.play()
  File "/usr/lib/python3.8/site-packages/lutris/game.py", line 302, in play
    if not self.is_launchable():
  File "/usr/lib/python3.8/site-packages/lutris/game.py", line 272, in is_launchable
    installed = self.runner.install_dialog()
  File "/usr/lib/python3.8/site-packages/lutris/runners/runner.py", line 270, in install_dialog
    self.install(downloader=simple_downloader)
  File "/usr/lib/python3.8/site-packages/lutris/runners/steam.py", line 269, in install
    raise NonInstallableRunnerError(
lutris.runners.NonInstallableRunnerError: Steam for Linux installation is not handled by Lutris.
```

**Comment by Pixeliz3d** [comment]
I found workaround

Create file `/usr/local/bin/steam` with this content:
```
#!/usr/bin/env bash
flatpak run com.valvesoftware.Steam $@
```

Now launching steam flatpak games from lutris works.

**Comment by strycore** [comment]
> Create file /usr/local/bin/steam with this content

I seriously wish Flatpak would create those kind of scripts by default. This is one of the biggest drawbacks of Flatpak.

**Comment by strycore** [comment]
With the latest commits, there's improved support for Flatpak runners. I was able to launch a Steam game from Lutris with only having the Flatpak version of Steam installed.

Note: I had some issues with Gamemode enabled so it might be necessary to disable that by default.

**Comment by CuriousApe2020** [comment]
Could this please be documented in the Wiki and be displayed as an error message?
