### ISSUE TITLE
ProcessLookupError: [Errno 3] No such process

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2142]
Reported by multiple users on Discord (I think this gets printed after they try to stop a game?).
As there is `lutris-wrapper` involed, I should notify @AaronOpfer.
```Traceback (most recent call last):
  File "/usr/bin/lutris-wrapper", line 130, in <module>
    main()
  File "/usr/bin/lutris-wrapper", line 103, in main
    returncode = subprocess.run(args).returncode
  File "/usr/lib/python3.7/subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 931, in communicate
    self.wait()
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/usr/bin/lutris-wrapper", line 85, in hard_sig_handler
    os.kill(child.pid, signal.SIGKILL)
ProcessLookupError: [Errno 3] No such process```

**Comment by AaronOpfer** [comment]
Thanks for the report.
