### ISSUE TITLE
Discord RPC connection: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2163]
When you run Lutris with the new DRP (Discord Rich Presence) addition, while not having discord open the following gets dumped on the terminal:

```
ERROR    2019-05-25 11:34:23,751 [discord.ensure_discord_disconnected:61]:Unable to close Discord RPC connection: 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "/src/lutris/lutris/discord.py", line 47, in ensure_discord_connected
    self.rpc_client.connect()
  File "/.local/lib/python3.6/site-packages/pypresence/presence.py", line 40, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/.local/lib/python3.6/site-packages/pypresence/baseclient.py", line 102, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/lutris/lutris/discord.py", line 59, in ensure_discord_disconnected
    self.rpc_client.close()
  File "/.local/lib/python3.6/site-packages/pypresence/presence.py", line 43, in close
    self.send_data(2, {'v': 1, 'client_id': self.client_id})
  File "/.local/lib/python3.6/site-packages/pypresence/baseclient.py", line 93, in send_data
    self.sock_writer.write(
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by isugimpy** [comment]
So, what you just hit here is why I had the log lines in in ensure_discord_connected and ensure_discord_disconnected set as a mix of debug and error rather than exception.  They were changed by another dev to fully raise the exceptions.  I think the older version provides a better user experience, as raising the actual exception doesn't benefit the user.  Perhaps we could revert them to the previous format.
