### ISSUE TITLE
Lutris Crashes Outright, doesn't get to gui

### ISSUE THREAD

**Issue by Thorhian** [lutris/lutris#2181]
After installing lutris on Arch Linux from the official Arch repos, the python code crashes upon starting the application and I never see the GUI or anything except the Traceback when lutris is ran from the terminal. After google searches I cannot figure this out for some reason.

I am running Arch Linux on a laptop that has both Intel Integrated Graphics and an Nvidia 940MX. 

```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 33, in <module>
    from lutris import pga
  File "/usr/lib/python3.7/site-packages/lutris/pga.py", line 10, in <module>
    from lutris.util import sql, system
  File "/usr/lib/python3.7/site-packages/lutris/util/system.py", line 10, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 374, in <module>
    LINUX_SYSTEM = LinuxSystem()
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 125, in __init__
    self.populate_libraries()
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 300, in populate_libraries
    for req in self.requirements:
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 216, in requirements
    return self.get_requirements()
  File "/usr/lib/python3.7/site-packages/lutris/util/linux.py", line 245, in get_requirements
    if drivers.is_amd():
  File "/usr/lib/python3.7/site-packages/lutris/util/graphics/drivers.py", line 80, in is_amd
    if get_gpu_info(card)["DRIVER"] == "amdgpu":
  File "/usr/lib/python3.7/site-packages/lutris/util/graphics/drivers.py", line 64, in get_gpu_info
    with open("/sys/class/drm/%s/device/uevent" % card) as card_uevent:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card1/device/uevent'
```
Any attempt to run the submit issue command argument with lutris fails and returns the same traceback before it can actually fulfill the command.

**Comment by vahtos** [comment]
If you cd to 

> /sys/class/drm/card1

What is in that folder? You should see a file called uevent that has contents similar to:

```
DRIVER=vboxvideo
PCI_CLASS=30000
PCI_ID=80EE:BEEF
PCI_SUBSYS_ID=0000:0000
PCI_SLOT_NAME=0000:00:02.0
MODALIAS=pci:v000080EEd0000BEEFsv00000000sd00000000bc03sc00i00
```

**Comment by Thorhian** [comment]
card1 in that folder is a broken symlink. :/ The folder it is supposed to point to doesn't exist. I do use nvidia-xrun since it seems to work better than bumblebee, and even then I've had to deal with some glitches, including the fact that the GPU won't turn off after ending the x-session. I have to reboot entirely. I think that has to do with the fact that the Nvidia 940MX doesn't play nicely with Bumblebee or Nvidia-Xrun.

**Comment by vahtos** [comment]
I think you are right and that sounds like an issue with your graphics card/driver configuration and not a bug in Lutris. Unfortunately, I do not know enough about bumblebee and Nvidia-Xrun etc to help you with that.

**Comment by Thorhian** [comment]
Is there any way to simply run lutris without it trying to to do anything with my discrete GPU? This is the only application I’ve tried using that seems to fail because of this.
