### ISSUE TITLE
Can't enable DXVK, output "TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'

### ISSUE THREAD

**Issue by Dakai** [lutris/lutris#2197]
**Describe the bug**

Hi, I followed every step in the wiki on installing DXVK on my Manjaro system, the spec is Intel i3-3450 and AMD Radeon HD7870, and I want to play the World of Warcraft Vanilla version with Lutris, I found The DXVK is unable to activated.

**Expected behavior**
Expected to enable DXVK normally.

**Current behavior**
The DXVK is unable to activated.

**Steps to reproduce**
When I try to enable the DXVK in the runner options, there is no error at all, but after I save the option and re-open the setting menu, the Enable DXVK option was back to disabled again.

**Lutris debugging output**
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/util/jobs.py", line 44, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'
Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.
```

**System information**
```
{
  "comment": "Hi, I followed every step in the wiki on installing DXVK on my Manjaro system, the spec is Intel i3-3450 and AMD Radeon HD7870, and I want to play the World of Warcraft Vanilla version with Lutris, I found The DXVK is unable to activated.",
  "system": {
    "gpus": [
      {
        "DRIVER": "radeon",
        "PCI_ID": "1002:6818",
        "PCI_SUBSYS_ID": "174B:E241",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:01:00.0",
        "MODALIAS": "pci:v00001002d00006818sv0000174Bsd0000E241bc03sc00i00"
      }
    ],
    "env": {
      "COLORFGBG": "15;0",
      "COLORTERM": "truecolor",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
      "DESKTOP_SESSION": "/usr/share/xsessions/plasma",
      "DISPLAY": ":0",
      "GS_LIB": "/home/dakai/.fonts",
      "GTK2_RC_FILES": "/etc/gtk-2.0/gtkrc:/home/dakai/.gtkrc-2.0:/home/dakai/.config/gtkrc-2.0",
      "GTK_IM_MODULE": "fcitx",
      "GTK_MODULES": "canberra-gtk-module:appmenu-gtk-module",
      "GTK_RC_FILES": "/etc/gtk/gtkrc:/home/dakai/.gtkrc:/home/dakai/.config/gtkrc",
      "HOME": "/home/dakai",
      "KDE_FULL_SESSION": "true",
      "KDE_SESSION_UID": "1000",
      "KDE_SESSION_VERSION": "5",
      "KONSOLE_DBUS_SERVICE": ":1.32",
      "KONSOLE_DBUS_SESSION": "/Sessions/1",
      "KONSOLE_PROFILE_NAME": "Shell",
      "KONSOLE_VERSION": "190402",
      "LANG": "en_US.UTF-8",
      "LANGUAGE": "",
      "LC_ADDRESS": "zh_CN.UTF-8",
      "LC_IDENTIFICATION": "zh_CN.UTF-8",
      "LC_MEASUREMENT": "zh_CN.UTF-8",
      "LC_MONETARY": "zh_CN.UTF-8",
      "LC_NAME": "zh_CN.UTF-8",
      "LC_NUMERIC": "zh_CN.UTF-8",
      "LC_PAPER": "zh_CN.UTF-8",
      "LC_TELEPHONE": "zh_CN.UTF-8",
      "LC_TIME": "zh_CN.UTF-8",
      "LOGNAME": "dakai",
      "MAIL": "/var/spool/mail/dakai",
      "MOZ_PLUGIN_PATH": "/usr/lib/mozilla/plugins",
      "OLDPWD": "/home/dakai",
      "PAM_KWALLET5_LOGIN": "/run/user/1000/kwallet5.socket",
      "PATH": "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/dakai/.fzf/bin",
      "PROFILEHOME": "",
      "PWD": "/home/dakai",
      "QT_AUTO_SCREEN_SCALE_FACTOR": "0",
      "QT_IM_MODULE": "fcitx",
      "QT_LINUX_ACCESSIBILITY_ALWAYS_ON": "1",
      "SESSION_MANAGER": "local/dakai-pc:@/tmp/.ICE-unix/915,unix/dakai-pc:/tmp/.ICE-unix/915",
      "SHELL": "/bin/zsh",
      "SHELL_SESSION_ID": "7cd2c4a5fa134218b1883dbdb961905c",
      "SHLVL": "2",
      "TERM": "xterm-256color",
      "UBUNTU_MENUPROXY": "1",
      "USER": "dakai",
      "WINDOWID": "48234503",
      "XAUTHORITY": "/tmp/xauth-1000-_0",
      "XCURSOR_SIZE": "0",
      "XCURSOR_THEME": "breeze_cursors",
      "XDG_CURRENT_DESKTOP": "KDE",
      "XDG_DATA_DIRS": "/home/dakai/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "XDG_SEAT": "seat0",
      "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
      "XDG_SESSION_CLASS": "user",
      "XDG_SESSION_DESKTOP": "KDE",
      "XDG_SESSION_ID": "2",
      "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session1",
      "XDG_SESSION_TYPE": "x11",
      "XDG_VTNR": "1",
      "XMODIFIERS": "im=fcitx",
      "_": "/usr/bin/lutris",
      "ZSH": "/home/dakai/.oh-my-zsh",
      "PAGER": "less",
      "LESS": "-R",
      "LC_CTYPE": "en_US.UTF-8",
      "LSCOLORS": "Gxfxcxdxbxegedabagacad",
      "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [
          "libgamemodeauto.so"
        ],
        [
          "libgamemodeauto.so"
        ]
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "58",
        "model name": "Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz",
        "stepping": "9",
        "microcode": "0x21",
        "cpu MHz": "1829.241",
        "cache size": "6144 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds",
        "bogomips": "6188.06",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "1",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "58",
        "model name": "Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz",
        "stepping": "9",
        "microcode": "0x21",
        "cpu MHz": "1859.038",
        "cache size": "6144 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds",
        "bogomips": "6188.06",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "2",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "58",
        "model name": "Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz",
        "stepping": "9",
        "microcode": "0x21",
        "cpu MHz": "1813.142",
        "cache size": "6144 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "2",
        "cpu cores": "4",
        "apicid": "4",
        "initial apicid": "4",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds",
        "bogomips": "6188.06",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "3",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "58",
        "model name": "Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz",
        "stepping": "9",
        "microcode": "0x21",
        "cpu MHz": "1764.317",
        "cache size": "6144 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "3",
        "cpu cores": "4",
        "apicid": "6",
        "initial apicid": "6",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds",
        "bogomips": "6188.06",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sda1",
            "fstype": "vfat",
            "label": null,
            "uuid": "4B8E-7EB0",
            "fsavail": "299.1M",
            "fsuse%": "0%",
            "mountpoint": "/boot/efi"
          },
          {
            "name": "sda2",
            "fstype": "ext4",
            "label": null,
            "uuid": "39d88f81-8978-45f9-86ff-af56fd56acdd",
            "fsavail": "38.4G",
            "fsuse%": "56%",
            "mountpoint": "/"
          },
          {
            "name": "sda3",
            "fstype": "swap",
            "label": null,
            "uuid": "4f15fc82-a43a-4ccc-adf5-9ec4ccb8d12e",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": "[SWAP]"
          }
        ]
      },
      {
        "name": "sdb",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdb1",
            "fstype": "ext4",
            "label": "HDD-ext4",
            "uuid": "c8277d98-2bb4-4c2a-ae6a-d05871c2789f",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": "/run/media/root/HDD-ext4"
          }
        ]
      },
      {
        "name": "sdc",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdc1",
            "fstype": "ntfs",
            "label": "SSD",
            "uuid": "AC128A31128A0116",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          },
          {
            "name": "sdc2",
            "fstype": "ntfs",
            "label": null,
            "uuid": "D8A04F76A04F59E0",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sdd",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdd1",
            "fstype": null,
            "label": null,
            "uuid": null,
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          },
          {
            "name": "sdd5",
            "fstype": "ntfs",
            "label": "DK-Apps",
            "uuid": "4E80B0D06C979E44",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          },
          {
            "name": "sdd6",
            "fstype": "ntfs",
            "label": "DK-Entertain",
            "uuid": "B0A18DDEEC101C79",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          },
          {
            "name": "sdd7",
            "fstype": "ntfs",
            "label": "DK-BACKUP",
            "uuid": "02F5A88B6AC74F10",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sde",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sde1",
            "fstype": null,
            "label": null,
            "uuid": null,
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          },
          {
            "name": "sde5",
            "fstype": "ntfs",
            "label": "Janny HDD2",
            "uuid": "7844C1DE44C19F6E",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          },
          {
            "name": "sde6",
            "fstype": "ntfs",
            "label": "Janny-HDD3",
            "uuid": "66A4CEF2A4CEC3B1",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          }
        ]
      }
    ],
    "ram": {
      "mem": {
        "total": "16369992",
        "used": "5467768",
        "free": "582772",
        "shared": "397852",
        "buff/cache": "10319452",
        "available": "10258084"
      },
      "swap": {
        "total": "18006880",
        "used": "14080",
        "free": "17992800"
      }
    },
    "dist": [
      "Manjaro Linux",
      "18.0.4",
      "Illyria"
    ],
    "glxinfo": {
      "screen": "0",
      "opengl_core_profile_version": "4.5 (Core Profile) Mesa 19.0.6",
      "opengl_core_profile_shading_language_version": "4.50",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "opengl_es_profile_version": "OpenGL ES 3.2 Mesa 19.0.6",
      "name_of_display": ":0",
      "opengl_renderer": "AMD PITCAIRN (DRM 2.50.0, 4.19.49-1-MANJARO, LLVM 8.0.0)",
      "opengl_context_flags": "(none)",
      "opengl_core_profile_context_flags": "(none)",
      "opengl_shading_language_version": "4.50",
      "opengl_core_profile_profile_mask": "core profile",
      "opengl_version": "4.5 (Compatibility Profile) Mesa 19.0.6",
      "opengl_profile_mask": "compatibility profile",
      "display": ":0",
      "direct_rendering": "Yes",
      "opengl_vendor": "X.Org"
    }
  }
}
```
**Screenshots**

**Comment by bbarnes11** [comment]
How did you resolve this, i'm having the same issue with the DXVK toggle

**Comment by Dakai** [comment]
I changed the GPU driver from radeon to amdgpu, then the DXVK can be turned on, however, the operation seems to involve with the kernel and my ethernet was down by the changing of the gpu driver, so I had to give up and use the radeon back, please be cautious and make the system backup before changing it. (Timeshift is the wonderful tool to backup a linux system)

Basically, you just need to follow the installation section in [AMDGPU - ArchWiki ](https://wiki.archlinux.org/index.php/AMDGPU) and then generate the boot image with mkinicpio command:
`mkinitcpio -p linux`
and if the command failed to load preset, you need to `ls /etc/mkinitcpio.d` to see what the actual preset name is, mine is `linux419.preset` so the command should be 
`mkinitcpio -p linux419`

After a bunch of terminal output, just reboot and use `inxi -G` to check if the driver is **amdgpu**

```
Graphics:  Device-1: AMD Pitcairn XT [Radeon HD 7870 GHz Edition] driver: radeon v: kernel 
           Display: x11 server: X.Org 1.20.5 driver: radeon FAILED: ati unloaded: modesetti
           resolution: 1920x1200~60Hz, 1680x1050~60Hz 
           OpenGL: renderer: AMD PITCAIRN (DRM 2.50.0 4.19.49-1-MANJARO LLVM 8.0.0) 
           v: 4.5 Mesa 19.1.1 
```
use `vulkaninfo` to see if it give some outputs of the vulkan driver, then just open lutris and turn on the DXVK.

**Comment by imsys** [comment]
I got the same problem and I think there should be a way to this work with the Radeon driver.

**Comment by Dakai** [comment]
I wish there is way to make it work with Radeon Driver, but so far, I
haven't found anything.

**Comment by edenprojectde** [comment]
Im on Nvidea and i got the same error happening.
```2019-11-19 09:39:31,211: Updating DXVK versions
2019-11-19 09:39:31,819: Updating D9VK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 44, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_bin_lutris.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 44, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 44, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_bin_lutris.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 44, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 44, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_bin_lutris.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 44, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'```
