### ISSUE TITLE
Wine-tkg-protonified extraction error

### ISSUE THREAD

**Issue by pumkinpal** [lutris/lutris#2234]
**Describe the bug**

I recently went to install the game "Sim City 4 Deluxe Edition" via GOG and the install kept failing as Lutris was unable to extract the wine-tkg-protonified-4.1-x86_64.tar.gz archive. I was also unable to manually extract the archive.

Extraction of the archive "wine-tkg-protonified-4.1-x86_64.tar.gz" fails during decompression due to an invalid distance code

**Expected behavior**

I expected the game to finish installing without any errors.

**Current behavior**

The game stops installing after "wine-tkg-protonified-4.1-x86_64.tar.gz" finishes downloading and an error pops up.

**Steps to reproduce**

- Try to install Sim City 4 Deluxe Edition via GOG.
- Error should occur after downloading of "wine-tkg-protonified-4.1-x86_64.tar.gz" finishes.

**Lutris debugging output**

```
INFO     2019-07-15 12:24:19,740 [application.do_command_line:225]:Running Lutris 0.5.2.2
INFO     2019-07-15 12:24:19,741 [startup.check_driver:54]:Using NVIDIA drivers 430.26 for x86_64
INFO     2019-07-15 12:24:19,741 [startup.check_driver:58]:GPU: GeForce GTX 770
INFO     2019-07-15 12:24:19,741 [startup.check_driver:75]:GPU: 10DE:1184 1458:3603 using nvidia drivers
INFO     2019-07-15 12:24:19,827 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-07-15 12:24:19,827 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
INFO     2019-07-15 12:24:19,971 [lutriswindow.toggle_connection:562]:Connected to lutris.net as pumpkinpal
DEBUG    2019-07-15 12:24:19,972 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-07-15 12:24:19,972 [http.get:68]:GET https://lutris.net/api/games/library/pumpkinpal
DEBUG    2019-07-15 12:24:23,400 [interpreter.fetch_script:54]:Fetching installer https://lutris.net/api/installers/simcity-4-deluxe
DEBUG    2019-07-15 12:24:23,401 [http.get:68]:GET https://lutris.net/api/installers/simcity-4-deluxe
DEBUG    2019-07-15 12:24:27,196 [interpreter.check_runner_install:440]:Required runners: [<lutris.runners.wine.wine object at 0x7f095d346c18>]
DEBUG    2019-07-15 12:24:27,197 [commands._get_runner_version:37]:Install script uses Wine tkg-protonified-4.1-x86_64
DEBUG    2019-07-15 12:24:27,197 [interpreter.check_runner_install:465]:Runner %s needs to be installed
DEBUG    2019-07-15 12:24:27,200 [interpreter.install_runner:481]:Installing wine
DEBUG    2019-07-15 12:24:27,200 [commands._get_runner_version:37]:Install script uses Wine tkg-protonified-4.1-x86_64
DEBUG    2019-07-15 12:24:27,200 [runner.install:295]:Installing wine (version=tkg-protonified-4.1-x86_64, downloader=<bound method InstallerWindow.start_download of <installerwindow.InstallerWindow object at 0x7f095753d318 (lutris+gui+installerwindow+InstallerWindow at 0x55ae8ee7e880)>>, callback=<bound method ScriptInterpreter.install_runners of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f095706e7f0>>)
INFO     2019-07-15 12:24:27,200 [runner.get_runner_version:257]:Getting runner information for wine(version: tkg-protonified-4.1-x86_64)
DEBUG    2019-07-15 12:24:27,201 [http.get:68]:GET https://lutris.net/api/runners/wine
DEBUG    2019-07-15 12:24:29,764 [installerwindow.start_download:307]:Downloading https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-4.1-x86_64.tar.gz to /home/martin/.cache/lutris/wine-tkg-protonified-4.1-x86_64.tar.gz
DEBUG    2019-07-15 12:24:29,765 [downloader.start:55]:Starting download of:
 https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-4.1-x86_64.tar.gz
DEBUG    2019-07-15 12:24:59,719 [downloader.on_done:97]:Finished downloading https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-4.1-x86_64.tar.gz
DEBUG    2019-07-15 12:24:59,824 [extract.extract_archive:68]:Extracting /home/martin/.cache/lutris/wine-tkg-protonified-4.1-x86_64.tar.gz to /home/martin/.local/share/lutris/runners/wine/tkg-protonified-4.1-x86_64
ERROR    2019-07-15 12:25:02,236 [extract.extract_archive:111]:Extraction failed: Error -3 while decompressing data: invalid distance code
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 109, in extract_archive
    _do_extract(path, temp_path, opener, mode, extractor)
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 154, in _do_extract
    handler.extractall(dest)
  File "/usr/lib64/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib64/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib64/python3.7/tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python3.7/tarfile.py", line 2163, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib64/python3.7/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/usr/lib64/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid distance code
ERROR    2019-07-15 12:25:02,237 [runner.extract:344]:Failed to extract the archive /home/martin/.cache/lutris/wine-tkg-protonified-4.1-x86_64.tar.gz file may be corrupt
ERROR    2019-07-15 12:25:02,237 [errors.__init__:15]:Failed to extract /home/martin/.cache/lutris/wine-tkg-protonified-4.1-x86_64.tar.gz: Error -3 while decompressing data: invalid distance code
None
DEBUG    2019-07-15 12:25:06,157 [interpreter.revert:732]:Install cancelled
DEBUG    2019-07-15 12:25:06,158 [downloader.cancel:74]:Download of https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-4.1-x86_64.tar.gz cancelled
```

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

https://paste.ubuntu.com/p/HH6bJMPyNC/

**Comment by Medath** [comment]
Have you tried this multiple times? Maybe the file got corrupted during download, retrying might fix this

**Comment by pumkinpal** [comment]
I have retried 5+ times over the last 2 weeks including just now, and I still get the same problem.

**Comment by Medath** [comment]
Can you try downloading https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-4.1-x86_64.tar.gz with your browser, then opening a terminal in the download folder and running `sha256sum wine-tkg-protonified-4.1-x86_64.tar.gz && tar xf wine-tkg-protonified-4.1-x86_64.tar.gz`?

**Comment by pumkinpal** [comment]
`sha256sum wine-tkg-protonified-4.1-x86_64.tar.gz && tar xf wine-tkg-protonified-4.1-x86_64.tar.gz 
6cca23051e648bf9f94911ebca7157579de7f4a9061980291088c80b0cda7370  wine-tkg-protonified-4.1-x86_64.tar.gz

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
`
This is the output i get when I run the aforementioned commands.

**Comment by Medath** [comment]
Interesting, you seem to be getting another file than me from the same download link. Can you try again by opening a terminal in an empty directory and running `wget https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-4.1-x86_64.tar.gz && sha256sum wine-tkg-protonified-4.1-x86_64.tar.gz && tar xvf wine-tkg-protonified-4.1-x86_64.tar.gz` and posting the entire output here once it's done?

**Comment by pumkinpal** [comment]
Here is the whole output:
https://paste.ubuntu.com/p/K7y7JX4n7F/

**Comment by tannisroot** [comment]
Where are you from (country)?

**Comment by pumkinpal** [comment]
I’m downloading from Sydney, Australia

**Comment by tannisroot** [comment]
I've purged CDN cache for these builds. Can you try again?

**Comment by pumkinpal** [comment]
It seems to work now. Thanks a lot :).
