### ISSUE TITLE
Lutris no longer shows installation completion message

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2305]
```
Traceback (most recent call last):
  File "/home/alex/git_projects/lutris/lutris/installer/interpreter.py", line 567, in _iter_commands
    self._finish_install()
  File "/home/alex/git_projects/lutris/lutris/installer/interpreter.py", line 613, in _finish_install
    self.parent.on_install_finished()
  File "/home/alex/git_projects/lutris/lutris/gui/installerwindow.py", line 438, in on_install_finished
    game = Game(game_data["id"])
KeyError: 'id'
```
caused by https://github.com/lutris/lutris/commit/c867322fe006cbca3abf476db3b330d5deebdb1a from @Medath.

**Comment by tannisroot** [comment]
should be fixed now
