### ISSUE TITLE
on_install_finished KeyError: 'id'

### ISSUE THREAD

**Issue by KartoffelCheetah** [lutris/lutris#2327]
**Describe the bug**

After the [Dark Mod](https://lutris.net/games/the-dark-mod/) installation Ubuntu Crash Reporter window opens showing an error message (pasted below).

**Expected behavior**

Do not throw error.

**Current behavior**

Error message:
```python
 Traceback:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 420, in _monitor_task
      self._iter_commands()
    File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 567, in _iter_commands
      self._finish_install()
    File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 613, in _finish_install
      self.parent.on_install_finished()
    File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 437, in on_install_finished
       game = Game(game_data["id"])
  KeyError: 'id'
```
https://github.com/lutris/lutris/blob/06afbc4ce4647d7956fd53d2cec71f125f8bfd7b/lutris/gui/installerwindow.py#L437
which i assume happened because `get_game_by_field` can return an `empty dictionary` in case of no game_results from the `PGA_DB`.
https://github.com/lutris/lutris/blob/06afbc4ce4647d7956fd53d2cec71f125f8bfd7b/lutris/pga.py#L234
Lutris itself continued running fine. After the error occured a usual window appeared about desktop shortcuts and the game appeared in the list of installed games. (Thought I haven't got the time to try it yet).

**Steps to reproduce**

- Install Dark Mod (it's pretty long)
- Wait until installation finishes...

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

Lutris: 0.5.3
Ubuntu: 18.04
Python 3.6.8

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by baryluk** [comment]
Same here when launching Battle.net installed via overwatch lutris installer:

```
00ea:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!
0054:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032FE9C
2019-10-28 20:08:28,101: Unable to read stat for process 2027
2019-10-28 20:08:28,101: Unable to read stat for process 2027
All children gone
Exit with returncode 0
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 567, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 613, in _finish_install
    self.parent.on_install_finished()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 437, in on_install_finished
    game = Game(game_data["id"])
KeyError: 'id'
sh: 0: getcwd() failed: No such file or directory
gtk-update-icon-cache: Cache file created successfully.
2019-10-28 20:08:51,900: Replacing /home/user/Games/overwatch/drive_c/windows/system32/dxgi with DXVK version
...
```

Debian testing amd64
