### ISSUE TITLE
GOG installers no longer work

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2353]
If you try to install a GOG game, the installation gets completely stuck. This affects **all** GOG installers:
![image](https://user-images.githubusercontent.com/10602045/64977823-d164b480-d8bc-11e9-9ac6-1bb130a11a1b.png)
Backtrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/installerwindow.py", line 239, in on_installer_selected
    self.prepare_install(installer_slug)
  File "/usr/lib/python3.7/site-packages/lutris/gui/installerwindow.py", line 197, in prepare_install
    self.interpreter = interpreter.ScriptInterpreter(install_script, self)
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 147, in __init__
    for file_desc in self.script.get("files", [])
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 148, in <listcomp>
    for file_id, file_meta in file_desc.items()
  File "/usr/lib/python3.7/site-packages/lutris/installer/installer_file.py", line 29, in __init__
    self.filename = os.path.basename(file_meta)
  File "/usr/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by tannisroot** [comment]
Doesn't seem like I can reproduce this anymore.
