### ISSUE TITLE
gtk critical error on 0.5.3, fails to launch

### ISSUE THREAD

**Issue by vovchykbratyk** [lutris/lutris#2358]
**Describe the bug**

Crossposted from the forums, figured this is the better place for this issue.

Attempting to launch lutris results in a crash.

**Expected behavior**

Lutris should launch successfully.

**Current behavior**

Crashes.

**Steps to reproduce**

- Install all lutris dependencies as recommended in the documentation.
- Install lutris. (`zypper in lutris`)

**Lutris debugging output**

```
XXXX@XXXX-xps-15:~> lutris
2019-09-21 16:30:50,179: Running Lutris 0.5.3
2019-09-21 16:30:50,179: Using NVIDIA drivers 435.21 for x86_64
2019-09-21 16:30:50,179: GPU: GeForce GTX 1050 Ti with Max-Q Design
2019-09-21 16:30:50,179: GPU: 8086:3E9B 1028:087C using i915 drivers
2019-09-21 16:30:50,179: GPU: 10DE:1C8C 1028:087C using nvidia drivers
2019-09-21 16:30:50,201: Vulkan is supported

** (lutris:6461): WARNING **: 16:30:50.202: expected enumeration type GtkWindowType, but got GtkMessageType instead

(lutris:6461): Gtk-CRITICAL **: 16:30:50.203: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 227, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.7/site-packages/lutris/startup.py", line 170, in run_all_checks
    check_donate()
  File "/usr/lib/python3.7/site-packages/lutris/startup.py", line 140, in check_donate
    secondary_message="Lutris is entirely funded by its community and will "
  File "/usr/lib/python3.7/site-packages/lutris/gui/dialogs/__init__.py", line 453, in __init__
    dont_show_checkbutton = Gtk.CheckButton(checkbox_message)
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
2019-09-21 16:30:50,204: Shutting down Lutris
```

**System information**

Lutris does not get far enough in the launch process to generate the debugging json.  However, the platform is a Dell XPS 15 9570

Distro: OpenSUSE tumbleweed
Nvidia 435 drivers
optimus laptop, at time of launch prime-select is set to nvidia

**Screenshots**

None necessary

**Comment by vovchykbratyk** [comment]
Turns out by installing python3-gobject-Gdk and typelib-1_0-Gtk-3_0 it now works. Will leave this issue open because it looks like this might be a regression to be addressed in next release.

**Comment by Adehom** [comment]
I don't have this problem in Debian 10.

**Comment by Medath** [comment]
Seems like the lutris package for OpenSUSE is missing some dependencies

**Comment by Adehom** [comment]
I will add this dependencies in the install documentation

**Comment by strycore** [comment]
PR merged
