### ISSUE TITLE
Dark Souls fails to install through winesteam

### ISSUE THREAD

**Issue by Alloyed** [lutris/lutris#236]
Using lutris 3.7, installed through the Arch Linux AUR. Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lutris/gui/installgamedialog.py", line 271, in on_install_clicked
    self.interpreter.iter_game_files()
  File "/usr/lib/python2.7/site-packages/lutris/installer/interpreter.py", line 149, in iter_game_files
    if self.should_create_target:
  File "/usr/lib/python2.7/site-packages/lutris/installer/interpreter.py", line 94, in should_create_target
    not os.path.exists(self.target_path)
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
Other games install fine.

**Comment by Xodetaetl** [comment]
Fixed: 67f0cae6a3b57aa4e48a1cd97609377dad8d9f25
Will be in 0.3.7.1
