### ISSUE TITLE
[Fedora] [0.5.3] user_agent(): http.py:64:user_agent:AttributeError: module 'platform' has no attribute 'dist'

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#2395]
Description of problem:
Problem manifested with fresh reboot, and immediately upon launching Lutris and attempting to 'login', the application completely quit.
It is worth noting that Lutris has had difficulty contacting Lutris.net for the last day, and this was a bit of an esculation in its methodology of displaying refusal to contect the server successfully.

Version-Release number of selected component:
lutris-0.5.3-1.fc32

Additional info:
reporter:       libreport-2.10.1
cgroup:         0::/user.slice/user-1000.slice/user@1000.service/gnome-shell-x11.service
cmdline:        /usr/bin/python3 -s /usr/bin/lutris
crash_function: user_agent
exception_type: AttributeError
executable:     /usr/bin/lutris
interpreter:    python3-3.8.0~rc1-1.fc32.x86_64
kernel:         5.4.0-0.rc1.git1.1.fc32.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
http.py:64:user_agent:AttributeError: module 'platform' has no attribute 'dist'

Traceback (most recent call last):
  File "[REDACTED]/lutris/gui/dialogs/__init__.py", line 307, in on_password_entry_activate
    self.on_connect(None)
  File "/usr/lib/python3.8/site-packages/lutris/gui/dialogs/__init__.py", line 313, in on_connect
  File "/usr/lib/python3.8/site-packages/lutris/api.py", line 51, in connect
    get_user_info()
  File "/usr/lib/python3.8/site-packages/lutris/api.py", line 69, in get_user_info
    request = http.Request(url, headers=[REDACTED]
  File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 48, in __init__
    self.headers = {"User-Agent": self.user_agent}
  File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 64, in user_agent
    PROJECT, VERSION, " ".join(platform.dist()), platform.machine()
AttributeError: module 'platform' has no attribute 'dist'

Local variables in innermost frame:
self: <lutris.util.http.Request object at 0x7f2dfbcf7670>

**Comment by strycore** [comment]
The offending code has been removed.
