### ISSUE TITLE
Lutris stopped launching

### ISSUE THREAD

**Issue by tuxutku** [lutris/lutris#2433]
**Describe the bug**

When launched from command line process doesn't end but lutris gui doesn't launch either:

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Expected behavior**

lutris to launch

**Current behavior**

Lutris process doesn't crash but gui doesn't launch

**Steps to reproduce**

- 
-
-

```
utku3@pop-os:~$ lutris -d
INFO     2019-10-31 21:19:49,613 [application.do_command_line:225]:Running Lutris 0.5.3
INFO     2019-10-31 21:19:49,639 [startup.check_driver:60]:Using X.Org
INFO     2019-10-31 21:19:49,639 [startup.check_driver:65]:Running Mesa driver 19.3.0 on AMD CARRIZO (DRM 3.35.0, 5.4.0-050400rc5-generic, LLVM 9.0.0) (0x9874)
INFO     2019-10-31 21:19:49,640 [startup.check_driver:75]:GPU: 1002:699F 1025:1210 using amdgpu drivers
INFO     2019-10-31 21:19:49,641 [startup.check_driver:75]:GPU: 1002:9874 1025:1201 using amdgpu drivers
INFO     2019-10-31 21:19:50,989 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-10-31 21:19:51,102 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
INFO     2019-10-31 21:19:52,625 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 128, in __init__
    self.sidebar_listbox = SidebarListBox()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 170, in __init__
    self.update()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 197, in update
    self.installed_runners = [runner.name for runner in runners.get_installed()]
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
  File "/usr/lib/python3/dist-packages/lutris/runners/winesteam.py", line 305, in is_installed
    return system.path_exists(self.get_steam_path())
  File "/usr/lib/python3/dist-packages/lutris/runners/winesteam.py", line 275, in get_steam_path
    return system.fix_path_case(registry.get_unix_path(steam_path))
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 236, in fix_path_case
    if os.path.exists(path):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 550, in add_proc_info
    self.add_proc_environ(pid, extraenv)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 619, in add_proc_environ
    env = _read_file('environ', dir_fd=proc_pid_fd).replace('\n', '\\n')
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in _read_file
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in <lambda>
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
TypeError: argument should be integer or None, not list

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 128, in __init__
    self.sidebar_listbox = SidebarListBox()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 170, in __init__
    self.update()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 197, in update
    self.installed_runners = [runner.name for runner in runners.get_installed()]
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
  File "/usr/lib/python3/dist-packages/lutris/runners/winesteam.py", line 305, in is_installed
    return system.path_exists(self.get_steam_path())
  File "/usr/lib/python3/dist-packages/lutris/runners/winesteam.py", line 275, in get_steam_path
    return system.fix_path_case(registry.get_unix_path(steam_path))
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 236, in fix_path_case
    if os.path.exists(path):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
^C
utku3@pop-os:~$ 
```

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

[https://raw.githubusercontent.com/tuxutku/myrepository/master/lutris/lutris-issue-report.json](https://raw.githubusercontent.com/tuxutku/myrepository/master/lutris/lutris-issue-report.json)

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by tuxutku** [comment]
Switching users fix the problem, i will try to remove some configuration files and try again

**Comment by tuxutku** [comment]
Removing `/home/utku3/.local/share/lutris/runners/winesteam` have fixed the problem.
[Here](https://github.com/tuxutku/myrepository/raw/master/lutris/lutris_files.tar.xz) are the lutris folders under `.cache`, `.local/share` and `.config` . I didn't uploaded the big files that didn't affected anything, only the configuration files in runners etc...

**Comment by tannisroot** [comment]
Not sure if this is a real bug but it should be looked at before the release.
