### ISSUE TITLE
Repeated Async Error

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#245]
```
ERROR    2016-01-06 16:36:47,824 [jobs]:Error while completing task <bound method Sync.sync_local of <lutris.sync.Sync object at 0x7f509c9c92d0>>: list index out of range
Traceback (most recent call last):
  File "util/jobs.py", line 36, in <lambda>
    GLib.idle_add(lambda: self.on_done(result, error))
  File "gui/lutriswindow.py", line 396, in update_gui
    self.update_existing_games(set(), set(), *result)
TypeError: update_existing_games() argument after * must be a sequence, not NoneType
```

**Comment by RobLoach** [comment]
Getting this error on `next` too.

**Comment by strycore** [comment]
Is this happening on a machine where steam isn't installed?

**Comment by RobLoach** [comment]
Steam is installed.

**Comment by strycore** [comment]
It shouldn't produce that error anymore, can you confirm?

**Comment by RobLoach** [comment]
### `master`

```
➜  lutris git:(master) bin/lutris 

** (lutris:7752): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-WjNkmZ4LHS: Connection refused
ERROR    2016-02-22 00:13:29,787 [jobs]:Error while completing task <bound method Sync.sync_local of <lutris.sync.Sync object at 0x7f332c37d410>>: list index out of range
ERROR    2016-02-22 00:13:29,788 [lutriswindow]:No results while syncing local Steam database
ERROR    2016-02-22 00:13:39,761 [jobs]:Error while completing task <bound method Sync.sync_local of <lutris.sync.Sync object at 0x7f332c3b75d0>>: list index out of range
ERROR    2016-02-22 00:13:39,762 [lutriswindow]:No results while syncing local Steam database
ERROR    2016-02-22 00:13:44,046 [jobs]:Error while completing task <bound method Sync.sync_all of <lutris.sync.Sync object at 0x7f3335db00d0>>: list index out of range
Traceback (most recent call last):
  File "/home/rob/Documents/lutris/lutris/util/jobs.py", line 36, in <lambda>
    GLib.idle_add(lambda: self.on_done(result, error))
  File "/home/rob/Documents/lutris/lutris/gui/lutriswindow.py", line 273, in update_gui
    added, updated, installed, uninstalled = result
TypeError: 'NoneType' object is not iterable
```

### `next`
```
➜  lutris git:(next) bin/lutris 

** (lutris:7944): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-WjNkmZ4LHS: Connection refused
ERROR    2016-02-22 00:14:38,685 [jobs]:Error while completing task <bound method Sync.sync_all of <lutris.sync.Sync object at 0x7f671caef450>>: list index out of range
Traceback (most recent call last):
  File "/home/rob/Documents/lutris/lutris/util/jobs.py", line 36, in <lambda>
    GLib.idle_add(lambda: self.on_done(result, error))
  File "/home/rob/Documents/lutris/lutris/gui/lutriswindow.py", line 273, in update_gui
    added, updated, installed, uninstalled = result
TypeError: 'NoneType' object is not iterable
ERROR    2016-02-22 00:14:44,355 [jobs]:Error while completing task <bound method Sync.sync_local of <lutris.sync.Sync object at 0x7f671caef610>>: list index out of range
Traceback (most recent call last):
  File "/home/rob/Documents/lutris/lutris/util/jobs.py", line 36, in <lambda>
    GLib.idle_add(lambda: self.on_done(result, error))
  File "/home/rob/Documents/lutris/lutris/gui/lutriswindow.py", line 396, in update_gui
    self.update_existing_games(set(), set(), *result)
TypeError: update_existing_games() argument after * must be a sequence, not NoneType
ERROR    2016-02-22 00:14:54,354 [jobs]:Error while completing task <bound method Sync.sync_local of <lutris.sync.Sync object at 0x7f671ddb3e90>>: list index out of range
Traceback (most recent call last):
  File "/home/rob/Documents/lutris/lutris/util/jobs.py", line 36, in <lambda>
    GLib.idle_add(lambda: self.on_done(result, error))
  File "/home/rob/Documents/lutris/lutris/gui/lutriswindow.py", line 396, in update_gui
    self.update_existing_games(set(), set(), *result)
TypeError: update_existing_games() argument after * must be a sequence, not NoneType
```

**Comment by strycore** [comment]
Ok, so you had the same problem with the local and remote library, I wonder why you're not getting results but now you shouldn't see these errors with the latest commit (maybe some new ones?)

**Comment by strycore** [comment]
I'm closing this because I've deleted all the code related to local sync, feel free to re-open if you're still experiencing this issue (which would only be related to the remote syncing if that was the case)
