### ISSUE TITLE
Unable to install Wine Steam game

### ISSUE THREAD

**Issue by Jan200101** [lutris/lutris#2486]
**Describe the bug**

When installing a Wine Steam the installer raises a exception and gets stuck at the screen prompting you to click install

**Expected behavior**

Installation of the game

**Current behavior**

Getting stuck on the first screen

**Steps to reproduce**

- Install the latest Lutris commit (I used the [lutris-git](https://copr.fedorainfracloud.org/coprs/sentry/lutris-git) copr)
- try to install a Wine Steam game

**Lutris debugging output**
I've gone through the debugging output and found this traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/installerwindow.py", line 252, in on_install_clicked
    self.interpreter.check_runner_install()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 470, in check_runner_install
    default_wine["architecture"]
KeyError: 'winesteam'
```
I am fairly sure f188a2f0f99fb4cdd40cc6d2e60cafc9da4c1ce8 has caused this and running a commit before that makes it work fine

**System information**
[lutris-issue-report.json](
https://gist.github.com/Jan200101/c1931998f316270e00dd5eb735f3724e).

**Comment by tannisroot** [comment]
I can reproduce the issue but i get a different traceback:
```Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 252, in on_install_clicked
    self.interpreter.check_runner_install()
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 468, in check_runner_install
    params["version"] = self.script[self.runner]["version"] = "{}-{}".format(
KeyError: 'winesteam'
```

**Comment by tannisroot** [comment]
Some other Steam installers (https://lutris.net/games/a-hat-in-time/) seem to give a completely different error:
```2019-11-24 20:25:54,700: Error while completing task <bound method ScriptInterpreter.install_steam_game of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f746d7627f0>>: 'appid'
<class 'KeyError'> 'appid'
  File "/usr/lib/python3.8/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 804, in install_steam_game
    appid = self.steam_data["appid"]
```
