### ISSUE TITLE
Freeze at  Updating D9VK versions

### ISSUE THREAD

**Issue by dev-zetta** [lutris/lutris#2487]
**Describe the bug**

Lutris stops working on step "Updating D9VK versions". Running from console "lutris -d -i /home/maxli/metro.yml". It open window and waits for response. No data being downloaded.

It does not timeout.

`INFO     2019-11-25 22:14:05,696 [startup.check_driver:60]:Using X.Org
INFO     2019-11-25 22:14:05,696 [startup.check_driver:65]:Running Mesa driver 20.0.0 on AMD Radeon R9 M280X (BONAIRE, DRM 3.33.0, 5.3.0-23-generic, LLVM 9.0.0) (0x6646)
INFO     2019-11-25 22:14:05,696 [startup.check_driver:75]:GPU: 1002:6646 103C:2256 using amdgpu drivers
WARNING: radv is not a conformant vulkan implementation, testing use only.
INFO     2019-11-25 22:14:05,721 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-11-25 22:14:05,722 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
INFO     2019-11-25 22:14:05,899 [lutriswindow.toggle_connection:580]:Connected to lutris.net as dddd
DEBUG    2019-11-25 22:14:05,899 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-11-25 22:14:05,900 [http.get:68]:GET https://lutris.net/api/games/library/dddd
DEBUG    2019-11-25 22:14:06,185 [interpreter.read_script:68]:Loading script(s) from /home/dddd/metro.yml
INFO     2019-11-25 22:14:06,337 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
`
I checked the runtime directory, nothing has been downloaded and installed.

**Expected behavior**

Please describe the behavior you are expecting.

**Current behavior**

What is the current behavior?

**Steps to reproduce**

-Fresh isntall, latest version 
-Run custom script install from terminal
-

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/3283719/69578747-6842a100-0fd1-11ea-9238-6e2d03d95ab7.png)

**Comment by tannisroot** [comment]
Can you open this page without VPN? https://api.github.com/repos/doitsujin/dxvk/releases

**Comment by dev-zetta** [comment]
Hello, yes, I can. After a bit of debugging I found out that the problem is not in networking but in install initialization while running from terminal. Installing games using scripts from online library works fine.

**Comment by bkdwt** [comment]
Same problem on Gentoo:

```
botnet@nsa ~ $ lutris -d

(lutris:11534): dbind-WARNING **: 17:41:49.820: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
INFO     2020-01-05 17:41:50,165 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-01-05 17:41:50,165 [startup.check_driver:62]:Using X.Org
INFO     2020-01-05 17:41:50,165 [startup.check_driver:67]:Running Mesa driver 19.3.1 on Radeon RX 570 Series (POLARIS10, DRM 3.35.0, 5.4.2, LLVM 8.0.1) (0x67df)
INFO     2020-01-05 17:41:50,165 [startup.check_driver:79]:GPU: 1002:67DF 1458:22F0 using amdgpu drivers
INFO     2020-01-05 17:41:50,183 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-01-05 17:41:50,184 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib64/python3.6/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib64/python3.6/site-packages/lutris/gui/lutriswindow.py", line 321, in get_store
    self.show_installed_first,
  File "/usr/lib64/python3.6/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'new_with_model'
INFO     2020-01-05 17:41:50,962 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
^Z
[2]+  Stopped                 lutris -d
```
Lutris won't start using GUI or CLI. I get stuck on this message.

**Comment by strycore** [comment]
@bkdwt that's a different issue and will be fixed in next release.
Open /usr/lib64/python3.6/site-packages/lutris/gui/views/store.py with a text editor using sudo and replace `Gtk.TreeModelSort.new_with_model` with `Gtk.TreeModelSort.sort_new_with_model`. Save and relaunch lutris

**Comment by bkdwt** [comment]
> @bkdwt that's a different issue and will be fixed in next release.
> Open /usr/lib64/python3.6/site-packages/lutris/gui/views/store.py with a text editor using sudo and replace `Gtk.TreeModelSort.new_with_model` with `Gtk.TreeModelSort.sort_new_with_model`. Save and relaunch lutris

Now I've already downgraded to version 0.53. But anyway, thanks for the feedback.

**Comment by neilsimp1** [comment]
On Arch Linux, doing the opposite just fixed Lutris for me.
I'm not sure what changed, but Lutris was working fine last night.

Now when I run, it gets stuck and never displays anything:
```
lutris -d                                                          16:09:52 
INFO     2020-02-17 16:09:55,777 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-02-17 16:09:55,778 [startup.check_driver:62]:Using X.Org
INFO     2020-02-17 16:09:55,778 [startup.check_driver:64]:Running Mesa driver 19.3.4 on Radeon RX 580 Series (POLARIS10, DRM 3.36.0, 5.5.4-arch1-1, LLVM 9.0.1) (0x67df)
INFO     2020-02-17 16:09:55,778 [startup.check_driver:77]:GPU: 1002:67DF 1462:3417 using amdgpu drivers
INFO     2020-02-17 16:09:55,857 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-02-17 16:09:55,858 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
INFO     2020-02-17 16:09:56,131 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
``

I edited `/usr/lib64/python3.8/site-packages/lutris/gui/views/store.py`, changed `Gtk.TreeModelSort.sort_new_with_model` to `Gtk.TreeModelSort.new_with_model`, and it's opening up again just fine.

**Comment by perara** [comment]
> On Arch Linux, doing the opposite just fixed Lutris for me.
> I'm not sure what changed, but Lutris was working fine last night.
> 
> Now when I run, it gets stuck and never displays anything:
> 
> ```
> lutris -d                                                          16:09:52 
> INFO     2020-02-17 16:09:55,777 [application.do_command_line:225]:Running Lutris 0.5.4
> INFO     2020-02-17 16:09:55,778 [startup.check_driver:62]:Using X.Org
> INFO     2020-02-17 16:09:55,778 [startup.check_driver:64]:Running Mesa driver 19.3.4 on Radeon RX 580 Series (POLARIS10, DRM 3.36.0, 5.5.4-arch1-1, LLVM 9.0.1) (0x67df)
> INFO     2020-02-17 16:09:55,778 [startup.check_driver:77]:GPU: 1002:67DF 1462:3417 using amdgpu drivers
> INFO     2020-02-17 16:09:55,857 [startup.check_vulkan:132]:Vulkan is supported
> INFO     2020-02-17 16:09:55,858 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
>     self.window = LutrisWindow(application=self)
>   File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
>     self.game_store = self.get_store()
>   File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
>     game_store = GameStore(
>   File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
>     self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
> AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
> INFO     2020-02-17 16:09:56,131 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
> ``
> 
> I edited `/usr/lib64/python3.8/site-packages/lutris/gui/views/store.py`, changed `Gtk.TreeModelSort.sort_new_with_model` to `Gtk.TreeModelSort.new_with_model`, and it's opening up again just fine.
> ```

I can confirm that the following solved the issue. On Arch (Updated system as of today)

**Comment by osdamv** [comment]
> I can confirm that the following solved the issue. On Arch (Updated system as of today)
Same here, looks like we like to play some stuff in the after noon

**Comment by wildw1ng** [comment]
Thanks neilsimp1 !

**Comment by FFY00** [comment]
I pushed a fixed package to the repos this morning. We should be able to close this now.

Can you guys confirm it fixes things for you?

**Comment by bkdwt** [comment]
> I pushed a fixed package to the repos this morning. We should be able to close this now.
> 
> Can you guys confirm it fixes things for you?

Still on 0.5.4 on Fedora 32 and still with the same problem.

**Comment by FFY00** [comment]
Sorry, I forgot to mentioned. I pushed a new package to the Archlinux repos.

**Comment by bkdwt** [comment]
> Sorry, I forgot to mentioned. I pushed a new package to the Archlinux repos.
Who is the maintainer of the Lutris package for Fedora? Do you know?

**Comment by FFY00** [comment]
> Who is the maintainer of the Lutris package for Fedora? Do you know?

Sorry, I don't.

**Comment by baryluk** [comment]
Same issue here. I am using Debian package from lutris. Debian testing/unstable amd64.

```
user@debian:~$ lutris
2020-03-06 21:03:03,984: Running Lutris 0.5.4
2020-03-06 21:03:03,984: Using X.Org
2020-03-06 21:03:03,984: Running Mesa driver 20.1.0 on AMD Radeon (TM) R9 Fury Series (FIJI, DRM 3.32.0, 5.2.0-3-amd64, LLVM 9.0.1) (0x7300)
2020-03-06 21:03:03,984: GPU: 1002:7300 1002:0B36 using amdgpu drivers
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
Unknown option 'output_relative_time'
Unknown option 'graph_y_zero'
Unknown option 'output_csv'
Unknown option 'output_per_frame'
Unknown option 'output_flush'
2020-03-06 21:03:04,005: Vulkan is supported
2020-03-06 21:03:04,006: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-03-06 21:03:04,352: Updating D9VK versions
```

It doesn't progress beyond that.

**Comment by baryluk** [comment]
BTW. I think the issue is not in DXVK or D9VK. I added some debugging stuff in the dxvk.py and it finishes successfully. The actual problem is somewhere else later in the code. The D9VK being the last thing displayed looks to be just a coincidence.

**Comment by baryluk** [comment]
Yes. Doh. 

```diff
-    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
+    self.modelsort = Gtk.TreeModelSort.new_with_model(self.modelfilter)
```

fixed the problem.

**Comment by baryluk** [comment]
Duplicate of #2554

**Comment by chris-echoz** [comment]
Debian Sid here, experienced the same problem and fixed it by making the change mentioned by @baryluk in `/usr/lib/python3/dist-packages/lutris/gui/views/store.py`

**Comment by credomane** [comment]
I'm running Debian sid with python 3.8.2 and lutris 0.5.4

I also had to do the opposite of what was mentioned above to make lutris work.

```diff
-    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
+    self.modelsort = Gtk.TreeModelSort.new_with_model(self.modelfilter)
```

**Comment by baryluk** [comment]
BTW. This is already fixed in master branch for lutris 0.5.5. Hopefully to be released soon(tm).
