### ISSUE TITLE
The name org.gnome.Mutter.DisplayConfig was not provided by any .service files

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2510]
**Describe the bug**
I updated to the latest git and found this on the following on the terminal. It didn't happen before I updated today. I update maybe once a week.

```
2019-12-03 07:04:40,287: Failed to instanciate MutterDisplayConfig. Please report with exception: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Mutter.DisplayConfig was not provided by any .service files
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.gnome.Mutter.DisplayConfig': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/src/lutris/lutris/util/display.py", line 110, in <module>
    DISPLAY_MANAGER = MutterDisplayManager()
  File "~/src/lutris/lutris/util/graphics/displayconfig.py", line 598, in __init__
    self.display_config = MutterDisplayConfig()
  File "~/src/lutris/lutris/util/graphics/displayconfig.py", line 415, in __init__
    proxy_obj = session_bus.get_object(self.namespace, self.dbus_path)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Mutter.DisplayConfig was not provided by any .service files
```

**Comment by Jan200101** [comment]
Same here
It was introduced in f5731088f29f2314a85d52e279869e1b48de5574

**Comment by aviallon** [comment]
Go the same issue.
