### ISSUE TITLE
Discord not open bug

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2516]
When you don't have Discord open, the following gets dumped on the terminal:

```
Traceback (most recent call last):
  File "~/src/lutris/lutris/game.py", line 627, in beat
    self.discord_presence.update_discord_rich_presence()
  File "~/src/lutris/lutris/discord.py", line 95, in update_discord_rich_presence
    if not self.connect():
  File "~/src/lutris/lutris/discord.py", line 47, in connect
    self.rpc_client.connect()
  File "~/.local/lib/python3.6/site-packages/pypresence/presence.py", line 40, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "~/.local/lib/python3.6/site-packages/pypresence/baseclient.py", line 102, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 444, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory 
```

**Comment by strycore** [comment]
I've tried to reproduce this with Discord closed and I just can't reproduce this error.
