### ISSUE TITLE
Can't open Wine Configuration

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2555]
Backtrace: 
```
DEBUG    2019-12-29 10:32:56,867 [wine.winecfg:381]:winecfg: /home/alex/.local/share/lutris/runners/wine/lutris-5.0-rc3-x86_64/bin/winecfg
DEBUG    2019-12-29 10:32:56,867 [wine.use_lutris_runtime:113]:/home/alex/.local/share/lutris/runners/wine/lutris-5.0-rc3-x86_64/bin/winecfg is provided by Lutris, using runtime
WARNING  2019-12-29 10:32:56,879 [wine.game_exe:529]:The game doesn't have an executable
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/runners/wine.py", line 677, in run_winecfg
    winecfg(
  File "/usr/lib/python3.8/site-packages/lutris/runners/commands/wine.py", line 383, in winecfg
    return wineexec(
  File "/usr/lib/python3.8/site-packages/lutris/runners/commands/wine.py", line 326, in wineexec
    command.start()
  File "/usr/lib/python3.8/site-packages/lutris/command.py", line 116, in start
    logger.debug("Running %s", " ".join(self.wrapper_command))
TypeError: sequence item 1: expected str instance, list found
```

**Comment by telanus** [comment]
I get the same error when I use "Run exe inside wine prefix"

**Comment by CartoonFan** [comment]
I'm getting the same error as well.

**Comment by tannisroot** [comment]
Seems to have been fixed.
