### ISSUE TITLE
Overwatch: "not a gzip file"

### ISSUE THREAD

**Issue by Quiquoqua48** [lutris/lutris#2593]
I receive the error "not a gzip file" for downloading dxvk. The output is:
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
ERROR    2020-01-11 15:14:38,301 [game.configure_game:317]:Game prelaunch unsuccessful
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
DEBUG    2020-01-11 15:15:02,571 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2020-01-11 15:15:07,608 [common.is_valid:479]:args validated successfully: ['--exec=launch Pro']
DEBUG    2020-01-11 15:15:07,611 [game.save:236]:Saving Overwatch (wine)
DEBUG    2020-01-11 15:15:07,612 [config.save:208]:Saving LutrisConfig(level=game, game_config_id=overwatch-standard-1578750530, runner=wine) config to /home/hunpan/.config/lutris/games/overwatch-standard-1578750530.yml
DEBUG    2020-01-11 15:15:07,770 [lutriswindow.on_game_updated:721]:Updating game Overwatch (wine)
DEBUG    2020-01-11 15:19:33,684 [application.launch:339]:Launching Overwatch (wine) (140195406139896)
DEBUG    2020-01-11 15:19:33,730 [game.play:297]:Prelaunching <lutris.runners.wine.wine object at 0x7f81c6020f60>
WARNING  2020-01-11 15:19:33,731 [joypad.get_devices:15]:python3-evdev not installed, controller support not available
WARNING  2020-01-11 15:19:33,732 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for Desktop
WARNING  2020-01-11 15:19:33,732 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for Personal
WARNING  2020-01-11 15:19:33,733 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for My Music
WARNING  2020-01-11 15:19:33,733 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for My Videos
WARNING  2020-01-11 15:19:33,733 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for My Pictures
DEBUG    2020-01-11 15:19:33,735 [downloader.start:55]:Starting download of:
 https://github.com/doitsujin/dxvk/releases/download/v1.5.1/dxvk-1.5.1.tar.gz
DEBUG    2020-01-11 15:19:35,097 [downloader.on_done:97]:Finished downloading https://github.com/doitsujin/dxvk/releases/download/v1.5.1/dxvk-1.5.1.tar.gz
DEBUG    2020-01-11 15:19:35,239 [extract.extract_archive:69]:Extracting /home/hunpan/.local/share/lutris/runtime/dxvk/dxvk-1.5.1.tar.gz to /home/hunpan/.local/share/lutris/runtime/dxvk/1.5.1
ERROR    2020-01-11 15:19:35,240 [extract.extract_archive:116]:Extraction failed: not a gzip file
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tarfile.py", line 1643, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/usr/lib64/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python3.6/tarfile.py", line 1092, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib64/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib64/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<?')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/util/extract.py", line 114, in extract_archive
    _do_extract(path, temp_path, opener, mode, extractor)
  File "/usr/lib/python3.6/site-packages/lutris/util/extract.py", line 166, in _do_extract
    handler = opener(archive, mode)
  File "/usr/lib64/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1647, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
ERROR    2020-01-11 15:19:35,241 [jobs.target:32]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f81c6020f60>>: not a gzip file
<class 'lutris.util.extract.ExtractFailure'> not a gzip file
  File "/usr/lib/python3.6/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 800, in prelaunch
    version=self.runner_config.get("dxvk_version"),
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 779, in setup_dxvk
    dxvk_manager=dxvk_manager,
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 761, in toggle_dxvk
    dxvk_manager.download()
  File "/usr/lib/python3.6/site-packages/lutris/util/wine/dxvk.py", line 142, in download
    extract_archive(dxvk_archive_path, self.dxvk_path, merge_single=True)
  File "/usr/lib/python3.6/site-packages/lutris/util/extract.py", line 117, in extract_archive
    raise ExtractFailure(str(ex))
ERROR    2020-01-11 15:19:35,242 [game.configure_game:314]:not a gzip file
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
ERROR    2020-01-11 15:19:37,031 [game.configure_game:317]:Game prelaunch unsuccessful
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
`

I've found an old error report but i didn't see (or understood) the workaround..

**Comment by strycore** [comment]
The "not a gzip file" bug is currently fixed in master. Since this is all there is for this bug report I'm going to go ahead and close this.
If the issue persists, the next release should make it easier to troubleshoot.
