### ISSUE TITLE
Lutris isn't downloading the runtime files

### ISSUE THREAD

**Issue by keithbowes** [lutris/lutris#2622]
**Describe the bug**

As mentioned in issue #1539, downloading of lib32 and lib64 aren't working (nor are most of the other runtime files).  They're not valid gzip/bzip2 files:
```
$ cat lib32.tar.bz2
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><RequestId>tx000000000000000307b5c-005e3ae7b7-340a218-nyc3a</RequestId><HostId>340a218-nyc3a-nyc</HostId></Error>
```

The trick in issue #1539 of downloading and extracting them manually doesn't work either, because Lutris deletes the downloaded and extracted files and tries to download them again, but again, they're not valid and so I still get warnings about missing files and invalid gzip/bzip2 files.  I got Lutris not to delete the extracted files by making them readonly, but I still get stderr messages about being unable to extract the files (and it shouldn't make users go through such hurdles anyway):
```
2020-02-08 19:51:50,107: Runtime update failed
2020-02-08 19:51:50,108: not a gzip file
2020-02-08 19:51:50,109: Runtime update failed
2020-02-08 19:51:50,109: not a gzip file
2020-02-08 19:51:50,110: Runtime update failed
2020-02-08 19:51:50,110: not a bzip2 file
2020-02-08 19:51:50,111: Runtime update failed
2020-02-08 19:51:50,111: not a bzip2 file
2020-02-08 19:51:50,112: Runtime update failed
2020-02-08 19:51:50,112: not a bzip2 file
```

**Expected behavior**

The runtime files should download and extract correctly.

**Current behavior**

The runtime files don't download and extract correctly.

**Steps to reproduce**

Um, run Lutris from the command line.

**Lutris debugging output**

[log.txt](https://github.com/lutris/lutris/files/4176341/log.txt)

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

[lutris-issue-report.json](https://github.com/lutris/lutris/files/4176333/lutris-issue-report.txt)

**Screenshots**

**Comment by tannisroot** [comment]
I'm really not sure why the package isn't extracting properly for you (it certainly does for me) but we really should handle this more gracefully.

**Comment by strycore** [comment]
I don't know what's up with that ticket but lib32 / lib64 are downloading just fine.

**Comment by tannisroot** [comment]
@strycore i flagged it because of this (see log.txt file)
```ERROR    2020-02-08 19:55:38,170 [extract.extract_archive:116]:Extraction failed: not a gzip file
Traceback (most recent call last):
  File "/usr/lib64/python3.7/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.7/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.7/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib64/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib64/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib64/python3.7/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<?')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 114, in extract_archive
    _do_extract(path, temp_path, opener, mode, extractor)
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 166, in _do_extract
    handler = opener(archive, mode)
  File "/usr/lib64/python3.7/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib64/python3.7/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file```

**Comment by yannDbe** [comment]
@keithbowes can you do an md5sum on your downloaded files, please ?

**Comment by tannisroot** [comment]
We purged our CDN cache recently, can you check whether that fixed your issue?

**Comment by strycore** [comment]
I fixed the stacktrace so I'm closing this ticket.

**Comment by keithbowes** [comment]
Now in my distro's update to 0.5.5, I'm now getting messages like:
`<class 'requests.exceptions.HTTPError'> 400 Client Error: Bad Request for url: https://lutris.nyc3.digitaloceanspaces.com/runtime/lib64.tar.bz2`

He he.  That's better than downloading funky XML files and pretending that they're .tar.bz2/.tar.gz files, I suppose.

**Comment by strycore** [comment]
0.5.5 is 2 versions behind.

**Comment by strycore** [comment]
But it's not a lutris issue, the Digital Ocean file downloads just fine here. I have no clue why our CDN is not nice to some people.

**Comment by tannisroot** [comment]
Some regions block DigitalOcean's IP pools. Plus CDNs seem to get corrupted? on rare occasions and the only way to fix them is to purge them.

**Comment by strycore** [comment]
there seems to be issues with the old runtime archives specifically (lib32, lib64). These are to be deprecated soon so I'm hope it might solve some of the issues? 
I don't see how a file on a CDN gets corrupted to begin with…

**Comment by barfin** [comment]
I still have this problem
version 0.5.8.3-2 on arch linux
```
╰─ lutris
2021-05-06 21:10:21,945: Loading of DXVK versions failed, defaulting to locally available versions
2021-05-06 21:10:21,955: Loading of DXVK versions failed, defaulting to locally available versions
2021-05-06 21:10:22,041: Initializing lutris
2021-05-06 21:10:22,043: Loading of DXVK versions failed, defaulting to locally available versions
2021-05-06 21:10:22,053: Loading of DXVK versions failed, defaulting to locally available versions
2021-05-06 21:10:23,315: Runtime lib64 is not available locally
2021-05-06 21:10:23,318: Runtime lib32 is not available locally
2021-05-06 21:11:15,544: Non existent path: /home/barfin/.local/share/lutris/runtime/lib32
2021-05-06 21:11:17,947: Extraction failed: Compressed file ended before the end-of-stream marker was reached
2021-05-06 21:11:17,947: Error while completing task <function extract_archive at 0x7efce1271f70>: Compressed file ended before the end-of-stream marker was reached
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/util/extract.py", line 138, in extract_archive
    raise ExtractFailure(str(ex))
2021-05-06 21:11:17,948: Runtime update failed
2021-05-06 21:11:17,948: Compressed file ended before the end-of-stream marker was reached
2021-05-06 21:11:22,183: Non existent path: /home/barfin/.local/share/lutris/runtime/lib64

```
