### ISSUE TITLE
Error Running Lutris from Command Line after installing Through Python

### ISSUE THREAD

**Issue by ecbcat20** [lutris/lutris#2623]
Hi, just went to install Lutris from CLI today. Git cloned, then followed instructions in install.rst. Everything worked smoothly, until I went to type `lutris` from the command line. It gave me this error: 

`Traceback (most recent call last):
  File "/usr/local/bin/lutris", line 4, in <module>
    __import__('pkg_resources').run_script('lutris==0.5.4', 'lutris')

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/EGG-INFO/scripts/lutris", line 34, in <module>
    from lutris.gui.application import Application

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/gui/application.py", line 54, in <module>
    from .lutriswindow import LutrisWindow

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/gui/lutriswindow.py", line 28, in <module>
    from lutris.gui.widgets.sidebar import SidebarListBox

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/platforms.py", line 17, in <module>
    _init_platforms()

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/platforms.py", line 12, in _init_platforms
    runner = runners.import_runner(runner_name)()

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/runners/__init__.py", line 80, in import_runner
    runner_module = get_runner_module(runner_name)

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/runners/__init__.py", line 74, in get_runner_module
    "lutris.runners.%s" % runner_name, globals(), locals(), [runner_name], 0

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/runners/web.py", line 11, in <module>
    DEFAULT_ICON = os.path.join(datapath.get(), "media/default_icon.png")

  File "/usr/local/lib/python3.6/dist-packages/lutris-0.5.4-py3.6.egg/lutris/util/datapath.py", line 26, in get
    raise IOError("data_path can't be found at : %s" % data_path)

OSError: data_path can't be found at : /usr/local/share/lutris
`

Does anyone know how to fix this?

**Comment by Swalkyn** [comment]
The problem seems to be that lutris resources folder does not exist or is misplaced.
I'm not able to help you further than this, except by recommending a different installation. You said that you installed lutris through python. Quoting INSTALL.rst:
> Although this is the standard way of installing Python packages we STRONGLY advice against using it.
Instead, use your distribution's package manager or just try lutris without installing it by running `./bin/lutris` inside the cloned directory.

**Comment by ecbcat20** [comment]
Yeah we figured it out. Thank you! Turns out we needed to run it through
the bash command.
-Evan
