### ISSUE TITLE
Lutris GUI dosent Start

### ISSUE THREAD

**Issue by Nighti69** [lutris/lutris#2640]
I installed Lutris and related Drivers and WINE as described. This worked fine on my Laptop but not on my main Computer.

I tried to reinstall and de-install and install it again servral Times with no  success. The runners from the Lutris Website work also without the normal GUI of Lutris. Then I try to Start Lutris right after booting in the Bash, the Result was this: 

xxxx@xxxxxxxx:~> lutris
2020-03-03 11:24:47,237: Running Lutris 0.5.4
2020-03-03 11:24:47,239: Using NVIDIA drivers 440.64 for x86_64
2020-03-03 11:24:47,239: GPU: GeForce GTX 1050 Ti
2020-03-03 11:24:47,240: GPU: 10DE:1C82 1043:85D6 using nvidia drivers
2020-03-03 11:24:47,387: Vulkan is supported
2020-03-03 11:24:47,389: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 321, in get_store
    self.show_installed_first,
  File "/usr/lib/python3.7/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-03-03 11:24:47,929: Updating D9VK versions

**Comment by kermeat** [comment]
duplicate https://github.com/lutris/lutris/issues/2554

**Comment by Nighti69** [comment]
Thx @kermeat this helped me out :-)
