### ISSUE TITLE
Something is not working on ubuntu focal looks like the gui?

### ISSUE THREAD

**Issue by frank-dspeed** [lutris/lutris#2692]
**Describe the bug**
lutris -d
INFO     2020-03-28 15:35:14,516 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-03-28 15:35:14,516 [startup.check_driver:54]:Using NVIDIA drivers 440.64 for x86_64
INFO     2020-03-28 15:35:14,516 [startup.check_driver:60]:GPU: GeForce GTX 970
INFO     2020-03-28 15:35:14,516 [startup.check_driver:77]:GPU: 10DE:13C2 19DA:1366 using nvidia drivers
INFO     2020-03-28 15:35:14,576 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-03-28 15:35:14,577 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
INFO     2020-03-28 15:35:14,759 [dxvk.get_dxvk_versions:21]:Updating D9VK versions

**Comment by frank-dspeed** [comment]
sorry for posting that just downloaded git source 0.5.5 it has no error
