### ISSUE TITLE
Atari800 runner configuration window is not displayed

### ISSUE THREAD

**Issue by Steinhagen** [lutris/lutris#2759]
**Describe the bug**
Atari800 runner configuration window is not displayed

**Expected behavior**
The configuration window should be displayed.

**Current behavior**
The Python code doesn't treat this scenario.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/dialogs/runners.py", line 145, in on_configure_clicked
    config_dialog = RunnerConfigDialog(runner, parent=self.dialog)
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/runner.py", line 21, in __init__
    self.build_tabs("runner")
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/common.py", line 75, in build_tabs
    self._build_runner_tab(config_level)
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/common.py", line 364, in _build_runner_tab
    self.runner_box = RunnerBox(self.lutris_config, self.game)
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/boxes.py", line 641, in __init__
    self.generate_widgets("runner")
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/boxes.py", line 76, in generate_widgets
    option["choices"] = option["choices"]()
  File "/usr/lib/python3.8/site-packages/lutris/runners/atari800.py", line 46, in get_resolutions
    (resolution, resolution) for resolution in display.get_resolutions()
AttributeError: module 'lutris.util.display' has no attribute 'get_resolutions'
```

**Steps to reproduce**
1. Open Lutris from the command line.
2. Open the 'Manage runners' window.
3. Make sure you don't have 'Atari800' runner installed.
4. Click the 'Configure Runner' button for the 'Atari800' runner.

**Comment by EMPI-PL** [comment]
Hi. Got the same BUG on my system.
**LUTRIS:** 0.5.6
**OS**: Debian 10 (Testing)
**Python**: 3.8.2

Debbuger info:
```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/runners.py", line 145, in on_configure_clicked
    config_dialog = RunnerConfigDialog(runner, parent=self.dialog)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/runner.py", line 21, in __init__
    self.build_tabs("runner")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 75, in build_tabs
    self._build_runner_tab(config_level)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 364, in _build_runner_tab
    self.runner_box = RunnerBox(self.lutris_config, self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 641, in __init__
    self.generate_widgets("runner")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 76, in generate_widgets
    option["choices"] = option["choices"]()
  File "/usr/lib/python3/dist-packages/lutris/runners/atari800.py", line 46, in get_resolutions
    (resolution, resolution) for resolution in display.get_resolutions()
AttributeError: module 'lutris.util.display' has no attribute 'get_resolutions'
```

Tried re-installing Atari 800 runner without any effect. Process of downloading & re-installation of the runner works just fine.

**Comment by Steinhagen** [comment]
> Tried re-installing Atari 800 runner without any effect. Process of downloading & re-installation of the runner works just fine.

There is a pull request open to fix this issue. 🙂

**Comment by Steinhagen** [comment]
The fix for this issue was merged.

**Comment by YihaoPeng** [comment]
I encountered the same issue but the error message is different in the current master branch (6dc584f78b2ccee4839ebbe3c51a1aee2bb28858).

```
Traceback (most recent call last):
  File "/parent/work/winegame/lutris/lutris/gui/dialogs/runners.py", line 148, in on_configure_clicked
    config_dialog = RunnerConfigDialog(runner, parent=self.dialog)
  File "/parent/work/winegame/lutris/lutris/gui/config/runner.py", line 23, in __init__
    self.build_tabs("runner")
  File "/parent/work/winegame/lutris/lutris/gui/config/common.py", line 75, in build_tabs
    self._build_runner_tab(config_level)
  File "/parent/work/winegame/lutris/lutris/gui/config/common.py", line 354, in _build_runner_tab
    self.runner_box = RunnerBox(self.lutris_config, self.game)
  File "/parent/work/winegame/lutris/lutris/gui/config/boxes.py", line 645, in __init__
    self.generate_widgets("runner")
  File "/parent/work/winegame/lutris/lutris/gui/config/boxes.py", line 99, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/parent/work/winegame/lutris/lutris/gui/config/boxes.py", line 164, in call_widget_generator
    self.generate_combobox(option_key, option["choices"], option["label"], value, default)
  File "/parent/work/winegame/lutris/lutris/gui/config/boxes.py", line 315, in generate_combobox
    self._populate_combobox_choices(liststore, choices, default)
  File "/parent/work/winegame/lutris/lutris/gui/config/boxes.py", line 302, in _populate_combobox_choices
    for choice in choices:
TypeError: 'staticmethod' object is not iterable
INFO     2020-06-18 04:42:39,843 [application.do_shutdown:522]:Shutting down Lutris
```
