### ISSUE TITLE
Error with preferences related to glxinfo

### ISSUE THREAD

**Issue by StelFux** [lutris/lutris#2768]
**Describe the bug**
It is impossible to launch preferences. When the button is clicked, nothing happens.

**Expected behavior**
Uh, run the preferences

**Current behavior**
Nothing

**Steps to reproduce**
- launch Lutris on Fedora 32 Beta
- try to launch preferences

**Lutris debugging output**
```
INFO     2020-04-18 12:24:39,182 [application.do_command_line:245]:Running Lutris 0.5.5
INFO     2020-04-18 12:24:39,183 [startup.check_driver:62]:Using Intel Open Source Technology Center
INFO     2020-04-18 12:24:39,183 [startup.check_driver:64]:Running Mesa driver 20.0.4 on Mesa DRI Intel(R) G45/G43 (ELK) (0x2e22)
INFO     2020-04-18 12:24:39,183 [startup.check_driver:77]:GPU: 8086:2E22 1028:0439 using i915 drivers
INFO     2020-04-18 12:24:39,257 [startup.check_vulkan:134]:Vulkan is not available or your system isn't Vulkan capable
INFO     2020-04-18 12:24:39,258 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-04-18 12:24:39,606 [store.get_missing_media:209]:Requesting missing icons from API for worms-4-mayhem, mindustry
DEBUG    2020-04-18 12:24:39,607 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-04-18 12:24:39,621 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-04-18 12:24:39,632 [lutriswindow.toggle_connection:642]:Connected to lutris.net as Coles
DEBUG    2020-04-18 12:24:39,648 [http.get:65]:GET https://lutris.net/api/games/library/Coles
DEBUG    2020-04-18 12:24:40,155 [api.get_game_api_page:132]:Loaded 2 games from page 1

(lutris:41827): Gtk-CRITICAL **: 12:24:40.821: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/generic_panel.py", line 99, in on_preferences_clicked
    SystemConfigDialog(get_main_window(button))
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/system.py", line 18, in __init__
    self.build_tabs("system")
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/common.py", line 78, in build_tabs
    self._build_sysinfo_tab()
  File "/usr/lib/python3.8/site-packages/lutris/gui/config/common.py", line 122, in _build_sysinfo_tab
    sysinfo_str = gather_system_info_str()
  File "/usr/lib/python3.8/site-packages/lutris/util/linux.py", line 474, in gather_system_info_str
    graphics_dict["OpenGL Core"] = system_info["glxinfo"]["opengl_core_profile_version"]
KeyError: 'opengl_core_profile_version'
```

**System information**
[lutris-issue-report.json](https://github.com/lutris/lutris/files/4496463/lutris-issue-report.json.txt)

**Comment by strycore** [comment]
Fixed in master
