### ISSUE TITLE
The mame package is missing from the setup.py

### ISSUE THREAD

**Issue by Steinhagen** [lutris/lutris#2783]
**Describe the bug**
The mame package is missing from the setup.py

**Current behavior**
Traceback (most recent call last):
  File "/usr/bin/lutris", line 40, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 54, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 28, in <module>
    from lutris.gui.widgets.sidebar import SidebarListBox
  File "/usr/lib/python3.8/site-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms
  File "/usr/lib/python3.8/site-packages/lutris/platforms.py", line 17, in <module>
    _init_platforms()
  File "/usr/lib/python3.8/site-packages/lutris/platforms.py", line 12, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3.8/site-packages/lutris/runners/__init__.py", line 79, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/usr/lib/python3.8/site-packages/lutris/runners/__init__.py", line 72, in get_runner_module
    return __import__(
  File "/usr/lib/python3.8/site-packages/lutris/runners/mame.py", line 9, in <module>
    from lutris.util.mame.database import get_supported_systems
ModuleNotFoundError: No module named 'lutris.util.mame'

**Steps to reproduce**
1. Run Lutris

**Comment by Steinhagen** [comment]
The fix was merged into the master branch.
