### ISSUE TITLE
Vortex Mod Manager crashes on start-up

### ISSUE THREAD

**Issue by hikagura99** [lutris/lutris#2797]
Yesterday I installed Vortex Mod Manager from the lutris.net installer, and it worked flawlessly right after that. But after i closed it and re-opened it after a while, this error keeps popping out

```
net.js:314
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:314:26)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object.<anonymous> (electron/js2c/browser_init.js:5669:13)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5824:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
```

I don't know what it could possibly be. I've got .net installed in the bottle from the 4.2 up until the latest one, and, as I said before, the program ran with no problems at all the first time.

**Comment by rockerbacon** [comment]
This is a known problem. Please refer to this issue on the official repo for the Vortex installer for details on why it happens and how to fix it:

https://github.com/rockerbacon/lutris-skyrimse-installers/issues/17

**Comment by hikagura99** [comment]
> This is a known problem. Please refer to this issue on the official repo for the Vortex installer for details on why it happens and how to fix it:
> 
> [rockerbacon/lutris-skyrimse-installers#17](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/17)
Thank you kindly, fixed it
