### ISSUE TITLE
Weird log with DOSBox

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2823]
Hello,

I saw this in my log when I launched a DOSBox game:
```

2020-05-01 00:23:19,258: Ultima Worlds of Adventure 2 - Martian Dreams - DOSBox stopped at ven., 01 mai 2020 00:23:19
2020-05-01 00:23:19,258: Saving Ultima Worlds of Adventure 2 - Martian Dreams - DOSBox (dosbox)
2020-05-01 00:23:19,316: Updating game Ultima Worlds of Adventure 2 - Martian Dreams - DOSBox (dosbox)
Traceback (most recent call last):
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/game.py", line 597, in beat
    self.on_game_quit()
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/game.py", line 652, in on_game_quit
    DISPLAY_MANAGER.set_resolution(self.original_outputs)
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/util/graphics/displayconfig.py", line 659, in set_resolution
    self.display_config.apply_monitors_config(resolution)
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/util/graphics/displayconfig.py", line 580, in apply_monitors_config
    self.resources = self.interface.GetResources()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.28437 was not provided by any .service files
```

**Comment by legluondunet** [comment]
can not reproduce, I  will reopen it later if necessary.
