### ISSUE TITLE
Lutris will not open

### ISSUE THREAD

**Issue by SmashleyG** [lutris/lutris#283]
Kubuntu 16.04

Installed 6/may/16. 

When trying to open through application menu, it shows up in my panel but then disappears. Opening through a terminal give the following output: 

Traceback (most recent call last):
  File "/usr/bin/lutris", line 43, in <module>
    from lutris.gui import dialogs
  File "/usr/lib/python2.7/dist-packages/lutris/gui/dialogs.py", line 6, in <module>
    from lutris import api, pga, runtime, settings
  File "/usr/lib/python2.7/dist-packages/lutris/api.py", line 8, in <module>
    from lutris.util import http
  File "/usr/lib/python2.7/dist-packages/lutris/util/http.py", line 6, in <module>
    from lutris.util.log import logger
  File "/usr/lib/python2.7/dist-packages/lutris/util/log.py", line 17, in <module>
    backupCount=5)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/ashley/.cache/lutris/lutris.log'

lutris log:

[ERROR:2016-05-06 19:58:19,956:api]: Unable to connect to server (https://lutris.net/api/accounts/token): HTTP Error 400: Bad Request
[ERROR:2016-05-06 19:58:40,112:api]: Unable to connect to server (https://lutris.net/api/accounts/token): HTTP Error 400: Bad Request
[ERROR:2016-05-06 19:58:57,541:api]: Unable to connect to server (https://lutris.net/api/accounts/token): HTTP Error 400: Bad Request

Though when I run it with sudo, it opens. 

If you require any more information, just ask :)

**Comment by strycore** [comment]
Fix the permissions of your files in ~/.cache so you can write to the log files

sudo chown -R yourusername:yourusername  ~/.cache
