### ISSUE TITLE
Lutris Crashes on Startup on Kubuntu 20.04

### ISSUE THREAD

**Issue by Jovonnus** [lutris/lutris#2853]
**A clear and concise description of what the bug is:
After installing on Kubuntu 20.04, Lutris fails to start. The following is output when starting in a terminal:

[jovonne@jss-cq60 ~]$ lutris
2020-05-08 21:07:25,442: Running Lutris 0.5.6
2020-05-08 21:07:25,442: Running migration: fix_playtime
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 246, in do_command_line
    migrate()
  File "/usr/lib/python3/dist-packages/lutris/migrations/__init__.py", line 31, in migrate
    migration.migrate()
  File "/usr/lib/python3/dist-packages/lutris/migrations/fix_playtime.py", line 23, in migrate
    fix_playtime(game)
  File "/usr/lib/python3/dist-packages/lutris/migrations/fix_playtime.py", line 9, in fix_playtime
    if not broken_playtime.endswith(" hrs"):
AttributeError: 'float' object has no attribute 'endswith'
2020-05-08 21:07:25,500: Shutting down Lutris
[jovonne@jss-cq60 ~]$

**Expected behavior**
The program should start with a GUI window.

**Current behavior**
Nothing. No perceptible activity.

**Steps to reproduce**
Start program from KDE panel menu

**Lutris debugging output**
[jovonne@jss-cq60 ~]$ lutris -d
INFO     2020-05-08 21:37:29,820 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-05-08 21:37:29,838 [__init__.migrate:29]:Running migration: fix_playtime
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 246, in do_command_line
    migrate()
  File "/usr/lib/python3/dist-packages/lutris/migrations/__init__.py", line 31, in migrate
    migration.migrate()
  File "/usr/lib/python3/dist-packages/lutris/migrations/fix_playtime.py", line 23, in migrate
    fix_playtime(game)
  File "/usr/lib/python3/dist-packages/lutris/migrations/fix_playtime.py", line 9, in fix_playtime
    if not broken_playtime.endswith(" hrs"):
AttributeError: 'float' object has no attribute 'endswith'
INFO     2020-05-08 21:37:29,946 [application.do_shutdown:491]:Shutting down Lutris
[jovonne@jss-cq60 ~]$ 

**System information**
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-29-generic
OS Type: 64-bit
Processors: 2 × Pentium® Dual-Core CPU T4300 @ 2.10GHz
Memory: 2.9 GiB of RAM

**Screenshots**
None

**Comment by AlexanderRavenheart** [comment]
Fresh install of Lutris?

**Comment by Jovonnus** [comment]
Yes, fresh install. I followed the instructions on the Lutris web site for
Ubuntu installation:


sudo add-apt-repository ppa:lutris-team/lutris
sudo apt-get update
sudo apt-get install lutris

Best regards,


Jovonne




On 05/09/2020 at 00:13, Alexandru Rudi <notifications@github.com> wrote:
Fresh install of Lutris?

**Comment by enboig** [comment]
I applied https://github.com/lutris/lutris/commit/02e6a5c2f55c84bcf03448ae29efcf3a603fb64b manually and it works. I hope next release will have this fix.

**Comment by strycore** [comment]
The migration bug is fixed in master
