### ISSUE TITLE
Lutris fails to launch everything (even steam games) (probably problem with my python)

### ISSUE THREAD

**Issue by Casul51** [lutris/lutris#2863]
OS: Manjaro

Well I reinstalled Lutris few times (from AUR too) and python and always the same - click "Play", few seconds shows that it works and stops. In game logs: (tested with different settings presets)

```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.8/io.py", line 52, in <module>
  File "/usr/lib/python3.8/abc.py", line 106
    print(f"Class: {cls.__module__}.{cls.__qualname__}", file=file)
                                                      ^
SyntaxError: invalid syntax

```

```
$ lutris

(lutris:4953): Gtk-WARNING **: 19:18:21.025: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:4953): Gtk-WARNING **: 19:18:21.025: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:4953): Gtk-WARNING **: 19:18:21.025: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
2020-05-11 19:18:21,269: Running Lutris 0.5.6
2020-05-11 19:18:21,269: Using NVIDIA drivers 440.82 for x86_64
2020-05-11 19:18:21,269: GPU: GeForce GTX 970
2020-05-11 19:18:21,270: GPU: 1002:6611 1B0A:90D3 using radeon drivers
2020-05-11 19:18:21,270: GPU: 10DE:13C2 1458:3679 using nvidia drivers
2020-05-11 19:18:21,333: Vulkan is supported
2020-05-11 19:18:21,334: Updating DXVK versions

(lutris:4953): Gtk-WARNING **: 19:18:21.365: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:4953): Gtk-WARNING **: 19:18:21.365: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:4953): Gtk-WARNING **: 19:18:21.365: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:4953): Gtk-WARNING **: 19:18:21.365: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:4953): Gtk-WARNING **: 19:18:21.365: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
2020-05-11 19:18:25,148: Runtime disabled by system configuration
2020-05-11 19:18:25,154: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,154: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,206: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,247: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,247: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,247: Replacing /home/casual/.wine/drive_c/windows/system32/dxgi with DXVK version
2020-05-11 19:18:25,248: Replacing /home/casual/.wine/drive_c/windows/system32/d3d11 with DXVK version
2020-05-11 19:18:25,248: Replacing /home/casual/.wine/drive_c/windows/system32/d3d10core with DXVK version
2020-05-11 19:18:25,249: Replacing /home/casual/.wine/drive_c/windows/system32/d3d9 with DXVK version
2020-05-11 19:18:25,250: Replacing /home/casual/.wine/drive_c/windows/syswow64/dxgi with DXVK version
2020-05-11 19:18:25,250: Replacing /home/casual/.wine/drive_c/windows/syswow64/d3d11 with DXVK version
2020-05-11 19:18:25,250: Replacing /home/casual/.wine/drive_c/windows/syswow64/d3d10core with DXVK version
2020-05-11 19:18:25,251: Replacing /home/casual/.wine/drive_c/windows/syswow64/d3d9 with DXVK version
2020-05-11 19:18:25,252: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,252: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,371: Runtime disabled by system configuration
2020-05-11 19:18:25,371: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,371: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2020-05-11 19:18:25,371: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
gamemodeauto: 
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.8/io.py", line 52, in <module>
  File "/usr/lib/python3.8/abc.py", line 106
    print(f"Class: {cls.__module__}.{cls.__qualname__}", file=file)
                                                      ^
SyntaxError: invalid syntax
2020-05-11 19:18:27,418: Game still running (state: running)
2020-05-11 19:18:27,418: Stopping Noita (wine)
2020-05-11 19:19:14,176: Runtime disabled by system configuration
2020-05-11 19:19:14,252: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/dxgi with DXVK version
2020-05-11 19:19:14,253: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/d3d11 with DXVK version
2020-05-11 19:19:14,253: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/d3d10core with DXVK version
2020-05-11 19:19:14,254: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/d3d9 with DXVK version
2020-05-11 19:19:14,254: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/dxgi with DXVK version
2020-05-11 19:19:14,255: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/d3d11 with DXVK version
2020-05-11 19:19:14,255: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/d3d10core with DXVK version
2020-05-11 19:19:14,256: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/d3d9 with DXVK version
2020-05-11 19:19:14,375: Runtime disabled by system configuration
gamemodeauto: 
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.8/io.py", line 52, in <module>
  File "/usr/lib/python3.8/abc.py", line 106
    print(f"Class: {cls.__module__}.{cls.__qualname__}", file=file)
                                                      ^
SyntaxError: invalid syntax
2020-05-11 19:19:16,433: Game still running (state: running)
2020-05-11 19:19:16,434: Stopping Noita (wine)
```

**Comment by strycore** [comment]
Reenable the runtime

**Comment by Casul51** [comment]
> Reenable the runtime

I am sorry, but what does this mean?

**Comment by strycore** [comment]
You have this:
> 2020-05-11 19:18:25,148: Runtime disabled by system configuration

So it means that the runtime gets disabled at some point.

I also see this: 
> 2020-05-11 19:18:25,154: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.

This means that your setup is likely completely broken and you haven't installed lutris the proper way.

**Comment by Casul51** [comment]
Nothing changed

```
$ lutris

(lutris:6434): Gtk-WARNING **: 21:21:57.604: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:6434): Gtk-WARNING **: 21:21:57.604: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:6434): Gtk-WARNING **: 21:21:57.604: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
2020-05-11 21:21:57,871: Running Lutris 0.5.6
2020-05-11 21:21:57,872: Using NVIDIA drivers 440.82 for x86_64
2020-05-11 21:21:57,872: GPU: GeForce GTX 970
2020-05-11 21:21:57,872: GPU: 1002:6611 1B0A:90D3 using radeon drivers
2020-05-11 21:21:57,872: GPU: 10DE:13C2 1458:3679 using nvidia drivers
2020-05-11 21:21:57,941: Vulkan is supported
2020-05-11 21:21:57,942: Updating DXVK versions

(lutris:6434): Gtk-WARNING **: 21:21:57.984: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:6434): Gtk-WARNING **: 21:21:57.984: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:6434): Gtk-WARNING **: 21:21:57.984: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:6434): Gtk-WARNING **: 21:21:57.984: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:6434): Gtk-WARNING **: 21:21:57.984: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
2020-05-11 21:22:01,305: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/dxgi with DXVK version
2020-05-11 21:22:01,306: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/d3d11 with DXVK version
2020-05-11 21:22:01,306: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/d3d10core with DXVK version
2020-05-11 21:22:01,307: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/system32/d3d9 with DXVK version
2020-05-11 21:22:01,307: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/dxgi with DXVK version
2020-05-11 21:22:01,308: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/d3d11 with DXVK version
2020-05-11 21:22:01,308: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/d3d10core with DXVK version
2020-05-11 21:22:01,309: Replacing /home/casual/Games/WineSomething/WinePrefix/drive_c/windows/syswow64/d3d9 with DXVK version
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.8/io.py", line 52, in <module>
  File "/usr/lib/python3.8/abc.py", line 106
    print(f"Class: {cls.__module__}.{cls.__qualname__}", file=file)
                                                      ^
SyntaxError: invalid syntax
2020-05-11 21:22:03,503: Game still running (state: running)
2020-05-11 21:22:03,503: Stopping isaac (wine)

```

**Comment by Casul51** [comment]
I tried to run on another user and this worked!

**Comment by strycore** [comment]
yeah, sure.
Your setup is deeply borked,
Sorry.
