### ISSUE TITLE
GOG scripts does nothing

### ISSUE THREAD

**Issue by Amathadius** [lutris/lutris#2865]
**Describe the bug**

After selecting the installation destination and pressing "Install", nothing happens.
I tried with several GOG scripts and nothing. The install button is replaced by "cancel", but that's it. Nothing happens.
The folder doesn't even create itself and if the folder is already created, it stays empty.

**Expected behavior**
That something happens

**Current behavior**

Nothing happens: not freezing, not crashing, nothing. 

**Steps to reproduce**

- Go to lutris.net
- Running an installation script for a GOG game

**Lutris debugging output**

```
2020-05-11 18:36:08,720: Fetching installer https://lutris.net/api/installers/dishonored-gog
2020-05-11 18:36:08,720: GET https://lutris.net/api/installers/dishonored-gog
2020-05-11 18:36:35,313: Required runners: [<lutris.runners.wine.wine object at 0x7fbe0f3c6d00>]
2020-05-11 18:36:35,313: Getting runner information for wine
2020-05-11 18:36:35,313: GET https://lutris.net/api/runners/wine
2020-05-11 18:36:36,021: Default wine version is lutris-5.6-2
2020-05-11 18:36:36,026: GET https://embed.gog.com/userData.json
2020-05-11 18:36:36,565: GET https://embed.gog.com/userData.json
2020-05-11 18:36:36,980: Getting game details for 1701063787
2020-05-11 18:36:36,981: GET https://api.gog.com/products/1701063787?expand=downloads
2020-05-11 18:36:37,645: Getting download info for http://api.gog.com/products/1701063787/downlink/installer/en1installer0
2020-05-11 18:36:37,645: GET http://api.gog.com/products/1701063787/downlink/installer/en1installer0
2020-05-11 18:36:38,609: Failed to request http://api.gog.com/products/1701063787/downlink/installer/en1installer0, check your GOG credentials and internet connectivity
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 247, in on_install_clicked
    self.interpreter.check_runner_install()
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 513, in check_runner_install
    self.install_runners()
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 520, in install_runners
    self.prepare_game_files()
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 383, in prepare_game_files
    self.swap_gog_game_files()
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 327, in swap_gog_game_files
    links = get_gog_download_links(self.gogid, self.runner)
  File "/usr/lib/python3.8/site-packages/lutris/services/gog.py", line 317, in get_gog_download_links
    download_info = gog_service.get_download_info(downlink)
  File "/usr/lib/python3.8/site-packages/lutris/services/gog.py", line 203, in get_download_info
    field_url = response[field]
TypeError: 'NoneType' object is not subscriptable
```

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

```
{
  "comment": "\nAfter selecting the installation destination and pressing \"Install\", nothing happens.\nI tried with several GOG scripts and nothing. The install button is replaced by \"cancel\", but that's it. Nothing happens.\nThe folder doesn't even create itself and if the folder is already created, it stays empty.",
  "system": {
    "gpus": [
      {
        "DRIVER": "amdgpu",
        "PCI_ID": "1002:67DF",
        "PCI_SUBSYS_ID": "1682:C580",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:01:00.0",
        "MODALIAS": "pci:v00001002d000067DFsv00001682sd0000C580bc03sc00i00"
      }
    ],
    "env": {
      "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
      "SESSION_MANAGER": "local/mthBureau:@/tmp/.ICE-unix/2592,unix/mthBureau:/tmp/.ICE-unix/2592",
      "LANG": "fr_CA.UTF-8",
      "XDG_CURRENT_DESKTOP": "GNOME",
      "PWD": "/home/mathieu",
      "TILIX_ID": "195a8d42-7227-4867-88ce-98f1a503fd7d",
      "COLORTERM": "truecolor",
      "QT_IM_MODULE": "ibus",
      "XDG_SESSION_DESKTOP": "gnome-xorg",
      "XDG_DATA_HOME": "/home/mathieu/.local/share",
      "XDG_CONFIG_HOME": "/home/mathieu/.config",
      "XDG_MENU_PREFIX": "gnome-",
      "USER": "mathieu",
      "DESKTOP_SESSION": "gnome-xorg",
      "PARALLEL_HOME": "/home/mathieu/.config/parallel",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus,guid=e4551a84ae5d189fc8d1606d5eb95314",
      "SDL_GAMECONTROLLERCONFIG": "050000005e040000e002000030110000,8BitDo SN30 Pro+,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,",
      "HOME": "/home/mathieu",
      "WINDOWPATH": "2",
      "JOURNAL_STREAM": "9:65791",
      "XDG_CACHE_HOME": "/home/mathieu/.cache",
      "VTE_VERSION": "6002",
      "GNUPGHOME": "/home/mathieu/.local/share/gnupg",
      "MANAGERPID": "2504",
      "MOZ_WEBRENDER": "1",
      "MAIL": "/var/spool/mail/mathieu",
      "LOGNAME": "mathieu",
      "PATH": "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "XMODIFIERS": "@im=ibus",
      "WINEPREFIX": "/home/mathieu/.local/share/wineprefixes/default",
      "SHELL": "/usr/bin/zsh",
      "DBUS_STARTER_BUS_TYPE": "session",
      "XDG_SESSION_TYPE": "x11",
      "USERNAME": "mathieu",
      "INVOCATION_ID": "56a0aa560c6c4f10beaa018a16271969",
      "SHLVL": "1",
      "XAUTHORITY": "/run/user/1000/gdm/Xauthority",
      "GDM_LANG": "fr_CA.UTF-8",
      "DBUS_STARTER_ADDRESS": "unix:path=/run/user/1000/bus,guid=e4551a84ae5d189fc8d1606d5eb95314",
      "DISPLAY": ":0",
      "XDG_SESSION_CLASS": "user",
      "GDMSESSION": "gnome-xorg",
      "TERM": "xterm-256color",
      "OLDPWD": "/home/mathieu",
      "ZDOTDIR": "/home/mathieu/.config/zsh",
      "HISTFILE": "/home/mathieu/.local/share/zsh/zsh_history",
      "ZSH": "/home/mathieu/.local/share/oh-my-zsh",
      "PAGER": "less",
      "LESS": "-R",
      "LSCOLORS": "Gxfxcxdxbxegedabagacad",
      "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
      "_": "/usr/bin/lutris"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [],
        []
      ],
      "RADEON": [
        [
          "libvulkan_radeon.so"
        ],
        [
          "libvulkan_radeon.so"
        ]
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "94",
        "model name": "Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz",
        "stepping": "3",
        "microcode": "0xd6",
        "cpu MHz": "3700.167",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "0",
        "cpu cores": "2",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "vmx flags": "vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7402.02",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "1",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "94",
        "model name": "Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz",
        "stepping": "3",
        "microcode": "0xd6",
        "cpu MHz": "3700.208",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "1",
        "cpu cores": "2",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "vmx flags": "vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7402.02",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "2",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "94",
        "model name": "Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz",
        "stepping": "3",
        "microcode": "0xd6",
        "cpu MHz": "3700.385",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "0",
        "cpu cores": "2",
        "apicid": "1",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "vmx flags": "vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7402.02",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "3",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "94",
        "model name": "Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz",
        "stepping": "3",
        "microcode": "0xd6",
        "cpu MHz": "3700.055",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "1",
        "cpu cores": "2",
        "apicid": "3",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "vmx flags": "vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7402.02",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "fsver": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sda1",
            "fstype": "vfat",
            "fsver": "FAT32",
            "label": null,
            "uuid": "DDB0-50F6",
            "fsavail": "510,7M",
            "fsuse%": "0%",
            "mountpoint": "/boot/efi"
          },
          {
            "name": "sda2",
            "fstype": "ext4",
            "fsver": "1.0",
            "label": null,
            "uuid": "70b67ba8-8b59-4f59-9abd-831f3f5f79c1",
            "fsavail": "49,9G",
            "fsuse%": "84%",
            "mountpoint": "/"
          }
        ]
      },
      {
        "name": "sdb",
        "fstype": null,
        "fsver": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdb1",
            "fstype": "ext4",
            "fsver": "1.0",
            "label": "WDC",
            "uuid": "11639865-6113-4903-9b77-5c9b4b4a629d",
            "fsavail": "54,9G",
            "fsuse%": "89%",
            "mountpoint": "/mnt/WDC"
          },
          {
            "name": "sdb2",
            "fstype": "swap",
            "fsver": "1",
            "label": null,
            "uuid": "8bdfde50-fe07-4cd2-8075-6977c143ea73",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sdc",
        "fstype": null,
        "fsver": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdc1",
            "fstype": "ntfs",
            "fsver": null,
            "label": "iOmega_320",
            "uuid": "9C8AC0068ABFDACA",
            "fsavail": "54,2G",
            "fsuse%": "82%",
            "mountpoint": "/run/media/mathieu/iOmega_320"
          }
        ]
      }
    ],
    "ram": {
      "MemTotal": "16361068",
      "MemFree": "772100",
      "MemAvailable": "12656728",
      "Buffers": "222464",
      "Cached": "11716776",
      "SwapCached": "0",
      "Active": "8837696",
      "Inactive": "6138924",
      "Active(anon)": "3042640",
      "Inactive(anon)": "80600",
      "Active(file)": "5795056",
      "Inactive(file)": "6058324",
      "Unevictable": "16",
      "Mlocked": "16",
      "SwapTotal": "0",
      "SwapFree": "0",
      "Dirty": "2088",
      "Writeback": "0",
      "AnonPages": "3037400",
      "Mapped": "431536",
      "Shmem": "85864",
      "KReclaimable": "372344",
      "Slab": "465424",
      "SReclaimable": "372344",
      "SUnreclaim": "93080",
      "KernelStack": "14944",
      "PageTables": "33204",
      "NFS_Unstable": "0",
      "Bounce": "0",
      "WritebackTmp": "0",
      "CommitLimit": "8180532",
      "Committed_AS": "9084060",
      "VmallocTotal": "34359738367",
      "VmallocUsed": "32808",
      "VmallocChunk": "0",
      "Percpu": "2384",
      "HardwareCorrupted": "0",
      "AnonHugePages": "0",
      "ShmemHugePages": "0",
      "ShmemPmdMapped": "0",
      "FileHugePages": "0",
      "FilePmdMapped": "0",
      "HugePages_Total": "0",
      "HugePages_Free": "0",
      "HugePages_Rsvd": "0",
      "HugePages_Surp": "0",
      "Hugepagesize": "2048",
      "Hugetlb": "0",
      "DirectMap4k": "403996",
      "DirectMap2M": "11094016",
      "DirectMap1G": "5242880"
    },
    "dist": [
      "Arch Linux",
      "rolling",
      "n/a"
    ],
    "arch": "x86_64",
    "kernel": "5.6.11-arch1-1",
    "glxinfo": {
      "opengl_profile_mask": "compatibility profile",
      "name_of_display": ":0",
      "opengl_core_profile_context_flags": "(none)",
      "opengl_core_profile_shading_language_version": "4.60",
      "screen": "0",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "direct_rendering": "Yes",
      "display": ":0",
      "opengl_core_profile_profile_mask": "core profile",
      "opengl_shading_language_version": "4.60",
      "opengl_version": "4.6 (Compatibility Profile) Mesa 20.0.6",
      "opengl_es_profile_version": "OpenGL ES 3.2 Mesa 20.0.6",
      "opengl_renderer": "Radeon RX 580 Series (POLARIS10, DRM 3.36.0, 5.6.11-arch1-1, LLVM 10.0.0)",
      "opengl_context_flags": "(none)",
      "opengl_vendor": "X.Org",
      "opengl_core_profile_version": "4.6 (Core Profile) Mesa 20.0.6"
    }
  }
}
```

**Comment by TheBrainScrambler** [comment]
"2020-05-11 18:36:38,609: Failed to request http://api.gog.com/products/1701063787/downlink/installer/en1installer0, **check your GOG credentials and internet connectivity**"
Did you synced your GOG account with Lutris ?
Try the following steps :
- Open Lutris
- Click "+" > "Import Games..."
- Select the GOG icon, and then log in to your account from there
- Once it is done, try to launch GOG scripts again

**Comment by Amathadius** [comment]
I actually stopped synchronizing my GOG account with Lutris because it was badly managed at the beginning (minimal interface with many games never make a good match) in addition to not seeing the interest of synchronization without any advantage and that downloading manually (and controlling the download) and launching the script by lutris.net is still better. In short, that was indeed the problem. Thank you for that.
