### ISSUE TITLE
Lutris will not start after Fedora 32 updates

### ISSUE THREAD

**Issue by Eric-Foote** [lutris/lutris#2867]
**Describe the bug**

Everytime I try to start lutris on my machine after the update it will not even start and will crash trying to open up. This has been happening since I did updates on May 10th on Fedora 32 

lutris -d in the terminal gives this output:

INFO     2020-05-12 09:53:50,721 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-05-12 09:53:50,721 [__init__.migrate:29]:Running migration: fix_playtime
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 246, in do_command_line
    migrate()
  File "/usr/lib/python3.8/site-packages/lutris/migrations/__init__.py", line 31, in migrate
    migration.migrate()
  File "/usr/lib/python3.8/site-packages/lutris/migrations/fix_playtime.py", line 23, in migrate
    fix_playtime(game)
  File "/usr/lib/python3.8/site-packages/lutris/migrations/fix_playtime.py", line 9, in fix_playtime
    if not broken_playtime.endswith(" hrs"):
AttributeError: 'float' object has no attribute 'endswith'
INFO     2020-05-12 09:53:50,757 [application.do_shutdown:491]:Shutting down Lutris

lutris --submit-issue will not even output anything

![Screenshot from 2020-05-12 09-55-28](https://user-images.githubusercontent.com/10342826/81693802-d4597a00-9436-11ea-8e19-5ecf47f61b55.png)
[soappoison@soappoison ~]$ lutris --submit-issue
2020-05-12 09:54:34,660: Running Lutris 0.5.6
2020-05-12 09:54:34,661: Running migration: fix_playtime
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 246, in do_command_line
    migrate()
  File "/usr/lib/python3.8/site-packages/lutris/migrations/__init__.py", line 31, in migrate
    migration.migrate()
  File "/usr/lib/python3.8/site-packages/lutris/migrations/fix_playtime.py", line 23, in migrate
    fix_playtime(game)
  File "/usr/lib/python3.8/site-packages/lutris/migrations/fix_playtime.py", line 9, in fix_playtime
    if not broken_playtime.endswith(" hrs"):
AttributeError: 'float' object has no attribute 'endswith'
2020-05-12 09:54:34,699: Shutting down Lutris

I have tried removing and reinstalling lutris multiple times
I have tried compiling from github and have had no success

**Comment by Eric-Foote** [comment]
I got it to work finally,

Here is what I did 

I edited the application.py file and commented out the function call to migrate()

After that I deleted everything to do with MangoHud and it seemed to work 

![Screenshot from 2020-05-12 15-37-47](https://user-images.githubusercontent.com/10342826/81732497-f7038700-9466-11ea-8659-c36089454ba0.png)

**Comment by byte1024** [comment]
Funny, I was literally just about done making a comment and didn't want to post that because of not knowing if it would have any side effects.

They already know about the issue with migrate and it was failing on the fix. It still needs to be fixed technically but there is at least one other issue already open with this problem so closing should be OK.
