### ISSUE TITLE
Can't install Linux Steam runner

### ISSUE THREAD

**Issue by mlms13** [lutris/lutris#2914]
**Describe the bug**

I'm unable to install the Steam (for Linux) runner. The error when running Lutris from the command line is:

```sh
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/runners.py", line 134, in on_install_clicked
    runner.install(downloader=simple_downloader)
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 269, in install
    raise NonInstallableRunnerError(
lutris.runners.NonInstallableRunnerError: Steam for Linux installation is not handled by Lutris.
Please go to <a href='http://steampowered.com'>http://steampowered.com</a> or install Steam with the package provided by your distribution.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/runners.py", line 139, in on_install_clicked
    ErrorDialog(ex.message, parent=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/__init__.py", line 92, in __init__
    super().__init__(buttons=Gtk.ButtonsType.OK, parent=parent)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 577, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 523, in __init__
    _window_init(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
TypeError: could not convert value for property `transient_for' from RunnersDialog to GtkWindow
```
I currently have Steam installed as a Flatpak on Pop!_OS 20.04.

**System Information**

```json
{
  "comment": "",
  "system": {
    "gpus": [
      {
        "DRIVER": "i915",
        "PCI_ID": "8086:5917",
        "PCI_SUBSYS_ID": "17AA:225C",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:00:02.0",
        "MODALIAS": "pci:v00008086d00005917sv000017AAsd0000225Cbc03sc00i00"
      }
    ],
    "env": {
      "LC_TELEPHONE": "en_US.UTF-8",
      "GJS_DEBUG_OUTPUT": "stderr",
      "GDMSESSION": "pop",
      "DESKTOP_SESSION": "pop",
      "PWD": "/home/michael",
      "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
      "LOGNAME": "michael",
      "MANDATORY_PATH": "/usr/share/gconf/pop.mandatory.path",
      "LC_MEASUREMENT": "en_US.UTF-8",
      "XDG_SESSION_TYPE": "x11",
      "PATH": "/tmp/fnm-shell-8191881/bin:/home/michael/.fnm:/home/michael/.npm-global/bin:./node_modules/.bin:/home/michael/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games",
      "HOME": "/home/michael",
      "USERNAME": "michael",
      "GIO_LAUNCHED_DESKTOP_FILE": "/usr/share/applications//guake.desktop",
      "QT_IM_MODULE": "ibus",
      "USER": "michael",
      "DISPLAY": ":1",
      "INVOCATION_ID": "210ca6c614514694b2acda942b990805",
      "GDK_BACKEND": "x11",
      "JOURNAL_STREAM": "9:35674",
      "LANG": "en_US.UTF-8",
      "LC_NAME": "en_US.UTF-8",
      "CLUTTER_IM_MODULE": "ibus",
      "XAUTHORITY": "/run/user/1000/gdm/Xauthority",
      "LC_PAPER": "en_US.UTF-8",
      "LANGUAGE": "en_US:en",
      "SESSION_MANAGER": "local/pop-os:@/tmp/.ICE-unix/1742,unix/pop-os:/tmp/.ICE-unix/1742",
      "GIO_LAUNCHED_DESKTOP_FILE_PID": "13380",
      "IM_CONFIG_PHASE": "1",
      "SSH_AGENT_PID": "1620",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "XDG_DATA_DIRS": "/usr/share/pop:/home/michael/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/",
      "XDG_SESSION_DESKTOP": "pop",
      "QT4_IM_MODULE": "ibus",
      "VTE_VERSION": "6001",
      "XDG_CURRENT_DESKTOP": "pop:GNOME",
      "SHLVL": "1",
      "XDG_CONFIG_DIRS": "/etc/xdg/xdg-pop:/etc/xdg",
      "_": "/usr/games/lutris",
      "LC_ADDRESS": "en_US.UTF-8",
      "SHELL": "/usr/bin/zsh",
      "GPG_AGENT_INFO": "/run/user/1000/gnupg/S.gpg-agent:0:1",
      "XDG_SESSION_CLASS": "user",
      "GTK_IM_MODULE": "ibus",
      "LC_IDENTIFICATION": "en_US.UTF-8",
      "GTK_MODULES": "gail:atk-bridge:appmenu-gtk-module",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
      "PAPERSIZE": "letter",
      "MANAGERPID": "1408",
      "DEFAULTS_PATH": "/usr/share/gconf/pop.default.path",
      "XMODIFIERS": "@im=ibus",
      "GJS_DEBUG_TOPICS": "JS ERROR;JS LOG",
      "LC_NUMERIC": "en_US.UTF-8",
      "GNOME_SHELL_SESSION_MODE": "pop",
      "TERM": "xterm-256color",
      "XDG_MENU_PREFIX": "gnome-",
      "COLORTERM": "truecolor",
      "LC_TIME": "en_US.UTF-8",
      "WINDOWPATH": "2",
      "QT_ACCESSIBILITY": "1",
      "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
      "LC_MONETARY": "en_US.UTF-8",
      "OLDPWD": "/home/michael/Dropbox/Documents/ToDo Lists",
      "ZSH": "/home/michael/.oh-my-zsh",
      "PAGER": "less",
      "LESS": "-R",
      "LSCOLORS": "Gxfxcxdxbxegedabagacad",
      "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
      "PROMPT_EOL_MARK": "",
      "CONDA_CHANGEPS1": "no",
      "EDITOR": "vi",
      "VISUAL": "vi",
      "FNM_MULTISHELL_PATH": "/tmp/fnm-shell-8191881",
      "FNM_DIR": "/home/michael/.fnm",
      "FNM_NODE_DIST_MIRROR": "https://nodejs.org/dist",
      "FNM_LOGLEVEL": "info",
      "VIRTUAL_ENV_DISABLE_PROMPT": "12"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [
          "libgamemodeauto.so"
        ],
        [
          "libgamemodeauto.so"
        ]
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.070",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "1",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.369",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "2",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.025",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "2",
        "cpu cores": "4",
        "apicid": "4",
        "initial apicid": "4",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "3",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.109",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "3",
        "cpu cores": "4",
        "apicid": "6",
        "initial apicid": "6",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "4",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.061",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "1",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "5",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.050",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "3",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "6",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.235",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "2",
        "cpu cores": "4",
        "apicid": "5",
        "initial apicid": "5",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "7",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
        "stepping": "10",
        "microcode": "0xca",
        "cpu MHz": "800.384",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "3",
        "cpu cores": "4",
        "apicid": "7",
        "initial apicid": "7",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit",
        "bogomips": "4199.88",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      }
    ],
    "drives": [
      {
        "name": "nvme0n1",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "nvme0n1p1",
            "fstype": "vfat",
            "label": null,
            "uuid": "A4F7-1813",
            "fsavail": "208M",
            "fsuse%": "58%",
            "mountpoint": "/boot/efi"
          },
          {
            "name": "nvme0n1p2",
            "fstype": "vfat",
            "label": null,
            "uuid": "A4F7-14E1",
            "fsavail": "1.9G",
            "fsuse%": "52%",
            "mountpoint": "/recovery"
          },
          {
            "name": "nvme0n1p3",
            "fstype": "ext4",
            "label": null,
            "uuid": "627597dc-14ca-4560-b901-072ff4d44d94",
            "fsavail": "383.8G",
            "fsuse%": "11%",
            "mountpoint": "/"
          },
          {
            "name": "nvme0n1p4",
            "fstype": "swap",
            "label": null,
            "uuid": "f667a050-1a81-454b-bb75-1090cc18d3fc",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null,
            "children": [
              {
                "name": "cryptswap",
                "fstype": "swap",
                "label": null,
                "uuid": "6351f2ae-83d7-45ad-8035-5b0b4127f3ab",
                "fsavail": null,
                "fsuse%": null,
                "mountpoint": "[SWAP]"
              }
            ]
          }
        ]
      }
    ],
    "ram": {
      "MemTotal": "16137968",
      "MemFree": "7286708",
      "MemAvailable": "11390276",
      "Buffers": "461264",
      "Cached": "4117616",
      "SwapCached": "0",
      "Active": "4966984",
      "Inactive": "2891492",
      "Active(anon)": "3549788",
      "Inactive(anon)": "270084",
      "Active(file)": "1417196",
      "Inactive(file)": "2621408",
      "Unevictable": "267748",
      "Mlocked": "48",
      "SwapTotal": "4193784",
      "SwapFree": "4193784",
      "Dirty": "0",
      "Writeback": "0",
      "AnonPages": "3547528",
      "Mapped": "842444",
      "Shmem": "540548",
      "KReclaimable": "409296",
      "Slab": "574060",
      "SReclaimable": "409296",
      "SUnreclaim": "164764",
      "KernelStack": "21216",
      "PageTables": "48444",
      "NFS_Unstable": "0",
      "Bounce": "0",
      "WritebackTmp": "0",
      "CommitLimit": "12262768",
      "Committed_AS": "12741856",
      "VmallocTotal": "34359738367",
      "VmallocUsed": "39572",
      "VmallocChunk": "0",
      "Percpu": "5504",
      "HardwareCorrupted": "0",
      "AnonHugePages": "0",
      "ShmemHugePages": "0",
      "ShmemPmdMapped": "0",
      "FileHugePages": "0",
      "FilePmdMapped": "0",
      "CmaTotal": "0",
      "CmaFree": "0",
      "HugePages_Total": "0",
      "HugePages_Free": "0",
      "HugePages_Rsvd": "0",
      "HugePages_Surp": "0",
      "Hugepagesize": "2048",
      "Hugetlb": "0",
      "DirectMap4k": "370452",
      "DirectMap2M": "10903552",
      "DirectMap1G": "5242880"
    },
    "dist": [
      "Pop!_OS",
      "20.04",
      "focal"
    ],
    "arch": "x86_64",
    "kernel": "5.4.0-7634-generic",
    "glxinfo": {
      "opengl_es_profile_version": "OpenGL ES 3.2 Mesa 20.0.4",
      "opengl_core_profile_context_flags": "(none)",
      "opengl_context_flags": "(none)",
      "display": ":1",
      "opengl_core_profile_profile_mask": "core profile",
      "direct_rendering": "Yes",
      "name_of_display": ":1",
      "opengl_core_profile_version": "4.6 (Core Profile) Mesa 20.0.4",
      "opengl_vendor": "Intel",
      "opengl_version": "4.6 (Compatibility Profile) Mesa 20.0.4",
      "opengl_core_profile_shading_language_version": "4.60",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "opengl_shading_language_version": "4.60",
      "opengl_profile_mask": "compatibility profile",
      "opengl_renderer": "Mesa Intel(R) UHD Graphics 620 (KBL GT2)",
      "screen": "0"
    }
  }
}
```

**Comment by xordspar0** [comment]
You're using Steam in a Flatpak; is this the same issue as https://github.com/lutris/lutris/issues/2086?

**Comment by mlms13** [comment]
Yes indeed! Not sure how I missed that one in my searching.
