### ISSUE TITLE
Allow downloading extras from GOG installers

### ISSUE THREAD

**Issue by Kern3l-Panic** [lutris/lutris#2945]
**Describe the bug**

When the Gog Summer Sale started, I decided to pick up Blood: One Unit Whole. because that's the only place I know that sells it (Even thought It's just an Extra of Blood: Fresh Supply)

But when I try to use the Lutris installer for the game, it doesn't register with the 'Extra' that Blood: One Unit Whole is within another game. I only figured this out after 1 hour of waiting for the game to not install and instead just had a message as if it was installing the game.

So on Lutris' Discord server, I asked for some help. And the help was to NOT login to my Gog account when I clicked install on Blood, and instead opt into choosing a local Gog installer, which was that 'Extra' Gog installer from Fresh Supply for Linux. And it worked.

**Expected behavior**

I'd either expect that Lutris would recognize an extra from Gog or that there be an optional choice to choose local Gog installer instead of waiting for nothing.

**Current behavior**

The installer says that Blood is being installed, but nothing happens.

**Steps to reproduce**

1. Go here: https://lutris.net/games/blood-one-unit-whole-blood/

2. Click Install (ONLY IF YOU DON'T HAVE BLOOD IN YOUR GOG ACCOUNT)

3. And wait... because nothing happens

**Lutris debugging output**

INFO     2020-06-14 18:56:54,005 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-06-14 18:56:54,005 [startup.check_driver:55]:Using NVIDIA drivers 440.82 for x86_64
INFO     2020-06-14 18:56:54,005 [startup.check_driver:60]:GPU: GeForce GTX 1070
INFO     2020-06-14 18:56:54,006 [startup.check_driver:79]:GPU: 10DE:1B81 19DA:2445 using nvidia drivers
INFO     2020-06-14 18:56:54,025 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-06-14 18:56:54,026 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-06-14 18:56:54,189 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-06-14 18:56:54,189 [lutriswindow.toggle_connection:642]:Connected to lutris.net as Creature6
DEBUG    2020-06-14 18:56:54,190 [store.get_missing_media:213]:Requesting missing icons from API for yo-frankie, rise-of-the-triad-dark-war
DEBUG    2020-06-14 18:56:54,191 [http.get:65]:GET https://lutris.net/api/games/library/Creature6
DEBUG    2020-06-14 18:56:54,191 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-06-14 18:56:54,538 [api.get_game_api_page:132]:Loaded 2 games from page 1
2020-06-14 18:57:06,185: Running Lutris 0.5.6
2020-06-14 18:57:06,185: Using NVIDIA drivers 440.82 for x86_64
2020-06-14 18:57:06,185: GPU: GeForce GTX 1070
2020-06-14 18:57:06,186: GPU: 10DE:1B81 19DA:2445 using nvidia drivers
2020-06-14 18:57:06,206: Vulkan is supported
2020-06-14 18:57:06,210: Fetching installer https://lutris.net/api/installers/blood-one-unit-whole-blood-gog
2020-06-14 18:57:06,210: GET https://lutris.net/api/installers/blood-one-unit-whole-blood-gog
2020-06-14 18:57:07,783: Retrieving video modes from XrandR
2020-06-14 18:57:09,132: Required runners: [<lutris.runners.linux.linux object at 0x7f8598051da0>]
2020-06-14 18:57:09,134: GET https://embed.gog.com/userData.json
2020-06-14 18:57:09,497: GET https://embed.gog.com/userData.json
2020-06-14 18:57:09,822: Getting game details for 1207658856
2020-06-14 18:57:09,823: GET https://api.gog.com/products/1207658856?expand=downloads
2020-06-14 18:57:10,202: Getting download info for http://api.gog.com/products/1207658856/downlink/installer/en3installer1
2020-06-14 18:57:10,203: GET http://api.gog.com/products/1207658856/downlink/installer/en3installer1
2020-06-14 18:57:11,097: Failed to request http://api.gog.com/products/1207658856/downlink/installer/en3installer1, check your GOG credentials and internet connectivity
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 247, in on_install_clicked
    self.interpreter.check_runner_install()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 513, in check_runner_install
    self.install_runners()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 520, in install_runners
    self.prepare_game_files()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 383, in prepare_game_files
    self.swap_gog_game_files()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 327, in swap_gog_game_files
    links = get_gog_download_links(self.gogid, self.runner)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 317, in get_gog_download_links
    download_info = gog_service.get_download_info(downlink)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 203, in get_download_info
    field_url = response[field]
TypeError: 'NoneType' object is not subscriptable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 247, in on_install_clicked
    self.interpreter.check_runner_install()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 513, in check_runner_install
    self.install_runners()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 520, in install_runners
    self.prepare_game_files()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 383, in prepare_game_files
    self.swap_gog_game_files()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 327, in swap_gog_game_files
    links = get_gog_download_links(self.gogid, self.runner)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 317, in get_gog_download_links
    download_info = gog_service.get_download_info(downlink)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 203, in get_download_info
    field_url = response[field]
TypeError: 'NoneType' object is not subscriptable

**System information**

This isn't based on my system information, It's more of a feature I'd like to see implemented into Lutris.

**Screenshots**

None.

**Comment by byte1024** [comment]
It looks like it should be possible to query for the extras https://gogapidocs.readthedocs.io/en/latest/galaxy.html#api-gog-com

I would assume Lutris devs just didn't get around to it as of yet.

**Comment by strycore** [comment]
We don't use the extras yet but the upcoming file-picker branch will let you override the GOG file so it will always be possible to provide a custom file.
There's a stacktrace here that can be fixed but it won't solve the issue itself.
