### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2969]
WWhen you use the right-click and right-hand column's Wine Configuration this gets printed on the terminal:

```
DEBUG    2020-06-28 12:14:19,544 [wine.winecfg:374]:winecfg: /usr/bin/winecfg
INFO     2020-06-28 12:14:19,545 [wine.use_lutris_runtime:121]:Using system wine version, not using runtime
WARNING  2020-06-28 12:14:19,577 [wine.game_exe:597]:The game doesn't have an executable
Traceback (most recent call last):
  File "~/src/lutris/lutris/runners/wine.py", line 751, in run_winecfg
    env=self.get_env(os_env=True),
  File "~/src/lutris/lutris/runners/commands/wine.py", line 384, in winecfg
    include_processes=["winecfg.exe"],
  File "~/src/lutris/lutris/runners/commands/wine.py", line 317, in wineexec
    exclude_processes=exclude_processes,
  File "~/src/lutris/lutris/command.py", line 80, in __init__
    self.cwd = self.get_cwd(cwd)
  File "~/src/lutris/lutris/command.py", line 112, in get_cwd
    cwd = self.runner.working_dir if self.runner else None
  File "~/src/lutris/lutris/runners/wine.py", line 615, in working_dir
    return super(wine, self).working_dir
  File "~/src/lutris/lutris/runners/runner.py", line 113, in working_dir
    return self.game_path or os.path.expanduser("~/")
  File "~/src/lutris/lutris/runners/runner.py", line 106, in game_path
    self.game_config.get(self.entry_point_option)
  File "/usr/lib/python3.6/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
 
Using Wine-staging 5.11, also happens with lutris-5.7-x86_64

**Comment by strycore** [comment]
Fixed in 4d28ed6093df2c22cc514d7e3538e93ce469f61e
