### ISSUE TITLE
Lutris broken: AttributeError: 'Game' object has no attribute 'system_config'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3012]
**Describe the bug**

Looks like commit https://github.com/lutris/lutris/commit/830061407678f937dc7263f38079196d6d979e66 broke Lutris. with it applied I get the following on the terminal:

```
Traceback (most recent call last):
  File "~/src/lutris/lutris/exceptions.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "~/src/lutris/lutris/game.py", line 499, in configure_game
    "terminal": self.get_terminal(),
  File "~/src/lutris/lutris/game.py", line 451, in get_terminal
    if self.system_config.get("terminal"):
AttributeError: 'Game' object has no attribute 'system_config'
```

Happens with all the runners I tested IE MAME, Libretro, Citra

@strycore

**Comment by telanus** [comment]
After the latest [commit](https://github.com/lutris/lutris/commit/863c781f0f56bf436f0e02682fd6af28ce600538) I get this:

```
Traceback (most recent call last):
  File "~/src/lutris/lutris/exceptions.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "~/src/lutris/lutris/game.py", line 511, in configure_game
    if self.system_config.get("use_us_layout"):
AttributeError: 'Game' object has no attribute 'system_config'
```

**Comment by telanus** [comment]
Had a look and

**Comment by telanus** [comment]
https://github.com/lutris/lutris/commit/a8ae60e9f0e5817417b84f6796f716fc5f54af97 fixes this
