### ISSUE TITLE
Can't configure runners on GNOME

### ISSUE THREAD

**Issue by Technical27** [lutris/lutris#3014]
**Describe the bug**
Some dialog boxes (like the ones to configure runners) don't open, but others (such as the one to manage installed runners) do work. This only happens on GNOME. (tested on my laptop with sway)

**Expected behavior**

A dialog box should appear when I click the settings icon for the runner

**Current behavior**

Nothing happens

**Steps to reproduce**

- Open lutris
- Try and change wine settings

**Lutris debugging output**
note: lutris *thinks* libs are missing, but they aren't and things like DXVK work perfectly fine.
```
/usr/bin/ldconfig: Can't open cache file /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/etc/ld.so.cache
: No such file or directory
2020-07-12 09:18:52,837: Failed to get libraries from ldconfig: Command '['/usr/bin/ldconfig', '-p']' returned non-zero exit status 1.
INFO     2020-07-12 09:18:53,105 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-07-12 09:18:53,105 [startup.check_driver:54]:Using NVIDIA drivers 440.100 for x86_64
INFO     2020-07-12 09:18:53,105 [startup.check_driver:60]:GPU: GeForce RTX 2070 SUPER
INFO     2020-07-12 09:18:53,105 [startup.check_driver:77]:GPU: 10DE:1E84 3842:3173 using nvidia drivers
ERROR    2020-07-12 09:18:53,106 [startup.check_libs:112]:i386 libGL.so.1 missing (needed by opengl)
ERROR    2020-07-12 09:18:53,106 [startup.check_libs:112]:x86_64 libGL.so.1 missing (needed by opengl)
ERROR    2020-07-12 09:18:53,106 [startup.check_libs:112]:i386 libvulkan.so.1 missing (needed by vulkan)
ERROR    2020-07-12 09:18:53,106 [startup.check_libs:112]:x86_64 libvulkan.so.1 missing (needed by vulkan)
INFO     2020-07-12 09:18:53,142 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-07-12 09:18:53,143 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-07-12 09:18:53,268 [http.get:65]:GET https://lutris.net/api/runtime
Traceback (most recent call last):
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/gui/widgets/sidebar.py", line 85, in on_configure_runner
    RunnerConfigDialog(self.runner, parent=self.get_toplevel())
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/gui/config/runner.py", line 21, in __init__
    self.build_tabs("runner")
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/gui/config/common.py", line 75, in build_tabs
    self._build_runner_tab(config_level)
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/gui/config/common.py", line 364, in _build_runner_tab
    self.runner_box = RunnerBox(self.lutris_config, self.game)
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/gui/config/boxes.py", line 641, in __init__
    self.generate_widgets("runner")
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/gui/config/boxes.py", line 76, in generate_widgets
    option["choices"] = option["choices"]()
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 629, in get_resolutions
    return sorted(
  File "/nix/store/v00kxa4pcw90ly9c5zx95wc6x15x2adh-lutris-original-0.5.6/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 630, in <lambda>
    set(resolutions), key=lambda x: int(x.split("x")[0]), reverse=True
ValueError: invalid literal for int() with base 10: 'dbus.UInt32(2560)'
```
**System information**
[lutris-issue-report.json](https://gist.github.com/Technical27/303fcd5fd7981f997174f1c3ed4aec70)

**Comment by strycore** [comment]
This seems like a simple fix but I don't want to fix the symptoms and want to understand what going on.
Sway + Nix is probably one of the least supported way of using lutris so I'll just wait for a patch.

**Comment by strycore** [comment]
I remember merging a fix for this issue in the last release.
