### ISSUE TITLE
Corrupted Retroarch config file crashes the client

### ISSUE THREAD

**Issue by warriormaster12** [lutris/lutris#3027]
Basically after I updated lutris to 0.5.7, it stopped working. Claiming that I have unsupported locale even though it wasn't an issue before 

```
lutris -d
Unsupported locale setting. Fix your locales

(lutris:18961): Gtk-WARNING **: 22:21:54.996: Locale not supported by C library.
        Using the fallback 'C' locale.
2020-07-16 22:21:55,351: MAME XML generation launched in the background, not returning anything this time
2020-07-16 22:21:55,352: Getting full game list from MAME...
2020-07-16 22:21:55,353: MAME isn't installed, can't retrieve systems list.
Traceback (most recent call last):
  File "/usr/games/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 52, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import SidebarListBox
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 10, in <module>
    from lutris import pga, platforms, runners
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 83, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 78, in get_runner_module
    return __import__("lutris.runners.%s" % runner_name, globals(), locals(), [runner_name], 0)
  File "/usr/lib/python3/dist-packages/lutris/runners/libretro.py", line 46, in <module>
    core_config = RetroConfig(entry)
  File "/usr/lib/python3/dist-packages/lutris/util/libretro.py", line 16, in __init__
    for line in config_file.readlines():
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 30: ordinal not in range(128)
```

System: 
KDE Neon (Ubuntu 18.04)
I5-4570
Gtx 1060
16gb ddr3

**Comment by strycore** [comment]
it's not about the locales, there seems to be a weird character in your retroarch config file and it's crashing lutris.
rename it to see if you can run lutris, it's either in ~/.local/share/lutris/runners/libretro or ~/.config/retroarch

**Comment by warriormaster12** [comment]
@strycore yup, removing retroarch folder from runners solved the issue. Thank you :D
