### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3036]
**Describe the bug**
Ran git pull this morning and started Lutris, but Lutris is refusing to start, it crashes with this on the terminal:
```
Traceback (most recent call last):
  File "./bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "~/src/lutris/lutris/gui/application.py", line 50, in <module>
    from .lutriswindow import LutrisWindow
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 38, in <module>
    @Gtk.Template(filename=os.path.join(datapath.get(), "ui", "lutris-window.ui"))
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'
```

**Comment by strycore** [comment]
on which distro? I removed the GtkTemplate shim so I have to know which versions of Gtk we're breaking with this change.

**Comment by telanus** [comment]
I'm on Kubuntu 18.04. 

Libgtk-3 version: 3.22.30-1ubuntu4

**Comment by strycore** [comment]
Ok, I have a Kubuntu 18.04 laptop I can test this on

**Comment by telanus** [comment]
seems to be fixed with the latest git commits. Closing

Thanx @strycore
