### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'present'

### ISSUE THREAD

**Issue by majidmc2** [lutris/lutris#3112]
I installed lutris with this command:
`$ sudo apt install lutris`
on Ubuntu and after run lutris I received this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 172, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 100, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 287, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 117, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 335, in do_command_line
    self.window.present()
AttributeError: 'NoneType' object has no attribute 'present'
```

**Comment by k0d3r1s** [comment]
getting same error on Debian Testing, lutris version: 0.5.1.3

**Comment by IPv777** [comment]
same error on Parrot OS (Debian)

**Comment by Anequit** [comment]
Yep, just got this. Not sure what to do or how to fix it. Doesn't really seem to be a fix anywhere.

**Comment by AlexanderRavenheart** [comment]
Solution: https://forums.lutris.net/t/lutris-stuck-updating-d9vk/8563/5?u=alexravenheart
Explanation: https://forums.lutris.net/t/solved-lutris-wont-open-no-errors-in-terminal/8599/4?u=alexravenheart

**Comment by strycore** [comment]
Your lutris installation is out of date. Please upgrade.
