### ISSUE TITLE
AttributeError: 'InstallerWindow' object has no attribute 'start_download'

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3135]
Hello,
when I tried to install this installer script:
https://lutris.net/games/diablo-diablo-th2-mod/installer/edit
**with last Lutris git version** from today, I obtained this error:

```
Traceback (most recent call last):
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/gui/installerwindow.py", line 262, in on_install_clicked
    self.interpreter.launch_install()
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/installer/interpreter.py", line 176, in launch_install
    self.install_runners()
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/installer/interpreter.py", line 256, in install_runners
    self.install_runner(self.runners_to_install.pop(0))
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/installer/interpreter.py", line 266, in install_runner
    downloader=self.parent.start_download,
AttributeError: 'InstallerWindow' object has no attribute 'start_download'
```

and I can only cancel installing.
I can not reproduce this bug with last stable version, only with last git version.

**Comment by legluondunet** [comment]
just tested it works ok, thank you @strycore
