### ISSUE TITLE
Lutris won't install on Arch.

### ISSUE THREAD

**Issue by pakro** [lutris/lutris#3169]
I'm seeing this issue after test runs.

```
FAILED (errors=2)
==> ERROR: A failure occurred in check().
    Aborting...
error making: lutris-git
```

When I look for the issue I find the following:

```
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'magic')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/paul/.cache/yay/lutris-git/src/lutris/tests/test_installer.py", line 2, in <module>
    from lutris.installer.interpreter import ScriptInterpreter
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/installer/installer.py", line 18, in <module>
    from lutris.util.game_finder import find_linux_game_executable, find_windows_game_executable
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/util/game_finder.py", line 4, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

```

and

```
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'magic')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/paul/.cache/yay/lutris-git/src/lutris/tests/test_dialogs.py", line 14, in <module>
    from lutris.gui.application import Application
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/gui/application.py", line 41, in <module>
    from lutris.gui.installerwindow import InstallerWindow
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/gui/installerwindow.py", line 15, in <module>
    from lutris.installer import interpreter
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/installer/installer.py", line 18, in <module>
    from lutris.util.game_finder import find_linux_game_executable, find_windows_game_executable
  File "/home/paul/.cache/yay/lutris-git/src/lutris/lutris/util/game_finder.py", line 4, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

```

**Comment by pakro** [comment]
probably not a issue in Lutris itself but in the AUR PKGBUILD. I think it is missing the python-magic library. Will raise this issue there too. Please close if I'm correct and sorry!

**Comment by CartoonFan** [comment]
Installing python-magic seems to have fixed it for me.

**Comment by pakro** [comment]
Closing this as this is an AUR issue.
