### ISSUE TITLE
Lutris crashes on startup due to missing database directory in site-packages/lutris

### ISSUE THREAD

**Issue by CartoonFan** [lutris/lutris#3172]
**Describe the bug**

Lutris looks for the database directory in site-packages/lutris and crashes on startup when it is not found. Copying the database directory to the right location seems to fix the problem. I've made a pull request here: https://github.com/lutris/lutris/pull/3171

**Steps to reproduce**

- Start Lutris

**Lutris debugging output (Optional)**
```bash
$ lutris -d
Unable to load locale dir, translations won't work.
Traceback (most recent call last):
  File "/usr/bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.database import games as games_db
ModuleNotFoundError: No module named 'lutris.database'
```
**System information (Optional)**

If you believe your issue is related to your system (on a hardware or OS level), it can be useful to for us to have more detailed information about your system. You can attach this information `lutris --submit-issue` in a terminal and attaching the resulting JSON file to this issue (please do not paste the file content directly on the issue)

**Screenshots (Optional)**

If your issue is hard to explain with words, feel free to attach screenshots.

**Comment by CartoonFan** [comment]
Closed by https://github.com/lutris/lutris/commit/31fc87967c403c9b3ca3ef429018e2e97431ab77.
