### ISSUE TITLE
a Couple of new "errors"

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3183]
Updated to the latest GIT tonight after work, and selected, under sources => local, got a list of local games, then selected Installed. And Lutris stalled, and found this on the terminal:

```
ERROR    2020-10-04 23:59:01,882 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 4 retries remaining
ERROR    2020-10-04 23:59:01,882 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-04 23:59:15,948 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? AND appid = ? ORDER BY slug ASC' failed. 4 retries remaining
ERROR    2020-10-04 23:59:15,948 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-04 23:59:16,949 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? AND appid = ? ORDER BY slug ASC' failed. 3 retries remaining
ERROR    2020-10-04 23:59:16,950 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-04 23:59:17,950 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? AND appid = ? ORDER BY slug ASC' failed. 2 retries remaining
ERROR    2020-10-04 23:59:17,951 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-04 23:59:18,952 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? AND appid = ? ORDER BY slug ASC' failed. 1 retries remaining
ERROR    2020-10-04 23:59:18,952 [sql.cursor_execute:41]:database is locked
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 679, in on_game_selection_changed
    game = ServiceGameCollection.get_game(self.service.id, game_id)
  File "~/src/lutris/lutris/database/services.py", line 23, in get_game
    results = sql.filtered_query(PGA_DB, "service_games", filters={"service": service, "appid": appid})
  File "~/src/lutris/lutris/database/sql.py", line 171, in filtered_query
    return db_query(db_path, query, tuple(params))
  File "~/src/lutris/lutris/database/sql.py", line 119, in db_query
    cursor_execute(cursor, query, params)
  File "~/src/lutris/lutris/database/sql.py", line 35, in cursor_execute
    return cursor.execute(query, params)
sqlite3.OperationalError: database is locked
```
Had to ^C (on the Terminal) to stop Lutris.

After I restarted, I got the following on the Terminal:

```
DEBUG    2020-10-05 00:02:14,954 [lutriswindow.switch_view:496]:View destroyed
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 185, in on_load
    self.switch_view()
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 513, in switch_view
    self.update_store()
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 388, in update_store
    games = self.get_games_from_filters()
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 319, in get_games_from_filters
    return dynamic_categories[self.filters["dynamic_category"]]()
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 257, in get_running_games
    return games_db.get_games_by_ids([game.id for game in self.application.running_games])
TypeError: 'ListStore' object is not iterable
```

**Comment by telanus** [comment]
A new one popped onto the Terminal:

```
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/widgets/game_bar.py", line 214, in on_play_clicked
    self.launch_service_game(service_runner["runner"], service_runner["slug"])
  File "~/src/lutris/lutris/gui/widgets/game_bar.py", line 229, in launch_service_game
    self.service.create_config(self.db_game, config_id)
  File "~/src/lutris/lutris/services/xdg.py", line 99, in create_config
    details = json.loads(db_game["details"])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Comment by telanus** [comment]
![2020-10-05 1219](https://user-images.githubusercontent.com/19357986/95028643-f67fbd00-06a1-11eb-874e-437fc2c1345c.png)
Selecting the Humble Bundle Source, Lutris list most games between two and three times.

![2020-10-05 1230](https://user-images.githubusercontent.com/19357986/95028664-229b3e00-06a2-11eb-89a5-53bc4342cee7.png)
Selecting the installed library it doesn't sort the entries according to the alphanumerical system. When you select All, under Runners, and Lutris will sort entries correctly
