### ISSUE TITLE
ImportError: cannot import name 'pga'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3189]
Got this, after updating this morning

```
Traceback (most recent call last):
  File "./bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "~/src/lutris/lutris/gui/application.py", line 37, in <module>
    from lutris.game import Game
  File "~/src/lutris/lutris/game.py", line 13, in <module>
    from lutris import pga, runtime, settings
ImportError: cannot import name 'pga'
```
 installed pga with pip3 install pga but still give that error

**Comment by telanus** [comment]
looks like this commit breaks lutris: https://github.com/lutris/lutris/commit/b11a16e1eaaa0dd724f002141270c4ce5f3cdf98
