### ISSUE TITLE
reload library makes Lutris unresponsive or unstable

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3209]
Hello,
beta testing, when I click on "reload" in Lutris category, Lutris becomes unresponsive and unstable, could crash.

![Capture d’écran de 2020-10-18 07-15-12](https://user-images.githubusercontent.com/325405/96359381-9f063600-1112-11eb-9fc8-31b74ac19fe0.png)

```
$ lutris -d
INFO     2020-10-18 06:58:31,687 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-18 06:58:31,687 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-18 06:58:31,687 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-18 06:58:31,687 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
WARNING  2020-10-18 06:58:31,760 [game.set_platform_from_runner:251]:Can't get platform for runner Libretro
DEBUG    2020-10-18 06:58:34,668 [store_item.platform:79]:Game Bomberman 64 has no platform
DEBUG    2020-10-18 06:58:34,894 [http.get:71]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-18 06:58:35,007 [http.get:71]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-18 06:58:57,258 [game.save:261]:Saving Hexen - Beyond Heretic - Brutal Hexen RPG mod - GZDoom (zdoom) with config ID hexen-beyond-heretic-all-pc-brutal-hexen--1602540488
DEBUG    2020-10-18 06:58:57,258 [config.save:211]:Saving LutrisConfig(level=game, game_config_id=hexen-beyond-heretic-all-pc-brutal-hexen--1602540488, runner=zdoom) config to /home/legluondunet/.config/lutris/games/hexen-beyond-heretic-all-pc-brutal-hexen--1602540488.yml
DEBUG    2020-10-18 06:59:02,714 [store_item.platform:79]:Game Bomberman 64 has no platform
DEBUG    2020-10-18 06:59:10,021 [base.wipe_game_cache:137]:Wiping lutris cache
DEBUG    2020-10-18 06:59:10,021 [base.wipe_game_cache:44]:Deleting games from service-games for lutris
DEBUG    2020-10-18 06:59:10,222 [http.get:71]:GET https://lutris.net/api/games/library/legluondunet
DEBUG    2020-10-18 07:03:01,763 [lutris.load:127]:Matching with already installed games
DEBUG    2020-10-18 07:07:52,450 [lutris.load:130]:Lutris games loaded

(lutris:929199): Gtk-CRITICAL **: 07:07:52.454: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:44: Warning: g_value_type_compatible: assertion 'src_type' failed
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:44: Warning: unable to set property 'pixbuf' of type 'GdkPixbuf' from value of type '(null)'
  return Gio.Application.run(self, *args, **kwargs)

(lutris:929199): Gtk-CRITICAL **: 07:07:52.952: gtk_list_store_get_path: assertion 'iter->stamp == priv->stamp' failed

(lutris:929199): Gtk-CRITICAL **: 07:07:52.952: gtk_tree_path_to_string: assertion 'path != NULL' failed
Erreur de segmentation (core dumped)
```

**Comment by legluondunet** [comment]
second try:

```
$ lutris -d
INFO     2020-10-18 07:08:56,385 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-18 07:08:56,386 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-18 07:08:56,386 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-18 07:08:56,386 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
WARNING  2020-10-18 07:08:56,456 [game.set_platform_from_runner:251]:Can't get platform for runner Libretro
DEBUG    2020-10-18 07:08:59,954 [store_item.platform:79]:Game Bomberman 64 has no platform
DEBUG    2020-10-18 07:09:00,174 [http.get:71]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-18 07:09:00,315 [http.get:71]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-18 07:09:04,954 [base.wipe_game_cache:137]:Wiping lutris cache
DEBUG    2020-10-18 07:09:04,955 [base.wipe_game_cache:44]:Deleting games from service-games for lutris
WARNING  2020-10-18 07:09:05,258 [lutriswindow.on_service_games_updating:401]:Wrong service None
DEBUG    2020-10-18 07:09:05,259 [http.get:71]:GET https://lutris.net/api/games/library/legluondunet
ERROR    2020-10-18 07:09:23,660 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 4 retries remaining
ERROR    2020-10-18 07:09:23,661 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:09:24,662 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 3 retries remaining
ERROR    2020-10-18 07:09:24,663 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:09:25,664 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 2 retries remaining
ERROR    2020-10-18 07:09:25,664 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:09:26,666 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 1 retries remaining
ERROR    2020-10-18 07:09:26,666 [sql.cursor_execute:41]:database is locked
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 449, in update_store
    games = self.get_games_from_filters()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 380, in get_games_from_filters
    return self.switch_to_service(service_name)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 343, in switch_to_service
    service_games = ServiceGameCollection.get_for_service(service_name)
  File "/usr/lib/python3/dist-packages/lutris/database/services.py", line 14, in get_for_service
    return sql.filtered_query(PGA_DB, "service_games", filters={"service": service})
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 168, in filtered_query
    return db_query(db_path, query, tuple(params))
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 116, in db_query
    cursor_execute(cursor, query, params)
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 35, in cursor_execute
    return cursor.execute(query, params)
sqlite3.OperationalError: database is locked
ERROR    2020-10-18 07:09:33,411 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 4 retries remaining
ERROR    2020-10-18 07:09:33,411 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:09:34,413 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 3 retries remaining
ERROR    2020-10-18 07:09:34,413 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:09:35,414 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 2 retries remaining
ERROR    2020-10-18 07:09:35,415 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:09:36,416 [sql.cursor_execute:40]:SQL query 'select * from service_games WHERE service = ? ORDER BY slug ASC' failed. 1 retries remaining
ERROR    2020-10-18 07:09:36,416 [sql.cursor_execute:41]:database is locked
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 449, in update_store
    games = self.get_games_from_filters()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 380, in get_games_from_filters
    return self.switch_to_service(service_name)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 343, in switch_to_service
    service_games = ServiceGameCollection.get_for_service(service_name)
  File "/usr/lib/python3/dist-packages/lutris/database/services.py", line 14, in get_for_service
    return sql.filtered_query(PGA_DB, "service_games", filters={"service": service})
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 168, in filtered_query
    return db_query(db_path, query, tuple(params))
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 116, in db_query
    cursor_execute(cursor, query, params)
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 35, in cursor_execute
    return cursor.execute(query, params)
sqlite3.OperationalError: database is locked
DEBUG    2020-10-18 07:10:38,039 [lutris.load:127]:Matching with already installed games
DEBUG    2020-10-18 07:11:07,222 [base.wipe_game_cache:137]:Wiping lutris cache
DEBUG    2020-10-18 07:11:07,222 [base.wipe_game_cache:44]:Deleting games from service-games for lutris
ERROR    2020-10-18 07:11:12,227 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 4 retries remaining
ERROR    2020-10-18 07:11:12,227 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:13,228 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 3 retries remaining
ERROR    2020-10-18 07:11:13,229 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:14,229 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 2 retries remaining
ERROR    2020-10-18 07:11:14,229 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:15,231 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 1 retries remaining
ERROR    2020-10-18 07:11:15,231 [sql.cursor_execute:41]:database is locked
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 137, in on_connect_clicked
    self.service.logout()
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 146, in logout
    self.wipe_game_cache()
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 142, in wipe_game_cache
    super().wipe_game_cache()
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 45, in wipe_game_cache
    sql.db_delete(PGA_DB, "service_games", "service", self.id)
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 77, in db_delete
    cursor_execute(cursor, "delete from {0} where {1}=?".format(table, field), (value, ))
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 35, in cursor_execute
    return cursor.execute(query, params)
sqlite3.OperationalError: database is locked
DEBUG    2020-10-18 07:11:17,106 [base.wipe_game_cache:137]:Wiping lutris cache
DEBUG    2020-10-18 07:11:17,106 [base.wipe_game_cache:44]:Deleting games from service-games for lutris
ERROR    2020-10-18 07:11:22,111 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 4 retries remaining
ERROR    2020-10-18 07:11:22,111 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:23,113 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 3 retries remaining
ERROR    2020-10-18 07:11:23,113 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:24,114 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 2 retries remaining
ERROR    2020-10-18 07:11:24,115 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:25,116 [sql.cursor_execute:40]:SQL query 'delete from service_games where service=?' failed. 1 retries remaining
ERROR    2020-10-18 07:11:25,116 [sql.cursor_execute:41]:database is locked
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 116, in on_refresh_clicked
    self.service.wipe_game_cache()
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 142, in wipe_game_cache
    super().wipe_game_cache()
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 45, in wipe_game_cache
    sql.db_delete(PGA_DB, "service_games", "service", self.id)
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 77, in db_delete
    cursor_execute(cursor, "delete from {0} where {1}=?".format(table, field), (value, ))
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 35, in cursor_execute
    return cursor.execute(query, params)
sqlite3.OperationalError: database is locked
ERROR    2020-10-18 07:11:35,994 [sql.cursor_execute:40]:SQL query 'SELECT * FROM games where configpath=?' failed. 4 retries remaining
ERROR    2020-10-18 07:11:35,994 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:36,996 [sql.cursor_execute:40]:SQL query 'SELECT * FROM games where configpath=?' failed. 3 retries remaining
ERROR    2020-10-18 07:11:36,996 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:37,997 [sql.cursor_execute:40]:SQL query 'SELECT * FROM games where configpath=?' failed. 2 retries remaining
ERROR    2020-10-18 07:11:37,997 [sql.cursor_execute:41]:database is locked
ERROR    2020-10-18 07:11:38,999 [sql.cursor_execute:40]:SQL query 'SELECT * FROM games where configpath=?' failed. 1 retries remaining
ERROR    2020-10-18 07:11:38,999 [sql.cursor_execute:41]:database is locked
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 456, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 148, in add_game
    gtk_safe(game.platform),
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store_item.py", line 75, in platform
    game_inst = Game(self._game_data["id"])
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 87, in __init__
    self.load_config()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 205, in load_config
    self.runner = self._get_runner()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 196, in _get_runner
    return runner_class(self.config)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 43, in __init__
    self.game_data = get_game_by_field(self.config.game_config_id, "configpath")
  File "/usr/lib/python3/dist-packages/lutris/database/games.py", line 111, in get_game_by_field
    game_result = sql.db_select(PGA_DB, "games", condition=(field, value))
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 102, in db_select
    cursor_execute(cursor, query, params)
  File "/usr/lib/python3/dist-packages/lutris/database/sql.py", line 35, in cursor_execute
    return cursor.execute(query, params)
sqlite3.OperationalError: database is locked


```

**Comment by legluondunet** [comment]
another way to test this:
launch "reload library" and change sources category in the left panel in the same time...I obtained a complete freeze during several minutes, could crash Lutris. 
Could it be possible to:
- sql operations and synchronisation do not freeze Lutris
- user do not know what's lutris doing during feeze (sql operations and synchronisation), it will be nice to see a progress bar and for example "synchronisation in progress: 3 games on 150"

**Comment by strycore** [comment]
seems ok now. it's a bit of a heavy load first time the icons are loaded but I scaled down the number of simultaneous downloads to 3 to reduce the load
