### ISSUE TITLE
some Humble Bundle games do not install

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3210]
When when I try to install a Humble Bundle game "super meat boy", the game installed but I can not launch it.
When I look at the game folder, it is empty.

```
 lutris -d
INFO     2020-10-18 07:44:14,385 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-18 07:44:14,385 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-18 07:44:14,385 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-18 07:44:14,385 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
WARNING  2020-10-18 07:44:14,451 [game.set_platform_from_runner:251]:Can't get platform for runner Libretro
DEBUG    2020-10-18 07:44:18,067 [http.get:71]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-18 07:44:18,164 [http.get:71]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-18 07:44:30,256 [base.install:100]:Installing supermeatboy_no_soundtrack from service humblebundle
DEBUG    2020-10-18 07:44:30,256 [http.get:71]:GET https://lutris.net/api/games/service/humblebundle
DEBUG    2020-10-18 07:44:30,358 [__init__.fetch_script:23]:Fetching installer https://lutris.net/api/installers/super-meat-boy
DEBUG    2020-10-18 07:44:30,358 [http.get:71]:GET https://lutris.net/api/installers/super-meat-boy
DEBUG    2020-10-18 07:44:32,914 [displayconfig.get_current_resolution:621]:Retrieving current resolution
INFO     2020-10-18 07:44:36,503 [installer.prepare_game_files:147]:Should install []
INFO     2020-10-18 07:44:36,506 [humblebundle.get_humble_download_link:313]:Found 1 download for supermeatboy_no_soundtrack
INFO     2020-10-18 07:44:36,506 [humblebundle.get_humble_download_link:315]:Reloading order Humble Indie Bundle V
DEBUG    2020-10-18 07:44:36,508 [http.get:71]:GET https://www.humblebundle.com/api/v1/order/E2M4ttAVFXeS?all_tpkds=true
DEBUG    2020-10-18 07:44:37,120 [files_box.check_files_ready:46]:Files are ready? True
DEBUG    2020-10-18 07:44:37,123 [interpreter.create_game_folder:177]:Creating destination path /home/legluondunet/Games/humblebundle/super-meat-boy
INFO     2020-10-18 07:44:38,490 [files_box.on_file_available:70]:All files available
INFO     2020-10-18 07:44:38,490 [installerwindow.on_files_available:411]:All files are available, continuing install
DEBUG    2020-10-18 07:44:38,493 [interpreter._iter_commands:309]:Installer command: {'chmodx': 'meatboy-archive'}
INFO     2020-10-18 07:44:38,494 [cache.save_to_cache:28]:File is already cached in /tmp/lutris-cache/super-meat-boy/meatboy_archive, skipping
DEBUG    2020-10-18 07:44:38,501 [interpreter._iter_commands:309]:Installer command: {'execute': {'args': '--destination $GAMEDIR', 'file': 'meatboy-archive'}}
DEBUG    2020-10-18 07:44:38,508 [command.start:131]:STEAM_RUNTIME="/home/legluondunet/.local/share/lutris/runtime/steam"
DEBUG    2020-10-18 07:44:38,509 [command.start:131]:LD_LIBRARY_PATH="/home/legluondunet/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/legluondunet/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/i386/lib:/home/legluondunet/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/i386/usr/lib:/home/legluondunet/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/lib:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2020-10-18 07:44:38,509 [command.start:131]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.8/dist-packages"
DEBUG    2020-10-18 07:44:38,509 [command.start:132]:/usr/share/lutris/bin/lutris-wrapper /tmp/lutris-cache/super-meat-boy/meatboy_archive/supermeatboy-linux-11112013-bin 0 0 /tmp/lutris-cache/super-meat-boy/meatboy_archive/supermeatboy-linux-11112013-bin --destination /home/legluondunet/Games/humblebundle/super-meat-boy
Running /tmp/lutris-cache/super-meat-boy/meatboy_archive/supermeatboy-linux-11112013-bin --destination /home/legluondunet/Games/humblebundle/super-meat-boy
Initial process has started with pid 938026
Start monitoring process.
/usr/bin/gnome-terminal.real: symbol lookup error: /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0: undefined symbol: atk_component_scroll_to_point
Monitored process exited.
Initial process has exited (return code: 32512)
All children have exited.
Exit with returncode 32512
DEBUG    2020-10-18 07:44:38,696 [command.on_stop:180]:Process hasn't terminated yet
DEBUG    2020-10-18 07:44:38,696 [command.on_stop:182]:Process 938023 has terminated with code 0
DEBUG    2020-10-18 07:44:39,522 [installer.write_game_config:217]:Writing game config to /home/legluondunet/.config/lutris/games/super-meat-boy-humble-bundle-1602999879.yml
DEBUG    2020-10-18 07:44:39,903 [game.save:261]:Saving Super Meat Boy (linux) with config ID super-meat-boy-humble-bundle-1602999879
DEBUG    2020-10-18 07:44:41,707 [http.get:71]:GET https://lutris.net/api/games/super-meat-boy
DEBUG    2020-10-18 07:44:43,814 [system.remove_folder:220]:Removing folder /home/legluondunet/.cache/lutris/installer/super-meat-boy



```

**Comment by legluondunet** [comment]
Other game failed to install: OGS Majhong
```

DEBUG    2020-10-18 07:55:06,595 [base.install:100]:Installing ogsmahjong from service humblebundle
DEBUG    2020-10-18 07:55:06,596 [http.get:71]:GET https://lutris.net/api/games/service/humblebundle
INFO     2020-10-18 07:55:06,743 [humblebundle.pick_download_url_from_download_info:294]:There are 2 downloads available:
DEBUG    2020-10-18 07:55:09,204 [displayconfig.get_current_resolution:621]:Retrieving current resolution
INFO     2020-10-18 07:55:12,612 [installer.prepare_game_files:147]:Should install []
INFO     2020-10-18 07:55:12,616 [humblebundle.get_humble_download_link:313]:Found 1 download for ogsmahjong
INFO     2020-10-18 07:55:12,616 [humblebundle.get_humble_download_link:315]:Reloading order OGS Mahjong Deluxe
DEBUG    2020-10-18 07:55:12,617 [http.get:71]:GET https://www.humblebundle.com/api/v1/order/RtKh62zK8uWxMpwU?all_tpkds=true
INFO     2020-10-18 07:55:13,032 [humblebundle.pick_download_url_from_download_info:294]:There are 2 downloads available:
DEBUG    2020-10-18 07:55:13,040 [files_box.check_files_ready:46]:Files are ready? True
DEBUG    2020-10-18 07:55:13,044 [interpreter.create_game_folder:177]:Creating destination path /home/legluondunet/Games/humblebundle/ogs-mahjong
INFO     2020-10-18 07:55:14,303 [files_box.on_file_available:70]:All files available
INFO     2020-10-18 07:55:14,303 [installerwindow.on_files_available:411]:All files are available, continuing install
DEBUG    2020-10-18 07:55:14,305 [interpreter._iter_commands:309]:Installer command: {'extract': {'file': 'humblegame'}}
INFO     2020-10-18 07:55:14,306 [cache.save_to_cache:28]:File is already cached in /tmp/lutris-cache/ogs-mahjong/humblegame, skipping
DEBUG    2020-10-18 07:55:14,307 [commands.extract:169]:Extracting ogs-mahjong-deluxe-1.1.0-linux64.tar.7z
DEBUG    2020-10-18 07:55:14,307 [commands.extract:173]:extracting file /tmp/lutris-cache/ogs-mahjong/humblegame/ogs-mahjong-deluxe-1.1.0-linux64.tar.7z to /home/legluondunet/Games/humblebundle/ogs-mahjong
DEBUG    2020-10-18 07:55:14,321 [extract.extract_archive:122]:Extracting /tmp/lutris-cache/ogs-mahjong/humblegame/ogs-mahjong-deluxe-1.1.0-linux64.tar.7z to /home/legluondunet/Games/humblebundle/ogs-mahjong

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=fr_FR.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 231794338 bytes (222 MiB)                  

Extracting archive: /tmp/lutris-cache/ogs-mahjong/humblegame/ogs-mahjong-deluxe-1.1.0-linux64.tar.7z
--
Path = /tmp/lutris-cache/ogs-mahjong/humblegame/ogs-mahjong-deluxe-1.1.0-linux64.tar.7z
Type = 7z
Physical Size = 231794338
Headers Size = 155
Method = LZMA:24
Solid = -
Blocks = 2

Everything is Ok                             

Files: 2
Size:       319805440
Compressed: 231794338
DEBUG    2020-10-18 07:55:27,023 [extract.extract_archive:175]:Finished extracting /tmp/lutris-cache/ogs-mahjong/humblegame/ogs-mahjong-deluxe-1.1.0-linux64.tar.7z to /home/legluondunet/Games/humblebundle/ogs-mahjong
DEBUG    2020-10-18 07:55:27,024 [commands._killable_process:521]:Process <function extract_archive at 0x7efcc1efb040> returned: ('/tmp/lutris-cache/ogs-mahjong/humblegame/ogs-mahjong-deluxe-1.1.0-linux64.tar.7z', '/home/legluondunet/Games/humblebundle/ogs-mahjong')
DEBUG    2020-10-18 07:55:27,032 [commands.extract:175]:Extract done
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 312, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 344, in _finish_install
    self.installer.save()
  File "/usr/lib/python3/dist-packages/lutris/installer/installer.py", line 229, in save
    configpath = self.write_game_config()
  File "/usr/lib/python3/dist-packages/lutris/installer/installer.py", line 214, in write_game_config
    config = self.get_game_config()
  File "/usr/lib/python3/dist-packages/lutris/installer/installer.py", line 207, in get_game_config
    if AUTO_WIN32_EXE in config["game"].get("exe", ""):
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by strycore** [comment]
For Super Meat Boy I deleted the installer from the website to let lutris generate one.
For OGS Majhong, Lutris wasn't able to guess the path of the executable. Can you send the details of the game directory?
(cd ogs-majhong && file *)

**Comment by legluondunet** [comment]
et voilà:

```
~/Games/ogs-mahjong$ file *
icons:               directory
lib:                 directory
mj:                  Bourne-Again shell script, ASCII text executable 
ogs-mahjong.desktop: UTF-8 Unicode text
ogs-mahjong.sh:      Bourne-Again shell script, UTF-8 Unicode text executable
res:                 directory

```

**Comment by strycore** [comment]
Ok, I've added support for "Bourne-Again shell script" so it will find something now. The problem is that it could return the wrong one (I'm guessing the correct one is "ogs-mahjong.sh" and not "mj")

**Comment by strycore** [comment]
auto-installers won't always be 100% correct anyway and in that case, it can be fixed by a script on the website
