### ISSUE TITLE
Lutris does not purpose correct scripts, game id problem?

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3214]
I asked Lutris to install neverwinternights enhanced edition and it listed me diamond edition scripts:
more than words:
![Capture d’écran de 2020-10-19 13-55-17](https://user-images.githubusercontent.com/325405/96448031-191de400-1213-11eb-9f0f-50ad9c3ba4d2.png)

It's an game id problem?

**Comment by legluondunet** [comment]
```
DEBUG    2020-10-19 13:53:40,091 [command.start:131]:PYTHONPATH="/home/legluondunet/Autres_applications/Jeux/Lutris/lutris:/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/bin:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.8/dist-packages"
DEBUG    2020-10-19 13:53:40,091 [command.start:132]:/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/share/lutris/bin/lutris-wrapper Neverwinter Nights: Enhanced Edition 0 0 gamemoderun /home/legluondunet/Games/neverwinter-nights-enhanced-edition/start.sh
Running gamemoderun /home/legluondunet/Games/neverwinter-nights-enhanced-edition/start.sh
Initial process has started with pid 1051718
Start monitoring process.
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
Running Neverwinter Nights: Enhanced Edition
Working Directory For Game Install Is: /home/legluondunet/Games/neverwinter-nights-enhanced-edition/game
Working Directory For Your Resources Is: /home/legluondunet/.local/share/Neverwinter Nights
INFO: set viewport
Registering crash signal handlers.
DEBUG    2020-10-19 13:54:16,448 [base.install:118]:Installing 1097893768 from service gog
DEBUG    2020-10-19 13:54:16,448 [http.get:73]:GET https://lutris.net/api/games/service/gog
DEBUG    2020-10-19 13:54:16,578 [__init__.fetch_script:23]:Fetching installer https://lutris.net/api/installers/neverwinter-nights
DEBUG    2020-10-19 13:54:16,578 [http.get:73]:GET https://lutris.net/api/installers/neverwinter-nights
DEBUG    2020-10-19 13:59:52,593 [base.install:118]:Installing 1207659051 from service gog
DEBUG    2020-10-19 13:59:52,593 [http.get:73]:GET https://lutris.net/api/games/service/gog
DEBUG    2020-10-19 13:59:52,729 [__init__.fetch_script:23]:Fetching installer https://lutris.net/api/installers/sid-meiers-colonization
DEBUG    2020-10-19 13:59:52,729 [http.get:73]:GET https://lutris.net/api/installers/sid-meiers-colonization
DEBUG    2020-10-19 14:00:15,095 [base.install:118]:Installing 1207658876 from service gog
DEBUG    2020-10-19 14:00:15,095 [http.get:73]:GET https://lutris.net/api/games/service/gog
DEBUG    2020-10-19 14:00:15,210 [__init__.fetch_script:23]:Fetching installer https://lutris.net/api/installers/serious-sam-the-first-encounter
DEBUG    2020-10-19 14:00:15,211 [http.get:73]:GET https://lutris.net/api/installers/serious-sam-the-first-encounter
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function InputDevice.__del__ at 0x7f46d4086040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
DEBUG    2020-10-19 14:00:43,459 [displayconfig.get_current_resolution:621]:Retrieving current resolution
DEBUG    2020-10-19 14:00:43,459 [prefix.set_virtual_desktop:202]:Enabling wine virtual desktop with default resolution of 1920x1080
DEBUG    2020-10-19 14:00:43,641 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/system32/dxgi with DXVK version
DEBUG    2020-10-19 14:00:43,683 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/system32/d3d11 with DXVK version
DEBUG    2020-10-19 14:00:43,734 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/system32/d3d10core with DXVK version
DEBUG    2020-10-19 14:00:43,771 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/system32/d3d9 with DXVK version
DEBUG    2020-10-19 14:00:43,813 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/system32/d3d12 with DXVK version
DEBUG    2020-10-19 14:00:43,834 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/syswow64/dxgi with DXVK version
DEBUG    2020-10-19 14:00:43,852 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/syswow64/d3d11 with DXVK version
DEBUG    2020-10-19 14:00:43,906 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/syswow64/d3d10core with DXVK version
DEBUG    2020-10-19 14:00:43,924 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/syswow64/d3d9 with DXVK version
DEBUG    2020-10-19 14:00:43,956 [dxvk.enable_dxvk_dll:173]:Replacing /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/windows/syswow64/d3d12 with DXVK version
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:STEAM_RUNTIME="/home/legluondunet/.local/share/lutris/runtime/steam"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:LD_LIBRARY_PATH="/home/legluondunet/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/lib:/home/legluondunet/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/lib64:/lib64:/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/lib/i386-linux-gnu/sse2:/usr/lib/i386-linux-gnu/i686/sse2:/lib:/usr/local/lib:/usr/lib32:/lib32:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/lib32:/home/legluondunet/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/i386/lib:/home/legluondunet/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/i386/usr/lib:/home/legluondunet/.local/share/lutris/runtime/lib64:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/lib:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/legluondunet/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:DXVK_HUD="full"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:WINEDEBUG="-all"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:WINEARCH="win64"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:WINE="/home/legluondunet/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/bin/wine"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:WINEPREFIX="/home/legluondunet/Games/serious-sam-the-first-encounter"
DEBUG    2020-10-19 14:00:44,135 [command.start:131]:WINEESYNC="0"
DEBUG    2020-10-19 14:00:44,136 [command.start:131]:WINEFSYNC="0"
DEBUG    2020-10-19 14:00:44,136 [command.start:131]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2020-10-19 14:00:44,136 [command.start:131]:game_name="Serious Sam - The First Encounter"
DEBUG    2020-10-19 14:00:44,136 [command.start:131]:PYTHONPATH="/home/legluondunet/Autres_applications/Jeux/Lutris/lutris:/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/bin:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.8/dist-packages"
DEBUG    2020-10-19 14:00:44,136 [command.start:132]:/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/share/lutris/bin/lutris-wrapper Serious Sam - The First Encounter 0 0 gamemoderun /home/legluondunet/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/bin/wine /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/GOG Games/Serious Sam The First Encounter/Bin/SeriousSam.exe
Running gamemoderun /home/legluondunet/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/bin/wine /home/legluondunet/Games/serious-sam-the-first-encounter/drive_c/GOG Games/Serious Sam The First Encounter/Bin/SeriousSam.exe
Initial process has started with pid 1052562
Start monitoring process.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
user.reg:553: Malformed value '"HDA NVidia HDMI/DP,pc"=3 (js)"="disabled"'
DEBUG    2020-10-19 14:00:52,296 [base.install:118]:Installing 1207658876 from service gog
DEBUG    2020-10-19 14:00:52,297 [http.get:73]:GET https://lutris.net/api/games/service/gog
DEBUG    2020-10-19 14:00:52,416 [__init__.fetch_script:23]:Fetching installer https://lutris.net/api/installers/serious-sam-the-first-encounter
DEBUG    2020-10-19 14:00:52,416 [http.get:73]:GET https://lutris.net/api/installers/serious-sam-the-first-encounter
Monitored process exited.
Initial process has exited (return code: 0)
All children have exited.
Exit with returncode 0
DEBUG    2020-10-19 14:01:22,334 [command.on_stop:180]:Process hasn't terminated yet
DEBUG    2020-10-19 14:01:22,334 [command.on_stop:182]:Process 1051716 has terminated with code 0
DEBUG    2020-10-19 14:01:23,922 [game.beat:536]:Game thread stopped
WARNING  2020-10-19 14:01:23,922 [game.on_game_quit:566]:Game still running (state: running)
INFO     2020-10-19 14:01:23,923 [game.stop:551]:Stopping Neverwinter Nights: Enhanced Edition (linux)
DEBUG    2020-10-19 14:01:23,987 [game.on_game_quit:587]:Neverwinter Nights: Enhanced Edition stopped at lun., 19 oct. 2020 14:01:23
DEBUG    2020-10-19 14:01:23,987 [game.save:261]:Saving Neverwinter Nights: Enhanced Edition (linux) with config ID neverwinter-nights-enhanced-e-gog-1601492793



```

**Comment by strycore** [comment]
game matching issues are to be solved on the website
