### ISSUE TITLE
Lutris just crashed after uninstalled a game

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3226]
Helllo dev team,
Lutris just crashed after uninstalled a game:

```
./lutris 
Unable to load locale dir, translations won't work.
2020-10-22 11:11:48,616: MAME XML generation launched in the background, not returning anything this time
2020-10-22 11:11:48,616: Getting full game list from MAME...
2020-10-22 11:11:48,619: MAME isn't installed, can't retrieve systems list.
2020-10-22 11:11:48,735: Lutris 0.5.7.1
2020-10-22 11:11:48,735: Running Intel Mesa driver 20.1.8 on Mesa Intel(R) HD Graphics 5300 (BDW GT2) (0x161e)
2020-10-22 11:11:48,736: GPU: 8086:161E 103C:2271 (i915 drivers)
2020-10-22 11:11:49,326: MAME XML written

(lutris:3912): Gtk-WARNING **: 11:12:13.714: ../gtk/gtk/gtktreemodel.c:657: Invalid path 0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24 passed to gtk_tree_path_new_from_string
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1218, in __new__
    return TreePath.new_from_string(path)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/legluondunet/Téléchargements/lutris/lutris/gui/views/base.py", line 34, in popup_contextual_menu
    selected_id = self.get_selected_id(self.get_model().get_iter(view.current_path))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 873, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 848, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1220, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24' as a tree path

(lutris:3912): Gtk-WARNING **: 11:12:14.131: ../gtk/gtk/gtktreemodel.c:657: Invalid path 0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24 passed to gtk_tree_path_new_from_string
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1218, in __new__
    return TreePath.new_from_string(path)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/legluondunet/Téléchargements/lutris/lutris/gui/views/base.py", line 34, in popup_contextual_menu
    selected_id = self.get_selected_id(self.get_model().get_iter(view.current_path))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 873, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 848, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1220, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24' as a tree path

(lutris:3912): Gtk-WARNING **: 11:12:14.135: ../gtk/gtk/gtktreemodel.c:657: Invalid path 0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24 passed to gtk_tree_path_new_from_string
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1218, in __new__
    return TreePath.new_from_string(path)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/legluondunet/Téléchargements/lutris/lutris/gui/views/base.py", line 34, in popup_contextual_menu
    selected_id = self.get_selected_id(self.get_model().get_iter(view.current_path))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 873, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 848, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1220, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24' as a tree path

(lutris:3912): Gtk-WARNING **: 11:12:14.381: ../gtk/gtk/gtktreemodel.c:657: Invalid path 0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24 passed to gtk_tree_path_new_from_string
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1218, in __new__
    return TreePath.new_from_string(path)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/legluondunet/Téléchargements/lutris/lutris/gui/views/base.py", line 34, in popup_contextual_menu
    selected_id = self.get_selected_id(self.get_model().get_iter(view.current_path))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 873, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 848, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1220, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24' as a tree path

(lutris:3912): Gtk-WARNING **: 11:12:14.384: ../gtk/gtk/gtktreemodel.c:657: Invalid path 0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24 passed to gtk_tree_path_new_from_string
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1218, in __new__
    return TreePath.new_from_string(path)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/legluondunet/Téléchargements/lutris/lutris/gui/views/base.py", line 34, in popup_contextual_menu
    selected_id = self.get_selected_id(self.get_model().get_iter(view.current_path))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 873, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 848, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1220, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '0:<Gtk.TreeViewColumn object at 0x7f9b38108d80 (GtkTreeViewColumn at 0x555e5290c8f0)>:186:24' as a tree path
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: xcb_io.c :260 : poll_for_event:  l'assertion « !xcb_xlib_threads_sequence_lost » a échoué.
Abandon (core dumped)
```

**Comment by legluondunet** [comment]
I can still reproduce this issue

**Comment by legluondunet** [comment]
just happened after uninstalling a game:

```
$ ./bin/lutris -d
Unable to load locale dir, translations won't work.
INFO     2020-10-31 07:42:39,913 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-31 07:42:39,941 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-31 07:42:39,941 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-31 07:42:39,942 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
DEBUG    2020-10-31 07:42:41,684 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-31 07:42:41,817 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-31 07:42:41,927 [http.get:73]:GET https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/24x24/apps/lutris.png
DEBUG    2020-10-31 07:42:41,927 [http.get:73]:GET https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/24x24/apps/steam.png
DEBUG    2020-10-31 07:42:41,935 [http.get:73]:GET https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/scalable/apps/lutris.svg
INFO     2020-10-31 07:42:42,160 [http.write_to_file:123]:Writing to /home/romain/.local/share/lutris/runtime/icons/hicolor/24x24/apps/lutris.png
INFO     2020-10-31 07:42:42,182 [http.write_to_file:123]:Writing to /home/romain/.local/share/lutris/runtime/icons/hicolor/24x24/apps/steam.png
INFO     2020-10-31 07:42:42,198 [http.write_to_file:123]:Writing to /home/romain/.local/share/lutris/runtime/icons/hicolor/scalable/apps/lutris.svg
DEBUG    2020-10-31 07:42:59,515 [config.remove:195]:Removed config /home/romain/.config/lutris/games/chronicles-of-the-sword-cd-1579977121.yml
DEBUG    2020-10-31 07:42:59,516 [system.remove_folder:220]:Removing folder /home/romain/Games/chronicles-of-the-sword
DEBUG    2020-10-31 07:45:20,493 [config.remove:195]:Removed config /home/romain/.config/lutris/games/d-the-game-cd-dos-1573887263.yml
DEBUG    2020-10-31 07:45:20,494 [system.remove_folder:220]:Removing folder /home/romain/Games/d-the-game
Erreur de segmentation (core dumped)

```

**Comment by legluondunet** [comment]
another one:
```

$ ./bin/lutris -d
Unable to load locale dir, translations won't work.
INFO     2020-10-31 07:42:39,913 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-31 07:42:39,941 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-31 07:42:39,941 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-31 07:42:39,942 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
DEBUG    2020-10-31 07:42:41,684 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-31 07:42:41,817 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-31 07:42:41,927 [http.get:73]:GET https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/24x24/apps/lutris.png
DEBUG    2020-10-31 07:42:41,927 [http.get:73]:GET https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/24x24/apps/steam.png
DEBUG    2020-10-31 07:42:41,935 [http.get:73]:GET https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/scalable/apps/lutris.svg
INFO     2020-10-31 07:42:42,160 [http.write_to_file:123]:Writing to /home/romain/.local/share/lutris/runtime/icons/hicolor/24x24/apps/lutris.png
INFO     2020-10-31 07:42:42,182 [http.write_to_file:123]:Writing to /home/romain/.local/share/lutris/runtime/icons/hicolor/24x24/apps/steam.png
INFO     2020-10-31 07:42:42,198 [http.write_to_file:123]:Writing to /home/romain/.local/share/lutris/runtime/icons/hicolor/scalable/apps/lutris.svg
DEBUG    2020-10-31 07:42:59,515 [config.remove:195]:Removed config /home/romain/.config/lutris/games/chronicles-of-the-sword-cd-1579977121.yml
DEBUG    2020-10-31 07:42:59,516 [system.remove_folder:220]:Removing folder /home/romain/Games/chronicles-of-the-sword
DEBUG    2020-10-31 07:45:20,493 [config.remove:195]:Removed config /home/romain/.config/lutris/games/d-the-game-cd-dos-1573887263.yml
DEBUG    2020-10-31 07:45:20,494 [system.remove_folder:220]:Removing folder /home/romain/Games/d-the-game
Erreur de segmentation (core dumped)
romain@tipingouin-home:~/Autres_applications/Jeux/Lutris/lutris$ ./bin/lutris -d
Unable to load locale dir, translations won't work.
INFO     2020-10-31 07:45:52,668 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-31 07:45:52,668 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-31 07:45:52,669 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-31 07:45:52,669 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
DEBUG    2020-10-31 07:45:55,047 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-31 07:45:55,134 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-31 07:45:55,266 [http.get:73]:GET https://raw.githubusercontent.com/lutris/lutris-runtime/master/icons/hicolor/24x24/apps/steam.png
INFO     2020-10-31 07:45:55,339 [http.write_to_file:123]:Writing to /home/romain/.local/share/lutris/runtime/icons/hicolor/24x24/apps/steam.png
DEBUG    2020-10-31 07:47:20,888 [config.remove:195]:Removed config /home/romain/.config/lutris/games/blade-runner-cd-dxwnd-1564935914.yml
DEBUG    2020-10-31 07:47:20,889 [system.remove_folder:220]:Removing folder /home/romain/Games/blade-runner-wine
DEBUG    2020-10-31 07:47:35,830 [config.remove:195]:Removed config /home/romain/.config/lutris/games/blade-runner-cd-1564936321.yml
DEBUG    2020-10-31 07:47:35,831 [system.remove_folder:220]:Removing folder /home/romain/Games/blade-runner-scummvm/Blade Runner/
DEBUG    2020-10-31 07:47:43,166 [config.remove:195]:Removed config /home/romain/.config/lutris/games/doom-3-dhewm3-steam-data-1604010171.yml
DEBUG    2020-10-31 07:48:09,290 [config.remove:195]:Removed config /home/romain/.config/lutris/games/enclave-gog-dxwnd-1579551262.yml
DEBUG    2020-10-31 07:48:09,291 [system.remove_folder:220]:Removing folder /home/romain/Games/enclave

(lutris:611509): Pango-CRITICAL **: 07:48:11.971: pango_layout_get_extents: assertion 'layout != NULL' failed

(lutris:611509): Pango-CRITICAL **: 07:48:11.971: pango_layout_get_line_count: assertion 'layout != NULL' failed

(lutris:611509): Gtk-CRITICAL **: 07:48:11.971: gtk_render_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed
DEBUG    2020-10-31 07:48:25,918 [config.remove:195]:Removed config /home/romain/.config/lutris/games/enemy-zero-cd-dxwnd-1564768521.yml
DEBUG    2020-10-31 07:48:25,918 [system.remove_folder:220]:Removing folder /home/romain/Games/enemy-zero
Erreur de segmentation (core dumped)

```

**Comment by legluondunet** [comment]
a last one:
```

$ ./bin/lutris -d
Unable to load locale dir, translations won't work.
INFO     2020-10-31 07:56:28,894 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-31 07:56:28,894 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-31 07:56:28,894 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-31 07:56:28,895 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
DEBUG    2020-10-31 07:56:30,717 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-31 07:56:30,838 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-31 07:57:14,585 [config.remove:195]:Removed config /home/romain/.config/lutris/games/tomb-raider-i-steam-tombati-hd-1587989165.yml
DEBUG    2020-10-31 07:57:49,451 [config.remove:195]:Removed config /home/romain/.config/lutris/games/tomb-raider-iv-the-last-revel-gog-dgvoodoo2-1587009714.yml
DEBUG    2020-10-31 07:57:49,452 [system.remove_folder:220]:Removing folder /home/romain/Games/tomb-raider-the-last-revelation
DEBUG    2020-10-31 07:58:17,921 [config.remove:195]:Removed config /home/romain/.config/lutris/games/worlds-of-ultima-the-savage-e-gog-1588289322.yml
DEBUG    2020-10-31 07:58:17,922 [system.remove_folder:220]:Removing folder /home/romain/Games/worlds-of-ultima-the-savage-empire
DEBUG    2020-10-31 07:58:28,476 [config.remove:195]:Removed config /home/romain/.config/lutris/games/oddworld-abes-oddysee-gog-dxwnd-1565941078.yml
DEBUG    2020-10-31 07:58:28,476 [system.remove_folder:220]:Removing folder /home/romain/Games/oddworld-abes-oddysee
DEBUG    2020-10-31 07:58:42,713 [config.remove:195]:Removed config /home/romain/.config/lutris/games/discworld-cd-scummvm-1588110244.yml
DEBUG    2020-10-31 07:58:42,714 [system.remove_folder:220]:Removing folder /home/romain/Games/discworld
DEBUG    2020-10-31 07:59:04,621 [config.remove:195]:Removed config /home/romain/.config/lutris/games/alone-in-the-dark-the-new-nig-gog-dxwnd-1600548663.yml
DEBUG    2020-10-31 07:59:04,621 [system.remove_folder:220]:Removing folder /home/romain/Games/alone-in-the-dark-the-new-nightmare
DEBUG    2020-10-31 07:59:19,714 [config.remove:195]:Removed config /home/romain/.config/lutris/games/beneath-a-steel-sky-gog-1587811216.yml
DEBUG    2020-10-31 07:59:31,600 [config.remove:195]:Removed config /home/romain/.config/lutris/games/beneath-a-steel-sky-change-me-1597498131.yml
DEBUG    2020-10-31 07:59:31,600 [system.remove_folder:220]:Removing folder /home/romain/Games/beneath-a-steel-sky-steam
Erreur de segmentation (core dumped)
romain@tipingouin-home:~/Autres_applications/Jeux/Lutris/lutris$ ./bin/lutris -d
Unable to load locale dir, translations won't work.
INFO     2020-10-31 07:59:47,928 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-31 07:59:47,928 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-10-31 07:59:47,928 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-10-31 07:59:47,928 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
DEBUG    2020-10-31 07:59:49,793 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-31 07:59:49,893 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-31 08:02:43,052 [config.remove:195]:Removed config /home/romain/.config/lutris/games/dragonsphere-gog-1579265357.yml
DEBUG    2020-10-31 08:02:43,053 [system.remove_folder:220]:Removing folder /home/romain/Games/dragonsphere
DEBUG    2020-10-31 08:02:56,665 [config.remove:195]:Removed config /home/romain/.config/lutris/games/disney-the-lion-king-gog-1574376023.yml
DEBUG    2020-10-31 08:02:56,666 [system.remove_folder:220]:Removing folder /home/romain/Games/disney-the-lion-king
DEBUG    2020-10-31 08:03:07,067 [config.remove:195]:Removed config /home/romain/.config/lutris/games/jotun-gogcom-1580418251.yml
DEBUG    2020-10-31 08:03:07,068 [system.remove_folder:220]:Removing folder /home/romain/Games/jotun
DEBUG    2020-10-31 08:03:27,329 [config.remove:195]:Removed config /home/romain/.config/lutris/games/moto-racer-2-gog-dxwnd-1576470556.yml
DEBUG    2020-10-31 08:03:27,330 [system.remove_folder:220]:Removing folder /home/romain/Games/moto-racer-2

(lutris:612079): Gtk-CRITICAL **: 08:03:27.647: gtk_container_propagate_draw: assertion '_gtk_widget_get_parent (child) == GTK_WIDGET (container)' failed
DEBUG    2020-10-31 08:03:46,622 [config.remove:195]:Removed config /home/romain/.config/lutris/games/cyber-gladiators-cd-nglide-dxwnd-1584918071.yml
DEBUG    2020-10-31 08:03:46,623 [system.remove_folder:220]:Removing folder /home/romain/Games/cyber-gladiators
DEBUG    2020-10-31 08:04:00,125 [config.remove:195]:Removed config /home/romain/.config/lutris/games/far-cry-3-steam-lgdn-1588971675.yml
DEBUG    2020-10-31 08:04:00,125 [system.remove_folder:220]:Removing folder /home/romain/Games/far-cry-3
DEBUG    2020-10-31 08:04:14,306 [config.remove:195]:Removed config /home/romain/.config/lutris/games/future-pinball-19120101231-27-1602238824.yml
DEBUG    2020-10-31 08:04:14,306 [system.remove_folder:220]:Removing folder /home/romain/Games/future-pinball
DEBUG    2020-10-31 08:04:25,199 [config.remove:195]:Removed config /home/romain/.config/lutris/games/figment-gog-1580547636.yml
DEBUG    2020-10-31 08:04:25,199 [system.remove_folder:220]:Removing folder /home/romain/Games/figment
DEBUG    2020-10-31 08:04:43,296 [config.remove:195]:Removed config /home/romain/.config/lutris/games/lego-indiana-jones-the-origin-gog-1601937904.yml
DEBUG    2020-10-31 08:04:54,850 [config.remove:195]:Removed config /home/romain/.config/lutris/games/heretic-ii-cd-dxwnd-ws-patch-1585656814.yml
DEBUG    2020-10-31 08:04:54,851 [system.remove_folder:220]:Removing folder /home/romain/Games/heretic-ii-us
**
Gtk:ERROR:../../../../gtk/gtkcssinheritvalue.c:33:gtk_css_value_inherit_free: code should not be reached
**
Gtk:ERROR:../../../../gtk/gtkcssinheritvalue.c:33:gtk_css_value_inherit_free: code should not be reached
Bail out! Gtk:ERROR:../../../../gtk/gtkcssinheritvalue.c:33:gtk_css_value_inherit_free: code should not be reached
Bail out! Gtk:ERROR:../../../../gtk/gtkcssinheritvalue.c:33:gtk_css_value_inherit_free: code should not be reached
Abandon (core dumped)

```

**Comment by strycore** [comment]
Lutris should no longer crash and the view should now update properly.
