### ISSUE TITLE
lutris beta: error mesages about device.py

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3250]
Hello Lutris dev team,
I just launched last Lutris beta and I obtained this error messages, I don't know if it's important, just in case:

```
$ ./bin/lutris -d
Unable to load locale dir, translations won't work.
INFO     2020-11-03 01:19:51,262 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-11-03 01:19:51,516 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-11-03 01:19:51,517 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-11-03 01:19:51,518 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
DEBUG    2020-11-03 01:20:06,053 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-11-03 01:20:06,175 [http.get:73]:GET https://lutris.net/api/runtimes/icons
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Exception ignored in: <function InputDevice.__del__ at 0x7fe0494b5040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
```

**Comment by strycore** [comment]
this is not our bug.
