### ISSUE TITLE
lutris beta: double click on a banner in "all games" section does not show install window menu

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3252]
Hello,

I was in "all games" section and I double click on a non installed game banner to launch install process and nothing appear.
In terminal I obtained this log:

```
$ ./bin/lutris -d
Unable to load locale dir, translations won't work.
INFO     2020-11-03 01:48:33,363 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-11-03 01:48:33,363 [startup.check_driver:61]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-11-03 01:48:33,363 [startup.check_driver:65]:GPU: GeForce GTX 770
INFO     2020-11-03 01:48:33,364 [startup.check_driver:81]:GPU: 10DE:1184 1462:2825 (nvidia drivers)
DEBUG    2020-11-03 01:48:35,173 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-11-03 01:48:35,281 [http.get:73]:GET https://lutris.net/api/runtimes/icons
Traceback (most recent call last):
  File "/home/romain/Autres_applications/Jeux/Lutris/lutris/lutris/gui/lutriswindow.py", line 789, in on_game_activated
    if self.service.id == "lutris":
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/romain/Autres_applications/Jeux/Lutris/lutris/lutris/gui/lutriswindow.py", line 789, in on_game_activated
    if self.service.id == "lutris":
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/romain/Autres_applications/Jeux/Lutris/lutris/lutris/gui/lutriswindow.py", line 789, in on_game_activated
    if self.service.id == "lutris":
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/romain/Autres_applications/Jeux/Lutris/lutris/lutris/gui/widgets/game_bar.py", line 221, in on_install_clicked
    self.service.install(self.db_game)
  File "/home/romain/Autres_applications/Jeux/Lutris/lutris/lutris/services/base.py", line 117, in install
    appid = db_game["appid"]
KeyError: 'appid'

```

**Comment by strycore** [comment]
this seems fixed already
