### ISSUE TITLE
'ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by ace510** [lutris/lutris#3275]
**Describe the bug**

whenever I launch Lutris after my last reboot it never even opens a screen,

if I launch it like
$ lutris
from the commandline, it gives an error

Unable to load locale dir, translations won't work.
Traceback (most recent call last):
  File "/usr/bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.command import exec_command
  File "/usr/lib/python3.9/site-packages/lutris/command.py", line 17, in <module>
    from lutris import runtime, settings
  File "/usr/lib/python3.9/site-packages/lutris/runtime.py", line 12, in <module>
    from lutris.util.downloader import Downloader
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

the system package 'python3-requests' is installed, and I can even open a Python shell and import the library that way

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

launch lutris

Unable to load locale dir, translations won't work.
Traceback (most recent call last):
  File "/usr/bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.command import exec_command
  File "/usr/lib/python3.9/site-packages/lutris/command.py", line 17, in <module>
    from lutris import runtime, settings
  File "/usr/lib/python3.9/site-packages/lutris/runtime.py", line 12, in <module>
    from lutris.util.downloader import Downloader
  File "/usr/lib/python3.9/site-packages/lutris/util/downloader.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information (Optional)**
Fedora 33

32GB RAM
>1TB of free disk space
NVIDIA Graphics card with 455 driver

If you believe your issue is related to your system (on a hardware or OS level), it can be useful to for us to have more detailed information about your system. You can attach this information `lutris --submit-issue` in a terminal and attaching the resulting JSON file to this issue (please do not paste the file content directly on the issue)

**Screenshots (Optional)**

If your issue is hard to explain with words, feel free to attach screenshots.

**Comment by strycore** [comment]
your version of python probably upgraded and the lutris dependencies are still for python 3.8? 
If so, try reinstalling lutris and it should fix the problem

**Comment by strycore** [comment]
Marking this as fixed.
