### ISSUE TITLE
Context menu for installed game doesn't appear in list view

### ISSUE THREAD

**Issue by TotalCaesar659** [lutris/lutris#3305]
**Describe the bug**

Context menu doesn't appear when right-clicking on installed game in list view.

**Steps to reproduce**

- Install any game.
- Switch to grid view, press right mouse button on installed game and see context menu.
- Switch to list view, press right mouse button on installed game again and see that there is no context menu.

**Lutris debugging output (Optional)**

```
DEBUG    2020-11-21 01:24:03,298 [http.get:73]:GET https://lutris.net/api/runtimes

(lutris:33700): GLib-GIO-CRITICAL **: 01:24:03.298: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
DEBUG    2020-11-21 01:24:03,492 [http.get:73]:GET https://lutris.net/api/runtimes/icons

(lutris:33700): Gtk-WARNING **: 01:24:13.678: ../../../../gtk/gtktreemodel.c:657: Invalid path 21:<Gtk.TreeViewColumn object at 0x7fa6861e83c0 (GtkTreeViewColumn at 0x330fc50)>:44:41 passed to gtk_tree_path_new_from_string
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1206, in __new__
    return TreePath.new_from_string(path)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/views/base.py", line 34, in popup_contextual_menu
    _iter = self.get_model().get_iter(view.current_path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 866, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 841, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1208, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '21:<Gtk.TreeViewColumn object at 0x7fa6861e83c0 (GtkTreeViewColumn at 0x330fc50)>:44:41' as a tree path
```

**System information (Optional)**

Lubuntu 20.04.1, Lutris 0.5.8 (from [Releases](https://github.com/lutris/lutris/releases/tag/0.5.8)).

**Comment by bsdf** [comment]
this issue appears to be due to `Gtk.TreeView.get_path_at_pos` returning a tuple with a `Gtk.TreePath` as the first item while `Gtk.IconView` just returns the `Gtk.TreePath`.

changing `base.py:34` to:
```python
_iter = self.get_model().get_iter(view.current_path[0])
```

works for both views but i'm not sure it's the best solution
