### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by Dani9OO** [lutris/lutris#3323]
**Describe the bug**

Lutris won't open with latest version of python-yaml installed

**Steps to reproduce**

- Run lutris using python-yaml 5.3.1-4 or 5.3.1-3

**Lutris debugging output**

```
$ lutris -d
Unable to load locale dir, translations won't work.
2020-11-26 15:10:04,077: Package 'distro' unavailable. Unable to read Linux distribution
Traceback (most recent call last):
  File "/usr/bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 37, in <module>
    from lutris.game import Game
  File "/usr/lib/python3.8/site-packages/lutris/game.py", line 15, in <module>
    from lutris.config import LutrisConfig
  File "/usr/lib/python3.8/site-packages/lutris/config.py", line 12, in <module>
    from lutris.util.yaml import read_yaml_from_file, write_yaml_to_file
  File "/usr/lib/python3.8/site-packages/lutris/util/yaml.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**System information**

OS: Arch Linux
python-yaml 5.3.1-4 (latest as of 2020-11-26 15:09:00)

Also tested with python-yaml 5.3.1-3

**Comment by Dani9OO** [comment]
I resolved the issue downgrading python-yaml to 5.3.1-2
