### ISSUE TITLE
Error when syncing good old games

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#3342]
As usual, this isn't my bug, but a Fedora report.

"opened Lutris then clicked the little sync icon next to each of my connections (Steam, Humble Bundle, GOG, and Lutris)." Supposedly, Lutris crashed when this was done?

**Lutris debugging output (Optional)**

__init__.py:101:__init__:TypeError: Must be string, not ValueError

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 142, in service_load_cb
    ErrorDialog(error)
  File "/usr/lib/python3.9/site-packages/lutris/gui/dialogs/__init__.py", line 101, in __init__
    self.set_markup(message)
TypeError: Must be string, not ValueError

Local variables in innermost frame:
self: <dialogs.ErrorDialog object at 0x7faf4cc3d6c0 (lutris+gui+dialogs+ErrorDialog at 0x55859f35e3c0)>
message: ValueError('Invalid response (https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=1:200): <!DOCTYPE html><html class="\n            embed-mode prices-in-usd lang--en curr-')
secondary: None
parent: None
__class__: <class 'lutris.gui.dialogs.ErrorDialog'>

**System information (Optional)**

Fedora system running 0.5.8.1 *without* python-magic (I had to remove that from the Fedora package due to conflicts with other packages...)

Here is the link to the Redhat BZ for the report: https://bugzilla.redhat.com/show_bug.cgi?id=1902912

**Comment by SwimmingTiger** [comment]
Same issue for me.

**Steps to reproduce**

- Rename lutris database dirs. 
   ```
   mv ~/.config/lutris ~/.config/lutris-bak
   mv ~/.local/share/lutris ~/.local/share/lutris-bak
   mv ~/.cache/lutris ~/.cache/lutris-bak
   ```
- `lutris -d`
- Click on Steam in the left sidebar. (**Important step**)
   ![ScreenShot](https://user-images.githubusercontent.com/4986069/101133036-f6208580-3642-11eb-868c-aac50bd7c2a9.png)
- Click the refresh button next to Steam.
- Lutris crashes when synchronization is complete

```
➜  ~ lutris -d
/usr/lib/python3/dist-packages/gi/overrides/Gdk.py:461: Warning: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
  initialized, argv = Gdk.init_check(sys.argv)
2020-12-04 15:02:21,960: Initializing lutris
2020-12-04 15:02:23,647: Runtime up-to-date. Initialization complete.
INFO     2020-12-04 15:02:23,656 [application.do_command_line:314]:Lutris 0.5.8.1
INFO     2020-12-04 15:02:23,656 [startup.check_driver:61]:Running X.Org Mesa driver 19.2.6 on AMD RENOIR (DRM 3.38.0, 5.8.13-050813-generic, LLVM 7.0.1) (0x1636)
INFO     2020-12-04 15:02:23,657 [startup.check_driver:69]:GPU: 1002:1636 1043:1E21 (amdgpu drivers)
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/hu60/.config/MangoHud/python3.7.conf [ not found ]
parsing config: /home/hu60/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Failed to initialize CPU power data
DEBUG    2020-12-04 15:02:59,271 [base.wipe_game_cache:44]:Deleting games from service-games for steam
DEBUG    2020-12-04 15:03:00,568 [http.get:73]:GET https://lutris.net/api/games/service/steam
DEBUG    2020-12-04 15:03:01,919 [steam.load:115]:53 Steam games loaded
[1]    20821 segmentation fault  lutris -d
```

**Comment by SwimmingTiger** [comment]
If Lutris does not crash when its first refreshed, it will also be in an abnormal state. If you repeatedly click the refresh button, the original content in the Steam game list may disappear completely. And a series of 404 errors appeared in the log.

![ScreenShot](https://user-images.githubusercontent.com/4986069/101133703-3a605580-3644-11eb-8f93-edb5ec9297e3.png)

**Comment by SwimmingTiger** [comment]
Another crash without renaming lutris database dirs.

Lutris crashes after refreshing twice.

![ScreenShot](https://user-images.githubusercontent.com/4986069/101134331-2b2dd780-3645-11eb-96d6-8ea953d4e097.png)

```
➜  ~ lutris -d
/usr/lib/python3/dist-packages/gi/overrides/Gdk.py:461: Warning: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
  initialized, argv = Gdk.init_check(sys.argv)
2020-12-04 15:23:59,565: Initializing lutris
2020-12-04 15:24:01,188: Runtime up-to-date. Initialization complete.
INFO     2020-12-04 15:24:01,200 [application.do_command_line:314]:Lutris 0.5.8.1
INFO     2020-12-04 15:24:01,200 [startup.check_driver:61]:Running X.Org Mesa driver 19.2.6 on AMD RENOIR (DRM 3.38.0, 5.8.13-050813-generic, LLVM 7.0.1) (0x1636)
INFO     2020-12-04 15:24:01,200 [startup.check_driver:69]:GPU: 1002:1636 1043:1E21 (amdgpu drivers)
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/hu60/.config/MangoHud/python3.7.conf [ not found ]
parsing config: /home/hu60/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Failed to initialize CPU power data
DEBUG    2020-12-04 15:24:30,441 [base.wipe_game_cache:44]:Deleting games from service-games for steam
DEBUG    2020-12-04 15:24:31,746 [http.get:73]:GET https://lutris.net/api/games/service/steam
DEBUG    2020-12-04 15:24:33,761 [steam.load:115]:53 Steam games loaded

(lutris:28471): Gtk-CRITICAL **: 15:24:33.771: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:44: Warning: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:44: Warning: unable to set property 'markup' of type 'gchararray' from value of type '(null)'
  return Gio.Application.run(self, *args, **kwargs)

(lutris:28471): Gtk-CRITICAL **: 15:24:33.772: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:28471): Gtk-CRITICAL **: 15:24:33.772: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:28471): Gtk-CRITICAL **: 15:24:33.773: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:28471): Gtk-CRITICAL **: 15:24:33.773: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:28471): Gtk-WARNING **: 15:24:33.773: lutris+gui+views+grid+GameGridView 0x2448820 reported min size 202 and natural size 6 in get_preferred_width(); natural size must be >= min size

(lutris:28471): Pango-WARNING **: 15:24:33.798: Invalid UTF-8 string passed to pango_layout_set_text()
DEBUG    2020-12-04 15:24:33,874 [http.get:73]:GET http://cdn.akamai.steamstatic.com/steam/apps/427460/capsule_184x69.jpg
DEBUG    2020-12-04 15:24:33,875 [http.get:73]:GET http://cdn.akamai.steamstatic.com/steam/apps/737010/capsule_184x69.jpg
DEBUG    2020-12-04 15:24:33,875 [http.get:73]:GET http://cdn.akamai.steamstatic.com/steam/apps/1083500/capsule_184x69.jpg
ERROR    2020-12-04 15:24:34,429 [http.download_file:161]:Failed to get url http://cdn.akamai.steamstatic.com/steam/apps/737010/capsule_184x69.jpg: Request to http://cdn.akamai.steamstatic.com/steam/apps/737010/capsule_184x69.jpg failed: HTTP Error 404: Not Found
ERROR    2020-12-04 15:24:34,432 [http.download_file:161]:Failed to get url http://cdn.akamai.steamstatic.com/steam/apps/427460/capsule_184x69.jpg: Request to http://cdn.akamai.steamstatic.com/steam/apps/427460/capsule_184x69.jpg failed: HTTP Error 404: Not Found
ERROR    2020-12-04 15:24:34,433 [http.download_file:161]:Failed to get url http://cdn.akamai.steamstatic.com/steam/apps/1083500/capsule_184x69.jpg: Request to http://cdn.akamai.steamstatic.com/steam/apps/1083500/capsule_184x69.jpg failed: HTTP Error 404: Not Found
DEBUG    2020-12-04 15:25:25,390 [base.wipe_game_cache:44]:Deleting games from service-games for steam
DEBUG    2020-12-04 15:25:27,015 [http.get:73]:GET https://lutris.net/api/games/service/steam
DEBUG    2020-12-04 15:25:29,103 [steam.load:115]:53 Steam games loaded

(lutris:28471): Gtk-CRITICAL **: 15:25:29.114: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:44: Warning: unable to set property 'pixbuf' of type 'GdkPixbuf' from value of type '(null)'
  return Gio.Application.run(self, *args, **kwargs)

(lutris:28471): Gtk-CRITICAL **: 15:25:29.114: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:28471): Gtk-CRITICAL **: 15:25:29.114: gtk_list_store_get_path: assertion 'iter->stamp == priv->stamp' failed

(lutris:28471): Gtk-CRITICAL **: 15:25:29.114: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:28471): Gtk-WARNING **: 15:25:29.115: lutris+gui+views+grid+GameGridView 0x2448820 reported min size 202 and natural size 6 in get_preferred_width(); natural size must be >= min size
[1]    28471 segmentation fault  lutris -d
```

**Comment by SwimmingTiger** [comment]
Another crash without renaming lutris database dirs.

Switch to the Steam game list before refreshing. Lutris crashes after refreshing once (unable to reproduce 100%).

```
➜  ~ lutris -d
/usr/lib/python3/dist-packages/gi/overrides/Gdk.py:461: Warning: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
  initialized, argv = Gdk.init_check(sys.argv)
2020-12-04 15:30:18,270: Initializing lutris
2020-12-04 15:30:19,965: Runtime up-to-date. Initialization complete.
INFO     2020-12-04 15:30:19,974 [application.do_command_line:314]:Lutris 0.5.8.1
INFO     2020-12-04 15:30:19,974 [startup.check_driver:61]:Running X.Org Mesa driver 19.2.6 on AMD RENOIR (DRM 3.38.0, 5.8.13-050813-generic, LLVM 7.0.1) (0x1636)
INFO     2020-12-04 15:30:19,975 [startup.check_driver:69]:GPU: 1002:1636 1043:1E21 (amdgpu drivers)
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/hu60/.config/MangoHud/python3.7.conf [ not found ]
parsing config: /home/hu60/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Failed to initialize CPU power data
DEBUG    2020-12-04 15:30:23,428 [base.wipe_game_cache:44]:Deleting games from service-games for steam
DEBUG    2020-12-04 15:30:25,114 [http.get:73]:GET https://lutris.net/api/games/service/steam
DEBUG    2020-12-04 15:30:26,482 [steam.load:115]:53 Steam games loaded

(lutris:30548): Gtk-CRITICAL **: 15:30:26.491: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:44: Warning: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:44: Warning: unable to set property 'markup' of type 'gchararray' from value of type '(null)'
  return Gio.Application.run(self, *args, **kwargs)
free(): invalid pointer
[1]    30548 abort      lutris -d
```
