### ISSUE TITLE
TypeError when parsing game playtime, installed games don't show in Library

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#3353]
**Describe the bug**

Starting Lutris 0.5.8.1 after a few months of not using it, I get this error in the terminal whenever I try to access a tab where there should be content I installed in the past (Games, Recent, Wine).

Those tabs also don't show any content, which is likely due to that error.

My installed games are Epic Game Store and Age of Empires

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/widgets/game_bar.py", line 233, in on_game_state_changed
    self.update_view()
  File "/usr/lib/python3.8/site-packages/lutris/gui/widgets/game_bar.py", line 73, in update_view
    self.put(self.get_playtime_label(), x_offset, y_offset)
  File "/usr/lib/python3.8/site-packages/lutris/gui/widgets/game_bar.py", line 140, in get_playtime_label
    playtime_label.set_markup(_("Time played:\n<b>%s</b>") % self.game.formatted_playtime)
  File "/usr/lib/python3.8/site-packages/lutris/game.py", line 160, in formatted_playtime
    return strings.get_formatted_playtime(self.playtime)
  File "/usr/lib/python3.8/site-packages/lutris/util/strings.py", line 124, in get_formatted_playtime
    hours = math.floor(playtime)
TypeError: must be real number, not str
```

I suspect that might be due to outdated saved playtime data which changed format since my last use (my Lutris prefix might be a year old), so I can dig into my files to pinpoint the culprit with some guidance. Still, this should be likely handled in the Lutris code to avoid throwing an exception.

**Steps to reproduce**

- Use my old Lutris prefix
- Run Lutris 0.5.8.1 and try to access the Library tab
- See error in terminal

**Lutris debugging output (Optional)**

```
INFO     2020-12-28 10:56:19,718 [application.do_command_line:314]:Lutris 0.5.8.1
INFO     2020-12-28 10:56:19,719 [startup.check_driver:57]:Running Intel Mesa driver 20.3.1 on Mesa Intel(R) HD Graphics 630 (KBL GT2) (0x591b)
INFO     2020-12-28 10:56:19,719 [startup.check_driver:69]:GPU: 1002:694E 103C:83BB (amdgpu drivers)
INFO     2020-12-28 10:56:19,720 [startup.check_driver:69]:GPU: 8086:591B 103C:83BB (i915 drivers)
```

**System information (Optional)**

```
System:    Host: cauldron Kernel: 5.10.3-desktop-1.mga8 x86_64 bits: 64 Desktop: KDE Plasma 5.20.4 Distro: Mageia 8 mga8 
CPU:       Info: Quad Core model: Intel Core i7-8705G bits: 64 type: MT MCP L2 cache: 8 MiB 
           Speed: 1335 MHz min/max: 800/3100 MHz Core speeds (MHz): 1: 1335 2: 1169 3: 1202 4: 1632 5: 1478 6: 1597 7: 1204 
           8: 1135 
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
           Device-2: Advanced Micro Devices [AMD/ATI] Polaris 22 XL [Radeon RX Vega M GL] driver: amdgpu v: kernel 
           Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision FHD Camera type: USB driver: uvcvideo 
           Display: x11 server: Mageia X.org 1.20.10 driver: intel,v4l resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 20.3.1
```

**Comment by akien-mga** [comment]
This patch solves the first error, but there are more:
```diff
diff --git a/lutris/gui/views/store_item.py b/lutris/gui/views/store_item.py
index e83f7764..4530c8f0 100644
--- a/lutris/gui/views/store_item.py
+++ b/lutris/gui/views/store_item.py
@@ -140,7 +140,7 @@ class StoreItem:
         """Playtime duration in hours (textual representation)"""
         try:
             _playtime_text = get_formatted_playtime(self.playtime)
-        except ValueError:
+        except (ValueError, TypeError):
             logger.warning("Invalid playtime value %s for %s", self.playtime, self)
             _playtime_text = ""  # Do not show erroneous values
         return gtk_safe(_playtime_text)
```

```
WARNING  2020-12-28 11:08:39,823 [store_item.playtime_text:145]:Invalid playtime value 0.04 for Age of Empires I - Gold edition - CD
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 440, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 159, in add_game
    self.store.append(
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1004, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 995, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 902, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 916, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 208, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 257, in set_value
    _gi._gvalue_set(self, py_value)
TypeError: Must be number, not str
```

As seen with the now-printed warning, the culprit is my Age of Empire install which seems to hold invalid values in the PGA? I can attach the `pga.db` if needed.

**Comment by akien-mga** [comment]
Force casting `self.playtime` to `float` seems to fix it, the entry I have in my DB for Age of Empire appears to be `0.04` as a `str`.

```diff
diff --git a/lutris/gui/views/store_item.py b/lutris/gui/views/store_item.py
index e83f7764..73755500 100644
--- a/lutris/gui/views/store_item.py
+++ b/lutris/gui/views/store_item.py
@@ -133,7 +133,8 @@ class StoreItem:
     @property
     def playtime(self):
         """Playtime duration in hours"""
-        return self._game_data.get("playtime") or 0.0
+        _playtime = self._game_data.get("playtime") or 0.0
+        return float(_playtime)
 
     @property
     def playtime_text(self):
```
(The `except` change is then no longer needed as the type is always `float`.)

**Comment by akien-mga** [comment]
It seems worse in the newly released 0.5.8.2:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 445, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 173, in add_game
    game.playtime_text,
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store_item.py", line 142, in playtime_text
    _playtime_text = get_formatted_playtime(self.playtime)
  File "/usr/lib/python3.8/site-packages/lutris/util/strings.py", line 135, in get_formatted_playtime
    minutes = int((playtime - hours) * 60)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 445, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 173, in add_game
    game.playtime_text,
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store_item.py", line 142, in playtime_text
    _playtime_text = get_formatted_playtime(self.playtime)
  File "/usr/lib/python3.8/site-packages/lutris/util/strings.py", line 135, in get_formatted_playtime
    minutes = int((playtime - hours) * 60)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by akien-mga** [comment]
It's still the same issue, `playtime` is a `str` in my DB, I think it would be better to sanitize it earlier on (when getting the value from the DB) and not in the String utils for pretty printing.

**Comment by akien-mga** [comment]
I'm not sure how to actual run tests but I suggest adding one for this situation if you want `get_formatted_playtime` not to fail on strings:
```diff
diff --git a/tests/test_utils.py b/tests/test_utils.py
index f4e74d2b..80547de1 100644
--- a/tests/test_utils.py
+++ b/tests/test_utils.py
@@ -86,6 +86,7 @@ class TestStringUtils(TestCase):
 
     def test_get_formatted_playtime(self):
         self.assertEqual(strings.get_formatted_playtime(None), strings.NO_PLAYTIME)
+        self.assertEqual(strings.get_formatted_playtime('1.04'), strings.NO_PLAYTIME)
         self.assertEqual(strings.get_formatted_playtime(1.0), "1 hour")
         self.assertEqual(strings.get_formatted_playtime(2.0), "2 hours")
         self.assertEqual(strings.get_formatted_playtime(0.5), "30 minutes")
```

**Comment by strycore** [comment]
I added the test and it returns "1 hour and 2 minutes" as it should.

**Comment by akien-mga** [comment]
Sadly, still more issues with the same entry...
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 445, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 157, in add_game
    self.store.append(
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1004, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 995, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 902, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 916, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 208, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 257, in set_value
    _gi._gvalue_set(self, py_value)
TypeError: Must be number, not str
```

**Comment by strycore** [comment]
It would be a lot easier for me to tackle this issue by knowing what kind of corrupted data you have stored in your database.
I'm kinda working blindly because I have no such invalid data.

**Comment by akien-mga** [comment]
Yes I mentioned this but was waiting for a confirmation of what data you'd need exactly.

> As seen with the now-printed warning, the culprit is my Age of Empire install which seems to hold invalid values in the PGA? I can attach the `pga.db` if needed.

[pga.db.gz](https://github.com/lutris/lutris/files/5823246/pga.db.gz)

**Comment by strycore** [comment]
Should be ok now
