### ISSUE TITLE
Stuck on Lutris is starting

### ISSUE THREAD

**Issue by CertainSomeone** [lutris/lutris#3369]
Hello!

I'm using a fresh install of 64bit Pop!_Os 20.10. I installed Lutris out of the Pop!_Shop and the program is stuck displaying a single message window, saying "Lutris is starting." Once I close it, however, Lutris starts up. Here is the output of the lutris -d command:
lutris -d
2021-01-22 18:18:36,760: Initializing lutris
2021-01-22 18:18:44,304: Runtime p7zip is not available locally
2021-01-22 18:18:44,309: Runtime dumbxinputemu is not available locally
2021-01-22 18:18:44,324: Runtime steam is not available locally
2021-01-22 18:18:44,386: Runtime lib64 is not available locally
2021-01-22 18:18:44,396: Runtime lib32 is not available locally
2021-01-22 18:18:49,966: Non existent path: /home/smeshk/.local/share/lutris/runtime/dumbxinputemu
2021-01-22 18:18:51,869: Non existent path: /home/smeshk/.local/share/lutris/runtime/p7zip
2021-01-22 18:19:41,459: Non existent path: /home/smeshk/.local/share/lutris/runtime/steam
2021-01-22 18:19:45,183: Extraction failed: Compressed file ended before the end-of-stream marker was reached
2021-01-22 18:19:45,184: Error while completing task <function extract_archive at 0x7f616a756ca0>: Compressed file ended before the end-of-stream marker was reached
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 135, in extract_archive
    raise ExtractFailure(str(ex))
2021-01-22 18:19:45,187: Runtime update failed
2021-01-22 18:19:45,188: Compressed file ended before the end-of-stream marker was reached
2021-01-22 18:20:26,654: Non existent path: /home/smeshk/.local/share/lutris/runtime/lib64
^CTraceback (most recent call last):
  File "/usr/games/lutris", line 56, in <module>
    app = Application()  # pylint: disable=invalid-name
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 73, in __init__
    init_dialog.run()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 580, in run
    return Gtk.Dialog.run(self, *args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)

**Comment by strycore** [comment]
You're not supposed to close the windows that says Lutris is starting, why in the name of all is unholy would you even do such thing??

**Comment by strycore** [comment]
I removed the close button from the init dialog so if there is a problem within that initialization process, it will have to be reported as such and not as a crash caused by an unintended behavior.

**Comment by EneHacheCe** [comment]
I'm saying this just for @CertainSomeone not to feel so alone: I had no close button and still closed the init dialog with pkill xD Don't be mad @strycore and thank you very much for your work. I removed the .tars in the runtime folder that failed to download, restarted lutris, and I think I'm back on track.

**Comment by strycore** [comment]
There's likely some failing scenario where the runtime downloads fails and gets stuck, needing to get rid of some corrupt archives.

**Comment by strycore** [comment]
Should be able to repro this by messing with the download process. I'll give this a try.

**Comment by jsmurray2** [comment]
Having the same issue! Running in PopOS 20.10, lutris -d returns:

2021-02-12 15:48:24,951: Initializing lutris
2021-02-12 15:48:25,683: Runtime p7zip is not available locally
2021-02-12 15:48:25,685: Runtime x360ce is not available locally
2021-02-12 15:48:25,686: Runtime dumbxinputemu is not available locally
2021-02-12 15:48:25,687: Runtime gamecontrollerdb is not available locally
2021-02-12 15:48:25,688: Runtime steam is not available locally
2021-02-12 15:48:25,688: Runtime lib64 is not available locally
2021-02-12 15:48:25,689: Runtime lib32 is not available locally
2021-02-12 15:48:25,778: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fbf28153eb0>>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
2021-02-12 15:48:25,779: Download failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-02-12 15:48:25,780: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fbf2815daf0>>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
2021-02-12 15:48:25,780: Download failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-02-12 15:48:25,784: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fbf28211eb0>>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
2021-02-12 15:48:25,784: Download failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-02-12 15:48:25,786: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fbf283fbfd0>>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
2021-02-12 15:48:25,786: Download failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-02-12 15:48:25,789: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fbf282110d0>>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
2021-02-12 15:48:25,790: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fbf28166b20>>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
2021-02-12 15:48:25,790: Download failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
2021-02-12 15:48:25,791: Download failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-02-12 15:48:25,791: Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7fbf28159c40>>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 117, in async_download
    response = requests.get(self.url, headers=headers, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
2021-02-12 15:48:25,791: Download failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by strycore** [comment]
@jsmurray2 is there anything particular on your network or ISP that would cause those network errors?

**Comment by jsmurray2** [comment]
> @jsmurray2 is there anything particular on your network or ISP that would cause those network errors?

Generally I am using a University WiFi network which I know blocks P2P protocols, in case that is the issue I have ran again using a different network, the error I receive now is different but the application still does not work and I am stuck at "Lutris is Starting".

2021-02-13 12:09:46,356: Initializing lutris
2021-02-13 12:09:47,199: Runtime p7zip is not available locally
2021-02-13 12:09:47,200: Runtime x360ce is not available locally
2021-02-13 12:09:47,203: Runtime dumbxinputemu is not available locally
2021-02-13 12:09:47,204: Runtime gamecontrollerdb is not available locally
2021-02-13 12:09:47,204: Runtime steam is not available locally
2021-02-13 12:09:47,205: Runtime lib64 is not available locally
2021-02-13 12:09:47,206: Runtime lib32 is not available locally
2021-02-13 12:09:47,909: Non existent path: /home/jsmurray2/.local/share/lutris/runtime/gamecontrollerdb
2021-02-13 12:09:49,212: Non existent path: /home/jsmurray2/.local/share/lutris/runtime/x360ce
2021-02-13 12:09:49,417: Non existent path: /home/jsmurray2/.local/share/lutris/runtime/dumbxinputemu
2021-02-13 12:09:54,144: Non existent path: /home/jsmurray2/.local/share/lutris/runtime/p7zip
2021-02-13 12:10:18,900: Non existent path: /home/jsmurray2/.local/share/lutris/runtime/lib32
2021-02-13 12:10:30,451: Non existent path: /home/jsmurray2/.local/share/lutris/runtime/lib64
2021-02-13 12:10:30,753: Non existent path: /home/jsmurray2/.local/share/lutris/runtime/steam
2021-02-13 12:10:32,964: Extraction failed: Compressed file ended before the end-of-stream marker was reached
2021-02-13 12:10:32,964: Error while completing task <function extract_archive at 0x7f1b4db76c10>: Compressed file ended before the end-of-stream marker was reached
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 138, in extract_archive
    raise ExtractFailure(str(ex))
2021-02-13 12:10:32,964: Runtime update failed
2021-02-13 12:10:32,965: Compressed file ended before the end-of-stream marker was reached

**Comment by strycore** [comment]
@jsmurray2 yes, you probably have some empty files from the previous attempt. Try deleting /home/jsmurray2/.local/share/lutris/runtime/ then retrying on the non University network.

**Comment by Ahmed-E-86** [comment]
I have the same issue. I deleted all Lutris folders, and launched it again, and it does not launch.

```
2021-02-25 00:03:32,695: Non existent path: /home/ahmed/.local/share/lutris/runtime/gamecontrollerdb
2021-02-25 00:03:35,909: Non existent path: /home/ahmed/.local/share/lutris/runtime/x360ce
2021-02-25 00:03:36,214: Non existent path: /home/ahmed/.local/share/lutris/runtime/dumbxinputemu
2021-02-25 00:03:43,351: Non existent path: /home/ahmed/.local/share/lutris/runtime/p7zip
2021-02-25 00:03:54,306: Non existent path: /home/ahmed/.local/share/lutris/runtime/Ubuntu-18.04-x86_64
2021-02-25 00:08:57,382: Non existent path: /home/ahmed/.local/share/lutris/runtime/Ubuntu-18.04-i686
2021-02-25 00:16:14,948: Non existent path: /home/ahmed/.local/share/lutris/runtime/lib64
2021-02-25 00:16:18,871: Extraction failed: Compressed file ended before the end-of-stream marker was reached
2021-02-25 00:16:18,871: Error while completing task <function extract_archive at 0x7f2c77cef790>: Compressed file ended before the end-of-stream marker was reached
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 138, in extract_archive
    raise ExtractFailure(str(ex))
2021-02-25 00:16:18,872: Runtime update failed
2021-02-25 00:16:18,872: Compressed file ended before the end-of-stream marker was reached
2021-02-25 00:16:22,778: Non existent path: /home/ahmed/.local/share/lutris/runtime/steam
2021-02-25 00:16:23,481: Non existent path: /home/ahmed/.local/share/lutris/runtime/lib32
2021-02-25 00:16:27,889: Extraction failed: Compressed file ended before the end-of-stream marker was reached
2021-02-25 00:16:27,890: Error while completing task <function extract_archive at 0x7f2c77cef790>: Compressed file ended before the end-of-stream marker was reached
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 138, in extract_archive
    raise ExtractFailure(str(ex))
2021-02-25 00:16:27,890: Runtime update failed
2021-02-25 00:16:27,890: Compressed file ended before the end-of-stream marker was reached
2021-02-25 00:16:28,243: Extraction failed: Compressed file ended before the end-of-stream marker was reached
2021-02-25 00:16:28,244: Error while completing task <function extract_archive at 0x7f2c77cef790>: Compressed file ended before the end-of-stream marker was reached
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 138, in extract_archive
    raise ExtractFailure(str(ex))
2021-02-25 00:16:28,244: Runtime update failed
2021-02-25 00:16:28,244: Compressed file ended before the end-of-stream marker was reached
```

**Comment by PeruanoLhama** [comment]
i'm also having this same problem. i tested on pop-os, manjaro kde, kubuntu and fedora. all are having this same problem.
no solution action worked

**Comment by TheZoooZ** [comment]
I'm also having similar problem. Running on Manjaro
`2021-03-05 14:59:04,596: Loading of DXVK versions failed, defaulting to locally available versions
2021-03-05 14:59:04,612: Loading of DXVK versions failed, defaulting to locally available versions
2021-03-05 14:59:04,762: Initializing lutris
2021-03-05 14:59:04,765: Loading of DXVK versions failed, defaulting to locally available versions
2021-03-05 14:59:04,786: Loading of DXVK versions failed, defaulting to locally available versions
2021-03-05 14:59:07,282: Runtime Ubuntu-18.04-i686 is not available locally
2021-03-05 14:59:07,287: Runtime Ubuntu-18.04-x86_64 is not available locally
2021-03-05 14:59:07,296: Runtime steam is not available locally
2021-03-05 14:59:07,300: Runtime lib64 is not available locally
2021-03-05 14:59:07,305: Runtime lib32 is not available locally
`

**Comment by DJLevel3** [comment]
Also on a school network, and also getting the problems on Ubuntu 20.10. I'll try again at home, but it looks like it can't find any local libraries.

**Comment by strycore** [comment]
The patch should prevent the dialog from getting as it notifies the updater it has finished, even in cases of failures.
