### ISSUE TITLE
The 'PyGObject' distribution was not found and is required by lutris

### ISSUE THREAD

**Issue by sucrecacao** [lutris/lutris#3383]
**Describe the bug**
Lutris doesn't work after following the debian install instruction

**Steps to reproduce**

- follow the step to install on debian
- run `lutris`

**Lutris debugging output (Optional)**
```
Traceback (most recent call last):
  File "/usr/local/bin/lutris", line 4, in <module>
    __import__('pkg_resources').run_script('lutris==0.5.8.3', 'lutris')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyGObject' distribution was not found and is required by lutris
```

**Comment by sucrecacao** [comment]
Fixed after installing wine

**Comment by strycore** [comment]
![wat](https://ih1.redbubble.net/image.708418323.9485/flat,1000x1000,075,f.u2.jpg)

**Comment by strycore** [comment]
![how the fuck](https://memegenerator.net/img/instances/24500782/how-the-fuck.jpg)
