### ISSUE TITLE
cannot launch lutris

### ISSUE THREAD

**Issue by wsamh** [lutris/lutris#3389]
I'm on the latest version on Pop OS 20.04

sammy@pop-os:~$ lutris
Traceback (most recent call last):
  File "/usr/games/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 56, in version
    return self.versions[0]
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 65, in load_dxvk_versions
    with open(versions_path, "r") as dxvk_version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sammy/.local/share/lutris/runtime/dxvk/dxvk_versions.json'

**Comment by teletrail** [comment]
similar error here: 

`Original exception was:
Traceback (most recent call last):
  File "/usr/games/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 56, in version
    return self.versions[0]
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 65, in load_dxvk_versions
    with open(versions_path, "r") as dxvk_version_file:
`

dvxk is installed.

**Comment by tmzhuang** [comment]
Lutris launches for me but I do see a similar python error:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 377, in on_game_start
    self.running_row.show()
AttributeError: 'NoneType' object has no attribute 'show'

**Comment by strycore** [comment]
your client is outdated
