### ISSUE TITLE
start-up KeyError

### ISSUE THREAD

**Issue by flo-abgrund** [lutris/lutris#3393]
Hi everyone,
I have encountered this error when trying to launch Lutris on my Ubuntu 20.10. Couldn't find any other solution yet. 

Here is the output:

```Traceback (most recent call last):
  File "/usr/games/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 56, in version
    return self.versions[0]
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 66, in load_dxvk_versions
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 66, in <listcomp>
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
KeyError: 'tag_name'```

**Comment by strycore** [comment]
delete the ~/.local/share/lutris/runtime/dxvk/ folder and lutris will start again if you have the latest update installed.

I'll write a patch to handle this kind of failure.

**Comment by flo-abgrund** [comment]
This just leads to the following:
```FileNotFoundError: [Errno 2] No such file or directory: '~/.local/share/lutris/runtime/dxvk/dxvk_versions.json'```

**Comment by miro-janosik** [comment]
I had the same problem with 5.8.3 on Ubuntu after system upgrade.

I guess it is incorrect json file in the 'cache' which was not updated during upgrade, so what I had to do is:

sudo apt remove lutris
rm -rf .local/share/lutris/
sudo apt install lutris

Before I thought that purge would help, but it didn't:
sudo apt purge lutris
