### ISSUE TITLE
Unable to Launch Lutris

### ISSUE THREAD

**Issue by anthonywork247** [lutris/lutris#3394]
**Describe the bug**

I did a clean install of Lutris

Traceback (most recent call last):
  File "/usr/games/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 56, in version
    return self.versions[0]
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 65, in load_dxvk_versions
    with open(versions_path, "r") as dxvk_version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anthony/.local/share/lutris/runtime/dxvk/dxvk_versions.json'

**Comment by strycore** [comment]
your version of lutris is out of date, please install 0.5.8.3

**Comment by HeyyItsBran** [comment]
> your version of lutris is out of date, please install 0.5.8.3

Looks like the launchpad repo is still pushing 0.5.8.2, any eta when it will be updated?

**Comment by strycore** [comment]
Yes, the PPA still needs to be updated. 

@muzena what's the easiest way to ping you about new lutris updates?

**Comment by anthonywork247** [comment]
I DuckDuckDuckGo the answer regarding version.

Open Lutris [Burger Menu] top left > Click on [Manage Runners] > scroll down to [WINE] > click on the box icon Wrench [manage version] > download your preferred version Look for lutris-6.0, it might not be on top.

After downloading the latest version select the gear icon [setting] this will give you a further range Runner and System Options

**Comment by strycore** [comment]
@anthonywork247 that's the procedure to get the wine build and you shouldn't even have to do that as the latest stable wine build is installed any time you installed a wine game.
To update the client while you wait for the Lutris PPA to be updated, you can grab the deb from here and install it manually: https://launchpad.net/ubuntu/+source/lutris/0.5.8.3-1/+build/20924560/+files/lutris_0.5.8.3-1_all.deb

**Comment by muzena** [comment]
PPA updated.

**Comment by strycore** [comment]
Thanks!
