### ISSUE TITLE
Cannot run lutris

### ISSUE THREAD

**Issue by Kameron97** [lutris/lutris#3403]
Hello! When i try to run Lutri i get the following message...

lutris
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 56, in version
    if self.versions:
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 69, in load_dxvk_versions
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 69, in <listcomp>
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
KeyError: 'tag_name'

not sure if its related to my python version or wine... Any help is appreiciated!

**Comment by strycore** [comment]
Make sure you are running the latest version of lutris (0.5.8.3) and if you are, delete the ~/.local/share/lutris/runners/dxvk folder. That should fix the issue.

**Comment by strycore** [comment]
I've added a patch that deletes invalid DXVK version files.
