### ISSUE TITLE
Segmentation fault when refreshing game list (v 0.5.8.3)

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#3429]
Refreshing GOG game list (while GOG is selected in the sidebar) results in a segmentation fault in libgtk:

```
#0  0x00007f900952dcee in gtk_tree_view_get_row_height (
    node=0x2e40e90, tree_view=0x2930be0)
    at ../../../../gtk/gtktreeview.c:13836
#1  gtk_tree_view_top_row_to_dy (
    tree_view=tree_view@entry=0x2930be0)
    at ../../../../gtk/gtktreeview.c:7313
#2  0x00007f900952dee5 in scroll_sync_handler (
    tree_view=0x2930be0)
    at ../../../../gtk/gtktreeview.c:7201
#3  0x00007f900bdd6fbd in gdk_threads_dispatch (
    data=0x2647720) at ../../../../gdk/gdk.c:769
#4  0x00007f900cf443df in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f900cf44788 in ?? ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f900cf44853 in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f900ccea54d in g_application_run ()
   from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f900d393249 in ?? ()
   from /lib/x86_64-linux-gnu/libffi.so.8
#9  0x00007f900d392629 in ?? ()
   from /lib/x86_64-linux-gnu/libffi.so.8
#10 0x00007f900d04cf25 in ?? ()
   from /usr/lib/python3/dist-packages/gi/_gi.cpython-38-x86_64-linux-gnu.so
#11 0x00007f900d043a8c in ?? ()
   from /usr/lib/python3/dist-packages/gi/_gi.cpython-38-x86_64-linux-gnu.so
#12 0x0000000000534f95 in PyObject_Call ()
#13 0x000000000050ac37 in _PyEval_EvalFrameDefault ()
#14 0x0000000000507965 in _PyEval_EvalCodeWithName ()
#15 0x000000000051e98a in _PyFunction_Vectorcall ()
#16 0x0000000000509571 in _PyEval_EvalFrameDefault ()
#17 0x0000000000507965 in _PyEval_EvalCodeWithName ()
#18 0x00000000005d3087 in PyEval_EvalCode ()
#19 0x00000000005f1bb5 in ?? ()
#20 0x00000000005ecfd3 in ?? ()
#21 0x00000000005f5bab in PyRun_FileExFlags ()
#22 0x00000000005f5644 in PyRun_SimpleFileExFlags ()
#23 0x00000000005ea3d9 in Py_RunMain ()
#24 0x00000000005c802d in Py_BytesMain ()
#25 0x00007f900e5bfcb2 in __libc_start_main (
    main=0x5c7ff0 <main>, argc=2, argv=0x7ffe8e7c6138, 
    init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe8e7c6128)
    at ../csu/libc-start.c:314
#26 0x00000000005c7f2e in _start ()
```

Debug output:

```
DEBUG    2021-02-14 22:08:52,410 [http.get:73]:GET https://embed.gog.com/userData.json
DEBUG    2021-02-14 22:08:52,806 [base.wipe_game_cache:155]:Wiping gog cache
DEBUG    2021-02-14 22:08:52,811 [base.wipe_game_cache:44]:Deleting games from service-games for gog
DEBUG    2021-02-14 22:08:52,821 [http.get:73]:GET https://embed.gog.com/userData.json
DEBUG    2021-02-14 22:08:53,014 [http.get:73]:GET https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=1
WARNING  2021-02-14 22:08:53,633 [http.get:92]:Failed to read response's content length
DEBUG    2021-02-14 22:08:53,691 [http.get:73]:GET https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=2
WARNING  2021-02-14 22:08:54,013 [http.get:92]:Failed to read response's content length
DEBUG    2021-02-14 22:08:54,952 [http.get:73]:GET https://lutris.net/api/games/service/gog
Segmenteringsfel (minnesutskrift skapad)
```

I can recreate it if you need more context.

**Comment by strycore** [comment]
Closed in 0.5.9
The whole service reloading + icon downloading is now done in the same thread and the UI only refreshes when everything is finished
