### ISSUE TITLE
today's git: Lutris can not launch

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3440]
Hello, Lutris git version from today (23 february 2021) does not launch, I obtain this error message:

```
Traceback (most recent call last):
  File "./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/legluondunet/Téléchargements/lutris/lutris/gui/application.py", line 35, in <module>
    from lutris import settings
  File "/home/legluondunet/Téléchargements/lutris/lutris/settings.py", line 9, in <module>
    from lutris.util.settings import SettingsIO
ModuleNotFoundError: No module named 'lutris.util.settings'
```

**Comment by legluondunet** [comment]
I erased my git folder and clone it again, I can not reproduce this issue.
