### ISSUE TITLE
The new lutris.util.dolphin package does not get installed, (Setup.py?)

### ISSUE THREAD

**Issue by aTosser** [lutris/lutris#3470]
```
$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 43, in <module>
    from lutris.gui.installerwindow import InstallerWindow
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 17, in <module>
    from lutris.installer import interpreter
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/usr/lib/python3.8/site-packages/lutris/installer/installer.py", line 16, in <module>
    from lutris.services import get_services
  File "/usr/lib/python3.8/site-packages/lutris/services/__init__.py", line 4, in <module>
    from lutris.services.dolphin import DolphinService
  File "/usr/lib/python3.8/site-packages/lutris/services/dolphin.py", line 9, in <module>
    from lutris.util.dolphin.cache_reader import DOLPHIN_GAME_CACHE_FILE, DolphinCacheReader
ModuleNotFoundError: No module named 'lutris.util.dolphin.cache_reader'; 'lutris.util.dolphin' is not a package
```
Missing Directory:
```
$ ls /usr/lib/python3.8/site-packages/lutris/util
audio.py       fileio.py            joypad.py           __pycache__     timer.py
cookies.py     gamecontrollerdb.py  keyring.py          resources.py    urlhandler.py
datapath.py    game_finder.py       libretro.py         settings.py     wine
disks.py       graphics             linux.py            shell.py        xdgshortcuts.py
display.py     http.py              log.py              steam           yaml.py
dolphin.py     i18n.py              mame                strings.py
downloader.py  __init__.py          process.py          system.py
extract.py     jobs.py              process_watcher.py  test_config.py
```

I think adding `lutris.util.dolphin` to Setup.py  packages list should fix it.

**Comment by aTosser** [comment]
Fixed by #3468.
