### ISSUE TITLE
Unable to add PPA

### ISSUE THREAD

**Issue by shag00** [lutris/lutris#3474]
Have tried with 2 PCs, both new installs of Kubuntu 20.10 and am unable to add the Lutris repository as per:
sudo add-apt-repository ppa:lutris-team/lutris on [https://lutris.net/downloads/](url) or various other methods.

On execution it just hangs and after Ctrl-C it sometimesd says the server cannot be found.

`anj@anjpc:~$ sudo add-apt-repository ppa:lutris-team/lutris
[sudo] password for anj: 
^CTraceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 331, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 314, in main
    shortcut = handler(source, **shortcut_params)
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 67, in __init__
    if self.lpppa.publish_debug_symbols:
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 94, in lpteam
    self._lpteam = self.lp.people(self.teamname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 85, in lp
    self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 400, in login_anonymously
    return cls(credentials, None, None, service_root=service_root,
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 209, in __init__
    super(Launchpad, self).__init__(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 485, in __init__
    self._wadl = self._browser.get_wadl_application(self._root_uri)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 456, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 398, in _request
    response, content = self._request_and_retry(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 368, in _request_and_retry
    response, content = self._connection.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1985, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 137, in _request
    response, content = super(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 193, in _request
    return super(RestfulHttp, self)._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1650, in _request
    (response, content) = self._conn_request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1557, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1324, in connect
    sock.connect((self.host, self.port))
KeyboardInterrupt
`

**Comment by shag00** [comment]
Seems it's a Kubuntu issue, typing:
`sudo apt install apt-transport-https`
in a terminal fixes the problem.
