### ISSUE TITLE
Fallout New Vegas Installer Broken

### ISSUE THREAD

**Issue by gnollhide** [lutris/lutris#3478]
Hi! I was trying to get Fallout New Vegas to install using the lutris installer, but every time I try it failes at "Please review the files needed for the installation and click 'Continue'" and does not show any files. This happens both from the lutris installer button on the web page, and trying to install from the lutris client itself. Running in terminal brings up the following error.
`2021-03-20 18:19:25,124: Getting game details for 1312824873
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 304, in on_runners_ready
    self.show_installer_files_screen()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 310, in show_installer_files_screen
    installer_files_box = InstallerFilesBox(self.interpreter.installer, self)
  File "/usr/lib/python3/dist-packages/lutris/gui/installer/files_box.py", line 27, in __init__
    installer_file_box = InstallerFileBox(installer_file)
  File "/usr/lib/python3/dist-packages/lutris/gui/installer/file_box.py", line 29, in __init__
    self.cache_to_pga = self.installer_file.uses_pga_cache()
`
It's worth noting that it doesn't seem to apply to the installer for Fallout 3, as that one installs just fine.

**Comment by gnollhide** [comment]
Oh my apologies I missed a bit, this is the final popup before closing out the box normally.
`AttributeError: 'str' object has no attribute 'uses_pga_cache'`

**Comment by briaguya-ai** [comment]
looks like there might actually be a bug in there

questions about environment:
* which installer are you using? there are 4 listed on the [game page](https://lutris.net/games/fallout-new-vegas/)
  * this will help with debugging if there's a bug 
* if it's the GOG installer or something similar, have you tried installing it by manually adding a new game? Just click the big plus button and select wine (assuming you have a wine runner installed) and in "Game options" select the installer as the executable.
  * if that's working but the script isn't, that looks more like a bug.
* if it's steam, does the steamplay install work?

suggested tags:
game specific
installer
not enough detail

#### additional reading
here's a [reddit post](https://www.reddit.com/r/linux_gaming/comments/jcz0sk/heavily_modded_fallout_new_vegas_in_linux_using/) by someone who had it running with a bunch of mods 5 months ago.

**Comment by gnollhide** [comment]
I'm using the GOG Wine installer on the game page. It does the same when added from the GOG games list.
Using wine as a runner and manually installing seems to work fine, however it does not automatically install all the other "goodies" like NVSE like the GOG installer did.
I do not have the steam version and cannot test the steamplay results, I hope someone could help with that.

**Comment by briaguya-ai** [comment]
just to confirm, you've manually downloaded the installer from gog.com? [the script](https://lutris.net/games/install/8872/view) is looking for `setup_fallout_new_vegas_1.4.0.525_(12010).exe`, as well as 2 .bin files.

I just tested the script out and it worked flawlessly for me (running Debian bullseye/sid, GNOME 3.38.4, Wayland,  Lutris 0.5.8.3)

more details about your environment could help sort this out

**Comment by Kjir** [comment]
I've run into the same problem while trying to install Planescape: Torment Enhanced Edition from GOG:

```
2021-04-30 22:49:18,454: Couldn't find a terminal emulator.
2021-04-30 22:49:18,488: Your version of python-magic is too old.
2021-04-30 22:49:18,542: Initializing lutris
2021-04-30 22:49:18,992: Downloading DXVK releases to /home/sb/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-04-30 22:49:18,994: Runtime updated. Initialization complete.
INFO     2021-04-30 22:49:18,995 [application.do_command_line:315]:Lutris 0.5.8.3
INFO     2021-04-30 22:49:18,995 [startup.check_driver:57]:Running AMD Mesa driver 21.0.3 on AMD Radeon RX 5600 XT (NAVI10, DRM 3.40.0, 5.11.16-arch1-1, LLVM 11.1.0) (0x731f)
INFO     2021-04-30 22:49:18,995 [startup.check_driver:69]:GPU: 1002:731F 1458:231C (amdgpu drivers)
DEBUG    2021-04-30 22:49:36,069 [http.get:73]:GET https://lutris.net/api/games?search=planescape
DEBUG    2021-04-30 22:49:38,720 [__init__.fetch_script:22]:Fetching installer https://lutris.net/api/installers/planescape-torment-enhanced-edition
DEBUG    2021-04-30 22:49:38,720 [http.get:73]:GET https://lutris.net/api/installers/planescape-torment-enhanced-edition
DEBUG    2021-04-30 22:49:41,099 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2021-04-30 22:49:42,199 [http.get:73]:GET https://embed.gog.com/userData.json
INFO     2021-04-30 22:49:42,444 [gog.get_game_details:278]:Getting game details for 1203613131
DEBUG    2021-04-30 22:49:42,445 [http.get:73]:GET https://api.gog.com/products/1203613131?expand=downloads
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 304, in on_runners_ready
    self.show_installer_files_screen()
  File "/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 310, in show_installer_files_screen
    installer_files_box = InstallerFilesBox(self.interpreter.installer, self)
  File "/usr/lib/python3.9/site-packages/lutris/gui/installer/files_box.py", line 27, in __init__
    installer_file_box = InstallerFileBox(installer_file)
  File "/usr/lib/python3.9/site-packages/lutris/gui/installer/file_box.py", line 29, in __init__
    self.cache_to_pga = self.installer_file.uses_pga_cache()
AttributeError: 'str' object has no attribute 'uses_pga_cache'
DEBUG    2021-04-30 22:49:42,638 [interpreter.create_game_folder:177]:Creating destination path /home/sb/Games/planescape-torment-enhanced-edition

```

I'm on Arch Linux, installed from zero in the last month or so.

**Comment by jrobio** [comment]
Ran into the same issue downloading and attempting to edit the installer for Pathologic Classic HD
```
2021-07-15 20:07:27,913: Initializing lutris
2021-07-15 20:07:28,462: Downloading DXVK releases to /home/rob/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-07-15 20:07:28,859: Writing to /home/rob/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-07-15 20:07:28,860: Runtime updated. Initialization complete.
2021-07-15 20:07:28,861: Lutris 0.5.8.4
2021-07-15 20:07:28,861: Using NVIDIA drivers 465.31 for x86_64
2021-07-15 20:07:28,861: GPU: NVIDIA GeForce GTX 1070 Ti
2021-07-15 20:07:28,861: GPU: 10DE:1B82 19DA:2435 (nvidia drivers)
2021-07-15 20:07:57,671: Getting runner information for wine
2021-07-15 20:07:59,313: Getting game details for 1445852217
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 304, in on_runners_ready
    self.show_installer_files_screen()
  File "/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 310, in show_installer_files_screen
    installer_files_box = InstallerFilesBox(self.interpreter.installer, self)
  File "/usr/lib/python3.9/site-packages/lutris/gui/installer/files_box.py", line 27, in __init__
    installer_file_box = InstallerFileBox(installer_file)
  File "/usr/lib/python3.9/site-packages/lutris/gui/installer/file_box.py", line 29, in __init__
    self.cache_to_pga = self.installer_file.uses_pga_cache()
AttributeError: 'str' object has no attribute 'uses_pga_cache'
```
result of `uname -a`:
```
Linux caliban 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux
```
result of `lsb_release -a`:
```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

**Comment by strycore** [comment]
fixed
