### ISSUE TITLE
Failed to kill game process: [Errno 3] No such process

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3492]
Was playing some CD32 game when Lutris failed to show up after exiting the game. Tried stopping the game from within Lutris when I found this on the terminal: 

```
UAE: Stopping
Monitored process exited.
Killing PID 9694 with SIGKILL
All monitored processes have exited.
No return code
DEBUG    2021-04-03 01:18:21,607 [command.on_stop:193]:Process 9692 has terminated with code 0
DEBUG    2021-04-03 01:19:00,856 [game.force_stop:521]:Failed to kill game process: [Errno 3] No such process
Traceback (most recent call last):
  File "~/src/lutris/lutris/game_actions.py", line 144, in on_game_stop
    game.force_stop()
  File "~/src/lutris/lutris/game.py", line 519, in force_stop
    os.kill(int(pid), signal.SIGTERM)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by telanus** [comment]
Happens especially when emulating a CD32 doesn't happen with other Emu settings. But it's such a corner case that I'm of the opinion that it can be ignored for now, as I doubt many Lutris users are into using Lutris as front-end for FS-UAE.
