### ISSUE TITLE
Lutris doesn't launch on ubuntu 20.04.

### ISSUE THREAD

**Issue by isthereavailableusername** [lutris/lutris#3572]
When i click the icon nothing happens, even on process monitor. I tried using commands I found in the internet but they don't work. Reinstalling or restarting computer also doesn't work.
2021-06-14 22:25:45,418: The Retroarch config in <DirEntry 'core_info.cache'> could not be read because of character encoding issues
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/init.py", line 79, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/usr/lib/python3/dist-packages/lutris/runners/init.py", line 71, in get_runner_module
    return import("lutris.runners.%s" % runner_name, globals(), locals(), [runner_name], 0)
  File "/usr/lib/python3/dist-packages/lutris/runners/libretro.py", line 47, in <module>
    if "categories" in core_config.keys() and "Emulator" in core_config["categories"]:
  File "/usr/lib/python3/dist-packages/lutris/util/libretro.py", line 80, in keys
    return list([key for (key, _value) in self.config])
TypeError: 'NoneType' object is not iterable
Help.

**Comment by FOSSilizedDaemon** [comment]
@isthereavailableusername Can you open a terminal and post the out of this command
```
lutris -d
```

**Comment by QEDeD** [comment]
Not OP, but on PopOS 21.04:

```
➜  ~ lutris -d

2021-08-14 09:37:25,377: The Retroarch config in <DirEntry 'core_info.cache'> could not be read because of character encoding issues
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 79, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 71, in get_runner_module
    return __import__("lutris.runners.%s" % runner_name, globals(), locals(), [runner_name], 0)
  File "/usr/lib/python3/dist-packages/lutris/runners/libretro.py", line 47, in <module>
    if "categories" in core_config.keys() and "Emulator" in core_config["categories"]:
  File "/usr/lib/python3/dist-packages/lutris/util/libretro.py", line 80, in keys
    return list([key for (key, _value) in self.config])
TypeError: 'NoneType' object is not iterable
```

**Comment by telanus** [comment]
@QEDeD I had the same problem, check in ~/.local/share/ Lutris/runners/RetroArch/info (or something similar, I'm at work and thus not near my machine) and see if there is any files that don't end in .info. I know that RetroArch creates a file in that directory that cased this error in Lutris. It was fixed in Master, but I'm not sure if that fix made it into a release yet.

**Comment by QEDeD** [comment]
Can confirm it is fixed in master at least :)
