### ISSUE TITLE
fail to start "magic is not available"

### ISSUE THREAD

**Issue by PowaBanga** [lutris/lutris#3604]
Hi everybody,
Since some days, lutris fail to start on my Archlinux (lts, cinnamon) .

When i launch it in a terminal, i have this error message : 
```
lutris
2021-07-21 12:44:52,430: Magic not available. Unable to automatically find game executables. Please install python-magic
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 56, in version
    if self.versions:
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 70, in load_dxvk_versions
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

So in installed python-magic and now i have this error : 
```
lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 56, in version
    if self.versions:
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 70, in load_dxvk_versions
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by PowaBanga** [comment]
Ok, fixed my this command : 
```
rm $HOME/.local/share/lutris/runtime/dxvk/dxvk_versions.json
```
the original file was empty, i really do not know why
