### ISSUE TITLE
lutris démarre pas 

### ISSUE THREAD

**Issue by notoverflow** [lutris/lutris#3610]
lutris ne veux pas démarrer 

(lutris:11150): Gtk-WARNING **: 21:56:35.770: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:11150): Gtk-WARNING **: 21:56:35.770: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:11150): Gtk-WARNING **: 21:56:35.770: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
2021-07-28 21:56:36,182: Starting Lutris 0.5.9
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 211, in do_startup
    init_lutris()
  File "/usr/lib/python3.9/site-packages/lutris/startup.py", line 162, in init_lutris
    runners.RUNNER_NAMES = runners.get_runner_names()
  File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 112, in get_runner_names
    return {
  File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 113, in <dictcomp>
    runner: import_runner(runner)().human_name for runner in __all__
  File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
    "choices": DXVKManager().version_choices,
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
    for version in self.versions:
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
    self._versions = self.load_versions()
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
    versions = [v["tag_name"] for v in json.load(version_file)]
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-07-28 21:56:36,191: Running migration: mess_to_mame
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 330, in do_command_line
    migrate()
  File "/usr/lib/python3.9/site-packages/lutris/migrations/__init__.py", line 29, in migrate
    migration.migrate()
  File "/usr/lib/python3.9/site-packages/lutris/migrations/mess_to_mame.py", line 9, in migrate
    game = Game(pga_game["id"])
  File "/usr/lib/python3.9/site-packages/lutris/game.py", line 85, in __init__
    self.load_config()
  File "/usr/lib/python3.9/site-packages/lutris/game.py", line 205, in load_config
    self.config = LutrisConfig(runner_slug=self.runner_name, game_config_id=self.game_config_id)
  File "/usr/lib/python3.9/site-packages/lutris/config.py", line 101, in __init__
    self.initialize_config()
  File "/usr/lib/python3.9/site-packages/lutris/config.py", line 135, in initialize_config
    self.update_cascaded_config()
  File "/usr/lib/python3.9/site-packages/lutris/config.py", line 142, in update_cascaded_config
    self.system_config.update(self.get_defaults("system"))
  File "/usr/lib/python3.9/site-packages/lutris/config.py", line 228, in get_defaults
    options_dict = self.options_as_dict(options_type)
  File "/usr/lib/python3.9/site-packages/lutris/config.py", line 239, in options_as_dict
    sysoptions.with_runner_overrides(self.runner_slug) if self.runner_slug else sysoptions.system_options
  File "/usr/lib/python3.9/site-packages/lutris/sysoptions.py", line 497, in with_runner_overrides
    runner = runner()
  File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
    "choices": DXVKManager().version_choices,
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
    for version in self.versions:
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
    self._versions = self.load_versions()
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
    versions = [v["tag_name"] for v in json.load(version_file)]
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-07-28 21:56:36,195: Shutting down Lutris

**Comment by KeetKhat** [comment]
We can't help you if you don't tell us what's your distro

**Comment by notoverflow** [comment]
hi, 
Manjaro Linux x86_64 
Kernel: 5.13.5-1-MANJARO

**Comment by KeetKhat** [comment]
Have you installed Lutris from the repos ?

**Comment by notoverflow** [comment]
(et je suis français, donc comme tu l'es aussi on peux parler français)

**Comment by notoverflow** [comment]
i try aur, pacman...

**Comment by KeetKhat** [comment]
> (et je suis français, donc comme tu l'es aussi on peux parler français)

C'est mieux d'écrire en anglais afin que tout le monde puisse comprendre, je peux éventuellement te conseiller de retirer lutris-git (yay -Rs lutris-git), purger son dossier dans "~/.config" et de réinstaller la version présente dans les dépôts de Manjaro (sudo pacman -S lutris)

**Comment by notoverflow** [comment]
purger  ? 
(en suprimant, puis en allant dans /bin 

[notoverflow@notoverflow bin]$ find lutris
find: ‘lutris’: Aucun fichier ou dossier de ce type
donc rien a suprimer)

**Comment by KeetKhat** [comment]
Désinstalle lutris-git

`sudo pacman -Rs lutris-git`

Rends toi dans ton répertoire utilisateur

`cd ~`

Puis dans .config

`cd .config`

Et pour finir, tu pourras effacer le dossier "lutris"

`rm -rf lutris`

Afin de réinstaller la version de Lutris présente dans les dépôts de ta distro

`sudo pacman -S lutris`

Normalement tu n'as rien à faire d'autre, Lutris doit se lancer sans problème

**Comment by notoverflow** [comment]
`
(lutris:149649): Gtk-WARNING **: 00:52:31.356: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:149649): Gtk-WARNING **: 00:52:31.356: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:149649): Gtk-WARNING **: 00:52:31.356: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 56, in version
    if self.versions:
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 70, in load_dxvk_versions
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
ça plante toujours 
mais je peuc le lancer avec un sudo

**Comment by KeetKhat** [comment]
Donc si tu peux le lancer avec sudo le problème ne vient pas de Lutris (Tu peux donc éventuellement fermer l'issue vu que le pb vient de ta config) mais des permissions de ton dossier utilisateur

Vérifie que tu as bien les bonnes permissions dans ton dossier utilisateur.

**Comment by notoverflow** [comment]
des indices sur comment faire si tas une idée ? 
et merci !

**Comment by KeetKhat** [comment]
Les commandes de base du système

ls -l pour lister ce que contient ton répertoire avec l'attribution et les droits
chown pour changer le propriétaire
chmod pour changer les permissions

N'hésite pas à utiliser le manuel (man) en cas de besoin

**Comment by notoverflow** [comment]
merci ! bonne soirée
