### ISSUE TITLE
EGS Service: Unable to install any game

### ISSUE THREAD

**Issue by matty-r** [lutris/lutris#3635]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 495, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3.9/site-packages/lutris/services/egs.py", line 375, in install
    [self.generate_installer(db_game, egs_game)],
  File "/usr/lib/python3.9/site-packages/lutris/services/egs.py", line 339, in generate_installer
    egs_exe = egs_game.config.game_config["exe"]
AttributeError: 'NoneType' object has no attribute 'game_config'

**Comment by strycore** [comment]
This was caused by having EGS present but uninstalled in Lutris, the client now checks if the EGS client is properly installed.
