### ISSUE TITLE
Installing with scripts fails (python errors KeyError: 'appid')

### ISSUE THREAD

**Issue by nzbtuxnews** [lutris/lutris#3642]
Tried to install Sim City 4 on lutris 0.5.8.4 but hit cancel by mistake.

Now trying to install it fails with:

wuser@wcp3:~$ lutris -d
2021-08-04 13:35:24,767: No cores found
Gtk-Message: 13:35:24.958: GtkDialog mapped without a transient parent. This is discouraged.
2021-08-04 13:35:24,959: Initializing lutris
2021-08-04 13:35:25,369: Downloading DXVK releases to /home/wuser/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-08-04 13:35:25,520: Writing to /home/wuser/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-08-04 13:35:25,521: Runtime updated. Initialization complete.
INFO     2021-08-04 13:35:25,522 [application.do_command_line:315]:Lutris 0.5.8.4
INFO     2021-08-04 13:35:25,522 [startup.check_driver:49]:Using NVIDIA drivers 470.57.02 for x86_64
INFO     2021-08-04 13:35:25,523 [startup.check_driver:53]:GPU: NVIDIA GeForce GT 1030
INFO     2021-08-04 13:35:25,523 [startup.check_driver:69]:GPU: 10DE:1D01 1043:85F4 (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 224, in on_install_clicked
    self.service.install(self.db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 117, in install
    appid = db_game["appid"]
KeyError: 'appid'

**System Info (from Lutris)**
[System]
OS:              Linux Mint 19.3 Tricia
Arch:            x86_64
Kernel:          5.4.0-80-generic
Desktop:         XFCE
Display Server:  x11
[CPU]
Vendor:          AuthenticAMD
Model:           AMD Phenom(tm) II X4 965 Processor
Physical cores:  4
Logical cores:   4
[Memory]
RAM:             11.7 GB
Swap:            12.0 GB
[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GT 1030/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.57.02
OpenGL Core:     4.6.0 NVIDIA 470.57.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.57.02
Vulkan:          Supported

**Comment by tannisroot** [comment]
Please try with master

**Comment by nzbtuxnews** [comment]
Different issue with master:  

Traceback (most recent call last):
  File "/home/wuser/lutris/lutris/gui/application.py", line 495, in on_game_install
    game_id = service.install(db_game)
  File "/home/wuser/lutris/lutris/services/base.py", line 186, in install
    appid = db_game["appid"]
TypeError: 'NoneType' object is not subscriptable

**Comment by nzbtuxnews** [comment]
After a system reboot (to increase value for ESYNC), now the installer throws:

2021-08-08 11:18:18,603: No game found. Replacing with placeholder {'id': 'simcity-4-deluxe', 'appid': 'simcity-4-deluxe', 'name': 'SimCity 4 Deluxe Edition', 'slug': 'simcity-4-deluxe', 'service': 'lutris'}
Traceback (most recent call last):
  File "/home/wuser/lutris/lutris/gui/application.py", line 495, in on_game_install
    game_id = service.install(db_game)
  File "/home/wuser/lutris/lutris/services/lutris.py", line 119, in install
    installers = fetch_script(slug)
  File "/home/wuser/lutris/lutris/installer/__init__.py", line 16, in fetch_script
    raise ValueError("No game_slug provided. Can't query an installer")
ValueError: No game_slug provided. Can't query an installer

**Comment by nzbtuxnews** [comment]
Third attempt:  this time I hit "Install" 2 or 3 times and the install dialog box appeared.  I hit browse to pinpoint to the setup.exe on CD1, then entered my key and it crashed with:

Original exception was:
Traceback (most recent call last):
  File "/home/wuser/lutris/lutris/gui/lutriswindow.py", line 788, in on_game_updated
    updated = self.game_store.update(db_game)
  File "/home/wuser/lutris/lutris/gui/views/store.py", line 127, in update
    store_item = StoreItem(db_game, self.service_media)
  File "/home/wuser/lutris/lutris/gui/views/store_item.py", line 21, in __init__
    raise RuntimeError("No game data provided")
RuntimeError: No game data provided

**Comment by nzbtuxnews** [comment]
No longer relevant after a system reformatting.
