### ISSUE TITLE
Error on startup: dxvk_versions.json is empty

### ISSUE THREAD

**Issue by basta** [lutris/lutris#3660]
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3.9/site-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 56, in version
    if self.versions:
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3.9/site-packages/lutris/util/wine/dxvk.py", line 70, in load_dxvk_versions
    dxvk_versions = [v["tag_name"] for v in json.load(dxvk_version_file)]
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I am getting this error on startup in terminal. After some investigation I figured out that dxvk_versions is empty. I recall that lutris crashed yesterday while playing League of Legends and I cannot start it since, but not sure if related.

What steps can I take to fix this? I could fill json with content but I don't know what lutris is expecting.

Specs:
Fedora 34
Python 3.9.6
Latest lutris currently available using dnf (cannot check version due to error)

**Comment by basta** [comment]
Fixed by deleting dxvk folder in runtime and lutris redownloading dxvk.

Not sure whether to close this, because the config file still got deleted and fixing the issue was non-obvious.

**Comment by BaaRamEwe** [comment]
I got a similar error yesterday, where ~/.local/share/lutris/runtime/dxvk/dxvk_versions.json was cut off after about 200 characters.
The problem was also solved by deleting the file, since Lutris would redownload/create a new one on startup if it wasn't present.

There's a few other mentions of this problem at https://forums.lutris.net/t/lutris-wont-run-launch/9280/12
Is it possible to make Lutris do this automatically? Catch that the json file is malformed when reading it, and redownload/recreate it if so? Possibly renaming the erroneous file into a backup first.

**Comment by tannisroot** [comment]
Please retest with master
