### ISSUE TITLE
Game Library doesn't appear, cannot run manually added Wine games

### ISSUE THREAD

**Issue by bayazidbh** [lutris/lutris#3668]
As I have described [here](https://github.com/lutris/lutris/issues/3504#issuecomment-901163212), I have the following issue. I'm sorry if this is a known issue, as I tried going through some issues with the words "library" or "python" in it and the other issue seems to be different from mine.

I am not sure what's causing it, but whenever I run lutris (even if I'm not invoking the GUI) I ran into a bunch of python errors. I am on lutris 0.5.9 (specifically lutris-git 0.5.9.beta1.r31.g2b7ef5dc-1 via chaotic-aur, but I have tested normal AUR as well) and have tried going back to 0.5.8 with the same issue.

I faced no issue prior to doing the monthly Manjaro update, where I believe there was a python update, so it might be that. I would be fine with any kind of fixing that I can do, or if the issue was on my end, as long as I can fix it since I use Lutris to track game length.

I believe the issue seems to specifically be with python and the config files for wine games, as for some reason Wine is absent from the Runner list in preferences while I can still run emulator games from tray icon or terminal.

Below is my original report in issue #3504.

> I'm having similar issues. It resulted in the window being blank:
> 
> ![image](https://user-images.githubusercontent.com/26621899/129912099-5586a3aa-aa71-4491-b448-7d76448f2802.png)
> 
> The tray icon shows the game is still there, and if I pressed Toggle View, it'll show the games:
> 
> ![image](https://user-images.githubusercontent.com/26621899/129912693-d76a3412-05a9-4888-8f6a-92cd91f7cdeb.png)
> 
> However, it doesn't allow me to run any game at all, and you can see that even when it's hovered (or right-clicked) it doesn't even show any options, except for the ones that are from an emulator.
> 
> For these ones I can no longer give screenshots, but I managed to run a game from an emulator, which popped up the Library text on the sidebar. Pressing it make only the game I had running shown on my Library. After exiting, no game appears on the Lutris window even after messing with search, the Toggle View button, or any of the button in the top right dropdown menu.
> 
> That said, tray icon still shows the games, I can still run emulator games from the tray icon, and I can still access Preferences:
> 
> ![image](https://user-images.githubusercontent.com/26621899/129914005-dd04f2c3-c70d-4dd5-a914-af6aa7273b1b.png)
> 
> And I noticed that Wine isn't there. Looking around in ~/.config/lutris, I saw that runners have their own runner-general .yml files while manually added Wine games have their own specific games .yml files, so I'm suspecting that there's something about Wine-specific config that is messing things up.
> 
> Trying to run wine games from terminal yielded some error, while trying to run an emulator game from terminal doesn't start anything but also doesn't run error. Here is a log of some of the things I've tried as well as my own system details:
> 
> ```
> $ python3 --version                                                                                                                                                      ✔ 
> Python 3.9.6
> $ lutris -d                                                                                                                                                              ✔ 
> 2021-08-18 20:57:48,275: Starting Lutris 0.5.9
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 211, in do_startup
>     init_lutris()
>   File "/usr/lib/python3.9/site-packages/lutris/startup.py", line 162, in init_lutris
>     runners.RUNNER_NAMES = runners.get_runner_names()
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 112, in get_runner_names
>     return {
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 113, in <dictcomp>
>     runner: import_runner(runner)().human_name for runner in __all__
>   File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
>     "choices": DXVKManager().version_choices,
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
>     for version in self.versions:
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
>     self._versions = self.load_versions()
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
>     versions = [v["tag_name"] for v in json.load(version_file)]
>   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> INFO     2021-08-18 20:57:48,291 [startup.check_driver:60]:Running AMD Mesa driver 21.1.6 on Radeon RX 570 Series (POLARIS10, DRM 3.41.0, 5.13.11-191-tkg-pds, LLVM 12.0.1) (0x67df)
> INFO     2021-08-18 20:57:48,291 [startup.check_driver:72]:GPU: 1002:67DF 148C:2379 (amdgpu drivers)
> skipping config: /usr/bin/MangoHud.conf [ not found ]
> skipping config: /home/fenglengshun/.config/MangoHud/python3.9.conf [ not found ]
> parsing config: /home/fenglengshun/.config/MangoHud/MangoHud.conf [ ok ]
> MANGOHUD: Connected to D-Bus as ":1.4334".
> WARNING  2021-08-18 20:57:48,623 [libretro.get_libretro_cores:47]:No cores found
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 328, in on_realize
>     runner = runners.import_runner(runner_name)()
>   File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
>     "choices": DXVKManager().version_choices,
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
>     for version in self.versions:
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
>     self._versions = self.load_versions()
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
>     versions = [v["tag_name"] for v in json.load(version_file)]
>   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> DEBUG    2021-08-18 20:57:53,511 [lutriswindow.on_toggle_viewtype:716]:View type changed to list
> DEBUG    2021-08-18 20:57:53,531 [lutriswindow.update_store:451]:Showing 17 games
> DEBUG    2021-08-18 20:57:54,183 [lutriswindow.on_toggle_viewtype:716]:View type changed to grid
> DEBUG    2021-08-18 20:57:54,189 [lutriswindow.update_store:451]:Showing 17 games
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/status_icon.py", line 107, in on_game_selected
>     Game(game_id).launch()
>   File "/usr/lib/python3.9/site-packages/lutris/game.py", line 85, in __init__
>     self.load_config()
>   File "/usr/lib/python3.9/site-packages/lutris/game.py", line 205, in load_config
>     self.config = LutrisConfig(runner_slug=self.runner_name, game_config_id=self.game_config_id)
>   File "/usr/lib/python3.9/site-packages/lutris/config.py", line 101, in __init__
>     self.initialize_config()
>   File "/usr/lib/python3.9/site-packages/lutris/config.py", line 135, in initialize_config
>     self.update_cascaded_config()
>   File "/usr/lib/python3.9/site-packages/lutris/config.py", line 142, in update_cascaded_config
>     self.system_config.update(self.get_defaults("system"))
>   File "/usr/lib/python3.9/site-packages/lutris/config.py", line 228, in get_defaults
>     options_dict = self.options_as_dict(options_type)
>   File "/usr/lib/python3.9/site-packages/lutris/config.py", line 239, in options_as_dict
>     sysoptions.with_runner_overrides(self.runner_slug) if self.runner_slug else sysoptions.system_options
>   File "/usr/lib/python3.9/site-packages/lutris/sysoptions.py", line 501, in with_runner_overrides
>     runner = runner()
>   File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
>     "choices": DXVKManager().version_choices,
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
>     for version in self.versions:
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
>     self._versions = self.load_versions()
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
>     versions = [v["tag_name"] for v in json.load(version_file)]
>   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ^C
> $ lutris -l                                                                                                                                                              ✔ 
> 2021-08-18 20:58:42,934: Starting Lutris 0.5.9
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 211, in do_startup
>     init_lutris()
>   File "/usr/lib/python3.9/site-packages/lutris/startup.py", line 162, in init_lutris
>     runners.RUNNER_NAMES = runners.get_runner_names()
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 112, in get_runner_names
>     return {
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 113, in <dictcomp>
>     runner: import_runner(runner)().human_name for runner in __all__
>   File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
>     "choices": DXVKManager().version_choices,
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
>     for version in self.versions:
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
>     self._versions = self.load_versions()
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
>     versions = [v["tag_name"] for v in json.load(version_file)]
>   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2021-08-18 20:58:42,947: Running AMD Mesa driver 21.1.6 on Radeon RX 570 Series (POLARIS10, DRM 3.41.0, 5.13.11-191-tkg-pds, LLVM 12.0.1) (0x67df)
> 2021-08-18 20:58:42,947: GPU: 1002:67DF 148C:2379 (amdgpu drivers)
> skipping config: /usr/bin/MangoHud.conf [ not found ]
> skipping config: /home/fenglengshun/.config/MangoHud/python3.9.conf [ not found ]
> parsing config: /home/fenglengshun/.config/MangoHud/MangoHud.conf [ ok ]
> MANGOHUD: Connected to D-Bus as ":1.4348".
>   16 | 11eyes                                   | 11eyes                                   | wine            | /media/fenglengshun/data/Media/Games/Win/VN/11eyes              
>    3 | Aiyoku no Eustia                         | aiyoku-no-eustia                         | wine            | /media/fenglengshun/data/Media/Games/Win/Aiyoku-no-Eustia       
>   19 | Ar tonelico II – Melody of Metafalica    | ar-tonelico-ii-melody-of-metafalica      | pcsx2           | -                                                               
>   18 | Ar tonelico - Melody of Elemia           | ar-tonelico-melody-of-elemia             | pcsx2           | -                                                               
>   12 | ChronoClock                              | chronoclock                              | wine            | /media/fenglengshun/data/Media/Games/Win/VN/ChronoClock/ChronoClock
>    7 | DRACU-RIOT!                              | dracu-riot                               | wine            | /media/fenglengshun/data/Media/Games/Win/VN/DRACU-RIOT!         
>    5 | Final Fantasy XIV Online - XIVLauncher   | final-fantasy-xiv-online                 | wine            | /media/fenglengshun/data/Media/Games/Win/final-fantasy-xiv-online
>    4 | Genshin Impact                           | genshin-impact                           | wine            | /media/fenglengshun/data/Media/Games/Win/GenshinImpact          
>    8 | HITMAN 3                                 | hitman-3                                 | wine            | /media/fenglengshun/ntfs/Hitman.3/Hitman 3                      
>   10 | Kinkoi: Golden Loveriche                 | kinkoi                                   | wine            | /media/fenglengshun/data/Media/Games/Win/VN/Kinkoi.Golden.Loveriche/Kinkoi.Golden.Loveriche
>    2 | Koi to Senkyo to Chocolate Portable      | koi-to-senkyo-to-chocolate-portable      | ppsspp          | /media/fenglengshun/data/Media/Games/PSP                        
>   14 | Noble ☆ Works                            | noble-works                              | wine            | /media/fenglengshun/data/Media/Games/Win/VN/Yuzusoft/Noble_Works
>   13 | Sugar * Style                            | sugar-style                              | wine            | /media/fenglengshun/data/Media/Games/Win/VN/Sugar.Style.v1.0/Sugar.Style.v1.0
>   11 | Suzukuri Dungeon: Karin in the Mountain  | suzukuri-dungeon-karin-in-the-mountain   | wine            | /media/fenglengshun/data/Media/Games/Win/VN/Suzukuri Dungeon Karin in the Mountain
>    9 | True Crime: Streets of LA                | true-crime-streets-of-la                 | wine            | /media/fenglengshun/data/Media/Games/Win/True_Crime_Streets_of_LA_Win_Files_EN/Game Files
>   15 | Tsujidou-san no Jun'ai Road              | tsujidou-san-no-junai-road               | wine            | /media/fenglengshun/data/Media/Games/Win/VN/Tsujidou-san no Jun'ai Road
>   17 | Yoake Mae yori Ruri Iro na: Brighter tha | yoake-mae-yori-ruri-iro-na-brighter-than | wine            | /media/fenglengshun/data/Media/Games/Win/VN/August/Yoake.Mae.yori.Ruri.Iro.na_brighter.than.dawning.blue
> 2021-08-18 20:58:43,083: Shutting down Lutris
> $ lutris:rungame/15                                                                                                                                                      ✔ 
> zsh: no such file or directory: lutris:rungame/15
> $ lutris rungame/15                                                                                                                                                  127 ✘ 
> 2021-08-18 21:00:16,117: Starting Lutris 0.5.9
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 211, in do_startup
>     init_lutris()
>   File "/usr/lib/python3.9/site-packages/lutris/startup.py", line 162, in init_lutris
>     runners.RUNNER_NAMES = runners.get_runner_names()
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 112, in get_runner_names
>     return {
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 113, in <dictcomp>
>     runner: import_runner(runner)().human_name for runner in __all__
>   File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
>     "choices": DXVKManager().version_choices,
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
>     for version in self.versions:
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
>     self._versions = self.load_versions()
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
>     versions = [v["tag_name"] for v in json.load(version_file)]
>   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2021-08-18 21:00:16,129: Running AMD Mesa driver 21.1.6 on Radeon RX 570 Series (POLARIS10, DRM 3.41.0, 5.13.11-191-tkg-pds, LLVM 12.0.1) (0x67df)
> 2021-08-18 21:00:16,130: GPU: 1002:67DF 148C:2379 (amdgpu drivers)
> skipping config: /usr/bin/MangoHud.conf [ not found ]
> skipping config: /home/fenglengshun/.config/MangoHud/python3.9.conf [ not found ]
> parsing config: /home/fenglengshun/.config/MangoHud/MangoHud.conf [ ok ]
> MANGOHUD: Connected to D-Bus as ":1.4357".
> 2021-08-18 21:00:16,408: No game found in library
> 2021-08-18 21:00:16,409: Shutting down Lutris
> 2021-08-18 21:00:16,416: Shutting down Lutris
> $ lutris rungame/1                                                                                                                                                       ✔ 
> 2021-08-18 21:00:24,393: Starting Lutris 0.5.9
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 211, in do_startup
>     init_lutris()
>   File "/usr/lib/python3.9/site-packages/lutris/startup.py", line 162, in init_lutris
>     runners.RUNNER_NAMES = runners.get_runner_names()
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 112, in get_runner_names
>     return {
>   File "/usr/lib/python3.9/site-packages/lutris/runners/__init__.py", line 113, in <dictcomp>
>     runner: import_runner(runner)().human_name for runner in __all__
>   File "/usr/lib/python3.9/site-packages/lutris/runners/wine.py", line 211, in __init__
>     "choices": DXVKManager().version_choices,
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 60, in version_choices
>     for version in self.versions:
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 36, in versions
>     self._versions = self.load_versions()
>   File "/usr/lib/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 69, in load_versions
>     versions = [v["tag_name"] for v in json.load(version_file)]
>   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2021-08-18 21:00:24,405: Running AMD Mesa driver 21.1.6 on Radeon RX 570 Series (POLARIS10, DRM 3.41.0, 5.13.11-191-tkg-pds, LLVM 12.0.1) (0x67df)
> 2021-08-18 21:00:24,405: GPU: 1002:67DF 148C:2379 (amdgpu drivers)
> skipping config: /usr/bin/MangoHud.conf [ not found ]
> skipping config: /home/fenglengshun/.config/MangoHud/python3.9.conf [ not found ]
> parsing config: /home/fenglengshun/.config/MangoHud/MangoHud.conf [ ok ]
> MANGOHUD: Connected to D-Bus as ":1.4360".
> 2021-08-18 21:00:24,658: No game found in library
> 2021-08-18 21:00:24,658: Shutting down Lutris
> 2021-08-18 21:00:24,664: Shutting down Lutris
> 
> ^C
> $ lutris rungame/19                                                                                                                                           INT ✘  5s  
> $ neofetch --off                                                                                                                                                       1 ✘ 
> fenglengshun@manjaro-pc 
> ----------------------- 
> OS: Manjaro Linux x86_64 
> Kernel: 5.13.11-191-tkg-pds 
> Uptime: 13 hours, 4 mins 
> Packages: 1865 (pacman), 25 (flatpak), 9 (snap) 
> Shell: zsh 5.8 
> Resolution: 1920x1080, 1366x768 
> DE: GNOME 40.3 
> WM: Mutter 
> Terminal: gnome-terminal 
> CPU: AMD Ryzen 5 3400G (8) @ 3.776GHz 
> GPU: AMD ATI Radeon 570 
> Memory: 14785MiB / 32031MiB
> ```
> 
> Of note, the main thing that might have triggered it was that Manjaro recently have a big update yesterday, so I think it might have been something from that.
> 
> Other than that, I did moved my winetricks cache folder out from my `/` ssd to a `/media/` hdd, then linked the folder to my ~/.cache folder but I did put it back just in case that's triggering some weird error but it doesn't fix it. And I have conda installed for my python class, but I need to trigger it first using `source /opt/anaconda/bin/activate root` so it shouldn't be part of the problem? Is there anything that might have conflict with lutris?
> 
> Please let me know if there is any other information I could give or if I should make a separate issue.

**Comment by bayazidbh** [comment]
For now, I've managed to fix it by copy pasting all of the lutris files from a fresh Manjaro install on a VM. I'm still not sure what exactly caused the error or what the error message exactly meant, however.
