### ISSUE TITLE
Error at end of battle.net install, perhaps a python 2=>3 bug

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#367]
```
DEBUG    2016-09-27 20:13:51,359 [interpreter]:Saved game entry battlenet (407)
Traceback (most recent call last):
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/commands.py", line 340, in _monitor_task
    self._iter_commands()
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 405, in _iter_commands
    self._finish_install()
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 433, in _finish_install
    self._write_config()
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 500, in _write_config
    self.script[self.runner]
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 533, in _substitute_config
    for key in script_config:
TypeError: 'NoneType' object is not iterable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type

Original exception was:
Traceback (most recent call last):
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/commands.py", line 340, in _monitor_task
    self._iter_commands()
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 405, in _iter_commands
    self._finish_install()
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 433, in _finish_install
    self._write_config()
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 500, in _write_config
    self.script[self.runner]
  File "/media/ovo/Données/Creation/Programmation/Programmes/Lutris/lutris/lutris/installer/interpreter.py", line 533, in _substitute_config
    for key in script_config:
TypeError: 'NoneType' object is not iterable
```

**Comment by strycore** [comment]
Badly formatted install script… I've fixed the script and changed the interpreter so it wouldn't crash at this point. Now I have to get Battle.net installed in a win64 prefix like the installer is supposed to do.

**Comment by strycore** [comment]
The bug itself is fixed but the Battle.net installer if far from being great :/

**Comment by strycore** [comment]
Works fine now.
