### ISSUE TITLE
Lutris sidebar blank, added games disappear on a reload

### ISSUE THREAD

**Issue by LexiBet** [lutris/lutris#3722]
Installed on Arch with KDE, neither 5.8 or 5.9 work properly. Installed all dependencies as suggested in the wiki. Works fine on Manjaro Arch KDE and Endevouros KDE. Changing GTK theme does not solve the issue.

Debug shows:

`Traceback (most recent call last):`
  `File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 322, in on_realize`
    `service = service_classes[service_name]()`
  `File "/usr/lib/python3.9/site-packages/lutris/services/gog.py", line 106, in __init__`
  `  self.locale = gog_locales.get(i18n.get_lang(), "en-US")`
  `File "/usr/lib/python3.9/site-packages/lutris/util/i18n.py", line 9, in get_lang`
  `  return user_locale[:2]`
`TypeError: 'NoneType' object is not subscriptable`

While when it works on Endevouros it shows:
`DEBUG 2021-20-05 19:10:15,245 [lutriswindow.on_sidebar_changed:745]:Sidebar changed`
`DEBUG 2021-20-05 19:10:15,848 [lutriswindow.update_store:451]:Showing 0 games`

I've reinstalled a few times, deleted files from the .config and others in the home directory with no change.

**Comment by LexiBet** [comment]
Thank you for explaining what the code meant, KDE was messing with my locale settings. So happy to have it working, thank you!
