### ISSUE TITLE
Cannot run WINE games error get_wine_version(path).lower() returns None

### ISSUE THREAD

**Issue by Blizzsuxx** [lutris/lutris#3764]
until recently running WINE games has worked really well
but now whenever i press on the "launch" button, it gets permanently greyed out with "Launching" on the button.
when running Lutris from a terminal and trying to launch a game, I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 840, in play
    wine_ver = is_version_esync(self.get_executable())
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 293, in is_version_esync
    wine_version = get_wine_version(path).lower()
AttributeError: 'NoneType' object has no attribute 'lower'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 840, in play
    wine_ver = is_version_esync(self.get_executable())
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 293, in is_version_esync
    wine_version = get_wine_version(path).lower()
AttributeError: 'NoneType' object has no attribute 'lower'

```

i know for a fact that i have WINE installed, because Lutris used to work and I can run games from the command line using wine

**Comment by jlmxyz** [comment]
same here if using the system's wine (either by selecting a system wine, or providing a path to executable) by the way lutris don't report all available wine installed on system : 
wine-vanilla
wine-vanilla-6.11
wine-vanilla-6.16
wine-vanilla-6.21

while lutris only report wine-6.11 as a choice

using lutris to install wine works fine

the most annoying issue on this is that we can't stop the game, lutris has to be killed to have the option to reconfigure the game and relaunch it... the error is not catched or displayed

**Comment by philippludwig** [comment]
Downgrading lutris to version 0.5.8.4 works as a workaround; just a note for anyone hitting this issue.
