### ISSUE TITLE
(default?) icons fail to load, most games missing from library

### ISSUE THREAD

**Issue by burner1024** [lutris/lutris#3768]
```
2021-10-22 03:57:19,122: Starting Lutris 0.5.9.1
2021-10-22 03:57:19,206: No cores found
2021-10-22 03:57:21,828: Startup complete
2021-10-22 03:57:21,831: Running Intel Mesa driver 21.1.8 on Mesa Intel(R) HD Graphics 520 (SKL GT2) (0x1916)
2021-10-22 03:57:21,832: GPU: 8086:1916 17AA:2245 (i915 drivers)
2021-10-22 03:57:22,238: Unable to load icon from image bg2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 455, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 158, in add_game
    game.get_pixbuf(),
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store_item.py", line 108, in get_pixbuf
    return get_pixbuf_for_game(
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 128, in get_pixbuf_for_game
    return get_pixbuf(image_abspath, size, fallback=get_default_icon(size), is_installed=is_installed)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 59, in get_pixbuf
    pixbuf = pixbuf.scale_simple(width, height, GdkPixbuf.InterpType.NEAREST)
AttributeError: 'NoneType' object has no attribute 'scale_simple'
```
[GLib.GError](https://github.com/lutris/lutris/blob/f4dee7eac3baaab5a5324fab2e5186729189bba8/lutris/gui/widgets/utils.py#L50) path is faulty. `pixbuf` is `None` in it, and it calls non-existing methods. https://github.com/lutris/lutris/blob/f4dee7eac3baaab5a5324fab2e5186729189bba8/lutris/gui/widgets/utils.py#L58, https://github.com/lutris/lutris/blob/f4dee7eac3baaab5a5324fab2e5186729189bba8/lutris/gui/widgets/utils.py#L62

Should init pixbuf to proper value before calling methods.

**Comment by WGH-** [comment]
Looks like it's a regression that happened between 0.5.8.4 and 0.5.9.1. The former worked (though rendered garbage, most likely uninitialized memory, instead of icons), and the latter simply spits out an exception and doesn't show any games at all.

**Comment by WGH-** [comment]
I had gdk-pixbuf built without jpeg support. I rebuilt it, and now both the old and the new lutris work fine.

**Comment by burner1024** [comment]
Could be, but lutris is handling the exception wrong still.

**Comment by WGH-** [comment]
Yeah, on second thought, my issue was a problem related to my Linux distribution. Bad image can still break everything, and it's indeed wrong.
