### ISSUE TITLE
strange issue with gui

### ISSUE THREAD

**Issue by WorkDevel** [lutris/lutris#3769]
I have strange issue since change my laptop to MSI Bravo 15 (AMD Ryzen 5). The symptoms are as following I cannot instal any games from integrations i.e.: GOG, Epic Games Store. There are few way to reproduce it:

**I - use install button:**
When I click install button imedietly got the message box

**GOG:**
![obraz](https://user-images.githubusercontent.com/29429051/138448169-9bcc50b6-74a4-4d4e-b608-f99575e6bc4d.png)

**EPIC:**
![obraz](https://user-images.githubusercontent.com/29429051/138448873-b9a29f30-17ac-4e53-9844-a10b6a369996.png)

And then the installation window cannot complete installation:

**GOG:**
![obraz](https://user-images.githubusercontent.com/29429051/138448322-e5aee160-366d-4323-9715-fe92d8ab25ca.png)

**EPIC:**
![obraz](https://user-images.githubusercontent.com/29429051/138449030-a1d6cb63-9d96-4565-a196-74340396b6c8.png)

**II - double click on the game entry or right click to begin install:**

This approache lead to the same result, installation window hangsup and do nothing

**GOG:**
![obraz](https://user-images.githubusercontent.com/29429051/138448631-78f35813-2953-4443-88d2-f85de07aac29.png)

**EPIC:**
![obraz](https://user-images.githubusercontent.com/29429051/138448726-02c23ebe-7c2a-4704-be48-e756e59da937.png)

Similar problem exist for any community installer without the dialog:
![obraz](https://user-images.githubusercontent.com/29429051/138449335-bdd9724f-131a-452b-ab64-4c0ee276c685.png)

The only way i could install any games was go to lutris website, search the game i want install and click install on the choosen script, then choose lutris to open:
![obraz](https://user-images.githubusercontent.com/29429051/138449714-712069d7-7751-4fc2-8488-2f32d6600b96.png)

After starting lutris from terminal I've got info about xrandr timeout:
`2021-10-22 18:27:09,320: Starting Lutris 0.5.9.1
2021-10-22 18:27:09,356: No cores found
2021-10-22 18:27:10,099: Startup complete
2021-10-22 18:27:10,100: Running AMD Mesa driver 21.2.4 on AMD RENOIR (DRM 3.40.0, 5.11.0-38-generic, LLVM 12.0.1) (0x1636)
2021-10-22 18:27:10,101: GPU: 1002:1636 1462:12B5 (amdgpu drivers)
2021-10-22 18:27:10,101: GPU: 1002:7340 1462:12B5 (amdgpu drivers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 155, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 59, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_resolution()
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 165, in get_current_resolution
    for line in _get_vidmodes():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 15, in _get_vidmodes
    return read_process_output(["xrandr"]).split("\n")
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 84, in read_process_output
    return subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['xrandr']' timed out after 2 seconds
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 155, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 59, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_resolution()
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 165, in get_current_resolution
    for line in _get_vidmodes():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 15, in _get_vidmodes
    return read_process_output(["xrandr"]).split("\n")
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 84, in read_process_output
    return subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['xrandr']' timed out after 2 seconds
2021-10-22 18:31:25,253: EGS (epic-games-store) not installed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 155, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 59, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_resolution()
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 165, in get_current_resolution
    for line in _get_vidmodes():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 15, in _get_vidmodes
    return read_process_output(["xrandr"]).split("\n")
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 84, in read_process_output
    return subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['xrandr']' timed out after 2 seconds
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 155, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 59, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_resolution()
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 165, in get_current_resolution
    for line in _get_vidmodes():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 15, in _get_vidmodes
    return read_process_output(["xrandr"]).split("\n")
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 84, in read_process_output
    return subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['xrandr']' timed out after 2 seconds
2021-10-22 18:27:09,320: Starting Lutris 0.5.9.1
2021-10-22 18:27:09,356: No cores found
2021-10-22 18:27:10,099: Startup complete
2021-10-22 18:27:10,100: Running AMD Mesa driver 21.2.4 on AMD RENOIR (DRM 3.40.0, 5.11.0-38-generic, LLVM 12.0.1) (0x1636)
2021-10-22 18:27:10,101: GPU: 1002:1636 1462:12B5 (amdgpu drivers)
2021-10-22 18:27:10,101: GPU: 1002:7340 1462:12B5 (amdgpu drivers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 155, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 59, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_resolution()
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 165, in get_current_resolution
    for line in _get_vidmodes():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 15, in _get_vidmodes
    return read_process_output(["xrandr"]).split("\n")
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 84, in read_process_output
    return subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['xrandr']' timed out after 2 seconds
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 155, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 59, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_resolution()
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 165, in get_current_resolution
    for line in _get_vidmodes():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/xrandr.py", line 15, in _get_vidmodes
    return read_process_output(["xrandr"]).split("\n")
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 84, in read_process_output
    return subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['xrandr']' timed out after 2 seconds
2021-10-22 18:31:25,253: EGS (epic-games-store) not installed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 155, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 59, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_`

I've got similar problem when try to run second time Star Wars The Force Unleashed Sith Edition from GOG - I add game installe by minigalxy. The only way to run game was to restart lutris and then I could run it only once to next lutris restart.

I've just check the lastest lutris version runned from source and there is no xrandr errors and I can install game from gog or epic after accepting the window with the prompt as on the first screenshot.

**Comment by strycore** [comment]
fixed
