### ISSUE TITLE
When i try to download a game from the egs intergration i get a KeyError

### ISSUE THREAD

**Issue by im-viriv** [lutris/lutris#3784]
Hey all. 
the title speaks for itself.

here's the full error

`Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 497, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3.9/site-packages/lutris/services/egs.py", line 400, in install
    [self.generate_installer(db_game, egs_game)],
  File "/usr/lib/python3.9/site-packages/lutris/services/egs.py", line 358, in generate_installer
    egs_exe = egs_game.config.game_config["exe"]
KeyError: 'exe'`

**Comment by tannisroot** [comment]
Can you write some reproduction steps?

**Comment by im-viriv** [comment]
it seems like reinstalling egs fixed it but i did a direct update from the old lutris version to the new and my egs install just broke somehow. but as i said re-installing egs fixed it
