### ISSUE TITLE
Won't open configure panel with some icons

### ISSUE THREAD

**Issue by sfjuocekr** [lutris/lutris#3802]
```
2021-11-03 02:59:23,691: Unable to load icon from image fl-studio
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 178, in on_edit_game_configuration
    EditGameConfigDialog(self.window, self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/edit_game.py", line 16, in __init__
    self.build_tabs("game")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 70, in build_tabs
    self._build_info_tab()
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 79, in _build_info_tab
    info_box.pack_start(self._get_banner_box(), False, False, 6)  # Banner
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 155, in _get_banner_box
    self._set_image("banner")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 195, in _set_image
    image.set_from_pixbuf(get_pixbuf_for_game(game_slug, size))
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 127, in get_pixbuf_for_game
    return get_pixbuf(image_abspath, size, fallback=get_default_icon(size), is_installed=is_installed)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 58, in get_pixbuf
    pixbuf = pixbuf.scale_simple(width, height, GdkPixbuf.InterpType.NEAREST)
AttributeError: 'NoneType' object has no attribute 'scale_simple'
```

This seems to happen with the icon for "FL Studio", right click > configure to reproduce.

**Comment by kaasknak** [comment]
I can confirm this happening as well on 0.5.9.1
The problem seems to only exist on one icon which is is a linux game. It never shows itself on another WINE game. The problem is also not consistent. Most of the time I can't open this menu but sometimes I suddenly can.
I only have two games installed so I can't do any further testing but my errors are the same as @sfjuocekr .

**Comment by compu42** [comment]
I have the same issue on 0.5.9.1. It seems to happen with almost every game I have.

**Comment by Azriel-Legnasia** [comment]
I have it happening on a couple of WINE titles including Star Citizen
