### ISSUE TITLE
Can't install local installers

### ISSUE THREAD

**Issue by Benni3D** [lutris/lutris#3811]
Doing `lutris -i /tmp/tarkov.yaml` does:
```
2021-11-07 20:52:40,453: Starting Lutris 0.5.9.1
2021-11-07 20:52:40,456: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,457: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,457: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,457: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,457: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,457: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,458: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,458: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,458: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,458: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,459: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,459: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,461: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,461: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,462: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,462: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,462: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,462: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,462: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,462: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,462: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,463: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,463: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,463: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,473: No cores found
2021-11-07 20:52:40,506: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,506: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,506: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,506: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,506: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,507: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,507: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,507: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,507: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,507: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,507: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,508: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,509: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,509: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,509: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,509: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,509: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,509: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:40,510: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,510: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,510: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:40,510: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,510: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,510: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:40,917: Failed to get url https://api.github.com/repos/lutris/dxvk/releases: HTTP Error 403: rate limit exceeded
2021-11-07 20:52:40,919: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:40,920: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,013: Failed to get url https://api.github.com/repos/lutris/dxvk-nvapi/releases: HTTP Error 403: rate limit exceeded
2021-11-07 20:52:41,014: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,015: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,121: Failed to get url https://api.github.com/repos/lutris/vkd3d/releases: HTTP Error 403: rate limit exceeded
2021-11-07 20:52:41,122: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,122: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,221: Failed to get url https://api.github.com/repos/lutris/d3d_extras/releases: HTTP Error 403: rate limit exceeded
2021-11-07 20:52:41,223: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,223: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,224: Startup complete
2021-11-07 20:52:41,225: Using NVIDIA drivers 495.44 for x86_64
2021-11-07 20:52:41,225: GPU: Unknown
2021-11-07 20:52:41,225: GPU: 1002:1636 1D05:1100 (amdgpu drivers)
2021-11-07 20:52:41,226: GPU: 10DE:1F15 1D05:1100 (nvidia drivers)
2021-11-07 20:52:41,445: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,446: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,448: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,448: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,448: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,449: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,451: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,451: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,451: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,451: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,452: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,452: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,452: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,452: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,452: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,452: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,453: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,453: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,455: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,455: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,455: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,456: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,456: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,456: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,456: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,456: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,456: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,457: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,457: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,457: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,470: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,470: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,470: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,470: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,471: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,471: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,471: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,471: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,471: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,471: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,472: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,472: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,473: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,473: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,473: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,474: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,474: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,474: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,474: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,474: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,475: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,475: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,475: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,475: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,477: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,478: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,478: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,478: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,478: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,478: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,479: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,479: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,479: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,479: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,479: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,479: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,481: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,482: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,482: Loading of DXVK versions failed, defaulting to locally available versions
2021-11-07 20:52:41,482: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,482: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,483: Loading of VKD3D versions failed, defaulting to locally available versions
2021-11-07 20:52:41,483: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,483: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,483: Loading of D3D Extras versions failed, defaulting to locally available versions
2021-11-07 20:52:41,483: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,484: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2021-11-07 20:52:41,484: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 468, in do_command_line
    self.show_installer_window(installers)
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 264, in show_installer_window
    self.show_window(
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 249, in show_window
    window_key = str(window_class) + self.get_window_key(**kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 236, in get_window_key
    return kwargs["installers"][0]["game_slug"]
KeyError: 'game_slug'
2021-11-07 20:52:42,548: Shutting down Lutris
```

**Comment by AlexanderRavenheart** [comment]
You're missing necessary details in the .yml file. Read: https://github.com/lutris/lutris/blob/master/docs/installers.rst

**Comment by Benni3D** [comment]
Looks like I should've clicked the "download" button and not copy the installer directly.
Thanks, problem resolved.
