### ISSUE TITLE
Client hang/crash when testing Morrowind openmw installer

### ISSUE THREAD

**Issue by Swizzler121** [lutris/lutris#3836]
### Bug description

Tried to update Morrowind + OpenMW installer for GOG to 0.47. When running the 0.46 installer it works fine, but if I edit the script just changing a single line (the path to the openmw download) just editing a single character (changing the 6 in 46 to a 7) it causes a crash. Visually I see a window asking me to press a continue button that isn't there.

was told to file a bug here, and that it still applied even though it's technically based around and installer, they said the client is crashing so to still submit it.

### How to Reproduce

1. Go to morrowind GOTY installer and edit it
2. edit line 2 to point to the .47 download (https://downloads.openmw.org/linux/generic/openmw-0.47.0-Linux-64Bit.tar.gz)
3. Save the draft
4. click "test this installer" and see the crash.

### Expected behavior

that morrowind+openmw .47 is installed

### Log output

```shell
$ lutris -d
2021-11-18 21:57:05,473: Magic not available. Unable to automatically find game executables. Please install python-magic
2021-11-18 21:57:05,510: No cores found
2021-11-18 21:57:05,549: Initializing lutris
2021-11-18 21:57:06,207: Downloading DXVK releases to /home/chrg/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-11-18 21:57:06,508: Writing to /home/chrg/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-11-18 21:57:06,510: Runtime updated. Initialization complete.
INFO     2021-11-18 21:57:06,510 [application.do_command_line:315]:Lutris 0.5.8.4
INFO     2021-11-18 21:57:06,511 [startup.check_driver:57]:Running AMD Mesa driver 21.2.3 on AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.42.0, 5.14.10-1-MANJARO, LLVM 12.0.1) (0x67df)
INFO     2021-11-18 21:57:06,511 [startup.check_driver:69]:GPU: 1002:67DF 1028:1701 (amdgpu drivers)
2021-11-18 21:57:50,103: Lutris 0.5.8.4
2021-11-18 21:57:50,104: Running AMD Mesa driver 21.2.3 on AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.42.0, 5.14.10-1-MANJARO, LLVM 12.0.1) (0x67df)
2021-11-18 21:57:50,104: GPU: 1002:67DF 1028:1701 (amdgpu drivers)
2021-11-18 21:57:50,118: Fetching installer https://lutris.net/api/installers/games/the-elder-scrolls-iii-morrowind-goty-edition/revisions/79952
2021-11-18 21:57:50,118: GET https://lutris.net/api/installers/games/the-elder-scrolls-iii-morrowind-goty-edition/revisions/79952
2021-11-18 21:57:54,535: Retrieving video modes from XrandR
2021-11-18 21:57:56,654: GET https://auth.gog.com/token?client_id=46899977096215655&client_secret=9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9&grant_type=refresh_token&refresh_token=L43seywHLbScjdNQGHkekBAQKmDEdTzTz7zo8MYytg4YmI2nVHA1rUNKjOzRvwLV
2021-11-18 21:57:57,000: GET https://embed.gog.com/userData.json
2021-11-18 21:57:57,643: Getting game details for 1440163901
2021-11-18 21:57:57,644: GET https://api.gog.com/products/1440163901?expand=downloads
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 304, in on_runners_ready
    self.show_installer_files_screen()
  File "/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 310, in show_installer_files_screen
    installer_files_box = InstallerFilesBox(self.interpreter.installer, self)
  File "/usr/lib/python3.9/site-packages/lutris/gui/installer/files_box.py", line 27, in __init__
    installer_file_box = InstallerFileBox(installer_file)
  File "/usr/lib/python3.9/site-packages/lutris/gui/installer/file_box.py", line 29, in __init__
    self.cache_to_pga = self.installer_file.uses_pga_cache()
AttributeError: 'str' object has no attribute 'uses_pga_cache'
2021-11-18 21:57:58,482: Creating destination path /mnt/gamedrv/games/lutris/the-elder-scrolls-iii-morrowind-goty-edition
```

### System Information

```shell
[System]
OS:              Manjaro Linux 21.1.6 Pahvo
Arch:            x86_64
Kernel:          5.14.10-1-MANJARO
Desktop:         KDE
Display Server:  tty

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3700X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            0.5 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.42.0, 5.14.10-1-MANJARO, LLVM 12.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.3
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.3
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.3
Vulkan:          Supported
```

### Media (optional)

![Screenshot_20211117_161856](https://user-images.githubusercontent.com/36831696/142566883-e559b39e-f1f3-4361-9e9b-3c5530335aef.png)

### Checklist:

- [X] I'm not asking for support with a game, an installer script or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by spawnedc** [comment]
From the logs you provided, `GET https://api.gog.com/products/1440163901?expand=downloads` is interesting. Even though it returns the correct game data, it does not have any installers. Out of curiosity, I checked my library in GoG and realised that GoG makes a request to `https://www.gog.com/account/gameDetails/1435828767.json` to retrieve data. Which comes with all the installer data.

From Lutris API for Morrowind GOTY: https://lutris.net/api/installers/the-elder-scrolls-iii-morrowind-goty-edition?format=json, `gogid` is set to `1440163901`, which matches your logs. However, GoG uses `1435828767` as this game's id. When this `gogid` is used in the initial API call to GoG, https://api.gog.com/products/1435828767?expand=downloads, you can see that all the download links are returned.

So maybe this can be solved by a simple change on Lutris DB to change the `gogid` for Morrowind.

**Comment by strycore** [comment]
if installed from the website (without the GOG integration) the installer would have defaulted to the wrong GOG ID.
Our previous sync with GOG was returning packages, where we are only interested in IDs for games. 
The crash also has been fixed by a recent patch.
