### ISSUE TITLE
Install button from steam for windows (winesteam) does nothing.

### ISSUE THREAD

**Issue by Zincr0** [lutris/lutris#3854]
### Bug description

Trying to install a game with the install button from the steam for windows panel doesn't work.

Log says there's an error on steamwindows.py, `UnboundLocalError: local variable 'appid' referenced before assignment`

### How to Reproduce

1. Go to 'Sources -> Steam for windows'
2. Click on 'reload button, wait for game list/icons to load.'
3. Click on any game and the Install button
4. See nothing.

### Expected behavior

Install dialog should appear.

### Log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 497, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/steamwindows.py", line 74, in install
    appid=appid
UnboundLocalError: local variable 'appid' referenced before assignment
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 497, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/steamwindows.py", line 74, in install
    appid=appid
UnboundLocalError: local variable 'appid' referenced before assignment
```

### System Information

```shell
[System]
OS:              KDE neon 20.04 focal
Arch:            x86_64
Kernel:          5.11.0-40-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.0 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.82.00
OpenGL Core:     4.6.0 NVIDIA 470.82.00
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.82.00
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by sgtnasty** [comment]
Same issue here:

```
[System]
OS:              Arch Linux  
Arch:            x86_64
Kernel:          5.15.11-arch2-1
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             30.9 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 495.46
OpenGL Core:     4.6.0 NVIDIA 495.46
OpenGL ES:       OpenGL ES 3.2 NVIDIA 495.46
Vulkan:          Not Supported

```

**Comment by strycore** [comment]
Fixed in master
