### ISSUE TITLE
Can't interact with existing winesteam games in the library

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3954]
```ERROR    2021-12-29 15:17:54,343 [game._get_runner:195]:Unable to import runner winesteam for steven-universe-save-the-light
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/lutriswindow.py", line 436, in update_revealer
    self.game_bar = GameBar(game, self.game_actions, self.application)
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 60, in __init__
    self.update_view()
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 76, in update_view
    self.play_button = self.get_play_button()
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 216, in get_play_button
    popover = self.get_popover(self.get_game_buttons(), popover_button)
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 223, in get_game_buttons
    displayed = self.game_actions.get_displayed_entries()
  File "/usr/lib/python3.10/site-packages/lutris/game_actions.py", line 106, in get_displayed_entries
    "execute-script": bool(self.game.is_installed and self.game.runner.system_config.get("manual_command")),
AttributeError: 'NoneType' object has no attribute 'system_config'```

**Comment by danieljohnson2** [comment]
I can't repro this, but it seems very obvious from the trace-back. There's a missing None check that blows up if a game has no runner.
