### ISSUE TITLE
Trying to edit Wine versions without a net connection just quietly errors

### ISSUE THREAD

**Issue by Freso** [lutris/lutris#396]
If I try to manage the installed versions of the Wine runner and I don't have a net connection, I get the following in the terminal, but Lutris' (G)UI just doesn't react to my input.
```
ERROR    2016-10-12 19:26:45,334 [http]:Unable to connect to server (https://lutris.net/api/runners/wine): <urlopen error timed out>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lutris/gui/sidebar.py", line 141, in on_manage_versions
    RunnerInstallDialog(dlg_title, self.parent_window, self.runner.name)
  File "/usr/lib/python3.5/site-packages/lutris/gui/runnerinstalldialog.py", line 30, in __init__
    label = Gtk.Label("%s version management" % self.runner_info['name'])
TypeError: 'NoneType' object is not subscriptable
```
It would probably be better to have Lutris give a message that it wasn't able to connect to the server or some such rather than doing… nothing.

Using git commit 44ed33a and Python 3.5.2.

**Comment by strycore** [comment]
Fixed by e89e805
