### ISSUE TITLE
python module lxml needs to be mannualy installed on Gentoo gnu/linux

### ISSUE THREAD

**Issue by trakBan** [lutris/lutris#4008]
### Bug description

I installed lutris with emerge

pretty much the title. When trying to double click on lutris icon nothing happens, when launching through the terminal it displays the log output that i pasted below. Problem is solved by typing
```
pip3 install lxml --user
```

### How to Reproduce

1. Open terminal on Gentoo GNU/linux
2. Type lutris
3. issue

### Expected behavior

launch without a problem

### Log output

```shell
2022-01-25 14:55:14,789: Package 'distro' unavailable. Unable to read Linux distribution
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 43, in <module>
    from lutris.gui.installerwindow import InstallerWindow
  File "/usr/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 16, in <module>
    from lutris.installer import interpreter
  File "/usr/lib/python3.9/site-packages/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/usr/lib/python3.9/site-packages/lutris/installer/installer.py", line 13, in <module>
    from lutris.services import SERVICES
  File "/usr/lib/python3.9/site-packages/lutris/services/__init__.py", line 9, in <module>
    from lutris.services.gog import GOGService
  File "/usr/lib/python3.9/site-packages/lutris/services/gog.py", line 9, in <module>
    from lxml import etree
```

### System Information

```shell
[System]
OS:              u n k n o w n
Arch:            x86_64
Kernel:          5.15.11-gentoo-x86_64
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 2700X Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.6 GB
Swap:            15.7 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.42.0, 5.15.11-gentoo-x86_64, LLVM 13.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.6
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.6
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.6
Vulkan:          Not Supported
```

### Media (optional)

![Screenshot_2022-01-25_15-00-42](https://user-images.githubusercontent.com/81049050/150990900-47c4b91f-bfc4-478e-8172-5716f7f5c1fe.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
this needs to be reported to the gentoo maintainer, we can't fix this.
