### ISSUE TITLE
Can't login to origin.

### ISSUE THREAD

**Issue by Casul51** [lutris/lutris#4011]
### Bug description

After origin's login page - there is empty webpage. It doesn't close it self and origin don't think there was any authentication (+ exceptions in log).
Also probably in log some sensitive information since it is authentication :)

### How to Reproduce

1. Click on Origin's login.
2. Login.
3. See empty page.
4. Wait and/or close it.
5. Lutris isn't  logged in in origin

### Expected behavior

Successfully login to origin.

### Log output

```shell
~  lutris -d                                                                                                         
INFO     2022-01-26 02:37:28,278 [startup.init_lutris:162]:Starting Lutris 0.5.9.1
WARNING  2022-01-26 02:37:28,300 [libretro.get_libretro_cores:48]:No cores found
DEBUG    2022-01-26 02:37:28,306 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-01-26 02:37:28,326 [startup.check_driver:63]:Running AMD Mesa driver 22.0.0 on AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 14.0.0, DRM 3.44, 5.16.2-238-tkg-pds) (0x73bf)
INFO     2022-01-26 02:37:28,326 [startup.check_driver:75]:GPU: 1002:73BF 1458:232C (amdgpu drivers)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
[2022-01-26 02:37:28.349] [MANGOHUD] [info] [config.cpp:114] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2022-01-26 02:37:28.349] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/casual/.config/MangoHud/python3.10.conf' [ not found ]
[2022-01-26 02:37:28.349] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/casual/.config/MangoHud/MangoHud.conf'
DEBUG    2022-01-26 02:37:28,515 [http.get:81]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2022-01-26 02:37:28,804 [http.get:81]:GET https://lutris.net/api/runtimes/icons
DEBUG    2022-01-26 02:37:29,008 [http.get:81]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2022-01-26 02:37:30,218 [http.write_to_file:131]:Writing to /home/casual/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2022-01-26 02:37:30,219 [http.get:81]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2022-01-26 02:37:31,219 [http.write_to_file:131]:Writing to /home/casual/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2022-01-26 02:37:31,220 [http.get:81]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2022-01-26 02:37:32,229 [http.write_to_file:131]:Writing to /home/casual/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2022-01-26 02:37:32,230 [http.get:81]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2022-01-26 02:37:33,171 [http.write_to_file:131]:Writing to /home/casual/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2022-01-26 02:37:33,171 [http.get:81]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2022-01-26 02:37:34,302 [http.write_to_file:131]:Writing to /home/casual/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2022-01-26 02:37:34,303 [startup.update_runtime:190]:Startup complete
DEBUG    2022-01-26 02:37:34,427 [lutriswindow.update_store:468]:Showing 0 games
DEBUG    2022-01-26 02:37:35,654 [lutriswindow.update_store:468]:Showing 0 games
DEBUG    2022-01-26 02:37:36,462 [base.wipe_game_cache:288]:Deleting origin cache /home/casual/.cache/lutris/origin/cache/
DEBUG    2022-01-26 02:37:36,462 [base.wipe_game_cache:126]:Deleting games from service-games for origin
DEBUG    2022-01-26 02:37:36,462 [base.logout:303]:logged out from origin
DEBUG    2022-01-26 02:37:36,463 [lutriswindow.update_store:468]:Showing 0 games
DEBUG    2022-01-26 02:37:36,994 [base.login:276]:Connecting to Origin
https://eaassets-a.akamaihd.net/resource_signin_ea_com/551.0.20220119.178.c24b24d/p/statics/originX/js/jquery.originX-pc-common.v_1618545688-min.js:1:9015: CONSOLE LOG [ORIGIN][WEBCHANNEL] No connection.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/dialogs/webconnect_dialog.py", line 57, in on_navigation
    if url in self.service.scripts:
AttributeError: 'OriginService' object has no attribute 'scripts'
https://eaassets-a.akamaihd.net/resource_signin_ea_com/551.0.20220119.178.c24b24d/p/statics/originX/js/jquery.originX-pc-common.v_1618545688-min.js:1:9015: CONSOLE LOG [ORIGIN][WEBCHANNEL] No connection.
https://signin.ea.com/p/originX/login?execution=e314969642s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fdisplay%3DoriginXWeb%252Flogin%26response_type%3Dcode%26release_type%3Dprod%26redirect_uri%3Dhttps%253A%252F%252Fwww.origin.com%252Fviews%252Flogin.html%26locale%3Den_US%26client_id%3DORIGIN_SPA_ID:44:28: CONSOLE LOG authenticaitonJShelper undefined
https://signin.ea.com/p/originX/login?execution=e314969642s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fdisplay%3DoriginXWeb%252Flogin%26response_type%3Dcode%26release_type%3Dprod%26redirect_uri%3Dhttps%253A%252F%252Fwww.origin.com%252Fviews%252Flogin.html%26locale%3Den_US%26client_id%3DORIGIN_SPA_ID:52:28: CONSOLE LOG [[ env =
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/dialogs/webconnect_dialog.py", line 57, in on_navigation
    if url in self.service.scripts:
AttributeError: 'OriginService' object has no attribute 'scripts'
https://www.origin.com/views/login.html?code=QUOwALn7Wjavg49wmLW1XrkGzkMMtVnayYc24FKzAQ:13:29: CONSOLE JS WARN Can't close the window since it was not opened by JavaScript
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/dialogs/webconnect_dialog.py", line 57, in on_navigation
    if url in self.service.scripts:
AttributeError: 'OriginService' object has no attribute 'scripts'
INFO     2022-01-26 02:38:19,065 [application.do_shutdown:646]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Garuda Linux Soaring Harpy-Eagle
Arch:            x86_64
Kernel:          5.16.2-238-tkg-pds
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            48.4 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 14.0.0, DRM 3.44, 5.16.2-238-tkg-pds)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-268fc8e5c1)
OpenGL Core:     4.6 (Core Profile) Mesa 22.0.0-devel (git-268fc8e5c1)
OpenGL ES:       OpenGL ES 3.2 Mesa 22.0.0-devel (git-268fc8e5c1)
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I added this scripts thing during the development of the Ubisoft Connect integration but forgot to add it to the base service.

I pushed a patch, you should be able to connect.
