### ISSUE TITLE
Game installation not working

### ISSUE THREAD

**Issue by rsf92** [lutris/lutris#4016]
### Bug description

I can't install any game, clicking on the install button does nothing and running the installer from the web also gets stuck after you select the installation path.
It looks like these may be two issues, I don't know, maybe they're related

### How to Reproduce

Select any game and click install

### Expected behavior

Well, I expect this to install the game as it did before

### Log output

```shell
=============================================================================================
HERE I USED THE DESKTOP APP 
=============================================================================================
INFO     2022-01-27 17:07:45,703 [startup.check_driver:53]:Using NVIDIA drivers 470.86 for x86_64
INFO     2022-01-27 17:07:45,703 [startup.check_driver:57]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2022-01-27 17:07:45,703 [startup.check_driver:73]:GPU: 10DE:1C82 3842:6251 (nvidia drivers)
DEBUG    2022-01-27 17:07:46,126 [lutriswindow.update_store:451]:Showing 205 games
DEBUG    2022-01-27 17:07:50,633 [lutriswindow.update_store:451]:Showing 17 games
DEBUG    2022-01-27 17:07:50,923 [lutriswindow.update_store:451]:Showing 1 games
DEBUG    2022-01-27 17:07:51,464 [lutriswindow.update_store:451]:Showing 1 games
DEBUG    2022-01-27 17:07:51,624 [lutriswindow.update_store:451]:Showing 1 games
DEBUG    2022-01-27 17:07:51,813 [lutriswindow.update_store:451]:Showing 1 games
DEBUG    2022-01-27 17:07:53,760 [lutriswindow.on_game_activated:833]:No service for view
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 497, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 188, in install
    appid = db_game["appid"]
TypeError: 'NoneType' object is not subscriptable

=============================================================================================
HERE I USED THE WEB 
=============================================================================================
2022-01-27 17:08:44,464: Using NVIDIA drivers 470.86 for x86_64
2022-01-27 17:08:44,465: GPU: NVIDIA GeForce GTX 1050 Ti
2022-01-27 17:08:44,465: GPU: 10DE:1C82 3842:6251 (nvidia drivers)
2022-01-27 17:08:44,520: Fetching installer https://lutris.net/api/installers/star-trek-voyager-elite-force-gog
2022-01-27 17:08:44,520: GET https://lutris.net/api/installers/star-trek-voyager-elite-force-gog
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 90, in get
    request = urllib.request.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 462, in do_command_line
    installers = get_installers(
  File "/usr/lib/python3/dist-packages/lutris/installer/__init__.py", line 50, in get_installers
    return fetch_script(game_slug=game_slug, revision=revision)
  File "/usr/lib/python3/dist-packages/lutris/installer/__init__.py", line 24, in fetch_script
    request.get()
  File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 96, in get
    raise HTTPError("Unable to connect to server %s: %s" % (self.url, error))
lutris.util.http.HTTPError: Unable to connect to server https://lutris.net/api/installers/star-trek-voyager-elite-force-gog: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
2022-01-27 17:09:32,160: Using NVIDIA drivers 470.86 for x86_64
2022-01-27 17:09:32,160: GPU: NVIDIA GeForce GTX 1050 Ti
2022-01-27 17:09:32,161: GPU: 10DE:1C82 3842:6251 (nvidia drivers)
2022-01-27 17:09:32,203: Fetching installer https://lutris.net/api/installers/star-trek-voyager-elite-force-gog
2022-01-27 17:09:32,203: GET https://lutris.net/api/installers/star-trek-voyager-elite-force-gog
2022-01-27 17:09:32,337: Showing window <class 'lutris.gui.installerwindow.InstallerWindow'>star-trek-voyager-elite-force
2022-01-27 17:09:35,320: Retrieving current resolution
2022-01-27 17:09:37,737: Getting runner information for wine
2022-01-27 17:09:37,737: GET https://lutris.net/api/runners/wine
2022-01-27 17:09:37,833: Default wine version is lutris-fshack-6.21-6
2022-01-27 17:09:37,839: GET https://embed.gog.com/userData.json
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 294, in on_runners_ready
    self.interpreter.installer.prepare_game_files()
  File "/usr/lib/python3/dist-packages/lutris/installer/installer.py", line 149, in prepare_game_files
    installer_files = self.service.get_installer_files(self, installer_file_id)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 393, in get_installer_files
    downloads = self.get_downloads(installer.service_appid)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 306, in get_downloads
    gog_data = self.get_game_details(gogid)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 282, in get_game_details
    raise ValueError("Missing product ID")
ValueError: Missing product ID
```

### System Information

```shell
[System]
OS:              Pop!_OS 21.10 impish
Arch:            x86_64
Kernel:          5.15.15-76051515-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             15.6 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.86
OpenGL Core:     4.6.0 NVIDIA 470.86
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.86
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Looks like Lutris is having issues contacting the website for some reason. Are you able to access https://lutris.net/api/installers/star-trek-voyager-elite-force-gog from a browser?

**Comment by rsf92** [comment]
> Looks like Lutris is having issues contacting the website for some reason. Are you able to access https://lutris.net/api/installers/star-trek-voyager-elite-force-gog from a browser?

Yes, i can access it

**Comment by strycore** [comment]
This is now fixed and worst case, if the website is unreachable lutris will ask to manually provide the file.
