### ISSUE TITLE
Lutris-Git, newly added Source, "Ubisoft Connect" shows File Not Found after login

### ISSUE THREAD

**Issue by 18iteration** [lutris/lutris#4019]
### Bug description

![image](https://user-images.githubusercontent.com/45468984/151615243-0cb5fdbb-a2c9-421a-b196-29ea4c4b87d1.png)
The bug shows a file not found exception when logging into the newly added source "Ubisoft Connect".
It attempts to work with a file in a folder that hasn't been created yet "ubisoft-connect/..." (see screenshot exception file path

### How to Reproduce

This error occured the following way:
1. Run Lutris via Terminal 
2. Enable Ubisoft as a Source or if already enabled continue:
3. Click login and login with info. Click on disallow cookies because common sense.
4. Either the login window will remain white until you close it (first time, same with origin but fixed after trying Step 3 again) or the Window will disappear and now a cogwheel will appear next to the Ubisoft Source.
5. The cogwheel will spin forever and reclick Ubisoft Connect Source will show coverless / iconless games of your library.
6. Clicking on "Install" on any game does nothing. No window, no message nothing.
The error message suggests that the lutris written ubisoft.py file attempts to read or write to a file that doesn't exist.

### Expected behavior

Logging in to Ubisoft Connect and seeing the listed games with their covers (like the way it perfectly worked with Origin Source).

### Log output

```shell
[tux@archlinux ~]$ lutris -d
INFO     2022-01-28 21:29:27,934 [startup.init_lutris:162]:Starting Lutris 0.5.9.1
WARNING  2022-01-28 21:29:27,968 [libretro.get_libretro_cores:48]:No cores found
DEBUG    2022-01-28 21:29:27,978 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-01-28 21:29:28,016 [startup.check_driver:55]:Using NVIDIA drivers 495.46 for x86_64
INFO     2022-01-28 21:29:28,016 [startup.check_driver:59]:GPU: Unknown
INFO     2022-01-28 21:29:28,016 [startup.check_driver:75]:GPU: 10DE:1F08 1043:868C (nvidia drivers)
DEBUG    2022-01-28 21:29:28,066 [http.get:81]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2022-01-28 21:29:28,205 [http.get:81]:GET https://lutris.net/api/runtimes/icons
DEBUG    2022-01-28 21:29:28,356 [http.get:81]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2022-01-28 21:29:28,429 [http.write_to_file:131]:Writing to /home/tux/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2022-01-28 21:29:28,430 [http.get:81]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2022-01-28 21:29:28,495 [http.write_to_file:131]:Writing to /home/tux/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2022-01-28 21:29:28,496 [http.get:81]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2022-01-28 21:29:28,559 [http.write_to_file:131]:Writing to /home/tux/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2022-01-28 21:29:28,560 [http.get:81]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2022-01-28 21:29:28,608 [http.write_to_file:131]:Writing to /home/tux/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2022-01-28 21:29:28,610 [http.get:81]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2022-01-28 21:29:28,785 [http.write_to_file:131]:Writing to /home/tux/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2022-01-28 21:29:28,786 [startup.update_runtime:190]:Startup complete
DEBUG    2022-01-28 21:29:29,021 [lutriswindow.update_store:468]:Showing 8 games
DEBUG    2022-01-28 21:29:34,713 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-01-28 21:29:34,719 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-01-28 21:29:34,764 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-01-28 21:29:34,802 [application.show_window:268]:Showing window <class 'lutris.gui.config.preferences_dialog.PreferencesDialog'>{}
DEBUG    2022-01-28 21:29:37,245 [lutriswindow.update_store:468]:Showing 8 games
DEBUG    2022-01-28 21:29:37,252 [lutriswindow.update_store:468]:Showing 8 games
DEBUG    2022-01-28 21:29:38,162 [application.on_app_window_destroyed:285]:Removed window <class 'lutris.gui.config.preferences_dialog.PreferencesDialog'>{}
DEBUG    2022-01-28 21:29:39,031 [lutriswindow.update_store:468]:Showing 3 games
DEBUG    2022-01-28 21:29:40,412 [base.wipe_game_cache:283]:Deleting ubisoft cache /home/tux/.cache/lutris/ubisoft/library/
DEBUG    2022-01-28 21:29:40,412 [base.wipe_game_cache:121]:Deleting games from service-games for ubisoft
DEBUG    2022-01-28 21:29:40,418 [base.logout:298]:logged out from ubisoft
DEBUG    2022-01-28 21:29:40,420 [lutriswindow.update_store:468]:Showing 0 games
DEBUG    2022-01-28 21:29:41,075 [base.login:271]:Connecting to Ubisoft Connect
https://ubistatic2-a.akamaihd.net/uplay-connect/v3/prod/default/dist/appdf7ce5430197b6467e21.bundle.js:1955:63532: CONSOLE WARN tracking script is not instantiated yet
https://ubistatic-a.akamaihd.net/0106/prod/global/tracking/analyticssdk.js:5:135565: CONSOLE LOG %cAnalytics SDK: Analytics SDK loaded, waiting for adobe scode background: #222; color: #bada55
https://ubistatic-a.akamaihd.net/0106/prod/global/tracking/analyticssdk.js:5:136269: CONSOLE LOG %cAnalytics SDK: Privacy policy refused background: #222; color: #bada55
https://ubistatic-a.akamaihd.net/0106/prod/global/tracking/analyticssdk.js:5:135910: CONSOLE LOG %cAnalytics SDK: Privacy policy viewed background: #222; color: #bada55
https://ubistatic2-a.akamaihd.net/uplay-connect/v3/prod/default/dist/appdf7ce5430197b6467e21.bundle.js:1955:183060: CONSOLE LOG ticket still valid for: 159.029 minutes, just return ticket
https://ubistatic-a.akamaihd.net/0106/prod/global/tracking/analyticssdk.js:5:140417: CONSOLE LOG %cAnalytics SDK: S.code has not been attached. background: #222; color: #bada55
DEBUG    2022-01-28 21:29:47,917 [client._do_request_safe:74]:rememberMeTicket expiration time: 0
DEBUG    2022-01-28 21:29:47,917 [client._refresh_ticket:148]:Refreshing ticket
INFO     2022-01-28 21:29:48,388 [client._do_request:66]:Response status: <Response [200]>
INFO     2022-01-28 21:29:48,538 [client._do_request:66]:Response status: <Response [200]>
INFO     2022-01-28 21:29:48,539 [client._do_request:58]:No headers in kwargs, using session headers
INFO     2022-01-28 21:29:48,731 [client._do_request:66]:Response status: <Response [200]>
DEBUG    2022-01-28 21:29:48,733 [base.wipe_game_cache:283]:Deleting ubisoft cache /home/tux/.cache/lutris/ubisoft/library/
DEBUG    2022-01-28 21:29:48,733 [base.wipe_game_cache:121]:Deleting games from service-games for ubisoft
DEBUG    2022-01-28 21:29:48,734 [client._do_request_safe:74]:rememberMeTicket expiration time: 1643412589
INFO     2022-01-28 21:29:48,734 [client._do_request:58]:No headers in kwargs, using session headers
INFO     2022-01-28 21:29:48,921 [client._do_request:66]:Response status: <Response [200]>
DEBUG    2022-01-28 21:29:48,922 [client._do_request_safe:74]:rememberMeTicket expiration time: 1643412589
INFO     2022-01-28 21:29:48,922 [client._do_request:58]:No headers in kwargs, using session headers
INFO     2022-01-28 21:29:49,110 [client._do_request:66]:Response status: <Response [200]>
ERROR    2022-01-28 21:29:49,127 [jobs.target:36]:Error while completing task <bound method BaseService.reload of <ubisoft.UbisoftConnectService object at 0x7fcc448187c0 (lutris+services+ubisoft+UbisoftConnectService at 0x5560d032d0c0)>>: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '/home/tux/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/configuration/configurations'
  File "/usr/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/lutris/services/base.py", line 97, in reload
    self.load()
  File "/usr/lib/python3.10/site-packages/lutris/services/ubisoft.py", line 147, in load
    configuration_data = self.get_configurations()
  File "/usr/lib/python3.10/site-packages/lutris/services/ubisoft.py", line 133, in get_configurations
    with open(configurations_path, "rb") as config_file:
DEBUG    2022-01-28 21:29:57,343 [lutriswindow.update_store:468]:Showing 8 games
DEBUG    2022-01-28 21:29:57,658 [lutriswindow.update_store:468]:Showing 3 games
DEBUG    2022-01-28 21:30:00,127 [base.install:207]:Installing 5172a557-50b5-4665-b7db-e3f2e8c5041d from service ubisoft
DEBUG    2022-01-28 21:30:00,128 [http.get:81]:GET https://lutris.net/api/games/service/ubisoft
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 507, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3.10/site-packages/lutris/services/base.py", line 220, in install
    installer = self.generate_installer(db_game)
  File "/usr/lib/python3.10/site-packages/lutris/services/ubisoft.py", line 208, in generate_installer
    uc_exe = ubisoft_connect.config.game_config["exe"]
AttributeError: 'NoneType' object has no attribute 'game_config'
INFO     2022-01-28 21:30:32,784 [application.do_shutdown:644]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.16.2-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 1600 Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.4 GB
Swap:            1.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 495.46
OpenGL Core:     4.6.0 NVIDIA 495.46
OpenGL ES:       OpenGL ES 3.2 NVIDIA 495.46
Vulkan:          Supported
```

### Media (optional)

![image](https://user-images.githubusercontent.com/45468984/151617234-6276a19b-4d18-4eae-bfea-6f05483d2624.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by 18iteration** [comment]
Apparently: 
1. Toggling (off) the source Ubisoft Connect
2. **Installing Ubisoft Connect manually / through lutris**
3. Toggling (on) the source Ubisoft Connect
Fixed everything. Now I can even click on any "Install". This is a user-error. Closing it and hopefully future readers will take something away from this.

**Comment by rakonkido** [comment]
This is not user error. It is supposed to give you the option to install Ubisoft Connect when you press the "Install" button on a game from the Ubisoft Connect source for the first time. This is what happens in the EA Origin source, but apparently it's not working for the Ubisoft Connect source. I encourage you to re-open this issue as it still affects the beta that was released today.
