### ISSUE TITLE
GOG: "URLTask"s in "goggame-*.info" stalls installers

### ISSUE THREAD

**Issue by bexnoss** [lutris/lutris#4080]
### Bug description

Attempting to install a GOG game that includes a "URLTask" in "goggame-*.info" stalls the installer with:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/installer/commands.py", line 452, in _monitor_task
    self._iter_commands()
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 320, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 344, in _finish_install
    game_id = self.installer.save()
  File "/usr/lib/python3.10/site-packages/lutris/installer/installer.py", line 250, in save
    lutris_config = convert_gog_config_to_lutris(gog_config, gog_game_path)
  File "/usr/lib/python3.10/site-packages/lutris/util/gog.py", line 57, in convert_gog_config_to_lutris
    config = get_game_config(task, gog_game_path)
  File "/usr/lib/python3.10/site-packages/lutris/util/gog.py", line 37, in get_game_config
    exe = task["path"]
KeyError: 'path'
```

An example from LIMBO ("goggame-1724299977.info"):
```json
{
    "gameId": "1724299977", 
    "language": "English", 
    "languages": [
        "en"
    ], 
    "name": "LIMBO", 
    "playTasks": [
        {
            "category": "game", 
            "isPrimary": true, 
            "languages": [
                "*"
            ], 
            "name": "LIMBO", 
            "path": "LIMBO.exe", 
            "type": "FileTask"
        }, 
        {
            "category": "tool", 
            "languages": [
                "en"
            ], 
            "name": "Language Setup", 
            "path": "language_setup.exe", 
            "type": "FileTask"
        }, 
        {
            "category": "document", 
            "languages": [
                "en"
            ], 
            "link": "http://www.gog.com/support/limbo", 
            "name": "Support", 
            "type": "URLTask"
        }
    ], 
    "rootGameId": "1724299977", 
    "version": 1
}
```

The code causing this is: https://github.com/lutris/lutris/blob/7d5dc55a81cceffcb3e108610e02780167c1976d/lutris/util/gog.py#L35-L62

This used to work, I assume GOG started adding the Support URLTask recently.

### How to Reproduce

1. Try to install a GOG game
   - tested with LIMBO and Stronghold Crusader 2

This seems to be a GOG wide change and might affect all GOG games.

### Expected behavior

The game install doesn't stall.

### Log output

```shell
Relevant output above.
```

### System Information

```shell
Running lutris-git@7d5dc55a81cceffcb3e108610e02780167c1976d (Add splash screen)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Limbo now installs correctly
