### ISSUE TITLE
Games no longer launching with Steam SteamDeck beta

### ISSUE THREAD

**Issue by fschaupp** [lutris/lutris#4141]
### Bug description

It seems like if you add the beta flag-file in ~./.steam/steam/package and update the Steam client, launching also non-Steam related games no longer launch. 
The start button will get stuck in "Launching" and no output to the protocol-window will be sent. 

### How to Reproduce

1. Basically set up the SteamDeck beta for Steam: https://www.reddit.com/r/SteamDeck/comments/t57l4t/how_to_get_the_steam_deck_ui_on_windowsany_linux/
2. Afterwards close the SteamDeck beta with -gamepadui and start in normal mode (without the flag)
3. Now when running Lutris the games no longer start.

### Expected behavior

Either
- not poke to Steam for non-Steam games
- start the game nonetheless
- display a message describing the error
- add SteamDeck compatibility

### Log output

```shell
INFO     2022-03-09 14:40:24,354 [startup.init_lutris:164]:Starting Lutris 0.5.10
WARNING  2022-03-09 14:40:24,413 [libretro.get_libretro_cores:24]:No folder at /home/<user>/.local/share/lutris/runners/retroarch/
DEBUG    2022-03-09 14:40:24,429 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-03-09 14:40:24,481 [startup.check_driver:65]:Running AMD Mesa driver 21.3.7 on Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.0-35-generic, LLVM 13.0.0) (0x67df)
INFO     2022-03-09 14:40:24,481 [startup.check_driver:77]:GPU: 1002:67DF 1DA2:E366 (amdgpu drivers)
INFO     2022-03-09 14:40:24,535 [startup.update_runtime:203]:Startup complete
DEBUG    2022-03-09 14:40:24,955 [lutriswindow.update_store:430]:Showing 4 games
DEBUG    2022-03-09 14:40:26,829 [grid.on_item_activated:57]:Item activated: 1
ERROR    2022-03-09 14:40:27,035 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2022-03-09 14:40:27,035 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 458, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 421, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 915, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 832, in get_env
    env = super().get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 208, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 879, in get_runtime_env
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 458, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 421, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 915, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 832, in get_env
    env = super().get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 208, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 879, in get_runtime_env
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'
```

### System Information

```shell
[System]
OS:              Linux Mint 20.3 una
Arch:            x86_64
Kernel:          5.13.0-35-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            9.3 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.0-35-generic, LLVM 13.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.3.7 - kisak-mesa PPA
OpenGL Core:     4.6 (Core Profile) Mesa 21.3.7 - kisak-mesa PPA
OpenGL ES:       OpenGL ES 3.2 Mesa 21.3.7 - kisak-mesa PPA
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by fschaupp** [comment]
For general info: at discord support channel, another user also tried the SteamDeck beta and after removing the beta file or switching to the "beta"-Channel through the Seam settings, it worked again.

**Comment by strycore** [comment]
The fix for this crash has been committed 12 days ago (https://github.com/lutris/lutris/commit/072e72a4aefd91101b79dd05d8ce9f100a4b6b0c) , are you using the beta 2 of 0.5.10?

**Comment by fschaupp** [comment]
Hi strycore!
Yes indeed, I do.

**Comment by strycore** [comment]
Fix released
