### ISSUE TITLE
Cannot install game with lutris script

### ISSUE THREAD

**Issue by pegasusearl** [lutris/lutris#4148]
This is continuing from: https://github.com/lutris/lutris/issues/4147

```
OS: Manjaro Linux x86_64 
Kernel: 5.15.25-1-MANJARO 
Uptime: 17 mins 
Packages: 1632 (pacman), 8 (snap) 
Shell: zsh 5.8.1 
Resolution: 1920x1080, 1920x1080 
DE: GNOME 41.4 
WM: Mutter 
WM Theme: Matcha-light-sea 
Theme: Vertex-Dark [GTK2/3] 
Icons: Fluent-green-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3500 (6) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 1650 
Memory: 3940MiB / 15921MiB 

Lutris version 0.5.9.1-4
```

What are the method to install games from lutris script made by other people? Is clicking "Install" button on the web the only way? If not I can't seem to find any other way.

However clicking install, and opening the link in lutris, it will run lutris or if lutris already ran, it will switch focus to it after awhile. But it does nothing.

```
2022-03-13 05:02:42,644: Using NVIDIA drivers 510.54 for x86_64
2022-03-13 05:02:42,645: GPU: Unknown
2022-03-13 05:02:42,645: GPU: 10DE:1F82 10DE:1F82 (nvidia drivers)
2022-03-13 05:02:42,774: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,774: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,774: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,775: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,775: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,775: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,775: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,775: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,775: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,777: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,778: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,779: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,779: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,779: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,779: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,779: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,780: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,780: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,780: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,780: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,782: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,782: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,782: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,782: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,782: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,782: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,782: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,783: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,783: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,791: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,792: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,793: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,793: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,793: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,793: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,793: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,793: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,794: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,794: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,794: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,795: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,795: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,795: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,796: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,796: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,796: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,796: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,796: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,796: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,798: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,798: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,798: Loading of DXVK versions failed, defaulting to locally available versions
2022-03-13 05:02:42,798: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,798: Loading of VKD3D versions failed, defaulting to locally available versions
2022-03-13 05:02:42,798: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,798: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-03-13 05:02:42,799: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:42,799: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-03-13 05:02:54,553: Using NVIDIA drivers 510.54 for x86_64
2022-03-13 05:02:54,553: GPU: Unknown
2022-03-13 05:02:54,553: GPU: 10DE:1F82 10DE:1F82 (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/util/http.py", line 90, in get
    request = urllib.request.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 462, in do_command_line
    installers = get_installers(
  File "/usr/lib/python3.10/site-packages/lutris/installer/__init__.py", line 50, in get_installers
    return fetch_script(game_slug=game_slug, revision=revision)
  File "/usr/lib/python3.10/site-packages/lutris/installer/__init__.py", line 24, in fetch_script
    request.get()
  File "/usr/lib/python3.10/site-packages/lutris/util/http.py", line 96, in get
    raise HTTPError("Unable to connect to server %s: %s" % (self.url, error))
lutris.util.http.HTTPError: Unable to connect to server https://lutris.net/api/installers/novaro-novaro: <urlopen error [Errno -3] Temporary failure in name resolution>
```

**Comment by danieljohnson2** [comment]
This looks okay to me; Lutris is being invoked with the "--install" option and it fails due to DNS failures "Temporary failure in name resolution". It writes out suitable errors to standard output. The web browser you use isn't reporting anything, but that's the web for you.

There is another way to do this- you can install Lutris.net games from inside the Lutris client UI. In 5.9.1, you click the 'Lutris' sidebar row; and then click the "Community Installers" button that appears in the upper left of the window. Now, use the search box to find the game.

In 5.10 this UI is changing, and the add games button (the plus in the upper left) is where you you go for this.

*But*- I think until you get your DNS fixed you will be out of luck. If we can't download those yml files, none of this will actually work.

**Comment by pegasusearl** [comment]
Ah I see. What might be causing those? Is it my ISP?
I also tried to run with and without VPN. Not sure if that would help but the result is the same.
I tried this evening and looks like it's magically work now.
