### ISSUE TITLE
No "continue" option on installation screen when testing an installer or using a local file for installation (for GOG game)

### ISSUE THREAD

**Issue by JackH3103** [lutris/lutris#4152]
### Bug description

When testing a script or trying to install with a local script, Lutris does not provide a "Continue" button. This even happens when downloading the original (working) script. I've only tested this with _An Elder Scrolls Legend: Battlespire_ from _GOG_

### How to Reproduce

1. Make a fork of the script [here](https://lutris.net/api/installers/an-elder-scrolls-legend-battl-gog?format=json)
2. Click on 'Test this installer'
3. On Lutris click "Install" next to GOG
4. Click install

### Expected behavior

There should be a "Continue" button, as there is when installing the script from the website

### Log output

```shell
2022-03-17 18:24:42,347: Starting Lutris 0.5.9.1
2022-03-17 18:24:42,390: No cores found
2022-03-17 18:24:44,028: Startup complete
2022-03-17 18:24:44,031: Using NVIDIA drivers 470.103.01 for x86_64
2022-03-17 18:24:44,031: GPU: NVIDIA GeForce 840M
2022-03-17 18:24:44,032: GPU: 10DE:1341 1028:0656 (nvidia drivers)
2022-03-17 18:24:44,032: GPU: 8086:1616 1028:0656 (i915 drivers)
2022-03-17 18:24:49,710: Using NVIDIA drivers 470.103.01 for x86_64
2022-03-17 18:24:49,711: GPU: NVIDIA GeForce 840M
2022-03-17 18:24:49,711: GPU: 10DE:1341 1028:0656 (nvidia drivers)
2022-03-17 18:24:49,711: GPU: 8086:1616 1028:0656 (i915 drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 90, in get
    request = urllib.request.urlopen(req, timeout=self.timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 462, in do_command_line
    installers = get_installers(
  File "/usr/lib/python3.8/site-packages/lutris/installer/__init__.py", line 50, in get_installers
    return fetch_script(game_slug=game_slug, revision=revision)
  File "/usr/lib/python3.8/site-packages/lutris/installer/__init__.py", line 24, in fetch_script
    request.get()
  File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 94, in get
    raise HTTPError("%s" % error, code=error.code)
lutris.util.http.HTTPError: HTTP Error 404: Not Found
2022-03-17 18:25:12,983: Using NVIDIA drivers 470.103.01 for x86_64
2022-03-17 18:25:12,983: GPU: NVIDIA GeForce 840M
2022-03-17 18:25:12,984: GPU: 10DE:1341 1028:0656 (nvidia drivers)
2022-03-17 18:25:12,984: GPU: 8086:1616 1028:0656 (i915 drivers)
2022-03-17 18:25:39,420: Getting game details for 1440163341
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 302, in on_runners_ready
    self.show_installer_files_screen()
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 308, in show_installer_files_screen
    installer_files_box = InstallerFilesBox(self.interpreter.installer, self)
  File "/usr/lib/python3.8/site-packages/lutris/gui/installer/files_box.py", line 27, in __init__
    installer_file_box = InstallerFileBox(installer_file)
  File "/usr/lib/python3.8/site-packages/lutris/gui/installer/file_box.py", line 30, in __init__
    self.cache_to_pga = self.installer_file.uses_pga_cache()
AttributeError: 'str' object has no attribute 'uses_pga_cache'
2022-03-17 18:25:47,982: Cancelling installation of An Elder Scrolls Legend: Battlespire
2022-03-17 18:25:47,983: Non existent path: /home/jack/.cache/lutris/installer/an-elder-scrolls-legend-battlespire
2022-03-17 18:25:49,604: Shutting down Lutris
```

### System Information

```shell
[System]
OS:              openSUSE Tumbleweed 20220316 n/a
Arch:            x86_64
Kernel:          5.16.14-1-default
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.7 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce 840M/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.103.01
OpenGL Core:     4.6.0 NVIDIA 470.103.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.103.01
Vulkan:          Supported
```

### Media (optional)

Actual output:
![no-continue](https://user-images.githubusercontent.com/23507259/158871415-d75e577f-4771-4d89-9080-6bbcef29719f.png)

Expected output:
![yes-continue](https://user-images.githubusercontent.com/23507259/158871562-b9f0f3d3-7b3d-4679-8fcc-8e9b546efd1c.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That trace-back seems suggestive; it looks like you've got a str where an InstallFile is expected to be. PR #4044 fixed a bug like that, and has been merged

So... maybe this is actually fixed. Could you try the beta to see if you still have trouble with this?

**Comment by JackH3103** [comment]
Completely forgot about this, but it works now on 0.5.10.1
