### ISSUE TITLE
Guix port

### ISSUE THREAD

**Issue by phodina** [lutris/lutris#4169]
### Bug description

Hi,
I'm porting Lutris to GNU Guix distribution. I included in the package input `python-pygobject` version `3.40.1`. But when I attempt to run `bin/lutris` I get the following error:
```
$ /gnu/store/zvlqmnkmn3f2j3kv1h3m6cazrx2kj6nc-lutris-0.5.9.1/bin/lutris
Traceback (most recent call last):
  File "/gnu/store/zvlqmnkmn3f2j3kv1h3m6cazrx2kj6nc-lutris-0.5.9.1/bin/.lutris-real", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/gnu/store/zvlqmnkmn3f2j3kv1h3m6cazrx2kj6nc-lutris-0.5.9.1/lib/python3.9/site-packages/lutris/gui/application.py", line 29, in <module>
    gi.require_version("Gdk", "3.0")
  File "/gnu/store/8wb8fmigxapchp6hhm274laljpp8s9x3-python-pygobject-3.40.1/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gdk not available
``` 

Could you please help me?

### How to Reproduce

1. Install Guix
2. Create `lutris.scm`
```
(define-module (lutris)
  #:use-module (gnu packages)
  #:use-module (guix packages)
  #:use-module (guix git-download)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages python-web)
  #:use-module (gnu packages xml)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system python)
  #:use-module ((guix licenses) #:prefix license:))

(define-public lutris
  (package
    (name "lutris")
    (version "0.5.9.1")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
	   (url "https://github.com/lutris/lutris")
	   (commit (string-append "v" version))))
       (sha256
        (base32
         "1v9ml5s17brr9hryc58y8cpga5li9y7hxi0zsfpm4v4aw2fwjhya"))))
    (build-system python-build-system)
	(arguments
	; Disable tests due to:
	; attempts to read distro
        ; needs to open /etc/ld.so.cache
        ; attempts to access GPU
	`(#:tests? #f
	  #:phases
	 (modify-phases %standard-phases
	  (add-before 'check 'home
	  (lambda* _
	  (setenv "HOME" "tmp"))))))
    (propagated-inputs
     (list gtk+ python python-pygobject python-pyaml python-pygobject python-evdev python-requests
	 python-magic python-lxml))
    (home-page
     "https://github.com/lutris/lutris")
    (synopsis
     "Lutris helps you install and play video games from all eras and from most
	 gaming systems")
    (description
     "")
    (license license:gpl3+)))
```
3. Run 'guix build -L. lutris'

### Expected behavior

Lutris starts

### Log output

```shell
Lutris package is not running yet :-(
```

### System Information

```shell
Lutris package is not running yet :-(
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by podiki** [comment]
I believe this is issues with how to set some paths in Guix. From my work on it running Lutris is fine, but likely needs our FHS sandboxing (from nonguix) to properly install/run games. I think it should be quite doable with what we have for Steam already, but I haven't had a chance to fully combine the work. I think the hard stuff is mostly figured out (I hope), other than making the Steam container more easily usable to stick Lutris in there.

https://gitlab.com/podiki/guix-pod/-/blob/main/lutris-wip.scm (very rough WIP)

https://gitlab.com/nonguix/nonguix/-/blob/master/nongnu/packages/steam-client.scm (working Steam from nonguix that should have the container ingredients needed)

**Comment by strycore** [comment]
Is Lutris available in Guix now? 

Also if there's a maintainer for Guix who wants to be added to the email list I have for distro maintainers, please get in touch with me.

**Comment by podiki** [comment]
@strycore I have not had a chance to work on it further, but did add an FHS container to Guix which should make it possible (haven't tried) to directly run Lutris without building ourselves. Over at Nonguix some recent changes are moving to making the Steam container more extensible and usable for other programs which should make a Lutris package easier, but again haven't tried yet.

Will update here if anything changes.
