### ISSUE TITLE
Is the libretro runner completely borked? Let's find out!!

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#426]
installed libretro fvia lutris, added a game (mario kart 64) and tried to download the core, and got this error:

```
Traceback (most recent call last):
  File "/home/user01/src/lutris/lutris/gui/lutriswindow.py", line 533, in on_game_run
    self.running_game.play()
  File "/home/user01/src/lutris/lutris/game.py", line 157, in play
    if not self.prelaunch():
  File "/home/user01/src/lutris/lutris/game.py", line 136, in prelaunch
    installed = self.runner.install_dialog()
  File "/home/user01/src/lutris/lutris/runners/runner.py", line 209, in install_dialog
    return self.install(version=version)
  File "/home/user01/src/lutris/lutris/runners/libretro.py", line 110, in install
    super(libretro, self).install(version, downloader, callback)
  File "/home/user01/src/lutris/lutris/runners/runner.py", line 268, in install
    self.name, self.arch
lutris.runners.RunnerInstallationError: libretro is not available for the x86_64 architecture
```

**Comment by telanus** [comment]
Also Libretro seems to no longer work, setup a few games and in it, works in 0.4.1 but no linger on git

**Comment by strycore** [comment]
Does the latest commit fixes this issue?

**Comment by telanus** [comment]
it works better :smile_cat: 

but if you don't have the core manually installed, it will run and silently exit without any info why

**Comment by strycore** [comment]
uh?
On my end, if the core isn't installed, it will download it. Are you sure you're not doing something funky?

**Comment by strycore** [comment]
what was the problem after all?

**Comment by telanus** [comment]
don't know, didn't work, and then suddenly decided to work
