### ISSUE TITLE
Game options not appearing. No right click menu or options at bottom of Lutris

### ISSUE THREAD

**Issue by rhysday** [lutris/lutris#4267]
### Bug description

After I did a Arch system update I no longer am able to access options in Lutris for installed games.

When I right click on Star Citizen nothing happens. I can run the game but there are no buttons/options either at the bottom of the Lutris window. 

Running version 0.5.10.1 of Lutris

### How to Reproduce

1. Open Lutris
2. Right click on installed game
3. Nothing happens

### Expected behavior

I want to access the config options for a specific game but can't.

### Log output

```shell
2022-05-11 12:32:10,612: Starting Lutris 0.5.10.1
2022-05-11 12:32:10,644: No folder at /home/me/.local/share/lutris/runners/retroarch/
2022-05-11 12:32:10,684: Using NVIDIA drivers 510.68.02 for x86_64
2022-05-11 12:32:10,684: GPU: NVIDIA GeForce GTX 1070
2022-05-11 12:32:10,684: GPU: 10DE:1B81 1462:3301 (nvidia drivers)
2022-05-11 12:32:10,735: Startup complete
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/lutriswindow.py", line 399, in update_revealer
    self.game_bar = GameBar(game, self.game_actions, self.application)
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 61, in __init__
    self.update_view()
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 86, in update_view
    self.play_button = self.get_play_button()
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 226, in get_play_button
    popover = self.get_popover(self.get_game_buttons(), popover_button)
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/game_bar.py", line 233, in get_game_buttons
    displayed = self.game_actions.get_displayed_entries()
  File "/usr/lib/python3.10/site-packages/lutris/game_actions.py", line 141, in get_displayed_entries
    and not steam_shortcut.shortcut_exists(self.game)
  File "/usr/lib/python3.10/site-packages/lutris/util/steam/shortcut.py", line 42, in shortcut_exists
    with open(shortcut_path, "rb") as shortcut_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/.local/share/Steam/userdata/373738888/config/shortcuts.vdf'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/views/base.py", line 52, in popup_contextual_menu
    self.contextual_menu.popup(event, game_actions)
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/contextual_menu.py", line 53, in popup
    displayed = game_actions.get_displayed_entries()
  File "/usr/lib/python3.10/site-packages/lutris/game_actions.py", line 141, in get_displayed_entries
    and not steam_shortcut.shortcut_exists(self.game)
  File "/usr/lib/python3.10/site-packages/lutris/util/steam/shortcut.py", line 42, in shortcut_exists
    with open(shortcut_path, "rb") as shortcut_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/.local/share/Steam/userdata/373738888/config/shortcuts.vdf'
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.17.5-arch1-2
Desktop:         Not found
Display Server:  tty

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 2700X Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             62.8 GB
Swap:            32.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.68.02
OpenGL Core:     4.6.0 NVIDIA 510.68.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.68.02
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by rhysday** [comment]
When starting Lutris I also get the error pop up: "[Errno 2] No such file or directory: '/home/me/.local/share/Steam/userdata/373738888/config/shortcuts.vdf'"

**Comment by rhysday** [comment]
Why would Lutris be looking for a file in my Steam folder anyway?? I only use Lutris for Star Citizen which doesn't even use Steam.

**Comment by telanus** [comment]
Looks like Lutris now rely on shortcuts.vdf to see if Steam have any games. But unfortunately, for some reason, it was accepted that every Linux install will have this file laying around, and no fallback was added for those who don't have this file.

Even if you do have steam installed the likelihood of you having this file is minimal, as it's only use, that I've seen, is for steam to document user added non-steam games.  IE: https://developer.valvesoftware.com/wiki/Add_Non-Steam_Game 

> Non-Steam Games are saved in the file: <<Steam Installation>>\userdata\<<User ID>>\config\shortcuts.vdf. 

@strycore

**Comment by telanus** [comment]
OK. This was fixed with https://github.com/lutris/lutris/commit/7a8a71d3005d9b5d118d0f48c62e025ae47aabff

**Comment by rhysday** [comment]
Yep fixed. Cheers!
