### ISSUE TITLE
[Feature request] Authenticate to services using default browser

### ISSUE THREAD

**Issue by pietrygamat** [lutris/lutris#4280]
I was wandering what it would take to allow Lutris to utilize browser in order to login to services like Epic Games Store / GOG / Origin / Ubisoft Connect / Humble Bundle.

Currently, when I want to login or refresh the connection, I have to use the build-in browser and go through full login flow (including copying password from password manager and obtain MFA token from email/mobile). This should not be necessary in most cases, as I am most likely already signed in to the service in my default browser. This could also potentially save Lutris some problems with crashes that do sometimes occur during login flows to all the mentioned services.

**Comment by strycore** [comment]
I don't think this is technically feasible, Lutris can't just read cookies or authentication credentials from any random browser. 
If those APIs had OAuth support, it would be an entirely different story. None of those APIs are public, they are built for each respective game client. In order to use them, we have to get the authentication details from somewhere we can access, which is the internal webkit2 browser.

That said, any software capable of writing the authentication credentials in the lutris cache folder would do the job. Maybe the solution is to have a Firefox/Chrome extension that can handle that? I'm not sure browser extensions are allowed to write to random files in the home directory.

**Comment by strycore** [comment]
Pretty much all the integrations are revere engineered, with a lot based on the existing integrations for GOG Galaxy. The problem here is a feasibility issue, I'm not against it. It would solve the problems we currently have with Humble Bundle and Origin.

**Comment by pw-64** [comment]
I'm not sure if I should open a new issue for my problem, because I think this might solve it. I cannot log into the epic games application:
- Press the start triangle in the sidebar for Sources -> Epic Games
- Epic Games launches
- I press continue with xbox/google/...
- It shows the "complete your login in your browser" screen but a browser window is never launched.

wine-ge-8-26-x86_64
Lutris 0.5.16 from the Ubuntu (22.04) software store
Epic games installer msi 15.17.1

IIRC it is Heroic that gives you a login link which you paste in your browser, then you give it the auth code once logged in; could this be possible for Lutris?

**Comment by ninetailedtori** [comment]
Yea I'm physically un*able* to log into anything due to the browser internally not supporting security keys and other auth lmfao. It would be cool to get an option to launch the oath request, then paste the success token uri back into the app to be read and then logged.

**Comment by ninetailedtori** [comment]
```
User not authenticated to EA

Traceback (most recent call last):

  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)

  File "/usr/lib/python3.13/site-packages/lutris/services/base.py", line 144, in do_reload
    self.load()
    ~~~~~~~~~^^

  File "/usr/lib/python3.13/site-packages/lutris/services/ea_app.py", line 260, in load
    user_id, _persona_id, _user_name = self.get_identity()
                                       ~~~~~~~~~~~~~~~~~^^

  File "/usr/lib/python3.13/site-packages/lutris/services/ea_app.py", line 234, in get_identity
    identity_data = self._request_identity()

  File "/usr/lib/python3.13/site-packages/lutris/services/ea_app.py", line 228, in _request_identity
    headers=self.get_auth_headers(),
            ~~~~~~~~~~~~~~~~~~~~~^^

  File "/usr/lib/python3.13/site-packages/lutris/services/ea_app.py", line 299, in get_auth_headers
    raise RuntimeError("User not authenticated to EA")

RuntimeError: User not authenticated to EA

Lutris log:
[INFO:2025-01-29 17:30:46,048:application]: Starting Lutris 0.5.18
[INFO:2025-01-29 17:30:46,219:startup]: "card1" is NVIDIA GeForce RTX 3080 Ti (10de:2208 10de:1535 nvidia) Driver 565.77
[WARNING:2025-01-29 17:30:46,748:base]: Tried to get auth status while login in progress
[WARNING:2025-01-29 17:30:46,829:base]: Tried to get auth status while login in progress
[WARNING:2025-01-29 17:30:46,830:base]: Tried to get auth status while login in progress
[ERROR:2025-01-29 17:30:46,847:style_manager]: Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/style_manager.py", line 74, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
[WARNING:2025-01-29 17:30:48,708:base]: Tried to get auth status while login in progress
[ERROR:2025-01-29 17:31:21,336:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x706b08fbf4c0>: <class 'RuntimeError'> User not authenticated to EA
[WARNING:2025-01-29 17:31:29,014:base]: Tried to get auth status while login in progress
[WARNING:2025-01-29 17:31:29,015:base]: Tried to get auth status while login in progress
[ERROR:2025-01-29 17:32:01,050:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x706b08fbede0>: <class 'RuntimeError'> User not authenticated to EA
```
I'm not honestly sure at this point what happened here.

**Comment by strycore** [comment]
I've done the copy / paste login for Humble so it's should be possible to do for other services. Given how little time I have to spend on Lutris these days, there is zero chance that I personally focus on this problem, but if someone wants to tackle this, please don't clutter the UI for regular users and hide this feature under an environment variable or something.

**Comment by ninetailedtori** [comment]
It's worth saying, that if we had the ability to copy the website with a right click, and then paste it in a browser, then paste it back into lutris, like how I sometimes bypass oath incompatibilities with non-spec internal browsers, it would also work, given the OATH success token can easily just be copy pasted back into the browser. It's also worth stating, that lutris's internal browser doesn't even deny a request, let's say signing in through mfa through google, when it needs to request a passkey. It just hangs...all in all, launch the OATH request out of the browser, along with a textbox that lets users copy the link if it didn't launch right, then sign in, then launch back into the app, would work. You could also generate a mime listing for the request type to allow some "open the success link in lutris directly" functionality like other apps do.

**Comment by ninetailedtori** [comment]
I don't mind writing a PR for it if you want btw? Unless someone's working on something for this already.

**Comment by strycore** [comment]
> I don't mind writing a PR for it if you want btw? Unless someone's working on something for this already.

That would be nice! If you could generalize the Humble Bundle login process to support other services using login. 

Recently, I haven't had any trouble signing in Humble so we should change the UI around this and revert to the regular login dialog. On that dialog, we can add a link saying "Trouble signing in?" or something similar that opens a dialog explaining the browser method.

**Comment by ninetailedtori** [comment]
I've got some code written, but...I'm not sure how to test it without it using the system-managed scripts to test? Sorry I'm so new to this repo still haha~ https://github.com/ninetailedtori/lutris

**Comment by strycore** [comment]
I don't know what you're trying to do but it seems complicated. I wouldn't work on Lutris at all if I needed to ninja build it between every little change. 

Just run it from the source directory with `./bin/lutris`.

idk what "system scripts" are so I can't help you on that one.

**Comment by ninetailedtori** [comment]
> I don't know what you're trying to do but it seems complicated. I wouldn't work on Lutris at all if I needed to ninja build it between every little change.
> 
> Just run it from the source directory with `./bin/lutris`.
> 
> idk what "system scripts" are so I can't help you on that one.

No, I mean, I want it to use my WebConnectDialog I wrote, but I'm not sure it's using the one that's in my system managed files, or the one in the cloned repo directory.

**Comment by strycore** [comment]
Oh, if you run Lutris from the source tree, it won't be a problem. Don't `ninja install` your development version, that will create a mess. Leave /usr to the version of Lutris installed by your package manager.
