### ISSUE TITLE
Lutris not starting from command line

### ISSUE THREAD

**Issue by DerScherenmann** [lutris/lutris#4287]
### Bug description

Lutris won't start from command line, stops with

5408 IOT instruction (core dumped)

### How to Reproduce

1. Open a Terminal
2. start lutris with 'lutris' or 'lutris -d'
3. Lutris exits after searching for runtime updates

### Expected behavior

Lutris opens a new window.

What I already tried to fix this bug:

sudo update-mime-database /usr/bin/mine

sudo pacman -Qqn | sudo pacman -S -

### Log output

```shell
INFO     2022-05-17 11:51:58,673 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-05-17 11:51:58,699 [libretro.get_libretro_cores:24]:No folder at /home/broesel233/.local/share/lutris/runners/retroarch/
DEBUG    2022-05-17 11:51:58,706 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-05-17 11:51:58,731 [startup.check_driver:57]:Using NVIDIA drivers 515.43.04 for x86_64
INFO     2022-05-17 11:51:58,732 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 2070 SUPER
INFO     2022-05-17 11:51:58,732 [startup.check_driver:77]:GPU: 10DE:1E84 1462:C729 (nvidia drivers)
WARNING  2022-05-17 11:51:58,733 [startup.check_vulkan:136]:Vulkan is not available or your system isn't Vulkan capable
INFO     2022-05-17 11:51:58,746 [startup.update_runtime:213]:Startup complete

(lutris:5953): Gtk-WARNING **: 11:51:58.777: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
DEBUG    2022-05-17 11:51:58,828 [lutriswindow.update_store:437]:Showing 21 games
ERROR    2022-05-17 11:51:58,829 [utils.get_pixbuf:51]:Unable to load icon from image /home/broesel233/.cache/lutris/banners/among-us.jpg
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/lutriswindow.py", line 732, in on_sidebar_changed
    self.redraw_view()
  File "/usr/lib/python3.10/site-packages/lutris/gui/lutriswindow.py", line 576, in redraw_view
    self.update_store()
  File "/usr/lib/python3.10/site-packages/lutris/gui/lutriswindow.py", line 441, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.10/site-packages/lutris/gui/views/store.py", line 161, in add_game
    game.get_pixbuf() if settings.SHOW_MEDIA else None,
  File "/usr/lib/python3.10/site-packages/lutris/gui/views/store_item.py", line 107, in get_pixbuf
    return get_pixbuf(image_path, self.service_media.size, is_installed=self.installed)
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/utils.py", line 61, in get_pixbuf
    transparent_pixbuf = get_overlay(overlay, size).copy()
  File "/usr/lib/python3.10/site-packages/lutris/gui/widgets/utils.py", line 122, in get_overlay
    transparent_pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(overlay_path, width, height)
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognise the image file format for file “/usr/share/lutris/media/unavailable.png” (3)
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
[1]    5953 IOT instruction (core dumped)  lutris -d
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.17.7-arch1-2
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.6 GB
Swap:            4.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 515.43.04
OpenGL Core:     4.6.0 NVIDIA 515.43.04
OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.43.04
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Looks like you're missing some dependencies that allow Gdk to load image formats. Lutris is complaining about loading both pngs and jpgs. 

Try installing a Gtk program that handles images like Gimp and see if it solves this issue.

Lutris is also complaining that Vulkan isn't supported, which means you're also missing a dependency for Vulkan.

**Comment by DerScherenmann** [comment]
I have Gimp installed and vulkan is woring if vulkan application is started over Steam. What's also confusing me is that this error only appears if Lutris is launched in a terminal and not if launched from desktop.

**Comment by gilmorem560** [comment]
@strycore I don't think so in this case.

I don't do anything with Lutris but came across this thread while searching for an explanation for that GDK-Pixbuf error that seems to be your root cause here.

Since then I solved that problem.

GDK-Pixbuf will present a message to the tune of "Couldn’t recognise the image file format for file \<path\>" when the determination of the file type fails. This is done by comparing against the MIME data currently installed on the host machine. The specifications for this data are here: https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html

The short of it is $XDG_DATA_DIR/mime (usually /usr/share/mime) must be populated with the data from the shared-mime-info package provided by https://gitlab.freedesktop.org/xdg/shared-mime-info/

YMMV with your own distro, but in the case of installing the package from source, you must setup the meson build with this option:

```
-Dupdate-mimedb=true
```

These MIME types then indicate to GDK-Pixbuf which module to load.  On my system, these modules are in /usr/lib/gdk-pixbuf, give or take some version information on the folder name. Note, GDK-Pixbuf allows for both static and dynamic decoders, so just because you don't see a given format in this folder, that doesn't mean it isn't supported. It could be packed in, as is the case by default with the jpeg and png decoders, although decoders can be shunted into either collection at build time.

At this point, so long as the module is statically or dynamically linked,  XDG_DATA_DIR is set properly, and the mime folder is contained and populated within, then this error should disappear.

Of course, these instructions apply to a UNIX system with proper XDG support. I don't know the specifics for macOS or Windows, but hopefully this matter of missing MIME data triggering a "Couldn’t recognise the image file format for file \<path\>" error is universal.

**Comment by strycore** [comment]
Thanks for looking into this.  Updating the Meson build to add this option should be easy enough

**Comment by gilmorem560** [comment]
Thing is, that option is an option in the shared-mime-info package. What would probably work best is checking for the presence of data a coalese of ($XDG_DATA_DIR/mime, /usr/share/mime). If no such data is present, then GDK down the line will bark about it.

The really real answer is GDK-Pixbuf needs to do better at illuminating the actual problem, saying you can't load something could point to a wide array of issues, saying you couldn't find a mime data representation of the file and *therefore* you can't load something actually gives someone a diagnostic to chew on. You're just the latest to be tripped up by that poor error reporting in GDK-Pixbuf.
