### ISSUE TITLE
Can't launch lutris on Arch Linux via Open-Source Nvidia Driver (root caused)

### ISSUE THREAD

**Issue by blueOkiris** [lutris/lutris#4288]
### Bug description

Something has changed with the versioning on nvidia's open-source drivers, so this code in /usr/lib/<python version>/site-packages/lutris/util/graphics/driver.py:

```
def get_nvidia_driver_info():
    """Return information about NVidia drivers"""
    version_file_path = "/proc/driver/nvidia/version"
    if not os.path.exists(version_file_path):
        return
    with open(version_file_path, encoding='utf-8') as version_file:
        content = version_file.readlines()
        nvrm_version = content[0].split(': ')[1].strip().split()
        return {
            'nvrm': {
                'vendor': nvrm_version[0],
                'platform': nvrm_version[1],
                'arch': nvrm_version[2],
                'version': nvrm_version[5],
                'date': ' '.join(nvrm_version[6:])
            }
        }
    return
```
doesn't work properly and causes lutris not to launch

The reading of `cat /proc/driver/nvidia/version/` is

```
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  515.43.04  Release Build  (archlinux-builder@archlinux)  
GCC version:  gcc version 12.1.0 (GCC) 
```

This causes an error later on at line 114: `major_version = int(driver_version.split(".")[0])` because the value being parsed is "for"

I can get a workaround for myself by hardcoding the version info (what I used to get system information), but I imagine others will stumble upon this as more people switch to the open driver, so it probably needs to be fixed properly.

### How to Reproduce

1. Install Arch, lutris, and the nvidia-open package
2. Try to launch lutris

### Expected behavior

Launch

### Log output

```shell
INFO     2022-05-17 09:33:59,656 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-05-17 09:33:59,677 [libretro.get_libretro_cores:24]:No folder at /home/dylan/.local/share/lutris/runners/retroarch/
DEBUG    2022-05-17 09:33:59,683 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-05-17 09:33:59,706 [startup.check_driver:57]:Using NVIDIA drivers for for Open
INFO     2022-05-17 09:33:59,706 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 3080 Laptop GPU
INFO     2022-05-17 09:33:59,706 [startup.check_driver:77]:GPU: 10DE:249C 1462:1305 (nvidia drivers)
INFO     2022-05-17 09:33:59,706 [startup.check_driver:77]:GPU: 8086:9A60 1462:1305 (i915 drivers)
INFO     2022-05-17 09:33:59,707 [drivers.is_outdated:108]:Added log 'driver_info': {'nvrm': {'vendor': 'NVIDIA', 'platform': 'UNIX', 'arch': 'Open', 'version': 'for', 'date': 'x86_64 515.43.04 Release Build (archlinux-builder@archlinux)'}}
INFO     2022-05-17 09:33:59,707 [drivers.is_outdated:110]:Added log 'driver_version': for
INFO     2022-05-17 09:33:59,707 [drivers.is_outdated:111]:Added log 'driver_version.split(".")[0]': for
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 409, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 156, in run_all_checks
    check_driver()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 81, in check_driver
    if drivers.is_outdated():
  File "/usr/lib/python3.10/site-packages/lutris/util/graphics/drivers.py", line 115, in is_outdated
    major_version = int(driver_version.split(".")[0])
ValueError: invalid literal for int() with base 10: 'for'
INFO     2022-05-17 09:33:59,707 [application.do_shutdown:885]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.17.7-arch1-2
Desktop:         i3
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.1 GB
Swap:            14.9 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 515.43.04
OpenGL Core:     4.6.0 NVIDIA 515.43.04
OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.43.04
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by blueOkiris** [comment]
Ah just saw that this is fixed in the latest lutris :)
