### ISSUE TITLE
lutris does not start on nvidia-"open" drivers

### ISSUE THREAD

**Issue by muchgitsuchwow** [lutris/lutris#4290]
### Bug description

* OS: Archlinux
* Lutris: `0.5.10.1`
* nvidia-open: `515.43.04-6`
* uname -r: `5.17.8-zen1-1-zen`

Startup stack:

```
2022-05-18 18:22:39,223: Starting Lutris 0.5.10.1
2022-05-18 18:22:39,274: Using NVIDIA drivers for for Open
2022-05-18 18:22:39,274: GPU: NVIDIA GeForce RTX 2060 SUPER
2022-05-18 18:22:39,274: GPU: 10DE:1F06 1043:870E (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 409, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 156, in run_all_checks
    check_driver()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 81, in check_driver
    if drivers.is_outdated():
  File "/usr/lib/python3.10/site-packages/lutris/util/graphics/drivers.py", line 112, in is_outdated
    major_version = int(driver_version.split(".")[0])
ValueError: invalid literal for int() with base 10: 'for'
2022-05-18 18:22:39,274: Shutting down Lutris
```

* `/proc/driver/nvidia/version` (nvidia-dkms-open)

```
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  515.43.04  Release Build  (archlinux-builder@archlinux)
GCC version:  gcc version 12.1.0 (GCC)
```

Everything the same, except in Archlinux using `nvidia-dkms` rather than `nvidia-open-dkms` package results in lutris starting up normally:

```
2022-05-18 18:32:34,129: Starting Lutris 0.5.10.1
2022-05-18 18:32:34,201: Using NVIDIA drivers 515.43.04 for x86_64
2022-05-18 18:32:34,201: GPU: NVIDIA GeForce RTX 2060 SUPER
2022-05-18 18:32:34,201: GPU: 10DE:1F06 1043:870E (nvidia drivers)
2022-05-18 18:32:36,237: Startup complete
```

* `/proc/driver/nvidia/version` (nvidia-dkms)

```
NVRM version: NVIDIA UNIX x86_64 Kernel Module  515.43.04  Tue Apr 26 15:52:32 UTC 2022
GCC version:  gcc version 12.1.0 (GCC)
```

On a final notice: Thanks for this nice peace of software!

### How to Reproduce

1. In Archlinux install nvidia-open{,-dkms}
2. Start `lutris` in terminal

### Expected behavior

The nvidia driver version parser is able to skip the string "Open" in `/proc/driver/nvidia/version`.

### Log output

```shell
2022-05-18 18:22:39,223: Starting Lutris 0.5.10.1
2022-05-18 18:22:39,274: Using NVIDIA drivers for for Open
2022-05-18 18:22:39,274: GPU: NVIDIA GeForce RTX 2060 SUPER
2022-05-18 18:22:39,274: GPU: 10DE:1F06 1043:870E (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 409, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 156, in run_all_checks
    check_driver()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 81, in check_driver
    if drivers.is_outdated():
  File "/usr/lib/python3.10/site-packages/lutris/util/graphics/drivers.py", line 112, in is_outdated
    major_version = int(driver_version.split(".")[0])
ValueError: invalid literal for int() with base 10: 'for'
2022-05-18 18:22:39,274: Shutting down Lutris
```
```


### System Information

```shell
Not possible due to lutris not starting up. Sorry.
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by muchgitsuchwow** [comment]
The current parser on the nvidia-open /proc file creates:

```
{'nvrm': {'vendor': 'NVIDIA', 'platform': 'UNIX', 'arch': 'Open', 'version': 'for', 'date': 'x86_64 515.43.04 Release Build (archlinux-builder@archlinux)'}}
```

Not sure how to fix this in a way that it doesn't break other users setups.

**Comment by strycore** [comment]
We merged in a fix for this recently, can you please test the latest git version?

**Comment by muchgitsuchwow** [comment]
-git works and features the same idea I would have thought of to address this. 

Should this issue kept open until the fix has been released, to "warn" others? I did not lookup git history or in closed issues, just in open ones. Clear label, fixed waiting for release, dunno.

Thanks anyway!

**Comment by aaronp24** [comment]
If it helps, you can read the version string directly from `/sys/module/nvidia/version` to avoid having to parse it out of `/proc/driver/nvidia/version`.

**Comment by ElCoyote27** [comment]
I'm also seeing this on Fedora35 with the non-open drivers:
```
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  515.65.01  Wed Jul 20 14:00:58 UTC 2022
GCC version:  gcc version 11.3.1 20220421 (Red Hat 11.3.1-2) (GCC) 

```

**Comment by ElCoyote27** [comment]
On Fedora 35 and I see the error whenever installing any game.
'lutris -d' shows:

```
$ lutris -d

(lutris:27757): Gtk-WARNING **: 16:18:54.182: Theme parsing error: gtk.css:1:8: Expected a valid selector

(lutris:27757): Gtk-WARNING **: 16:18:54.182: Theme parsing error: gtk.css:11:2: Expected a valid selector
INFO     2022-08-06 16:18:54,195 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-08-06 16:18:54,206 [libretro.get_libretro_cores:24]:No folder at /export/home/raistlin/.local/share/lutris/runners/retroarch/
INFO     2022-08-06 16:18:54,219 [startup.check_driver:57]:Using NVIDIA drivers 515.65.01 for x86_64
INFO     2022-08-06 16:18:54,219 [startup.check_driver:61]:GPU: NVIDIA RTX A4000 Laptop GPU
INFO     2022-08-06 16:18:54,219 [startup.check_driver:77]:GPU: 10DE:24B7 17AA:22D8 (nvidia drivers)
INFO     2022-08-06 16:18:54,264 [startup.update_runtime:213]:Startup complete
DEBUG    2022-08-06 16:18:54,308 [lutriswindow.update_store:437]:Showing 1 games
DEBUG    2022-08-06 16:18:58,787 [application.show_window:332]:Showing window AddGamesWindow{}
DEBUG    2022-08-06 16:19:04,938 [http.get:83]:GET https://lutris.net/api/games?search=guild+wards&with-installers=True
DEBUG    2022-08-06 16:19:06,186 [http.get:83]:GET https://lutris.net/api/games?search=guild+wars&with-installers=True
DEBUG    2022-08-06 16:19:07,770 [api.get_game_installers:160]:Fetching installer https://lutris.net/api/installers/guild-wars-2
DEBUG    2022-08-06 16:19:07,771 [http.get:83]:GET https://lutris.net/api/installers/guild-wars-2
DEBUG    2022-08-06 16:19:08,034 [application.show_window:332]:Showing window InstallerWindowguild-wars-2
DEBUG    2022-08-06 16:19:08,035 [application.on_app_window_destroyed:350]:Removed window AddGamesWindow{}
DEBUG    2022-08-06 16:19:09,552 [displayconfig.get_current_resolution:624]:Retrieving current resolution
ERROR    2022-08-06 16:19:09,552 [displayconfig.get_current_resolution:627]:Could not retrieve the current display mode
DEBUG    2022-08-06 16:19:15,662 [interpreter.get_extras:159]:Checking if service provide extra files
DEBUG    2022-08-06 16:19:15,662 [installer.prepare_game_files:146]:No service to retrieve files from
DEBUG    2022-08-06 16:19:17,360 [downloader.start:65]:⬇ https://s3.amazonaws.com/gw2cdn/client/branches/Gw2Setup-64.exe
DEBUG    2022-08-06 16:19:17,363 [downloader.start:65]:⬇ https://github.com/Zeioth/zeioth-lutris/raw/master/game-installers/guild-wars-2/gw2-d9vk-shader-cache-0.0.2.zip
DEBUG    2022-08-06 16:19:18,480 [downloader.download_cb:125]:Finished downloading https://github.com/Zeioth/zeioth-lutris/raw/master/game-installers/guild-wars-2/gw2-d9vk-shader-cache-0.0.2.zip
INFO     2022-08-06 16:19:18,866 [file_box.on_download_complete:252]:Download completed
DEBUG    2022-08-06 16:19:18,867 [files_box.on_file_available:93]:gw2shadercache is available
DEBUG    2022-08-06 16:19:19,335 [downloader.download_cb:125]:Finished downloading https://s3.amazonaws.com/gw2cdn/client/branches/Gw2Setup-64.exe
INFO     2022-08-06 16:19:19,363 [file_box.on_download_complete:252]:Download completed
DEBUG    2022-08-06 16:19:19,363 [files_box.on_file_available:93]:gw2installer is available
INFO     2022-08-06 16:19:19,364 [files_box.on_file_available:99]:All files available
INFO     2022-08-06 16:19:19,364 [installerwindow.on_files_available:463]:All files are available, continuing install
DEBUG    2022-08-06 16:19:19,366 [interpreter._iter_commands:317]:Installer command: {'extract': {'dst': '$GAMEDIR', 'file': 'gw2shadercache', 'format': 'zip'}}
ERROR    2022-08-06 16:19:19,369 [jobs.target:36]:Error while completing task <bound method CommandsMixin.extract of <interpreter.ScriptInterpreter object at 0x7ff99f90d280 (lutris+installer+interpreter+ScriptInterpreter at 0x55d88a334f40)>>: <class 'ValueError'> invalid literal for int() with base 10: ''
  File "/usr/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/lutris/installer/commands.py", line 188, in extract
    dest_path = self._substitute(data["dst"])
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 420, in _substitute
    return system.substitute(template_string, self._get_string_replacements())
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 400, in _get_string_replacements
    "RESOLUTION_WIDTH_HEX": hex(int(self.current_resolution[0])),
ERROR    2022-08-06 16:19:19,370 [interpreter._iter_commands:302]:Last install command failed, show error

```

**Comment by ElCoyote27** [comment]
I just tried the git version and it worked! Can't wait for a new release...
