### ISSUE TITLE
`KeyError: 'game_slug'` when installing local .yaml

### ISSUE THREAD

**Issue by haluzpav** [lutris/lutris#4293]
### Bug description

I've copied [this YAML installer](https://lutris.net/games/install/21163/view) to a local file. However when I try to launch it, I get an error, see the log.

Is the installer wrong? Why does the "Download" button on the website download only JSON? Why does [your tutorial](https://github.com/lutris/lutris/blob/master/docs/installers.rst) say we should use YAML? ("_Local installers can be launched from the CLI with lutris -i /path/to/file.yaml._") Why are there both YAML and JSON, seemingly doing the same thing? I'm honestly confused. 

The installer in JSON format works fine in Lutris. (well, actually, it doesn't install properly, that's what I'm trying to figure out, but that's another issue)

Same issue, already closed: #3811

### How to Reproduce

1. Go to https://lutris.net/games/install/21163/view
2. Copy YAML to local file
3. Do `lutris -i local.yaml`
4. See the error in the log

### Expected behavior

The installer opens in Lutris.

### Log output

```shell
~ ❭ lutris -d -i world-of-tanks-all-regions.yaml 
INFO     2022-05-21 19:38:06,650 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-05-21 19:38:06,663 [libretro.get_libretro_cores:24]:No folder at /home/rooster/.local/share/lutris/runners/retroarch/
INFO     2022-05-21 19:38:06,679 [startup.check_driver:65]:Running AMD Mesa driver 22.0.3 on AMD Radeon RX 6800 XT (sienna_cichlid, LLVM 14.0.0, DRM 3.44, 5.17.6-300.fc36.x86_64) (0x73bf)
INFO     2022-05-21 19:38:06,679 [startup.check_driver:77]:GPU: 1002:73BF 1462:3953 (amdgpu drivers)
INFO     2022-05-21 19:38:06,702 [startup.update_runtime:213]:Startup complete
DEBUG    2022-05-21 19:38:06,761 [lutriswindow.update_store:437]:Showing 2 games
DEBUG    2022-05-21 19:38:06,795 [__init__.read_script:14]:Loading script(s) from /home/rooster/Downloads/world-of-tanks-all-regions.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 598, in do_command_line
    self.show_installer_window(installers)
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 337, in show_installer_window
    self.show_window(
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 318, in show_window
    window_key = str(window_class.__name__) + self.get_window_key(**kwargs)
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 303, in get_window_key
    return kwargs["installers"][0]["game_slug"]
KeyError: 'game_slug'
```

### System Information

```shell
[System]
OS:              Fedora Linux 36 
Arch:            x86_64
Kernel:          5.17.6-300.fc36.x86_64
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (sienna_cichlid, LLVM 14.0.0, DRM 3.44, 5.17.6-300.fc36.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.0.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.0.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.0.3
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by haluzpav** [comment]
Ok, I figured it out. The JSON script that's *shown* on the website is different than the one *downloaded*. 

BTW, I also [figured out](https://forums.lutris.net/t/world-of-tanks-fails-to-install/15099/2) how to make the installer install properly. But I won't be posting it to the Lutris website, because it seems it requires *yet another* format of installer script?!

Rant over. :smile: Sorry for spam.
