### ISSUE TITLE
Vortex Mod Manager crashing on startup

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#4311]
Hello. Sorry if there are some things I miss while writing this, as I'm brand new to GitHub. I installed Vortex Mod Manager from the Lutris website (https://lutris.net/games/vortex-mod-manager/) and everything seemed to complete without error. However, once I disconnected my internet in order to start up Vortex and disable auto-updates, Vortex was running extremely slowly. I did seem to be able to disable auto-updates, but it froze afterwards. 

I decided to try to restart it to see if I could get it to run again. When trying to start it in Lutris, hitting play makes it change to "Stop" as if it's starting up, but it changes right back to "Play" after a few seconds. No windows open during this time period. I saw some posts talking about starting it manually, and I tried the command `env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/1`, which is the command the desktop shortcut uses, but it's the same result without any output in the terminal. Reinstalling Vortex results in the same issue. Any help would be appreciated.

**Comment by Thermatix** [comment]
> @KassNB @egetin try my installer from [Nexus-Mods/Vortex#10686](https://github.com/Nexus-Mods/Vortex/issues/10686#issuecomment-1161352635) instead. The installer available on the Vortex mm Lutris page is outdated. I submitted my installer, but it hasn't been published.
> 
> > Vortex logs from Lutris:
> > ```
> > lutris-wrapper: Vortex Mod Manager
> > Started initial process 3099 from /home/erkka/.local/share/lutris/runners/wine/lutris-6.14-4-x86_64/bin/wine /home/erkka/Games/vortex-mod-manager/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe
> > Start monitoring process.
> > esync: up and running.
> > 
> > net.js:329
> >       err = this._handle.open(fd);
> >                          ^
> > 
> > Error: EINVAL: invalid argument, uv_pipe_open
> >     at new Socket (net.js:329:26)
> >     at createWritableStdioStream (internal/bootstrap/switches/is_main_thread.js:67:18)
> >     at process.getStdout [as stdout] (internal/bootstrap/switches/is_main_thread.js:122:12)
> >     at Object.<anonymous> (electron/js2c/browser_init.js:185:793)
> >     at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3714)
> >     at __webpack_require__ (electron/js2c/browser_init.js:1:128)
> >     at electron/js2c/browser_init.js:1:1200
> >     at electron/js2c/browser_init.js:1:1267
> >     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:277:7)
> >     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10) {
> >   errno: -4071,
> >   code: 'EINVAL',
> >   syscall: 'uv_pipe_open'
> > }
> > Monitored process exited.
> > Initial process has exited (return code: 256)
> > Exit with return code 256
> > ```
> 
> This has already been reported to Vortex. See [Nexus-Mods/Vortex#9629 (comment)](https://github.com/Nexus-Mods/Vortex/issues/9629#issuecomment-1030657368)

But I actually got around this by running Vortex within a Windowed virtual desktop, it now works, though the desktop thing is a bit annoying, I can live with that.
