### ISSUE TITLE
ImportError when launching Morrowind on Steam Deck with the Flatpak version

### ISSUE THREAD

**Issue by loki-47-6F-64** [lutris/lutris#4313]
When launching `The Elder Scrolls III: Morrowind GOTY Edition` using the `Linux` runner an `ImportError` occurs in `lutris/util/log.py`:

```
(deck@Loki-deck ~)$ "/usr/bin/flatpak" run net.lutris.Lutris "lutris:rungame/the-elder-scrolls-iii-morrowind-goty-edition"
Gtk-Message: 12:02:05.195: Failed to load module "canberra-gtk-module"
2022-06-08 12:02:05,982: Starting Lutris 0.5.10.1
2022-06-08 12:02:06,024: No folder at /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/retroarch/
2022-06-08 12:02:06,082: Running AMD Mesa driver 21.3.8 on AMD VANGOGH (DRM 3.45.0, 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a, LLVM 12.0.1) (0x163f)
2022-06-08 12:02:06,082: GPU: 1002:163F 1002:0123 (amdgpu drivers)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
2022-06-08 12:02:06,190: Startup complete
Traceback (most recent call last):
  File "/app/share/lutris/bin/lutris-wrapper", line 16, in <module>
    from lutris.util.log import logger
  File "/app/lib/python3.9/site-packages/lutris/util/log.py", line 10, in <module>
    from gi.repository import GLib
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref
2022-06-08 12:02:06,459: No file /tmp/lutris-329a8791-a573-4baa-b7d3-1d823fb51265
2022-06-08 12:02:08,373: Game still running (state: running)
2022-06-08 12:02:08,373: Stopping The Elder Scrolls III: Morrowind GOTY Edition (linux)
2022-06-08 12:02:08,375: The game has run for a very short time, did it crash?
2022-06-08 12:02:08,376: Shutting down Lutris
```

*Setup*
* Steam Deck
* Flatpak version of Lutris
* `flatpak install org.gnome.Platform.Compat.i386 org.freedesktop.Platform.GL32.default org.freedesktop.PlatformGL.default`

After some debugging it became clear the issue is the following line:
`from gi.repository import GLib`

After replacing the folliwing lines in `lutris/util/log.py`:
```
from gi.repository import GLib

# Used to store log buffers for games.
LOG_BUFFERS = {}

CACHE_DIR = os.path.realpath(os.path.join(GLib.get_user_cache_dir(), "lutris"))
```
with
```
# Used to store log buffers for games.
LOG_BUFFERS = {}

CACHE_DIR = os.path.realpath(os.path.join("/var/.cache/lutris"))
```
The game will run fine.

**Comment by horatiog** [comment]
I have also been encountering this problem when running the same game, though I use Lutris in a distrobox container running on Fedora Kinoite. On my system, I found I had to edit the proposed solution to use my home directory cache dir:

`# Used to store log buffers for games.
LOG_BUFFERS = {}

CACHE_DIR = os.path.realpath(os.path.join(os.path.expanduser('~'), ".cache/lutris"))`

There's undoubtedly a better way to fix the problem while still following the XDG cache directory, but for the quick fix for my local system just hardcoding ~/.cache worked fine.

**Comment by e2002e** [comment]
Can you not make a pull request for your changes ? Still the same issue with openwm and game from gog.
