### ISSUE TITLE
mednafen crash on startup

### ISSUE THREAD

**Issue by dmp1ce** [lutris/lutris#432]
When I try to start my ROM I get the error below on the terminal. The ROM doesn't start.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lutris/gui/lutriswindow.py", line 533, in on_game_run
    self.running_game.play()
  File "/usr/lib/python3.5/site-packages/lutris/game.py", line 164, in play
    self.do_play(True)
  File "/usr/lib/python3.5/site-packages/lutris/game.py", line 172, in do_play
    gameplay_info = self.runner.play()
  File "/usr/lib/python3.5/site-packages/lutris/runners/mednafen.py", line 246, in play
    joy_ids = self.find_joysticks()
  File "/usr/lib/python3.5/site-packages/lutris/runners/mednafen.py", line 92, in find_joysticks
    ouput = output.split("\n")
TypeError: a bytes-like object is required, not 'str'
```

**Comment by strycore** [comment]
I'll fix that but note that mednafen is soon to be deprecated in favor of retroarch ;)
