### ISSUE TITLE
Lutris won't launch due to GPU version check error

### ISSUE THREAD

**Issue by Mobmaker55** [lutris/lutris#4338]
Running Lutris gives me this error:
```
 lutris
2022-06-22 16:39:47,346: Starting Lutris 0.5.10.1
2022-06-22 16:39:47,366: No folder at /home/mob/.local/share/lutris/runners/retroarch/
2022-06-22 16:39:47,386: Using NVIDIA drivers for for Open
2022-06-22 16:39:47,387: GPU: NVIDIA GeForce GTX 1660
2022-06-22 16:39:47,387: GPU: 10DE:2184 196E:1332 (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 409, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 156, in run_all_checks
    check_driver()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 81, in check_driver
    if drivers.is_outdated():
  File "/usr/lib/python3.10/site-packages/lutris/util/graphics/drivers.py", line 112, in is_outdated
    major_version = int(driver_version.split(".")[0])
ValueError: invalid literal for int() with base 10: 'for'
2022-06-22 16:39:47,387: Shutting down Lutris
```

My device is a Ryzen 5 5600x, B550 Motherboard, with an NVidia GeForce GTX 1660.
I am running Arch Linux, GNOME 42.2.

**Comment by danieljohnson2** [comment]
This looks a lot like #4270, which has a fix already in master, so the next Lutris should fix it.

You could give the master branch a try and see if that helps you.

**Comment by Mobmaker55** [comment]
Yep, that fixes it, thank you!
