### ISSUE TITLE
Lutris won't start

### ISSUE THREAD

**Issue by R1D3R175** [lutris/lutris#4376]
Hi, when I try to run Lutris I get the following error.
# Log
```
$ lutris 
2022-07-15 01:49:40,667: Starting Lutris 0.5.10.1
2022-07-15 01:49:40,688: No folder at /home/imagine/.local/share/lutris/runners/retroarch/
2022-07-15 01:49:40,714: Using NVIDIA drivers for for Open
2022-07-15 01:49:40,715: GPU: NVIDIA GeForce GTX 1650 with Max-Q Design
2022-07-15 01:49:40,715: GPU: 10DE:1F9D 1462:12F4 (nvidia drivers)
2022-07-15 01:49:40,715: GPU: 8086:9BC4 1462:12F4 (i915 drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 409, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 156, in run_all_checks
    check_driver()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 81, in check_driver
    if drivers.is_outdated():
  File "/usr/lib/python3.10/site-packages/lutris/util/graphics/drivers.py", line 112, in is_outdated
    major_version = int(driver_version.split(".")[0])
ValueError: invalid literal for int() with base 10: 'for'
2022-07-15 01:49:40,716: Shutting down Lutris
```
# Debugging
The issues lies in the `get_nvidia_driver_info()`, in the specific when splitting the lines of `/proc/driver/nvidia/version`.
```python
pprint(get_nvidia_driver_info())
{'nvrm': {'arch': 'Open',
          'date': 'x86_64 515.57 Release Build (archlinux-builder@)',
          'platform': 'UNIX',
          'vendor': 'NVIDIA',
          'version': 'for'}}
```

```
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  515.57  Release Build  (archlinux-builder@)  
GCC version:  gcc version 12.1.0 (GCC) 
```

```python
nvrm_version = content[0].split(': ')[1].strip().split()
pprint(nvrm_version)

# Output
['NVIDIA',
 'UNIX',
 'Open',
 'Kernel',
 'Module',
 'for',
 'x86_64',
 '515.57',
 'Release',
 'Build',
 '(archlinux-builder@)']

# Correct index should be 7 and not 5
```

# Workaround (my fix)
```python
def find_driver_version_index(to_search: list) -> (int | None):
    for index, value in enumerate(to_search):
        if '.' in value:
            return index

    return None


def get_nvidia_driver_info():
    """Return information about NVidia drivers"""
    version_file_path = "/proc/driver/nvidia/version"
    if not os.path.exists(version_file_path):
        return
    with open(version_file_path, encoding='utf-8') as version_file:
        content = version_file.readlines()
        nvrm_version = content[0].split(': ')[1].strip().split()
        return {
            'nvrm': {
                'vendor': nvrm_version[0],
                'platform': nvrm_version[1],
                'arch': nvrm_version[2],
                'version': nvrm_version[find_driver_version_index(nvrm_version)],
                'date': ' '.join(nvrm_version[6:])
            }
        }
    return
```

**Comment by danieljohnson2** [comment]
This looks like issue #4270, which has already got a fix merged.

Could you try the master branch? You need not install it, just clone it and run the bin/lutris script and see if that will start.

**Comment by ThisNekoGuy** [comment]
@danieljohnson2 It works with latest master

**Comment by danieljohnson2** [comment]
Excellent. I hope it works for @R1D3R175 also.

**Comment by danieljohnson2** [comment]
Well, nothing from @R1D3R175, but I think this is probably #4270, and so is fixed.
