### ISSUE TITLE
Ubuntu 22.04 Lutris gets stuck saying 'launching' when launching any game

### ISSUE THREAD

**Issue by thesocialproject** [lutris/lutris#4385]
I've tried to find a solution to this issue but I can't see anything online. I've launched Lutris with Lutris -d but I didn't get any king of comprehensive logging from the linux terminal. I had previously used the Pop_Os release of Lutris and that worked fine. However ever since switching to ubuntu I've been unable to resolve this issue. 

I've tried to launch the FFXIV launcher as well as Vortex (the mod manager) both will not launch and are stuck at simply saying "launching." When I click show logs on the specific games the log file is empty. Clearly there is something wrong here. 

If y'all have any way for me to even submit logs let me know, but I'd like to resolve this issue so I can actually launch my games from Lutris

**Comment by thesocialproject** [comment]
> `lutris -d >~/out.txt`

Well I've changed literally nothing in my computer setup since I've been having this problem, and when I ran this command Lutris launched applications fine. So maybe somehow it fixed the problem?? 

Very weird anyways I appreciate the help

**Comment by Nekuzar** [comment]
I have the same issue in Linux Mint 21, which is based on Ubuntu 22.04. I only tried with Hearthstone/Blizzard Battle.net, but it doesnt open.

lutris -d >~/out.txt:

2022-07-20 21:54:49,819: Starting Lutris 0.5.9.1
2022-07-20 21:54:49,882: No cores found
2022-07-20 21:54:52,275: Startup complete
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 825, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 749, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 186, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 789, in get_runtime_env
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 825, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 749, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 186, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 789, in get_runtime_env
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'

**Comment by danieljohnson2** [comment]
@Nekuzar, that looks like #4198, fixed in 0.5.10. Could you give 0.5.10 (or later) a try? I believe it will fix your issue.

It *possible* that @thesocialproject had the same issue, and it's fixed because he got updated to a newer Lutris without noticing. But there's no way to know.

If your problem is resolved by 0.5.10, I'll close this issue, since nobody will be having the problem anymore.

**Comment by Nekuzar** [comment]
@danieljohnson2 It worked, thank you!
