### ISSUE TITLE
KeyError: 'item'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#439]
got this warning this morning:

```
DEBUG    2016-11-20 05:48:49,755 [sync]:Syncing details for tomb-raider-i
DEBUG    2016-11-20 05:48:54,638 [sync]:1 games updated
Traceback (most recent call last):
  File "/home/user01/src/lutris/lutris/gui/lutriswindow.py", line 346, in update_existing_games
    self.view.update_row(pga.get_game_by_field(game_id, 'id'))
  File "/home/user01/src/lutris/lutris/gui/flowbox.py", line 213, in update_row
    self.update_image(game['id'], _game['installed'])
  File "/home/user01/src/lutris/lutris/gui/flowbox.py", line 218, in update_image
    item = game['item']
KeyError: 'item'
```

**Comment by strycore** [comment]
Fixed the crash part but haven't fixed the underlying issue yet, this will have to go in it's own ticket once we know what's causing it.
