### ISSUE TITLE
errors while launching epic games launcher

### ISSUE THREAD

**Issue by fily-gif** [lutris/lutris#4443]
Hello, when i try to open Epic Games launcher, it gives me a huge error
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 825, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 749, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 186, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 789, in get_runtime_env
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'
```
Thanks in advance.

**Comment by danieljohnson2** [comment]
This appears to be an error fixed in master some time ago. I believe the latest release (0.5.11! Get it while its hot!) should fix it.

If your distro is *so lazy* that it doesn't have 0.5.11, released an hour ago (I mean *really*) then you could get it off github, [here](https://github.com/lutris/lutris/releases).

**Comment by fily-gif** [comment]
> This appears to be an error fixed in master some time ago. I believe the latest release (0.5.11! Get it while its hot!) should fix it.
> 
> If your distro is _so lazy_ that it doesn't have 0.5.11, released an hour ago (I mean _really_) then you could get it off github, [here](https://github.com/lutris/lutris/releases).

i did all of it on 0.5.11 release, same error

**Comment by danieljohnson2** [comment]
Hmm. I think that the trace-back should have at least changed on 0.5.11

**Comment by strycore** [comment]
This crash is from an old Lutris version.
