### ISSUE TITLE
Amazon Prime Gaming - games do not download

### ISSUE THREAD

**Issue by lgaudreau** [lutris/lutris#4489]
Using X11 I was able to sign in to Amazon Games after adding the source to Lutris.  (I was not able to log in when using Wayland, but that's a separate issue).

I can see my games list successfully.  When I try to download a game, nothing happens in the GUI at all.

In the console the following errors are reported:

`2022-09-07 16:52:28,722: Startup complete
2022-09-07 16:52:35,251: Unable to get games from API: HTTP Error 405: Method Not Allowed
2022-09-07 16:52:36,513: Failed http request https://sds.amazon.com/amazon/
2022-09-07 16:52:36,514: There was an error getting patches: 34c0dca0-678c-170e-ed82-477d9e5bbc98
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 628, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 252, in install
    installer = self.generate_installer(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/amazon.py", line 605, in generate_installer
    file_dict, directories = self.get_game_files(details["id"])
  File "/usr/lib/python3/dist-packages/lutris/services/amazon.py", line 544, in get_game_files
    game_patches = self.get_game_patches(game_id, manifest_info["versionId"], hashpairs)
  File "/usr/lib/python3/dist-packages/lutris/services/amazon.py", line 504, in get_game_patches
    raise UnavailableGame(
lutris.exceptions.UnavailableGame: ('Unable to get the patches of game, please check your Amazon credentials and internet connectivity', '34c0dca0-678c-170e-ed82-477d9e5bbc98')`

Running Pop!_OS 22.04, NVIDIA GeForce RTX 2080 with Max-Q Design.

What other information would be helpful?

**Comment by Patola** [comment]
I have the same problem but only with some specific games. For example, this is the message when trying to download Rain World (given by Amazon Prime subscription) (hex string obfuscated for privacy):
```
2022-09-11 05:36:20,767: There was an error getting patches: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 628, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3.10/site-packages/lutris/services/base.py", line 252, in install
    installer = self.generate_installer(db_game)
  File "/usr/lib/python3.10/site-packages/lutris/services/amazon.py", line 605, in generate_installer
    file_dict, directories = self.get_game_files(details["id"])
  File "/usr/lib/python3.10/site-packages/lutris/services/amazon.py", line 544, in get_game_files
    game_patches = self.get_game_patches(game_id, manifest_info["versionId"], hashpairs)
  File "/usr/lib/python3.10/site-packages/lutris/services/amazon.py", line 504, in get_game_patches
    raise UnavailableGame(
lutris.exceptions.UnavailableGame: ('Unable to get the patches of game, please check your Amazon credentials and internet connectivity', 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')
```
After this, it seems like Lutris loses the state on its own state machine and just doesn't do anything when the 'install' button pressed, not even a message to the terminal.

Other titles like Maniac Mansion don't even generate an output as verbose as Rain World, with only that line showing when I press the "install" button:
`2022-09-11 05:44:19,849: Unable to get games from API: HTTP Error 405: Method Not Allowed`

So, it seems that the current Amazon connectivity is in a rather precarious state, needing more polish and bug-squatting to be in production.

**Comment by ItsRogueRen** [comment]
Bumping this with the same issue, I can't install Psychonauts or Metal Slug 2/3, which were the whole reason I even set this up.

debug from terminal here: https://pastebin.com/a0CyyMWn

**Comment by danieljohnson2** [comment]
The traceback makes this fairly clear- the exception is being dropper on the floor.

I've added code to display it as an error dialog. This won't make your Amazon account *work*, but it should tell you to check your credentials and internet connectivity.

That may or may not be the problem, but at least this commit should fix this bug that is definitely there, where there's no error report.
