### ISSUE TITLE
Blank installer window if wine is not found

### ISSUE THREAD

**Issue by denilsonsa** [lutris/lutris#4537]
## How to reproduce

1. Brand-new freshly installed Manjaro Linux.
    * Install `lutris`, don't bother installing `wine`.
2. Open Lutris.
    * If you open from a terminal, you can see the error message.
    * If you open from the GUI, the interface will be blank and you will keep wondering what's wrong.
3. "Add Game".
4. "Search the Lutris website for installers".
5. Try searching for some game known to be native to linux. You can try "Abuse", or probably [one of the hundreds available](https://lutris.net/games?q=&platforms=2&flags=free&search-installers=on).
6. At the dialog asking to choose a version, pick any one by clicking on the "Install" button.
7. **BUG!**

## What happens

The installation window goes empty, with just the "Cache" and "Cancel" buttons visible. It is impossible to install a game.

If you had the terminal open, you would see this:

```
2022-10-03 00:28:42,406: Starting Lutris 0.5.11
2022-10-03 00:28:42,573: Running Intel Mesa driver 22.1.7 on Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x1912)
2022-10-03 00:28:42,573: GPU: 8086:1912 103C:8056 (i915 drivers)
2022-10-03 00:28:42,573: i386 libgnutls.so.30 missing (needed by gnutls)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
2022-10-03 00:28:42,733: Startup complete
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/installerwindow.py", line 159, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 69, in __init__
    file.set_url(self._substitute(file.url))
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 431, in _substitute
    return system.substitute(template_string, self._get_string_replacements())
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 413, in _get_string_replacements
    "WINEBIN": self.get_wine_path(),
  File "/usr/lib/python3.10/site-packages/lutris/installer/commands.py", line 391, in get_wine_path
    return get_wine_version_exe(self._get_runner_version())
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/wine.py", line 219, in get_wine_version_exe
    raise RuntimeError("Wine is not installed")
RuntimeError: Wine is not installed
```

## What should happen

Wine is optional. Lutris shouldn't crash if it's not found. And most definitely it should not crash if the game/installer doesn't depend on it.

If an installer requires Wine, it should display a nice error message at the GUI.

## Related issues:

* #3290
* #4276

**Comment by danieljohnson2** [comment]
I've been working today on improving this window's error reporting. Could you try the master branch and see if that helps?

Just download it and run the "bin/lutris" script in there; no need to install anything.

**Comment by denilsonsa** [comment]
Indeed, this specific bug seems to be fixed in `master`, as I cannot reproduce it. Thanks!
