### ISSUE TITLE
Installing gog.com Deus Ex GOTY causes a crash and hang in installer interpreter

### ISSUE THREAD

**Issue by ColonelPhantom** [lutris/lutris#4595]
Here's the traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/installer/commands.py", line 452, in _monitor_task
    self._iter_commands()
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 326, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 350, in _finish_install
    game_id = self.installer.save()
  File "/usr/lib/python3.10/site-packages/lutris/installer/installer.py", line 260, in save
    lutris_config = convert_gog_config_to_lutris(gog_config, gog_game_path)
  File "/usr/lib/python3.10/site-packages/lutris/util/gog.py", line 60, in convert_gog_config_to_lutris
    config = get_game_config(task, gog_game_path)
  File "/usr/lib/python3.10/site-packages/lutris/util/gog.py", line 42, in get_game_config
    if os.path.exists(exe_abspath):
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Unfortunately I don't really know what is going wrong :( I'm running Lutris 0.5.11

It seems like creating the path goes wrong somehow, but I'm not sure why.

**Comment by danieljohnson2** [comment]
It's a known issue, fixed in the 0.5.12 beta.

It's trying to correct the case of a path from the installation, but the path does not refer to a file that exists; 0.5.11 dies horribly in that case, and 0.5.12 corrects the case so far as it can and keeps the rest.
