### ISSUE TITLE
After GPU upgrade lutris crashes with stack smashing detected

### ISSUE THREAD

**Issue by x0r13** [lutris/lutris#4608]
Today I upgraded my system from a nVidia 1060 to a RX 6600 and now lutris constantly crashes when trying to install battle.net.
Current system:

```
[System]
OS:              Ubuntu 20.04 focal
Arch:            x86_64
Kernel:          5.4.0-132-lowlatency
Desktop:         Budgie:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 1700 Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.6 GB
Swap:            3.8 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 (dimgrey_cavefish, LLVM 14.0.1, DRM 3.46, 5.4.0-132-lowlatency)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.1.0-devel
OpenGL Core:     4.6 (Core Profile) Mesa 22.1.0-devel
OpenGL ES:       OpenGL ES 3.2 Mesa 22.1.0-devel
Vulkan:          Supported
```

I had lutris installed before, with battle.net running Diablo II Resurrected just fine. After the GPU upgrade my battle.net shortcuts did not work anymore, and trying to start via lutris did not work either.

So I removed everything, and tried to install battle.net again, but it always fails right after creating the prefix:

```
INFO     2022-11-22 23:01:24,866 [startup.init_lutris:174]:Starting Lutris 0.5.12
INFO     2022-11-22 23:01:24,934 [startup.check_driver:66]:Running AMD Mesa driver 22.1.0 on AMD Radeon RX 6600 (dimgrey_cavefish, LLVM 14.0.1, DRM 3.46, 5.4.0-132-lowlatency) (0x73ff)
INFO     2022-11-22 23:01:24,935 [startup.check_driver:78]:GPU: 1002:73FF 1EAE:6505 (amdgpu drivers)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
DEBUG    2022-11-22 23:01:25,133 [lutriswindow.update_store:448]:Showing 1 games
INFO     2022-11-22 23:01:25,146 [startup.update_runtime:215]:Startup complete
DEBUG    2022-11-22 23:01:28,724 [lutriswindow.update_store:448]:Showing 1 games
WARNING: radv is not a conformant Vulkan implementation, testing use only.
DEBUG    2022-11-22 23:01:33,893 [application.show_window:327]:Showing window PreferencesDialog{}
DEBUG    2022-11-22 23:03:54,241 [application.on_app_window_destroyed:345]:Removed window PreferencesDialog{}
DEBUG    2022-11-22 23:04:03,106 [config.remove:213]:Removed config /home/xxx/.config/lutris/games/diablo-ii-resurrected-1669154115.yml
DEBUG    2022-11-22 23:04:03,151 [lutriswindow.update_store:448]:Showing 1 games
DEBUG    2022-11-22 23:04:11,145 [lutriswindow.update_store:448]:Showing 0 games
DEBUG    2022-11-22 23:04:23,779 [lutriswindow.update_store:448]:Showing 0 games
DEBUG    2022-11-22 23:04:25,540 [application.show_window:327]:Showing window AddGamesWindow{}
DEBUG    2022-11-22 23:04:30,233 [http._request:87]:GET https://lutris.net/api/games?search=diablo&with-installers=True
DEBUG    2022-11-22 23:04:31,846 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/diablo-2-ressurected
DEBUG    2022-11-22 23:04:31,846 [http._request:87]:GET https://lutris.net/api/installers/diablo-2-ressurected
DEBUG    2022-11-22 23:04:32,024 [application.show_window:327]:Showing window InstallerWindowdiablo-2-ressurected
DEBUG    2022-11-22 23:04:32,025 [application.on_app_window_destroyed:345]:Removed window AddGamesWindow{}
DEBUG    2022-11-22 23:04:38,745 [displayconfig.get_current_resolution:643]:Retrieving current resolution
INFO     2022-11-22 23:04:40,286 [runner.get_runner_version:346]:Getting runner information for wine
DEBUG    2022-11-22 23:04:40,286 [http._request:87]:GET https://lutris.net/api/runners/wine
DEBUG    2022-11-22 23:04:40,382 [interpreter.get_runners_to_install:228]:Default wine version is lutris-7.2-2
DEBUG    2022-11-22 23:04:40,397 [interpreter.create_game_folder:186]:Creating destination path /home/xxx/Games/diablo-2-ressurected
DEBUG    2022-11-22 23:04:42,518 [downloader.start:65]:⬇ https://www.battle.net/download/getInstallerForGame?os=win&version=LIVE&gameProgram=BATTLENET_APP
DEBUG    2022-11-22 23:04:44,044 [downloader.download_cb:125]:Finished downloading https://www.battle.net/download/getInstallerForGame?os=win&version=LIVE&gameProgram=BATTLENET_APP
INFO     2022-11-22 23:04:44,521 [file_box.on_download_complete:239]:Download completed
DEBUG    2022-11-22 23:04:44,521 [files_box.on_file_available:93]:setup is available
INFO     2022-11-22 23:04:44,522 [files_box.on_file_available:99]:All files available
INFO     2022-11-22 23:04:44,522 [installerwindow.on_files_available:492]:All files are available, continuing install
DEBUG    2022-11-22 23:04:44,524 [interpreter._iter_commands:322]:Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2022-11-22 23:04:44,528 [wine.create_prefix:98]:Creating a win64 prefix in /home/xxx/Games/diablo-2-ressurected
DEBUG    2022-11-22 23:04:44,529 [system.execute:57]:Executing /home/xxx/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wineboot
DEBUG    2022-11-22 23:04:44,529 [system.execute:63]:WINEARCH=win64 WINEPREFIX=/home/xxx/Games/diablo-2-ressurected WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/xxx/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/mono WINE_GECKO_CACHE_DIR=/home/xxx/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/gecko
INFO     2022-11-22 23:04:59,709 [wine.create_prefix:153]:win64 Prefix created in /home/xxx/Games/diablo-2-ressurected
DEBUG    2022-11-22 23:04:59,788 [interpreter._iter_commands:322]:Installer command: {'task': {'app': 'arial', 'arch': 'win64', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
DEBUG    2022-11-22 23:04:59,815 [wine.use_lutris_runtime:116]:/home/xxx/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine is provided by Lutris, using runtime
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,825 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,826 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,826 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,826 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,888 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,888 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,946 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,946 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,946 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,946 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,946 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
WARNING  2022-11-22 23:04:59,951 [runner.game_config:87]:Accessing game config while runner wasn't given one.
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

I can install it with a local wine version though (wine-7.0), but mangohud did not work with the locally installed version.
I also tried the kisak-mesa drivers but removed them again after it did not fix the issue, and also introduced another problem (MESA: error: failed to load D3D12)

Any tips why lutris is crashing?

**Comment by x0r13** [comment]
After checking the dump:

```
Core was generated by `/usr/bin/python3 /usr/games/lutris -d'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f634080d700 (LWP 6381))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6357b3f859 in __GI_abort () at abort.c:79
#2  0x00007f6357baa26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6357cd408f "*** %s ***: terminated\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f6357c4caba in __GI___fortify_fail (msg=msg@entry=0x7f6357cd4077 "stack smashing detected") at fortify_fail.c:26
#4  0x00007f6357c4ca86 in __stack_chk_fail () at stack_chk_fail.c:24
#5  0x00007f6357c7d9b4 in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7f6357d562d0 <call_dl_init>, args=args@entry=0x7f634080ac70) at dl-error-skeleton.c:219
#6  0x00007f6357d570cf in dl_open_worker (a=a@entry=0x7f634080ae20) at dl-open.c:758
#7  0x00007f6357c7d928 in __GI__dl_catch_exception (exception=exception@entry=0x7f634080ae00, operate=operate@entry=0x7f6357d56c20 <dl_open_worker>, args=args@entry=0x7f634080ae20) at dl-error-skeleton.c:208
#8  0x00007f6357d5660a in _dl_open (file=0x7f63414ae250 "libGLX_nvidia.so.0", mode=-2147483646, caller_dlopen=<optimized out>, nsid=-2, argc=3, argv=0x7ffea42ca508, env=0x7ffea42ca528) at dl-open.c:837
#9  0x00007f6357af534c in dlopen_doit (a=a@entry=0x7f634080b040) at dlopen.c:66
#10 0x00007f6357c7d928 in __GI__dl_catch_exception (exception=exception@entry=0x7f634080afe0, operate=operate@entry=0x7f6357af52f0 <dlopen_doit>, args=args@entry=0x7f634080b040) at dl-error-skeleton.c:208
#11 0x00007f6357c7d9f3 in __GI__dl_catch_error
    (objname=objname@entry=0x7f6330031700, errstring=errstring@entry=0x7f6330031708, mallocedp=mallocedp@entry=0x7f63300316f8, operate=operate@entry=0x7f6357af52f0 <dlopen_doit>, args=args@entry=0x7f634080b040)
    at dl-error-skeleton.c:227
#12 0x00007f6357af5b59 in _dlerror_run (operate=operate@entry=0x7f6357af52f0 <dlopen_doit>, args=args@entry=0x7f634080b040) at dlerror.c:170
#13 0x00007f6357af53da in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#14 0x00007f63521f4ad1 in  () at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#15 0x00000000005f69ca in PyCFunction_Call ()
#16 0x00000000005f74f6 in _PyObject_MakeTpCall ()
#17 0x0000000000570d55 in _PyEval_EvalFrameDefault ()
#18 0x0000000000569dba in _PyEval_EvalCodeWithName ()
#19 0x000000000059c996 in  ()
#20 0x00000000005f745f in _PyObject_MakeTpCall ()
#21 0x0000000000570d55 in _PyEval_EvalFrameDefault ()
#22 0x00000000005f6cd6 in _PyFunction_Vectorcall ()
#23 0x000000000056bacd in _PyEval_EvalFrameDefault ()
#24 0x00000000005f6cd6 in _PyFunction_Vectorcall ()
#25 0x000000000056bacd in _PyEval_EvalFrameDefault ()
#26 0x0000000000569dba in _PyEval_EvalCodeWithName ()
#27 0x00000000005f6eb3 in _PyFunction_Vectorcall ()
#28 0x000000000056bbfa in _PyEval_EvalFrameDefault ()
#29 0x00000000005f6cd6 in _PyFunction_Vectorcall ()
#30 0x000000000056bbfa in _PyEval_EvalFrameDefault ()
#31 0x00000000005f6cd6 in _PyFunction_Vectorcall ()
#32 0x000000000056bbfa in _PyEval_EvalFrameDefault ()
#33 0x0000000000569dba in _PyEval_EvalCodeWithName ()
#34 0x00000000005f6eb3 in _PyFunction_Vectorcall ()
#35 0x000000000056cc1f in _PyEval_EvalFrameDefault ()
#36 0x0000000000569dba in _PyEval_EvalCodeWithName ()
#37 0x00000000005f6eb3 in _PyFunction_Vectorcall ()
#38 0x00000000005f6082 in PyObject_Call ()
#39 0x000000000056d2d5 in _PyEval_EvalFrameDefault ()
#40 0x00000000005f6cd6 in _PyFunction_Vectorcall ()
#41 0x000000000050bc2c in  ()
#42 0x00000000005f6082 in PyObject_Call ()
#43 0x000000000056d2d5 in _PyEval_EvalFrameDefault ()
#44 0x0000000000569dba in _PyEval_EvalCodeWithName ()
#45 0x00000000005f6eb3 in _PyFunction_Vectorcall ()
#46 0x000000000050bc2c in  ()
#47 0x00000000005f6082 in PyObject_Call ()
#48 0x000000000056d2d5 in _PyEval_EvalFrameDefault ()
--Type <RET> for more, q to quit, c to continue without paging--
```

Why is it trying to load libGLX_nvidia.so.0 ?

**Comment by al12gamer** [comment]
Please upgrade to the most recent Ubuntu release if you plan on running more modern hardware, as older releases that came out before said hardware may not properly support the GPUs on a driver level.

**Comment by strycore** [comment]
Marking as resolved.
- Consider upgrading to 22.04
- Update to lutris 0.5.13
- Use lutris-GE-Proton8 to run your game.
- Make sure the correct Vulkan ICD is being used (in the system tab)
