### ISSUE TITLE
Unsupported architecture aarch64

### ISSUE THREAD

**Issue by TYeniyayla** [lutris/lutris#4621]
Is lutris arm64 not compatible? When I run it from console I get the following error. when I run it as an application, only the error report screen appears.

```
$ lutris
2022-11-28 19:18:24,700: Unsupported architecture aarch64
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 38, in <module>
    from lutris.command import exec_command
  File "/usr/lib/python3/dist-packages/lutris/command.py", line 13, in <module>
    from lutris import runtime, settings
  File "/usr/lib/python3/dist-packages/lutris/runtime.py", line 12, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 434, in <module>
    LINUX_SYSTEM = LinuxSystem()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 123, in __init__
    self.populate_libraries()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 359, in populate_libraries
    for req in self.requirements:
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 258, in requirements
    return self.get_requirements()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 287, in get_requirements
    if drivers.is_amd():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/drivers.py", line 91, in is_amd
    for card in get_gpus():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/drivers.py", line 69, in get_gpus
    for cardname in os.listdir("/sys/class/drm/"):
PermissionError: [Errno 13] Permission denied: '/sys/class/drm/'
```

uname -m
`aarch64`

uname -a
`Linux localhost 5.4.0-faked #1 SMP PREEMPT Tue Nov 15 06:59:43 UTC 2022 aarch64 GNU/Linux
`

**Comment by strycore** [comment]
This has nothing to do with the ARM architecture. Lutris is trying to read available GPUs from /sys/class/drm but your distribution doesn't allow it. 
If added error handling for this case, so it should go beyond that point now.
Please note that while the Lutris client should run without issue on ARM, we don't have runners for ARM yet.
