### ISSUE TITLE
failed to install dbus-python

### ISSUE THREAD

**Issue by rachmadaniHaryono** [lutris/lutris#4630]
running pip install on lutris give error related to dbus-python

<details><summary>error log</summary>
<p>

```python
> python -m pip install -e .
Obtaining file:///mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/lutris
  Preparing metadata (setup.py) ... done
Collecting certifi
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting dbus-python
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [218 lines of output]
      The Meson build system
      Version: 0.63.3
      Source dir: /tmp/pip-install-8ov5cpj2/dbus-python_cda5878d9a2144db9ea9ca8c8334d5b9
      Build dir: /tmp/pip-install-8ov5cpj2/dbus-python_cda5878d9a2144db9ea9ca8c8334d5b9/.mesonpy-nygmk90h/build
      Build type: native build
      Project name: dbus-python
      Project version: 1.3.2
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Ubuntu 12.2.0-3ubuntu1) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.39
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -fno-common: YES
      Compiler for C supports arguments -Wno-missing-field-initializers: YES
      Compiler for C supports arguments -Wno-declaration-after-statement: YES
      Compiler for C supports arguments -Wno-inline: YES
      Compiler for C supports arguments -Wno-redundant-decls: YES
      Compiler for C supports arguments -Wno-switch-default: YES
      Compiler for C supports arguments -Wno-write-strings: YES
      Compiler for C supports arguments -Wcast-align: YES
      Compiler for C supports arguments -Wdouble-promotion: YES
      Compiler for C supports arguments -Wduplicated-cond: YES
      Compiler for C supports arguments -Wfloat-equal: YES
      Compiler for C supports arguments -Wformat-nonliteral: YES
      Compiler for C supports arguments -Wformat-security: YES
      Compiler for C supports arguments -Wformat=2: YES
      Compiler for C supports arguments -Winit-self: YES
      Compiler for C supports arguments -Wlogical-op: YES
      Compiler for C supports arguments -Wmissing-declarations: YES
      Compiler for C supports arguments -Wmissing-format-attribute: YES
      Compiler for C supports arguments -Wmissing-include-dirs: YES
      Compiler for C supports arguments -Wmissing-noreturn: YES
      Compiler for C supports arguments -Wnull-dereference: YES
      Compiler for C supports arguments -Wpacked: YES
      Compiler for C supports arguments -Wpointer-arith: YES
      Compiler for C supports arguments -Wshadow: YES
      Compiler for C supports arguments -Wswitch-enum: YES
      Compiler for C supports arguments -Wundef: YES
      Compiler for C supports arguments -Wunused-but-set-variable: YES
      Compiler for C supports arguments -Wjump-misses-init: YES
      Compiler for C supports arguments -Wmissing-prototypes: YES
      Compiler for C supports arguments -Wnested-externs: YES
      Compiler for C supports arguments -Wold-style-definition: YES
      Compiler for C supports arguments -Wpointer-sign: YES
      Compiler for C supports arguments -Wstrict-prototypes: YES
      Configuring _dbus-python-config.h using configuration

      Executing subproject dbus-gmain

      dbus-gmain| Project name: dbus-gmain
      dbus-gmain| Project version: undefined
      dbus-gmain| C compiler for the host machine: cc (gcc 12.2.0 "cc (Ubuntu 12.2.0-3ubuntu1) 12.2.0")
      dbus-gmain| C linker for the host machine: cc ld.bfd 2.39
      dbus-gmain| Compiler for C supports arguments -fno-common: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wcast-align: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wdouble-promotion: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wduplicated-branches: YES
      dbus-gmain| Compiler for C supports arguments -Wduplicated-cond: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wfloat-equal: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-nonliteral: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-security: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat=2: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Winit-self: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wlogical-op: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-declarations: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-format-attribute: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-include-dirs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-noreturn: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnull-dereference: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpacked: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-arith: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wredundant-decls: YES
      dbus-gmain| Compiler for C supports arguments -Wshadow: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wswitch-default: YES
      dbus-gmain| Compiler for C supports arguments -Wswitch-enum: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wundef: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wunused-but-set-variable: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wwrite-strings: YES
      dbus-gmain| Compiler for C supports arguments -Wdeclaration-after-statement: YES
      dbus-gmain| Compiler for C supports arguments -Wjump-misses-init: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-prototypes: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnested-externs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wold-style-definition: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-sign: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wstrict-prototypes: YES (cached)
      dbus-gmain| Found pkg-config: /usr/bin/pkg-config (0.29.2)
      dbus-gmain| Run-time dependency dbus-1 found: YES 1.14.0
      dbus-gmain| Run-time dependency glib-2.0 found: YES 2.74.0
      dbus-gmain| Run-time dependency gthread-2.0 found: YES 2.74.0
      dbus-gmain| Program dbus-run-session found: YES (/usr/bin/dbus-run-session)
      dbus-gmain| Build targets in project: 1
      dbus-gmain| Subproject dbus-gmain finished.

      Program python found: YES (/home/r3r/.pyenv/versions/lutris/bin/python)
      Dependency dbus-1 found: YES 1.14.0 (cached)
      Configuring TestSuitePythonService.service using configuration
      Configuring tmp-session-bus.conf using configuration
      Program dbus-run-session found: YES (/usr/bin/dbus-run-session)
      Build targets in project: 5

      dbus-python 1.3.2

        Subprojects
          dbus-gmain  : YES

        User defined options
          Native files: /tmp/pip-install-8ov5cpj2/dbus-python_cda5878d9a2144db9ea9ca8c8334d5b9/.mesonpy-native-file.ini
          debug       : false
          optimization: 2
          prefix      : /home/r3r/.pyenv/versions/3.11.0

      Found ninja-1.10.2.git.kitware.jobserver-1 at /tmp/pip-build-env-l61fgqld/overlay/bin/ninja
      [1/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_bytes.c.o
      [2/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_conn.c.o
      [3/32] Compiling C object subprojects/dbus-gmain/libdbus-gmain.a.p/dbus-gmain.c.o
      [4/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_abstract.c.o
      [5/32] Linking static target subprojects/dbus-gmain/libdbus-gmain.a
      [6/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_debug.c.o
      [7/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_exceptions.c.o
      [8/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_bus.c.o
      [9/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_conn-methods.c.o
      [10/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_containers.c.o
      [11/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_float.c.o
      [12/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_generic.c.o
      [13/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_int.c.o
      [14/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_unixfd.c.o
      [15/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_libdbusconn.c.o
      [16/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_message-append.c.o
      [17/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_mainloop.c.o
      [18/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_message-get-args.c.o
      [19/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_signature.c.o
      [20/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_pending-call.c.o
      [21/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_module.c.o
      [22/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_string.c.o
      [23/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_validation.c.o
      [24/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_server.c.o
      [25/32] Compiling C object test/dbus_py_test.cpython-311-x86_64-linux-gnu.so.p/dbus_py_test.c.o
      [26/32] Linking target test/dbus_py_test.cpython-311-x86_64-linux-gnu.so
      [27/32] Compiling C object test/test-import-repeatedly.p/import-repeatedly.c.o
      [28/32] Compiling C object _dbus_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_bindings_message.c.o
      [29/32] Linking target _dbus_bindings.cpython-311-x86_64-linux-gnu.so
      [30/32] Compiling C object _dbus_glib_bindings.cpython-311-x86_64-linux-gnu.so.p/dbus_glib_bindings_module.c.o
      [31/32] Linking target _dbus_glib_bindings.cpython-311-x86_64-linux-gnu.so
      [32/32] Linking target test/test-import-repeatedly
      FAILED: test/test-import-repeatedly
      cc  -o test/test-import-repeatedly test/test-import-repeatedly.p/import-repeatedly.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a -Wl,--end-group
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(floatobject.o): in function `_float_div_mod':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:675: undefined reference to `fmod'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(floatobject.o): in function `float_rem':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:655: undefined reference to `fmod'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(floatobject.o): in function `float_pow':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:788: undefined reference to `fmod'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:847: undefined reference to `pow'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:798: undefined reference to `fmod'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:824: undefined reference to `fmod'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(floatobject.o): in function `float___round___impl':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:1090: undefined reference to `round'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/floatobject.c:1093: undefined reference to `round'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(longobject.o): in function `PyLong_FromString':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/longobject.c:2441: undefined reference to `log'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(complexobject.o): in function `_Py_c_abs':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:208: undefined reference to `hypot'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(complexobject.o): in function `_Py_c_pow':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:144: undefined reference to `hypot'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:145: undefined reference to `pow'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:146: undefined reference to `atan2'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:148: undefined reference to `sincos'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:149: undefined reference to `exp'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:150: undefined reference to `log'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(complexobject.o): in function `_Py_c_abs':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Objects/complexobject.c:208: undefined reference to `hypot'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(pytime.o): in function `pytime_round_half_even':
      /tmp/python-build.20221026064216.163796/Python-3.11.0/Python/pytime.c:241: undefined reference to `round'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Python/pytime.c:244: undefined reference to `round'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Python/pytime.c:241: undefined reference to `round'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Python/pytime.c:244: undefined reference to `round'
      /usr/bin/ld: /tmp/python-build.20221026064216.163796/Python-3.11.0/Python/pytime.c:241: undefined reference to `round'
      /usr/bin/ld: /home/r3r/.pyenv/versions/3.11.0/lib/libpython3.11.a(pytime.o):/tmp/python-build.20221026064216.163796/Python-3.11.0/Python/pytime.c:244: more undefined references to `round' follow
      collect2: error: ld returned 1 exit status
      ninja: build stopped: subcommand failed.
      + meson setup --native-file=/tmp/pip-install-8ov5cpj2/dbus-python_cda5878d9a2144db9ea9ca8c8334d5b9/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/home/r3r/.pyenv/versions/3.11.0 /tmp/pip-install-8ov5cpj2/dbus-python_cda5878d9a2144db9ea9ca8c8334d5b9 /tmp/pip-install-8ov5cpj2/dbus-python_cda5878d9a2144db9ea9ca8c8334d5b9/.mesonpy-nygmk90h/build
      + meson compile
      Traceback (most recent call last):
        File "/home/r3r/.pyenv/versions/lutris/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/r3r/.pyenv/versions/lutris/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/r3r/.pyenv/versions/lutris/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/r3r/.pyenv/versions/lutris/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l61fgqld/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 987, in build_wheel
          return project.wheel(out).name
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l61fgqld/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 935, in wheel
          wheel = self._wheel_builder.build(self._build_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l61fgqld/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 576, in build
          self._project.build()  # ensure project is built
          ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l61fgqld/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 765, in build
          self._meson('compile')
        File "/tmp/pip-build-env-l61fgqld/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l61fgqld/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/home/r3r/.pyenv/versions/3.11.0/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
</p>
</details>

on dbus-python repo there is related issue https://gitlab.freedesktop.org/dbus/dbus-python/-/issues/45

similar issue is reported here https://github.com/mesonbuild/meson-python/issues/55

on linked meson-python issue there is fix to avoid this by installing 1.2.18 version and it work

```diff
diff --git a/setup.py b/setup.py
index 19a2d93a..5bfcad48 100644
--- a/setup.py
+++ b/setup.py
@@ -56,7 +56,7 @@ setup(
     zip_safe=False,
     install_requires=[
         'certifi',
-        'dbus-python',
+        'dbus-python==1.2.18',
         'distro',
         'evdev',
         'lxml',
```

**Comment by strycore** [comment]
This seems to have been fixed upstream and Fedora 36 is EOL
