### ISSUE TITLE
missing executable

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#465]
forgot to add a executable to a game I was adding, and got this on the terminal:

```
Launching Tony Hawk's Pro Skater 2: {'file': None, 'error': 'FILE_NOT_FOUND'}
Traceback (most recent call last):
  File "/home/user01/src/lutris/lutris/gui/lutriswindow.py", line 523, in on_game_run
    self.running_game.play()
  File "/home/user01/src/lutris/lutris/game.py", line 164, in play
    self.do_play(True)
  File "/home/user01/src/lutris/lutris/game.py", line 178, in do_play
    show_error_message(gameplay_info)
  File "/home/user01/src/lutris/lutris/game.py", line 29, in show_error_message
    message_text = message['file'].replace('&', '&amp;')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by strycore** [comment]
What runner are you using?

**Comment by strycore** [comment]
Oh, this shouldn't matter, it's not runner specific
