### ISSUE TITLE
Lutirs won't launch since first commit after 0.5.12

### ISSUE THREAD

**Issue by Gnatzelle** [lutris/lutris#4655]
Hi Guys and Gals...
Since this commit: https://github.com/lutris/lutris/commit/dcde7f528087ecab14d21941a0fde44ad9a19f2a
Lutris won't launch anymore. Output when starting from the Terminal:

_Traceback (most recent call last):
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/bin/./lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/gui/application.py", line 45, in <module>
    from lutris.gui.installerwindow import InstallerWindow, InstallationKind
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/gui/installerwindow.py", line 17, in <module>
    from lutris.installer import InstallationKind, get_installers, interpreter
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/installer/interpreter.py", line 15, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/installer/installer.py", line 13, in <module>
    from lutris.services import SERVICES
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/services/__init__.py", line 5, in <module>
    from lutris.services.amazon import AmazonService
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/services/amazon.py", line 16, in <module>
    from lutris.services.base import OnlineService
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/services/base.py", line 16, in <module>
    from lutris.gui.dialogs.webconnect_dialog import DEFAULT_USER_AGENT, WebConnectDialog
  File "/home/xyz/Downloads/lutris-dcde7f528087ecab14d21941a0fde44ad9a19f2a/lutris/gui/dialogs/webconnect_dialog.py", line 6, in <module>
    gi.require_version("WebKit2", "4.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace WebKit2 not available for version 4.0_

OS is an up-to-date Arch Linux. Maybe the problem is that Arch is at Webkit2 4.1 whereas Lutris would like to have the older 4.0 version installed?

**Comment by Gnatzelle** [comment]
Ok...after manually changing "gi.require_version("WebKit2", "4.0")" to 4.1 in webconnect_dialog.py Lutris starts normally again.
But since this was not reverted just for fun (Webkit2 4.1 > 4.0), don't know what to do now ^^"

**Comment by danieljohnson2** [comment]
Can you install the older WebKit alongside the new one?

This merge was reverted because it caused incompatibility with Debian 11, which does not have WebKit 4.1.

**Comment by danieljohnson2** [comment]
I think that would have been a good idea, but I cocked up review on that merge the first time, so I'm inclined to let @strycore handle the issue properly now.

**Comment by Gnatzelle** [comment]
@danieljohnson2 Yeah, i'm a dumbass xD Didn't saw that Arch has now 3 different WebKit2 Packages since Dec 01st (webkit2, webkit2-4.1, webkit2-5.0) and only 4.1 is installed. 
Problem clearly on my side...sorry for the mess :/
