### ISSUE TITLE
Handle "file://" prefixes when selecting installation media

### ISSUE THREAD

**Issue by JackH3103** [lutris/lutris#4674]
When I drag-and-drop my installation files from Dolphin into the Lutris install window, the file path gets a "file://" prefix. Lutris currently cannot handle this, so I then need to go back through each file and remove the prefix. It would be nice if Lutris could do this internally.

The reason I drag-and-drop is because I do not like using the Gnome file manager (used by Lutris since I have Lutris installed as a native package).

Output of `lutris -d`:

```
INFO     2022-12-28 14:33:20,041 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2022-12-28 14:33:20,098 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2022-12-28 14:33:20,402 [startup.check_driver:57]:Using NVIDIA drivers 525.60.11 for x86_64
INFO     2022-12-28 14:33:20,403 [startup.check_driver:61]:GPU: NVIDIA GeForce 840M
INFO     2022-12-28 14:33:20,404 [startup.check_driver:77]:GPU: 10DE:1341 1028:0656 (nvidia drivers)
INFO     2022-12-28 14:33:20,405 [startup.check_driver:77]:GPU: 8086:1616 1028:0656 (i915 drivers)
DEBUG    2022-12-28 14:33:20,699 [lutriswindow.update_store:448]:Showing 126 games
INFO     2022-12-28 14:33:21,049 [startup.update_runtimes:218]:Startup complete
DEBUG    2022-12-28 14:33:23,284 [grid.on_item_activated:57]:Item activated: 1340672747
DEBUG    2022-12-28 14:33:23,284 [lutriswindow.on_game_activated:857]:Looking up gog game 1340672747
DEBUG    2022-12-28 14:33:23,286 [base.install:245]:Installing 1340672747 from service gog
DEBUG    2022-12-28 14:33:23,286 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2022-12-28 14:33:23,508 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/carcassonne-tiles-tactics
DEBUG    2022-12-28 14:33:23,509 [http._request:88]:GET https://lutris.net/api/installers/carcassonne-tiles-tactics
DEBUG    2022-12-28 14:33:23,660 [application.show_window:328]:Showing window InstallerWindow1340672747
DEBUG    2022-12-28 14:33:25,442 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2022-12-28 14:33:26,998 [runner.get_runner_version:345]:Getting runner information for wine
DEBUG    2022-12-28 14:33:26,998 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2022-12-28 14:33:27,223 [interpreter.get_runners_to_install:228]:Default wine version is lutris-7.2-2
DEBUG    2022-12-28 14:33:27,228 [gog.get_extras:328]:Download extras for GOG ID 1340672747 and its DLCs
INFO     2022-12-28 14:33:27,229 [gog.get_game_details:294]:Getting game details for 1340672747
DEBUG    2022-12-28 14:33:27,230 [http._request:88]:GET https://api.gog.com/products/1340672747?expand=downloads&locale=en-US
INFO     2022-12-28 14:33:27,491 [gog.get_game_details:294]:Getting game details for 1340672747
DEBUG    2022-12-28 14:33:27,494 [http._request:88]:GET https://api.gog.com/products/1340672747?expand=downloads&locale=en-US
DEBUG    2022-12-28 14:33:27,631 [http._request:88]:GET https://api.gog.com/products?ids=1902471514%2C2012415469%2C1426364362%2C1955642987%2C2055249872&expand=downloads
DEBUG    2022-12-28 14:33:27,889 [http._request:88]:GET https://embed.gog.com/userData.json
INFO     2022-12-28 14:33:28,197 [installer.prepare_game_files:154]:Getting files for goginstaller
INFO     2022-12-28 14:33:28,198 [installer.prepare_game_files:156]:Adding selected extras to downloads
INFO     2022-12-28 14:33:28,198 [gog.get_game_details:294]:Getting game details for 1340672747
DEBUG    2022-12-28 14:33:28,200 [http._request:88]:GET https://api.gog.com/products/1340672747?expand=downloads&locale=en-US
INFO     2022-12-28 14:33:28,340 [gog.get_download_info:300]:Getting download info for https://api.gog.com/products/1340672747/downlink/installer/en1installer0
DEBUG    2022-12-28 14:33:28,341 [http._request:88]:GET https://api.gog.com/products/1340672747/downlink/installer/en1installer0
DEBUG    2022-12-28 14:33:28,553 [interpreter.create_game_folder:186]:Creating destination path /home/jack/Games/Lutris/gog/carcassonne-tiles-tactics
INFO     2022-12-28 14:33:29,489 [files_box.check_files_ready:72]:Waiting for user to provide files
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/installer/files_box.py", line 87, in on_file_unready
    self.ready_files.remove(file_id)
KeyError: 'goginstaller'
```

The last four lines appear when I drag-and-drop.

**Comment by danieljohnson2** [comment]
There's handling for this, but only from *some* files, and not those files. I'll generalize it to work for all file choosers. And fix that on_file_unready bug also, which is unrelated.

Should be better now.

**Comment by JackH3103** [comment]
Still doesn't seem to work, but this time it's a differnt issue. I'm now trying to install Assassin's Creed: Directors Cut using local GOG installer files. I get the following output when dragging and dropping the file 'setup_assassins_creed_1.02_v2_(28524)_2.bin'.

```
jack@localhost:~> lutris -d
INFO     2023-03-27 20:33:39,365 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-03-27 20:33:39,840 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-03-27 20:33:40,449 [startup.check_driver:57]:Using NVIDIA drivers 525.89.02 for x86_64
INFO     2023-03-27 20:33:40,449 [startup.check_driver:61]:GPU: NVIDIA GeForce 840M
INFO     2023-03-27 20:33:40,450 [startup.check_driver:77]:GPU: 10DE:1341 1028:0656 (nvidia drivers)
INFO     2023-03-27 20:33:40,450 [startup.check_driver:77]:GPU: 8086:1616 1028:0656 (i915 drivers)
DEBUG    2023-03-27 20:33:42,218 [lutriswindow.update_store:448]:Showing 141 games
INFO     2023-03-27 20:33:42,733 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-03-27 20:33:55,410 [lutriswindow.update_store:448]:Showing 23 games
DEBUG    2023-03-27 20:33:56,575 [lutriswindow.update_store:448]:Showing 2 games
DEBUG    2023-03-27 20:33:58,597 [grid.on_item_activated:57]:Item activated: 1207659023
DEBUG    2023-03-27 20:33:58,597 [lutriswindow.on_game_activated:857]:Looking up gog game 1207659023
DEBUG    2023-03-27 20:33:58,599 [base.install:245]:Installing 1207659023 from service gog
DEBUG    2023-03-27 20:33:58,600 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2023-03-27 20:33:59,093 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/assassins-creed
DEBUG    2023-03-27 20:33:59,094 [http._request:88]:GET https://lutris.net/api/installers/assassins-creed
DEBUG    2023-03-27 20:33:59,658 [application.show_window:328]:Showing window InstallerWindow1207659023
DEBUG    2023-03-27 20:34:04,177 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-03-27 20:34:05,777 [runner.get_runner_version:345]:Getting runner information for wine
DEBUG    2023-03-27 20:34:05,777 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2023-03-27 20:34:06,042 [interpreter.get_runners_to_install:228]:Default wine version is lutris-7.2-2
DEBUG    2023-03-27 20:34:06,044 [gog.get_extras:328]:Download extras for GOG ID 1207659023 and its DLCs
INFO     2023-03-27 20:34:06,044 [gog.get_game_details:294]:Getting game details for 1207659023
DEBUG    2023-03-27 20:34:06,045 [http._request:88]:GET https://api.gog.com/products/1207659023?expand=downloads&locale=en-US
INFO     2023-03-27 20:34:06,938 [gog.get_game_details:294]:Getting game details for 1207659023
DEBUG    2023-03-27 20:34:06,940 [http._request:88]:GET https://api.gog.com/products/1207659023?expand=downloads&locale=en-US
DEBUG    2023-03-27 20:34:07,318 [interpreter.create_game_folder:186]:Creating destination path /home/jack/Games/Lutris/gog/assassins-creed
DEBUG    2023-03-27 20:34:09,939 [http._request:88]:GET https://embed.gog.com/userData.json
INFO     2023-03-27 20:34:10,710 [installer.prepare_game_files:154]:Getting files for install
INFO     2023-03-27 20:34:10,710 [installer.prepare_game_files:156]:Adding selected extras to downloads
INFO     2023-03-27 20:34:10,710 [gog.get_game_details:294]:Getting game details for 1207659023
DEBUG    2023-03-27 20:34:10,712 [http._request:88]:GET https://api.gog.com/products/1207659023?expand=downloads&locale=en-US
INFO     2023-03-27 20:34:11,021 [gog.get_download_info:300]:Getting download info for https://api.gog.com/products/1207659023/downlink/installer/en1installer0
DEBUG    2023-03-27 20:34:11,023 [http._request:88]:GET https://api.gog.com/products/1207659023/downlink/installer/en1installer0
INFO     2023-03-27 20:34:11,739 [gog.get_download_info:300]:Getting download info for https://api.gog.com/products/1207659023/downlink/installer/en1installer1
DEBUG    2023-03-27 20:34:11,740 [http._request:88]:GET https://api.gog.com/products/1207659023/downlink/installer/en1installer1
INFO     2023-03-27 20:34:12,453 [gog.get_download_info:300]:Getting download info for https://api.gog.com/products/1207659023/downlink/installer/en1installer2
DEBUG    2023-03-27 20:34:12,455 [http._request:88]:GET https://api.gog.com/products/1207659023/downlink/installer/en1installer2
INFO     2023-03-27 20:34:16,945 [files_box.check_files_ready:72]:Waiting for user to provide files
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/installer/files_box.py", line 87, in on_file_unready
    self.ready_files.remove(file_id)
KeyError: 'setup_assassins_creed_1.02_v2_(28524)_2.bin'
```

When I click "Next", it brings me to the page shown in the screenshot:

![Screenshot_20230327_203803](https://user-images.githubusercontent.com/23507259/228048823-4e82d6bc-5ce3-4cbd-8529-419f670b49eb.png)

**Comment by JackH3103** [comment]
Ignore my previous comment (now deleted). I've just realised that Lutris hasn't been updated since you made the fix.
