### ISSUE TITLE
Lutris broke due to libtiff.so.6 error

### ISSUE THREAD

**Issue by LethalManBoob** [lutris/lutris#4697]
➜  ~ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 40, in <module>
    from lutris.game import Game, export_game, import_game
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 24, in <module>
    from lutris.runners import InvalidRunner, import_runner, wine
  File "/usr/lib/python3.10/site-packages/lutris/runners/wine.py", line 24, in <module>
    from lutris.util.wine.extract_icon import PEFILE_AVAILABLE, ExtractIcon
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/extract_icon.py", line 12, in <module>
    from PIL import Image
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: libtiff.so.6: cannot open shared object file: No such file or directory

**Comment by KenMizz** [comment]
same error happened to me :(

**Comment by geajack** [comment]
What OS are you on and how did you install Lutris?

**Comment by Th3N3rdyGam3r** [comment]
After some investigation in [this issue](https://github.com/python-pillow/Pillow/issues/6864), I found a fix for my system. Try updating or removing pillow in the user environment. Updating with pacman had the newest version of pillow in the system environment, but an outdated version in my user environment wasn't updated with pacman and was being used over the newer version in the system environment.

**Comment by LethalManBoob** [comment]
forgot to say that there was another libtiff update the same day that fixed the error.

**Comment by eudy97** [comment]
Removing the outdated Chromebrew (py3_pillow) version of Pillow and installing Python's newest (pip install pillow) fixed it for me.
