### ISSUE TITLE
[Solved] Cant Start WorldOfWarcraft 

### ISSUE THREAD

**Issue by Fluke667** [lutris/lutris#4705]
[System]
OS:              Ubutuntu 22.04 LTS
Arch:            x86_64
Kernel:          5.15.0-57-generic
Desktop:         GNOME 42.5
Display Server:  x11

[CPU]
Vendor:          AMD
Model:           AMD Ryzen 9 5950 16-Core Processor x32
Physical cores:  
Logical cores:   

[Memory]
RAM:             64 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2

Can not Start World of Warcraft.

Syslog says:

```
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
     return function(*args, **kwargs)
   File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
     gameplay_info = self.get_gameplay_info()
   File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
     gameplay_info = self.runner.play()
   File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 825, in play
     launch_info = {"env": self.get_env(os_env=False)}
   File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 749, in get_env
     env = super(wine, self).get_env(False)
   File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 186, in get_env
     runtime_env = self.get_runtime_env()
   File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 789, in get_runtime_env
     for proton_path in get_proton_paths():
   File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
     for path in _iter_proton_locations():
   File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
     for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
   File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
     library_config = self.get_library_config()
   File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
     return read_library_folders(self.steam_data_dir)
   File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
     library["libraryfolders"].pop("contentstatsid")
 KeyError: 'contentstatsid'
 update-notifier-crash[5355]: lutris
 2023-01-08 14:50:08,850: The game has run for a very short time, did it crash?
```

AND
```
lutris
 2023-01-08 13:12:12,985: Failed to parse environment variables: 266126897,17612943163343396587,131072
 2023-01-08 13:12:12,985: Failed to parse environment variables: 266126897,17612943163343396587,131072
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 144, in on_game_stop
     game.force_stop()
   File "/usr/lib/python3/dist-packages/lutris/game.py", line 527, in force_stop
     os.kill(int(pid), signal.SIGTERM)
 PermissionError: [Errno 1] Vorgang nicht zulässig
```

![grafik](https://user-images.githubusercontent.com/20209642/211200090-c26d8242-6e98-44c5-ae5a-74e226aec6d7.png)
![grafik](https://user-images.githubusercontent.com/20209642/211200139-94c69190-bec8-4fba-8283-3a5eba02f209.png)

**Comment by danieljohnson2** [comment]
The first one looks old. Upgrade to the latest Lutris (0.5.12) and try it again.

If you are still having these problems, run "lutris -d" at the command line and it will emit much more logging. Give us that output.

**Comment by Fluke667** [comment]
Thanks its working

**Comment by danieljohnson2** [comment]
Let's just close this, then.
