### ISSUE TITLE
Dependencies issue debian 11 stable - can't install ( Python )

### ISSUE THREAD

**Issue by Rstment25** [lutris/lutris#4722]
### Bug description

Can't install on latest debian 11 stable...

sudo dpkg -i  '/home/z/Downloads/lutrisworking.deb'  ( I downloaded this from github latest release , the one from lutris website has even more dependency issues )

Selecting previously unselected package lutris.
(Reading database ... 200151 files and directories currently installed.)
Preparing to unpack .../z/Downloads/lutrisworking.deb ...
Unpacking lutris (0.5.12) ...
dpkg: dependency problems prevent configuration of lutris:
 lutris depends on python3-yaml; however:
  Package python3-yaml is not installed.
 lutris depends on python3-lxml; however:
  Package python3-lxml is not installed.
 lutris depends on python3-pil; however:
  Package python3-pil is not installed.
 lutris depends on python3-setproctitle; however:
  Package python3-setproctitle is not installed.
 lutris depends on python3-magic; however:
  Package python3-magic is not installed.
 lutris depends on cabextract; however:
  Package cabextract is not installed.
 lutris depends on fluid-soundfont-gs; however:
  Package fluid-soundfont-gs is not installed.
 lutris depends on mesa-utils; however:
  Package mesa-utils is not installed.

dpkg: error processing package lutris (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
 lutris

![luitris](https://user-images.githubusercontent.com/32986283/214274851-bf5d552f-a52f-48d9-aedb-66408e28d4e5.png)

### How to Reproduce

echo 'deb http://download.opensuse.org/repositories/home:/strycore/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/home:strycore.list
curl -fsSL https://download.opensuse.org/repositories/home:strycore/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_strycore.gpg > /dev/null
sudo apt update
(copied from: https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris , debian 11 stable )
sudo dpkg -i lutris.deb

### Expected behavior

It should install? I see an icon but clicking on it nothing happens 

### Log output

```shell
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 40, in <module>
    from lutris.game import Game, export_game, import_game
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 17, in <module>
    from lutris.config import LutrisConfig
  File "/usr/lib/python3/dist-packages/lutris/config.py", line 11, in <module>
    from lutris.util.yaml import read_yaml_from_file, write_yaml_to_file
  File "/usr/lib/python3/dist-packages/lutris/util/yaml.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

### System Information

```shell
cant open lutris..................................................
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Rstment25** [comment]
Installing those python dependencies manually works...

My bad , can someone update the website so installation is easier ?

I had to jump hoops till i figured out that github has working lutris , then download python dependenices and install wine from winehq ;p

**Comment by Rstment25** [comment]
> 

Thank you , it says nothing is broken now that I've tried those 2 commands

I'll try apt next time I have package like this to install

**Comment by Rstment25** [comment]
> @Rstment25 You can also install local packages with `apt`, then the dependencies will be resolved.
> 
> ```shell
> sudo apt install '/home/z/Downloads/lutrisworking.deb'
> ```
> 
> Also, after installing the package with `dpkg`, don’t forget to run apt install with `--fix-missing` and `--fix-broken` — this should also resolve broken dependencies.
> 
> ```shell
> sudo apt install --fix-missing
> sudo apt install --fix-broken
> ```

Thank you , it says nothing is broken now that I've tried those 2 commands

I'll try apt next time I have package like this to install
