### ISSUE TITLE
Lutris Nightly won't start (again)... Started with Battle.net Integration

### ISSUE THREAD

**Issue by Gnatzelle** [lutris/lutris#4729]
Hey Guys and Gals...

Since this commit, Lutris Nightly is broken again: https://github.com/lutris/lutris/commit/bcfcf92bf426e8ce670ea0350c6ca602180eecfd

Output from the Terminal with ./lutris -d:

Traceback (most recent call last):
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/bin/./lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/lutris/gui/application.py", line 44, in <module>
    from lutris.gui.installerwindow import InstallerWindow, InstallationKind
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/lutris/gui/installerwindow.py", line 20, in <module>
    from lutris.installer import InstallationKind, get_installers, interpreter
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/lutris/installer/installer.py", line 14, in <module>
    from lutris.services import SERVICES
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/lutris/services/__init__.py", line 6, in <module>
    from lutris.services.battlenet import BattleNetService
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/lutris/services/battlenet.py", line 18, in <module>
    from lutris.util.battlenet.product_db_pb2 import ProductDb
  File "lutris-bcfcf92bf426e8ce670ea0350c6ca602180eecfd/lutris/util/battlenet/product_db_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

Output from latest Nightly - https://github.com/lutris/lutris/commit/a0f3806972caf323fa94fdf8c4f85270d2f47c20

Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 44, in <module>
    from lutris.gui.installerwindow import InstallerWindow, InstallationKind
  File "/usr/lib/python3.10/site-packages/lutris/gui/installerwindow.py", line 20, in <module>
    from lutris.installer import InstallationKind, get_installers, interpreter
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/usr/lib/python3.10/site-packages/lutris/installer/installer.py", line 14, in <module>
    from lutris.services import SERVICES
  File "/usr/lib/python3.10/site-packages/lutris/services/__init__.py", line 6, in <module>
    from lutris.services.battlenet import BattleNetService
  File "/usr/lib/python3.10/site-packages/lutris/services/battlenet.py", line 18, in <module>
    from lutris.util.battlenet.product_db_pb2 import ProductDb
  File "/usr/lib/python3.10/site-packages/lutris/util/battlenet/product_db_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

**Comment by danieljohnson2** [comment]
I believe the issue is that you need a dependency called 'protobuf', but I'm not sure how you get it.

**Comment by vlakam** [comment]
Latest lutris-git in AUR is also affected

**Comment by Astrobald** [comment]
Same here on Manjaro (mesa tkg git & linux tkg git) :

```
git clone https://github.com/lutris/lutris
cd lutris
./bin/lutris
Traceback (most recent call last):
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/lutris/gui/application.py", line 44, in <module>
    from lutris.gui.installerwindow import InstallerWindow, InstallationKind
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/lutris/gui/installerwindow.py", line 20, in <module>
    from lutris.installer import InstallationKind, get_installers, interpreter
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/lutris/installer/installer.py", line 14, in <module>
    from lutris.services import SERVICES
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/lutris/services/__init__.py", line 6, in <module>
    from lutris.services.battlenet import BattleNetService
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/lutris/services/battlenet.py", line 18, in <module>
    from lutris.util.battlenet.product_db_pb2 import ProductDb
  File "/mnt/data-linux/WINE-POPO-BUILD/1-BACKUP/lutris-git/lutris/lutris/util/battlenet/product_db_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

```
The official package still works thankfully except for AUR PKGBUILD

**Comment by rchris494** [comment]
i installed python3-protobuf & libprotobuf-dev on my debian bookworm and now the nightly finally launches again.

**Comment by Astrobald** [comment]
Also works on Manjaro with:

`sudo pip install protobuf`

or

`sudo pacman -S python-protobuf`

**Comment by Gnatzelle** [comment]
Works again after installing python-protobuf...thanks :)

**Comment by PrimaIVoid** [comment]
On Debian:
```
sudo pip install protobuf
sudo pip install google
```

**Comment by strycore** [comment]
the last error can be fixed with `sudo pip install protobuf==3.2.0`.

**Comment by strycore** [comment]
Lutris will no longer crash if protobuf isn't installed / is the wrong version. The Battle.net integration will simply be disabled.
