### ISSUE TITLE
ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by PrimaIVoid** [lutris/lutris#4731]
### Bug description

After updating Lutris from source to latest commit (https://github.com/lutris/lutris/commit/03581a121b78b935ff1b7cd8ce6b599b2485b569)
I receive this error:

```
File "/home/user/lutris/lutris/util/battlenet/product_db_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```
Previously i was using a recent commit from master, around 1/2 days ago
Might this 'google module' be a new dependency?

### How to Reproduce

1. From cloned Lutris folder (git clone [...](https://github.com/lutris/))
2. cd lutris
3. ./bin/lutris
4. Error

### Expected behavior

Able to launch Lutris without errors

### Log output

```shell
Traceback (most recent call last):
  File "/home/user/lutris/./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/user/lutris/lutris/gui/application.py", line 44, in <module>
    from lutris.gui.installerwindow import InstallerWindow, InstallationKind
  File "/home/user/lutris/lutris/gui/installerwindow.py", line 20, in <module>
    from lutris.installer import InstallationKind, get_installers, interpreter
  File "/home/user/lutris/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/home/user/lutris/lutris/installer/installer.py", line 14, in <module>
    from lutris.services import SERVICES
  File "/home/user/lutris/lutris/services/__init__.py", line 6, in <module>
    from lutris.services.battlenet import BattleNetService
  File "/home/user/lutris/lutris/services/battlenet.py", line 18, in <module>
    from lutris.util.battlenet.product_db_pb2 import ProductDb
  File "/home/user/lutris/lutris/util/battlenet/product_db_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

### System Information

```shell
Linux, Debian 11, amd64 4gb RAM, i5
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Astrobald** [comment]
Look like #4729
