### ISSUE TITLE
Allow running dosbox games without opusfile (custom dosbox executable)

### ISSUE THREAD

**Issue by Zaechus** [lutris/lutris#4736]
### Bug description

On NixOS, the lutris package doesn't have opusfile as a dependency which disables you from launching DOS games directly from Lutris. This is fine, but when you have a standalone package like dosbox-staging specified in the Lutris DOSBox runner settings, it still doesn't let you launch the game.

### How to Reproduce

1. Open Lutris on NixOS
2. Configure the DOSBox runner to use dosbox-staging as the custom executable
3. Install a DOS game
4. Run it

### Expected behavior

Launch the game in dosbox-staging without checking for dependencies since dosbox-staging runs fine by itself

### Log output

```shell
INFO     2023-02-05 12:44:05,600 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-02-05 12:44:05,655 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-02-05 12:44:05,696 [startup.check_driver:65]:Running AMD Mesa driver 22.3.4 on AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.42, 5.15.91) (0x1638)
INFO     2023-02-05 12:44:05,697 [startup.check_driver:77]:GPU: 1002:1638 17AA:5094 (amdgpu drivers)
DEBUG    2023-02-05 12:44:05,985 [lutriswindow.update_store:448]:Showing 28 games
INFO     2023-02-05 12:44:06,049 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-02-05 12:44:17,300 [grid.on_item_activated:57]:Item activated: 10
ERROR    2023-02-05 12:44:17,329 [jobs.target:36]:Error while completing task <bound method Runner.prelaunch of <lutris.runners.dosbox.dosbox object at 0x7f1744385870>>: <class 'lutris.exceptions.UnavailableLibrariesError'> The following  libraries are required but are not installed on your system:
libopusfile.so.0
ERROR    2023-02-05 12:44:17,373 [lutriswindow.on_game_error:718]:Warcraft: Orcs and Humans (dosbox) has encountered an error: The following  libraries are required but are not installed on your system:
libopusfile.so.0
Traceback (most recent call last):
  File "/nix/store/fm9yhl5qjvcw4jycv6rxnhrgi5m7kh1g-lutris-unwrapped-0.5.12/lib/python3.10/site-packages/lutris/exceptions.py", line 80, in wrapper
    result = function(*args, **kwargs)
  File "/nix/store/fm9yhl5qjvcw4jycv6rxnhrgi5m7kh1g-lutris-unwrapped-0.5.12/lib/python3.10/site-packages/lutris/game.py", line 476, in configure_game
    raise error
  File "/nix/store/fm9yhl5qjvcw4jycv6rxnhrgi5m7kh1g-lutris-unwrapped-0.5.12/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/nix/store/fm9yhl5qjvcw4jycv6rxnhrgi5m7kh1g-lutris-unwrapped-0.5.12/lib/python3.10/site-packages/lutris/runners/runner.py", line 267, in prelaunch
    raise UnavailableLibrariesError(unavailable_libs, self.arch)
lutris.exceptions.UnavailableLibrariesError: The following  libraries are required but are not installed on your system:
libopusfile.so.0
INFO     2023-02-05 12:44:31,182 [application.do_shutdown:898]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              NixOS 23.05 Stoat
Arch:            x86_64
Kernel:          5.15.91
Desktop:         sway
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 PRO 5850U with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             14.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.42, 5.15.91)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.4
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.4
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.4
Vulkan:          Supported
```

### Media (optional)

![image](https://user-images.githubusercontent.com/19353212/216840641-eb2dcab9-0914-4477-9ac0-2e91d1cc1a51.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I suppose we can disable this check if a custom DosBox executable has been set, but how is it DosBox-staging can work if libopusfile is not present?

Is it really installed, but we're detecting it or something like that?

**Comment by Zaechus** [comment]
The nixpkgs dosbox-staging package makes use of opusfile as an input, while their lutris package does not.

**Comment by danieljohnson2** [comment]
I don't understand what it means to 'make use of opusfile as a input'. How can it do that if it isn't installed?
