### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by tkalfaoglu** [lutris/lutris#4742]
### Bug description

When I finish my World of Warcraft game, Lutris displays the error
could not convert string to float(0.55555555555)  or something similar..

and the progress is never saved. It always shows "Time played: Never played"

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'
1. Launch game World of Warcraft
2. waste hours playing it
3. quit the game,
4. the error message is shown, and time played stays at "never"

### Expected behavior

No error message and actual counting of time wasted on that game

### Log output

```shell
[turgut@tkbiglaptop ~]$ lutris -d
ATTENTION: default value of option vblank_mode overridden by environment.
INFO     2023-02-10 23:11:03,193 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-02-10 23:11:03,265 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-02-10 23:11:03,310 [startup.check_driver:65]:Running AMD Mesa driver 22.3.4 on AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.9-200.fc37.x86_64) (0x67df)
INFO     2023-02-10 23:11:03,310 [startup.check_driver:77]:GPU: 1002:67DF 1043:1A60 (amdgpu drivers)
DEBUG    2023-02-10 23:11:03,588 [lutriswindow.update_store:448]:Showing 7 games
INFO     2023-02-10 23:11:03,609 [startup.update_runtimes:218]:Startup complete
WARNING  2023-02-10 23:11:04,873 [strings.get_formatted_playtime:127]:Invalid playtime value '0.00.020555555555555556'
WARNING  2023-02-10 23:11:06,129 [strings.get_formatted_playtime:127]:Invalid playtime value '0.00.020555555555555556'
ERROR    2023-02-10 23:11:06,295 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2023-02-10 23:11:06,296 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
WARNING  2023-02-10 23:11:06,413 [runner_interpreter.get_launch_parameters:60]:libstrangle is not available on this system, FPS limiter disabled
DEBUG    2023-02-10 23:11:06,431 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/turgut/Games/wow/firestorm/WoW Shadowlands 9.1.5 - FS"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:LD_LIBRARY_PATH="/home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/lib:/home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/lib64:/lib64:/lib:/usr/lib64/dyninst:/usr/lib64/pipewire-0.3/jack:/usr/lib64/iscsi:/usr/lib64/tcl8.6:/usr/lib:/usr/lib64:/home/turgut/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/turgut/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/turgut/.local/share/lutris/runtime/steam/i386/lib:/home/turgut/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/turgut/.local/share/lutris/runtime/steam/i386/usr/lib:/home/turgut/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/turgut/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/turgut/.local/share/lutris/runtime/steam/amd64/lib:/home/turgut/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/turgut/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:WINEARCH="win64"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:WINE="/home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/bin/wine"
DEBUG    2023-02-10 23:11:06,440 [command.start:141]:WINE_MONO_CACHE_DIR="/home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/mono"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/gecko"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/lib64/gstreamer-1.0/:/home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:WINEPREFIX="/home/turgut/.wine"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:WINEESYNC="1"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/turgut/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:PROTON_EAC_RUNTIME="/home/turgut/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:game_name="World of Warcraft"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/lib64/python311.zip:/usr/lib64/python3.11:/usr/lib64/python3.11/lib-dynload:/usr/lib64/python3.11/site-packages:/usr/lib/python3.11/site-packages"
DEBUG    2023-02-10 23:11:06,441 [command.start:141]:LUTRIS_GAME_UUID="7f27740d-13de-4b72-9074-dc91a3197316"
WARNING  2023-02-10 23:11:06,467 [strings.get_formatted_playtime:127]:Invalid playtime value '0.00.020555555555555556'
Discord ID: 356875762940379136
INFO     2023-02-10 23:11:06,468 [game.start_game:586]:Discord RPC Disabled or Discord APP ID Not Present
lutris-wrapper: World of Warcraft
Started initial process 100053 from gamemoderun /home/turgut/.local/share/lutris/runners/wine/lutris-GE-Proton7-33-x86_64/bin/wine /home/turgut/Games/wow/firestorm/WoW Shadowlands 9.1.5 - FS/WoW 9.2.7 Firestorm.exe
Start monitoring process.
gamemodeauto: 
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
Initial process has exited (return code: 0)
Monitored process exited.
Exit with return code 0
DEBUG    2023-02-10 23:11:25,473 [command.on_stop:195]:Process 100051 has terminated with code 0
DEBUG    2023-02-10 23:11:26,482 [game.beat:694]:Game thread stopped
WARNING  2023-02-10 23:11:26,482 [game.on_game_quit:731]:Game still running (state: running)
INFO     2023-02-10 23:11:26,482 [game.stop:705]:Stopping World of Warcraft (wine)
DEBUG    2023-02-10 23:11:26,483 [game.stop_game:664]:World of Warcraft (wine) has run for 20 seconds
WARNING  2023-02-10 23:11:26,510 [strings.get_formatted_playtime:127]:Invalid playtime value '0.00.020555555555555556'
ERROR    2023-02-10 23:11:26,511 [lutriswindow.on_game_error:718]:World of Warcraft (wine) has encountered an error: could not convert string to float: '0.00.020555555555555556'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 80, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 695, in beat
    self.on_game_quit()
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 732, in on_game_quit
    self.stop()
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 713, in stop
    self.stop_game()
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 676, in stop_game
    self.playtime += str(float(self.playtime)+ (float(self.timer.duration) / 3600))
                         ^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '0.00.020555555555555556'
```

### System Information

```shell
[System]
OS:              Fedora Linux 37 Workstation Edition
Arch:            x86_64
Kernel:          6.1.9-200.fc37.x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 1700 Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.9-200.fc37.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.4
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.4
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.4
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by tkalfaoglu** [comment]
OK, I fixed this with:

[root@tkbiglaptop lutris]# diff game.py ~turgut
675c675,678
<             self.playtime += self.timer.duration / 3600
---
>             self.playtime = float(self.playtime)
>             self.playtime += float(self.timer.duration) / 3600.0
> #            self.playtime = 5.0
> #            self.playtime += float(self.playtime) + (float(self.timer.duration) / 3600)

please put this into the main code..

**Comment by danieljohnson2** [comment]
I don't think we need it, because we've already got PR #4650 merged (12/12/22). I believe that should be enough.

Perhaps try the 0.5.13 beta and see if your bug still occurs with that?
