### ISSUE TITLE
Wine prefix created before checking if exe exists

### ISSUE THREAD

**Issue by Zykino** [lutris/lutris#4765]
### Bug description

The EGS disappeared from my PC and I see no way to re-install it.
```sh
$ ls /mnt/Data/Games/Lutris/epic-games-store/drive_c/Program\ Files\ \(x86\)/
'Common Files'  'Internet Explorer'  'Windows Media Player'  'Windows NT'
```
Apparently lutris try to start EGS from `/mnt/Data/Games/Lutris/epic-games-store/drive_c/Program\ Files\ \(x86\)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe`, but as seen above, there is no "Epic Games" folder there.
I do not find a way to re-install EGS. Starting a game that was installed say that the binary is not present/no permission to start it.
And trying to install a new EGS game give the same kind of error.

_Notes:_
* /mnt/Data is a different hard drive than / (which contains /home)
* in the `lutris -d` output I first try to start a game that is shown as installed, then I try installing a game
* **Auxiliary bug:** the logs from `lutris -d` are in french and any accentuated letter is missing, ex: êéèàù
> Le programme n'a pas pu tre lanc, ou aucun programme n'est associ au fichier spcifi.
ShellExecuteEx a chou: Chemin introuvable.

should be:
> Le programme n'a pas pu **ê**tre lanc**é**, ou aucun programme n'est associ**é** au fichier sp**é**cifi**é**.
ShellExecuteEx a **é**chou**é**: Chemin introuvable.

### How to Reproduce

Steps to reproduce the behavior (I think it is what removed it):
1. Install an EGS game (install the launcher, install the game inside, leave all, start the game, play, repeat)
2. a. Try installing a new game (in my case First class Trouble) that fail the installation.
2. b. Cancel the install when you see 
> Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
2. c. See the popup asking you to cancel the install. (I think I checked the box "Delete the game files". I don’t really remember)
3. Try starting a game already installed -> EGS.exe not found
4. Try installing a new EGS game -> EGS.exe not found

### Expected behavior

Canceling an install should remove the game’s files, not the launcher. Even if the checkbox is checked (or the French translation is non-obvious to me).
If the launcher is uninstalled, there should be a way to re-install it.

### Log output

```shell
INFO     2023-03-05 11:06:13,028 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-03-05 11:06:13,103 [startup.check_driver:57]:Using NVIDIA drivers 525.85.05 for x86_64
INFO     2023-03-05 11:06:13,103 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1070 Ti
INFO     2023-03-05 11:06:13,103 [startup.check_driver:77]:GPU: 10DE:1B82 1043:8620 (nvidia drivers)
DEBUG    2023-03-05 11:06:13,446 [lutriswindow.update_store:448]:Showing 92 games
DEBUG    2023-03-05 11:06:13,516 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2023-03-05 11:06:13,668 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-03-05 11:06:13,794 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2023-03-05 11:06:13,945 [http.write_to_file:142]:Writing to /home/zykino/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2023-03-05 11:06:13,947 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-03-05 11:06:14,080 [http.write_to_file:142]:Writing to /home/zykino/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2023-03-05 11:06:14,081 [http._request:88]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2023-03-05 11:06:14,211 [http.write_to_file:142]:Writing to /home/zykino/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2023-03-05 11:06:14,212 [http._request:88]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2023-03-05 11:06:14,323 [http.write_to_file:142]:Writing to /home/zykino/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2023-03-05 11:06:14,324 [http._request:88]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2023-03-05 11:06:14,453 [http.write_to_file:142]:Writing to /home/zykino/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2023-03-05 11:06:14,454 [startup.update_runtimes:218]:Startup complete
ERROR    2023-03-05 11:06:25,347 [lutriswindow.on_game_error:718]:Insurmountable (wine) has encountered an error: Le fichier /mnt/Data/Games/Lutris/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe n'a pas pu être trouvé
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 80, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 477, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 446, in get_gameplay_info
    raise self.get_config_error(gameplay_info)
lutris.exceptions.GameConfigError: Le fichier /mnt/Data/Games/Lutris/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe n'a pas pu être trouvé
DEBUG    2023-03-05 11:06:44,170 [grid.on_item_activated:57]:Item activated: 61e074e998044594b7bb566fe111687b
DEBUG    2023-03-05 11:06:44,170 [lutriswindow.on_game_activated:857]:Looking up egs game 61e074e998044594b7bb566fe111687b
DEBUG    2023-03-05 11:06:44,212 [application.show_window:328]:Showing window InstallerWindow61e074e998044594b7bb566fe111687b
DEBUG    2023-03-05 11:06:47,882 [displayconfig.get_current_resolution:643]:Retrieving current resolution
DEBUG    2023-03-05 11:06:47,910 [installerwindow.show_installer_files_screen:339]:Installer doesn't require files
DEBUG    2023-03-05 11:06:47,914 [interpreter._iter_commands:322]:Installer command: {'task': {'name': 'wineexec', 'executable': '/mnt/Data/Games/Lutris/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe', 'args': '-opengl -SkipBuildPatchPrereq -com.epicgames.launcher://apps/61e074e998044594b7bb566fe111687b?action=install', 'prefix': '/mnt/Data/Games/Lutris/epic-games-store'}}
DEBUG    2023-03-05 11:06:48,034 [wine.use_lutris_runtime:121]:/home/zykino/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine is provided by Lutris, using runtime
WARNING  2023-03-05 11:06:48,041 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,041 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,041 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,042 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,042 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,042 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,042 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,043 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,043 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,043 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,043 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,057 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,057 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,069 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,069 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,069 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,069 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,069 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,074 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,074 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,074 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,074 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,074 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,075 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,075 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,075 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,075 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,075 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,076 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,076 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,076 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,076 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,076 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,089 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,089 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,089 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,090 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,090 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,093 [runner.game_config:86]:Accessing game config while runner wasn't given one.
WARNING  2023-03-05 11:06:48,093 [runner.game_config:86]:Accessing game config while runner wasn't given one.
ERROR    2023-03-05 11:06:48,093 [wine.game_exe:519]:The game doesn't have an executable
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/zykino/.cache/lutris/shaders/wine"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:LD_LIBRARY_PATH="/home/zykino/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/lib:/home/zykino/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/lib64:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/lib32:/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/i386-linux-gnu/sse2:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib64:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/zykino/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/zykino/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/zykino/.local/share/lutris/runtime/steam/i386/lib:/home/zykino/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/zykino/.local/share/lutris/runtime/steam/i386/usr/lib:/home/zykino/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/zykino/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/zykino/.local/share/lutris/runtime/steam/amd64/lib:/home/zykino/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/zykino/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINEARCH="win64"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINE="/home/zykino/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINE_MONO_CACHE_DIR="/home/zykino/.local/share/lutris/runners/wine/lutris-ge-lol-7.14-1-x86_64/mono"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/zykino/.local/share/lutris/runners/wine/lutris-ge-lol-7.14-1-x86_64/gecko"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/zykino/.local/share/lutris/runners/wine/lutris-ge-lol-7.14-1-x86_64/lib64/gstreamer-1.0/:/home/zykino/.local/share/lutris/runners/wine/lutris-ge-lol-7.14-1-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINEPREFIX="/mnt/Data/Games/Lutris/epic-games-store"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINEESYNC="1"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/zykino/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:PROTON_EAC_RUNTIME="/home/zykino/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:WINEDLLOVERRIDES="winemenubuilder="
DEBUG    2023-03-05 11:06:48,093 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/home/zykino/.local/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2023-03-05 11:06:48,094 [command.start:141]:LUTRIS_GAME_UUID="41142bae-96a0-4f67-b8dc-0bfbfa96297e"
Started initial process 5534 from /home/zykino/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /mnt/Data/Games/Lutris/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq -com.epicgames.launcher://apps/61e074e998044594b7bb566fe111687b?action=install
Start monitoring process.
fsync: up and running.
Le programme n'a pas pu tre lanc, ou aucun programme n'est associ au fichier spcifi.
ShellExecuteEx a chou: Chemin introuvable.

Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
DEBUG    2023-03-05 11:06:50,342 [command.on_stop:195]:Process 5528 has terminated with code 256
DEBUG    2023-03-05 11:06:51,095 [commands._monitor_task:454]:Return code: 256
ERROR    2023-03-05 11:06:51,096 [errors.__init__:18]:La commande s'est terminée avec le code 256
None
INFO     2023-03-05 11:09:45,100 [interpreter.revert:385]:Cancelling installation of Recipe for Disaster
DEBUG    2023-03-05 11:09:45,185 [wine.winekill:172]:Killing all wine processes: ['/home/zykino/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wineserver', '-k']
DEBUG    2023-03-05 11:09:45,185 [wine.winekill:173]:   Wine prefix: /mnt/Data/Games/Lutris/epic-games-store
DEBUG    2023-03-05 11:09:45,185 [wine.winekill:174]:   Wine arch: win64
DEBUG    2023-03-05 11:09:45,186 [wine.winekill:180]:Waiting for wine processes to terminate
DEBUG    2023-03-05 11:09:45,186 [wine.winekill:196]:Done waiting.
DEBUG    2023-03-05 11:09:45,186 [system.remove_folder:291]:Removing folder /home/zykino/.cache/lutris/installer/recipe-for-disaster
DEBUG    2023-03-05 11:09:45,187 [application.on_app_window_destroyed:346]:Removed window InstallerWindow61e074e998044594b7bb566fe111687b
DEBUG    2023-03-05 11:12:47,569 [application.show_window:328]:Showing window PreferencesDialog{}
DEBUG    2023-03-05 11:14:08,107 [application.on_app_window_destroyed:346]:Removed window PreferencesDialog{}
INFO     2023-03-05 11:21:13,014 [application.do_shutdown:898]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          6.1.11-76060111-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            22.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.85.05
OpenGL Core:     4.6.0 NVIDIA 525.85.05
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.85.05
Vulkan:          Supported
```

### Media (optional)

Talking about this cancel install’s checkbox.
![image](https://user-images.githubusercontent.com/3809938/222956306-10da950f-57c3-44f2-9eaf-ce7b8cff5bda.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
You started EGS while the drive EGS was installed on wasn't mounted.
This made Lutris create a new Wine prefix which doesn't contain EGS.
We need to check for executable presence *before* the prefix creation stuff.

**Comment by Zykino** [comment]
Hmmm yeah, maybe the drive did not mount and I tried to start EGS (or maybe something else?) which broke Lutris.
I honestly do not know how I broke it, sorry.

**Comment by strycore** [comment]
Lutris isn't broken. If you have created an empty prefix because a drive wasn't mounted, you can delete it, mount the drive and relaunch EGS. Everything should work fine.
