### ISSUE TITLE
battle.net installer crashes lutris

### ISSUE THREAD

**Issue by kstenerud** [lutris/lutris#4779]
### Bug description

When I try to run the battle.net installer, lutris throws an exception.

### How to Reproduce

1. Follow https://github.com/lutris/docs/blob/master/Battle.Net.md
2. Try to run the battle.net installer from within lutris

### Expected behavior

I expected it to install battle.net

### Log output

```shell
$ lutris -d
2023-03-20 17:15:34,729: Starting Lutris 0.5.9.1
2023-03-20 17:15:34,733: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,733: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,733: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,733: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,733: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,733: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,734: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,734: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,734: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,734: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,734: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,734: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,737: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,738: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,738: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,738: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,748: No cores found
2023-03-20 17:15:34,769: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,770: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,771: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,771: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,772: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,772: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,772: Loading of DXVK versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of VKD3D versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of D3D Extras versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:34,773: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2023-03-20 17:15:35,662: Startup complete
INFO     2023-03-20 17:15:35,663 [startup.check_driver:61]:Running AMD Mesa driver 23.0.0 on AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.47, 5.19.0-35-generic) (0x73ff)
INFO     2023-03-20 17:15:35,664 [startup.check_driver:73]:GPU: 1002:73FF 1462:5020 (amdgpu drivers)
DEBUG    2023-03-20 17:15:35,834 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2023-03-20 17:15:42,433 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2023-03-20 17:15:42,434 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2023-03-20 17:15:47,328 [http.get:81]:GET https://lutris.net/api/games?search=battle.net
DEBUG    2023-03-20 17:15:47,889 [lutriswindow.update_store:451]:Showing 2 games
WARNING  2023-03-20 17:15:50,382 [lutriswindow.on_game_selection_changed:779]:No game found. Replacing with placeholder {'id': 'battlenet', 'appid': 'battlenet', 'name': 'Blizzard Battle.net', 'slug': 'battlenet', 'service': 'lutris'}
DEBUG    2023-03-20 17:15:53,586 [__init__.fetch_script:22]:Fetching installer https://lutris.net/api/installers/battlenet
DEBUG    2023-03-20 17:15:53,586 [http.get:81]:GET https://lutris.net/api/installers/battlenet
DEBUG    2023-03-20 17:15:53,775 [application.show_window:259]:Showing window <class 'lutris.gui.installerwindow.InstallerWindow'>battlenet
DEBUG    2023-03-20 17:15:56,407 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 160, in launch_install
    self.runners_to_install = self.get_runners_to_install()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 228, in get_runners_to_install
    if not runner.is_installed(**params):
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 548, in is_installed
    return system.path_exists(self.get_executable(version, fallback))
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 524, in get_executable
    wine_path = self.get_path_for_version(version)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 505, in get_path_for_version
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 160, in launch_install
    self.runners_to_install = self.get_runners_to_install()
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 228, in get_runners_to_install
    if not runner.is_installed(**params):
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 548, in is_installed
    return system.path_exists(self.get_executable(version, fallback))
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 524, in get_executable
    wine_path = self.get_path_for_version(version)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 505, in get_path_for_version
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'
```

### System Information

```shell
[System]
OS:              KDE neon 22.04 jammy
Arch:            x86_64
Kernel:          5.19.0-35-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.47, 5.19.0-35-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.0 - kisak-mesa PPA
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.0 - kisak-mesa PPA
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.0 - kisak-mesa PPA
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I think this is issue #4198, fixed in 0.5.10. You're on a very old release; you should upgrade to something more recent.

**Comment by legluondunet** [comment]
Hello, is this issue still relevant? Did you test with a more recent Lutris version?

**Comment by kstenerud** [comment]
Hi sorry, I tried a more recent version and had the same problem. Eventually I gave up and ran it under Steam instead.

**Comment by danieljohnson2** [comment]
I am quite confident that you did not have the *same* problem; you must have had a different one. The debug log would have been different.

The code listed in that trace-back has changed. It was fixed (and moved!) in 0.5.10.

Any Lutris later than 0.5.9.1 would not point at line 161 like that.

**Comment by kstenerud** [comment]
Yes, it could very well have been a different issue. I was getting frustrated at this point which is why I opted for a different approach. Sorry, this report is probably not going to be very useful since I don't have lutris installed anymore...

**Comment by danieljohnson2** [comment]
I think we can close this one, then.

**Comment by danieljohnson2** [comment]
... we can if I can figure out how to GitHub anyway.
