### ISSUE TITLE
Can't set attribute 'runner' message

### ISSUE THREAD

**Issue by Smoukus** [lutris/lutris#4792]
### Bug description

As of the latest lutris-git version (latest commit 502952930ae93ea88b49eb0fb4c7020026615706), it's impossible to `Save` any changes in the Window when you `right click on game -> configure`. After clicking on `Save`, you get the following message:
![image](https://user-images.githubusercontent.com/48409293/229205846-1ea6be96-e800-49e4-8569-9f7b914615f2.png)

It doesn't matter if you changed anything in the window or not, the message always appears.

Here is the video of me demonstrating it:

https://user-images.githubusercontent.com/48409293/229206741-92e69875-2b1e-4771-b744-ad5bdfe565ef.mp4

### How to Reproduce

1. Right click any game
2. Press on Configure
3. Change anything if you want (not needed for bug to occur)
4. Press Save

### Expected behavior

Settings are saved, and window disappears

### Log output

```shell
INFO     2023-03-31 20:55:46,013 [startup.init_lutris:190]:Starting Lutris 0.5.13
DEBUG    2023-03-31 20:55:46,042 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-03-31 20:55:46,064 [startup.check_driver:72]:Running AMD Mesa driver 23.1.0 on AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.0-rc4-273-tkg-cfs) (0x73bf)
INFO     2023-03-31 20:55:46,064 [startup.check_driver:84]:GPU: 1002:73BF 1EAE:6701 (amdgpu drivers)
DEBUG    2023-03-31 20:55:47,922 [application.show_window:339]:Showing window EditGameConfigDialog2
ERROR    2023-03-31 20:55:48,936 [exceptions.wrapper:63]:can't set attribute 'runner'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/lutris/gui/config/common.py", line 591, in on_save
    self.game.runner = runner
AttributeError: can't set attribute 'runner'
DEBUG    2023-03-31 20:55:50,257 [application.on_app_window_destroyed:357]:Removed window EditGameConfigDialog2
INFO     2023-03-31 20:55:51,029 [application.do_shutdown:960]:Shutting down Lutris
```
```


### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.3.0-rc4-273-tkg-cfs
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.2 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.0-rc4-273-tkg-cfs)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.0-devel (git-4faa0c2f10)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.0-devel (git-4faa0c2f10)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.0-devel (git-4faa0c2f10)
Vulkan:          Supported

```
```


### Media (optional)

_No response_

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by kellerman** [comment]
I just wanted to post about this issue, but @Smoukus was quicker. The issue started after this commit I suppose:
https://github.com/lutris/lutris/commit/502952930ae93ea88b49eb0fb4c7020026615706

**Comment by danieljohnson2** [comment]
Whoops, I missed a trick. We need to be able to replace the config and runner on the fly.

Hopefully it will be okay now. Sorry about that!
