### ISSUE TITLE
Allow us to use the GOG installers for local files when not signed into GOG

### ISSUE THREAD

**Issue by JackH3103** [lutris/lutris#4804]
### Bug description

I like to buy games from GOG and then store the installers locally on an external hard drive. If I want to install these through Lutris, I have to sign into GOG just to be able to run the installer scripts (presumably because the script has the option to download files from GOG's cdn).

It would be nice if the GOG installer scripts would without the login functionality. One of the main reasons I use GOG is for offline installations.

### How to Reproduce

1. Click "Add Game"
2. Click "Search the Lutris website for installers"
3. Search for "Lego DC Super-Villains"

Observed result:
Only the "Steam Proton" script is available.

### Expected behavior

There should be a GOG version available. (There is a GOG script but you have to be signed into a GOG account and search from the GOG tab to see it.)

If the user is not signed into GOG, then the installer should require us to provide local files. If they are signed in, then run the installer with login functionality.

### Log output

```shell
jack@localhost:~> lutris -d

(lutris:10434): Gtk-WARNING **: 18:31:07.364: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(lutris:10434): Gtk-WARNING **: 18:31:07.364: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
jack@localhost:~> lutris -d

(lutris:10476): Gtk-WARNING **: 18:31:15.858: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(lutris:10476): Gtk-WARNING **: 18:31:15.858: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
INFO     2023-04-08 18:31:16,736 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-04-08 18:31:16,782 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-04-08 18:31:17,121 [startup.check_driver:57]:Using NVIDIA drivers 525.105.17 for x86_64
INFO     2023-04-08 18:31:17,121 [startup.check_driver:61]:GPU: NVIDIA GeForce 840M
INFO     2023-04-08 18:31:17,122 [startup.check_driver:77]:GPU: 10DE:1341 1028:0656 (nvidia drivers)
INFO     2023-04-08 18:31:17,122 [startup.check_driver:77]:GPU: 8086:1616 1028:0656 (i915 drivers)
DEBUG    2023-04-08 18:31:17,417 [lutriswindow.update_store:448]:Showing 143 games
INFO     2023-04-08 18:31:17,880 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-04-08 18:31:21,283 [application.show_window:328]:Showing window AddGamesWindow{}
DEBUG    2023-04-08 18:31:29,706 [http._request:88]:GET https://lutris.net/api/games?search=lego+dc+super-villains&with-installers=True
DEBUG    2023-04-08 18:31:31,948 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/lego-dc-super-villains
DEBUG    2023-04-08 18:31:31,948 [http._request:88]:GET https://lutris.net/api/installers/lego-dc-super-villains
DEBUG    2023-04-08 18:31:32,166 [application.show_window:328]:Showing window InstallerWindowlego-dc-super-villains
DEBUG    2023-04-08 18:31:32,167 [application.on_app_window_destroyed:346]:Removed window AddGamesWindow{}
```

### System Information

```shell
[System]
OS:              openSUSE Tumbleweed 20230407 n/a
Arch:            x86_64
Kernel:          6.2.9-1-default
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.7 GB
Swap:            2.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.1
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
That's going to be tricky since we also use the fact that the user is signed to GOG to query the API for more information about a game. For example, the platforms for a GOG game will tell us if we should create a Linux native installer or a Wine installer. 
We do have the ability to install a game from a setup file so that's your best option for now.

Once we migrate to a more metadata based approach for automated installers, we won't need to query the GOG API so we should be able to provide installers without having to sign in.

**Comment by danieljohnson2** [comment]
Well, one deficiency you still have is that installing from an executable only works for WINE games; actual Linux games can't be installed like this.

**Comment by strycore** [comment]
I would like to add support for Linux and DOS games in the install from executable dialog. Should be fairly simple.

**Comment by pizzamountain** [comment]
Offline GOG installer scripts seem to be broken. I've tried installing Rayman 2 through this script with an offline GOG installer: [](https://lutris.net/games/install/12468/view)

It throws an error saying "You are not authenticated to gog". I've used this one before and it worked fine, which is strange.

No critical errors occurred when installing on 0.15.12.

Now, here's the log for using script on 0.15.13: 
```
INFO     2023-05-30 00:51:20,987 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-05-30 00:51:20,989 [startup.check_driver:73]:Running AMD Mesa driver 22.2.5 on AMD Radeon Graphics (raven, LLVM 15.0.6, DRM 3.47, 5.19.0-42-generic) (0x15d8)
INFO     2023-05-30 00:51:20,989 [startup.check_driver:85]:GPU: 1002:15D8 1414:0034 (amdgpu drivers)
DEBUG    2023-05-30 00:51:21,174 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-30 00:51:21,216 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-05-30 00:51:23,056 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-05-30 00:51:26,731 [http._request:88]:GET https://lutris.net/api/games?search=rayman+2&with-installers=True
DEBUG    2023-05-30 00:51:28,780 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/rayman-2
DEBUG    2023-05-30 00:51:28,780 [http._request:88]:GET https://lutris.net/api/installers/rayman-2
DEBUG    2023-05-30 00:51:29,395 [application.show_window:339]:Showing window InstallerWindowrayman-2
DEBUG    2023-05-30 00:51:29,396 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}
DEBUG    2023-05-30 00:51:30,085 [application.on_app_window_destroyed:357]:Removed window InstallerWindowrayman-2
DEBUG    2023-05-30 00:51:32,116 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-05-30 00:51:35,296 [http._request:88]:GET https://lutris.net/api/games?search=rayman+2&with-installers=True
DEBUG    2023-05-30 00:51:40,238 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/rayman-2-the-great-escape
DEBUG    2023-05-30 00:51:40,239 [http._request:88]:GET https://lutris.net/api/installers/rayman-2-the-great-escape
DEBUG    2023-05-30 00:51:41,501 [application.show_window:339]:Showing window InstallerWindowrayman-2-the-great-escape
DEBUG    2023-05-30 00:51:41,502 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}
DEBUG    2023-05-30 00:51:48,253 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-05-30 00:51:50,190 [runner.get_runner_version:480]:Getting runner information for wine (version: lutris-GE-Proton8-7-x86_64)
DEBUG    2023-05-30 00:51:50,190 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2023-05-30 00:51:50,458 [interpreter.get_runners_to_install:264]:Default wine version is lutris-GE-Proton8-7
DEBUG    2023-05-30 00:51:50,479 [gog.get_extras:320]:Download extras for GOG ID 1207658940 and its DLCs
INFO     2023-05-30 00:51:50,479 [gog.get_game_details:286]:Getting game details for 1207658940
WARNING  2023-05-30 00:51:50,479 [gog.get_extras:323]:Unable to get GOG data for game 1207658940
ERROR    2023-05-30 00:51:50,480 [exceptions.wrapper:63]:You are not authenticated to gog
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 563, in on_extras_ready
    if not self.load_installer_files_page():
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 579, in load_installer_files_page
    self.interpreter.installer.prepare_game_files(patch_version)
  File "/usr/lib/python3/dist-packages/lutris/installer/installer.py", line 162, in prepare_game_files
    raise AuthenticationError(_("You are not authenticated to %s") % self.service.id)
lutris.exceptions.AuthenticationError: You are not authenticated to gog
```

**Comment by strycore** [comment]
This is fixed in https://github.com/lutris/lutris/commit/3b64e70e2a2a4f90e2679b12f9f2bf56cb0a5986
