### ISSUE TITLE
installgamedialog.py Error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#481]
made a booboo this morning and found a bug :smile_cat: 

```
[http]:Unavailable url (https://lutris.net/games/install/gran-turismo-2/): HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/user01/src/lutris/lutris/util/jobs.py", line 38, in <lambda>
    GLib.idle_add(lambda: self.callback(result, error))
  File "/home/user01/src/lutris/lutris/gui/installgamedialog.py", line 120, in on_scripts_obtained
    self.run_no_installer_dialog()
  File "/home/user01/src/lutris/lutris/gui/installgamedialog.py", line 141, in run_no_installer_dialog
    self.parent.window,
AttributeError: 'LutrisWindow' object has no attribute 'window'
```

**Comment by TingPing** [comment]
The fix is changing `self.parent.window` to `self.parent`.
