### ISSUE TITLE
[Flatpak] PCSX2: The following i386 libraries are required but are not installed on your system: libgdk-x11-2.0.so.0

### ISSUE THREAD

**Issue by JoshuaFern** [lutris/lutris#4814]
### Bug description

Launching PCSX2 results in the error: `The following i386 libraries are required but are not installed on your system: libgdk-x11-2.0.so.0`

### How to Reproduce

1. Install Lutris in a Flatpak and install the PCSX2 runner.
2. Add a PS2 game and try to run it.
3. Receive the error: `The following i386 libraries are required but are not installed on your system: libgdk-x11-2.0.so.0`

### Expected behavior

The game should run properly.

### Log output

```shell
  ~ ❯ flatpak run net.lutris.Lutris -d
INFO     2023-04-17 12:31:03,310 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-04-17 12:31:03,370 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-04-17 12:31:03,441 [mame.write_mame_xml:22]:Writing full game list from MAME to /home/jdf/.var/app/net.lutris.Lutris/cache/lutris/mame/mame.xml
DEBUG    2023-04-17 12:31:03,443 [system.execute:57]:Executing /home/jdf/.var/app/net.lutris.Lutris/data/lutris/runners/mame/mame -listxml
DEBUG    2023-04-17 12:31:03,443 [system.execute:63]:LD_LIBRARY_PATH=/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/Ubuntu-18.04-i686:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/lib:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/usr/lib:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/Ubuntu-18.04-x86_64:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/lib:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/usr/lib PATH=/home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/network-tools:/app/bin:/usr/bin:/app/utils/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/app/jre/bin/
INFO     2023-04-17 12:31:03,446 [startup.check_driver:57]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-04-17 12:31:03,446 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1060 3GB
INFO     2023-04-17 12:31:03,446 [startup.check_driver:77]:GPU: 10DE:1C02 3842:6160 (nvidia drivers)
WARNING  2023-04-17 12:31:03,491 [mame.write_xml_list:253]:Couldn't get any output for mame -listxml
WARNING  2023-04-17 12:31:03,491 [mame.write_mame_xml:26]:MAME did not write anything to /home/jdf/.var/app/net.lutris.Lutris/cache/lutris/mame/mame.xml
DEBUG    2023-04-17 12:31:03,611 [lutriswindow.update_store:448]:Showing 1 games
DEBUG    2023-04-17 12:31:03,629 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2023-04-17 12:31:04,026 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-04-17 12:31:04,407 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2023-04-17 12:31:04,688 [http.write_to_file:142]:Writing to /home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2023-04-17 12:31:04,690 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-04-17 12:31:04,959 [http.write_to_file:142]:Writing to /home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2023-04-17 12:31:04,960 [http._request:88]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2023-04-17 12:31:05,221 [http.write_to_file:142]:Writing to /home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2023-04-17 12:31:05,222 [http._request:88]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2023-04-17 12:31:05,427 [http.write_to_file:142]:Writing to /home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2023-04-17 12:31:05,428 [http._request:88]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2023-04-17 12:31:05,825 [http.write_to_file:142]:Writing to /home/jdf/.var/app/net.lutris.Lutris/data/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
DEBUG    2023-04-17 12:31:05,826 [http._request:88]:POST https://lutris.net/api/games
DEBUG    2023-04-17 12:31:06,354 [lutris.sync_media:197]:Syncing 0 banners, 0 icons and 1 covers
DEBUG    2023-04-17 12:31:06,355 [http._request:88]:GET https://lutris.net/media/igdb/cover_big/co1ovo.jpg
DEBUG    2023-04-17 12:31:06,673 [http.write_to_file:142]:Writing to /home/jdf/.var/app/net.lutris.Lutris/cache/lutris/coverart/gran-turismo-4-prologue.jpg
INFO     2023-04-17 12:31:06,674 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-04-17 12:31:09,273 [grid.on_item_activated:57]:Item activated: 4
ERROR    2023-04-17 12:31:09,278 [jobs.target:36]:Error while completing task <bound method Runner.prelaunch of <lutris.runners.pcsx2.pcsx2 object at 0x7f2d262b67d0>>: <class 'lutris.exceptions.UnavailableLibrariesError'> The following i386 libraries are required but are not installed on your system:
libgdk-x11-2.0.so.0
  File "/app/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/lutris/runners/runner.py", line 267, in prelaunch
    raise UnavailableLibrariesError(unavailable_libs, self.arch)
ERROR    2023-04-17 12:31:09,291 [lutriswindow.on_game_error:718]:Gran Turismo 4 - Prologue (pcsx2) has encountered an error: The following i386 libraries are required but are not installed on your system:
libgdk-x11-2.0.so.0
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/lutris/exceptions.py", line 80, in wrapper
    result = function(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/lutris/game.py", line 476, in configure_game
    raise error
  File "/app/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/lutris/runners/runner.py", line 267, in prelaunch
    raise UnavailableLibrariesError(unavailable_libs, self.arch)
lutris.exceptions.UnavailableLibrariesError: The following i386 libraries are required but are not installed on your system:
libgdk-x11-2.0.so.0
```
```


### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.2.9-zen1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            7.8 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by legluondunet** [comment]
Our old PCSX2 runner needs an update.
@strycore please could you review my pullrequest: https://github.com/lutris/lutris/pull/4815

**Comment by legluondunet** [comment]
@JoshuaFern issue should be fixed now.
Uninstall and reinstall PCSX2 runner.
