### ISSUE TITLE
When i tried to install lutris and this happens

### ISSUE THREAD

**Issue by nikolas-marques** [lutris/lutris#4823]
### Bug description

I tried for the fist time installing lutris but this error ocuraded:

i tried an sudo apt install libgtk-3-dev but didn't work

(sorry for anything, this is my fist issue and english is not my fist language)

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

i expected to lutris to run 

### Log output

```shell
** (process:46033): WARNING **: 17:23:39.786: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 33, in <module>
    from gi.repository import Gio, GLib, Gtk, GObject
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gdk.py", line 83, in <module>
    Color = override(Color)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```

### System Information

```shell
linux Xubuntu 22.04
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I don't know how you got into this situation but you have a library mismatch for GDK3 about something Wayland related. 
This is not going to be solved by installing the Gtk3 development libraries.

First make sure your system is fully up to date and that you don't have any errors regarding your Ubuntu repositories.
Also make sure you're not using any PPA that might override system libraries such as GTK, GDK or Wayland.
Last, make sure you're not using Wayland, XFCE is still X11 only afaik.

**Comment by strycore** [comment]
Closing the issue since it this doesn't follow the standard way of installing Lutris.
