### ISSUE TITLE
Lutris doesn't launch with error "AttributeError: 'NoneType' object has no attribute 'items'"

### ISSUE THREAD

**Issue by Ciel-MC** [lutris/lutris#4825]
### Bug description

Can't launch Lutris on latest git.

### How to Reproduce

Run lutris from GitHub as instructed in README

### Expected behavior

Lutris launches

### Log output

```shell
Traceback (most recent call last):
  File "/home/ciel/lutris/./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/ciel/lutris/lutris/gui/application.py", line 40, in <module>
    from lutris.game import Game, export_game, import_game
  File "/home/ciel/lutris/lutris/game.py", line 24, in <module>
    from lutris.runners.wine import get_wine_version
  File "/home/ciel/lutris/lutris/runners/wine.py", line 23, in <module>
    from lutris.util.wine.dxvk import DXVKManager
  File "/home/ciel/lutris/lutris/util/wine/dxvk.py", line 17, in <module>
    class DXVKManager(DLLManager):
  File "/home/ciel/lutris/lutris/util/wine/dxvk.py", line 23, in DXVKManager
    vulkan_api_version = vkquery.get_expected_api_version_tuple()
  File "/home/ciel/lutris/lutris/util/graphics/vkquery.py", line 354, in get_expected_api_version_tuple
    _best_dev_name, best_dev_version = get_best_device_info()
  File "/home/ciel/lutris/lutris/util/graphics/vkquery.py", line 341, in get_best_device_info
    devices_dict.items(),
AttributeError: 'NoneType' object has no attribute 'items'
```

### System Information

```shell
**Note: Since it's a crash issue, this is obtained using latest stable Lutris, not Git/AUR**

[System]
OS:              Arch Linux  
Arch:            x86_64
Kernel:          6.2.12-arch1-1
Desktop:         hyprland
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5950X 16-Core Processor
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (gfx1100, LLVM 15.0.7, DRM 3.49, 6.2.12-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.2
Vulkan:          Not Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I begin to feel it would have been better just to use exceptions throughout this Vulkan stuff, really. But that would require lots of catching, and it's not Lutris's style.

I've changed one method to return an empty dict instead of None, and added some more checks as well. Should do better now.
