### ISSUE TITLE
undefined symbol: g_variant_dict_ref

### ISSUE THREAD

**Issue by SaltSouls** [lutris/lutris#4854]
### Bug description

When trying to run `Baldur's Gate: Enhanced Edition` it crashes when trying to run it through lutris. This isn't a problem when I run it normally using the startup script the game provides.

### How to Reproduce

1. Install 'Baldur's Gate: Enhanced Edition'
2. Click on 'Play'
4. See 'It crash immediately'

### Expected behavior

Shouldn't be crashing on launch.

### Log output

```shell
INFO     2023-05-12 01:46:50,633 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-05-12 01:46:50,663 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-05-12 01:46:50,682 [startup.check_driver:65]:Running AMD Mesa driver 23.0.3 on AMD Radeon RX 6900 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.1-x64v1-xanmod1-2) (0x73bf)
INFO     2023-05-12 01:46:50,683 [startup.check_driver:77]:GPU: 10DE:1E07 1462:3715 (nouveau drivers)
INFO     2023-05-12 01:46:50,683 [startup.check_driver:77]:GPU: 1002:73BF 1462:3952 (amdgpu drivers)
DEBUG    2023-05-12 01:46:50,777 [lutriswindow.update_store:448]:Showing 7 games
INFO     2023-05-12 01:46:50,790 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-05-12 01:46:52,161 [grid.on_item_activated:57]:Item activated: 1207666353
DEBUG    2023-05-12 01:46:52,161 [lutriswindow.on_game_activated:857]:Looking up gog game 1207666353
DEBUG    2023-05-12 01:46:52,178 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/media/rstore/games/steamapps/custom/gog/baldurs-gate-enhanced-edition"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:DRI_PRIME="1"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:LD_LIBRARY_PATH="/home/gigapain/.steam/bin/steam-runtime/lib/x86_64-linux-gnu:/usr/lib:/usr/lib32:/usr/lib/libfakeroot:/usr/lib64:/home/gigapain/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/gigapain/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/gigapain/.local/share/lutris/runtime/steam/i386/lib:/home/gigapain/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/gigapain/.local/share/lutris/runtime/steam/i386/usr/lib:/home/gigapain/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/gigapain/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/gigapain/.local/share/lutris/runtime/steam/amd64/lib:/home/gigapain/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/gigapain/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:game_name="Baldur's Gate: Enhanced Edition"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages"
DEBUG    2023-05-12 01:46:52,180 [command.start:141]:LUTRIS_GAME_UUID="f77d4f36-207f-4918-ac5a-19767bf2838f"
Discord ID: None
INFO     2023-05-12 01:46:52,185 [game.start_game:586]:Discord RPC Disabled or Discord APP ID Not Present
Traceback (most recent call last):
  File "/usr/share/lutris/bin/lutris-wrapper", line 16, in <module>
    from lutris.util.log import logger
  File "/usr/lib/python3.11/site-packages/lutris/util/log.py", line 7, in <module>
    from gi.repository import GLib
  File "/usr/lib/python3.11/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/libgobject-2.0.so.0: undefined symbol: g_variant_dict_ref
WARNING  2023-05-12 01:46:52,216 [command.get_return_code:185]:No file /tmp/lutris-f77d4f36-207f-4918-ac5a-19767bf2838f
DEBUG    2023-05-12 01:46:52,216 [command.on_stop:195]:Process 74546 has terminated with code
DEBUG    2023-05-12 01:46:54,188 [game.beat:693]:Game thread stopped
WARNING  2023-05-12 01:46:54,188 [game.on_game_quit:730]:Game still running (state: running)
INFO     2023-05-12 01:46:54,189 [game.stop:704]:Stopping Baldur's Gate: Enhanced Edition (linux)
DEBUG    2023-05-12 01:46:54,189 [game.stop_game:664]:Baldur's Gate: Enhanced Edition (linux) has run for 2 seconds
WARNING  2023-05-12 01:46:54,189 [game.stop_game:666]:The game has run for a very short time, did it crash?
DEBUG    2023-05-12 01:46:54,196 [game.on_game_quit:748]:Baldur's Gate: Enhanced Edition stopped at Fri, 12 May 2023 01:46:54
DEBUG    2023-05-12 01:46:54,196 [game.save:299]:Saving Baldur's Gate: Enhanced Edition (linux) with config ID baldurs_gate_enhanced_edition-1683834804
INFO     2023-05-12 01:46:56,597 [application.do_shutdown:898]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.3.1-x64v1-xanmod1-2
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             62.7 GB
Swap:            128.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6900 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.1-x64v1-xanmod1-2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.3
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.3
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This sounds like #4425, though the details differ.

That is an issue GOG games have, where GOG provides some libraries with the game, but they wind up being incompatible with other libraries your distribution includes. Turning off the Lutris runtime won't help, since the conflicting libraries are coming from the distribution, as a rule.

You can fix this by removing the GOG libraries, sometimes. But it looks like its not the same library at issue as in #4425 here.

**Comment by strycore** [comment]
The fact this is a GOG game is irrelevant, this looks like a Python and PyGObject configuration issue.

Almost certain this was fixed by an Arch Linux update.
