### ISSUE TITLE
Lutris 0.5.13 PermissionError: [Errno 13] Permission denied: '/proc/driver/nvidia/version'

### ISSUE THREAD

**Issue by JLA4444** [lutris/lutris#4858]
### Bug description

Installed Lutris 0.5.13 since Starcraft 2 stopped working in Lutris 0.5.11. I uninstalled the apt install of Lutris and installed the Snap version instead.

However Lutris won't start at all. Issuing the start command in CLI gives the following error. See using sudo below for other errors.

$~$ snap run lutris
/usr/share/libdrm/amdgpu.ids: No such file or directory
ERROR:dbus.proxies:Introspect error on :1.37:/org/gnome/Mutter/DisplayConfig: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.659" (uid=1000 pid=594319 comm="python3 /snap/lutris/39/usr/bin/lutris " label="snap.lutris.lutris (enforce)") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.37" (uid=1000 pid=2891 comm="/usr/bin/gnome-shell " label="unconfined")
/usr/share/libdrm/amdgpu.ids: No such file or directory
2023-05-17 15:14:02,956: Starting Lutris 0.5.13
INFO:lutris.util.log:Starting Lutris 0.5.13
Traceback (most recent call last):
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/application.py", line 436, in do_command_line
    run_all_checks()
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/startup.py", line 189, in run_all_checks
    check_driver()
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/startup.py", line 63, in check_driver
    driver_info = drivers.get_nvidia_driver_info()
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/util/graphics/drivers.py", line 18, in get_nvidia_driver_info
    with open(version_file_path, encoding='utf-8') as version_file:
PermissionError: [Errno 13] Permission denied: '/proc/driver/nvidia/version'
2023-05-17 15:14:02,958: Shutting down Lutris
INFO:lutris.util.log:Shutting down Lutris

$~$ sudo snap run lutris
mkdir: cannot create directory '/run/user/0': Permission denied
No protocol specified
No protocol specified
No protocol specified
Error: unable to open display :0
2023-05-17 15:16:05,856: ['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 255.
2023-05-17 15:16:05,856: No available glxinfo output
2023-05-17 15:16:05,856: Invalid glxinfo received
No protocol specified
/usr/share/libdrm/amdgpu.ids: No such file or directory

(lutris:594524): Gtk-CRITICAL **: 15:16:06.442: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/snap/lutris/39/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/application.py", line 58, in <module>
    from .lutriswindow import LutrisWindow
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 19, in <module>
    from lutris.gui.config.preferences_dialog import PreferencesDialog
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/config/preferences_dialog.py", line 10, in <module>
    from lutris.gui.config.runners_box import RunnersBox
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/config/runners_box.py", line 8, in <module>
    from lutris.gui.config.runner_box import RunnerBox
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/config/runner_box.py", line 9, in <module>
    from lutris.gui.dialogs.runner_install import RunnerInstallDialog
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/dialogs/runner_install.py", line 51, in <module>
    class RunnerInstallDialog(ModelessDialog):
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/dialogs/runner_install.py", line 61, in RunnerInstallDialog
    if has_stock_icon("software-installed-symbolic") else "wine-symbolic"
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 155, in has_stock_icon
    return theme.has_icon(name)
AttributeError: 'NoneType' object has no attribute 'has_icon'

### How to Reproduce

snap run lutris

### Expected behavior

I expect the Lutris GUI to show up

### Log output

```shell
$~$ lutris -d
/usr/share/libdrm/amdgpu.ids: No such file or directory
ERROR:dbus.proxies:Introspect error on :1.37:/org/gnome/Mutter/DisplayConfig: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.671" (uid=1000 pid=595487 comm="python3 /snap/lutris/39/usr/bin/lutris -d " label="snap.lutris.lutris (enforce)") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.37" (uid=1000 pid=2891 comm="/usr/bin/gnome-shell " label="unconfined")
/usr/share/libdrm/amdgpu.ids: No such file or directory
INFO     2023-05-17 15:26:06,543 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO:lutris.util.log:Starting Lutris 0.5.13
Traceback (most recent call last):
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/gui/application.py", line 436, in do_command_line
    run_all_checks()
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/startup.py", line 189, in run_all_checks
    check_driver()
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/startup.py", line 63, in check_driver
    driver_info = drivers.get_nvidia_driver_info()
  File "/snap/lutris/39/usr/lib/python3/dist-packages/lutris/util/graphics/drivers.py", line 18, in get_nvidia_driver_info
    with open(version_file_path, encoding='utf-8') as version_file:
PermissionError: [Errno 13] Permission denied: '/proc/driver/nvidia/version'
INFO     2023-05-17 15:26:06,549 [application.do_shutdown:960]:Shutting down Lutris
INFO:lutris.util.log:Shutting down Lutris
```

### System Information

```shell
I am using nvidia-driver-470 i havn't dared to upgrade due to bad experiences.

I am unable to get this but lshw gives:

$~$ sudo lshw
h-tech-g14                  
    description: Notebook
    product: ROG Zephyrus G14 GA401IV
    vendor: ASUSTeK COMPUTER INC.
    version: 1.0
    serial: LBNRKDCZR07Z492
    width: 64 bits
    capabilities: smbios-3.2.0 dmi-3.2.0 smp vsyscall32
    configuration: boot=normal chassis=notebook family=ROG Zephyrus G14 uuid=1ED63EDC-0C22-406F-B4F5-2CD4E1392913
  *-core
       description: Motherboard
       product: GA401IV
       vendor: ASUSTeK COMPUTER INC.
       physical id: 0
       version: 1.0
       serial: YS0YMC00AD
       slot: MIDDLE
     *-firmware
          description: BIOS
          vendor: American Megatrends Inc.
          physical id: 0
          version: GA401IV.219
          date: 12/30/2020
          size: 64KiB
          capacity: 16MiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial int17printer acpi usb smartbattery biosbootspecification uefi
     *-memory
          description: System Memory
          physical id: a
          slot: System board or motherboard
          size: 32GiB
        *-bank:0
             description: SODIMM DDR4 Synchronous Unbuffered (Unregistered) 3200 MHz (0,3 ns)
             product: M471A2G43AB2-CWE
             vendor: Samsung
             physical id: 0
             serial: 00000000
             slot: DIMM 0
             size: 16GiB
             width: 64 bits
             clock: 3200MHz (0.3ns)
        *-bank:1
             description: SODIMM DDR4 Synchronous Unbuffered (Unregistered) 3200 MHz (0,3 ns)
             product: M471A2K43DB1-CWE
             vendor: Samsung
             physical id: 1
             serial: 37E8B296
             slot: DIMM 0
             size: 16GiB
             width: 64 bits
             clock: 3200MHz (0.3ns)
     *-cache:0
          description: L1 cache
          physical id: c
          slot: L1 - Cache
          size: 512KiB
          capacity: 512KiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=1
     *-cache:1
          description: L2 cache
          physical id: d
          slot: L2 - Cache
          size: 4MiB
          capacity: 4MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=2
     *-cache:2
          description: L3 cache
          physical id: e
          slot: L3 - Cache
          size: 8MiB
          capacity: 8MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=3
     *-cpu
          description: CPU
          product: AMD Ryzen 9 4900HS with Radeon Graphics
          vendor: Advanced Micro Devices [AMD]
          physical id: f
          bus info: cpu@0
          slot: FP6
          size: 1362MHz
          capacity: 3GHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es cpufreq
          configuration: cores=8 enabledcores=8 threads=16
     *-pci:0
          description: Host bridge
          product: Renoir Root Complex
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 00
          width: 32 bits
          clock: 33MHz
        *-generic UNCLAIMED
             description: IOMMU
             product: Renoir IOMMU
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 0.2
             bus info: pci@0000:00:00.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: msi ht cap_list
             configuration: latency=0
        *-pci:0
             description: PCI bridge
             product: Renoir PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 1.1
             bus info: pci@0000:00:01.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:26 ioport:f000(size=4096) memory:fb000000-fc0fffff ioport:b0000000(size=303038464)
           *-display
                description: VGA compatible controller
                product: TU106 [GeForce RTX 2060]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: irq:100 memory:fb000000-fbffffff memory:b0000000-bfffffff memory:c0000000-c1ffffff ioport:f000(size=128) memory:fc000000-fc07ffff
           *-multimedia
                description: Audio device
                product: TU106 High Definition Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:01:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:95 memory:fc080000-fc083fff
           *-usb
                description: USB controller
                product: TU106 USB 3.1 Host Controller
                vendor: NVIDIA Corporation
                physical id: 0.2
                bus info: pci@0000:01:00.2
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: msi pciexpress pm xhci cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:34 memory:c2000000-c203ffff memory:c2040000-c204ffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-71-generic xhci-hcd
                   physical id: 0
                   bus info: usb@1
                   logical name: usb1
                   version: 5.15
                   capabilities: usb-2.00
                   configuration: driver=hub slots=2 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-71-generic xhci-hcd
                   physical id: 1
                   bus info: usb@2
                   logical name: usb2
                   version: 5.15
                   capabilities: usb-3.10
                   configuration: driver=hub slots=4 speed=10000Mbit/s
           *-serial UNCLAIMED
                description: Serial bus controller
                product: TU106 USB Type-C UCSI Controller
                vendor: NVIDIA Corporation
                physical id: 0.3
                bus info: pci@0000:01:00.3
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: msi pciexpress pm cap_list
                configuration: latency=0
                resources: memory:fc084000-fc084fff
        *-pci:1
             description: PCI bridge
             product: Renoir PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.2
             bus info: pci@0000:00:02.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:27 memory:fc800000-fc8fffff
           *-network
                description: Wireless interface
                product: Wi-Fi 6 AX200
                vendor: Intel Corporation
                physical id: 0
                bus info: pci@0000:02:00.0
                logical name: wlp2s0
                version: 1a
                serial: ac:12:03:d9:7e:1b
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=iwlwifi driverversion=5.15.0-71-generic firmware=66.f1c864e0.0 cc-a0-66.ucode ip=192.168.1.225 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                resources: irq:78 memory:fc800000-fc803fff
        *-pci:2
             description: PCI bridge
             product: Renoir PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.4
             bus info: pci@0000:00:02.4
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:28 memory:fc700000-fc7fffff
           *-storage
                description: Non-Volatile memory controller
                product: Sandisk Corp
                vendor: Sandisk Corp
                physical id: 0
                bus info: pci@0000:03:00.0
                version: 01
                width: 64 bits
                clock: 33MHz
                capabilities: storage pm msi msix pciexpress nvm_express bus_master cap_list
                configuration: driver=nvme latency=0
                resources: irq:36 memory:fc700000-fc703fff memory:fc704000-fc7040ff
              *-nvme0
                   description: NVMe device
                   product: WDC PC SN530 SDBPNPZ-1T00-1002
                   physical id: 0
                   logical name: /dev/nvme0
                   version: 21106000
                   serial: 20231D456603
                   configuration: nqn=nqn.2018-01.com.wdc:nguid:E8238FA6BF53-0001-001B444A443ACE9C state=live
                 *-namespace
                      description: NVMe namespace
                      physical id: 1
                      logical name: /dev/nvme0n1
                      size: 953GiB (1024GB)
                      capabilities: gpt-1.00 partitioned partitioned:gpt
                      configuration: guid=5b1f081b-7d64-4349-92bd-8ee0cac2419b logicalsectorsize=512 sectorsize=512
                    *-volume:0
                         description: Windows FAT volume
                         vendor: mkfs.fat
                         physical id: 1
                         logical name: /dev/nvme0n1p1
                         logical name: /boot/efi
                         version: FAT32
                         serial: fe0a-bf19
                         size: 510MiB
                         capacity: 511MiB
                         capabilities: boot fat initialized
                         configuration: FATs=2 filesystem=fat mount.fstype=vfat mount.options=rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro name=EFI System Partition state=mounted
                    *-volume:1
                         description: EXT4 volume
                         vendor: Linux
                         physical id: 2
                         logical name: /dev/nvme0n1p2
                         logical name: /boot
                         version: 1.0
                         serial: 86246166-acf5-408f-a5db-78f7c48c3e3d
                         size: 732MiB
                         capabilities: journaled extended_attributes large_files huge_files dir_nlink recover 64bit extents ext4 ext2 initialized
                         configuration: created=2021-07-22 18:42:16 filesystem=ext4 lastmountpoint=/boot modified=2023-05-08 11:31:50 mount.fstype=ext4 mount.options=rw,relatime mounted=2023-05-08 11:31:50 state=mounted
                    *-volume:2
                         description: EFI partition
                         physical id: 3
                         logical name: /dev/nvme0n1p3
                         serial: 2d2a3d7a-bb14-43c1-b67b-232821aef836
                         size: 952GiB
                         capacity: 952GiB
                         width: 2954738264 bits
                         capabilities: encrypted luks initialized
                         configuration: bits=24429574744 filesystem=luks hash=sha256 version=2
        *-pci:3
             description: PCI bridge
             product: Renoir Internal PCIe GPP Bridge to Bus
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.1
             bus info: pci@0000:00:08.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:29 ioport:e000(size=4096) memory:fc200000-fc5fffff ioport:d0000000(size=270532608)
           *-display
                description: VGA compatible controller
                product: Renoir
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0
                bus info: pci@0000:04:00.0
                version: c5
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix vga_controller bus_master cap_list
                configuration: driver=amdgpu latency=0
                resources: irq:49 memory:d0000000-dfffffff memory:e0000000-e01fffff ioport:e000(size=256) memory:fc500000-fc57ffff
           *-multimedia:0
                description: Audio device
                product: Advanced Micro Devices, Inc. [AMD/ATI]
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0.1
                bus info: pci@0000:04:00.1
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:98 memory:fc5c8000-fc5cbfff
           *-generic
                description: Encryption controller
                product: Family 17h (Models 10h-1fh) Platform Security Processor
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.2
                bus info: pci@0000:04:00.2
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix bus_master cap_list
                configuration: driver=ccp latency=0
                resources: irq:75 memory:fc400000-fc4fffff memory:fc5cc000-fc5cdfff
           *-usb:0
                description: USB controller
                product: Renoir USB 3.1
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.3
                bus info: pci@0000:04:00.3
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:40 memory:fc300000-fc3fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-71-generic xhci-hcd
                   physical id: 0
                   bus info: usb@3
                   logical name: usb3
                   version: 5.15
                   capabilities: usb-2.00
                   configuration: driver=hub slots=4 speed=480Mbit/s
                 *-usb:0
                      description: Mouse
                      product: USB OPTICAL MOUSE
                      vendor: [Maxxter]
                      physical id: 1
                      bus info: usb@3:1
                      version: 1.00
                      capabilities: usb-1.10
                      configuration: driver=usbhid maxpower=100mA speed=1Mbit/s
                 *-usb:1
                      description: USB hub
                      product: USB Hub
                      vendor: Alcor Micro Corp.
                      physical id: 2
                      bus info: usb@3:2
                      version: 1.00
                      capabilities: usb-2.00
                      configuration: driver=hub maxpower=100mA slots=4 speed=480Mbit/s
                    *-usb
                         description: Keyboard
                         product: D4269
                         vendor: Metadot - Das Keyboard
                         physical id: 1
                         bus info: usb@3:2.1
                         version: 1.00
                         capabilities: usb-1.10
                         configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
                 *-usb:2
                      description: Keyboard
                      product: N-KEY Device
                      vendor: ASUSTeK Computer Inc.
                      physical id: 3
                      bus info: usb@3:3
                      version: 0.02
                      capabilities: usb-2.00
                      configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
                 *-usb:3
                      description: Keyboard
                      product: ITE Device(8910)
                      vendor: ITE Tech. Inc.
                      physical id: 4
                      bus info: usb@3:4
                      version: 0.03
                      capabilities: usb-2.00
                      configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-71-generic xhci-hcd
                   physical id: 1
                   bus info: usb@4
                   logical name: usb4
                   version: 5.15
                   capabilities: usb-3.10
                   configuration: driver=hub slots=2 speed=10000Mbit/s
           *-usb:1
                description: USB controller
                product: Renoir USB 3.1
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.4
                bus info: pci@0000:04:00.4
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:49 memory:fc200000-fc2fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-71-generic xhci-hcd
                   physical id: 0
                   bus info: usb@5
                   logical name: usb5
                   version: 5.15
                   capabilities: usb-2.00
                   configuration: driver=hub slots=4 speed=480Mbit/s
                 *-usb:0 UNCLAIMED
                      description: Generic USB device
                      product: FingerPrint
                      vendor: Goodix
                      physical id: 3
                      bus info: usb@5:3
                      version: 1.00
                      capabilities: usb-2.00
                      configuration: maxpower=100mA speed=12Mbit/s
                 *-usb:1
                      description: Bluetooth wireless interface
                      vendor: Intel Corp.
                      physical id: 4
                      bus info: usb@5:4
                      version: 0.01
                      capabilities: bluetooth usb-2.01
                      configuration: driver=btusb maxpower=100mA speed=12Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 5.15.0-71-generic xhci-hcd
                   physical id: 1
                   bus info: usb@6
                   logical name: usb6
                   version: 5.15
                   capabilities: usb-3.10
                   configuration: driver=hub slots=2 speed=10000Mbit/s
           *-multimedia:1 UNCLAIMED
                description: Multimedia controller
                product: Raven/Raven2/FireFlight/Renoir Audio Processor
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.5
                bus info: pci@0000:04:00.5
                version: 01
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi cap_list
                configuration: latency=0
                resources: memory:fc580000-fc5bffff
           *-multimedia:2
                description: Audio device
                product: Family 17h (Models 10h-1fh) HD Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.6
                bus info: pci@0000:04:00.6
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:37 memory:fc5c0000-fc5c7fff
        *-pci:4
             description: PCI bridge
             product: Renoir Internal PCIe GPP Bridge to Bus
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.2
             bus info: pci@0000:00:08.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:30 memory:fc600000-fc6fffff
           *-sata:0
                description: SATA controller
                product: FCH SATA Controller [AHCI mode]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0
                bus info: pci@0000:05:00.0
                version: 81
                width: 32 bits
                clock: 33MHz
                capabilities: sata pm pciexpress msi ahci_1.0 bus_master cap_list
                configuration: driver=ahci latency=0
                resources: irq:33 memory:fc601000-fc6017ff
           *-sata:1
                description: SATA controller
                product: FCH SATA Controller [AHCI mode]
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.1
                bus info: pci@0000:05:00.1
                version: 81
                width: 32 bits
                clock: 33MHz
                capabilities: sata pm pciexpress msi ahci_1.0 bus_master cap_list
                configuration: driver=ahci latency=0
                resources: irq:39 memory:fc600000-fc6007ff
        *-serial
             description: SMBus
             product: FCH SMBus Controller
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 51
             width: 32 bits
             clock: 66MHz
             configuration: driver=piix4_smbus latency=0
             resources: irq:0
        *-isa
             description: ISA bridge
             product: FCH LPC Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14.3
             bus info: pci@0000:00:14.3
             version: 51
             width: 32 bits
             clock: 66MHz
             capabilities: isa bus_master
             configuration: latency=0
     *-pci:1
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 101
          bus info: pci@0000:00:01.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:2
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 102
          bus info: pci@0000:00:02.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:3
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 103
          bus info: pci@0000:00:08.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:4
          description: Host bridge
          product: Renoir Device 24: Function 0
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 104
          bus info: pci@0000:00:18.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:5
          description: Host bridge
          product: Renoir Device 24: Function 1
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 105
          bus info: pci@0000:00:18.1
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:6
          description: Host bridge
          product: Renoir Device 24: Function 2
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 106
          bus info: pci@0000:00:18.2
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:7
          description: Host bridge
          product: Renoir Device 24: Function 3
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 107
          bus info: pci@0000:00:18.3
          version: 00
          width: 32 bits
          clock: 33MHz
          configuration: driver=k10temp
          resources: irq:0
     *-pci:8
          description: Host bridge
          product: Renoir Device 24: Function 4
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 108
          bus info: pci@0000:00:18.4
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:9
          description: Host bridge
          product: Renoir Device 24: Function 5
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 109
          bus info: pci@0000:00:18.5
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:10
          description: Host bridge
          product: Renoir Device 24: Function 6
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10a
          bus info: pci@0000:00:18.6
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:11
          description: Host bridge
          product: Renoir Device 24: Function 7
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10b
          bus info: pci@0000:00:18.7
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pnp00:00
          product: PnP device PNP0c01
          physical id: 1
          capabilities: pnp
          configuration: driver=system
     *-pnp00:01
          product: PnP device PNP0b00
          physical id: 2
          capabilities: pnp
          configuration: driver=rtc_cmos
     *-pnp00:02
          product: PnP device PNP0c02
          physical id: 3
          capabilities: pnp
          configuration: driver=system
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
> I uninstalled the apt install of Lutris and installed the Snap version instead.

Then uninstall it and re-install the deb package, it's available on the releases page.
To my knowledge, the snap package is still being worked on and isn't ready for regular use.

**Comment by strycore** [comment]
Also, leave an issue here: https://github.com/CapeCrusader321/Lutris-snap

This seems to be the source of the Snap

**Comment by strycore** [comment]
Closing this issue since it's specific to the Snap package.

**Comment by JLA4444** [comment]
Just for other with the same issue. I can confirm that installing 0.5.13 deb package works without issue and solved my Starcraft 2 boot issue.
