### ISSUE TITLE
Battle.net service

### ISSUE THREAD

**Issue by tdockx** [lutris/lutris#4862]
### Bug description

I cannot find the service of Battle.net.
Although I am using the latest version. I am using flatpak.

I see the service file available here : https://github.com/lutris/lutris/blob/master/lutris/services/battlenet.py

Is there something / requirement that I might be missing in order to see it properly?

Thank in advance.

### How to Reproduce

Simply go to Preferences/Sources.
Or the services being listed.

### Expected behavior

Being able to see the service.

### Log output

```shell
No log. No errors.
Even flatpak run <lutris> -d does not show anything interesting.
```

### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.1.0-9-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i5-11600 @ 2.80GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             46.9 GB
Swap:            1.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.105.17
OpenGL Core:     4.6.0 NVIDIA 525.105.17
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.105.17
Vulkan Version:  1.3.224
Vulkan Drivers:  NVIDIA GeForce RTX 3060 Ti (1.3.224)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Svenum** [comment]
Same here

**Comment by cd4d** [comment]
Same, Ubuntu 22.04, Lutris 5.13 installed with Flatpak.

**Comment by danieljohnson2** [comment]
Can we get a debug log from this?

I would guess that the flatpak is missing the google.protobuf dependency, as that should cause the Battle.net service to just disappear. But if it's not that, I'd expect some log spam about it.

**Comment by tdockx** [comment]
Hi @danieljohnson2,

Thanks for your reply.
Here is my log of running it with debug at launch and going through preferences / sources trying to find it.

```
INFO     2023-05-23 10:30:37,645 [startup.init_lutris:237]:Starting Lutris 0.5.13
INFO     2023-05-23 10:30:37,650 [startup.check_driver:64]:Using NVIDIA drivers 525.105.17 for x86_64
INFO     2023-05-23 10:30:37,650 [startup.check_driver:68]:GPU: NVIDIA GeForce RTX 3060 Ti
INFO     2023-05-23 10:30:37,651 [startup.check_driver:84]:GPU: 10DE:2489 1043:883C (nvidia drivers)
DEBUG    2023-05-23 10:30:37,797 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-23 10:30:37,870 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2023-05-23 10:30:44,164 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-05-23 10:30:50,484 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2023-05-23 10:30:50,908 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk_versions.json
INFO     2023-05-23 10:30:50,910 [dll_manager.upgrade:275]:Downloading DXVK v2.2...
INFO     2023-05-23 10:30:50,911 [dll_manager.download:134]:Downloading https://github.com/lutris/dxvk/releases/download/v2.2/dxvk-2.2.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk-2.2.tar.xz
DEBUG    2023-05-23 10:30:50,911 [http._request:88]:GET https://github.com/lutris/dxvk/releases/download/v2.2/dxvk-2.2.tar.xz
DEBUG    2023-05-23 10:30:51,890 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk-2.2.tar.xz
INFO     2023-05-23 10:30:51,893 [dll_manager.download:139]:Extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk-2.2.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/v2.2
DEBUG    2023-05-23 10:30:51,893 [extract.extract_archive:127]:Extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk-2.2.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/v2.2
DEBUG    2023-05-23 10:30:52,102 [system.remove_folder:304]:Removing folder /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/v2.2/.extract-d91dfc43
DEBUG    2023-05-23 10:30:52,102 [extract.extract_archive:179]:Finished extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/dxvk-2.2.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk/v2.2
DEBUG    2023-05-23 10:30:52,103 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-05-23 10:30:52,449 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
INFO     2023-05-23 10:30:52,450 [dll_manager.upgrade:275]:Downloading DXVK-NVAPI v0.6.3...
INFO     2023-05-23 10:30:52,451 [dll_manager.download:134]:Downloading https://github.com/lutris/dxvk-nvapi/releases/download/v0.6.3/dxvk-nvapi-v0.6.3.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.3.tar.xz
DEBUG    2023-05-23 10:30:52,451 [http._request:88]:GET https://github.com/lutris/dxvk-nvapi/releases/download/v0.6.3/dxvk-nvapi-v0.6.3.tar.xz
DEBUG    2023-05-23 10:30:54,171 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.3.tar.xz
INFO     2023-05-23 10:30:54,173 [dll_manager.download:139]:Extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.3.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/v0.6.3
DEBUG    2023-05-23 10:30:54,173 [extract.extract_archive:127]:Extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.3.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/v0.6.3
DEBUG    2023-05-23 10:30:54,273 [system.remove_folder:304]:Removing folder /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/v0.6.3/.extract-15c8ab6b
DEBUG    2023-05-23 10:30:54,273 [extract.extract_archive:179]:Finished extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.3.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk-nvapi/v0.6.3
DEBUG    2023-05-23 10:30:54,274 [http._request:88]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2023-05-23 10:30:54,625 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/vkd3d_versions.json
INFO     2023-05-23 10:30:54,626 [dll_manager.upgrade:275]:Downloading VKD3D v2.9...
INFO     2023-05-23 10:30:54,627 [dll_manager.download:134]:Downloading https://github.com/lutris/vkd3d/releases/download/v2.9/vkd3d-v2.9.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/vkd3d-v2.9.tar.xz
DEBUG    2023-05-23 10:30:54,627 [http._request:88]:GET https://github.com/lutris/vkd3d/releases/download/v2.9/vkd3d-v2.9.tar.xz
DEBUG    2023-05-23 10:30:55,355 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/vkd3d-v2.9.tar.xz
INFO     2023-05-23 10:30:55,356 [dll_manager.download:139]:Extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/vkd3d-v2.9.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/v2.9
DEBUG    2023-05-23 10:30:55,356 [extract.extract_archive:127]:Extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/vkd3d-v2.9.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/v2.9
DEBUG    2023-05-23 10:30:55,459 [system.remove_folder:304]:Removing folder /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/v2.9/.extract-d8e1ddcd
DEBUG    2023-05-23 10:30:55,459 [extract.extract_archive:179]:Finished extracting /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/vkd3d-v2.9.tar.xz to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/vkd3d/v2.9
DEBUG    2023-05-23 10:30:55,460 [http._request:88]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2023-05-23 10:30:55,680 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2023-05-23 10:30:55,681 [http._request:88]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2023-05-23 10:30:55,986 [http.write_to_file:142]:Writing to /home/thibault/.var/app/net.lutris.Lutris/data/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2023-05-23 10:30:55,987 [runtime.update_runtimes:233]:Startup complete
DEBUG    2023-05-23 10:31:09,800 [application.show_window:339]:Showing window PreferencesDialog{}
DEBUG    2023-05-23 10:31:16,792 [application.on_app_window_destroyed:357]:Removed window PreferencesDialog{}
INFO     2023-05-23 10:31:19,100 [application.do_shutdown:960]:Shutting down Lutris
```

I don't see anything of importance here.  
It might be, as you said, that flatpak does not contain the `google.protobuf` dependency.
Any chance to have it included in the future?

Thanks a lot.

**Comment by danieljohnson2** [comment]
OK, I've managed to repro this and I've extracted this error:

```
2023-05-23 19:17:37,796: TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/lutris/services/battlenet.py", line 20, in <module>
    from lutris.util.battlenet.product_db_pb2 import ProductDb
  File "/app/lib/python3.10/site-packages/lutris/util/battlenet/product_db_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/app/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
```

So it is the protobuf thing, but it looks like the problem is not that it isn't there, but we're getting a too-recent google protobuf library, and we may need to rebuild something. I'm not that familiar with this stuff, but I find that running this command:

```
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python flatpak run net.lutris.Lutris
```

Causes Battle.net to appear in the sources.

Could someone with an account try that command line and verify that the thing actually works like that?

**Comment by danieljohnson2** [comment]
It appears I don't have the ``product_db.proto`` file that the _pb2.py is generated from, so I can't regenerate it. I'm not sure we even want to- might not be compatible with older software. Maybe the flatpak can set that environment variable.

@strycore, can we get some guidance here?

**Comment by strycore** [comment]
The Blizzard integration was made for an older version of Protobuf so the way of fixing the Flatpak is by sticking to 3.20.x like specified in the error message.

The integration was based off the one for GOG Galaxy. You can find the .proto file there: https://github.com/bartok765/galaxy_blizzard_plugin/tree/master/src

**Comment by strycore** [comment]
Fix commited here: https://github.com/lutris/net.lutris.Lutris/commit/b78490e108c4ae3da0280fe767c46a287a8856a3

**Comment by danieljohnson2** [comment]
That tests out for me.

Will we have to wait until 0.5.13.1 is released before updating the flatpak, or is that going to get published sooner?

**Comment by strycore** [comment]
No, we can publish updates to the Flatpak independently. It should already be in Flathub Beta.

**Comment by al12gamer** [comment]
Will this also be in the next Flatpak release, outside of the beta?

**Comment by strycore** [comment]
The update is now published on Flathub. Updated Lutris on the Steam Deck and the Battle.net service can be enabled.

**Comment by tdockx** [comment]
Just to leave a quick thanks to dev team for the update.  
Keep this amazing work!
