### ISSUE TITLE
Excluding %s from process monitor error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#487]
got this when looking at the terminal, not sure what is wrong:

```
Traceback (most recent call last):
  File "/home/user01/src/lutris/lutris/thread.py", line 228, in watch_children
    logger.debug("Excluding %s from process monitor" % child.name)
  File "/home/user01/src/lutris/lutris/util/process.py", line 63, in name
    _stat = self.get_stat(parsed=False)
  File "/home/user01/src/lutris/lutris/util/process.py", line 27, in get_stat
    with open(stat_filename) as stat_file:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/10276/stat'
```

**Comment by telanus** [comment]
seems to be still there:

 ```
 File "/home/user01/src/lutris/lutris/thread.py", line 210, in watch_children
    process = Process(self.rootpid)
  File "/home/user01/src/lutris/lutris/util/process.py", line 18, in __init__
    self.get_children()
  File "/home/user01/src/lutris/lutris/util/process.py", line 58, in get_children
    self.children.append(Process(child_pid, parent=self))
  File "/home/user01/src/lutris/lutris/util/process.py", line 18, in __init__
    self.get_children()
  File "/home/user01/src/lutris/lutris/util/process.py", line 58, in get_children
    self.children.append(Process(child_pid, parent=self))
  File "/home/user01/src/lutris/lutris/util/process.py", line 18, in __init__
    self.get_children()
  File "/home/user01/src/lutris/lutris/util/process.py", line 56, in get_children
    for tid in self.get_thread_ids():
  File "/home/user01/src/lutris/lutris/util/process.py", line 41, in get_thread_ids
    return [tid for tid in os.listdir(basedir)]
FileNotFoundError: [Errno 2] No such file or directory: '/proc/23816/task/'

```
