### ISSUE TITLE
Building from source (Devuan): gpg: skipped "Mathieu Comandon <mathieucomandon@gmail.com>": No secret key

### ISSUE THREAD

**Issue by Russtopia** [lutris/lutris#4870]
### Bug description

What keyring do I need to import to ensure the proper keys are present for a source build?

Thanks.

### How to Reproduce

1. From a Devuan GNU/Linux (Debian kernel 8.3.0) install
2. git clone https://github.com/lutris/lutris.git
3. cd lutris
4. make

### Expected behavior

BTW I had to manually patch `/usr/lib/python3.7/functools.py` before `./bin/lutris -d` would run, with

```    elif maxsize is not None:
        #raise TypeError('Expected maxsize to be an integer or None')
        maxsize = 128
```

### Log output

```shell
$ ./bin/lutris -d
Xlib:  extension "NV-GLX" missing on display ":0.0".
Xlib:  extension "NV-GLX" missing on display ":0.0".

(lutris:476): Gtk-WARNING **: 22:47:45.827: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "RegisterClient" with signature "ss" on interface "org.xfce.Session.Manager" doesn't exist

INFO     2023-05-24 22:47:45,829 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-05-24 22:47:45,830 [startup.check_driver:77]:Running Intel Open Source Technology Center Mesa driver 18.3.6 on Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)  (0x3e9b)
INFO     2023-05-24 22:47:45,831 [startup.check_driver:85]:GPU: 8086:3E9B 1028:0905 (i915 drivers)
Xlib:  extension "NV-GLX" missing on display ":0.0".
Xlib:  extension "NV-GLX" missing on display ":0.0".
WARNING  2023-05-24 22:47:45,870 [startup.check_vulkan:152]:Vulkan reports an API version of 1.1.0. 1.3.0 is required for the latest DXVK.
Xlib:  extension "NV-GLX" missing on display ":0.0".
Xlib:  extension "NV-GLX" missing on display ":0.0".
WARNING  2023-05-24 22:47:45,894 [startup.check_vulkan:161]:Vulkan reports that the 'Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)' device has API version of 1.1.90. 1.3.0 is required for the latest DXVK.
ERROR    2023-05-24 22:47:45,895 [jobs.target:36]:Error while completing task <function lru_cache.<locals>.decorating_function at 0x7f87c16441e0>: <class 'TypeError'> decorating_function() takes 1 positional argument but 2 were given
ERROR    2023-05-24 22:47:45,895 [jobs.target:36]:Error while completing task <function lru_cache.<locals>.decorating_function at 0x7f87c16441e0>: <class 'TypeError'> decorating_function() takes 1 positional argument but 2 were given
  File "/home/russtopia/pkgs/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
ERROR    2023-05-24 22:47:45,895 [jobs.target:36]:Error while completing task <function lru_cache.<locals>.decorating_function at 0x7f87c16441e0>: <class 'TypeError'> decorating_function() takes 1 positional argument but 2 were given
ERROR    2023-05-24 22:47:45,896 [jobs.target:36]:Error while completing task <function lru_cache.<locals>.decorating_function at 0x7f87c16441e0>: <class 'TypeError'> decorating_function() takes 1 positional argument but 2 were given
  File "/home/russtopia/pkgs/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/home/russtopia/pkgs/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/home/russtopia/pkgs/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
DEBUG    2023-05-24 22:47:46,048 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-24 22:47:46,100 [lutris.get_missing_game_ids:191]:Checking for missing games
Traceback (most recent call last):
  File "/home/russtopia/pkgs/lutris/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
```

### System Information

```shell
[System]
OS:              Devuan GNU/Linux 3 beowulf
Arch:            x86_64
Kernel:          5.7.0rlabs
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.3 GB
Swap:            16.2 GB

[Graphics]
Vendor:          Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)
OpenGL Version:  3.0 Mesa 18.3.6
OpenGL Core:     4.5 (Core Profile) Mesa 18.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 18.3.6
Vulkan Version:  1.1.0
Vulkan Drivers:  Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) (1.1.90)

---

Devuan sources.list

$ cat /etc/apt/sources.list
# 

# deb cdrom:[Devuan GNU/Linux 3.0 (beowulf) amd64 - netinstall 20200526]/ beowulf contrib main non-free

#deb cdrom:[Devuan GNU/Linux 3.0 (beowulf) amd64 - netinstall 20200526]/ beowulf contrib main non-free

deb http://deb.devuan.org/merged beowulf main non-free contrib
deb-src http://deb.devuan.org/merged beowulf main non-free contrib

deb http://deb.devuan.org/merged beowulf-security main contrib non-free
deb-src http://deb.devuan.org/merged beowulf-security main contrib non-free

# beowulf-updates, previously known as 'volatile'
deb http://deb.devuan.org/merged beowulf-updates main contrib non-free
deb-src http://deb.devuan.org/merged beowulf-updates main contrib non-free
```
```


### Media (optional)

_No response_

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
You can't make a signed deb because you don't have my GPG private key. 
Instead, you can make an unsigned deb with `make unsigned`

**Comment by strycore** [comment]
Btw, you have a lot of errors going on at startup. This is certainly not normal and will cause issues.

**Comment by Russtopia** [comment]
> Btw, you have a lot of errors going on at startup. This is certainly not normal and will cause issues.

Yes, thanks I should look into those before going further I guess. My install is definitely not optimal; I have been meaning to look into getting the NVIDIA gfx going on this laptop.

`01:00.0 3D controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)`
