### ISSUE TITLE
Lutris doesn't open, raises JSONDecodeError.

### ISSUE THREAD

**Issue by Exellin** [lutris/lutris#4873]
### Bug description

Lutris doesn't open, raises JSONDecodeError.

I have been using lutris successfully on EndeavourOS for the past year or so.  This started happening a few days ago.

This seems to be a similar issue to https://github.com/lutris/lutris/issues/3725 and https://github.com/lutris/lutris/issues/4526

### How to Reproduce

Run `lutris` from the command land

### Expected behavior

Lutris starts running

### Log output

```shell
INFO     2023-05-27 14:42:30,036 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-05-27 14:42:30,037 [startup.check_driver:73]:Running AMD Mesa driver 23.1.0 on AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.52, 6.3.4-arch1-1) (0x731f)
INFO     2023-05-27 14:42:30,038 [startup.check_driver:85]:GPU: 1002:731F 1458:2313 (amdgpu drivers)
DEBUG    2023-05-27 14:42:30,358 [lutris.get_missing_game_ids:191]:Checking for missing games
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 652, in do_command_line
    self.show_update_runtime_dialog()
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 299, in show_update_runtime_dialog
    runtime_updater = StartupRuntimeUpdater(force=self.force_updates)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/startup.py", line 231, in __init__
    super().__init__(force)
  File "/usr/lib/python3.11/site-packages/lutris/runtime.py", line 203, in __init__
    self.add_update("runtime", self._update_runtime_components, hours=12)
  File "/usr/lib/python3.11/site-packages/lutris/runtime.py", line 210, in add_update
    last_call = update_cache.get_last_call(key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/update_cache.py", line 41, in get_last_call
    date = read_date_from_cache(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/update_cache.py", line 31, in read_date_from_cache
    cache = _read_cache_content()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/update_cache.py", line 25, in _read_cache_content
    cache = json.load(json_file)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### System Information

```shell
./o.             
                   ./sssso-                ---------------------- 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Kernel: 6.3.4-arch1-1 
             `-/ossssssssssssso/.          Uptime: 8 mins 
           `-/+sssssssssssssssso+:`        Packages: 1458 (pacman) 
         `-:/+sssssssssssssssssso+/.       Shell: bash 5.1.16 
       `.://osssssssssssssssssssso++-      Resolution: 2560x1440 
      .://+ssssssssssssssssssssssso++:     DE: GNOME 44.1 
    .:///ossssssssssssssssssssssssso++:    WM: Mutter 
  `:////ssssssssssssssssssssssssssso+++.   WM Theme: Adwaita 
`-////+ssssssssssssssssssssssssssso++++-   Theme: Adwaita [GTK2/3] 
 `..-+oosssssssssssssssssssssssso+++++/`   Icons: Adwaita [GTK2/3] 
   ./++++++++++++++++++++++++++++++/:.     Terminal: gnome-terminal 
  `:::::::::::::::::::::::::------``       CPU: Intel i7-4770K (8) @ 3.900GHz 
                                           GPU: AMD ATI Radeon RX 5600 OEM/5600 
                                           Memory: 4157MiB / 32040MiB 

I can't open Lutris, so this is just from neofetch
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Looks like you have a corrupt '~/.cache/lutris/updates.json' file. This file tracks when you last downloaded updates for Lutris components. It's not too critical.

I've committed a fix; it will react to this problem by updating all components, and rewriting that file.

Please download the latest master code and run the 'bin/lutris' script within; this should fix your updates.json file, and after that the release Lutris should work too.

**Comment by Exellin** [comment]
Thank you @danieljohnson2!  It turns out it was corrupted just by being an empty file, and i was able to fix it by putting `{}` into the file which is what your fix was doing.

**Comment by ebdavison** [comment]
I had the same issue but no real error until I ran it with `lutris -d` to see the None type error.
