### ISSUE TITLE
Lutris no longer shows games in the library

### ISSUE THREAD

**Issue by Dubi1** [lutris/lutris#4885]
### Bug description

Since 0.5.13 Lutris no longer shows games in the library. It seems to just be a GUI problem, as I can still search games in the top bar and games in the recent and favourites categories still display.

### How to Reproduce

Open Lutris

### Expected behavior

The games should show up in the Library

### Log output

```shell
INFO     2023-06-02 14:26:39,651 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-02 14:26:39,653 [startup.check_driver:65]:Using NVIDIA drivers 530.30.02 for x86_64
INFO     2023-06-02 14:26:39,653 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 3070 Ti
INFO     2023-06-02 14:26:39,653 [startup.check_driver:85]:GPU: 10DE:2482 19DA:1653 (nvidia drivers)
WARNING  2023-06-02 14:26:39,680 [startup.check_vulkan:149]:Vulkan reports an API version of 1.2.162. 1.3.0 is required for the latest DXVK.
DEBUG    2023-06-02 14:26:39,939 [lutris.get_missing_game_ids:191]:Checking for missing games
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 936, in on_sidebar_changed
    self.redraw_view()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 739, in redraw_view
    self.update_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 583, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 160, in add_game
    game.runner_text,
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store_item.py", line 95, in runner_text
    return gtk_safe(get_runner_human_name(self.runner))
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 123, in get_runner_human_name
    _cached_runner_human_names[runner_name] = import_runner(runner_name)().human_name
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 82, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/usr/lib/python3/dist-packages/lutris/runners/__init__.py", line 73, in get_runner_module
    raise InvalidRunner("Invalid runner name '%s'" % runner_name)
lutris.runners.InvalidRunner: Invalid runner name 'winesteam'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux 11 bullseye
Arch:            x86_64
Kernel:          5.10.0-23-amd64
Desktop:         GNOME-Classic:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            64.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.30.02
OpenGL Core:     4.6.0 NVIDIA 530.30.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.30.02
Vulkan Version:  1.2.162
Vulkan Drivers:  NVIDIA GeForce RTX 3070 Ti (1.3.236)
```

### Media (optional)

![Bildschirmfoto von 2023-06-02 14-17-49](https://github.com/lutris/lutris/assets/5871166/5bcbea19-60e8-4534-a132-4f0d38c6f8de)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Damn, I seem to remember having obsolete runners in your library didn't crash Lutris.

Anyway, should be easy to fix.

**Comment by danieljohnson2** [comment]
This looks very like #4863, which is fixed in the master.

**Comment by danieljohnson2** [comment]
Please try downloading the master branch of Lutris, and then run the bin/lutris script within. No need to install.

Hopefully, this will show your games- and you can remove or edit any games that use the 'winestream' runner.

**Comment by Dubi1** [comment]
> Please try downloading the master branch of Lutris, and then run the bin/lutris script within. No need to install.
> 
> Hopefully, this will show your games- and you can remove or edit any games that use the 'winestream' runner.
> 
This did indeed solve the problem

**Comment by danieljohnson2** [comment]
Then I think we can declare victory.
