### ISSUE TITLE
Lutris won't start

### ISSUE THREAD

**Issue by kraetur** [lutris/lutris#4897]
Updated my system yesterday and now Lutris won't launch after reboot. Here is my Lutris -d

INFO     2023-06-09 12:17:09,070 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-09 12:17:09,071 [startup.check_driver:73]:Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.6-zen1-1-zen) (0x73df)
INFO     2023-06-09 12:17:09,072 [startup.check_driver:85]:GPU: 1002:73DF 1849:5210 (amdgpu drivers)
DEBUG    2023-06-09 12:17:09,244 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 40, in get_installed_apps
name, appid, version, branch, origin, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 291, in do_activate
self.window = LutrisWindow(application=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 123, in __init__
self.sidebar.initialize_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
self.update_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
self.installed_runners = [runner.name for runner in runners.get_installed()]
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
if runner.is_installed():
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 476, in is_installed
return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 60, in is_app_installed
for app in get_installed_apps():
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 43, in get_installed_apps
name, appid, version, branch, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 1)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 657, in do_command_line
self.window.present()
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

2023-06-09 12:26:38,806: Starting Lutris 0.5.13
2023-06-09 12:26:38,807: Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.6-zen1-1-zen) (0x73df)
2023-06-09 12:26:38,807: GPU: 1002:73DF 1849:5210 (amdgpu drivers)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 40, in get_installed_apps
name, appid, version, branch, origin, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 291, in do_activate
self.window = LutrisWindow(application=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 123, in __init__
self.sidebar.initialize_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
self.update_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
self.installed_runners = [runner.name for runner in runners.get_installed()]
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
if runner.is_installed():
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 476, in is_installed
return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 60, in is_app_installed
for app in get_installed_apps():
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 43, in get_installed_apps
name, appid, version, branch, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 1)
2023-06-09 12:26:38,865: Fetching installer https://lutris.net/api/installers/flatpak
2023-06-09 12:26:38,866: GET https://lutris.net/api/installers/flatpak
INFO     2023-06-09 12:36:28,939 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-09 12:36:28,940 [startup.check_driver:73]:Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.6-zen1-1-zen) (0x73df)
INFO     2023-06-09 12:36:28,941 [startup.check_driver:85]:GPU: 1002:73DF 1849:5210 (amdgpu drivers)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 40, in get_installed_apps
name, appid, version, branch, origin, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 291, in do_activate
self.window = LutrisWindow(application=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 123, in __init__
self.sidebar.initialize_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
self.update_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
self.installed_runners = [runner.name for runner in runners.get_installed()]
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
if runner.is_installed():
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 476, in is_installed
return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 60, in is_app_installed
for app in get_installed_apps():
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 43, in get_installed_apps
name, appid, version, branch, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 1)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 657, in do_command_line
self.window.present()
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'
INFO     2023-06-09 12:37:03,744 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-09 12:37:03,745 [startup.check_driver:73]:Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.6-zen1-1-zen) (0x73df)
INFO     2023-06-09 12:37:03,745 [startup.check_driver:85]:GPU: 1002:73DF 1849:5210 (amdgpu drivers)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 40, in get_installed_apps
name, appid, version, branch, origin, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 291, in do_activate
self.window = LutrisWindow(application=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 123, in __init__
self.sidebar.initialize_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
self.update_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
self.installed_runners = [runner.name for runner in runners.get_installed()]
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
if runner.is_installed():
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 476, in is_installed
return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 60, in is_app_installed
for app in get_installed_apps():
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 43, in get_installed_apps
name, appid, version, branch, installation = package.split("\t")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 1)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 657, in do_command_line
self.window.present()
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

**Comment by Kandelai** [comment]
Ok, this looks like the same issue I am getting. I think it is maybe due to python, my python version 3.11.3-1. 

I am on Arch/Garuda Linux/KDE

System Info;
Operating System: Garuda Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.6-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 6 × Intel® Core™ i5-9600K CPU @ 3.70GHz
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

I have tried; Lutris from Arch repos version 0.5.13-5 and currently Lutris-git version, whatever git version is currently. Both crash at startup leaving Python in running/zombie state.

Here is my output from CLI;
[xxxx@xxxx-mainpc ~]$ lutris
2023-06-09 12:48:12,592: Starting Lutris 0.5.13
2023-06-09 12:48:12,594: Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.6-zen1-1-zen) (0x73df)
2023-06-09 12:48:12,594: GPU: 1002:73DF 148C:2310 (amdgpu drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 40, in get_installed_apps
    name, appid, version, branch, origin, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 291, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 123, in __init__
    self.sidebar.initialize_rows()
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
    self.update_rows()
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 476, in is_installed
    return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 60, in is_app_installed
    for app in get_installed_apps():
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 43, in get_installed_apps
    name, appid, version, branch, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 1)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 657, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

**Comment by danieljohnson2** [comment]
You may not be using flatpak, but Lutris is trying to use it to access any flatpak games you have installed, I think. It is choking on the output of the flatpak list command.

Please provide the output of this command:
```
flatpak list > list.txt
```

That command will drop the output into a file 'list.txt' and I want to see what's in there.

**Comment by kraetur** [comment]
The output for me was blank because I didn't have any flatpaks installed. I just installed a flatpak and I guess lutris now has what it needs and has opened fine.  Thanks!

**Comment by danieljohnson2** [comment]
@Kandelai, can you provide the flatpak list output?

I've got a theory, but I'd like something concrete here.

**Comment by danieljohnson2** [comment]
OK, alternate plan. I think this happens when 'flatpak list' returns nothing and we try to parse a blank line. I've added a check to the master branch to skip blank lines. It's not a real blank line, it's what happens when you split nothing, but it crashes us all the same.

So, if anyone is still having this problem, please download the master branch and run the bin/lutris script within- see if that will start up and let us know.

It looks like @kraetur's work-around can be used until the next Lutris release- just install anything as a flatpak. But I would like to confirm that my fix fixes things.

**Comment by Kandelai** [comment]
New Lutris update and the issue is fixed for me. Sorry I missed your previous request, but all is good. I think you figured it out, much thanks.

**Comment by danieljohnson2** [comment]
Glorious victory!

Thanks for checking.

**Comment by Kandelai** [comment]
Looks like this issue might be back...

> Traceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 45, in <module>
    from lutris.gui.dialogs.delegates import LaunchUIDelegate, InstallUIDelegate, CommandLineUIDelegate
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/delegates.py", line 9, in <module>
    from lutris.runners import wine
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 26, in <module>
    from lutris.util.wine.extract_icon import PEFILE_AVAILABLE, ExtractIcon
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/extract_icon.py", line 12, in <module>
    from PIL import Image
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: libimagequant.so.0: cannot open shared object file: No such file or directory
