### ISSUE TITLE
Error python?

### ISSUE THREAD

**Issue by Rxon7** [lutris/lutris#490]
$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 27, in <module>
    app = Application()
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 48, in __init__
    self.add_main_option('debug',
AttributeError: 'Application' object has no attribute 'add_main_option'

**Comment by TingPing** [comment]
Duplicate of #464
