### ISSUE TITLE
gobject `lutris+gui+dialogs+MessageDialog' doesn't support property `secondary_message'

### ISSUE THREAD

**Issue by toby3d** [lutris/lutris#4903]
### Bug description

Any attempt to run the game via Wine leads to an error message that can only close the game does not start.

### How to Reproduce

1. Install any Windows game via exe-installer, for my example, Nancy Drew: Secrets can kill (1998)
2. Use system libraries and Wine 8.9 (staging)
3. Try run the game

### Expected behavior

Trying to start the game, there may be errors on her part, but not on Lutris.

### Log output

```shell
NFO     2023-06-15 00:37:36,850 [startup.init_lutris:203]:Starting Lutris 0.5.13
INFO     2023-06-15 00:37:36,852 [startup.check_driver:65]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-06-15 00:37:36,852 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 3080 Laptop GPU
INFO     2023-06-15 00:37:36,852 [startup.check_driver:85]:GPU: 10DE:24DC 17AA:3A58 (nvidia drivers)
[obs-vkcapture] Init Vulkan 1.3.3
[obs-vkcapture] Init Vulkan 1.3.3
DEBUG    2023-06-15 00:37:36,981 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-15 00:37:37,053 [lutris.get_missing_game_ids:191]:Checking for missing games
ERROR    2023-06-15 00:37:40,627 [exceptions.wrapper:95]:Nancy Drew: Secrets can kill (wine) has encountered an error: gobject `lutris+gui+dialogs+MessageDialog' doesn't support property `secondary_message'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 643, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 621, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 1103, in play
    fsync_display_version_warning()
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/wine.py", line 423, in fsync_display_version_warning
    MessageDialog(
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 577, in __init__
    self._init(*args, **new_kwargs)
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 522, in __init__
    _window_init(self, *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gobject `lutris+gui+dialogs+MessageDialog' doesn't support property `secondary_message'
DEBUG    2023-06-15 00:37:40,629 [application.on_game_stop:679]:Removing 39 from running IDs
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.1.31-1-lts
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800H with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            17.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan Version:  1.3.253
Vulkan Drivers:  NVIDIA GeForce RTX 3080 Laptop GPU (1.3.236)
```

### Media (optional)

![изображение](https://github.com/lutris/lutris/assets/5412322/89e67b92-8139-4f16-9583-cc31c62d6dfa)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Fixed by https://github.com/lutris/lutris/commit/129f2c91424f2dfd9889fef05804d7243c5d9301
