### ISSUE TITLE
AutoMicroX Profile not working

### ISSUE THREAD

**Issue by mintdaniel42** [lutris/lutris#4911]
### Bug description

I tried to setup AntiMicroX for games that do not support controllers natively. When I execute AMX directly it works as intended but when I setup Lutris to use the AMX config file it does nothing.

### How to Reproduce

1. Go to 'Global Settings > Input > AntiMicroX Profile'
2. Enter a valid file path pointing to a .amgp file
3. Start any game
4. Controller mapping does not work

### Expected behavior

Lutris should map the keys / mouse to the buttons / sticks as AMX does

### Additional Information

- Flatpak Permissions are fine (devices=all and able to read the file)
- Tried with Lutris[deb] and Lutris[Flatpak]
- Tried with different games

### Log output

```shell
Using Mindustry for testing:
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete

** (process:188725): WARNING **: 21:05:14.281: Error writing credentials to socket: Fehler beim Senden der Nachricht: Datenübergabe unterbrochen (broken pipe)
INFO     2023-06-18 21:05:14,355 [startup.init_lutris:237]:Starting Lutris 0.5.13
INFO     2023-06-18 21:05:14,359 [startup.check_driver:72]:Running Intel Mesa driver 23.1.1 on Mesa Intel(R) HD Graphics 4000 (IVB GT2) (0x166)
INFO     2023-06-18 21:05:14,359 [startup.check_driver:84]:GPU: 8086:0166 1028:0534 (i915 drivers)
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
WARNING  2023-06-18 21:05:14,419 [startup.check_vulkan:171]:Vulkan reports that the 'Intel(R) HD Graphics 4000 (IVB GT2)' device has API version of 1.2.246. 1.3.0 is required for the latest DXVK.
DEBUG    2023-06-18 21:05:14,571 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-18 21:05:19,611 [application.show_window:339]:Showing window EditGameConfigDialog19
DEBUG    2023-06-18 21:05:20,761 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-18 21:05:20,912 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-18 21:05:21,116 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-18 21:05:21,262 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-18 21:05:21,424 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-18 21:05:23,725 [application.on_app_window_destroyed:357]:Removed window EditGameConfigDialog19
DEBUG    2023-06-18 21:05:24,320 [grid.on_item_activated:99]:Item activated: 19
DEBUG    2023-06-18 21:05:24,393 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
WARNING  2023-06-18 21:05:24,543 [game.start_antimicrox:519]:Antimicrox is not installed.
WARNING  2023-06-18 21:05:24,544 [game.start_prelaunch_command:531]:Command /home/daniel/.var/app/net.lutris.Lutris/config/pre.sh not found
DEBUG    2023-06-18 21:05:24,546 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-06-18 21:05:24,546 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-06-18 21:05:24,547 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/daniel/Games/mindustry"
DEBUG    2023-06-18 21:05:24,547 [command.start:141]:SDL_GAMECONTROLLERCONFIG="030000007900000006000000100100001216,DragonRise Inc. Generic USB Joystick,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,"
DEBUG    2023-06-18 21:05:24,547 [command.start:141]:SDL_VIDEO_FULLSCREEN_DISPLAY="1"
DEBUG    2023-06-18 21:05:24,547 [command.start:141]:VK_ICD_FILENAMES="/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json"
DEBUG    2023-06-18 21:05:24,547 [command.start:141]:LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/app/lib/i386-linux-gnu:/app/lib:/app/lib32:/usr/lib/x86_64-linux-gnu/GL/default/lib:/app/lib/i386-linux-gnu/GL/default/lib:/app/lib/ffmpeg/.:/app/lib32/ffmpeg/.:/usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/lib:/usr/lib/x86_64-linux-gnu/openh264/extra:/lib:/lib64:/usr/lib:/usr/lib64:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/Ubuntu-18.04-i686:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/lib:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/usr/lib:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/Ubuntu-18.04-x86_64:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/lib:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/daniel/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-06-18 21:05:24,548 [command.start:141]:game_name="Mindustry"
DEBUG    2023-06-18 21:05:24,548 [command.start:141]:PYTHONPATH="/app/lib/lutris:/app/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/app/lib/python3.10/site-packages:/usr/lib/python3.10/site-packages"
DEBUG    2023-06-18 21:05:24,548 [command.start:141]:LUTRIS_GAME_UUID="f89c7cb9-c007-43fc-82ce-0a65ee959556"
Started initial process 101 from gamemoderun ./start.sh
Start monitoring process.
[W] Failed to initialize Discord RPC - you are likely using a JVM <16.
[I] [Core] Initialized SDL v2.0.10
[I] [Audio] Initialized SoLoud 202111 using MiniAudio at 44100hz / 900 samples / 2 channels
[I] [GL] Version: OpenGL 4.2.0 / Intel / Mesa Intel(R) HD Graphics 4000 (IVB GT2)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 11.0.18
[I] [RAM] Available: 3.8 GB
[I] [Mindustry] Version: 144.3
[I] Loaded mod 'moon mod' in 24.203112ms
[E] rhino.JavaScriptException: Error: Module "planet" not found. (main.js#3)
	at rhino.ScriptRuntime.throwError(ScriptRuntime.java:3939)
	at rhino.module.Require.getModule(Require.java:346)
	at rhino.module.Require.getExportedModuleInterface(Require.java:248)
	at rhino.module.Require.call(Require.java:202)
	at rhino.optimizer.OptRuntime.callName(OptRuntime.java:51)
	at rhino.gen.main_js_3._c_anonymous_1(main.js:3)
	at rhino.gen.main_js_3.call(main.js)
	at rhino.optimizer.OptRuntime.call0(OptRuntime.java:15)
	at rhino.gen.main_js_3._c_script_0(main.js:0)
	at rhino.gen.main_js_3.call(main.js)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.main_js_3.call(main.js)
	at rhino.gen.main_js_3.exec(main.js)
	at rhino.Context.evaluateString(Context.java:989)
	at mindustry.mod.Scripts.run(Scripts.java:86)
	at mindustry.mod.Scripts.run(Scripts.java:76)
	at mindustry.mod.Mods.lambda$loadScripts$24(Mods.java:645)
	at arc.struct.Seq.each(Seq.java:182)
	at mindustry.mod.Mods.eachEnabled(Mods.java:787)
	at mindustry.mod.Mods.loadScripts(Mods.java:633)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:159)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:333)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:206)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

[E] [moon-mod/main.js]: JavaScriptException: Error: Module "planet" not found. (main.js#3)
[I] Time to initialize modded scripts: 299.91827
[W] [ATG.hjson]: Ignoring unknown field: flameRadius (DrawCrucibleFlame)
[W] [Alectro.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [Alectro.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [Alectro.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: firstShotDelay (LaserBulletType)
[W] [Defragmentation.hjson]: Ignoring unknown field: shotDelay (LaserBulletType)
[W] [Dragonfly.hjson]: Ignoring unknown field: drawOutlines (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: heigth (BasicBulletType)
[W] [Fortress-music.hjson]: Ignoring unknown field: isAir (LogicBlock)
[W] [Fortressspeaker.hjson]: Ignoring unknown field: pause (GenericCrafter)
[W] [Frostbite.hjson]: Ignoring unknown field: recoilAmount (LaserTurret)
[W] [Frostbite.hjson]: Ignoring unknown field: restitution (LaserTurret)
[W] [Getharspeaker.hjson]: Ignoring unknown field: pause (GenericCrafter)
[W] [Ghetar-music.hjson]: Ignoring unknown field: isAir (LogicBlock)
[W] [Leech.hjson]: Ignoring unknown field: burstSpacing (ContinuousTurret)
[W] [Leech.hjson]: Ignoring unknown field: shots (ContinuousTurret)
[W] [Leech.hjson]: Ignoring unknown field: recoilAmount (ContinuousTurret)
[W] [Leech.hjson]: Ignoring unknown field: length (PointLaserBulletType)
[W] [Leech.hjson]: Ignoring unknown field: width (PointLaserBulletType)
[W] [MoonRay.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [MoonRay.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [MoonRay.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Pike.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [Pike.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [Pike.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Restart-missle.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [Restart-missle.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [Restart-missle.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [Restart.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [Restart.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Restart.hjson]: Ignoring unknown field: smoothReloadSpeed (ItemTurret)
[W] [Restart.hjson]: Ignoring unknown field: hidden (ItemTurret)
[W] [Solar-music.hjson]: Ignoring unknown field: isAir (LogicBlock)
[W] [Solarspeaker.hjson]: Ignoring unknown field: pause (GenericCrafter)
[W] [Stinger.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Stinger.hjson]: Ignoring unknown field: spread (ItemTurret)
[W] [Stinger.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [Stinger.hjson]: Ignoring unknown field: restitution (ItemTurret)
[W] [Stormer.hjson]: Ignoring unknown field: basePrefix (ItemTurret)
[W] [Tide.hjson]: Ignoring unknown field: spread (ShootPattern)
[W] [Zap.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [Zap.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Zap.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [Zilo.hjson]: Ignoring unknown field: accesible (Planet)
[W] [Zilo.hjson]: Ignoring unknown field: allowWavesSimulation (Planet)
[W] [Zilo.hjson]: Ignoring unknown field: allowSectorSimulation (Planet)
[W] [Zilo.hjson]: Ignoring unknown field: sectorSize (Planet)
[W] [aerogel.hjson]: Ignoring unknown field: type (Item)
[W] [aluminium.hjson]: Ignoring unknown field: type (Item)
[W] [arcalith-mixer.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [arcalith-synthesizer.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [arcalith.hjson]: Ignoring unknown field: cache (Liquid)
[W] [arcanite.hjson]: Ignoring unknown field: type (Item)
[W] [arcanthium-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [arcanthium-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [arcanthium-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [arcanthium.hjson]: Ignoring unknown field: type (Item)
[W] [axoflare4.hjson]: Ignoring unknown field: shootSoundVolume (Weapon)
[W] [axoflare5.hjson]: Ignoring unknown field: heigth (BasicBulletType)
[W] [bauxite.hjson]: Ignoring unknown field: type (Item)
[W] [burner.hjson]: Ignoring unknown field: consumeEffect (Incinerator)
[W] [burner.hjson]: Ignoring unknown field: power (Incinerator)
[W] [cryo-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [cryo-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [cryo-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [cryoflare4.hjson]: Ignoring unknown field: colors (BasicBulletType)
[W] [cryoflare4.hjson]: Ignoring unknown field: collidesFloor (BasicBulletType)
[W] [cryogenic-generator.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [cryogenium-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [cryogenium-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [cryogenium-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [cryogenium.hjson]: Ignoring unknown field: type (Item)
[W] [cryomech.hjson]: Ignoring unknown field: mechStepShake (UnitType)
[W] [cryomech.hjson]: Ignoring unknown field: explodeRange (BasicBulletType)
[W] [cryomech2.hjson]: Ignoring unknown field: mechStepShake (UnitType)
[W] [cryomech2.hjson]: Ignoring unknown field: explodeRange (BasicBulletType)
[W] [cryomech3.hjson]: Ignoring unknown field: mechStepShake (UnitType)
[W] [cryospider4.hjson]: Ignoring unknown field: shots (Weapon)
[W] [diamond.hjson]: Ignoring unknown field: type (Item)
[W] [excisionflare.hjson]: Ignoring unknown field: speed (Weapon)
[W] [flame-missile.hjson]: Ignoring unknown field: collidesGround (UnitType)
[W] [flame-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [flame-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [flame-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [ice-shard.hjson]: Ignoring unknown field: type (Item)
[W] [ionized-xenon.hjson]: Ignoring unknown field: cache (Liquid)
[W] [ionized-xenon.hjson]: Ignoring unknown field: parent (Liquid)
[W] [moonstone-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [moonstone-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [moonstone-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [moonstone.hjson]: Ignoring unknown field: type (Item)
[W] [payload-constructor.hjson]: Ignoring unknown field: craftEffect (Constructor)
[W] [payload-constructor.hjson]: Ignoring unknown field: updateEffect (Constructor)
[W] [pin.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [pin.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [pin.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [pin.hjson]: Ignoring unknown field: explodeRange (BasicBulletType)
[W] [reinforced-cryofabric.hjson]: Ignoring unknown field: type (Item)
[W] [repair-field.hjson]: Ignoring unknown field: phase (MendProjector)
[W] [repair-field.hjson]: Ignoring unknown field: color (MendProjector)
[W] [resotank6.hjson]: Ignoring unknown field: collidesFloor (BasicBulletType)
[W] [salmon.hjson]: Ignoring unknown field: hitsize (UnitType)
[W] [shield.hjson]: Ignoring unknown field: hidden (BaseShield)
[W] [xenon.hjson]: Ignoring unknown field: cache (Liquid)
[W] [xenon.hjson]: Ignoring unknown field: parent (Liquid)
[W] [yttrium.hjson]: Ignoring unknown field: type (Item)
[W] Sprite 'eror' in mod 'moon-mod' attempts to override a non-existent sprite. Ignoring.
[I] Total time to load: 7880ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 44 community servers.
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
DEBUG    2023-06-18 21:05:37,585 [command.on_stop:195]:Process 99 has terminated with code 0
DEBUG    2023-06-18 21:05:38,573 [game.beat:842]:Game thread stopped
WARNING  2023-06-18 21:05:38,573 [game.on_game_quit:879]:Game still running (state: running)
INFO     2023-06-18 21:05:38,573 [game.stop:853]:Stopping Mindustry (linux)
DEBUG    2023-06-18 21:05:38,574 [game.stop_game:809]:Mindustry (linux) has run for 14 seconds
DEBUG    2023-06-18 21:05:38,574 [application.on_game_stop:679]:Removing 19 from running IDs
DEBUG    2023-06-18 21:05:38,598 [game.stop_game:821]:Playtime: 13 minutes
DEBUG    2023-06-18 21:05:38,598 [game.on_game_quit:897]:Mindustry stopped at So, 18 Jun 2023 21:05:38
DEBUG    2023-06-18 21:05:38,751 [lutris.add_to_path_cache:154]:Adding Mindustry (linux) to path cache
DEBUG    2023-06-18 21:05:38,770 [xrandr.change_resolution:127]:Switching to 1366x768 on LVDS-1
INFO     2023-06-18 21:05:38,770 [xrandr.change_resolution:138]:Switching resolution of LVDS-1 to 1366x768
DEBUG    2023-06-18 21:05:38,776 [xrandr.change_resolution:127]:Switching to 1920x1080 on HDMI-2
INFO     2023-06-18 21:05:38,776 [xrandr.change_resolution:138]:Switching resolution of HDMI-2 to 1920x1080
WARNING  2023-06-18 21:05:38,781 [display.restore_gamma:53]:xgamma is not available on your system
```

### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          5.19.0-45-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             15.5 GB
Swap:            2.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version:  4.2 (Compatibility Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL Core:     4.2 (Core Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL ES:       OpenGL ES 3.0 Mesa 23.1.1 (git-fa55e3c026)
Vulkan Version:  1.3.224
Vulkan Drivers:  Intel(R) HD Graphics 4000 (IVB GT2) (1.2.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
That's because you're in a Flatpak and it can't see programs installed on your host. 
I made a patch to use flatpak-spawn in this situation: 10c0aacf
