### ISSUE TITLE
Error 256 (League of Legends)

### ISSUE THREAD

**Issue by TheBatman** [lutris/lutris#4921]
### Bug description

I've surfed the web looking for possible fixes such this one: https://forums.lutris.net/t/how-to-fix-exit-with-return-code-256/17392
Sadly, i was unlucky and the issue persists, i can't install LoL it's always the same outcome with the latest lutris which is 0.5.13, with earlier versions such as 0.5.9 this issue doesn't pop out and i can install LoL and any other wine game with no issue.
However, if Lutris was installed through flatpak it installs LoL.

![image](https://github.com/lutris/lutris/assets/13712357/0960ed2e-e87b-4639-bf1e-b6f01c80e7c1)

### How to Reproduce

1. Go to '+ in order to install LoL'
2. Click on 'Look for installers on Lutris'
3. Do 'Search for desired game, click on standard install'
4. See 'Error 256 while creating a wineprefix'

### Expected behavior

Install League of legends

### Log output

```shell
rodrigoal@Rodrigo-Al-HP:~$ lutris -d
WARNING: radv is not a conformant Vulkan implementation, testing use only.
INFO     2023-07-02 17:54:21,562 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-02 17:54:21,570 [startup.check_driver:73]:Running AMD Mesa driver 23.1.3 on AMD Radeon R5 Graphics (kabini, LLVM 15.0.7, DRM 3.49, 6.1.0-9-amd64) (0x9851)
INFO     2023-07-02 17:54:21,571 [startup.check_driver:85]:GPU: 1002:9851 103C:2266 (amdgpu drivers)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
DEBUG    2023-07-02 17:54:22,405 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-07-02 17:54:30,518 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-07-02 17:54:33,450 [http._request:88]:GET https://lutris.net/api/games?search=lea&with-installers=True
DEBUG    2023-07-02 17:54:51,923 [http._request:88]:GET https://lutris.net/api/games?search=league+of+legends&with-installers=True
DEBUG    2023-07-02 17:54:55,551 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/league-of-legends
DEBUG    2023-07-02 17:54:55,551 [http._request:88]:GET https://lutris.net/api/installers/league-of-legends
DEBUG    2023-07-02 17:54:56,819 [application.show_window:339]:Showing window InstallerWindowleague-of-legends
DEBUG    2023-07-02 17:54:56,820 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}
DEBUG    2023-07-02 17:54:58,566 [displayconfig.get_current_resolution:643]:Retrieving current resolution
DEBUG    2023-07-02 17:55:01,524 [downloader.start:67]:⬇ https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe
DEBUG    2023-07-02 17:55:07,794 [downloader.on_download_completed:170]:Finished downloading https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe
INFO     2023-07-02 17:55:08,033 [file_box.on_download_complete:239]:Download completed
DEBUG    2023-07-02 17:55:08,033 [files_box.on_file_available:108]:lol_installer is available
INFO     2023-07-02 17:55:08,034 [files_box.on_file_available:114]:All files available
INFO     2023-07-02 17:55:08,034 [installerwindow.on_files_available:635]:All files are available, continuing install
DEBUG    2023-07-02 17:55:08,039 [interpreter.create_game_folder:218]:Creating destination path /home/rodrigoal/Games/league-of-legends
DEBUG    2023-07-02 17:55:08,040 [interpreter._iter_commands:361]:Installer command: {'input_menu': {'id': 'LOCALE', 'options': [{'cs_CZ': 'Čeština'}, {'en_AU': 'English AUS'}, {'en_GB': 'English U.K.'}, {'en_US': 'English U.S.'}, {'fr_FR': 'Français'}, {'de_DE': 'Deutsch'}, {'es_ES': 'Español'}, {'es_MX': 'Español Mexicano'}, {'it_IT': 'Italiano'}, {'ja_JP': '日本語'}, {'hu_HU': 'Magyar'}, {'pl_PL': 'Polski'}, {'pt_BR': 'Português do Brasil'}, {'ro_RO': 'Romanian'}, {'ru_RU': 'русский'}, {'tr_TR': 'Türkçe'}], 'preselect': 'en_US'}}
DEBUG    2023-07-02 17:55:10,486 [interpreter._iter_commands:361]:Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2023-07-02 17:55:10,498 [wine.create_prefix:98]:Creating a win64 prefix in /home/rodrigoal/Games/league-of-legends
DEBUG    2023-07-02 17:55:10,499 [system.execute:74]:Executing /home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineboot
DEBUG    2023-07-02 17:55:10,500 [system.execute:80]:WINEARCH=win64 WINEPREFIX=/home/rodrigoal/Games/league-of-legends WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/mono WINE_GECKO_CACHE_DIR=/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/gecko
INFO     2023-07-02 17:56:01,546 [wine.create_prefix:153]:win64 Prefix created in /home/rodrigoal/Games/league-of-legends
DEBUG    2023-07-02 17:56:01,580 [interpreter._iter_commands:361]:Installer command: {'task': {'args': '$lol_installer', 'executable': '$GAMEDIR/drive_c/windows/explorer.exe', 'include_processes': 'explorer.exe', 'name': 'wineexec'}}
DEBUG    2023-07-02 17:56:01,723 [wine.use_lutris_runtime:123]:/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine is provided by Lutris, using runtime
ERROR    2023-07-02 17:56:01,775 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2023-07-02 17:56:01,775 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2023-07-02 17:56:01,798 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-07-02 17:56:01,799 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/rodrigoal/Games/league-of-legends"
DEBUG    2023-07-02 17:56:01,799 [command.start:141]:LD_LIBRARY_PATH="/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib:/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib64:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/lib/i386-linux-gnu/i686/sse2:/lib:/lib64:/lib32:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/rodrigoal/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/rodrigoal/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/rodrigoal/.local/share/lutris/runtime/steam/i386/lib:/home/rodrigoal/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/rodrigoal/.local/share/lutris/runtime/steam/i386/usr/lib:/home/rodrigoal/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/rodrigoal/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/rodrigoal/.local/share/lutris/runtime/steam/amd64/lib:/home/rodrigoal/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/rodrigoal/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-07-02 17:56:01,799 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-07-02 17:56:01,799 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-07-02 17:56:01,800 [command.start:141]:WINEARCH="win64"
DEBUG    2023-07-02 17:56:01,800 [command.start:141]:WINE="/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine"
DEBUG    2023-07-02 17:56:01,800 [command.start:141]:WINE_MONO_CACHE_DIR="/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/mono"
DEBUG    2023-07-02 17:56:01,800 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/gecko"
DEBUG    2023-07-02 17:56:01,800 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib64/gstreamer-1.0/:/home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-07-02 17:56:01,801 [command.start:141]:WINEPREFIX="/home/rodrigoal/Games/league-of-legends"
DEBUG    2023-07-02 17:56:01,801 [command.start:141]:WINEESYNC="1"
DEBUG    2023-07-02 17:56:01,801 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-07-02 17:56:01,801 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-07-02 17:56:01,801 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-07-02 17:56:01,801 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-07-02 17:56:01,802 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/rodrigoal/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-07-02 17:56:01,802 [command.start:141]:PROTON_EAC_RUNTIME="/home/rodrigoal/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-07-02 17:56:01,802 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d12core,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-07-02 17:56:01,802 [command.start:141]:DXVK_STATE_CACHE_PATH="/home/rodrigoal/Games/league-of-legends"
DEBUG    2023-07-02 17:56:01,802 [command.start:141]:STAGING_SHARED_MEMORY="1"
DEBUG    2023-07-02 17:56:01,803 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-07-02 17:56:01,803 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/local/lib/python3.11/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2023-07-02 17:56:01,803 [command.start:141]:LUTRIS_GAME_UUID="a2a25289-caef-4c29-a613-fe65d91ca5e3"
Started initial process 12302 from /home/rodrigoal/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine /home/rodrigoal/Games/league-of-legends/drive_c/windows/explorer.exe /home/rodrigoal/.cache/lutris/installer/league-of-legends/lol_installer/live.na.exe
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
DEBUG    2023-07-02 17:56:02,131 [command.on_stop:195]:Process 12296 has terminated with code 256
DEBUG    2023-07-02 17:56:02,806 [commands._monitor_task:444]:Return code: 256
ERROR    2023-07-02 17:56:02,807 [errors.__init__:18]:El comando ha finalizado con código 256
ERROR    2023-07-02 17:56:02,807 [exceptions.wrapper:63]:El comando ha finalizado con código 256
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 446, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: El comando ha finalizado con código 256
G    2023-07-02 19:19:01,827 [application.show_window:339]:Showing window AddGamesWindow{}
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux 12 bookworm
Arch:            x86_64
Kernel:          6.1.0-9-amd64
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD A8-6410 APU with AMD Radeon R5 Graphics
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             10.6 GB
Swap:            1.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon R5 Graphics (kabini, LLVM 15.0.7, DRM 3.49, 6.1.0-9-amd64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.3 - kisak-mesa PPA
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.3 - kisak-mesa PPA
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.3 - kisak-mesa PPA
Vulkan Version:  1.3.239
Vulkan Drivers:  AMD Radeon R5 Graphics (RADV KABINI) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by RedsonBr140** [comment]
I'm having the same issue with the BR version.
logs here:
```
lutris -d
INFO     2023-07-03 10:45:08,846 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-03 10:45:08,849 [startup.check_driver:73]:Running Intel Mesa driver 23.1.3 on Mesa Intel(R) HD Graphics 2000 (SNB GT1) (0x102)
INFO     2023-07-03 10:45:08,850 [startup.check_driver:85]:GPU: 8086:0102 1019:3190 (i915 drivers)
WARNING  2023-07-03 10:45:08,851 [startup.check_vulkan:144]:Vulkan is not available or your system isn't Vulkan capable
DEBUG    2023-07-03 10:45:10,167 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-03 10:45:10,250 [lutris.get_missing_game_ids:191]:Checking for missing games
WARNING  2023-07-03 10:45:10,251 [lutriswindow.get_missing_games:408]:Path cache out of date? (2 IDs missing)
DEBUG    2023-07-03 10:45:15,288 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-07-03 10:45:22,665 [http._request:88]:GET https://lutris.net/api/games?search=league+of+legends&with-installers=True
DEBUG    2023-07-03 10:45:25,707 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/league-of-legends
DEBUG    2023-07-03 10:45:25,707 [http._request:88]:GET https://lutris.net/api/installers/league-of-legends
DEBUG    2023-07-03 10:45:26,924 [application.show_window:339]:Showing window InstallerWindowleague-of-legends
DEBUG    2023-07-03 10:45:26,925 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}
DEBUG    2023-07-03 10:45:29,034 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-03 10:45:33,290 [downloader.start:67]:⬇ https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.br.exe
DEBUG    2023-07-03 10:45:40,731 [downloader.on_download_completed:170]:Finished downloading https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.br.exe
INFO     2023-07-03 10:45:40,800 [file_box.on_download_complete:239]:Download completed
DEBUG    2023-07-03 10:45:40,800 [files_box.on_file_available:108]:lol_installer is available
INFO     2023-07-03 10:45:40,801 [files_box.on_file_available:114]:All files available
INFO     2023-07-03 10:45:40,801 [installerwindow.on_files_available:635]:All files are available, continuing install
DEBUG    2023-07-03 10:45:40,803 [interpreter._iter_commands:361]:Installer command: {'input_menu': {'id': 'LOCALE', 'options': [{'cs_CZ': 'Čeština'}, {'en_AU': 'English AUS'}, {'en_GB': 'English U.K.'}, {'en_US': 'English U.S.'}, {'fr_FR': 'Français'}, {'de_DE': 'Deutsch'}, {'es_ES': 'Español'}, {'es_MX': 'Español Mexicano'}, {'it_IT': 'Italiano'}, {'ja_JP': '日本語'}, {'hu_HU': 'Magyar'}, {'pl_PL': 'Polski'}, {'pt_BR': 'Português do Brasil'}, {'ro_RO': 'Romanian'}, {'ru_RU': 'русский'}, {'tr_TR': 'Türkçe'}], 'preselect': 'pt_BR'}}
DEBUG    2023-07-03 10:45:44,098 [interpreter._iter_commands:361]:Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2023-07-03 10:45:44,102 [wine.create_prefix:98]:Creating a win64 prefix in /home/redson/Games/league-of-legends
DEBUG    2023-07-03 10:45:44,102 [system.execute:74]:Executing /home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineboot
DEBUG    2023-07-03 10:45:44,103 [system.execute:80]:WINEARCH=win64 WINEPREFIX=/home/redson/Games/league-of-legends WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/mono WINE_GECKO_CACHE_DIR=/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/gecko
INFO     2023-07-03 10:45:48,012 [wine.create_prefix:153]:win64 Prefix created in /home/redson/Games/league-of-legends
DEBUG    2023-07-03 10:45:48,111 [interpreter._iter_commands:361]:Installer command: {'task': {'args': '$lol_installer', 'executable': '$GAMEDIR/drive_c/windows/explorer.exe', 'include_processes': 'explorer.exe', 'name': 'wineexec'}}
DEBUG    2023-07-03 10:45:48,158 [wine.use_lutris_runtime:123]:/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine is provided by Lutris, using runtime
ERROR    2023-07-03 10:45:48,827 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2023-07-03 10:45:48,827 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2023-07-03 10:45:48,870 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-07-03 10:45:48,870 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/redson/Games/league-of-legends"
DEBUG    2023-07-03 10:45:48,870 [command.start:141]:LD_LIBRARY_PATH="/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib:/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib64:/usr/lib:/usr/lib32:/usr/lib/libfakeroot:/usr/lib64:/home/redson/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/redson/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/redson/.local/share/lutris/runtime/steam/i386/lib:/home/redson/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/redson/.local/share/lutris/runtime/steam/i386/usr/lib:/home/redson/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/redson/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/redson/.local/share/lutris/runtime/steam/amd64/lib:/home/redson/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/redson/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-07-03 10:45:48,871 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-07-03 10:45:48,871 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-07-03 10:45:48,871 [command.start:141]:WINEARCH="win64"
DEBUG    2023-07-03 10:45:48,871 [command.start:141]:WINE="/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine"
DEBUG    2023-07-03 10:45:48,871 [command.start:141]:WINE_MONO_CACHE_DIR="/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/mono"
DEBUG    2023-07-03 10:45:48,871 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/gecko"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib64/gstreamer-1.0/:/home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:WINEPREFIX="/home/redson/Games/league-of-legends"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:WINEESYNC="1"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/redson/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-07-03 10:45:48,872 [command.start:141]:PROTON_EAC_RUNTIME="/home/redson/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-07-03 10:45:48,873 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d12core,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-07-03 10:45:48,873 [command.start:141]:DXVK_STATE_CACHE_PATH="/home/redson/Games/league-of-legends"
DEBUG    2023-07-03 10:45:48,873 [command.start:141]:STAGING_SHARED_MEMORY="1"
DEBUG    2023-07-03 10:45:48,873 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-07-03 10:45:48,873 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/home/redson/.local/lib/python3.11/site-packages:/usr/lib/python3.11/site-packages"
DEBUG    2023-07-03 10:45:48,873 [command.start:141]:LUTRIS_GAME_UUID="94127e47-ed5f-42e3-9a95-06a2ef988d1e"
lutris-wrapper: /home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine
Started initial process 126697 from /home/redson/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine /home/redson/Games/league-of-legends/drive_c/windows/explorer.exe /home/redson/.cache/lutris/installer/league-of-legends/lol_installer/live.br.exe
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
DEBUG    2023-07-03 10:45:49,127 [command.on_stop:195]:Process 126691 has terminated with code 256
DEBUG    2023-07-03 10:45:49,875 [commands._monitor_task:444]:Return code: 256
ERROR    2023-07-03 10:45:49,876 [errors.__init__:18]:Comando encerrado com o código 256
ERROR    2023-07-03 10:45:49,876 [exceptions.wrapper:63]:Comando encerrado com o código 256
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 446, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Comando encerrado com o código 256
```

**Comment by qwarl** [comment]
@TheBatman how did you install graphics driver? i use debian 12  too. do you get the error "E: The repository 'https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu bookworm Release' does not have a Release file." when install it?

**Comment by lucasalberto01** [comment]
I had a similar problem using the flatpack version of lutris on ubuntu. The solution was to use the .deb version and it worked perfectly.

I think flatpack has some problem with system permissions

**Comment by strycore** [comment]
> @TheBatman how did you install graphics driver? i use debian 12 too. do you get the error "E: The repository 'https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu bookworm Release' does not have a Release file." when install it?

You're not supposed to use Launchpad PPAs on Debian. There is no "bookworm" release on Launchpad as the error message is telling you.

**Comment by TheBatman** [comment]
> @TheBatman how did you install graphics driver? i use debian 12 too. do you get the error "E: The repository 'https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu bookworm Release' does not have a Release file." when install it?

I followed the steps highlighted here: https://salmorejogeek.com/2023/06/23/como-tener-la-ultima-version-de-mesa-en-debian-12-bookworm-rama-estable/
It's in Spanish but it worked with no issues, steam (flatpak) works flawlessly and so does LoL under lutris (Flatpak).

> I had a similar problem using the flatpack version of lutris on ubuntu. The solution was to use the .deb version and it worked perfectly.
> 
> I think flatpack has some problem with system permissions

I used the deb version on Debian and followed the instructions on the website, but i kept getting error 256 :( in my case installing Lutris through Flatpak was the workaround and so far, it's been working only on Flatpak.

**Comment by qwarl** [comment]
@strycore yes and i don't know how to bypass it

@TheBatman thank you, i'll try what you say

**Comment by strycore** [comment]
> @strycore yes and i don't know how to bypass it

You can bypass the error message by installing Ubuntu, which the PPAs support.

**Comment by MattJeanLouis** [comment]
Hello, has anyone found a solution? I was unable to install an older version of Lutris on my Steam Deck, so I'm a bit stuck. Any help would be greatly appreciated.

**Comment by strycore** [comment]
> Hello, has anyone found a solution? I was unable to install an older version of Lutris on my Steam Deck, so I'm a bit stuck. Any help would be greatly appreciated.

I tried installing League on the Steam Deck recently. Installing it in Game mode wasn't possible since completing the install requires closing the Riot launcher from an icon that doesn't appear on Gamescope. On desktop mode, I didn't have any issue installing the game. 
Do you have a download cache set up? During the install, there is a menu on top of the window where you can set that up. I suspect not having a download cache enabled might cause issues during installs but I haven't been able to confirm that.

**Comment by mfernandezgarcia** [comment]
Is someone trying to correc this issue?

**Comment by strycore** [comment]
> Is someone trying to correc this issue?

no, because the people who contribute to Lutris all have League of Legends working just fine.

**Comment by strycore** [comment]
As long as we *know* what is going wrong, writing a fix shouldn't take more than a few minutes.

**Comment by tridoxx** [comment]
some solution when the riotclient keep on running on background. is open the system monitor, o proccess manager, and search for riot rigth click and kill the proccess the installer, will finish

**Comment by strycore** [comment]
The new wine-lol build released a few days ago makes the game playable again.

Other failures to launch seem to be related to older GPUs that don't support Vulkan. 
If anyone still has LoL crashing, is using an older GPU and wants to help troubleshoot this, let me know and I'll re-open the issue.
