### ISSUE TITLE
Support for detecting "bc" command within Lutris Flatpak

### ISSUE THREAD

**Issue by QmwJlHuSg9pa** [lutris/lutris#4927]
### Bug description

I have a pre-launch bash script that requires "bc" for floating point operations.

The pre-launch script determines whether it is running inside a Flatpak environment (`$container` env var) and, if necessary, runs `flatpak-spawn --host bc`. This works well enough, but I would like to utilise `require-binaries: bc` as a safe-guard before installing the game files.

Though, Lutris Flatpak is unable to detect system binaries via `require-binaries` ("This installer requires bc on your system"); it seems to only search within its Flatpak environment.

"bc" comes pre-installed on distros such as Ubuntu and Fedora, but is not included with Lutris Flatpak itself (verifiable by running `flatpak run --command="bc" net.lutris.Lutris`).

### How to Reproduce

1. Create a basic, working installer script
2. Under `script:`, add: `require-binaries: bc`
3. Run Lutris Flatpak, press "Install from a local install script", and select the script.

### Expected behavior

Either, it would be nice to see capability for `require-binaries` somehow expanded to support the above scenario, or alternatively include "bc" with Lutris Flatpak.

### Log output

```shell
DEBUG    2023-07-10 03:50:01,744 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-07-10 03:50:13,098 [__init__.read_script:23]:Loading script(s) from /var/home/<user>/test.yml
DEBUG    2023-07-10 03:50:13,142 [application.show_window:339]:Showing window InstallerWindowtest-test-test-321
DEBUG    2023-07-10 03:50:13,143 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}
DEBUG    2023-07-10 03:50:15,667 [displayconfig.get_current_resolution:643]:Retrieving current resolution
ERROR    2023-07-10 03:50:15,667 [errors.__init__:18]:This installer requires bc on your system
ERROR    2023-07-10 03:50:15,667 [exceptions.wrapper:63]:This installer requires bc on your system
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/lutris/gui/installerwindow.py", line 336, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
  File "/app/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 95, in __init__
    self._check_binary_dependencies()
  File "/app/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 160, in _check_binary_dependencies
    raise ScriptingError(_("This installer requires %s on your system") % dependency)
lutris.installer.errors.ScriptingError: This installer requires bc on your system
```

### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.3.8-100.fc37.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600X Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.52, 6.3.8-100.fc37.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.1 (git-fa55e3c026)
Vulkan Version:  1.3.224
Vulkan Drivers:  AMD Radeon RX 580 Series (RADV POLARIS10) (1.3.246)*
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by QmwJlHuSg9pa** [comment]
FWIW, my desire for this has diminished as I've since rewritten the pre-launch script in Python. This has turned out to be much more concise in execution and no longer relies upon any optional dependencies, such as 'bc'.
