### ISSUE TITLE
ResidualVM removal breaks libraries that have ResidualVM games installed

### ISSUE THREAD

**Issue by snyman** [lutris/lutris#4941]
### Bug description

I have Myst III: Exile installed, it uses the ResidualVM runner. After updating to 0.5.13, my library stopped showing some of my games. After looking at the debug output, it seems like the game using the now-removed runner is causing an exception to be thrown, which I speculate is stopping the loading of games prematurely. It seems to be dependent on the sort order - any game sorted after the ResidualVM game will not appear.

### How to Reproduce

1. Install Lutris 0.5.12
2. Install a game using the ResidualVM runner
3. Install another game using a different runner
4. Update Lutris to 0.5.13
5. If you sort games by install date, neither game should show up due to this error.

### Expected behavior

I expect that if a runner is removed due to being replaced by a different runner, then games are properly migrated to the new runner to avoid issues like this. Or, at least properly show all my games and notify me about the ones that were broken by having an unrecognized runner, rather than a silent error that causes weird behavior.

### Log output

```shell
(lutris:1217152): dbind-WARNING **: 17:41:27.367: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_0: Connection refused
INFO     2023-07-20 17:41:27,902 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-20 17:41:27,904 [startup.check_driver:65]:Using NVIDIA drivers 525.89.02 for x86_64
INFO     2023-07-20 17:41:27,904 [startup.check_driver:69]:GPU: NVIDIA GeForce GTX 1080
INFO     2023-07-20 17:41:27,904 [startup.check_driver:85]:GPU: 10DE:1B80 1462:3360 (nvidia drivers)
INFO     2023-07-20 17:41:27,904 [startup.check_driver:85]:GPU: 1002:7340 1458:2319 (amdgpu drivers)
DEBUG    2023-07-20 17:41:28,034 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-20 17:41:28,088 [lutris.get_missing_game_ids:191]:Checking for missing games
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 936, in on_sidebar_changed
    self.redraw_view()
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 739, in redraw_view
    self.update_store()
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 583, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.11/site-packages/lutris/gui/views/store.py", line 160, in add_game
    game.runner_text,
    ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/views/store_item.py", line 95, in runner_text
    return gtk_safe(get_runner_human_name(self.runner))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 123, in get_runner_human_name
    _cached_runner_human_names[runner_name] = import_runner(runner_name)().human_name
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 82, in import_runner
    runner_module = get_runner_module(runner_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 73, in get_runner_module
    raise InvalidRunner("Invalid runner name '%s'" % runner_name)
lutris.runners.InvalidRunner: Invalid runner name 'residualvm'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files (2)
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.2.2-arch1-1
Desktop:         
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3950X 16-Core Processor
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             62.7 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5500 XT (navi14, LLVM 15.0.7, DRM 3.49, 6.2.2-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.0
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.0
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.0
Vulkan Version:  1.3.246
Vulkan Drivers:  AMD Radeon RX 5500 XT (RADV NAVI14) (1.3.246), NVIDIA GeForce GTX 1080 (1.3.224)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This is a dupe of #4863, fixed in master.

**Comment by snyman** [comment]
Sorry about that, I was searching for issues involving ResidualVM and that didn't turn up

**Comment by danieljohnson2** [comment]
This was all part of the performance work for 0.5.13. Yeah, it crashes, but it crashes *so damn fast*.

@snyman, what you can down is download the master branch and then run the 'bin/lutris' script inside. This should start Lutris and you should be able to get the ResidualVM games and reconfigure them.
