### ISSUE TITLE
Wine prefix not found error (regression)

### ISSUE THREAD

**Issue by JohanG-75** [lutris/lutris#4943]
### Bug description

Running a game since https://github.com/lutris/lutris/commit/9caa508ef1c66b7b4ba8bbd4b09b2e6505322a5f with ~ in the wine prefix crashes wine causing the wine prefix not found error after a while
Lutris is attempting to create an existing prefix (and failing) for some reason

### How to Reproduce

Edit the .yml game launcher manually with ~/path/to/prefix recreates the bug

### Expected behavior

The game starts?

### Log output

```shell
[imecth@localhost ~]$ lutris -d
2023-07-21 19:17:47,129: Command 'fluidsynth' not found on your system
INFO     2023-07-21 19:17:47,456 [startup.init_lutris:171]:Starting Lutris 0.5.13
INFO     2023-07-21 19:17:47,458 [startup.check_driver:72]:Running AMD Mesa driver 23.1.3 on AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.52, 6.3.12-204.fsync.fc38.x86_64) (0x73ff)
INFO     2023-07-21 19:17:47,458 [startup.check_driver:84]:GPU: 1002:73FF 1EAE:6505 (amdgpu drivers)
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
INFO     2023-07-21 19:17:47,530 [api.get_default_runner_version:109]:Getting runner information for wine
DEBUG    2023-07-21 19:17:47,530 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2023-07-21 19:17:49,104 [lutris.get_missing_game_ids:191]:Checking for missing games
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/local/lib64/libinput-config.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
WARNING  2023-07-21 19:17:54,361 [wine.prelaunch:921]:No valid prefix detected in ~/.wine_lol, creating one...
INFO     2023-07-21 19:17:54,362 [wine.create_prefix:98]:Creating a win64 prefix in ~/.wine_lol
DEBUG    2023-07-21 19:17:54,362 [system.execute:74]:Executing /home/imecth/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineboot
DEBUG    2023-07-21 19:17:54,362 [system.execute:80]:WINEARCH=win64 WINEPREFIX=~/.wine_lol WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/imecth/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/mono WINE_GECKO_CACHE_DIR=/home/imecth/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/gecko
INFO     2023-07-21 19:18:08,331 [runner.use_runtime:391]:Runtime disabled by system configuration
DEBUG    2023-07-21 19:18:08,475 [wine.winekill:172]:Killing all wine processes: ['/home/imecth/.local/share/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineserver', '-k']
DEBUG    2023-07-21 19:18:08,475 [wine.winekill:173]:	Wine prefix: ~/.wine_lol
DEBUG    2023-07-21 19:18:08,475 [wine.winekill:174]:	Wine arch: win64
DEBUG    2023-07-21 19:18:08,476 [wine.winekill:180]:Waiting for wine processes to terminate
DEBUG    2023-07-21 19:18:08,476 [wine.winekill:196]:Done waiting.
ERROR    2023-07-21 19:18:08,476 [game.get_game_pids:782]:No LUTRIS_GAME_UUID recorded. The game's PIDs cannot be computed.
DEBUG    2023-07-21 19:18:08,476 [game.stop_game:810]:tft (wine) has run for 0 seconds
WARNING  2023-07-21 19:18:08,476 [game.stop_game:812]:The game has run for a very short time, did it crash?
DEBUG    2023-07-21 19:18:08,476 [application.on_game_stop:680]:Removing 2 from running IDs
DEBUG    2023-07-21 19:18:08,495 [game.stop_game:822]:Playtime: 119 hours and 41 minutes
WARNING  2023-07-21 19:18:24,882 [wine.create_prefix:149]:Wine prefix creation is taking longer than expected...
ERROR    2023-07-21 19:26:14,647 [wine.create_prefix:151]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2023-07-21 19:26:14,648 [registry.__init__:85]:No registry file at ~/.wine_lol/user.reg
ERROR    2023-07-21 19:26:14,648 [jobs.target:36]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7fe9786fb3d0>>: <class 'OSError'> Invalid Wine prefix path ~/.wine_lol, make sure to create the prefix before saving to a registry
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 929, in prelaunch
    self.set_regedit_keys()
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 883, in set_regedit_keys
    prefix_manager.clear_registry_subkeys(path, key)
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/prefix.py", line 132, in clear_registry_subkeys
    registry.save()
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/registry.py", line 157, in save
    raise OSError(
ERROR    2023-07-21 19:26:14,650 [exceptions.wrapper:95]:tft (wine) has encountered an error: Invalid Wine prefix path ~/.wine_lol, make sure to create the prefix before saving to a registry
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 693, in configure_game
    raise error
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 929, in prelaunch
    self.set_regedit_keys()
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 883, in set_regedit_keys
    prefix_manager.clear_registry_subkeys(path, key)
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/prefix.py", line 132, in clear_registry_subkeys
    registry.save()
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/registry.py", line 157, in save
    raise OSError(
OSError: Invalid Wine prefix path ~/.wine_lol, make sure to create the prefix before saving to a registry
```

### System Information

```shell
[System]
OS:              Nobara Linux 38 Thirty Eight
Arch:            x86_64
Kernel:          6.3.12-204.fsync.fc38.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600G with Radeon Graphics
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.2 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.52, 6.3.12-204.fsync.fc38.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.3
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.3
Vulkan Version:  1.3.240
Vulkan Drivers:  AMD Radeon RX 6600 (RADV NAVI23) (1.3.255)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I wish I knew what versions of Lutris 'lutris-0.5.13-9.git.fc38.x86_64' and 'lutris-0.5.l13-8.git.fc38.x86_64' are.

What I'm seeing is that it's trying to use the prefix '~/.wine_lol', and I don't think that can work- it does not have any code to expand the ~ thing to your home directory, so that's just a bogus path to it.

But Lutris is supposed to auto-expand these guys when you enter them in the configuration dialog; so you should be getting the full path with no ~.

Please check the configuration of your game; is the prefix really set to '~/.wine_lol'? Or if not, does the game path itself start with ~?

**Comment by Imecth** [comment]
The path in my settings is complete /home/imecth/.wine, this issue is also present with other runners and prefixes
When moving the wine_prefix to a public path (no .)  i get instead
> "[Errno 17] File exists: '/home/imecth/wine_lol/drive_c/users/imecth' -> '/home/imecth/wine_lol/drive_c/users/steamuser'

**Comment by danieljohnson2** [comment]
I don't think the '.' is an issue; that file exists is odd but I do not understand what you actually did to get it. Maybe it does exist, who knows!

But... I guess your game config did have '~/.wine_lol' and the UI expanded it, so you didn't see it. Changing it and then changing it back saved it as '/home/imecht/.wine_lol', and that's what it needs to be, so now it works.

The question is how it came to be '~/.wine_lol' ever; the auto-expand in the UI feature has been here longer than I have.

May I ask if you recall how you installed the game in the first place? There may still be a bug here.

**Comment by Imecth** [comment]
Manually, they're prefixes i created in the last year or so. It doesn't explain why updating git lutris suddenly causes problems.
Apparently i'm allowed to parse  ~/.wine_lol into the prefix and lutris doesn't correct it. Nor does the ui update afterwards.

**Comment by danieljohnson2** [comment]
It is mysterious, indeed. It'd help to know which commit broke it, but I don't think anyone can bisect this now that it's working again.

**Comment by Imecth** [comment]
Editing the .yml launcher manually with ~/path/to/prefix recreates the identical bug

**Comment by danieljohnson2** [comment]
Hmm. I can't get this to repro for me.

But that commit removed code to fall back to a default prefix (~/.wine); I'd guess that your bogus prefix tripped that code, and you were running in that prefix.

I think that explains most of it- the only question is how you came to have ~ in there in the first place. Just editing the YAML directly is cheating.

**Comment by Liorst4** [comment]
This happened to me as well.
In the configure dialog in the UI, the path didn't have the `~`, it was expanded.
I manually edited the `yaml`s to remove the `~` and replace the wine prefix with a full path.
I have no idea how the `~` got there in the first place.

I'm using the flatpak version on a steam deck, at first I though it has something to do with flatpak's sandboxing shenanigans, but I see that it can also happen for the non flatpak version.

**Comment by danieljohnson2** [comment]
We've got a "fix", which is to expand this ~ when we encounter them. Still wish I knew where they came from though.
