### ISSUE TITLE
FlatPak runner does not work

### ISSUE THREAD

**Issue by 6XGate** [lutris/lutris#4952]
### Bug description

Any attempt to use the flatpak app runner produces a simple modal with the text 'install_type'. Running from the console produces the following error:
```
2023-07-26 19:04:05,128: Runtime disabled by system configuration
2023-07-26 19:04:05,165: CaveStory (flatpak) has encountered an error: 'install_type'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 602, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 585, in get_gameplay_info
    gameplay_info["working_dir"] = self.runner.working_dir
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 188, in working_dir
    return self.game_path or os.path.expanduser("~/")
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/flatpak.py", line 112, in game_path
    install_type, application, arch, branch = (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/flatpak.py", line 113, in <genexpr>
    self.game_config[key] for key in ("install_type", "appid", "arch", "branch")
    ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'install_type'
```

### How to Reproduce

1. Install a game from FlatHub such as _CaveStory NS_.
2. Add the came to Lutris with _+_ button, _Add locally installed game_.
2. Select the _Flatpak (Runs Flatpak applications)_ **Runner**.
3. Enter the title, release year on the **Game info** tab.
4. In the **Game options**, enter the **Application ID**, for example, _CaveStory NX_ is `com.gitlab.coringao.cavestory-nx`.
5. **Save** the game info and double-click the game's entry.

### Expected behavior

CaveStory NX would launch without any error, complaint, or drama.

### Log output

No log text shows in the log **Show logs** modal in the UI, the console outputs the following:

```shell
INFO     2023-07-26 19:08:43,714 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-26 19:08:43,715 [startup.check_driver:65]:Using NVIDIA drivers 535.54.03 for x86_64
INFO     2023-07-26 19:08:43,715 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 2080 Ti
INFO     2023-07-26 19:08:43,715 [startup.check_driver:85]:GPU: 10DE:1E07 10DE:12A4 (nvidia drivers)
DEBUG    2023-07-26 19:08:43,875 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-07-26 19:08:53,047 [application.show_window:339]:Showing window RunnerConfigDialogflatpak
DEBUG    2023-07-26 19:08:54,889 [application.on_app_window_destroyed:357]:Removed window RunnerConfigDialogflatpak
DEBUG    2023-07-26 19:09:00,078 [application.show_window:339]:Showing window PreferencesDialog{}
DEBUG    2023-07-26 19:09:09,747 [application.on_app_window_destroyed:357]:Removed window PreferencesDialog{}
INFO     2023-07-26 19:09:17,106 [runner.use_runtime:440]:Runtime disabled by system configuration
ERROR    2023-07-26 19:09:17,155 [exceptions.wrapper:95]:CaveStory (flatpak) has encountered an error: 'install_type'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 602, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 585, in get_gameplay_info
    gameplay_info["working_dir"] = self.runner.working_dir
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 188, in working_dir
    return self.game_path or os.path.expanduser("~/")
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/flatpak.py", line 112, in game_path
    install_type, application, arch, branch = (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/flatpak.py", line 113, in <genexpr>
    self.game_config[key] for key in ("install_type", "appid", "arch", "branch")
    ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'install_type'
DEBUG    2023-07-26 19:09:17,156 [application.on_game_stop:679]:Removing 1 from running IDs
```
```


### System Information

```shell
[System]
OS:              Manjaro Linux 23.0.0 Uranos
Arch:            x86_64
Kernel:          6.1.38-1-MANJARO
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            0.5 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.255
Vulkan Drivers:  NVIDIA GeForce RTX 2080 Ti (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Hmm. It looks to me like the Flatpak runner really needs you to fill in all that stuff that's on the Game Options tab. It's crashing because the Install Type is blank.

The UI here could be better, but for now I've put better error message in for this case.

**Comment by 6XGate** [comment]
I do now see an Install Type field in the modal. Where is it?

**Comment by danieljohnson2** [comment]
I think you should see this:
![image](https://github.com/lutris/lutris/assets/6507403/857a0cd3-a4e5-485c-bc37-2cc07db560a3)

In 0.5.13.

**Comment by 6XGate** [comment]
I have 0.5.13, but all I have is this:
![image](https://github.com/lutris/lutris/assets/5586463/f0345260-9578-4778-9a8b-b06f1e9f6e0a)
![image](https://github.com/lutris/lutris/assets/5586463/59e89a73-3e71-48cf-a985-52625d1abb35)

**Comment by danieljohnson2** [comment]
That does not seem right. Can you run 'lutris -d', visit that UI, and give us the terminal output?

I think you are having some kind of error during the page initialization, and I'm hoping it will turn up in the output.

**Comment by 6XGate** [comment]
Here is the console output:
```
INFO     2023-07-29 16:38:09,862 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-29 16:38:09,864 [startup.check_driver:65]:Using NVIDIA drivers 535.86.05 for x86_64
INFO     2023-07-29 16:38:09,864 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 2080 Ti
INFO     2023-07-29 16:38:09,864 [startup.check_driver:85]:GPU: 10DE:1E07 10DE:12A4 (nvidia drivers)
DEBUG    2023-07-29 16:38:10,041 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-07-29 16:38:42,140 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-07-29 16:38:44,007 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}
INFO     2023-07-29 16:38:49,630 [common._switch_runner:500]:Creating new configuration with runner flatpak
WARNING  2023-07-29 16:38:50,406 [runner.game_config:141]:Accessing game config while runner wasn't given one.
ERROR    2023-07-29 16:38:50,410 [boxes.generate_widgets:184]:Failed to generate option widget for 'working_dir': 'install_type'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 117, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 282, in call_widget_generator
    self.generate_directory_chooser(option, value)
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 474, in generate_directory_chooser
    default_path = self.game.runner.working_dir
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 188, in working_dir
    return self.game_path or os.path.expanduser("~/")
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/flatpak.py", line 112, in game_path
    install_type, application, arch, branch = (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/flatpak.py", line 113, in <genexpr>
    self.game_config[key] for key in ("install_type", "appid", "arch", "branch")
    ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'install_type'
WARNING  2023-07-29 16:39:12,045 [common.on_save:558]:Current configuration is not valid, ignoring save request
DEBUG    2023-07-29 16:39:20,540 [game.save:423]:Saving Cave Story (flatpak) with config ID cave-story-1690666760
DEBUG    2023-07-29 16:39:20,540 [config.save:229]:Saving LutrisConfig(level=game, game_config_id=cave-story-1690666760, runner=flatpak) config to ~/.config/lutris/games/cave-story-1690666760.yml
ERROR    2023-07-29 16:39:20,541 [game.id:195]:The game 'Cave Story' has no ID, it is not stored in the PGA.
DEBUG    2023-07-29 16:39:20,576 [lutris.add_to_path_cache:158]:Adding Cave Story (flatpak) to path cache
WARNING  2023-07-29 16:39:20,577 [lutris.get_path_from_config:126]:No path found in LutrisConfig(level=game, game_config_id=cave-story-1690666760, runner=flatpak)
WARNING  2023-07-29 16:39:20,577 [lutris.add_to_path_cache:161]:No path for Cave Story (flatpak)
INFO     2023-07-29 16:40:19,408 [application.do_shutdown:960]:Shutting down Lutris
```

Here is a video:
[Screencast from 2023-07-29 16-38-39.webm](https://github.com/lutris/lutris/assets/5586463/f12dd1e8-fc70-4041-9fb4-2086580c7213)

**Comment by strycore** [comment]
Different Flatpak versions support different fields. Pretty sure that's what happening here.

**Comment by 6XGate** [comment]
Okay, I just found out something. After enabling Advanced, it requires starting over (for adding the game) to make the new fields appear. It seems the _Game options_ page don't update with that switch.
![image](https://github.com/lutris/lutris/assets/5586463/a8b1b018-e900-48c5-a9df-dd0622660b4f)

Also, I'm running Flatpak 1.15.4 (didn't realize Manjaro was running a version flatpak still calls pre-release in github).

**Comment by danieljohnson2** [comment]
Right, there's a bug in the advanced switch so that it won't update the game options if there's no game object yet. I'll fix that.
