### ISSUE TITLE
Installer finishes successfully, but deletes the game again

### ISSUE THREAD

**Issue by Curunir** [lutris/lutris#4974]
### Bug description

I have installed the GOG version of Huniepop 2 - Double Date twice now, once on a current Nobara Linux, and once on a current Manjaro Linux. It worked flawlessly on Nobara, but on Manjaro, I had the following issue: Installer finishes and starts the game, but when the (100% working) game is quit again, Lutris apparently thinks it failed due to some non-breaking bug. Then, without any other option except "Abort", Lutris effectively force-removes the already working game.
I suppose this is caused by the line "Source does not exist: 91238" in the log below, but the real issue here is that we need some kind of "ignore this error and finish" button, so the successful installation is not deleted.

### How to Reproduce

Install Lutris in a fresh Manjaro install (I used the unofficial Cinnamon edition). Install the GOG version of HuniePop 2, launch the game after installation, quit it again.

### Expected behavior

Recognise the successful installation; alternatively, offer to keep the installation and not force-remove it.

### Log output

```shell
INFO     2023-08-11 12:36:21,252 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-08-11 12:36:21,253 [startup.check_driver:73]:Running AMD Mesa driver 23.0.4 on AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.7, DRM 3.52, 6.4.6-1-MANJARO) (0x15d8)
INFO     2023-08-11 12:36:21,253 [startup.check_driver:85]:GPU: 1002:15D8 1002:15D8 (amdgpu drivers)
DEBUG    2023-08-11 12:36:21,390 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-11 12:36:21,457 [lutris.get_missing_game_ids:191]:Checking for missing games
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 68, in _new_for_bus_cb
    proxy = obj.new_for_bus_finish(result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Fehler beim Aufruf von StartServiceByName für org.freedesktop.portal.Desktop: Zeitüberschreitung wurde erreicht (24)
DEBUG    2023-08-11 12:36:48,910 [application.show_window:339]:Showing window PreferencesDialog{}
DEBUG    2023-08-11 12:36:57,488 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-11 12:36:57,502 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-11 12:36:57,534 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-11 12:36:57,541 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-11 12:36:57,548 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-11 12:37:10,475 [application.on_app_window_destroyed:357]:Removed window PreferencesDialog{}
DEBUG    2023-08-11 12:38:15,368 [services.get_game:17]:Getting service game 1455877361 for gog
DEBUG    2023-08-11 12:38:16,675 [services.get_game:17]:Getting service game 1455877361 for gog
DEBUG    2023-08-11 12:38:16,675 [base.install:263]:Installing 1455877361 from service gog
DEBUG    2023-08-11 12:38:16,676 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2023-08-11 12:38:16,814 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/huniepop-2-double-date
DEBUG    2023-08-11 12:38:16,815 [http._request:88]:GET https://lutris.net/api/installers/huniepop-2-double-date
DEBUG    2023-08-11 12:38:17,042 [application.show_window:339]:Showing window InstallerWindow1455877361
DEBUG    2023-08-11 12:38:19,364 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-11 12:38:21,413 [interpreter.get_runners_to_install:264]:Default wine version is system
DEBUG    2023-08-11 12:38:21,425 [gog.get_extras:320]:Download extras for GOG ID 1455877361 and its DLCs
INFO     2023-08-11 12:38:21,425 [gog.get_game_details:286]:Getting game details for 1455877361
DEBUG    2023-08-11 12:38:21,426 [http._request:88]:GET https://api.gog.com/products/1455877361?expand=downloads&locale=de-DE
INFO     2023-08-11 12:38:21,607 [gog.get_game_details:286]:Getting game details for 1455877361
DEBUG    2023-08-11 12:38:21,608 [http._request:88]:GET https://api.gog.com/products/1455877361?expand=downloads&locale=de-DE
DEBUG    2023-08-11 12:38:21,666 [http._request:88]:GET https://api.gog.com/products?ids=1366600472%2C1951514936&expand=downloads
DEBUG    2023-08-11 12:38:23,928 [http._request:88]:GET https://embed.gog.com/userData.json
INFO     2023-08-11 12:38:24,181 [installer.prepare_game_files:175]:Getting files for install
INFO     2023-08-11 12:38:24,181 [installer.prepare_game_files:177]:Adding selected extras to downloads
INFO     2023-08-11 12:38:24,181 [gog.get_game_details:286]:Getting game details for 1455877361
DEBUG    2023-08-11 12:38:24,183 [http._request:88]:GET https://api.gog.com/products/1455877361?expand=downloads&locale=de-DE
INFO     2023-08-11 12:38:24,261 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1455877361/downlink/installer/en1installer0
DEBUG    2023-08-11 12:38:24,262 [http._request:88]:GET https://api.gog.com/products/1455877361/downlink/installer/en1installer0
DEBUG    2023-08-11 12:38:25,607 [downloader.start:67]:⬇ https://content-system.gog.com/products/1455877361/users/46987554972193878/namespaces/website/download?path=%2Fsecure%2Foffline%2F1455877361%2F1455877361%2F55898712513408984%2F4110%2Fsetup_huniepop_2_double_date_1.1.0a_%2864bit%29_%2859528%29.exe&token=eyJhbGciOiJIUzI1NiIsImV4cCI6IjE2OTE4NTA4NDQifQ.eyJjb250ZW50Ijoie1widXNlcl9pZFwiOjQ2OTg3NTU0OTcyMTkzODc4LFwicHJvZHVjdF9pZFwiOjE0NTU4NzczNjEsXCJwYXRoXCI6XCJcXFwvc2VjdXJlXFxcL29mZmxpbmVcXFwvMTQ1NTg3NzM2MVxcXC8xNDU1ODc3MzYxXFxcLzU1ODk4NzEyNTEzNDA4OTg0XFxcLzQxMTBcXFwvc2V0dXBfaHVuaWVwb3BfMl9kb3VibGVfZGF0ZV8xLjEuMGFfKDY0Yml0KV8oNTk1MjgpLmV4ZVwifSIsImV4cCI6IjE2OTE4NTA4NDQifQ.IZGVWGKnncD_qH--ztNG2futRz6HS7IXNyGXUAbLZOc&access_token=VJLJmRM6t3PH3BLht6Otzqe0IuUMGkn0ABlJAC8X2QqozunShkRDxNSHGYgoegk2Vztl26oyvPZdpehklk7pFycKScahJKIeoBldp9e9hvKA7WGrJO94IwGgr8RrJD1Xv5ubSrosKrKu60RIvaq1Iw
DEBUG    2023-08-11 12:38:51,090 [downloader.on_download_completed:170]:Finished downloading https://content-system.gog.com/products/1455877361/users/46987554972193878/namespaces/website/download?path=%2Fsecure%2Foffline%2F1455877361%2F1455877361%2F55898712513408984%2F4110%2Fsetup_huniepop_2_double_date_1.1.0a_%2864bit%29_%2859528%29.exe&token=eyJhbGciOiJIUzI1NiIsImV4cCI6IjE2OTE4NTA4NDQifQ.eyJjb250ZW50Ijoie1widXNlcl9pZFwiOjQ2OTg3NTU0OTcyMTkzODc4LFwicHJvZHVjdF9pZFwiOjE0NTU4NzczNjEsXCJwYXRoXCI6XCJcXFwvc2VjdXJlXFxcL29mZmxpbmVcXFwvMTQ1NTg3NzM2MVxcXC8xNDU1ODc3MzYxXFxcLzU1ODk4NzEyNTEzNDA4OTg0XFxcLzQxMTBcXFwvc2V0dXBfaHVuaWVwb3BfMl9kb3VibGVfZGF0ZV8xLjEuMGFfKDY0Yml0KV8oNTk1MjgpLmV4ZVwifSIsImV4cCI6IjE2OTE4NTA4NDQifQ.IZGVWGKnncD_qH--ztNG2futRz6HS7IXNyGXUAbLZOc&access_token=VJLJmRM6t3PH3BLht6Otzqe0IuUMGkn0ABlJAC8X2QqozunShkRDxNSHGYgoegk2Vztl26oyvPZdpehklk7pFycKScahJKIeoBldp9e9hvKA7WGrJO94IwGgr8RrJD1Xv5ubSrosKrKu60RIvaq1Iw
INFO     2023-08-11 12:38:51,135 [file_box.on_download_complete:239]:Download completed
DEBUG    2023-08-11 12:38:51,135 [files_box.on_file_available:108]:install is available
INFO     2023-08-11 12:38:51,135 [files_box.on_file_available:114]:All files available
INFO     2023-08-11 12:38:51,135 [installerwindow.on_files_available:635]:All files are available, continuing install
DEBUG    2023-08-11 12:38:51,136 [interpreter._iter_commands:361]:Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2023-08-11 12:38:51,137 [wine.create_prefix:98]:Creating a win64 prefix in /home/playtest/Games/gog/huniepop-2-double-date
ERROR    2023-08-11 12:38:51,138 [wine.create_prefix:121]:No wineboot executable found in wine, your wine installation is most likely broken
DEBUG    2023-08-11 12:38:51,138 [interpreter._iter_commands:361]:Installer command: {'task': {'executable': 'install', 'name': 'wineexec', 'prefix': '$GAMEDIR'}}
INFO     2023-08-11 12:38:51,186 [wine.use_lutris_runtime:126]:Using system wine version, not using runtime
ERROR    2023-08-11 12:38:51,211 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2023-08-11 12:38:51,211 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/playtest/.cache/lutris/shaders/wine"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:LD_LIBRARY_PATH="/usr/lib:/usr/lib64:/usr/lib:/usr/lib32:/usr/lib/libstrangle:/usr/lib32/libstrangle:/usr/lib/libfakeroot:/usr/lib64:/home/playtest/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/playtest/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/playtest/.local/share/lutris/runtime/steam/i386/lib:/home/playtest/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/playtest/.local/share/lutris/runtime/steam/i386/usr/lib:/home/playtest/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/playtest/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/playtest/.local/share/lutris/runtime/steam/amd64/lib:/home/playtest/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/playtest/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINEARCH="win64"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINE="wine"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINE_MONO_CACHE_DIR="/home/playtest/.local/share/lutris/runners/wine/system/mono"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/playtest/.local/share/lutris/runners/wine/system/gecko"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINEPREFIX="/home/playtest/Games/gog/huniepop-2-double-date"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINEESYNC="1"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-08-11 12:38:51,219 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-08-11 12:38:51,220 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-08-11 12:38:51,220 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/playtest/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-08-11 12:38:51,220 [command.start:141]:PROTON_EAC_RUNTIME="/home/playtest/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-08-11 12:38:51,220 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d12core,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-08-11 12:38:51,220 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages"
DEBUG    2023-08-11 12:38:51,220 [command.start:141]:LUTRIS_GAME_UUID="d9dbc06d-d77e-4700-8e2d-7d2f195d8e04"
Started initial process 15795 from wine /home/playtest/.cache/lutris/installer/huniepop-2-double-date/gog/setup_huniepop_2_double_date_1.1.0a_(64bit)_(59528).exe
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2023-08-11 12:39:29,270 [command.on_stop:195]:Process 15793 has terminated with code 0
DEBUG    2023-08-11 12:39:30,244 [commands._monitor_task:444]:Return code: 0
DEBUG    2023-08-11 12:39:30,244 [interpreter._iter_commands:361]:Installer command: {'copy': {'src': '91238', 'dst': '$GAMEDIR/extras'}}
DEBUG    2023-08-11 12:39:30,245 [commands.merge:268]:Merging 91238 into /home/playtest/Games/gog/huniepop-2-double-date/extras
ERROR    2023-08-11 12:39:30,245 [errors.__init__:18]:Quelle existiert nicht: 91238
{'src': '91238', 'dst': '$GAMEDIR/extras'}
ERROR    2023-08-11 12:39:30,245 [jobs.target:36]:Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x7fde1a9c3240>: <class 'lutris.installer.errors.ScriptingError'> Quelle existiert nicht: 91238
{'src': '91238', 'dst': '$GAMEDIR/extras'}
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 371, in dispatch
    return method(params)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 288, in copy
    self.merge(params)
  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 273, in merge
    raise ScriptingError(_("Source does not exist: %s") % src, params)
ERROR    2023-08-11 12:39:30,246 [interpreter._iter_commands:346]:Last install command failed, show error
```

### System Information

```shell
[System]
OS:              Manjaro Linux 23.0.0 Uranos
Arch:            x86_64
Kernel:          6.4.6-1-MANJARO
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3400G with Radeon Vega Graphics
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             13.6 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.7, DRM 3.52, 6.4.6-1-MANJARO)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.4
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.4
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.4
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon Vega 11 Graphics (RADV RAVEN) (1.3.238)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Hmm. Are you using the GOG installer from Lutris, or the automatic GOG install - "GOG (auto generated)"- you can get that from the GOG source view.

If you have not tried the auto version, try it. I find that that tends to work better, for me.

**Comment by strycore** [comment]
>  I suppose this is caused by the line "Source does not exist: 91238" in the log below, but the real issue here is that we need some kind of "ignore this error and finish" button, so the successful installation is not deleted.

No, we can't just ignore errors without creating an abomination of a piece of software that will unanimously be rejected by humanity and our descendants for the generations to come.  

We can, however, fix the bug you're facing.

**Comment by strycore** [comment]
This is related to GOG Extra downloads. Not the game itself.

**Comment by IIIphr** [comment]
> This is related to GOG Extra downloads. Not the game itself.

I tried installing legend of keeper with extras, got "lutris source does not exist: 84907"
Tired installing it without the extras, installed the game without errors. 
So probably yeah, it's something with extras.

**Comment by Darren-Penner** [comment]
I have been able to replicate this with Baldur's Gate 3 on Ubuntu 22.04 and Lutris 0.5.14.

When trying to include the GOG extras I got the same screen with only abort as an option and this in the logs.

Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2024-01-01 16:25:18,415 [command.on_stop:195]:Process 708297 has terminated with code 0
DEBUG    2024-01-01 16:25:18,902 [commands._monitor_task:448]:Return code: 0
DEBUG    2024-01-01 16:25:18,902 [interpreter._iter_commands:349]:Installer command: {'copy': {'src': '95459', 'dst': '$GAMEDIR/extras'}}
DEBUG    2024-01-01 16:25:18,921 [commands.merge:272]:Merging 95459 into /home/darren/Games/gog/baldurs-gate-3/extras
ERROR    2024-01-01 16:25:18,921 [errors.__init__:18]:Source does not exist: 95459
{'src': '95459', 'dst': '$GAMEDIR/extras'}
ERROR    2024-01-01 16:25:18,921 [jobs.target:33]:Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x7f737bfbf7f0>: <class 'lutris.installer.errors.ScriptingError'> Source does not exist: 95459
{'src': '95459', 'dst': '$GAMEDIR/extras'}
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 31, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 359, in dispatch
    return method(params)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 292, in copy
    self.merge(params)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 277, in merge
    raise ScriptingError(_("Source does not exist: %s") % src, params)
ERROR    2024-01-01 16:25:18,923 [interpreter._iter_commands:334]:Last install command failed, show error


Once I removed the extras the game installed successfully.

**Comment by danieljohnson2** [comment]
I think I see it, but it's hard to be sure; this is pretty spread out.

It generates that list of extras, and assumes that each of those corresponds to just one file each. It can actually be more or fewer files than that- it's up to the service, it gives us what it gives us.

So, I've reworked this so the download list (that you see the download progress bars in) drives this, and whatever files we download are the ones we copy to the $GAMEDIR/extras directory. This applies to GOG and itchio- as far as I can see no other service gets extras like this.

So, @Curunir or @Darren-Penner, if you could test this for me? Download the latest master and run the bin/lutris script within, no need to install it.

Install a game with this issue. Include the extras. Does it work? Do you get your extras? Are any missing?

**Comment by danieljohnson2** [comment]
Hmm. Looks like I can repro this with "War for the Overworld"; master doesn't crash but does not download the DLC goodies. Better but not ideal.

**Comment by strycore** [comment]
Unless you find a quick fix for this, I think it's OK to postpone this for the next release.

**Comment by danieljohnson2** [comment]
It appears to me we need to separately request the download links for the DLC extras- they don't seem to be in the JSON we get. Does not look that quick, but I will be looking into it.

**Comment by danieljohnson2** [comment]
Had to do some more work here; Lutris has been showing extras to GOG users that they do not own; that will never work. I think I have this fixed, and you should see only what you are allowed to install, and you should be able to install it.
