### ISSUE TITLE
ImportError: cannot import name 'MutableMapping' from 'collections'

### ISSUE THREAD

**Issue by Jacobw1oo** [lutris/lutris#4977]
ImportError: cannot import name 'MutableMapping' from 'collections'

In Python 3.11.3 'MutableMapping' was removed from collections 

it is in collections.abc with this command below, it works
from collections.abc import MutableMapping

I am on Arch linux (x86_64), the most recent update broke Lutris.

**Comment by danieljohnson2** [comment]
You are going to have to give us more than that. The Lutris source has no mentions of 'MutableMapping' at all, so whatever's going on it's not as simple as 'Python 3.11.3 breaking change'.

Maybe post your debug log. Run this:
```
lutris -d
```
And post the terminal spam you get.

**Comment by Jacobw1oo** [comment]
   ~  lutris -d                                                                                           ✔ 
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.api import parse_installer_url, get_runners
  File "/usr/lib/python3.11/site-packages/lutris/api.py", line 11, in <module>
    import requests
  File "/home/jacobw1ooo/.local/lib/python3.11/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/jacobw1ooo/.local/lib/python3.11/site-packages/requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/jacobw1ooo/.local/lib/python3.11/site-packages/requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "/home/jacobw1ooo/.local/lib/python3.11/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/jacobw1ooo/.local/lib/python3.11/site-packages/requests/packages/urllib3/__init__.py", line 24, in <module>
    from .poolmanager import PoolManager, ProxyManager, proxy_from_url
  File "/home/jacobw1ooo/.local/lib/python3.11/site-packages/requests/packages/urllib3/poolmanager.py", line 14, in <module>
    from ._collections import RecentlyUsedContainer
  File "/home/jacobw1ooo/.local/lib/python3.11/site-packages/requests/packages/urllib3/_collections.py", line 7, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

**Comment by danieljohnson2** [comment]
It's blowing up inside of urllib3, which is part of Python 3, not Lutris.

This suggests to me that you have some kind of screwed up Python install. Maybe you have different versions of Python installed system-wide and also locally? That can cause problems like this when different version of packages get mixed together.

**Comment by strycore** [comment]
Any error coming from Python packages installed in `~/.local/lib/python3.xx` can be immediately closed.

**Comment by strycore** [comment]
@Jacobw1oo you can fix your problem by running : `rm -rf ~/.local/lib/python*`
