### ISSUE TITLE
Advanced (visibility) button no longer works correctly

### ISSUE THREAD

**Issue by Astrobald** [lutris/lutris#4992]
It seems that the "advanced visibility" button in the the game configuration window of Lutris no longer works correctly, since commit 7b115a0.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/common.py", line 478, in <lambda>
    switch.connect("state_set", lambda _w, s: self.on_show_advanced_options_toggled(bool(s)))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/common.py", line 503, in on_show_advanced_options_toggled
    self._set_advanced_options_visible(is_active)
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/common.py", line 507, in _set_advanced_options_visible
    self.system_box.set_advanced_visibility(value)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SystemBox' object has no attribute 'set_advanced_visibility'. Did you mean: '_advanced_visibility'?
```
However, saving the game configuration enforces the function.

**Comment by danieljohnson2** [comment]
I blame Git for somehow botching the merger. I swear I tested that thing.

Anyway, I've updated the call site so the switch should work again.
