### ISSUE TITLE
Importance of watcher.py ?

### ISSUE THREAD

**Issue by capecrusader-121** [lutris/lutris#4994]
Hey there Snap Maintainer here, lutris snap is getting ready at a good pace, but there are some roadblocker especially --> https://github.com/lutris/lutris/blob/master/lutris/util/process_watcher.py as this file makes lutris access '@{PROC}/@{pid}/task/5312/children' and '@{PROC}/@{pid}/task/[0-9]*/children' which isnt permitted in snap sandbox even if connected with the process plug, the snappy-debug tool spits out the following error ;
```
= AppArmor =
Time: Aug 21 19:04:26
Log: apparmor="DENIED" operation="open" class="file" profile="snap.lutris.lutris" name="/proc/5312/task/5312/children" pid=5312 comm="lutris-wrapper:" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
File: /proc/5312/task/5312/children (read)
Suggestions:
* adjust program to not access '@{PROC}/@{pid}/task/5312/children'
* adjust program to not access '@{PROC}/@{pid}/task/[0-9]*/children'
```

So i want to ask if this file is actually needed for the app ? and if possible can this be removed ?

**Comment by danieljohnson2** [comment]
Well, 'watcher.py' seems unused entirely so that one would be easy. But 'process_watcher.py' is used; it's used to wait for a game to start, and then to exit again. I think we need it.

I think the offending code is actually in process.py; not sure why you are lighting up on process_watcher.py in particular.

I don't know what we could be doing here that would be snap compatible. This code is iterating over the process's threads and child processes, and it seems necessary to do this.

In another place we extract the environment of the processes, and we could probably avoid doing that by running a degraded mode. But I'm not sure we should- that code is trying to protect us from the 'Stop button kills every process in your session' bug that was so much fun. Would snap ensure we can't do more than kill Lutris even we went berserk?

**Comment by capecrusader-121** [comment]
@danieljohnson2  I believe you are correct i may have misinterpreted few things, due to the fact that on firing scummvm inside lutris snap it gives the following error, with watcher.py also in the view.
```
Traceback (most recent call last):
  File "/snap/lutris/180/usr/share/lutris/bin/lutris-wrapper", line 202, in <module>
    main()
  File "/snap/lutris/180/usr/share/lutris/bin/lutris-wrapper", line 167, in main
    if not watcher.is_alive():
  File "/snap/lutris/180/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 75, in is_alive
    return next(self.iterate_processes(), None) is not None
  File "/snap/lutris/180/usr/lib/python3/dist-packages/lutris/util/process_watcher.py", line 64, in iterate_processes
    for child in self.iterate_children():
  File "/snap/lutris/180/usr/lib/python3/dist-packages/lutris/util/process.py", line 131, in iter_children
    for child in self.children:
  File "/snap/lutris/180/usr/lib/python3/dist-packages/lutris/util/process.py", line 125, in children
    for child_pid in self.get_children_pids_of_thread(tid):
  File "/snap/lutris/180/usr/lib/python3/dist-packages/lutris/util/process.py", line 71, in get_children_pids_of_thread
    with open(children_path, encoding='utf-8') as children_file:
PermissionError: [Errno 13] Permission denied: '/proc/6841/task/6841/children'
```

Also the process-control  plug isn't the correct instead it should be the system observe one--> https://snapcraft.io/docs/system-observe-interface, i think instead of removing if this can be adjusted to the snap sandbox especially the system-observe plug can be a better solution.
I tried giving the system observe but thats also not sufficient for lutris.

**Comment by danieljohnson2** [comment]
Yes, it's the one at the bottom that is the issue here, not the top one.

I'm afraid that link you have given me tells me almost nothing; I've no idea what would be involved in using this 'interface'.

Maybe we need someone who understands how to use this.

**Comment by strycore** [comment]
Yes, process_watcher is heavily used in how Lutris works.  
There is however a possible solution. We use 2 different mechanisms to track processes. 1st one is tracking the children of the lutris-wrapper process. 2nd one is setting a LUTRIS_GAME_UUID and looking up which processes match this UUID. This was implemented because some Wine processes have PID 1 as their parent.

Maybe we can add an error handler to ignore the fact that we're not able to read children processes and depend entirely on LUTRIS_GAME_UUID. This is quite risky since it would make tracking processes different from the normal Lutris.

Is it '/proc/PID/task/PID/children' that is forbidden or is it the whole /proc folder? If the proc folder is off limits then the LUTRIS_GAME_UUID won't work either.

As a general rule, you'll find out that the environment Lutris runs in needs to be very permissive, since it is an application launcher.

Another solution to explore and this is what I want to explore with Flatpak as well: games are launched in another container, not the same one as the Lutris GUI. We're currently adding Flatpak support for most runners. Let's say for example someone launches a game with the MAME Flatpak. The idea would be to only track the running status of that particular Flatpak while completely ignoring the processes spawned by Lutris or lutris-wrapper. For Wine, we would need to package it in its own Flatpak and for Linux native games, we will need to create a set of Flatpak runtimes that are specifically tailored to run different types of Linux games (32bit, 64bit, SDL1, etc...). The exact same methodology could be applied for Snaps. This implies to add permissions for Lutris to manage Snaps (to install and run them).

This will make the Lutris snap a lot lighter because it will only need the GTK components to run the UI and not every single library that could possibly be used in a game.

I'm going to be talking about this at the Ubuntu Summit in November so I'd really like to experiment on the feasibility of this feature in the coming weeks.

**Comment by capecrusader-121** [comment]
@strycore  What you wish for is using https://snapcraft.io/docs/desktop-launch-interface which is super privileged and usually not even provided to canonical snaps, the only feasible way is to use xdg-open within a snap sandbox although i cant vouch for their response on it if its sought by the upstream of any app.

For experiment, scummvm/steam snap is available, can something be done for it, i mean lutris at the end becomes a central point for launching other VMs/Apps used for gaming ?

Also regarding the system observe plug, its a quiet strong plug i mean it can successfully run system monitor apps but lutris wants access to something even beyond it ?, it should be the last plug for reading system activities & processes . I am trying to scrape snapd source code to find its limit.

**Comment by strycore** [comment]
Desktop-launch-interface is exactly what is needed. It's not important whether this is used by Canonical Snaps or not. This kind of API is made specifically for apps like Lutris that act as process launchers. I have received similar warnings regarding the Flatpak Talk API. Turns out it was a bunch of nonsense and I've merged in the Flatpak Talk API support in Lutris without asking for anyone's opinion, permitting the project to move forward.

You can try testing with the ScummVM snap but I would highly recommend not using Steam for testing. Steam is a special case because we don't actually care about the running status of the Steam client, only about the status of games launched by Steam.
"i mean lutris at the end becomes a central point for launching other VMs/Apps used for gaming ?" that's always been the goal of Lutris. But the current architecture using a runtime folder and maintaining builds of all runners is kinda outdated and not future proof. Shoving every runner along with every single library that could be used by a Linux native game isn't really a viable solution. It creates a huge app and becomes a maintenance nightmare. 

We should take advantage of the containerization offered by Snap and Flatpak and make Lutris better thanks to those technologies rather than creating constraints.

If we stick to reading the contents of /proc, will that be compatible with runners launched via a Snap or a Flatpak? I feel like accessing /proc is somewhat hackish and migrating to something entirely based on Snaps / Flatpaks would be way cleaner. Obviously, the /proc method should stick around as long as we also support non containerized solutions.

**Comment by danieljohnson2** [comment]
I certainly hope non-containerized solutions remain available.

**Comment by strycore** [comment]
While we're probably not going to force a Snap or Flatpak dependency on Lutris, it's likely that we'll adopt some kind of containerization with bwrap sometime in the future. This is what Steam does.

**Comment by danieljohnson2** [comment]
I'm concerned with compatibility for Linux and Wine games, which are not in a VM and are not isolated; I'd expect to have compatibility problems with *any* containerization. If you want to be a "Video Game Preservation Platform", maybe you should avoid that.

**Comment by strycore** [comment]
Currently, the Flatpak version has Wine support and is able to run Wine games just as well as having it natively installed on the OS. 

Regarding Linux native games, I'm hoping that Flatpak and Snap will make the situation better than what it currently is without containers. A huge chunk of Linux native games released more than 10 years ago won't even launch on modern distros. By creating Flatpak runtimes specifically tailored to run older games, it would be possible to recreate an environment where games can run as expected. 

For me this new approach is the way to preserve games. Linux distros are a moving target and we can't keep proprietary software running on them in the long run. At some point we need to recreate an environment similar to what OSes where like **when the game was released**. Linux games not being maintainable over the long term is what made Win32 the most stable API on Linux ( https://blog.hiler.eu/win32-the-only-stable-abi/ )

**Comment by danieljohnson2** [comment]
There is much in what you say. I've certainly seen the issues with Linux native games. I hope you turn out to be right about this.

**Comment by capecrusader-121** [comment]
@strycore  @danieljohnson2  I have wondered do apps like bottles do something different than lutris ? They work fine in the flatpak sandbox and allows custom wine versions to be downloaded. I am trying to do something similar for the lutris snap, in my latest revisions i am not stuffing the snap with any wine etc. libs leaving this to be provided by lutris but that is not what happening. I am facing two different situations  , to get the snap working a user will have to do any of the following to get it working; (Can any one of these be ideally patched to be the default at-least for snaps, as without doing them manually lutris snap is just a demo app with only the frontend working but backend nonfunctional  ?)
1) Enabling 'Disable Lutris Runtime' in settings helps get rid of this problem.
2) Also, instead of 1, Disabling 'Prefer System Libraries' also gets rid of this problem.

I have detailed the problem and the different consequences of the above options at --> https://bugs.launchpad.net/lutris-snap/+bug/2031886

I prefer disabling prefer system libraries but going with lutris runtime leads to permission error upon which this issue is created, the lutris snap wont move forward the permission error, is there any way i could temporarily make the snap move forward ?

** Do note Unlike flatpak snaps do not wine sdk etc. which can be used to provide wine to lutrs snap etc.

**Comment by strycore** [comment]
Bottles is only dealing with Wine so it's a much simpler situation to handle. 
But like we've been saying, Lutris needs at least the Wine dependencies to function properly. 

Also, the Lutris runtime needs to work, if you're getting errors while running some runners, find out the missing components. Here, it looks like you're missing libSDL2 and libffi. If Lutris can't control other Snaps then for the moment, Lutris will have to provide any library need to have runners function correctly. 

For Protobuf, the last version that's currently supported is 3.20.3. Protobuf 4.x won't work, but we really need to update that as 4.x is what's usually shipped now.

I've added an exception handler for the permission issue. Does that make anything better?

**Comment by capecrusader-121** [comment]
@strycore  I do have staged libsdl and the log is bit outdated, but yes after libsdl has been added, the permission error is the road-block, i will try building from the source and report back.

**Comment by capecrusader-121** [comment]
@strycore  Well the lutris snap successfully bypassed the permission error although its conflicting with gnome-sdk.

```
2023-08-24 10:12:43,139: Accessing game config while runner wasn't given one.
Started initial process 33388 from /home/sam/snap/lutris/184/.local/share/lutris/runners/scummvm/bin/scummvm --extrapath=/home/sam/snap/lutris/184/.local/share/lutris/runners/scummvm/share/scummvm --themepath=/home/sam/snap/lutris/184/.local/share/lutris/runners/scummvm/share/scummvm
Start monitoring process.
Waiting for game to start (first non-excluded process started)
/home/sam/snap/lutris/184/.local/share/lutris/runners/scummvm/bin/scummvm: symbol lookup error: /snap/lutris/184/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0: undefined symbol: pango_font_description_set_variations
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```

**Comment by strycore** [comment]
The fact that the error is bypassed doesn't mean Lutris is working correctly.
