### ISSUE TITLE
Cannot sign into Ubisoft Connect

### ISSUE THREAD

**Issue by IvoryJam** [lutris/lutris#5011]
### Bug description

Trying to sign in Ubisoft Connect doesn't work and results in the error

```RuntimeError: Ubisoft authentication has been lost: Nonce was not found for the profile```

### How to Reproduce

1. Click "Connect" on Ubisoft Connect
2. Sign in

### Expected behavior

Ubisoft Connect should sign in

### Log output

```shell
➜ ~ lutris -d
INFO     2023-08-30 15:44:46,943 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-08-30 15:44:46,945 [startup.check_driver:65]:Using NVIDIA drivers 535.98 for x86_64
INFO     2023-08-30 15:44:46,945 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 2070
INFO     2023-08-30 15:44:46,945 [startup.check_driver:85]:GPU: 10DE:1F07 3842:2173 (nvidia drivers)
DEBUG    2023-08-30 15:44:47,214 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-08-30 15:44:51,557 [base.login:358]:Connecting to Ubisoft Connect
DEBUG    2023-08-30 15:44:58,326 [client._do_request_safe:78]:rememberMeTicket expiration time: 0
DEBUG    2023-08-30 15:44:58,327 [client._refresh_ticket:152]:Refreshing ticket
INFO     2023-08-30 15:44:58,653 [client._do_request:67]:Response status: <Response [200]>
INFO     2023-08-30 15:44:58,778 [client._do_request:67]:Response status: <Response [200]>
DEBUG    2023-08-30 15:44:58,780 [client._refresh_remember_me:130]:Refreshing rememberMeTicket
INFO     2023-08-30 15:44:58,859 [client._do_request:67]:Response status: <Response [200]>
INFO     2023-08-30 15:44:58,991 [client._do_request:67]:Response status: <Response [401]>
ERROR    2023-08-30 15:44:58,992 [client._do_request_safe:99]:Unable to refresh authentication calling auth lost: Nonce was not found for the profile
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 121, in _refresh_auth
    self._service.store_credentials(self.get_credentials())
  File "/usr/lib/python3.11/site-packages/lutris/services/ubisoft.py", line 170, in store_credentials
    with open(self.token_path, "w", encoding='utf-8') as auth_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user_name/.cache/lutris/ubisoft/.token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 84, in _do_request_safe
    self._refresh_auth()
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 123, in _refresh_auth
    self._refresh_remember_me()
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 132, in _refresh_remember_me
    j = self._do_request(
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 70, in _do_request
    raise RuntimeError(result['message'])
RuntimeError: Nonce was not found for the profile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/webconnect_dialog.py", line 81, in on_navigation
    self.service.login_callback(url)
  File "/usr/lib/python3.11/site-packages/lutris/services/ubisoft.py", line 120, in login_callback
    user_data = self.client.authorise_with_local_storage(storage_jsons)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 230, in authorise_with_local_storage
    self.post_sessions()
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 312, in post_sessions
    return self._do_request_safe(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/ubisoft/client.py", line 102, in _do_request_safe
    raise RuntimeError(_("Ubisoft authentication has been lost: %s") % ex) from ex
RuntimeError: Ubisoft authentication has been lost: Nonce was not found for the profile
```
```


### System Information

```shell
[System]
OS:              Fedora Linux 38 Workstation Edition
Arch:            x86_64
Kernel:          6.4.12-200.fc38.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 2700X Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.98
OpenGL Core:     4.6.0 NVIDIA 535.98
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.98
Vulkan Version:  1.3.243
Vulkan Drivers:  NVIDIA GeForce RTX 2070 (1.3.242)
```

### Media (optional)

![image](https://github.com/lutris/lutris/assets/35709713/3a1226fc-a0e2-460a-a304-ff2d534a3b64)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Ubisoft Connect login works fine. Is there something weird going on with your Ubisoft account that would trigger the "Nonce was not found for the profile" error?

**Comment by IvoryJam** [comment]
I've got MFA enabled, so maybe that's something? When I tried after logging in, it shows up with my account already there.

**Comment by IvoryJam** [comment]
Removed MFA, same error. I know python so I'm trying to work backwards through the ubisoft client.py to pinpoint what's happening

**Comment by IvoryJam** [comment]
Figured it out, it wasn't creating the ~/.cache/lutris/ubisoft/ directory. Manually creating it I was able to get past that.

**Comment by IvoryJam** [comment]
Same for the flatpak, had to create the ubisoft directory `~/var/app/net.lutris.Lutris/cache/lutris/ubisoft/`

**Comment by strycore** [comment]
I wasn't able to reproduce the issue but also it's not clear where the folder gets created. So I added something to make sure the folder is created just before your crash occurred.
