### ISSUE TITLE
Cannot install Epic Games Store on Lutris: downloading arialb32.exe failed

### ISSUE THREAD

**Issue by ReturnMinusOne** [lutris/lutris#5033]
### Bug description

Hello,

I've now failed twice to install the Epic Games Launcher through Lutris. According to the installation window, Lutris tries to connect to :

`https://web.archive.org/web/2000/https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe`

but gets a 503 Service Unavailable error. The installation then exits with the return code 256.

Having tried the URL myself, archive.org is up and running, and I'm able to download arialb32.exe manually.

### How to Reproduce

1. Open Lutris.
2. Click the installation button next to "Epic Games Store".

### Expected behavior

Installation completes successfully.

### Log output

```shell
(I've replace my username with "username"; everything else is unchanged.)

lutris -d                                                                     ✔ 
INFO     2023-09-23 14:43:32,080 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-09-23 14:43:32,082 [startup.check_driver:73]:Running AMD Mesa driver 23.1.7 on AMD Radeon RX 590 Series (polaris10, LLVM 16.0.6, DRM 3.49, 6.1.53-1-MANJARO) (0x67df)
INFO     2023-09-23 14:43:32,082 [startup.check_driver:85]:GPU: 1002:67DF 1458:2311 (amdgpu drivers)
ERROR    2023-09-23 14:43:32,082 [startup.check_libs:120]:i386 libgnutls.so.30 missing (needed by gnutls)
DEBUG    2023-09-23 14:43:32,247 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-09-23 14:43:32,284 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-09-23 14:43:56,441 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/epic-games-store
DEBUG    2023-09-23 14:43:56,441 [http._request:88]:GET https://lutris.net/api/installers/epic-games-store
DEBUG    2023-09-23 14:43:56,905 [application.show_window:339]:Showing window InstallerWindowepic-games-store
DEBUG    2023-09-23 14:43:58,837 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-09-23 14:44:02,359 [runner.get_runner_version:480]:Getting runner information for wine (version: lutris-GE-Proton8-14-x86_64)
DEBUG    2023-09-23 14:44:02,360 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2023-09-23 14:44:02,552 [interpreter.get_runners_to_install:278]:Failed to get default wine version (got {})
DEBUG    2023-09-23 14:44:03,986 [downloader.start:67]:⬇ https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
DEBUG    2023-09-23 14:44:04,010 [downloader.start:67]:⬇ https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi
DEBUG    2023-09-23 14:44:31,221 [downloader.on_download_completed:170]:Finished downloading https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi
INFO     2023-09-23 14:44:31,543 [file_box.on_download_complete:239]:Download completed
DEBUG    2023-09-23 14:44:31,544 [files_box.on_file_available:108]:epicsetup is available
DEBUG    2023-09-23 14:44:37,792 [downloader.on_download_completed:170]:Finished downloading https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
INFO     2023-09-23 14:44:38,036 [file_box.on_download_complete:239]:Download completed
DEBUG    2023-09-23 14:44:38,036 [files_box.on_file_available:108]:uplay is available
INFO     2023-09-23 14:44:38,037 [files_box.on_file_available:114]:All files available
INFO     2023-09-23 14:44:38,037 [installerwindow.on_files_available:635]:All files are available, continuing install
DEBUG    2023-09-23 14:44:38,040 [interpreter._iter_commands:361]:Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2023-09-23 14:44:38,045 [wine.create_prefix:98]:Creating a win64 prefix in /home/username/Games/epic-games-store
DEBUG    2023-09-23 14:44:38,045 [system.execute:74]:Executing /home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wineboot
DEBUG    2023-09-23 14:44:38,046 [system.execute:80]:WINEARCH=win64 WINEPREFIX=/home/username/Games/epic-games-store WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/mono WINE_GECKO_CACHE_DIR=/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/gecko
INFO     2023-09-23 14:44:39,280 [wine.create_prefix:153]:win64 Prefix created in /home/username/Games/epic-games-store
DEBUG    2023-09-23 14:44:39,299 [interpreter._iter_commands:361]:Installer command: {'write_file': {'content': 'overlay:\n  enabled: false\n  forceunhookgame: false\n  fps_enabled: false\n  warning_enabled: false\nuser:\n  closebehavior: CloseBehavior_Close\nuser:\n  start_on_windows_start: false', 'file': '$GAMEDIR/drive_c/users/$USER/Local Settings/Application Data/Ubisoft Game Launcher/settings.yml'}}
DEBUG    2023-09-23 14:44:39,305 [interpreter._iter_commands:361]:Installer command: {'task': {'app': 'corefonts', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
DEBUG    2023-09-23 14:44:39,330 [wine.use_lutris_runtime:123]:/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wine is provided by Lutris, using runtime
ERROR    2023-09-23 14:44:39,530 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2023-09-23 14:44:39,531 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2023-09-23 14:44:39,555 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-09-23 14:44:39,555 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/username/.cache/lutris/shaders/wine"
DEBUG    2023-09-23 14:44:39,555 [command.start:141]:LD_LIBRARY_PATH="/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/lib:/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/lib64:/usr/lib:/usr/lib32:/opt/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/lib/opencollada:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/latest/linux/lib:/usr/lib/libfakeroot:/usr/lib64:/home/username/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/username/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/username/.local/share/lutris/runtime/steam/i386/lib:/home/username/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/username/.local/share/lutris/runtime/steam/i386/usr/lib:/home/username/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/username/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/username/.local/share/lutris/runtime/steam/amd64/lib:/home/username/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/username/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-09-23 14:44:39,555 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:WINEARCH="win64"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:WINE="/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wine"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:WINE_MONO_CACHE_DIR="/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/mono"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/gecko"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/lib64/gstreamer-1.0/:/home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:WINEPREFIX="/home/username/Games/epic-games-store"
DEBUG    2023-09-23 14:44:39,556 [command.start:141]:WINEESYNC="1"
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/username/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:PROTON_EAC_RUNTIME="/home/username/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d12core,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64=n;winemenubuilder="
DEBUG    2023-09-23 14:44:39,557 [command.start:141]:STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/username/.local/share/Steam/"
DEBUG    2023-09-23 14:44:39,558 [command.start:141]:STEAM_COMPAT_DATA_PATH="/home/username/Games/epic-games-store"
DEBUG    2023-09-23 14:44:39,558 [command.start:141]:STEAM_COMPAT_APP_ID="0"
DEBUG    2023-09-23 14:44:39,558 [command.start:141]:SteamAppId="0"
DEBUG    2023-09-23 14:44:39,558 [command.start:141]:SteamGameId="lutris-game"
DEBUG    2023-09-23 14:44:39,558 [command.start:141]:PATH="/home/username/.local/share/lutris/runtime/winetricks:/home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
DEBUG    2023-09-23 14:44:39,558 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages"
DEBUG    2023-09-23 14:44:39,558 [command.start:141]:LUTRIS_GAME_UUID="be851e85-2264-459d-bb23-1af143d7ca88"
lutris-wrapper: /home/username/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 56411 from /home/username/.local/share/lutris/runtime/winetricks/winetricks --unattended corefonts
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20220411-next, latest upstream is winetricks-20230212!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
Executing mkdir -p /home/username/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 50b745d7f46ead56fd0c9e6d753d53ea0ae368c988434c25d65fec66307e5d4f with wine-5.12-23835-g0bee1bf20f5 (Staging) and WINEARCH=win64
Executing w_do_call corefonts
Executing mkdir -p /home/username/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_corefonts 
Executing w_do_call andale
Executing mkdir -p /home/username/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_andale 
grep: avertissement : \ surnuméraire avant /
Executing cabextract -q -d /home/username/Games/epic-games-store/dosdevices/c:/windows/temp /home/username/.cache/winetricks/corefonts/andale32.exe
------------------------------------------------------
warning: Running /home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/home/username/Games/epic-games-store terminate
------------------------------------------------------
Executing /home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Executing /home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /home/username/Games/epic-games-store/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.AcjTQBfA/_reg_90ad6a9f_56411.reg
Executing /home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/username/.local/share/lutris/runners/wine/lutris-GE-Proton8-14-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /home/username/Games/epic-games-store/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.AcjTQBfA/_reg_f6204652_56411.reg
Executing w_do_call arial
Executing mkdir -p /home/username/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_arial 
grep: avertissement : \ surnuméraire avant /
grep: avertissement : \ surnuméraire avant /
Executing cd /home/username/.cache/winetricks/corefonts
Downloading https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe to /home/username/.cache/winetricks/corefonts
--2023-09-23 14:44:50--  https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe
Certificat de l’autorité de certification « /etc/ssl/certs/ca-certificates.crt » chargé
Résolution de mirrors.kernel.org (mirrors.kernel.org)… 147.75.80.249, 2604:1380:4601:e00::3
Connexion à mirrors.kernel.org (mirrors.kernel.org)|147.75.80.249|:443… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2023-09-23 14:44:56 erreur 404 : Not Found.

Executing cd /home/username/.cache/winetricks/corefonts
Downloading https://web.archive.org/web/2000/https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe to /home/username/.cache/winetricks/corefonts
--2023-09-23 14:44:56--  https://web.archive.org/web/2000/https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe
Certificat de l’autorité de certification « /etc/ssl/certs/ca-certificates.crt » chargé
Résolution de web.archive.org (web.archive.org)… 207.241.237.3
Connexion à web.archive.org (web.archive.org)|207.241.237.3|:443… connecté.
requête HTTP transmise, en attente de la réponse… 302 FOUND
Emplacement : https://web.archive.org/web/20180406173701/https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe [suivant]
--2023-09-23 14:45:07--  https://web.archive.org/web/20180406173701/https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe
Réutilisation de la connexion existante à web.archive.org:443.
requête HTTP transmise, en attente de la réponse… 503 Service Unavailable
2023-09-23 14:45:12 erreur 503 : Service Unavailable.

------------------------------------------------------
warning: Downloading https://web.archive.org/web/2000/https://mirrors.kernel.org/gentoo/distfiles/arialb32.exe failed
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
DEBUG    2023-09-23 14:45:12,451 [command.on_stop:195]:Process 56405 has terminated with code 256
DEBUG    2023-09-23 14:45:12,578 [commands._monitor_task:444]:Return code: 256
ERROR    2023-09-23 14:45:12,579 [errors.__init__:18]:La commande s'est terminée avec le code 256
ERROR    2023-09-23 14:45:12,579 [exceptions.wrapper:63]:La commande s'est terminée avec le code 256
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 446, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: La commande s'est terminée avec le code 256
```

### System Information

```shell
[System]
OS:              Manjaro Linux 23.0.2 Uranos
Arch:            x86_64
Kernel:          6.1.53-1-MANJARO
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 590 Series (polaris10, LLVM 16.0.6, DRM 3.49, 6.1.53-1-MANJARO)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.7-1
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.7-1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.7-1
Vulkan Version:  1.3.264
Vulkan Drivers:  AMD Radeon RX 590 Series (RADV POLARIS10) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReturnMinusOne** [comment]
One day later and after one reboot, the launcher has now installed successfully.

I can't say I have any idea where the issue came from, as I turn off the system at the end of each day. But the launcher is connected and appears to install and run  games correctly.

**Comment by strycore** [comment]
Looks like a temporary network glitch from Archive.org's servers where the Arial font is hosted.

**Comment by ReturnMinusOne** [comment]
Well, since the URL was still accessible in browser, maybe the installer could ask for the file locally if it can't be found on the server? I don't know if other files are also required in the same way.

**Comment by strycore** [comment]
The installer uses Winetricks to install components to Wine prefixes, it can't really interfere with how it works.

**Comment by ReturnMinusOne** [comment]
If the software can identify the problem when it happens, I'd settle for a brief explanation and some suggestions (like rebooting or waiting 24 hours, in my case) when the install fails.
