### ISSUE TITLE
InstallerFile._file_meta can be none if the entry is not indented enough, triggering cryptic errors

### ISSUE THREAD

**Issue by zurgeg** [lutris/lutris#5057]
### Bug description

If you only indent file metadata with one tab instead of two, the installer parser won't recognize the file metadata. I reproduced it with this installer:
```yml
name: "Lutris Bug MREX"
game_slug: "deadbeef"
version: "zurgeg was here :)"
slug: "deadbeef"
runner: "wine"
script:
  game:
    exe: "example.exe"
  files:
  - working: 
    url: https://example.com/broken
    filename: broken.txt
  - working:
      url: https://example.com/working
      filename: working.txt
```

### How to Reproduce

Steps to reproduce this bug:
1. Paste the installer into a file (I called it `mrex.yml`)
2. Try to install it with `lutris -di mrex.yml`
3. Hit the install button next to "zurgeg was here :)"
4.  Look in the console. Notice that the installer fails

### Expected behavior

Lutris should parse it just fine, or throw a less confusing error (i.e., throw an error if `_file_meta == none`)

### Log output

```shell
(Note: I added a small print statement to show file meta for debugging purposes)
INFO     2023-10-04 19:59:38,683 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-10-04 19:59:38,687 [startup.check_driver:65]:Using NVIDIA drivers 535.113.01 for x86_64
INFO     2023-10-04 19:59:38,687 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 2060
INFO     2023-10-04 19:59:38,688 [startup.check_driver:85]:GPU: 10DE:1E89 1462:3755 (nvidia drivers)
INFO     2023-10-04 19:59:38,688 [startup.check_driver:85]:GPU:   (simple-framebuffer drivers)
DEBUG    2023-10-04 19:59:38,938 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-10-04 19:59:39,035 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-10-04 19:59:39,040 [__init__.read_script:23]:Loading script(s) from /home/jg/RS2014 Lutris Installer/mrex.yml
DEBUG    2023-10-04 19:59:39,074 [application.show_window:339]:Showing window InstallerWindowdeadbeef
DEBUG    2023-10-04 19:59:57,305 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-10-04 19:59:57,375 [runner.get_runner_version:480]:Getting runner information for wine (version: lutris-GE-Proton8-15-x86_64)
DEBUG    2023-10-04 19:59:57,376 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2023-10-04 19:59:57,644 [interpreter.get_runners_to_install:264]:Default wine version is lutris-GE-Proton8-15
File meta:
{'url': 'https://example.com/working', 'filename': 'working.txt'}
File meta:
None
ERROR    2023-10-04 19:59:57,683 [exceptions.wrapper:63]:'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 563, in on_extras_ready
    if not self.load_installer_files_page():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 579, in load_installer_files_page
    self.interpreter.installer.prepare_game_files(patch_version)
  File "/usr/lib/python3.11/site-packages/lutris/installer/installer.py", line 170, in prepare_game_files
    file.set_url(self.interpreter._substitute(file.url))
                                              ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/installer_file.py", line 40, in url
    if _url.startswith("/"):
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### System Information

```shell
[System]
OS:              Garuda Linux Soaring Raptor
Arch:            x86_64
Kernel:          6.5.5-zen1-1-zen
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            15.5 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.113.01
OpenGL Core:     4.6.0 NVIDIA 535.113.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.113.01
Vulkan Version:  1.3.264
Vulkan Drivers:  NVIDIA GeForce RTX 2060 (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I added a check  to catch this kind of error
