### ISSUE TITLE
Lutris 5.14 (Arch Linux) [Errno 2] No such file or directory: ~/.wine/user.reg 

### ISSUE THREAD

**Issue by LyrixTheDj** [lutris/lutris#5110]
### Bug description

After update to 5.14, can't start any game with message "No such file or directory: '~/.wine_gms/ass/user.reg'". In previous 5.13 all was ok.

### How to Reproduce

It happens only if in configs (/home/USERNAME/.config/lutris/games/*.yml) path to "/home/.wine/" written like ~/.wine/ with tilde symbol.

### Expected behavior

.

### Log output

```shell
[lyrix@lrxdsnix /]$ LC_MESSAGES=C lutris
2023-10-29 19:22:58,203: Starting Lutris 0.5.14
2023-10-29 19:22:58,204: Running AMD Mesa driver 23.2.1 on AMD Radeon RX 570 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.9-AMD-znver2) (0x67df)
2023-10-29 19:22:58,204: GPU: 1002:67DF 1462:341B (amdgpu drivers)
2023-10-29 19:23:03,993: [Errno 2] No such file or directory: '~/.wine_gms/ass/user.reg'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 67, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/game_bar.py", line 267, in on_link_button_clicked
    callback(button)
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 794, in run_winecfg
    self.prelaunch()
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 915, in prelaunch
    self.sandbox(prefix_manager)
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 1062, in sandbox
    wine_prefix.enable_desktop_integration_sandbox(desktop_dir=self.runner_config.get("sandbox_dir"))
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/prefix.py", line 163, in enable_desktop_integration_sandbox
    self.enable_desktop_disintegration()
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/prefix.py", line 192, in enable_desktop_disintegration
    desktop_folders = self.get_desktop_folders()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/prefix.py", line 147, in get_desktop_folders
    folder = self.get_registry_key(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/prefix.py", line 116, in get_registry_key
    registry = WineRegistry(self.get_registry_path(key))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/registry.py", line 86, in __init__
    self.parse_reg_file(reg_filename)
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/registry.py", line 113, in parse_reg_file
    registry_lines = self.get_raw_registry(reg_filename)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/registry.py", line 103, in get_raw_registry
    with open(reg_filename, "r", encoding='utf-8') as reg_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/.wine_gms/ass/user.reg'
2023-10-29 19:23:06,820: Shutting down Lutris
```

### System Information

```shell
[System]
OS:              ArcoLinux rolling n/a
Arch:            x86_64
Kernel:          6.5.9-AMD-znver2
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            7.8 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 570 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.9-AMD-znver2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-arch1.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-arch1.2
Vulkan Version:  1.3.269
Vulkan Drivers:  AMD Radeon RX 570 Series (RADV POLARIS10) (1.3.255)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Oooh, oooh! I've seen this one!

I bet this is #5101, where Lutris somehow gets those ~ things in its .yml files. Still don't know what causes that, but the master branch can consume them (I hope), and a workaround is to update all these paths by re-saving the configuration files. See #5101.

**Comment by strycore** [comment]
@Sweeper5 instead of staying on 0.5.13 which we don't support, can you try running the current development branch and confirm the issue is fixed?

**Comment by Sweeper5** [comment]
@strycore If I under Arch Linux go the AUR route and pull the Git package and compile it, it seems to run normally.
So clearly this issue has been fixed, however I do recommend that you do a point release to include this, as for most people will seem like a broken update of Lutris.
While Arch is a minority, it is the canary in the coal mine, so you may want to stem the tide before other distros pick up on it and you get a lot of issue reports regarding this from people trying to be helpful.
Just a quick tip from me to save yourself some future headaches and let you focus on making this awesome tool.

**Comment by danieljohnson2** [comment]
We're not quite ready to go on the next release; we'd like to properly address the "twiddle your thumbs while a new Wine downloads" issue.

I wish I understood where all those dumb ~ came from; it's not universal, and it's hard to gauge how common this problem is.

**Comment by 1basti1** [comment]
Hello, I noticed this same problem now on my steam deck.
I tried to launch a game and I won't open, on desktop mode I see this error.

I didn't used lutris for probably 6 months now. Everything worked fine last time I used it.

Is there any fix now that I can do? I use flatpak.
