### ISSUE TITLE
[Arch Linux] expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Iron-Squid** [lutris/lutris#5120]
### Bug description

Certain games/runners seem to not execute properly, despite working outside of Lutris. 
(EasyRPG is a runner I only install through Lutris, it doesn't work at all anymore due to this same issue.)

For example, I may run a game with my system installation+prefix of Wine (it also occurs with other installations of wine, including lutris-provided wine) perfectly fine via the terminal, but Lutris doesn't execute it at all. It complains of some python issues from the CLI.

I see that this has occurred multiple times before via closed bug reports, I wish to bring it to knowledge again. This also occurs while using the Flatpak, if that's any indication of what may be occurring.
I've ensured that my system packages are up-to-date and uncorrupted.

### How to Reproduce

1. Go to 'Lutris UI'
2. Click on 'Play'
3. Do 'Wait for game to launch'
4. See 'expected str, bytes or os.PathLike object, not NoneType'

### Expected behavior

What's expected is that the game should execute. (Sorry I don't mean to sound rude)

### Log output

```shell
INFO     2023-11-07 07:23:08,722 [application.do_command_line:439]:Starting Lutris 0.5.14
INFO     2023-11-07 07:23:08,724 [startup.get_drivers:68]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.9-arch2-1) (0x67df)
INFO     2023-11-07 07:23:08,724 [display.display_gpu_info:78]:GPU: 1002:67DF 1682:C580 (amdgpu drivers)
DEBUG    2023-11-07 07:23:09,988 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2023-11-07 07:23:13,561 [application.show_window:362]:Showing window EditGameConfigDialog3
DEBUG    2023-11-07 07:23:17,503 [game.save:429]:Saving The Fruit of Grisaia (wine) with config ID the-fruit-of-grisaia-1672430619
DEBUG    2023-11-07 07:23:17,504 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=the-fruit-of-grisaia-1672430619, runner=wine) config to /home/squid/.config/lutris/games/the-fruit-of-grisaia-1672430619.yml
DEBUG    2023-11-07 07:23:18,392 [lutris.add_to_path_cache:164]:Adding The Fruit of Grisaia (wine) to path cache
DEBUG    2023-11-07 07:23:18,414 [application.on_app_window_destroyed:380]:Removed window EditGameConfigDialog3
ERROR    2023-11-07 07:23:20,009 [jobs.target:33]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f0d382b8790>>: <class 'TypeError'> expected str, bytes or os.PathLike object, not NoneType
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 31, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 907, in prelaunch
    prefix_path = self.prefix_path
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 615, in prefix_path
    _prefix_path = os.path.expanduser(_prefix_path)  # just in case!
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 232, in expanduser
ERROR    2023-11-07 07:23:20,025 [exceptions.wrapper:103]:The Fruit of Grisaia (wine) has encountered an error: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 97, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 699, in configure_game
    raise error
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 31, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 907, in prelaunch
    prefix_path = self.prefix_path
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 615, in prefix_path
    _prefix_path = os.path.expanduser(_prefix_path)  # just in case!
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 232, in expanduser
TypeError: expected str, bytes or os.PathLike object, not NoneType
DEBUG    2023-11-07 07:23:20,026 [application.on_game_stop:733]:Removing 3 from running IDs
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.5.9-arch2-1
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600 Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.9-arch2-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-arch1.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-arch1.2
Vulkan Version:  1.3.269
Vulkan Drivers:  AMD Radeon RX 580 Series (RADV POLARIS10) (1.3.255), AMD Radeon RX 580 Series (1.3.250)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Iron-Squid** [comment]
Also of note is that some games still work perfectly fine with the exact same wine prefix.
I can launch a majority of my games, but some of them fail to launch with this issue.

**Comment by Iron-Squid** [comment]
Something I tried just now is to use a generate a new wine prefix.... That fixed my wine issue, but doesn't explain the EasyRPG issue.

**Comment by Iron-Squid** [comment]
```INFO     2023-11-07 07:34:08,663 [application.do_command_line:439]:Starting Lutris 0.5.14
INFO     2023-11-07 07:34:08,665 [startup.get_drivers:68]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.9-arch2-1) (0x67df)
INFO     2023-11-07 07:34:08,665 [display.display_gpu_info:78]:GPU: 1002:67DF 1682:C580 (amdgpu drivers)
DEBUG    2023-11-07 07:34:09,910 [lutris.get_missing_game_ids:206]:Checking for missing games
ERROR    2023-11-07 07:34:22,607 [exceptions.wrapper:103]:Ib (easyrpg) has encountered an error: expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 97, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 665, in configure_game
    self.start_game()
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 721, in start_game
    self.game_thread.start()
  File "/usr/lib/python3.11/site-packages/lutris/command.py", line 156, in start
    self.game_process = self.execute_process(wrapper_command, env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/command.py", line 241, in execute_process
    return subprocess.Popen(  # pylint: disable=consider-using-with
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not int
DEBUG    2023-11-07 07:34:22,609 [application.on_game_stop:733]:Removing 37 from running IDs
```

Here is the output when running an EasyRPG game.

**Comment by danieljohnson2** [comment]
You have two different issues here. The original issue is in our Wine support, and it's a bug in the code I added to cope with the mysterious ~/ paths we are getting in .yml config files. Still no idea where they come from, but this is a simple bug; I've added a check to handle that case where the prefix is not supplied and not try to expand the ~ in it in that case.

The EasyRPG issue is very odd looking; it's an int where a str was expected, not a None, and it's blowing up deep inside Popen and I am not sure where an int can be getting into there. Definitely not the same thing as what I just fixed.

Please file that separately, and I'll look into it. I expect I'll need to ask you to run tests for me, though.
