### ISSUE TITLE
[Arch Linux] (easyrpg) has encountered an error: expected str, bytes or os.PathLike object, not int

### ISSUE THREAD

**Issue by Iron-Squid** [lutris/lutris#5125]
### Bug description

Currently I am unable to launch Lutris, as #5124 currently affects me. Described below is copied over from #5120, at the request of @danieljohnson2.

The issue is that Easyrpgplayer fails to launch via Lutris, this is describing the runner that Lutris itself installs. Running the executable (that lutris provides) _outside_ of lutris (via command line) results in the executable functioning properly. 

### How to Reproduce

1. Go to 'Lutris UI'
2. Click on 'Any EasyRPG-player game'
3. Do 'Launch the game'
4. See '(expected str, bytes or os.PathLike object, not int'

### Expected behavior

Expected is that Lutris launches EasyRPG-Player without issue.

### Log output

```shell
INFO     2023-11-07 07:34:08,665 [startup.get_drivers:68]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.9-arch2-1) (0x67df)
INFO     2023-11-07 07:34:08,665 [display.display_gpu_info:78]:GPU: 1002:67DF 1682:C580 (amdgpu drivers)
DEBUG    2023-11-07 07:34:09,910 [lutris.get_missing_game_ids:206]:Checking for missing games
ERROR    2023-11-07 07:34:22,607 [exceptions.wrapper:103]:Ib (easyrpg) has encountered an error: expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 97, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 665, in configure_game
    self.start_game()
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 721, in start_game
    self.game_thread.start()
  File "/usr/lib/python3.11/site-packages/lutris/command.py", line 156, in start
    self.game_process = self.execute_process(wrapper_command, env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/command.py", line 241, in execute_process
    return subprocess.Popen(  # pylint: disable=consider-using-with
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not int
DEBUG    2023-11-07 07:34:22,609 [application.on_game_stop:733]:Removing 37 from running IDs
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.5.9-arch2-1
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600 Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.9-arch2-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-arch1.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-arch1.2
Vulkan Version:  1.3.269
Vulkan Drivers:  AMD Radeon RX 580 Series (RADV POLARIS10) (1.3.255), AMD Radeon RX 580 Series (1.3.250)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Iron-Squid** [comment]
I've temporarily worked around #5124 using LD_LIBRARY_PATH to a folder with the "missing" `.so` file. I am now able to launch Lutris for the purpose of resolving this issue.

**Comment by danieljohnson2** [comment]
Hang on; I'll need to set up a branch with some tests for you to run to try to find the source of the mystery int.

**Comment by danieljohnson2** [comment]
OK, I've got something. Download [this branch here](https://github.com/lutris/lutris/tree/dj/int_hunting).

Do not install it; just run the bin/lutris script, use the -d option, in there and try to start your game. You should get a bunch of log spam that lists out all the stuff going into execute_process and gives the type of each. We're looking for <class: 'int'> in there somewhere.

Please post the spam for me. Thank you!

**Comment by Iron-Squid** [comment]
```squid@ious:~/Downloads/lutris-dj-int_hunting$ ./bin/lutris -d
INFO     2023-11-15 15:47:08,467 [application.do_command_line:439]:Starting Lutris 0.5.14
INFO     2023-11-15 15:47:08,474 [startup.get_drivers:68]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.6.1-arch1-1) (0x67df)
INFO     2023-11-15 15:47:08,475 [display.display_gpu_info:78]:GPU: 1002:67DF 1682:C580 (amdgpu drivers)
DEBUG    2023-11-15 15:47:09,820 [http._request:88]:GET https://lutris.net/api/runtimes/versions?pci_ids=1002:67DF%201682:C580
DEBUG    2023-11-15 15:47:10,149 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-11-15 15:47:10,415 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2023-11-15 15:47:16,414 [command.start:153]:['/home/squid/Downloads/lutris-dj-int_hunting/share/lutris/bin/lutris-wrapper', 'Ib', '0', '0', 'gamemoderun', '/home/squid/Games/1b Lutris Runners/easyrpg/easyrpg-player', '--seed', -1, '--music-volume', 100, '--sound-volume', 100, '--window', '--game-resolution', 'original', '--scaling', 'bilinear', '--fps-limit', 60, '--project-path', '/home/squid/Games/rpgmakergames/Ib107']
DEBUG    2023-11-15 15:47:16,414 [command.start:155]:  /home/squid/Downloads/lutris-dj-int_hunting/share/lutris/bin/lutris-wrapper: <class 'str'>
DEBUG    2023-11-15 15:47:16,415 [command.start:155]:  Ib: <class 'str'>
DEBUG    2023-11-15 15:47:16,415 [command.start:155]:  0: <class 'str'>
DEBUG    2023-11-15 15:47:16,415 [command.start:155]:  0: <class 'str'>
DEBUG    2023-11-15 15:47:16,415 [command.start:155]:  gamemoderun: <class 'str'>
DEBUG    2023-11-15 15:47:16,416 [command.start:155]:  /home/squid/Games/1b Lutris Runners/easyrpg/easyrpg-player: <class 'str'>
DEBUG    2023-11-15 15:47:16,416 [command.start:155]:  --seed: <class 'str'>
DEBUG    2023-11-15 15:47:16,416 [command.start:155]:  -1: <class 'int'>
DEBUG    2023-11-15 15:47:16,416 [command.start:155]:  --music-volume: <class 'str'>
DEBUG    2023-11-15 15:47:16,417 [command.start:155]:  100: <class 'int'>
DEBUG    2023-11-15 15:47:16,417 [command.start:155]:  --sound-volume: <class 'str'>
DEBUG    2023-11-15 15:47:16,417 [command.start:155]:  100: <class 'int'>
DEBUG    2023-11-15 15:47:16,417 [command.start:155]:  --window: <class 'str'>
DEBUG    2023-11-15 15:47:16,417 [command.start:155]:  --game-resolution: <class 'str'>
DEBUG    2023-11-15 15:47:16,418 [command.start:155]:  original: <class 'str'>
DEBUG    2023-11-15 15:47:16,418 [command.start:155]:  --scaling: <class 'str'>
DEBUG    2023-11-15 15:47:16,418 [command.start:155]:  bilinear: <class 'str'>
DEBUG    2023-11-15 15:47:16,418 [command.start:155]:  --fps-limit: <class 'str'>
DEBUG    2023-11-15 15:47:16,418 [command.start:155]:  60: <class 'int'>
DEBUG    2023-11-15 15:47:16,419 [command.start:155]:  --project-path: <class 'str'>
DEBUG    2023-11-15 15:47:16,419 [command.start:155]:  /home/squid/Games/rpgmakergames/Ib107: <class 'str'>
DEBUG    2023-11-15 15:47:16,419 [command.start:158]:SHELL="/bin/bash" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,419 [command.start:158]:SESSION_MANAGER="local/ious:@/tmp/.ICE-unix/1267,unix/ious:/tmp/.ICE-unix/1267" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,420 [command.start:158]:COLORTERM="truecolor" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,420 [command.start:158]:XDG_MENU_PREFIX="gnome-" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,420 [command.start:158]:DOTNET_ROOT="/usr/share/dotnet" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,420 [command.start:158]:SSH_AUTH_SOCK="/run/user/1000/keyring/ssh" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,421 [command.start:158]:MEMORY_PRESSURE_WRITE="c29tZSAyMDAwMDAgMjAwMDAwMAA=" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,421 [command.start:158]:DESKTOP_SESSION="gnome" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,421 [command.start:158]:PWD="/home/squid/Downloads/lutris-dj-int_hunting" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,421 [command.start:158]:LOGNAME="squid" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,421 [command.start:158]:XDG_SESSION_DESKTOP="gnome" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,422 [command.start:158]:QT_QPA_PLATFORMTHEME="qt5ct" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,422 [command.start:158]:XDG_SESSION_TYPE="wayland" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,422 [command.start:158]:SYSTEMD_EXEC_PID="1509" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,422 [command.start:158]:XAUTHORITY="/run/user/1000/.mutter-Xwaylandauth.SUGJE2" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,423 [command.start:158]:MOTD_SHOWN="pam" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,423 [command.start:158]:GDM_LANG="en_US.UTF-8" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,423 [command.start:158]:HOME="/home/squid" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,423 [command.start:158]:USERNAME="squid" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,423 [command.start:158]:LANG="en_US.UTF-8" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,424 [command.start:158]:XDG_CURRENT_DESKTOP="GNOME" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,424 [command.start:158]:MEMORY_PRESSURE_WATCH="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.SettingsDaemon.MediaKeys.service/memory.pressure" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,424 [command.start:158]:VTE_VERSION="7401" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,424 [command.start:158]:WAYLAND_DISPLAY="wayland-0" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,424 [command.start:158]:GNOME_TERMINAL_SCREEN="/org/gnome/Terminal/screen/9e875bc3_13a4_4baa_a056_123fe0b90a7d" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,425 [command.start:158]:DOTNET_BUNDLE_EXTRACT_BASE_DIR="/home/squid/.cache/dotnet_bundle_extract" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,425 [command.start:158]:GNOME_SETUP_DISPLAY=":1" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,425 [command.start:158]:XDG_SESSION_CLASS="user" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,425 [command.start:158]:TERM="xterm-256color" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,425 [command.start:158]:USER="squid" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,426 [command.start:158]:GNOME_TERMINAL_SERVICE=":1.102" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,426 [command.start:158]:DISPLAY=":0" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,426 [command.start:158]:SHLVL="1" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,426 [command.start:158]:XDG_RUNTIME_DIR="/run/user/1000" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,426 [command.start:158]:PS1="\[\033[38;5;10m\]\u@\h\[\]:\[\]\[\033[38;5;69m\]\w\[\]\$ \[\]" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,426 [command.start:158]:DEBUGINFOD_URLS="https://debuginfod.archlinux.org " (<class 'str'>)
DEBUG    2023-11-15 15:47:16,427 [command.start:158]:XDG_DATA_DIRS="/home/squid/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,427 [command.start:158]:PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/home/squid/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,427 [command.start:158]:GDMSESSION="gnome" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,427 [command.start:158]:DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,427 [command.start:158]:MAIL="/var/spool/mail/squid" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,427 [command.start:158]:_="./bin/lutris" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,428 [command.start:158]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,428 [command.start:158]:__GL_SHADER_DISK_CACHE="1" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,428 [command.start:158]:__GL_SHADER_DISK_CACHE_PATH="/home/squid/.cache/lutris/shaders/easyrpg" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,428 [command.start:158]:PULSE_LATENCY_MSEC="60" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,428 [command.start:158]:LD_LIBRARY_PATH="/usr/lib:/usr/lib32:/usr/lib/libfakeroot:/usr/lib64:/home/squid/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/squid/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/squid/.local/share/lutris/runtime/steam/i386/lib:/home/squid/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/squid/.local/share/lutris/runtime/steam/i386/usr/lib:/home/squid/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/squid/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/squid/.local/share/lutris/runtime/steam/amd64/lib:/home/squid/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/squid/.local/share/lutris/runtime/steam/amd64/usr/lib" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,428 [command.start:158]:game_name="Ib" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,429 [command.start:158]:PYTHONPATH="/home/squid/Downloads/lutris-dj-int_hunting:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages" (<class 'str'>)
DEBUG    2023-11-15 15:47:16,429 [command.start:158]:LUTRIS_GAME_UUID="d19a87dc-85c3-42ac-9800-55ea86464b90" (<class 'str'>)
ERROR    2023-11-15 15:47:16,429 [exceptions.wrapper:103]:Ib (easyrpg) has encountered an error: expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "/home/squid/Downloads/lutris-dj-int_hunting/lutris/exceptions.py", line 97, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/squid/Downloads/lutris-dj-int_hunting/lutris/game.py", line 665, in configure_game
    self.start_game()
  File "/home/squid/Downloads/lutris-dj-int_hunting/lutris/game.py", line 721, in start_game
    self.game_thread.start()
  File "/home/squid/Downloads/lutris-dj-int_hunting/lutris/command.py", line 159, in start
    self.game_process = self.execute_process(wrapper_command, env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/squid/Downloads/lutris-dj-int_hunting/lutris/command.py", line 244, in execute_process
    return subprocess.Popen(  # pylint: disable=consider-using-with
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not int
DEBUG    2023-11-15 15:47:16,434 [application.on_game_stop:733]:Removing 37 from running IDs
INFO     2023-11-15 15:47:20,354 [application.do_shutdown:1043]:Shutting down Lutris
```

**Comment by danieljohnson2** [comment]
I see a bunch of <class: 'int'> in there. Let's see if I can't fix that.

**Comment by danieljohnson2** [comment]
OK, I think I've got it. It's those odd [- | +] controls EasyRPG uses in its config- those provide ints. Only MAME uses that control outside of EasyRPG, and it does convert the int to a string.

So, I've added code to do that for EasyRPG too.

Please download [the master branch](https://github.com/lutris/lutris) and run the bin/lutris script within, and see if that won't work for you now. I bet it works!

**Comment by Iron-Squid** [comment]
Can confirm that this fixes the problem. Thank you!
