### ISSUE TITLE
Lutris don't working on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by jfespinal** [lutris/lutris#5128]
### Bug description

When I try to run it. I get some errors  and can't run
`lutris

(process:9359): Gtk-CRITICAL **: 13:05:11.744: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 60, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 19, in <module>
    from lutris.gui.config.preferences_dialog import PreferencesDialog
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/preferences_dialog.py", line 12, in <module>
    from lutris.gui.config.runners_box import RunnersBox
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/runners_box.py", line 8, in <module>
    from lutris.gui.config.runner_box import RunnerBox
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/runner_box.py", line 9, in <module>
    from lutris.gui.dialogs.runner_install import RunnerInstallDialog
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/runner_install.py", line 64, in <module>
    class RunnerInstallDialog(ModelessDialog):
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/runner_install.py", line 74, in RunnerInstallDialog
    if has_stock_icon("software-installed-symbolic") else "wine-symbolic"
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/utils.py", line 155, in has_stock_icon
    return theme.has_icon(name)
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'has_icon'
`

### How to Reproduce

1. Trying to run it

### Expected behavior

Run normally

### Log output

```shell
lutris -d

(process:8595): Gtk-CRITICAL **: 13:02:40.599: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 60, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 19, in <module>
    from lutris.gui.config.preferences_dialog import PreferencesDialog
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/preferences_dialog.py", line 12, in <module>
    from lutris.gui.config.runners_box import RunnersBox
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/runners_box.py", line 8, in <module>
    from lutris.gui.config.runner_box import RunnerBox
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/runner_box.py", line 9, in <module>
    from lutris.gui.dialogs.runner_install import RunnerInstallDialog
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/runner_install.py", line 64, in <module>
    class RunnerInstallDialog(ModelessDialog):
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/runner_install.py", line 74, in RunnerInstallDialog
    if has_stock_icon("software-installed-symbolic") else "wine-symbolic"
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/utils.py", line 155, in has_stock_icon
    return theme.has_icon(name)
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'has_icon'
```

### System Information

```shell
Operating System: openSUSE Tumbleweed 20231108
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.1.7-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HK CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2
Manufacturer: Alienware
Product Name: Alienware 17 R4
System Version: 1.18.0
```

**Comment by strycore** [comment]
how did you install Lutris?

**Comment by jfespinal** [comment]
via Yast from openSUSE repositories

**Comment by strycore** [comment]
looking into this and it doesn't seem to be a dependency issue.

what does `echo $DISPLAY` give you?

**Comment by jfespinal** [comment]
`echo $DISPLAY
:1
`

**Comment by strycore** [comment]
hm, that may be the source of your issue. Normally you should get `:0`. 
Can you try running `DISPLAY=:0 lutris -d` ?

**Comment by jfespinal** [comment]
The :1 was because I had a second monitor plugged in, but I ran DISPLAY=:0 lutris -d and I got the same error.
Then I unplug the second monitor and restart the PC, when I run echo $DISPLAY it shows :0 but when I run lutris -d I get the same error.

**Comment by strycore** [comment]
Well I'm running out of ideas...

**Comment by danieljohnson2** [comment]
The stack trace suggests that somehow @jfespinal has no icon-theme at all. I think we could tolerate that. I'll ad a check; heavens knows what else will break though.

@jfespinal, please download the master branch and run the bin/lutris script therein. It should not crash there anymore; I wonder what will happen. Will you have any icons?

**Comment by jfespinal** [comment]
Hello,
Running from the master branch I get this:
`
./lutris -d

(process:28149): Gtk-CRITICAL **: 18:42:11.104: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
INFO     2023-11-12 18:42:11,250 [application.do_command_line:439]:Starting Lutris 0.5.14
INFO     2023-11-12 18:42:11,252 [startup.get_drivers:55]:Using NVIDIA drivers 535.129.03 for x86_64
INFO     2023-11-12 18:42:11,252 [startup.get_drivers:59]:GPU: NVIDIA GeForce GTX 1080
INFO     2023-11-12 18:42:11,252 [display.display_gpu_info:78]:GPU: 10DE:1BA0 1028:0778 (nvidia drivers)
INFO     2023-11-12 18:42:11,252 [display.display_gpu_info:78]:GPU: 8086:591B 1028:0778 (i915 drivers)
Traceback (most recent call last):
  File "/home/jfespinal/Desktop/lutris-master/lutris/gui/application.py", line 313, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jfespinal/Desktop/lutris-master/lutris/gui/lutriswindow.py", line 90, in __init__
    self.game_store = GameStore(self.service, self.service_media)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jfespinal/Desktop/lutris-master/lutris/gui/views/store.py", line 70, in __init__
    self.store = Gtk.ListStore(
                 ^^^^^^^^^^^^^^
TypeError: GObject.__init__() takes exactly 0 arguments (16 given)
Traceback (most recent call last):
  File "/home/jfespinal/Desktop/lutris-master/lutris/gui/application.py", line 697, in do_command_line
    self.show_update_runtime_dialog(gpu_info)
  File "/home/jfespinal/Desktop/lutris-master/lutris/gui/application.py", line 324, in show_update_runtime_dialog
    init_dialog = LutrisInitDialog(runtime_updater)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jfespinal/Desktop/lutris-master/lutris/gui/dialogs/__init__.py", line 325, in __init__
    self.label = Gtk.Label(_("Checking for runtime updates, please wait…"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)


`

**Comment by danieljohnson2** [comment]
Oh, wow. That is very, very screwed up. There's no way Lutris can run with GTK in a state like that; it seems to not recognize any of GTK's types. That first assertion suggest that is not just PyGTK either; that's blowing up inside of the GTK implementation.

Does any GNOME software work at all for you at all?

You won't be seeing any icons in Lutris; it can't open any windows with errors like that.

**Comment by jfespinal** [comment]
I have gnome-pie and it's running normally, I installed now gnome-calculator for testing, and is running normally. What other gnome app should I try?

**Comment by danieljohnson2** [comment]
This is very strange; these errors should prevent any GNOME application from working. Somehow they are just happening to Lutris.

There's a good chance that the flatpak version of Lutris would work for you, for what that's worth.

**Comment by strycore** [comment]
Maybe the Lollipop media player? https://wiki.gnome.org/Apps/Lollypop

It's also written in Python so that would get you close to what Lutris is using.

@danieljohnson2 I think the recent commits to check if a theme is available should be reverted since they can mask issues. This is clearly not a theme issue and we should find the root cause before applying patches.

**Comment by danieljohnson2** [comment]
Sure, they were informative this time but didn't fix anything. I'll revert them.

**Comment by jfespinal** [comment]
Hello,
I have some good news. I kept reading on the Internet and it was a missing library that I had. When the system updated python 3.10 to python 3.11 there was no the python311-gobject library available yet. So it was that all the time. Just within installing this library, it works now.
Thank you so much for being so kind and helpful. Keep making the world a better place.
