### ISSUE TITLE
Error: Failed to retrieve wine (custom) information

### ISSUE THREAD

**Issue by Mephistople** [lutris/lutris#5139]
### Bug description

When trying to install a game using a GOG installer, Lutris will fail during installation with error saying Failed to retrieve wine (custom) information.

And yes I have several wine versions installed already (see attachment), manual installation works fine.
Using a git version of Lutris from today.

### How to Reproduce

1. Go to the GOG tab.
2. Choose your game.
3. Click install
4. Choose your installer
5. Click continue
6. Get an error message.

### Expected behavior

The installer should continue installing the game without an error.

### Log output

```shell
INFO     2023-11-19 13:02:54,089 [application.do_command_line:439]:Starting Lutris 0.5.14
INFO     2023-11-19 13:02:54,091 [startup.get_drivers:55]:Using NVIDIA drivers 545.29.02 for x86_64
INFO     2023-11-19 13:02:54,092 [startup.get_drivers:59]:GPU: NVIDIA GeForce RTX 2080 Ti
INFO     2023-11-19 13:02:54,092 [display.display_gpu_info:78]:GPU: 10DE:1E07 1458:37A9 (nvidia drivers)
DEBUG    2023-11-19 13:02:54,909 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-19 13:02:56,088 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2023-11-19 13:02:57,541 [services.get_game:34]:Getting service game 1772238447 for gog
DEBUG    2023-11-19 13:02:58,943 [services.get_game:34]:Getting service game 1772238447 for gog
DEBUG    2023-11-19 13:02:58,944 [base.install:276]:Installing 1772238447 from service gog
DEBUG    2023-11-19 13:02:58,944 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2023-11-19 13:02:59,236 [api.get_game_installers:256]:Fetching installer https://lutris.net/api/installers/blacksad-under-the-skin
DEBUG    2023-11-19 13:02:59,237 [http._request:88]:GET https://lutris.net/api/installers/blacksad-under-the-skin
DEBUG    2023-11-19 13:02:59,539 [application.show_window:362]:Showing window InstallerWindow1772238447
DEBUG    2023-11-19 13:03:01,033 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-11-19 13:03:03,423 [interpreter.get_runners_to_install:269]:Runner <lutris.runners.wine.wine object at 0x7f8c83b2ba90> needs to be installed
DEBUG    2023-11-19 13:03:03,423 [interpreter.install_runner:286]:Installing wine
DEBUG    2023-11-19 13:03:03,441 [runner.install:429]:Installing wine (version=custom, callback=<function ScriptInterpreter.install_runner.<locals>.install_more_runners at 0x7f8c80a1c720>)
INFO     2023-11-19 13:03:03,441 [api.get_default_runner_version:149]:Getting runner information for wine (version: custom)
DEBUG    2023-11-19 13:03:03,441 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2023-11-19 13:03:03,750 [interpreter.install_runner:294]:Failed to retrieve wine (custom) information
ERROR    2023-11-19 13:03:03,750 [errors.__init__:18]:Failed to retrieve wine (custom) information
ERROR    2023-11-19 13:03:03,750 [exceptions.wrapper:69]:Failed to retrieve wine (custom) information
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 288, in install_runner
    runner.install(
  File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 441, in install
    raise RunnerInstallationError(_("Failed to retrieve {} ({}) information").format(self.name, version))
lutris.runners.RunnerInstallationError: Failed to retrieve wine (custom) information

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 67, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 416, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 201, in launch_install
    self.install_runners(ui_delegate)
  File "/usr/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 277, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/usr/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 295, in install_runner
    raise ScriptingError(ex.message) from ex
lutris.installer.errors.ScriptingError: Failed to retrieve wine (custom) information
```

### System Information

```shell
[System]
OS:              Manjaro Linux 23.1.0 Vulcan
Arch:            x86_64
Kernel:          6.6.1-1-MANJARO
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            8.8 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 545.29.02
OpenGL Core:     4.6.0 NVIDIA 545.29.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 545.29.02
Vulkan Version:  1.3.269
Vulkan Drivers:  NVIDIA GeForce RTX 2080 Ti (1.3.260)
```

### Media (optional)

https://github.com/lutris/lutris/assets/53997310/b740589d-c16c-41ae-bb05-4822a9e87341

![Wine versions installed](https://github.com/lutris/lutris/assets/53997310/9e3111ab-5d8b-4628-8f6e-31cac8ae20d0)

**Comment by danieljohnson2** [comment]
I can't seem to repro what you are seeing, but you seem to be installing a game using a custom WINE, which in my testing does not work but fails with other errors.

I've reworked the versions again, and got them supporting 'custom' WINE versions for installations. Can't be sure it will help you, but please give it try.

Download the latest master, and run the 'bin/lutris' script within. Try to install your game; does it work now?

**Comment by Mephistople** [comment]
Tried the latest build and gog installers seems to work fine now, thanks for the help :)

**Comment by danieljohnson2** [comment]
Very good. Declaring victory!
