### ISSUE TITLE
Cannot choose setup file when adding a Wine game manually.

### ISSUE THREAD

**Issue by JooJooBee666** [lutris/lutris#5155]
### Bug description

When choosing he option to add a game from "Install a Windows Game from an executable", after setting up the initial name and Wine versions, the Install Windows shows "Wine Setup File                           Install".  At no point am I ever asked to choose the actual EXE to install.  Clicking past this goes to the next screen but when clicking "Continue", the following error pops up in a window "'list' object is not callable".  Right, I'm sure since you have no idea what EXE to install...you never asked.  So now I cannot manually install any new games through Lutris.  

My only options are to currently create the prefix manually, them add an already installed game, link it to Explorer.exe, run it and install the game.  This is obviously less than ideal as I lose some of the automated functions that Lutris does to the prefixes.

### How to Reproduce

1. Click on + in upper left
2. Choose **Install a Windows Game from an executable**
3. Input game name and select Wine versions.  The information here doesn't matter
4. NExt widows comes up but you are then unable to select an executable file.

### Expected behavior

Duh...

### Log output

```shell
023-11-30 15:09:28,252: Command 'fluidsynth' not found on your system
TU: error: ../src/freedreno/vulkan/tu_knl.cc:214: device /dev/dri/renderD129 (amdgpu) is not compatible with turnip (VK_ERROR_INCOMPATIBLE_DRIVER)
TU: error: ../src/freedreno/vulkan/tu_knl.cc:214: device /dev/dri/renderD128 (amdgpu) is not compatible with turnip (VK_ERROR_INCOMPATIBLE_DRIVER)
INFO     2023-11-30 15:09:28,667 [application.do_command_line:460]:Starting Lutris 0.5.14
INFO     2023-11-30 15:09:28,668 [startup.get_drivers:67]:Running AMD Mesa driver 24.0.0 on AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 17.0.4, DRM 3.54, 6.5.12-300.fc39.x86_64) (0x73df)
INFO     2023-11-30 15:09:28,668 [display.display_gpu_info:80]:GPU: 1002:73DF 1EAE:6601 (amdgpu drivers)
INFO     2023-11-30 15:09:28,668 [display.display_gpu_info:80]:GPU: 1002:164E 1458:D000 (amdgpu drivers)
TU: error: ../src/freedreno/vulkan/tu_knl.cc:214: device /dev/dri/renderD129 (amdgpu) is not compatible with turnip (VK_ERROR_INCOMPATIBLE_DRIVER)
TU: error: ../src/freedreno/vulkan/tu_knl.cc:214: device /dev/dri/renderD128 (amdgpu) is not compatible with turnip (VK_ERROR_INCOMPATIBLE_DRIVER)
TU: error: ../src/freedreno/vulkan/tu_knl.cc:214: device /dev/dri/renderD129 (amdgpu) is not compatible with turnip (VK_ERROR_INCOMPATIBLE_DRIVER)
TU: error: ../src/freedreno/vulkan/tu_knl.cc:214: device /dev/dri/renderD128 (amdgpu) is not compatible with turnip (VK_ERROR_INCOMPATIBLE_DRIVER)
DEBUG    2023-11-30 15:09:29,186 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
ERROR    2023-11-30 15:09:30,461 [i18n.get_user_locale:10]:Unable to get locale
DEBUG    2023-11-30 15:09:30,544 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2023-11-30 15:09:34,527 [application.show_window:383]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7f3ce5657a40 (LutrisWindow at 0x563c1b020830)>}
DEBUG    2023-11-30 15:09:41,395 [application.show_window:383]:Showing window InstallerWindowtest
DEBUG    2023-11-30 15:09:41,395 [application.on_app_window_destroyed:401]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7f3ce5657a40 (LutrisWindow at 0x563c1b020830)>}
DEBUG    2023-11-30 15:09:44,786 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-30 15:12:29,166 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-11-30 15:12:38,661 [api.get_default_runner_version_info:161]:Getting runner information for wine (version: wine-ge-8-24-x86_64)
DEBUG    2023-11-30 15:12:38,661 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2023-11-30 15:12:38,895 [wine.get_installer_runner_version:783]:Default wine version is wine-ge-8-24
ERROR    2023-11-30 15:12:40,345 [exceptions.wrapper:81]:'list' object is not callable
Traceback (most recent call last):
  File "/home/user/source/lutris/lutris/exceptions.py", line 79, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/source/lutris/lutris/gui/installerwindow.py", line 561, in on_extras_ready
    if not self.load_installer_files_page():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/source/lutris/lutris/gui/installerwindow.py", line 577, in load_installer_files_page
    self.interpreter.installer.prepare_game_files(patch_version)
  File "/home/user/source/lutris/lutris/installer/installer.py", line 167, in prepare_game_files
    file.set_url(self.interpreter._substitute(file.url))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/source/lutris/lutris/installer/interpreter.py", line 460, in _substitute
    return system.substitute(template_string, self._get_string_replacements())
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/source/lutris/lutris/installer/interpreter.py", line 410, in _get_string_replacements
    current_res = self.current_resolution()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'list' object is not callable
```

### System Information

```shell
[System]
OS:              Fedora Linux 39 KDE Plasma
Arch:            x86_64
Kernel:          6.5.12-300.fc39.x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 7950X 16-Core Processor
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             124.9 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 17.0.4, DRM 3.54, 6.5.12-300.fc39.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 24.0.0-devel
OpenGL Core:     4.6 (Core Profile) Mesa 24.0.0-devel
OpenGL ES:       OpenGL ES 3.2 Mesa 24.0.0-devel
Vulkan Version:  1.3.250
Vulkan Drivers:  AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO) (1.3.267), AMD Radeon RX 6700 XT (RADV NAVI22) (1.3.267)
```

### Media (optional)

![lutirs fail](https://github.com/lutris/lutris/assets/1514297/e0fc3627-b826-4a9f-b108-b095b0fa288a)

**Comment by danieljohnson2** [comment]
Oh, that's just my clever prophylactic type-safety stuff breaking everything!

So the () on that line is trying to invoke that field as a method, but it's just a field and it all goes wrong. I just needed to remove the ().

**Comment by JooJooBee666** [comment]
That did the trick.  Thanks :+1:
