### ISSUE TITLE
Only single field to choose GOG game installation files. Install would exit with error.

### ISSUE THREAD

**Issue by junglized** [lutris/lutris#5166]
Hello.

I'm trying to install Disco Elysium. I go down the usual path: choose game from GOG to install, click install, choose version of installer, etc, until I get to choose whether to download files for the game or to choose already downloaded installer files. I choose the latter and see only one field to choose game files. I thought that I might be able to choose al of them and Lutris automagically sort them out for me. I was wrong. I tried selecting .exe or any of the .bin files, everytime ending up with failing instaltion. I also nooticed when I proceed to download files instead of choosing those aleady downloaded only the last .bin file is being downloaded. Am I doing something wrong?

here is what I have in terminal:
INFO     2023-12-03 17:11:56,895 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-03 17:11:56,897 [startup.get_drivers:57]:Using NVIDIA drivers 535.129.03 for x86_64
INFO     2023-12-03 17:11:56,897 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2023-12-03 17:11:56,897 [display.display_gpu_info:78]:GPU: 10DE:1C82 10DE:1C82 (nvidia drivers)
DEBUG    2023-12-03 17:11:57,349 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-12-03 17:11:58,644 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-12-03 17:12:18,041 [services.get_game:34]:Getting service game 1771589310 for gog
DEBUG    2023-12-03 17:12:18,201 [services.get_game:34]:Getting service game 1771589310 for gog
DEBUG    2023-12-03 17:12:18,201 [grid.on_item_activated:95]:Item activated: 1771589310
DEBUG    2023-12-03 17:12:18,202 [lutriswindow.on_game_activated:1099]:Looking up gog game 1771589310
DEBUG    2023-12-03 17:12:18,202 [services.get_game:34]:Getting service game 1771589310 for gog
DEBUG    2023-12-03 17:12:18,202 [base.install:264]:Installing 1771589310 from service gog
DEBUG    2023-12-03 17:12:18,202 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2023-12-03 17:12:18,415 [api.get_game_installers:256]:Fetching installer https://lutris.net/api/installers/disco-elysium
DEBUG    2023-12-03 17:12:18,415 [http._request:88]:GET https://lutris.net/api/installers/disco-elysium
DEBUG    2023-12-03 17:12:18,679 [application.show_window:359]:Showing window InstallerWindow1771589310
DEBUG    2023-12-03 17:12:21,380 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-12-03 17:12:44,613 [gog.get_extras:320]:Download extras for GOG ID 1771589310 and its DLCs
INFO     2023-12-03 17:12:44,613 [gog.get_game_details:286]:Getting game details for 1771589310
DEBUG    2023-12-03 17:12:44,618 [http._request:88]:GET https://api.gog.com/products/1771589310?expand=downloads&locale=en-US
INFO     2023-12-03 17:12:44,910 [gog.get_game_details:286]:Getting game details for 1771589310
DEBUG    2023-12-03 17:12:44,911 [http._request:88]:GET https://api.gog.com/products/1771589310?expand=downloads&locale=en-US
DEBUG    2023-12-03 17:12:45,067 [http._request:88]:GET https://api.gog.com/products?ids=1618612563%2C1370620137%2C1377256194&expand=downloads
INFO     2023-12-03 17:12:50,567 [installer.prepare_game_files:171]:Getting files for game
INFO     2023-12-03 17:12:50,567 [installer.prepare_game_files:173]:Adding selected extras to downloads
INFO     2023-12-03 17:12:50,567 [gog.get_game_details:286]:Getting game details for 1771589310
DEBUG    2023-12-03 17:12:50,570 [http._request:88]:GET https://api.gog.com/products/1771589310?expand=downloads&locale=en-US
INFO     2023-12-03 17:12:50,727 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1771589310/downlink/installer/en1installer0
DEBUG    2023-12-03 17:12:50,729 [http._request:88]:GET https://api.gog.com/products/1771589310/downlink/installer/en1installer0
INFO     2023-12-03 17:12:51,001 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1771589310/downlink/installer/en1installer1
DEBUG    2023-12-03 17:12:51,002 [http._request:88]:GET https://api.gog.com/products/1771589310/downlink/installer/en1installer1
INFO     2023-12-03 17:12:51,240 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1771589310/downlink/installer/en1installer2
DEBUG    2023-12-03 17:12:51,241 [http._request:88]:GET https://api.gog.com/products/1771589310/downlink/installer/en1installer2
INFO     2023-12-03 17:12:51,481 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1771589310/downlink/installer/en1installer3
DEBUG    2023-12-03 17:12:51,482 [http._request:88]:GET https://api.gog.com/products/1771589310/downlink/installer/en1installer3
DEBUG    2023-12-03 17:12:59,949 [files_box.on_file_available:108]:game is available
INFO     2023-12-03 17:12:59,949 [files_box.on_file_available:114]:All files available
INFO     2023-12-03 17:12:59,949 [installerwindow.on_files_available:631]:All files are available, continuing install
DEBUG    2023-12-03 17:12:59,956 [interpreter._iter_commands:349]:Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2023-12-03 17:13:00,020 [wine.create_prefix:99]:Creating a win64 prefix in /home/junglized/Games/Disco Elysium
DEBUG    2023-12-03 17:13:00,020 [system.execute:74]:Executing /home/junglized/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wineboot
DEBUG    2023-12-03 17:13:00,020 [system.execute:80]:WINEARCH=win64 WINEPREFIX=/home/junglized/Games/Disco Elysium WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/junglized/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/mono WINE_GECKO_CACHE_DIR=/home/junglized/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/gecko
INFO     2023-12-03 17:13:07,937 [wine.create_prefix:154]:win64 Prefix created in /home/junglized/Games/Disco Elysium
DEBUG    2023-12-03 17:13:07,960 [interpreter._iter_commands:349]:Installer command: {'task': {'args': '/SP- /NOCANCEL /SUPPRESSMSGBOXES', 'executable': 'game', 'name': 'wineexec', 'prefix': '$GAMEDIR'}}
WARNING  2023-12-03 17:13:08,121 [runner.game_config:84]:Accessing game config while runner wasn't given one.
WARNING  2023-12-03 17:13:08,121 [runner.game_config:84]:Accessing game config while runner wasn't given one.
ERROR    2023-12-03 17:13:08,121 [wine.game_exe:623]:The game doesn't have an executable
Started initial process 4269 from /home/junglized/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/junglized/.cache/lutris/installer/disco-elysium/gog/setup_disco_elysium_a0a062e7_(64bit)_(63158).exe /SP- /NOCANCEL /SUPPRESSMSGBOXES
Start monitoring process.
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: failed to open "/home/junglized/.cache/lutris/installer/disco-elysium/gog/setup_disco_elysium_a0a062e7_(64bit)_(63158).exe": c0000135
Monitored process exited.
Initial process has exited (return code: 13568)
Exit with return code 13568
DEBUG    2023-12-03 17:13:08,786 [command.on_stop:195]:Process 4263 has terminated with code 13568
DEBUG    2023-12-03 17:13:09,123 [commands._monitor_task:448]:Return code: 13568
ERROR    2023-12-03 17:13:09,123 [errors.__init__:18]:Command exited with code 13568
ERROR    2023-12-03 17:13:09,123 [exceptions.wrapper:69]:Command exited with code 13568
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 67, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 450, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 13568

Lutris version: 0.5.14
OS: Linux Mint 21.2

![image](https://github.com/lutris/lutris/assets/26525585/27003438-42bd-40e2-a4bf-df2b85676f26)

**Comment by danieljohnson2** [comment]
Ah, unexpected. I think that means you have an older GLib, but I think I can improve compatibility by using using 0 for DEFAULT_FLAGS.

I've committed that change- please re-download and try it again.

**Comment by junglized** [comment]
I've go this:

![screenshot](https://github.com/lutris/lutris/assets/26525585/ab986a67-9567-4013-b2cb-3599cdc63e71)

**Comment by strycore** [comment]
Could you give this a try after setting a path for the download cache at the start of the install?

**Comment by junglized** [comment]
> Could you give this a try after setting a path for the download cache at the start of the install?

Right. Your suggestion worked. If I set cache path game can be installed. Without cache path installer gives out an error. Another problem I encountered is that wine-ge-8-25 is not working. Installer is stuck at "wine: RLIMIT_NICE is <= 20, unable to use setpriority safely". If I use system Wine it works (but only with download cache).

**Comment by junglized** [comment]
For now I resorted to creating Wine prefix for the game manually, then installing GOG game using Wine Staging and "run exe inside wine prefix" option, then switching to Wine GE inside game config and adding GOG ID into the database. It's tedious at best, sadly, but it works.

Also I opened https://github.com/lutris/lutris/issues/5178 for WIne GE installation problems and it appears GOG installers are at fault here...

**Comment by danieljohnson2** [comment]
I'v e found I can use lutris-7.2-2-x86-64 to run installers normally, and then switch Wines after installation. Saves on data entry that way.

**Comment by strycore** [comment]
If Wine-GE does not work for installing GOG games, there is likely an issue with the runtime environment on your setup. On my side (Nobara / AMD GPU) there is no issue running  the installer. 

Try running the installer with `LUTRIS_RUNTIME=0 lutris -d` and see if it makes any difference.

**Comment by danieljohnson2** [comment]
I have this too sometimes, but not all the time, on Nobara 38/NVidia/Wayland. Not on Pop!_OS/Intel/X11.

But it won't repro for me right now. I suspect it's something about the specific NVidia driver version I'm using, and that's why it comes and goes and why you aren't seeing it.

But I don't really know.

**Comment by junglized** [comment]
@strycore 

> Try running the installer with `LUTRIS_RUNTIME=0 lutris -d` and see if it makes any difference.

It produced this (and froze at the last line so I killed it with CTRL+C):

```
INFO     2023-12-17 12:25:29,915 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-17 12:25:29,916 [startup.get_drivers:57]:Using NVIDIA drivers 535.129.03 for x86_64
INFO     2023-12-17 12:25:29,916 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2023-12-17 12:25:29,917 [display.display_gpu_info:78]:GPU: 10DE:1C82 10DE:1C82 (nvidia drivers)
DEBUG    2023-12-17 12:25:30,373 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
WARNING  2023-12-17 12:25:31,668 [runtime.__init__:221]:Runtime disabled. Safety not guaranteed.
DEBUG    2023-12-17 12:25:31,702 [lutris.get_missing_game_ids:202]:Checking for missing games
INFO     2023-12-17 12:25:49,379 [runner.use_runtime:383]:Runtime disabled by environment
INFO     2023-12-17 12:25:49,379 [runner.use_runtime:383]:Runtime disabled by environment
Started initial process 20555 from /home/----/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/----/Mounted/NAS/Games/PC/Ys Series/Ys I/setup_ys_i_2022-01-03_(52678).exe
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ioctl (GFEATURE): Input/output error

```

**Comment by strycore** [comment]
> /Mounted/NAS/Games

looks like you are pulling the game files from a NAS. 
Copy the installer to your local drive and see if it makes any difference.

**Comment by junglized** [comment]
@strycore 

stuck at:

```
INFO     2023-12-19 19:33:28,957 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-19 19:33:28,958 [startup.get_drivers:57]:Using NVIDIA drivers 535.129.03 for x86_64
INFO     2023-12-19 19:33:28,958 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2023-12-19 19:33:28,959 [display.display_gpu_info:78]:GPU: 10DE:1C82 10DE:1C82 (nvidia drivers)
DEBUG    2023-12-19 19:33:29,423 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
WARNING  2023-12-19 19:33:30,644 [runtime.__init__:221]:Runtime disabled. Safety not guaranteed.
DEBUG    2023-12-19 19:33:30,677 [lutris.get_missing_game_ids:202]:Checking for missing games
INFO     2023-12-19 19:33:42,257 [runner.use_runtime:383]:Runtime disabled by environment
INFO     2023-12-19 19:33:42,258 [runner.use_runtime:383]:Runtime disabled by environment
Started initial process 22337 from /home/----/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/----/setup_ys_i_2022-01-03_(52678).exe
Start monitoring process.
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

**Comment by strycore** [comment]
Oh gosh. 

So it's not the Lutris runtime and it's not the storage medium.

I have a very hard time not blaming Linux Mint right now. In fact, I very much know that if you were to install pretty much anything else, your GOG installer would work.

**Comment by junglized** [comment]
@strycore @danieljohnson2 Thank you very much for your time and support, gentlemen!

**As a sidenote:** it worked with earlier version of Wine GE (that was wine-ge-8-23 if I remember correctly) and with Lutris 0.5.13 but not straight away. It had similar problem initially, when Wine GE has been introduced into Lutris, but then it went away somehow. I didn't notice what made it go away unfortunately. Only after switching to wine-ge-8-24 the problem started being prevalent again. Maybe upcoming update to Linux Mint 21.3 will change the situation for the better. I don't mind installing games with Wine Staging only to switch to GE after successful install though.

**Comment by junglized** [comment]
Just for heads-up: I tried to run GOG launcher with Wine GE after updating to Mint 21.3 and it worked, with both Lutris 0.5.14 and 0.5.16. So yay! :)
