### ISSUE TITLE
Hang on startup when selected_category name includes a colon

### ISSUE THREAD

**Issue by UpYoursMicrosoft** [lutris/lutris#5176]
I searched for the word "colon" and found no results. Apologies if this is a duplicate.

Lutris remembers the category you have selected when you close it. It seems that if you make a category with a colon in the name and close Lutris with that category selected, it will hang indefinitely when you try to open it again.

It looks like the `selected_category` option is parsed by splitting the string on the colon character and it can't handle more than 2 items. Making the `selected_category` option blank in `lutris.conf` fixed it for me.

Offending `lutris.conf`:
```
[services]
lutris = False
gog = True
egs = False
ea_app = False
ubisoft = False
steam = False
dolphin = True

[lutris]
dark_theme = True
width = 790
height = 236
window_x = 805
window_y = 590
maximized = False
selected_category = user_category:Location:Gamedrive
show_advanced_options = False
library_ignores = 
migration_version = 13
view_type = grid
view_sorting = name
view_sorting_ascending = True

[list view]
name_column_width = 200
year_column_width = 60
runner_column_width = 131
platform_column_width = 120
lastplayed_column_width = 120
playtime_column_width = 100
installedat_column_width = 120
```

`lutris -d`:
```
INFO     2023-12-08 14:17:07,532 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-08 14:17:07,533 [startup.get_drivers:57]:Using NVIDIA drivers 545.29.06 for x86_64
INFO     2023-12-08 14:17:07,534 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1070
INFO     2023-12-08 14:17:07,534 [display.display_gpu_info:78]:GPU: 10DE:1B81 1458:3772 (nvidia drivers)
INFO     2023-12-08 14:17:07,534 [display.display_gpu_info:78]:GPU: 8086:3E92 1028:0859 (i915 drivers)
DEBUG    2023-12-08 14:17:07,626 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 310, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 150, in __init__
    self.sidebar.selected_category = selected_category.split(":") if selected_category else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 453, in selected_category
    selected_row_type, selected_row_id = value or ("category", "all")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 699, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

(lutris:8369): Gtk-WARNING **: 14:17:07.663: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
```
The GTK warning is unrelated. It happens on my system regardless of `lutris.conf` and everything works fine for me.

**Comment by danieljohnson2** [comment]
That seems like a job for maxsplit=1, which fixes this for me. Seems straightforward.

**Comment by UpYoursMicrosoft** [comment]
I knew it would probably be something simple. Thank you for all you do @danieljohnson2 and co. Lutris is excellent.
