### ISSUE TITLE
[Arch Linux] Ryujinx does not execute

### ISSUE THREAD

**Issue by Iron-Squid** [lutris/lutris#5185]
Expected Behavior: Ryujinx executes
Actual Behavior: Ryujinx doesn't execute

I have installed Flatpak+AUR versions of Ryujinx to ensure that my system is compatible with Ryujinx. They both executed and ran games perfectly fine. Lutris' version does not function properly.

I have launched the version of Ryujinx that Lutris packages in a terminal, it does not execute outside of Lutris either, the terminal output is identical to the following:

Here is the lutris log output from executing a game:
```Started initial process 59322 from gamemoderun /home/squid/.local/share/lutris/runners/ryujinx/publish/Ryujinx /home/squid/Games/roms/nintendoswitch/game.nsp
Start monitoring process.
00:00:00.002 |W| Application GetWindowScaleFactor: Couldn't determine monitor DPI: The type initializer for 'Gdip' threw an exception.
00:00:00.299 |W| Application Load: Unsupported configuration version 48, loading default.
00:00:00.305 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.325 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.326 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.327 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.327 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.328 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.331 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.343 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.343 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.344 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.344 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.344 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.345 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.346 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.346 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.346 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.348 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.7074
00:00:00.355 |N| Application Print: Operating System: Linux 6.6.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000 (X64)
00:00:00.355 |N| Application Print: CPU: AMD Ryzen 5 2600 Six-Core Processor ; 12 logical
00:00:00.356 |N| Application Print: RAM: Total 15936 MB ; Available 12096 MB
00:00:00.358 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.358 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.880 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder)
   at Ryujinx.Program.Main(String[] args)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder)
   at Ryujinx.Program.Main(String[] args)
Monitored process exited.
Initial process has exited (return code: 134)
All processes have quit
Exit with return code 134
```

**Comment by danieljohnson2** [comment]
I see we're running Ryujinx version 1.0.7074, which isn't quite the latest. What version do you have installed from the AUR?

Could you use the 'custom executable for the runner' option and point it a the AUR version? Does that make it work?

I suspect you are looking at a Ryujinx bug that has been fixed, but Lutris still severs the older version.

**Comment by Iron-Squid** [comment]
Version from AUR is 1.1.1098

Directing Lutris to run the Executable under `/bin/Ryujinx` (NOT `/bin/Ryujinx.sh`) allows it to run properly within Lutris.

**Comment by danieljohnson2** [comment]
I guess it's a problem with the Ryujinx version we ship, then.

**Comment by strycore** [comment]
![Screenshot_20231217_202654](https://github.com/lutris/lutris/assets/280336/b009d9c7-46be-4ea5-ba80-69b3119e9acc)

We ship a working version of Ryujinx, but there might be conflicts with some system as it may happen with any runner. 
If the Lutris provided version doesn't work, it can be uninstalled and Lutris should pick up the Flatpak version instead.

**Comment by legluondunet** [comment]
if our runner does not work, you can still use another package (Flatpak, AppImage, another binary...) using "custom executable" field in Ryujinx runner options.
