### ISSUE TITLE
Latest build failing

### ISSUE THREAD

**Issue by solarisfire** [lutris/lutris#5194]
<pre>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.11/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 245, in load_module
    return load_package(name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 217, in load_package
    return _load(spec)
           ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/solarisfire/.cache/yay/lutris-git/src/lutris/lutris/gui/dialogs/__init__.py", line 12, in <module>
    from lutris import api, settings
  File "/home/solarisfire/.cache/yay/lutris-git/src/lutris/lutris/api.py", line 17, in <module>
    from lutris.util import http, system
  File "/home/solarisfire/.cache/yay/lutris-git/src/lutris/lutris/util/http.py", line 14, in <module>
    from lutris.util import system
  File "/home/solarisfire/.cache/yay/lutris-git/src/lutris/lutris/util/system.py", line 20, in <module>
    from lutris.exceptions import MissingExecutableError
  File "/home/solarisfire/.cache/yay/lutris-git/src/lutris/lutris/exceptions.py", line 8, in <module>
    from lutris.gui.dialogs import ErrorDialog
ImportError: cannot import name 'ErrorDialog' from partially initialized module 'lutris.gui.dialogs' (most likely due to a circular import) (/home/solarisfire/.cache/yay/lutris-git/src/lutris/lutris/gui/dialogs/__init__.py)
</pre>

**Comment by strycore** [comment]
How broken is the commit I published on Flathub Beta last night? I did some quick testing and it was working ok. 
Anyway, Flathub Beta will receive frequent updates until the 0.5.15 release.

**Comment by danieljohnson2** [comment]
... not broken all?

There is a circular import, as near as I can see, but when I test Lutris I can't make it fail this way.

Not sure why not; dialogs/__init__.py imports from exceptions.py which imports from dialogs (to get ErrorDialog). That isn't kosher, is it? But it does not crash for me.

**Comment by danieljohnson2** [comment]
I've separated all that stuff into its own module; that was the fix I committed. It was the wrong place for the code, everything and its dog was importing it for no reason.
