### ISSUE TITLE
Lutris crashes on start

### ISSUE THREAD

**Issue by joaonunatings** [lutris/lutris#5202]
## Information
**OS:** Arch Linux x86_64
**Kernel:** 6.6.8-arch1-1
**Lutris:** 0.5.14-1

## Traceback
```bash
Traceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 37, in <module>
    from lutris.api import parse_installer_url, get_runners
  File "/usr/lib/python3.11/site-packages/lutris/api.py", line 18, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "/usr/lib/python3.11/site-packages/lutris/util/linux.py", line 459, in <module>
    LINUX_SYSTEM = LinuxSystem()
                   ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/linux.py", line 130, in __init__
    self.glxinfo = self.get_glxinfo()
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/linux.py", line 289, in get_glxinfo
    _glxinfo = glxinfo.GlxInfo()
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/glxinfo.py", line 23, in __init__
    self.parse()
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/glxinfo.py", line 46, in parse
    key, value = line.split(":", 1)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by danieljohnson2** [comment]
Curious. Could you run this command:
```
glxinfo -B
```
And let us know what you get? It seems like it is choking on that output.

**Comment by joaonunatings** [comment]
> Curious. Could you run this command:
> 
> ```
> glxinfo -B
> ```
> 
> And let us know what you get? It seems like it is choking on that output.

Sure, here it is:
```bash
name of display: :0
Invalid value (0) for DRI_PRIME. Should be > 0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Vega 10 Graphics (radeonsi, raven, LLVM 16.0.6, DRM 3.54, 6.6.8-arch1-1) (0x15d8)
    Version: 23.3.1
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1279 MB, largest block: 1279 MB
    VBO free aux. memory - total: 6843 MB, largest block: 6843 MB
    Texture free memory - total: 1279 MB, largest block: 1279 MB
    Texture free aux. memory - total: 6843 MB, largest block: 6843 MB
    Renderbuffer free memory - total: 1279 MB, largest block: 1279 MB
    Renderbuffer free aux. memory - total: 6843 MB, largest block: 6843 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 9011 MB
    Currently available dedicated video memory: 1279 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Vega 10 Graphics (radeonsi, raven, LLVM 16.0.6, DRM 3.54, 6.6.8-arch1-1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.3.1-arch1.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.1-arch1.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.3.1-arch1.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

Interesting line: _Invalid value (0) for DRI_PRIME. Should be > 0_
I have been getting this for multiple programs, but not sure what's the cause of this. And maybe it's unrelated to this issue.

**Comment by danieljohnson2** [comment]
Looks like you have an environmental variable set incorrectly; perhaps in some login script you have, like ~/.bashrc maybe.

I'll try to add some tolerance for this sort of thing, but the real fix it to track down that environment variable.

**Comment by danieljohnson2** [comment]
I've tweaked the code to skip this extra line.

You can try it if you like; download the latest code and run the bin/lutris script within (no need to install). Pretty sure it'll get past that crash now.

**Comment by joaonunatings** [comment]
> Looks like you have an environmental variable set incorrectly; perhaps in some login script you have, like ~/.bashrc maybe.
> 
> I'll try to add some tolerance for this sort of thing, but the real fix it to track down that environment variable.

I tracked back to _~/.bash_profile_, I was setting _DRI_PRIME=0_ there for some reason. Thank you for your help :+1:
