### ISSUE TITLE
EA App login page showing in a foreign language compared to the system one

### ISSUE THREAD

**Issue by Deewens** [lutris/lutris#5205]
Hello,

New Lutris user here. I  installed the EA App launcher, but when connecting my EA account to add my game library to Lutris, the sign in page is in a foreign language (compared to my distro language which is English). Looks like Arabic or something alike, I am not sure, sorry ^^ !

I do not think this is an expected behaviour, at least on a system not configured in this language.

![image](https://github.com/lutris/lutris/assets/26287270/6b4bc95c-0775-4e28-841f-6af1700951b4)

Thanks :) !

**Comment by strycore** [comment]
Well that an interesting and completely new one.
Can you post the output of the console output when running `lutris -d` ?

**Comment by Deewens** [comment]
So, I ran `lutris -d` and then started the login process again. This is the output of de debug from start to connection (Btw, login is working, the UI is just in another language).
```
INFO     2023-12-28 20:11:30,087 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-28 20:11:30,088 [startup.get_drivers:57]:Using NVIDIA drivers 545.29.06 for x86_64
INFO     2023-12-28 20:11:30,089 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1660 Ti
INFO     2023-12-28 20:11:30,089 [display.display_gpu_info:78]:GPU: 10DE:2191 1028:08EA (nvidia drivers)
INFO     2023-12-28 20:11:30,089 [display.display_gpu_info:78]:GPU: 8086:3E9B 1028:08EA (i915 drivers)
DEBUG    2023-12-28 20:11:33,080 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-12-28 20:11:35,550 [base.login:359]:Connecting to EA App
DEBUG    2023-12-28 20:12:15,615 [base.wipe_game_cache:370]:Deleting ea_app cache /home/deewens/.cache/lutris/ea_app/cache/
DEBUG    2023-12-28 20:12:15,615 [base.wipe_game_cache:175]:Deleting games from service-games for ea_app
INFO     2023-12-28 20:12:19,654 [ea_app.load:260]:Retrieved 14 games from EA library
DEBUG    2023-12-28 20:12:19,654 [services.get_game:34]:Getting service game 1026023 for ea_app
DEBUG    2023-12-28 20:12:19,661 [services.get_game:34]:Getting service game 198196 for ea_app
DEBUG    2023-12-28 20:12:19,664 [services.get_game:34]:Getting service game 1003943 for ea_app
DEBUG    2023-12-28 20:12:19,667 [services.get_game:34]:Getting service game 195133 for ea_app
DEBUG    2023-12-28 20:12:19,671 [services.get_game:34]:Getting service game 71715_pc for ea_app
DEBUG    2023-12-28 20:12:19,674 [services.get_game:34]:Getting service game 198281 for ea_app
DEBUG    2023-12-28 20:12:19,677 [services.get_game:34]:Getting service game 1005288 for ea_app
DEBUG    2023-12-28 20:12:19,680 [services.get_game:34]:Getting service game 196216 for ea_app
DEBUG    2023-12-28 20:12:19,683 [services.get_game:34]:Getting service game 16274527 for ea_app
DEBUG    2023-12-28 20:12:19,686 [services.get_game:34]:Getting service game 1005288 for ea_app
DEBUG    2023-12-28 20:12:19,689 [services.get_game:34]:Getting service game 1035052 for ea_app
DEBUG    2023-12-28 20:12:19,692 [services.get_game:34]:Getting service game 16274525 for ea_app
DEBUG    2023-12-28 20:12:19,694 [services.get_game:34]:Getting service game 196485 for ea_app
DEBUG    2023-12-28 20:12:19,697 [services.get_game:34]:Getting service game 196787 for ea_app
DEBUG    2023-12-28 20:12:19,710 [ea_app.add_installed_games:320]:Installed 0 EA games
```

**Comment by strycore** [comment]
Ok so the logs don't tell us anything interesting... What's the locale of your OS?

**Comment by Deewens** [comment]
Locale is English (Ireland). See below:
![image](https://github.com/lutris/lutris/assets/26287270/b2f01bae-1ce7-4f02-96b4-638ee46cf6ea)

**Comment by Deewens** [comment]
For information, I switched from Pop!_OS to Fedora due to other issues I had using other distros, and now, the EA App UI language is back to English. I have no idea why it didn't on Pop!_OS though.

**Comment by Deewens** [comment]
Nevermind, the UI for installing EA App is in English, but the UI to connect and link my EA accoutn with Lutris is in this arabic-_like_ language.

**Comment by danieljohnson2** [comment]
It seems to me that if you are still seeing that on a new OS install, it must be a setting kept on EA's servers that is doing this.

**Comment by strycore** [comment]
Could you try to launch lutris with locale C or en_US.UTF-8 and see if it makes any difference?

**Comment by francisjavi** [comment]
It happens the same to me

**Comment by strycore** [comment]
> It happens the same to me

well yeah ok, and there's not much we can do about it if you don't tell us your system's locale and other details that might be useful.

**Comment by francisjavi** [comment]
My only intention was to express that it is a recurring problem, nothing more. But yes, in fact I failed to say that it happens to me on a Steam Deck (LANG=es).

**Comment by strycore** [comment]
oh, on the Steam Deck. That means Flatpak is also affected.

**Comment by Deewens** [comment]
> Could you try to launch lutris with locale C or en_US.UTF-8 and see if it makes any difference?

sorry I haven't been able to do it. I'll try this week and let you know what happened.

One thing to note, however, is that I have Nobara Linux on my other PC and it did not happen. So maybe it fixed itself in one of last updates.

**Comment by Caedorus** [comment]
![image](https://github.com/user-attachments/assets/1586ae65-b5a8-4a35-b431-9fea88c80536)
I have this issue too, it is very frustrating. Interestingly, if I try to launch the EA app as a game from the library, it tells me the executable can't be found.

I have confirmed the language is Arabic using an image text translator.

Using lutris -d, I saw this error while installing:

```
ERROR    2024-09-29 11:18:14,182 [jobs.target:32]:Error while completing task <bound method InstallerWindow.create_shortcut of <installerwindow.InstallerWindow object at 0x7d8728a01700 (lutris+gui+installerwindow+InstallerWindow at 0x6154e77d5960)>>: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '/home/user/.cache/lutris/net.lutris.ea-app-27.desktop'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 916, in create_shortcut
    xdgshortcuts.create_launcher(game_slug, game_id, game_name, menu=True)
  File "/usr/lib/python3/dist-packages/lutris/util/xdgshortcuts.py", line 101, in create_launcher
    os.remove(tmp_launcher_path)
```
While trying to start the EA App as a game, I saw this:

```
ERROR    2024-09-29 11:20:07,905 [exception_backstops.wrapper:36]:EA App (wine) has encountered an error: The file /home/robrecht/Games/ea-app/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe could not be found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 31, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 668, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 607, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 1202, in play
    raise MissingGameExecutableError(filename=game_exe)
lutris.exceptions.MissingGameExecutableError: The file /home/robrecht/Games/ea-app/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe could not be found
```
And finally, starting the EA App login from the sidebar gives only this line:

`DEBUG    2024-09-29 11:21:48,693 [base.login:430]:Connecting to EA App`

Any help is appreciated!

**Comment by Caedorus** [comment]
Update: Downloaded the .exe from the EA webpage, then I tried to "install a game from an executable". Got this:

```
libc++abi: terminating due to uncaught exception of type std::bad_alloc: std::bad_alloc
Monitored process exited.
Initial process has exited (return code: 768)
Exit with return code 768
DEBUG    2024-09-29 11:24:43,355 [monitored_command.on_stop:228]:Process 41010 has terminated with code 768
DEBUG    2024-09-29 11:24:44,035 [commands._monitor_task:444]:Return code: 768
ERROR    2024-09-29 11:24:44,036 [errors.__init__:19]:Command exited with code 768
ERROR    2024-09-29 11:24:44,036 [exception_backstops.error_wrapper:110]:Error handling timeout function: Command exited with code 768
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 446, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 768
```

**Comment by Caedorus** [comment]
> Ok so the logs don't tell us anything interesting... What's the locale of your OS?

   System Locale: LANG=en_IE.UTF-8
                  LANGUAGE=en_IE:en
       VC Keymap: n/a
      X11 Layout: be
       X11 Model: pc105

**Comment by sio-k** [comment]
I've reproduced the error as pictured (arabic text).
```sh
LANGUAGE=
LC_ADDRESS=en_DK.UTF-8
LC_NAME=en_DK.UTF-8
LC_MONETARY=en_DK.UTF-8
LANG=en_DK.UTF-8
LC_PAPER=en_DK.UTF-8
LC_IDENTIFICATION=en_DK.UTF-8
LC_TELEPHONE=en_DK.UTF-8
LC_MEASUREMENT=en_DK.UTF-8
LC_TIME=en_SE.UTF-8
LC_NUMERIC=en_DK.UTF-8
```

Launching Lutris using `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 lutris` fixed the issue.

This is presumably caused by something somewhere along the way not knowing what to do with most locales and reverting to a default as a result, so for a fix I'd suggest just setting `LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8` for that login window if user locale begins with `en_`.

**Comment by Caedorus** [comment]
> I've reproduced the error as pictured (arabic text).
> 
> ```shell
> LANGUAGE=
> LC_ADDRESS=en_DK.UTF-8
> LC_NAME=en_DK.UTF-8
> LC_MONETARY=en_DK.UTF-8
> LANG=en_DK.UTF-8
> LC_PAPER=en_DK.UTF-8
> LC_IDENTIFICATION=en_DK.UTF-8
> LC_TELEPHONE=en_DK.UTF-8
> LC_MEASUREMENT=en_DK.UTF-8
> LC_TIME=en_SE.UTF-8
> LC_NUMERIC=en_DK.UTF-8
> ```
> 
> Launching Lutris using `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 lutris` fixed the issue.
> 
> This is presumably caused by something somewhere along the way not knowing what to do with most locales and reverting to a default as a result, so for a fix I'd suggest just setting `LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8` for that login window if user locale begins with `en_`.

Wouldn't that only fix it for English users though?

**Comment by LoKolbasz** [comment]
For me only LA

> I've reproduced the error as pictured (arabic text).
> 
> LANGUAGE=
> LC_ADDRESS=en_DK.UTF-8
> LC_NAME=en_DK.UTF-8
> LC_MONETARY=en_DK.UTF-8
> LANG=en_DK.UTF-8
> LC_PAPER=en_DK.UTF-8
> LC_IDENTIFICATION=en_DK.UTF-8
> LC_TELEPHONE=en_DK.UTF-8
> LC_MEASUREMENT=en_DK.UTF-8
> LC_TIME=en_SE.UTF-8
> LC_NUMERIC=en_DK.UTF-8
> Launching Lutris using `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 lutris` fixed the issue.
> 
> This is presumably caused by something somewhere along the way not knowing what to do with most locales and reverting to a default as a result, so for a fix I'd suggest just setting `LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8` for that login window if user locale begins with `en_`.

For me only `LANG=en_US.UTF-8` was needed. `LC_ALL` overwrites every locale variable, but it looks like `LANG` is the one causing issues.

**Comment by LoKolbasz** [comment]
Changing the locals in [lutris/services/ea_app.py](https://github.com/lutris/lutris/blob/master/lutris/services/ea_app.py) does not seem to fix it. The ea app login page probably tries to load it from somewhere else.
