### ISSUE TITLE
Failed to retrieve wine information when wine version not installed

### ISSUE THREAD

**Issue by DocKDE** [lutris/lutris#5310]
I was trying to install a game with a custom install script. After clicking "Continue" in the dialog for choosing the installation location I get this error popup: `Failed to retrieve wine (None) information`. 

Here is the stack trace:
```
➜ flatpak run net.lutris.Lutris -d
2024-02-13 09:43:00,678: Command 'fluidsynth' not found on your system
INFO     2024-02-13 09:43:01,146 [application.do_command_line:479]:Starting Lutris 0.5.16
INFO     2024-02-13 09:43:01,147 [startup.get_drivers:67]:Running Intel Mesa driver 23.3.4 on Mesa Intel(R) Graphics (ADL GT2) (0x46a6)
INFO     2024-02-13 09:43:01,148 [display.display_gpu_info:78]:GPU: 8086:46A6 1D05:1171 (i915 drivers)
DEBUG    2024-02-13 09:43:01,506 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2024-02-13 09:43:03,229 [application.show_window:392]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7f2276029fc0 (LutrisWindow at 0x55f73a83c4a0)>}
DEBUG    2024-02-13 09:43:10,543 [__init__.read_script:23]:Loading script(s) from /home/benedikt/Code/gothic/balancing.yaml
DEBUG    2024-02-13 09:43:10,609 [application.show_window:392]:Showing window InstallerWindowgothic
DEBUG    2024-02-13 09:43:10,610 [application.on_app_window_destroyed:419]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7f2276029fc0 (LutrisWindow at 0x55f73a83c4a0)>}
DEBUG    2024-02-13 09:43:11,839 [displayconfig.get_current_resolution:643]:Retrieving current resolution
INFO     2024-02-13 09:43:12,778 [api.get_default_runner_version_info:204]:Getting runner information for wine (version: wine-ge-8-25-x86_64)
DEBUG    2024-02-13 09:43:12,779 [http._request:88]:GET https://lutris.net/api/runners/wine
INFO     2024-02-13 09:43:12,887 [interpreter.get_runners_to_install:257]:Runner <lutris.runners.wine.wine object at 0x7f22764421d0> needs to be installed
DEBUG    2024-02-13 09:43:12,888 [interpreter.install_runner:276]:Installing wine
DEBUG    2024-02-13 09:43:12,888 [runner.install:469]:Installing wine (version=None, callback=<function ScriptInterpreter.install_runner.<locals>.install_more_runners at 0x7f22764598a0>)
INFO     2024-02-13 09:43:12,888 [api.get_default_runner_version_info:204]:Getting runner information for wine (version: wine-ge-8-25-x86_64)
DEBUG    2024-02-13 09:43:12,888 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2024-02-13 09:43:12,992 [interpreter.install_runner:284]:Failed to retrieve wine (None) information
ERROR    2024-02-13 09:43:12,992 [errors.__init__:18]:Failed to retrieve wine (None) information
ERROR    2024-02-13 09:43:12,993 [exception_backstops.error_wrapper:81]:Error handling idle function: Failed to retrieve wine (None) information
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 278, in install_runner
    runner.install(
  File "/app/lib/python3.11/site-packages/lutris/runners/runner.py", line 481, in install
    raise RunnerInstallationError(_("Failed to retrieve {} ({}) information").format(self.name, version))
lutris.runners.RunnerInstallationError: Failed to retrieve wine (None) information

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 444, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 211, in launch_install
    self.install_runners(ui_delegate)
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 265, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 285, in install_runner
    raise ScriptingError(ex.message) from ex
lutris.installer.errors.ScriptingError: Failed to retrieve wine (None) information
```
I'm assuming this is due to the fact that the wine version that Lutris tried to get information about (see `INFO     2024-02-13 09:43:12,888 [api.get_default_runner_version_info:204]:Getting runner information for wine (version: wine-ge-8-25-x86_64)`) does not exist anymore but I don't know why it would try to retrieve that info at all because the global wine version was set to the system default. 
After changing the global wine version to a Wine-GE version that is actually installed this error does not appear anymore but the UX at this point is suboptimal IMHO.

**Comment by danieljohnson2** [comment]
I've had this happen to me; it turned out to be that the ``versions.json`` file was out of date, but hadn't yet updated. It eventually does, but in the meantime it is broken.

I've already done a fix for this in master so that it will just use the out-of-date ``versions.json`` data, and not care that the server disagrees until it gets updated.

You can delete ``~/.cache/lutris/versions.json`` (and restart Lutris) to force an immediate update- that should clear this up.

If that works for you, or if this has just gone away anyway, then I think that means it was a stale ``versions.json``, and we can close this as already fixed.

**Comment by DocKDE** [comment]
Sounds good to me. Glad that this doesn't add more work for anyone, then :)
