### ISSUE TITLE
Installing Epic Games Store attempts to download old an wine runner

### ISSUE THREAD

**Issue by ojsl1** [lutris/lutris#5318]
The epic-games-store installer seems to be broken for me on `lutris-git:0.5.16.r154.g32ec71116-1`. In below log line 4 it's apparently fetching `lutris-GE-Proton8-12`, but the runner downloaded into my system is instead: `~/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/` as it should, as that is what I have as the default Wine runner in preferences. However, few lines later the executable `~/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine` is not being found. Is some cache not being invalidated correctly here?

To start the installer I'm just pressing connect and following the prompts, i get a popup that says it's installing `wine-ge-8-26-x86_64`, but later on during installation it fails.

I'm also not sure where the reported `winetricks-20230212-next` is being read from, as my system has the newest 20240105.

After the installer stops with the line:  "Command exited with code 256", it won't let me close/abort the installer, trying to press the Abort button produces the below trace each time it's pressed, forcing me to quit lutris completely.

<details>
  <summary>System information</summary>

 ```
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Manjaro Linux 23.1.3 Vulcan
Arch: x86_64
Kernel: 6.8.0-1-MANJARO
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5800X3D 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 78.5 GB
Swap: 0.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 16.0.6, DRM 3.57, 6.8.0-1-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.0-devel (git-60cf1ede4f)
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.0-devel (git-60cf1ede4f)
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.0-devel (git-60cf1ede4f)
Vulkan Version: 1.3.276
Vulkan Drivers: AMD Radeon RX 7900 XTX (RADV NAVI31) (1.3.278)
```
  
</details>
<details>
  <summary>System Wine information</summary>

 ```
$ winetricks --version
20240105 - sha256sum: 8f28985b06e9e04b5268e2aef3429b2a0f6abd4fd12c4a30472dfe66355128fa

$ wine --version
wine-8.21 (Staging)
```
  
</details>

```
$ lutris
2024-02-20 22:57:03,694: Starting Lutris 0.5.16
2024-02-20 22:57:03,773: AMD Radeon RX 7900 XTX (1002:744C 1DA2:471E amdgpu) Driver 24.1.0
2024-02-20 22:57:21,163: Runner <lutris.runners.wine.wine object at 0x710b95615d90> needs to be installed
2024-02-20 22:57:21,171: Getting runner information for wine (version: lutris-GE-Proton8-12)
2024-02-20 22:58:35,216: Download completed
2024-02-20 22:59:06,754: Download completed
2024-02-20 22:59:06,754: All files available
2024-02-20 22:59:06,754: All files are available, continuing install
2024-02-20 22:59:06,754: Launching installer commands
2024-02-20 22:59:06,820: Creating a win64 prefix in /home/saukko/Games/epic-games-store
2024-02-20 22:59:06,820: Winepath: /home/saukko/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine
2024-02-20 22:59:06,820: No wineboot executable found in /home/saukko/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine, your wine installation is most likely broken
2024-02-20 22:59:06,925: Creating a win64 prefix in /home/saukko/Games/epic-games-store
2024-02-20 22:59:06,925: Winepath: /home/saukko/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine
2024-02-20 22:59:06,925: No wineboot executable found in /home/saukko/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine, your wine installation is most likely broken
2024-02-20 22:59:06,948: No valid prefix detected in /home/saukko/Games/epic-games-store, creating one...
2024-02-20 22:59:06,950: Creating a win64 prefix in /home/saukko/Games/epic-games-store
2024-02-20 22:59:06,950: Winepath: /usr/bin/wine
2024-02-20 22:59:36,693: win64 Prefix created in /home/saukko/Games/epic-games-store
lutris-wrapper: /home/saukko/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 653733 from /home/saukko/.local/share/lutris/runtime/winetricks/winetricks --unattended corefonts
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20230212-next, latest upstream is winetricks-20240105!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: WINE is /home/saukko/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine, which is neither on the path nor an executable file
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2024-02-20 22:59:37,792: Command exited with code 256
2024-02-20 22:59:37,792: Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 109, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 443, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```

```
2024-02-20 23:00:31,161: Cancelling installation of Epic Games Store
2024-02-20 23:00:31,216: No executable found in ['/home/saukko/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wineserver', '-k']
2024-02-20 23:00:31,216: Error handling signal 'clicked': not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 109, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 250, in on_cancel_clicked
    self.interpreter.revert(remove_game_dir=remove_checkbox.get_active())
  File "/usr/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 399, in revert
    self.task({"name": "winekill"})
  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 429, in task
    command = task(**data)
              ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/commands/wine.py", line 185, in winekill
    system.execute(command, env=env, quiet=True)
  File "/usr/lib/python3.11/site-packages/lutris/util/system.py", line 57, in execute
    stdout, _stderr = _execute(command, env=env, cwd=cwd, quiet=quiet, shell=shell, timeout=timeout)
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
2024-02-20 23:05:55,248: Shutting down Lutris
```

**Comment by ojsl1** [comment]
I was able to somehow fix it myself by manually changing the default wine version around, i can't recall the exact steps i did though. Just thought I'd post this here for reference.
