### ISSUE TITLE
Missing 'ulwgl-run' dependency

### ISSUE THREAD

**Issue by PrimaIVoid** [lutris/lutris#5333]
Last working commit for me: `35e29e657cdbb0b50c18925081f296e4fa825e6a`

Recent commits give me this error when trying to launch any game or app:

```
Traceback (most recent call last):

  File "/home/user/lutris/lutris/exception_backstops.py", line 31, in wrapper
    result = function(*args, **kwargs)

  File "/home/user/lutris/lutris/game.py", line 673, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)

  File "/home/user/lutris/lutris/game.py", line 620, in get_gameplay_info
    gameplay_info = self.runner.play()

  File "/home/user/lutris/lutris/runners/wine.py", line 1205, in play
    command = self.get_command()

  File "/home/user/lutris/lutris/runners/wine.py", line 1175, in get_command
    ulwgl_path = system.find_executable("ulwgl-run")

  File "/home/user/lutris/lutris/util/system.py", line 229, in find_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % exec_name)

lutris.exceptions.MissingExecutableError: The executable 'ulwgl-run' could not be found.
```

This is probably due to a new required dependecy from Lutris core that lacks on my system

**Comment by strycore** [comment]
It is not a required dependency (unless you want to use Proton). The code has been updated to not fail when it is not present.
