### ISSUE TITLE
Can't use Epic login

### ISSUE THREAD

**Issue by Tear4Pixelation** [lutris/lutris#5361]
My Os: Kubuntu 22.4
I installed lutris via `apt-get`
When I click the button for epic login, nothing happens.
This is the error I get:
```
2024-03-17 19:57:33,693: Startup complete
2024-03-17 19:57:33,695: Using NVIDIA drivers 545.23.08 for x86_64
2024-03-17 19:57:33,695: GPU: NVIDIA GeForce GTX 1080
2024-03-17 19:57:33,695: GPU: 10DE:1B80 1462:3367 (nvidia drivers)

** (lutris:87337): CRITICAL **: 19:57:37.576: WebKitNetworkProxySettings* webkit_network_proxy_settings_new(const char*, const char* const*): assertion 'URL(String::fromUTF8(defaultProxyURI)).isValid()' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 171, in on_connect_clicked
    self.service.login()
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 254, in login
    dialog = WebConnectDialog(self, parent)
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/webconnect_dialog.py", line 19, in __init__
    proxy = WebKit2.NetworkProxySettings.new(os.environ["http_proxy"])
TypeError: constructor returned NULL
```
If you need any more info, please ask and I will provide it if I can.

Any help greatly appreciated!

**Comment by strycore** [comment]
What's your proxy situation?

**Comment by Tear4Pixelation** [comment]
> What's your proxy situation?

Uhh I am sorry but I don’t know what that means, sorry. Can you explain what you want from me in a bit more detail?

**Comment by strycore** [comment]
Lutris is throwing an error when trying to setup the proxy. Usually people don't use one so this does nothing but in your case it crashes. 


What's your internet situation? Who is your provider? Is your government doing weird things with your internet? Etc....
