### ISSUE TITLE
The key 'appid' could not be found (Flatpak)

### ISSUE THREAD

**Issue by FilBot3** [lutris/lutris#5370]
I attempted to start an application I had installed in Lutris on 2024-03-19, and was presented with the error:

![image](https://github.com/lutris/lutris/assets/3039509/d66ab5e0-3ffb-4fef-a561-f50a78abe26b)

```
The key 'appid' is missing
```

and another time

```
The key 'appid' could not be found
```

When I launched Lutris via the command-line via flatpak, this is the error I received.

```bash
➜  ~ 
> flatpak run net.lutris.Lutris 
2024-03-21 08:04:26,773: Command 'fluidsynth' not found on your system
Gtk-Message: 08:04:27.013: Failed to load module "canberra-gtk-module"
2024-03-21 08:04:27,159: Starting Lutris 0.5.17
MESA: error: Use of VkSurfacePresentModeCompatibilityEXT without a VkSurfacePresentModeEXT set. This is an application bug.
2024-03-21 08:04:27,196: AMD Radeon RX 6700 XT (1002:73DF 1462:3980 amdgpu) Driver 24.0.3
2024-03-21 08:04:27,441: Error while completing task <bound method LutrisWindow.get_games_from_filters of <lutriswindow.LutrisWindow object at 0x7fdc5014d180 (LutrisWindow at 0x556287398ca0)>>: <class 'KeyError'> 'appid'
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 477, in get_games_from_filters
    games = [game for game in games if game["id"] in category_game_ids and self.game_matches(game)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 477, in <listcomp>
    games = [game for game in games if game["id"] in category_game_ids and self.game_matches(game)]
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 416, in game_matches
    if game["appid"] not in games_db.get_service_games(self.service.id):
       ~~~~^^^^^^^^^
2024-03-21 08:04:27,474: Error handling idle function: 'appid'
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 57, in discarding_result
    function(*args, **kwargs)
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 572, in on_games_ready
    raise error  # bounce any error against the backstop
    ^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 477, in get_games_from_filters
    games = [game for game in games if game["id"] in category_game_ids and self.game_matches(game)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 477, in <listcomp>
    games = [game for game in games if game["id"] in category_game_ids and self.game_matches(game)]
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 416, in game_matches
    if game["appid"] not in games_db.get_service_games(self.service.id):
       ~~~~^^^^^^^^^
KeyError: 'appid'
```

Flatpak information

```bash
➜  ~ 
> flatpak info net.lutris.Lutris        

Lutris Team - Video game preservation platform

          ID: net.lutris.Lutris
         Ref: app/net.lutris.Lutris/x86_64/beta
        Arch: x86_64
      Branch: beta
     Version: 0.5.16
     License: GPL-3.0-or-later
      Origin: flathub-user-beta
  Collection: org.flathub.Beta
Installation: user
   Installed: 971.5 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: b364d2e2c4432ea3e9aaf64fb2ab55d7eb8a02797ee0a1754362cfb0629750dd
      Parent: 9a4dfaaf27a65de27ef6ffcdfc532614e660d44f23774767b2c60882d0189a98
     Subject: Update to latest commit (8009d5c9)
        Date: 2024-03-19 04:27:38 +0000

➜  ~ 
> flatpak info --show-permissions net.lutris.Lutris
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;
devices=all;
features=devel;multiarch;
filesystems=home;/media;/run/media;~/.config/MangoHud:ro;xdg-run/gamescope-0:ro;~/.var/app/com.valvesoftware.Steam:ro;~/Games;

[Session Bus Policy]
org.gnome.Mutter.DisplayConfig=talk
org.kde.StatusNotifierWatcher=talk
org.freedesktop.ScreenSaver=talk
org.freedesktop.Flatpak=talk

[System Bus Policy]
org.freedesktop.UDisks2=talk

[Environment]
LUTRIS_ENABLE_PROTON=1
LD_LIBRARY_PATH=/usr/lib/extensions/vulkan/gamescope/lib
GST_PLUGIN_SYSTEM_PATH=/app/lib32/gstreamer-1.0:/app/lib/gstreamer-1.0:/usr/lib/i386-linux-gnu/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
PATH=/app/bin:/usr/bin:/app/utils/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/app/jre/bin/:/usr/lib/extensions/vulkan/gamescope/bin
APPIMAGE_EXTRACT_AND_RUN=1
WEBKIT_DISABLE_DMABUF_RENDERER=1
```

**Comment by danieljohnson2** [comment]
This looks *very* much like #5366 which unfortunately seems to have made it to the Flatpak beta; it is already fixed in the master.

If so, you can turn off 'Installed games only"? That should alleviate the symptom.

Though this seems like bad timing; I think the bug was in master for less than a day, but it must have been just the wrong day.

**Comment by strycore** [comment]
Bugs in the version shipped in Flathub Beta are to be expected.
