### ISSUE TITLE
Lutris not starting.

### ISSUE THREAD

**Issue by MizxGaming** [lutris/lutris#5381]
**Expected behaviour:**
Lutris GUI open up to manage and play games

**Current Behaviour:**
Nothing starts and running it from the command line gives this error

**Steps to reproduce:**
Open lutris from the icon on the application list or desktop or run `lutris -d` in terminal

**System information:**
System:
Kernel: 6.8.1-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
clocksource: tsc avail: hpet,acpi_pm
parameters: BOOT_IMAGE=/@/boot/vmlinuz-linux-zen
root=UUID=336b5c23-1f7f-41e1-8933-dd698d69d080 rw rootflags=subvol=@
quiet resume=UUID=a567939b-2896-417d-bf09-00f98f8b3e82 loglevel=3 ibt=off
Desktop: KDE Plasma v: 6.0.2 tk: Qt v: N/A info: frameworks v: 6.0.0
wm: kwin_wayland with: krunner vt: 1 dm: SDDM Distro: Garuda
base: Arch Linux
Machine:
Type: Desktop Mobo: N/A model: ZRD1105 v: REV V52.9
serial: <superuser required> uuid: <superuser required>
UEFI: American Megatrends v: 5.12 date: 02/15/2023
CPU:
Info: model: Intel Core i3-7100 bits: 64 type: MT MCP arch: Kaby Lake
gen: core 7 level: v3 note: check built: 2018 process: Intel 14nm family: 6
model-id: 0x9E (158) stepping: 9 microcode: 0xF8
Topology: cpus: 1x cores: 2 tpc: 2 threads: 4 smt: enabled cache:
L1: 128 KiB desc: d-2x32 KiB; i-2x32 KiB L2: 512 KiB desc: 2x256 KiB
L3: 3 MiB desc: 1x3 MiB
Speed (MHz): avg: 800 min/max: 800/3900 scaling: driver: intel_pstate
governor: powersave cores: 1: 800 2: 800 3: 800 4: 800 bogomips: 31199
Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Vulnerabilities: <filter>
Graphics:
Device-1: Intel HD Graphics 630 driver: i915 v: kernel arch: Gen-9.5
process: Intel 14nm built: 2016-20 ports: active: DP-1
empty: HDMI-A-1,HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:5912 class-ID: 0300
Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4
compositor: kwin_wayland driver: X: loaded: modesetting
alternate: fbdev,intel,vesa dri: iris gpu: i915 display-ID: 0
Monitor-1: DP-1 res: 1366x768 size: N/A modes: N/A
API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris
device: 1 drv: swrast surfaceless: drv: iris wayland: drv: iris x11:
drv: iris inactive: gbm
API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.0.3-arch1.2
glx-v: 1.4 direct-render: yes renderer: Mesa Intel HD Graphics 630 (KBL GT2)
device-ID: 8086:5912 memory: 7.5 GiB unified: yes display-ID: :1.0
API: Vulkan v: 1.3.279 layers: 13 device: 0 type: integrated-gpu
name: Intel HD Graphics 630 (KBL GT2) driver: mesa intel v: 24.0.3-arch1.2
device-ID: 8086:5912 surfaces: xcb,xlib,wayland device: 1 type: cpu
name: llvmpipe (LLVM 17.0.6 256 bits) driver: mesa llvmpipe
v: 24.0.3-arch1.2 (LLVM 17.0.6) device-ID: 10005:0000
surfaces: xcb,xlib,wayland
Info:
Memory: total: 8 GiB available: 7.68 GiB used: 2.94 GiB (38.2%)
Processes: 227 Power: uptime: 25m states: freeze,mem,disk suspend: s2idle
wakeups: 0 hibernate: platform avail: shutdown, reboot, suspend, test_resume
image: 3.06 GiB services: org_kde_powerdevil, power-profiles-daemon,
upowerd Init: systemd v: 255 default: graphical tool: systemctl
Packages: pm: pacman pkgs: 1941 libs: 563 tools: octopi,pamac,paru,yay
Compilers: clang: 17.0.6 gcc: 13.2.1 Shell: garuda-inxi default: fish
v: 3.7.0 running-in: konsole inxi: 3.3.33
Garuda (2.6.23-1):
System install date:     2024-03-24
Last full system update: 2024-03-25 ↻
Is partially upgraded:   No
Relevant software:       snapper NetworkManager dracut
Windows dual boot:       Probably (Run as root to verify)
Failed units:

**Output of `lutris -d`:**

lutris -d
2024-03-25 18:15:45,459: Unable to run command, qdbus not found
INFO     2024-03-25 18:15:45,694 [application.do_command_line:479]:Starting Lutris 0.5.16
INFO     2024-03-25 18:15:45,696 [startup.get_drivers:67]:Running Intel Mesa driver 24.0.3 on Mesa Intel(R) HDGraphics 630 (KBL GT2) (0x5912)
INFO     2024-03-25 18:15:45,696 [display.display_gpu_info:78]:GPU: 8086:5912 8086:2212 (i915 drivers)
DEBUG    2024-03-25 18:15:45,938 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 347, in do_activate
self.window = LutrisWindow(application=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 129, in __init__
self.sidebar.initialize_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
self.update_rows()
File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 549, in update_rows
service = service_class()
^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/lutris/services/egs.py", line 183, in __init__
self.session_data = json.loads(token_file.read())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 773, in do_command_line
self.window.present()
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

**Comment by strycore** [comment]
Delete your corrupted EGS token file in .cache/lutris and lutris will start
