### ISSUE TITLE
Lutris crash on startup

### ISSUE THREAD

**Issue by Fxzzi** [lutris/lutris#5383]
Just performed one a system update - upon launching lutris again after a reboot I'm treated to this error message:

```python
Traceback (most recent call last):
  File "/usr/bin/lutris", line 58, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 35, in <module>
    from gi.repository import Gio, GLib, Gtk, GObject
  File "/usr/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gio, introspection typelib not found
```

This is caused by the system update, as reverting it and Lutris can then launch again successfully. Here's what was upgraded:

```
[2024-03-24T02:16:10+0000] [ALPM] upgraded glib2 (2.78.4-1.1 -> 2.80.0-2)
[2024-03-24T02:16:29+0000] [ALPM] upgraded util-linux (2.39.3-2.1 -> 2.40rc2-1)
[2024-03-24T02:16:31+0000] [ALPM] upgraded util-linux-libs (2.39.3-2.1 -> 2.40rc2-1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded adwaita-cursors (45.0-1 -> 46.0-1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded util-linux-libs (2.40rc2-1 -> 2.40rc2-1.1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded libsysprof-capture (45.2-1.1 -> 46.0-1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded librsvg (2:2.57.3-1.1 -> 2:2.58.0-1.1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded gtk-update-icon-cache (1:4.12.5-1.1 -> 1:4.14.1-1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded adwaita-icon-theme (45.0-1 -> 46.0-1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded alsa-card-profiles (1:1.0.4-1.1 -> 1:1.0.4-2)
[2024-03-24T16:24:30+0000] [ALPM] upgraded gsettings-desktop-schemas (45.0-1 -> 46.0-1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded util-linux (2.40rc2-1 -> 2.40rc2-1.1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded at-spi2-core (2.50.2-1 -> 2.52.0-1.1)
[2024-03-24T16:24:30+0000] [ALPM] upgraded gstreamer (1.24.1-1.1 -> 1.24.1-2)
[2024-03-24T16:24:30+0000] [ALPM] upgraded gst-plugins-base-libs (1.24.1-1.1 -> 1.24.1-2)
[2024-03-24T16:24:30+0000] [ALPM] upgraded glib-networking (1:2.78.1-1.1 -> 1:2.80.0-1.1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gst-plugins-bad-libs (1.24.1-1.1 -> 1.24.1-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded tracker3 (3.6.0-3.1 -> 3.7.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gtk4 (1:4.12.5-1.1 -> 1:4.14.1-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded libadwaita (1:1.4.4-1.1 -> 1:1.5.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded libpipewire (1:1.0.4-1.1 -> 1:1.0.4-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded pipewire (1:1.0.4-1.1 -> 1:1.0.4-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded file-roller (43.1-1.1 -> 44beta-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded glibmm (2.66.6-1.1 -> 2.66.7-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded glibmm-2.68 (2.78.1-1.1 -> 2.80.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded lib32-util-linux (2.39.3-1.1 -> 2.40rc2-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded lib32-glib2 (2.78.4-1.1 -> 2.80.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded libgirepository (1.78.1-1.1 -> 1.80.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gobject-introspection-runtime (1.78.1-1.1 -> 1.80.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gst-plugins-base (1.24.1-1.1 -> 1.24.1-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gst-plugins-good (1.24.1-1.1 -> 1.24.1-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gvfs (1.52.2-2.1 -> 1.54.0-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gvfs-mtp (1.52.2-2.1 -> 1.54.0-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded hyprcursor (0.1.4-2.1 -> 0.1.5-1.1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded lib32-at-spi2-core (2.50.2-1 -> 2.52.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded lib32-librsvg (2:2.57.3-1.1 -> 2:2.58.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded pipewire-audio (1:1.0.4-1.1 -> 1:1.0.4-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded pipewire-alsa (1:1.0.4-1.1 -> 1:1.0.4-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded pipewire-jack (1:1.0.4-1.1 -> 1:1.0.4-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded pipewire-pulse (1:1.0.4-1.1 -> 1:1.0.4-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded python-gobject (3.46.0-1.1 -> 3.48.1-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded vte-common (0.74.2-1.1 -> 0.76.0-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded vte3 (0.74.2-1.1 -> 0.76.0-2)
[2024-03-24T16:24:31+0000] [ALPM] upgraded webkit2gtk (2.42.5-2 -> 2.44.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded webkit2gtk-4.1 (2.42.5-2 -> 2.44.0-1)
[2024-03-24T16:49:42+0000] [ALPM] upgraded librewolf-bin (123.0.1-1 -> 124.0.1-1)
```

Any ideas what could've caused this? An issue on my end?

Thanks in advance for the help :)

**Comment by strycore** [comment]
Those packages are used by Lutris:

```
[2024-03-24T16:24:31+0000] [ALPM] upgraded libgirepository (1.78.1-1.1 -> 1.80.0-1)
[2024-03-24T16:24:31+0000] [ALPM] upgraded gobject-introspection-runtime (1.78.1-1.1 -> 1.80.0-1)
...
[2024-03-24T16:24:31+0000] [ALPM] upgraded python-gobject (3.46.0-1.1 -> 3.48.1-2)
```

Try uninstalling Lutris, run your updates then reinstall Lutris.

**Comment by Fxzzi** [comment]
Thank you for the quick response - I just tried this - however lutris is still crashing. I have also tried building from source via the `lutris-git` package on the AUR. Sadly, still crashing.

**Comment by Fxzzi** [comment]
I've tried upgrading and then downgrading these specific packages, however it doesn't allow me to because of other dependency issues. So for now I am not updating my system. Hopefully this can be solved soon.

**Comment by strycore** [comment]
Try to uninstall software from the AUR that is suspected to cause issues. This is likely what is preventing you from fully upgrading your system.

**Comment by Fxzzi** [comment]
> Try to uninstall software from the AUR that is suspected to cause issues. This is likely what is preventing you from fully upgrading your system.

Hi there, the only update in that list that was from the AUR was librewolf-bin, and that's just my browser. I've added those packages you listed earlier to my list of packages to skip for upgrades and my lutris is working. Therefore this is not an issue with the AUR.

I can complete the update just fine, it's just that lutris doesn't work afterwards.

**Comment by Fxzzi** [comment]
Hi, could I be given the reason for this being listed as not a lutris bug? This must be a lutris bug as if I downgrade all packages, and only upgrade those 3 packages and packages which depend on them, and lutris still crashes. This is not an issue with any AUR package. It seems @Kerkpower has liked my original post. Are they also experiencing this issue?

**Comment by danieljohnson2** [comment]
No clear idea why the typelib is not being found, but to me this suggests a packaging issue. Like something important has been moved into a different package that needs to be installed, but the AUR packagers have not updated their Lutris package to depend on it properly.

Something like that.

**Comment by Fxzzi** [comment]
Lutris is not packaged in the AUR. It's an official arch Linux package.

**Comment by Fxzzi** [comment]
Tested on my laptop - lutris seems to launch fine. Now I am confused. I tried renaming lutris directories in `~/.local/share/lutris` and `~/.config/lutris` however still does not seem to be launching.

**Comment by danieljohnson2** [comment]
This suggests that it is not a package error actually, but that your OS install is corrupted in some way.

**Comment by Fxzzi** [comment]
Finally fixed this issue. Seems like a weird issue but I went ahead and reinstalled all packages on my system with `pacman -Qqn | sudo pacman -Syu -`. Afterwards and a reboot, lutris is launching again 🥳 

thanks for your help and for the amazing software!!
