### ISSUE TITLE
Failed to extract /home/User/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/User/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-

### ISSUE THREAD

**Issue by Viliansh** [lutris/lutris#5388]
Installing Need for speed World, Lutris apparently try to install again an already installed wine version, and doing so it fail because it's already installed
```
flatpak run net.lutris.Lutris 

(process:2): Gtk-WARNING **: 16:42:00.047: Locale not supported by C library.
        Using the fallback 'C' locale.
Unsupported locale setting: unsupported locale setting

(lutris:2): Gtk-WARNING **: 16:42:00.310: Locale not supported by C library.
        Using the fallback 'C' locale.
2024-03-27 16:42:00,495: Command 'fluidsynth' not found on your system
qdbus: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
2024-03-27 16:42:01,169: Starting Lutris 0.5.16
2024-03-27 16:42:01,171: Running AMD Mesa driver 24.0.3 on AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.8.1-300.fc40.x86_64) (0x164c)
2024-03-27 16:42:01,171: GPU: 1002:164C 17AA:3F95 (amdgpu drivers)
2024-03-27 16:42:30,933: Runner <lutris.runners.wine.wine object at 0x7f6c07150b50> needs to be installed
2024-03-27 16:42:30,939: Getting runner information for wine (version: wine-ge-8-26-x86_64)
2024-03-27 16:43:06,977: Overwrite existing path /home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/share
2024-03-27 16:43:08,580: Overwrite existing path /home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64
2024-03-27 16:43:08,582: Failed to merge to destination /home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'
2024-03-27 16:43:08,582: Failed to extract the archive /home/vdaros/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz file may be corrupt
2024-03-27 16:43:08,582: Failed to extract /home/vdaros/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'
2024-03-27 16:43:08,582: Failed to extract /home/vdaros/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'
2024-03-27 16:43:08,582: Error handling idle function: Failed to extract /home/vdaros/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/extract.py", line 170, in extract_archive
    system.merge_folders(source_path, destination_path)
  File "/app/lib/python3.11/site-packages/lutris/util/system.py", line 350, in merge_folders
    shutil.copy(os.path.join(dirpath, filename), os.path.join(dst_abspath, filename), follow_symlinks=False)
  File "/usr/lib/python3.11/shutil.py", line 431, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 254, in copyfile
    os.symlink(os.readlink(src), dst)
FileExistsError: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/runners/runner.py", line 510, in extract
    extract_archive(archive, dest, merge_single=merge_single)
  File "/app/lib/python3.11/site-packages/lutris/util/extract.py", line 177, in extract_archive
    raise ExtractError(str(ex)) from ex
lutris.util.extract.ExtractError: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 278, in install_runner
    runner.install(
  File "/app/lib/python3.11/site-packages/lutris/runners/runner.py", line 492, in install
    self.download_and_extract(runner_version_info["url"], **opts)
  File "/app/lib/python3.11/site-packages/lutris/runners/runner.py", line 504, in download_and_extract
    self.extract(archive=runner_archive, dest=dest, merge_single=merge_single, callback=callback)
  File "/app/lib/python3.11/site-packages/lutris/runners/runner.py", line 513, in extract
    raise RunnerInstallationError(_("Failed to extract {}: {}").format(archive, ex)) from ex
lutris.runners.RunnerInstallationError: Failed to extract /home/vdaros/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 444, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 211, in launch_install
    self.install_runners(ui_delegate)
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 265, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 285, in install_runner
    raise ScriptingError(ex.message) from ex
lutris.installer.errors.ScriptingError: Failed to extract /home/vdaros/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0' -> '/home/vdaros/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/lib64/libgstpbutils-1.0.so'
2024-03-27 16:46:05,742: Non existent path: /home/vdaros/.var/app/net.lutris.Lutris/cache/lutris/installer/need-for-speed-world
2024-03-27 16:46:15,556: Shutting down Lutris
```
how to reproduce:
have Wine-ge-8-26 installed, the click add game, search lutris for a game(in my example i uses need for speed world) select it, lutris gonna download the wine again and in extracting it, it gonna fail, if the folder /.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64 is deleted the launcher install wine fine, but it fail again if trying to add a game

i tried to screencapture the instructions but github only accept the video if it's less than 10mb, what make it a have such a crappy quality that i don't think it's worth, but i can share if needed

lutris is from flatpak and i'm using Fedora Kinoite

Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.1-300.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700U with Radeon Graphics
Memory: 7,1 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 82MF
System Version: IdeaPad 3 15ALC6

**Comment by MrRinkana** [comment]
How does one find what version lutris provides/correct version string to get them? 

I was trying to install league of legends (euw) and the current install scripts fail to download the version given (wine-ge-lol-8-27-x86_64) instead downloading another runner (still from gloriousEggrolls git: wine-ge-8-26-x86_64). 

Is it specific GE-wine releases that are supported or is lutris failing to resolve/download the specified runner version?

I tried manually putting the wine version in the runners folder, changing the version string in the installer but it still downloaded 8.26 and errored out with the "file exists" stuff.. What worked was removing the version line, getting lucky that the games own installer works with wine-ge-8.26 and then manually changing to the correct runner post install..

**Comment by danieljohnson2** [comment]
That version seems to be available; you may need to install it by hand. There's a couple of buttons next to "Wine" in sidebar; click the left one of the two. This gives you a list of what's available. That one seems to be the topmost. Try installing it ahead of the game.

It is not a specific release that troubles Lutris 0.5.16; the bug is handling Wine versions specified in the install script. It should install it, but actually tries to install the default Wine which you already have, and hilarity ensues. Hopefully if the Wine it needs is already there, it will be fine and continue the install.

**Comment by strycore** [comment]
> lol just removing that weird wine version fix everything, thanks for the explanation!, i'm gonna send a update for the script in the site :D

It's not a "weird wine version" and I'm going to reject your change.

**Comment by strycore** [comment]
I've reverted the installer to use the NFS specific build. We do want to get rid of it eventually (it's Wine 5, it's going to break on modern systems at some point) but we have to make sure the game runs with the latest Proton version.

**Comment by Viliansh** [comment]
> > lol just removing that weird wine version fix everything, thanks for the explanation!, i'm gonna send a update for the script in the site :D
> 
> It's not a "weird wine version" and I'm going to reject your change.

sorry, i couldn't find that wine version on lutris and the other guy said that they didn't knew about that, so i tried to help :/

**Comment by strycore** [comment]
> sorry, i couldn't find that wine version on lutris and the other guy said that they didn't knew about that, so i tried to help :/

no worry, it's ok, we're missing an important part of Lutris which is disallowing pinned Wine version without a reason.

**Comment by MrRinkana** [comment]
> It is not a specific release that troubles Lutris 0.5.16; the bug is handling Wine versions specified in the install script. It should install it, but actually tries to install the default Wine which you already have, and hilarity ensues. Hopefully if the Wine it needs is already there, it will be fine and continue the install.

I tried putting it there but either there is some very specific syntax required (other than the name of the folder/wine version) or the discovery of existing wine versions is broken and it just always tries default wine. I was lucky that the game installer works with the default wine, and then I could replace it with the correct in advanced runner options after install..

**Comment by danieljohnson2** [comment]
Well, glad you worked around it. I do not know what went wrong with your manual install effort- it should just need to be in a directory with the right name inside of ~/.local/share/lutris/runners/wine.

But hopefully the bug-fix will be out soon anyway.
