### ISSUE TITLE
First time install and launch of Lutris

### ISSUE THREAD

**Issue by zaazz55** [lutris/lutris#541]
OS: Ubuntu 16.04.2 LTS x86_64 
Kernel: 4.4.0-66-generic 

'~$ lutris -d
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 152, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 83, in __init__
    steam.sync_with_lutris()
  File "/usr/lib/python3/dist-packages/lutris/util/steam.py", line 255, in sync_with_lutris
    steamapps_paths = get_steamapps_paths()
  File "/usr/lib/python3/dist-packages/lutris/util/steam.py", line 211, in get_steamapps_paths
    for folder in winesteam_runner.get_steamapps_dirs():
  File "/usr/lib/python3/dist-packages/lutris/runners/winesteam.py", line 296, in get_steamapps_dirs
    steam_data_dir = self.steam_data_dir
  File "/usr/lib/python3/dist-packages/lutris/runners/winesteam.py", line 203, in steam_data_dir
    steam_path = self.get_steam_path()
  File "/usr/lib/python3/dist-packages/lutris/runners/winesteam.py", line 229, in get_steam_path
    registry = WineRegistry(user_reg)
  File "/usr/lib/python3/dist-packages/lutris/util/wineregistry.py", line 80, in __init__
    self.parse_reg_file(reg_filename)
  File "/usr/lib/python3/dist-packages/lutris/util/wineregistry.py", line 124, in parse_reg_file
    current_key.parse(line)
  File "/usr/lib/python3/dist-packages/lutris/util/wineregistry.py", line 218, in parse
    key, value = re.split(re.compile(r'(?<=[^\\]\")='), line, maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
'

**Comment by strycore** [comment]
This doesn't give me enough information to fix this bug so it will have to be fixed in version 0.4.7 unless you can give me the exact line that is causing the issue (it's a registry key in a wine prefix).

Otherwise, I'll add a patch to catch that error and display the faulty value, which you can paste here.
We're releasing a new version tomorrow so you won't have to wait long to get a fix for this.

**Comment by zaazz55** [comment]
Ok. Thanks for the update. I tried to reinstall python -regex as per a
suggestion in your support channel but it didn't change the results. I'll
wait for the release and see what happens. How would you like me to capture
the results next time? The same way?

Thank you,

~P

**Comment by strycore** [comment]
> I tried to reinstall python -regex as per a suggestion in your support channel 

What? That's a weird idea…

There's another option that would allow a quicker fix, assuming that you don't have any private info in the reg files, could you send me those? Since this is the first time you've installed lutris, the faulty files are likely to be the ones from the default Wine prefix (so ~/.wine/*.reg). With those, I'll be able to ship a proper fix tomorrow.

**Comment by zaazz55** [comment]
Can I paste the output here

**Comment by strycore** [comment]
yes, you an attach the files directly to this issue.

**Comment by zaazz55** [comment]
[regfiles.zip](https://github.com/lutris/lutris/files/840061/regfiles.zip)

**Comment by zaazz55** [comment]
let me know if that's what you were looking for

**Comment by strycore** [comment]
That did the trick, next release should work ok for you :)
