### ISSUE TITLE
Some Wine GE games don't launch under Lutris 0.5.17 + system slowdowns

### ISSUE THREAD

**Issue by bunga-teratai** [lutris/lutris#5417]
Updated from `0.5.12~ubuntu22.04.1` to `0.5.17-0ubuntu1ppa1~ubunty22.04`, and some Wine games that worked on the previous version now don't launch.

Additionally, this update also causes system slowdowns, even when just interacting with UI elements. A similar thing happens to me when I launch Steam, actually.

Example log after trying to launch a game:

```
Started initial process 10656 from gamemoderun /home/cafune/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /mnt/SamsungSSD_1TB/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe
Start monitoring process.
gamemodeauto: 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  43 ()
  Serial number of failed request:  539
  Current serial number in output stream:  540
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
```

`Xorg.0.log` output after trying to launch a game:

```
[  1179.776] (--) NVIDIA(GPU-0): DFP-0: disconnected
[  1179.776] (--) NVIDIA(GPU-0): DFP-0: Internal DisplayPort
[  1179.776] (--) NVIDIA(GPU-0): DFP-0: 2670.0 MHz maximum pixel clock
[  1179.776] (--) NVIDIA(GPU-0): 
[  1179.776] (--) NVIDIA(GPU-0): DFP-1: disconnected
[  1179.776] (--) NVIDIA(GPU-0): DFP-1: Internal TMDS
[  1179.776] (--) NVIDIA(GPU-0): DFP-1: 165.0 MHz maximum pixel clock
[  1179.776] (--) NVIDIA(GPU-0): 
[  1179.776] (--) NVIDIA(GPU-0): DFP-2: disconnected
[  1179.776] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[  1179.776] (--) NVIDIA(GPU-0): DFP-2: 2670.0 MHz maximum pixel clock
[  1179.776] (--) NVIDIA(GPU-0): 
[  1179.776] (--) NVIDIA(GPU-0): DFP-3: disconnected
[  1179.776] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[  1179.776] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[  1179.777] (--) NVIDIA(GPU-0): 
[  1179.777] (--) NVIDIA(GPU-0): DFP-4: disconnected
[  1179.777] (--) NVIDIA(GPU-0): DFP-4: Internal TMDS
[  1179.777] (--) NVIDIA(GPU-0): DFP-4: 165.0 MHz maximum pixel clock
[  1179.777] (--) NVIDIA(GPU-0): 
[  1179.777] (--) NVIDIA(GPU-0): DFP-0: disconnected
[  1179.777] (--) NVIDIA(GPU-0): DFP-0: Internal DisplayPort
[  1179.777] (--) NVIDIA(GPU-0): DFP-0: 2670.0 MHz maximum pixel clock
[  1179.777] (--) NVIDIA(GPU-0): 
[  1179.777] (--) NVIDIA(GPU-0): DFP-1: disconnected
[  1179.777] (--) NVIDIA(GPU-0): DFP-1: Internal TMDS
[  1179.777] (--) NVIDIA(GPU-0): DFP-1: 165.0 MHz maximum pixel clock
[  1179.777] (--) NVIDIA(GPU-0): 
[  1179.777] (--) NVIDIA(GPU-0): DFP-2: disconnected
[  1179.777] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[  1179.777] (--) NVIDIA(GPU-0): DFP-2: 2670.0 MHz maximum pixel clock
[  1179.777] (--) NVIDIA(GPU-0): 
[  1179.777] (--) NVIDIA(GPU-0): DFP-3: disconnected
[  1179.777] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[  1179.777] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[  1179.777] (--) NVIDIA(GPU-0): 
[  1179.777] (--) NVIDIA(GPU-0): DFP-4: disconnected
[  1179.777] (--) NVIDIA(GPU-0): DFP-4: Internal TMDS
[  1179.777] (--) NVIDIA(GPU-0): DFP-4: 165.0 MHz maximum pixel clock
[  1179.777] (--) NVIDIA(GPU-0): 
```

System info (copied from _Settings > System_):

```
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Linux Mint 21.1 Vera
Arch: x86_64
Kernel: 5.15.0-102-lowlatency
Desktop: MATE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 15.4 GB
Swap: 0.7 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 535.171.04
OpenGL Core: 4.6.0 NVIDIA 535.171.04
OpenGL ES: OpenGL ES 3.2 NVIDIA 535.171.04
Vulkan Version: 1.3.204
Vulkan Drivers: Intel(R) UHD Graphics (CML GT2) (1.3.255), NVIDIA GeForce RTX 3060 Laptop GPU (1.3.242)
```

**Comment by bunga-teratai** [comment]
For now, I will downgrade back to 0.5.12 or 0.5.13.

**Comment by danieljohnson2** [comment]
From the sound of it the issue is not the game launch- it's something more pervasive. It is affecting you even if you do not launch a game, yes?

Might help to get a complete log; might be something earlier that would be a clue.

Also, can you upgrade to 0.5.16? It'd be nice to know if this issue is caused by the latest update or some prior one.

**Comment by strycore** [comment]
Linux Mint, Nvidia GPU and user who is purposefully downgrading to 0.5.12. 

Sorry but I'm not touching this one.

**Comment by danieljohnson2** [comment]
Could be worse. Could be running X11.

**Comment by Dskobra** [comment]
I'm getting severe stability issues since the last update on Fedora 39 kde with flatpak version. While playing wow computer starts to lag and eventually locks up and crashes xwayland. I also tried x11 and didnt make it any better. Using latest winege 8-26

`Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.8.4-200.fc39.x86_64
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 4800H with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 30.7 GB
Swap: 8.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.8.4-200.fc39.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.4 (git-bb6a55b75b)
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.4 (git-bb6a55b75b)
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.4 (git-bb6a55b75b)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon RX 5600M (RADV NAVI10) (1.3.274), AMD Radeon Graphics (RADV RENOIR) (1.3.274)`

_log for battle.net profile_
https://pastebin.com/Q3snTspr

_wayland log_
https://pastebin.com/nCiZYJ11

**Comment by strycore** [comment]
What happens if you force Lutris to run WoW on your 5600M with the GPU option in system settings?
Does it have bad performance from the start or does it start to slow down after a while?

**Comment by Dskobra** [comment]
No difference. When I login the game it's fine for about a min then slowly starts to stutter eventually leading to more freezes to xwayland crashing

**Comment by bunga-teratai** [comment]
@strycore 

> Linux Mint, Nvidia GPU and user who is purposefully downgrading to 0.5.12.
> 
> Sorry but I'm not touching this one.

Understandable, lol

---

@danieljohnson2 

> From the sound of it the issue is not the game launch- it's something more pervasive. It is affecting you even if you do not launch a game, yes?
> 
> Might help to get a complete log; might be something earlier that would be a clue.
> 
> Also, can you upgrade to 0.5.16? It'd be nice to know if this issue is caused by the latest update or some prior one.

I've tried 0.5.13, and the effect seems to be the same -- system stutter when interacting with Lutris UI & `BadMatch` in game logs. Haven't tried any of the other versions between 0.5.12 and 0.5.17.
As for the log, I'd like to get a complete one; how do I go about it? Does Lutris store them somewhere, or is there a toggle in Settings that I might've missed?

**Comment by danieljohnson2** [comment]
Sounds like the issue was introduced in 0.5.13 then.

You can get a more complete log via the terminal:
```bash
lutris -d &>lutris.log
```

What is strange to me is the BadMatch stuff. Did those occur in 0.5.12, or just in 0.5.13? Sounds like those occur during the game, but you seems to be using the same version of Wine and of the game regardless, so what would that change?

**Comment by bunga-teratai** [comment]
Ok, so I seem to have misremembered things -- the _BadMatch thing only happens on 0.15.17_. But, on other versions, the games still don't launch regardless. I've tested several games on different versions of Lutris and have produced some logs. I'm adding them here, with a table summary of how things went.

Additionally, I've noticed that stutters mostly happen when opening "Runner options" and "System options" in the game configuration window, as well as when trying to launch Wine games.

| Lutris version | UI | Elite Dangerous (Wine GE 8.26 x86_64) | MX vs ATV Reflex (Wine GE 8.26 x86_64) | Potion Craft (Wine GE 8.26 x86_64) | Cogmind (lutris-fshack-7.2-x86_64) | Last Call BBS (native Linux) |
|---|---|---|---|---|---|---|
| 0.5.12 | OK | OK | OK | OK | OK | not tested, assumed OK |
| 0.5.13 | Stutter | Fail, stutter when launching | Fail, stutter when launching | Fail, stutter when launching | Fail, stutter when launching | OK |
| 0.5.16 | Stutter | Fail, stutter when launching | Fail, stutter when launching | Fail, stutter when launching | Fail, stutter when launching | OK |
| 0.5.17 | Stutter | Fail, no stutter, BadMatch | Fail, no stutter, brief screen flicker, BadMatch | Fail, no stutter, brief screen flicker, BadMatch | OK, but runs in a weird non-fullscreen borderless window | OK |

[lutris_0_5_12.log](https://github.com/lutris/lutris/files/14966961/lutris_0_5_12.log)
[lutris_0_5_13.log](https://github.com/lutris/lutris/files/14966963/lutris_0_5_13.log)
[lutris_0_5_16.log](https://github.com/lutris/lutris/files/14966964/lutris_0_5_16.log)
[lutris_0_15_17.log](https://github.com/lutris/lutris/files/14966965/lutris_0_15_17.log)

**Comment by danieljohnson2** [comment]
I'll have to read these logs.

But I think there's one thing in 0.5.17 that might be related to the BadMatch- the new GPU selector. That's not just a new UI; it may be configuring things difficulty for you now.

Can we get a screenie for a game's "System options"? This is in the game configuration window, and I want to see the "Display" group box with 'Advanced' mode on. On these old Lutris versions, you are looking for the "Vulkan ICD Loader" setting and stuff near it, though there are no group boxes yet.

This does not explain the stutter. Just confirm for me- is this stuttering just when launching, or does it happen before or after the launch too? And does it stutter if you launch it a second time in the same session?

This all seems Wine related, but if so it should have no effect before you launch a game.

**Comment by bunga-teratai** [comment]
Here's that screenshot (0.5.17):

![Screenshot at 2024-04-13 13-13-35](https://github.com/lutris/lutris/assets/98167379/2673d7ff-0e77-4686-8eb1-f6275171dc0b)

And another (0.5.13):

![Screenshot at 2024-04-13 13-21-47](https://github.com/lutris/lutris/assets/98167379/243584c4-3ba0-4237-ad76-f113c0c9b01f)

So, the stutters during game launch happens about a second after pressing "Play", last for 5-10 seconds, and then the "Stop" button goes back to "Play". Meanwhile, UI-related stutters happen for several seconds when pressing either the "Runner options" or "System options" tabs, before finally switching to them.

**Comment by danieljohnson2** [comment]
Can we get a screenie from 0.5.12? I'd like to see if the Vulkan ICD loader is different. Sill Unknown GPU?

In 0.5.17, does the "GPU" drop-down offer an "Auto (default)" option? Can you try that?

**Comment by danieljohnson2** [comment]
I've noticed a couple of things. The environment for some process you have is messed up, but the code to generate a message over this got removed from Lutris in 0.5.13, it just skips bad data silently. This code is called often while you play, to see if the game is still running.

Could you try [this branch](https://github.com/lutris/lutris/tree/dj/old_school_environ) that restores the old environment code? Does it help the stuttering?

Second thing, you are getting errors as if you had the setting "Disable desktop effects" turned on, and this is kind of  obsolete. I found a bug where it would try to apply the setting though it can't figure out your compositor, and I have pushed a fix. If you can, turn this setting off and see if it helps. If it's disabled, you may be affected by the bug I found. Try downloading the latest master (with my fix) and see if that helps.

**Comment by bunga-teratai** [comment]
> Can we get a screenie from 0.5.12?

Sure, here you go:

![Screenshot at 2024-04-13 21-37-23](https://github.com/lutris/lutris/assets/98167379/203240f7-b2a7-45e6-90db-7ce958dee34c)

> In 0.5.17, does the "GPU" drop-down offer an "Auto (default)" option? Can you try that?

I think I've tried that; same effect (haven't checked the logs, though).

I'll give the latest master + fix a try and will report later.

**Comment by bunga-teratai** [comment]
So, on latest `master`, "Disable desktop effects" is greyed out, so I can't do much about it, anyway. Oh, and the games don't launch, either.

System settings screenshot:
![Screenshot at 2024-04-13 21-54-37](https://github.com/lutris/lutris/assets/98167379/f649d325-1dbf-4e24-94bf-bee449eb44ba)

Lutris log:
<details>
<pre>
$ ./lutris -d
2024-04-13 21:58:04,130: Command 'fluidsynth' not found on your system
Unknown command get org.mate.Marco.general

Usage:
  gsettings --version
  gsettings [--schemadir SCHEMADIR] COMMAND [ARGS…]

Commands:
  help                      Show this information
  list-schemas              List installed schemas
  list-relocatable-schemas  List relocatable schemas
  list-keys                 List keys in a schema
  list-children             List children of a schema
  list-recursively          List keys and values, recursively
  range                     Queries the range of a key
  describe                  Queries the description of a key
  get                       Get the value of a key
  set                       Set the value of a key
  reset                     Reset the value of a key
  reset-recursively         Reset all values in a given schema
  writable                  Check if a key is writable
  monitor                   Watch for changes

Use “gsettings help COMMAND” to get detailed help.


INFO     2024-04-13 21:58:04,573 [application.do_command_line:480]:Starting Lutris 0.5.17
INFO     2024-04-13 21:58:04,651 [startup.run_all_checks:120]:NVIDIA GeForce RTX 3060 Laptop GPU (10de:2520 1028:0a64 nvidia) Driver 535.171.04
INFO     2024-04-13 21:58:04,682 [startup.run_all_checks:120]:Intel UHD Graphics (8086:9bc4 1028:0a64 i915) Driver None
DEBUG    2024-04-13 21:58:04,873 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 21:58:06,236 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 21:58:06,306 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-04-13 21:58:06,352 [api.check_stale_runtime_versions:52]:Modified at Сб 13 апр 2024 21:52:00, will update after Вс 14 апр 2024 03:52:00
DEBUG    2024-04-13 21:58:06,413 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-04-13 21:58:09,581 [application.show_window:395]:Showing window EditGameConfigDialog112
DEBUG    2024-04-13 21:58:10,586 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 21:58:11,963 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 21:58:11,964 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 21:58:13,376 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 21:58:13,377 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 21:58:14,748 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 21:58:14,752 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 21:58:16,111 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 21:58:16,114 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 21:58:17,482 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 21:58:22,537 [application.on_app_window_destroyed:420]:Removed window EditGameConfigDialog112
DEBUG    2024-04-13 21:58:24,673 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 21:58:26,048 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
Started initial process 182990 from gamemoderun /home/cafune/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /mnt/SamsungSSD_1TB/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe
Start monitoring process.
gamemodeauto: 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
DEBUG    2024-04-13 21:58:37,725 [monitored_command.on_stop:228]:Process 182985 has terminated with code 256
DEBUG    2024-04-13 21:58:38,077 [game.beat:926]:Game thread stopped
WARNING  2024-04-13 21:58:38,078 [game.on_game_quit:964]:Game still running (state: running)
INFO     2024-04-13 21:58:38,078 [game.stop:937]:Stopping Elite: Dangerous (wine)
DEBUG    2024-04-13 21:58:38,078 [game.stop_game:893]:Elite: Dangerous (wine) has run for 12 seconds
DEBUG    2024-04-13 21:58:38,078 [application.on_game_stopped:795]:Removing 112 from running IDs
DEBUG    2024-04-13 21:58:38,093 [game.stop_game:905]:Playtime: 9 hours 24 minutes
DEBUG    2024-04-13 21:58:38,093 [game.on_game_quit:982]:Elite: Dangerous stopped at Сб, 13 апр 2024 21:58:38
DEBUG    2024-04-13 21:58:38,140 [path_cache.add_to_path_cache:47]:Adding Elite: Dangerous (wine) to path cache
INFO     2024-04-13 21:58:58,964 [application.do_shutdown:1052]:Shutting down Lutris
</pre>
</details>

And this is on your "old environment" branch; I attempted two launches -- the first one with GPU set to Auto, and the other one set to the dedicated Nvidia one:

<details>
<pre>
$ ./lutris -d
2024-04-13 22:04:11,520: Command 'fluidsynth' not found on your system
Unknown command get org.mate.Marco.general

Usage:
  gsettings --version
  gsettings [--schemadir SCHEMADIR] COMMAND [ARGS…]

Commands:
  help                      Show this information
  list-schemas              List installed schemas
  list-relocatable-schemas  List relocatable schemas
  list-keys                 List keys in a schema
  list-children             List children of a schema
  list-recursively          List keys and values, recursively
  range                     Queries the range of a key
  describe                  Queries the description of a key
  get                       Get the value of a key
  set                       Set the value of a key
  reset                     Reset the value of a key
  reset-recursively         Reset all values in a given schema
  writable                  Check if a key is writable
  monitor                   Watch for changes

Use “gsettings help COMMAND” to get detailed help.


INFO     2024-04-13 22:04:11,981 [application.do_command_line:480]:Starting Lutris 0.5.17
INFO     2024-04-13 22:04:12,060 [startup.run_all_checks:120]:NVIDIA GeForce RTX 3060 Laptop GPU (10de:2520 1028:0a64 nvidia) Driver 535.171.04
INFO     2024-04-13 22:04:12,090 [startup.run_all_checks:120]:Intel UHD Graphics (8086:9bc4 1028:0a64 i915) Driver None
DEBUG    2024-04-13 22:04:12,348 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:04:13,699 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:04:13,768 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-04-13 22:04:13,812 [api.check_stale_runtime_versions:52]:Modified at Сб 13 апр 2024 21:52:00, will update after Вс 14 апр 2024 03:52:00
DEBUG    2024-04-13 22:04:13,875 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-04-13 22:04:24,305 [application.show_window:395]:Showing window EditGameConfigDialog112
DEBUG    2024-04-13 22:04:25,689 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:04:27,033 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:04:27,740 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 22:04:29,096 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:04:29,098 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 22:04:30,492 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:04:30,493 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:04:31,853 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:04:31,857 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:04:33,209 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:04:33,211 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:04:34,570 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:04:41,318 [application.on_app_window_destroyed:420]:Removed window EditGameConfigDialog112
DEBUG    2024-04-13 22:04:48,110 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 22:04:49,470 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
Started initial process 184845 from gamemoderun /home/cafune/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /mnt/SamsungSSD_1TB/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe
Start monitoring process.
gamemodeauto: 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
DEBUG    2024-04-13 22:05:01,154 [monitored_command.on_stop:228]:Process 184842 has terminated with code 256
DEBUG    2024-04-13 22:05:02,527 [game.beat:926]:Game thread stopped
WARNING  2024-04-13 22:05:02,528 [game.on_game_quit:964]:Game still running (state: running)
INFO     2024-04-13 22:05:02,529 [game.stop:937]:Stopping Elite: Dangerous (wine)
DEBUG    2024-04-13 22:05:02,529 [game.stop_game:893]:Elite: Dangerous (wine) has run for 13 seconds
DEBUG    2024-04-13 22:05:02,529 [application.on_game_stopped:795]:Removing 112 from running IDs
DEBUG    2024-04-13 22:05:02,544 [game.stop_game:905]:Playtime: 9 hours 24 minutes
DEBUG    2024-04-13 22:05:02,544 [game.on_game_quit:982]:Elite: Dangerous stopped at Сб, 13 апр 2024 22:05:02
DEBUG    2024-04-13 22:05:02,585 [path_cache.add_to_path_cache:47]:Adding Elite: Dangerous (wine) to path cache
DEBUG    2024-04-13 22:06:01,240 [application.show_window:395]:Showing window EditGameConfigDialog112
DEBUG    2024-04-13 22:06:02,164 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 22:06:03,510 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:06:03,511 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 22:06:04,852 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:06:04,854 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:06:06,246 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:06:06,250 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:06:07,646 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:06:07,649 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-13 22:06:08,995 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
DEBUG    2024-04-13 22:07:38,676 [game.save:450]:Saving Elite: Dangerous (wine) with config ID elite-dangerous-1711785717
DEBUG    2024-04-13 22:07:38,676 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=elite-dangerous-1711785717, runner=wine) config to /home/cafune/.config/lutris/games/elite-dangerous-1711785717.yml
DEBUG    2024-04-13 22:07:38,798 [path_cache.add_to_path_cache:47]:Adding Elite: Dangerous (wine) to path cache
DEBUG    2024-04-13 22:07:38,814 [application.on_app_window_destroyed:420]:Removed window EditGameConfigDialog112
DEBUG    2024-04-13 22:07:50,850 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-13 22:07:52,261 [xrandr._get_vidmodes:18]:Retrieving 60 video modes from XrandR
Started initial process 186995 from gamemoderun /home/cafune/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /mnt/SamsungSSD_1TB/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe
Start monitoring process.
gamemodeauto: 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  43 ()
  Serial number of failed request:  539
  Current serial number in output stream:  540
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2024-04-13 22:07:55,021 [monitored_command.on_stop:228]:Process 186993 has terminated with code 0
DEBUG    2024-04-13 22:07:56,278 [game.beat:926]:Game thread stopped
WARNING  2024-04-13 22:07:56,279 [game.on_game_quit:964]:Game still running (state: running)
INFO     2024-04-13 22:07:56,279 [game.stop:937]:Stopping Elite: Dangerous (wine)
DEBUG    2024-04-13 22:07:56,279 [game.stop_game:893]:Elite: Dangerous (wine) has run for 4 seconds
WARNING  2024-04-13 22:07:56,279 [game.stop_game:895]:The game has run for a very short time, did it crash?
DEBUG    2024-04-13 22:07:56,279 [application.on_game_stopped:795]:Removing 112 from running IDs
DEBUG    2024-04-13 22:07:56,293 [game.stop_game:905]:Playtime: 9 hours 24 minutes
DEBUG    2024-04-13 22:07:56,293 [game.on_game_quit:982]:Elite: Dangerous stopped at Сб, 13 апр 2024 22:07:56
DEBUG    2024-04-13 22:07:56,338 [path_cache.add_to_path_cache:47]:Adding Elite: Dangerous (wine) to path cache
INFO     2024-04-13 22:08:10,440 [application.do_shutdown:1052]:Shutting down Lutris
</pre>
</details>

**Comment by danieljohnson2** [comment]
Looks like the desktop effects thing was a dead end.

It looks like when it worked it had selected "NVidia proprietary" and now it is a specific video card. Which seems pretty proprietary to me. It really seems to me that this should work, but the code is very different now and its hard for me to track the changes.

**Comment by bunga-teratai** [comment]
Damn, that's a shame. Guess this is either a Linux Mint related behaviour, or I just have a very specific hardware combination or something

**Comment by 10407dev** [comment]
GPU selection UI changes also confused me for a while, as I was used to how it was. I had the same NV-GLX errors after updating until I switched from Proton 8 to Proton 9. After selecting the dGPU in the new settings it worked just like before the update without any issues

**Comment by strycore** [comment]
We not going to keep around our most shameful features just because people got used to them, that's not how software design works.

We already feel bad enough we had those options in the first place.

**Comment by MadByteDE** [comment]
Just want to add that this is not a single case. I had at least two other users reporting issues with the `BadMatch` error and both of them where using an Intel iGPU and a Nvidia dGPU setup (I maintain a lutris installer script, that's why ppl let me know). Vulkan drivers, ICD loader and proprietary Nvidia drivers *seemed* to be installed just fine.. here is the output of `vulkaninfo --summary` made by one of them:

[paste-8b78a4a648798c3d.txt](https://github.com/lutris/lutris/files/15452992/paste-8b78a4a648798c3d.txt)

And a snippet of the error (unfortunately made with a Kron4ek wine build, but also happened with latest wine-ge):

```
warning: Running /home/USER/.local/share/lutris/runners/wine/wine-9.9-amd64/bin/wineserver -w. This will hang until all wine processes in prefix=/run/media/USER/stuff/Games/EFT terminate
------------------------------------------------------
Executing cd /home/USER/.cache/winetricks/vcrun2019
Executing /home/USER/.local/share/lutris/runners/wine/wine-9.9-amd64/bin/wine vc_redist.x86.exe /q
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  43 ()
  Serial number of failed request:  149
  Current serial number in output stream:  150
------------------------------------------------------
warning: Note: command /home/USER/.local/share/lutris/runners/wine/wine-9.9-amd64/bin/wine vc_redist.x86.exe /q returned status 183. Aborting.
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
DEBUG    2024-05-25 23:21:53,475 [monitored_command.on_stop:228]:Process 129829 has terminated with code 256
DEBUG    2024-05-25 23:21:53,582 [commands._monitor_task:444]:Return code: 256
ERROR    2024-05-25 23:21:53,583 [errors.__init__:19]:Command exited with code 256
ERROR    2024-05-25 23:21:53,584 [exception_backstops.error_wrapper:110]:Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/commands.py", line 446, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```
Unfortunately, I dont have the lutris.log files... I'll make sure to send ppl here if I get another one of those reports.

**Comment by xXDaGiXx** [comment]
Has this been resolbed for anymore?
Im on Lutris 0.5.17 w/ Fedora 40 X11 and for some reason a few days ago pretty all of my stuff through Lutris stopped working and started throwing this error:
```
Initial process has exited (return code: 0)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  43 ()
  Serial number of failed request:  510
```

Zero idea whats caused this and im not using a laptop, but dedicated Nvidia GPU (GTX 1050 I know oof). Im still pretty new to Linux so im super confused. I was on Wayland originally but dropped down to X11 because the Nvidia drivers on Wayland was giving me tons of issues.

**Comment by bunga-teratai** [comment]
Haven't tried yet, still on 0.5.12. Though I've upgraded to Mint 21.3, so I might give it another shot

**Comment by MadByteDE** [comment]
There is an ongoing wine issue regarding some cases of this issue:
https://bugs.winehq.org/show_bug.cgi?id=49407

Setting discrete GPU manually or disabling an existing integrated GPU in the BIOS usually works around that issue - the option often is called `GFX/iGPU Multi-Monitor`.

**Comment by xXDaGiXx** [comment]
Ahhh ok yah, I disabled my iGPU through blacklist.conf and that seemed to fix it after updating initramfs. Weird issue but since this is a desktop doesnt really effect me since I only use my dedicated GPU, not sure about mobile users though who switch between them for battery life. Will have to try it on my laptop and see what its like

**Comment by realsifocopypaste333** [comment]
i am using  xlibre with cinnamon de in debian testing and lutris flatpak is working without any issue :)
