### ISSUE TITLE
Lutris 0.5.17 Fails to Correctly set the Vulkan ICD Loader  

### ISSUE THREAD

**Issue by thevinter** [lutris/lutris#5439]
After upgrading to .17 I get the following error when launching lutris
```
➜  ~ lutris -d
2024-04-19 03:58:09,079: Command 'fluidsynth' not found on your system
INFO     2024-04-19 03:58:09,301 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-04-19 03:58:09,346 [startup.run_all_checks:120]:NVIDIA GeForce RTX 3060 (10de:2504 1043:881d nvidia) Driver 550.67
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:688:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-04-19 03:58:09,352 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-04-19 03:58:09,352 [startup.run_all_checks:120]: (simple-framebuffer) Driver None
DEBUG    2024-04-19 03:58:09,437 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-19 03:58:09,490 [xrandr._get_vidmodes:18]:Retrieving 34 video modes from XrandR
DEBUG    2024-04-19 03:58:09,525 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-04-19 03:58:09,544 [api.check_stale_runtime_versions:52]:Modified at Fri Apr 19 00:17:16 2024, will update after Fri Apr 19 06:17:16 2024
ERROR    2024-04-19 03:58:09,551 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
DEBUG    2024-04-19 03:58:09,577 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
```

I disabled my internal GPU from the bios as seen here
```
➜  ~ lspci
00:00.0 Host bridge: Intel Corporation Device 4c43 (rev 01)
00:01.0 PCI bridge: Intel Corporation Device 4c01 (rev 01)
00:06.0 PCI bridge: Intel Corporation Device 4c09 (rev 01)
00:14.0 USB controller: Intel Corporation Tiger Lake-H USB 3.2 Gen 2x1 xHCI Host Controller (rev 11)
00:14.2 RAM memory: Intel Corporation Tiger Lake-H Shared SRAM (rev 11)
00:16.0 Communication controller: Intel Corporation Tiger Lake-H Management Engine Interface (rev 11)
00:17.0 SATA controller: Intel Corporation Device 43d2 (rev 11)
00:1b.0 PCI bridge: Intel Corporation Tiger Lake-H PCIe Root Port #17 (rev 11)
00:1b.2 PCI bridge: Intel Corporation Device 43c2 (rev 11)
00:1b.4 PCI bridge: Intel Corporation Device 43c4 (rev 11)
00:1c.0 PCI bridge: Intel Corporation Tiger Lake-H PCIe Root Port #1 (rev 11)
00:1c.4 PCI bridge: Intel Corporation Tiger Lake-H PCI Express Root Port #5 (rev 11)
00:1d.0 PCI bridge: Intel Corporation Tiger Lake-H PCI Express Root Port #9 (rev 11)
00:1d.4 PCI bridge: Intel Corporation Device 43b4 (rev 11)
00:1f.0 ISA bridge: Intel Corporation Z590 LPC/eSPI Controller (rev 11)
00:1f.3 Audio device: Intel Corporation Tiger Lake-H HD Audio Controller (rev 11)
00:1f.4 SMBus: Intel Corporation Tiger Lake-H SMBus Controller (rev 11)
00:1f.5 Serial bus controller: Intel Corporation Tiger Lake-H SPI Controller (rev 11)
01:00.0 VGA compatible controller: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GA106 High Definition Audio Controller (rev a1)
02:00.0 Non-Volatile memory controller: INNOGRIT Corporation NVMe SSD Controller IG5216 (DRAM-less) (rev 01)
04:00.0 Ethernet controller: Intel Corporation Ethernet Controller I225-V (rev 03)
07:00.0 Network controller: Intel Corporation Wi-Fi 5(802.11ac) Wireless-AC 9x6x [Thunder Peak] (rev 29)
```
And launching `vulkaninfo` myself works fine

Downgrading to 0.5.16 fixes the issue and I can see the correct loader in the configuration (it's also the only option)
![image](https://github.com/lutris/lutris/assets/33670112/327e9e66-9763-417a-9753-c9213328c86b)

**Comment by ChuckBartowski91** [comment]
That's an issue for me too, but the games are working fine with vulkan.

**Comment by danieljohnson2** [comment]
I think you may be affected by a bug I just turned up; where Lutris does not fall back to lspci if Vulkan is present, but fails to work with your GPU.

You could try to [download the latest master](https://github.com/lutris/lutris), run the ``bin/lutris`` script within, and see if that does anything for you.

**Comment by ChuckBartowski91** [comment]
> I think you may be affected by a bug I just turned up; where Lutris does not fall back to lspci if Vulkan is present, but fails to work with your GPU.
> 
> You could try to [download the latest master](https://github.com/lutris/lutris), run the `bin/lutris` script within, and see if that does anything for you.

the error in the terminal still shows for me (don't understand why no wrapped text in code, maybe new firefox update, sorry):

`./lutris
2024-04-21 12:32:40,353: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
2024-04-21 12:32:40,743: Starting Lutris 0.5.17
2024-04-21 12:32:40,892: NVIDIA GeForce GT 1030 (10de:1d01 1458:375c nvidia) Driver 550.67
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:688:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
2024-04-21 12:32:40,898: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
2024-04-21 12:32:40,908: No GPU (simple-framebuffer) Driver None
2024-04-21 12:32:42,098: Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/home/chuck/Scaricati/lutris-master/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)`

**Comment by ViNi-Arco** [comment]
Could you bring back the Vulkan ICD Loader option?
This makes it easier to switch between RADV, AMDVLK and AMDGPU-PRO, than adding some envars manually..

**Comment by strycore** [comment]
We absolutely DO NO WANT  anyone on this planet or in the whole galaxy to use AMDVLK or AMDGPU-Pro for gaming. 

We will do everything in our power to prevent people from using those.

**Comment by ViNi-Arco** [comment]
> We absolutely DO NOT WANT anyone on this planet or in the whole galaxy to use AMDVLK or AMDGPU-Pro for gaming.
> 
> We will do everything in our power to prevent people from using those.

You're being ironic, right?

Using any of them when necessary is an advantage, see [this issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10309#note_2210896) on Mesa as an example.

And anyway, it's a useful option, I don't see anything against it..

**Comment by strycore** [comment]
No I'm not being ironic. I've messed up more than one system trying to get AMD proprietary drivers working. 
Those drivers are not for gaming they are for professional workloads and are only supported on Ubuntu LTS and RHEL.
No edge case will justify having support for those in Lutris. Lutris is software aimed at making gaming easier, not giving people a false impression that there is possibly a better alternative than mesa that will just end up ruining their OS.

If anything, I would ads detection of AMDGPU Pro in Lutris to show a warning users to switch back to mesa.

We have good free and open source drivers for AMD GPUs while AMD offers piss poor support for their proprietary alternative, we can do without.

**Comment by AdelKS** [comment]
I was having stutters for a few months and I realized just today that I was running on `amdgpu-pro` all this time, turns out the ICD loader choice in Lutris has disappeared and the `amdgpu-pro` takes priority because of the precedence. The stutters were happening because `amdgpu-pro` does not support Graphics Pipeline Library.

**Comment by orlfman** [comment]
can you bring the ability back to change it? i need to use amdvlk only for wow because with wow, radv will either crash or hard lock my system, only in WoW with my 7900 xtx. amdvlk doesn't have this issue, and the bug report on mesa, that has other people who have the same issue, has been open for months and no progress.
i just got back into classic wow today and i already had a system crash with radv in wow -_-

**Comment by danieljohnson2** [comment]
I wouldn't get your hopes up, @orlfman. I think the decision has been made.
