### ISSUE TITLE
Problems with Ubisoft Connect

### ISSUE THREAD

**Issue by cheetahbyte** [lutris/lutris#5469]
### Bug Description
Hi there, so I encountered two errors when using Ubisoft Connect with lutris. 
1. lutris shows some games twice (with some difference in the name). (See M#1)
2. lutris throws an error when trying to reload ubisoft connect.
3. lutris does not render the cover images of the games. (See M#1)
4. lutris is missing one game i purchased (Ghost Recon Breakpoint)

I already tried reinstalling multiple times.

### How to Reproduce
I am not quite sure, if I am the only one that has got this problem. I saw some other issues here concerning problems with ubisoft connect. 
1. Launch lutris
2. go to ubisoft connect page

### Expected Behavior
Show all game covers, show every game and reload the page.

### Log output
This is the output lutris shows me in the gui on the frontend
```
list index out of range

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 142, in do_reload
    self.load()

  File "/usr/lib/python3.12/site-packages/lutris/services/ubisoft.py", line 160, in load
    for game in config_parser.parse_games(configuration_data):

  File "/usr/lib/python3.12/site-packages/lutris/util/ubisoft/parser.py", line 329, in parse_games
    def get_owned_local_games(self, ownership_data):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/ubisoft/parser.py", line 300, in _parse_game
    "spaceId": space_id,
                     ^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/ubisoft/parser.py", line 283, in _get_registry_properties_from_yaml
    game_registry_path = registry_path
                    ^^^^^^^^^^^^^^^^^^^

IndexError: list index out of range
```

### System Information
```
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.8.9-arch1-2
Desktop: GNOME
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 7500F 6-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 31.1 GB
Swap: 4.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.57, 6.8.9-arch1-2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.6-arch1.2
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.6-arch1.2
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.6-arch1.2
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 7800 XT (RADV NAVI32) (1.3.274)
```

### Media
Overview of all Ubisoft Connect Games (M#1)
![image](https://github.com/lutris/lutris/assets/40123243/086f0483-c4ec-432a-aace-1f661aa04811)

**Comment by cheetahbyte** [comment]
### Lutris Debug Log
```
[leo@computer ~]$ lutris -d
2024-05-10 12:01:39,762: Command 'vulkaninfo' not found on your system
2024-05-10 12:01:39,921: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'

(lutris:22128): Gtk-WARNING **: 12:01:39.933: Theme directory apps@2x/22 of theme WhiteSur-dark has no size field


(lutris:22128): Gtk-WARNING **: 12:01:39.933: Theme directory apps@2x/32 of theme WhiteSur-dark has no size field


(lutris:22128): Gtk-WARNING **: 12:01:39.933: Theme directory preferences@2x/22 of theme WhiteSur-dark has no size field

INFO     2024-05-10 12:01:40,000 [application.do_command_line:479]:Starting Lutris 0.5.17
DEBUG    2024-05-10 12:01:40,001 [system._execute:109]:Executing lspci
INFO     2024-05-10 12:01:40,023 [startup.run_all_checks:120]:Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] (1002:747e 1da2:475d amdgpu) Driver 24.0.6
ERROR    2024-05-10 12:01:40,023 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)

(lutris:22128): Gtk-WARNING **: 12:01:40.148: Theme directory apps@2x/22 of theme WhiteSur-dark has no size field


(lutris:22128): Gtk-WARNING **: 12:01:40.148: Theme directory apps@2x/32 of theme WhiteSur-dark has no size field


(lutris:22128): Gtk-WARNING **: 12:01:40.148: Theme directory preferences@2x/22 of theme WhiteSur-dark has no size field

DEBUG    2024-05-10 12:01:40,166 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-05-10 12:01:40,205 [api.check_stale_runtime_versions:52]:Modified at Fr 10 Mai 2024 11:33:09 , will update after Fr 10 Mai 2024 17:33:09 
DEBUG    2024-05-10 12:01:40,206 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-05-10 12:01:41,167 [http._request:88]:POST https://lutris.net/api/users/library?since=1715335226
DEBUG    2024-05-10 12:01:42,985 [base.wipe_game_cache:441]:Deleting ubisoft cache /home/leo/.cache/lutris/ubisoft/library/
DEBUG    2024-05-10 12:01:42,985 [base.wipe_game_cache:175]:Deleting games from service-games for ubisoft
DEBUG    2024-05-10 12:01:42,999 [client._do_request_safe:75]:rememberMeTicket expiration time: 1715344674
INFO     2024-05-10 12:01:42,999 [client._do_request:56]:No headers in kwargs, using session headers
INFO     2024-05-10 12:01:43,700 [client._do_request:64]:Response status: <Response [200]>
DEBUG    2024-05-10 12:01:43,700 [client._do_request_safe:75]:rememberMeTicket expiration time: 1715344674
INFO     2024-05-10 12:01:43,700 [client._do_request:56]:No headers in kwargs, using session headers
INFO     2024-05-10 12:01:43,911 [client._do_request:64]:Response status: <Response [200]>
ERROR    2024-05-10 12:01:44,148 [jobs.target:32]:Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x70b450757ec0>: <class 'IndexError'> list index out of range
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 142, in do_reload
    self.load()
  File "/usr/lib/python3.12/site-packages/lutris/services/ubisoft.py", line 160, in load
    for game in config_parser.parse_games(configuration_data):
  File "/usr/lib/python3.12/site-packages/lutris/util/ubisoft/parser.py", line 327, in parse_games
    yield self._parse_game(yaml_object, game["install_id"], game["launch_id"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/ubisoft/parser.py", line 298, in _parse_game
    registry_path, exe = self._get_registry_properties_from_yaml(game_yaml)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/ubisoft/parser.py", line 282, in _get_registry_properties_from_yaml
    registry_path = game_yaml["root"]["start_game"]["online"]["executables"][0]["working_directory"]["register"]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
```

**Comment by cheetahbyte** [comment]
### Investigation
So looking a bit through the source code of lutris, I think the error boils down to this function in `lutris/util/ubisoft/parser.py`
```py
def _get_registry_properties_from_yaml(self, game_yaml):
        game_registry_path = ""
        game_name = game_yaml["localizations"].get("default")
        exe = ""
        if "online" not in game_yaml["root"]["start_game"]:
           return None, None
           registry_path = game_yaml["root"]["start_game"]["online"]["executables"][0]["working_directory"]["register"]
           game_registry_path = registry_path
           try:
               exe = game_yaml["root"]["start_game"]["online"]["executables"][0]["path"]["relative"]
           except KeyError:     
               exe = game_yaml["root"]["start_game"]["online"]["executables"][0]["path"]["register"]
        return game_registry_path, exe
```

Printing out the input of the game_yaml i found that sometimes there is just nothing inside the executables list.
Example: FarCry New Dawn
```python
{
   "name":"l1",
   "sort_string":"Far Cry 08",
   "background_image":"859a1a741b5700ad075576e2f82838ab.jpg",
   "thumb_image":"l2",
   "logo_image":"9ee476f2e4a826935ca651431d25e9d1.png",
   "splash_image":"812eedebbf8d351e3b364910ecd63df1.png",
   "help_url":"https://support.ubi.com",
   "facebook_url":"https://www.facebook.com/farcry.fr/",
   "homepage_url":"l3",
   "forum_url":"https://discord.gg/ubisoftofficial",
   "overlay_notifications_position":"top_left",
   "overlay_virtual_control_enabled":false,
   "overlay_notifications":[
      {
         "id":0,
         "text":"l4",
         "permanent":true
      },
      {
         "id":1,
         "text":"l5",
         "permanent":false
      },
      {
         "id":2,
         "text":"l6",
         "permanent":false
      }
   ],
   "start_game":{
      "online":{
         "overlay_required":true,
         "overlay_shop_enabled":true,
         "overlay_shop_default_enabled":true,
         "overlay_shop_sigma":true,
         "overlay_browser_home_url":"https://far-cry.ubisoft.com/game/en-us/home/",
         "overlay_product_activation_enabled":true,
         "overlay_supported":true,
         "executables":[
            
         ]
      },
      "steam":{
         "overlay_required":true,
         "overlay_shop_enabled":true,
         "overlay_shop_default_enabled":true,
         "overlay_shop_sigma":true,
         "overlay_browser_home_url":"https://far-cry.ubisoft.com/game/en-us/home/",
         "overlay_supported":true,
         "steam_app_id":939960,
         "steam_installation_status_register":"HKEY_LOCAL_MACHINE\\SOFTWARE\\Valve\\Steam\\InstallPath",
         "game_installation_status_register":"HKEY_CURRENT_USER\\SOFTWARE\\Valve\\Steam\\Apps\\939960\\Installed",
         "arguments":"-uplay_steam_mode",
         "offline_supported":true
      }
    ...
   }
```
After seeing this printed out, I noticed that I've got Far Cry New Dawn over Steam, which is then linked into Ubisoft Connect.

For now, I just wrapped the rest of the code in another try/except block to get most games on the page to work/display. My current function looks like this: 
```py
def _get_registry_properties_from_yaml(self, game_yaml):
        try:
            game_registry_path = ""
            exe = ""
            if "online" not in game_yaml["root"]["start_game"]:
                return None, None
            registry_path = game_yaml["root"]["start_game"]["online"]["executables"][0]["working_directory"]["register"]
            game_registry_path = registry_path
            try:
                exe = game_yaml["root"]["start_game"]["online"]["executables"][0]["path"]["relative"]
            except KeyError:
                
                exe = game_yaml["root"]["start_game"]["online"]["executables"][0]["path"]["register"]
            return game_registry_path, exe
        except IndexError:
            return None, None
```

Result: 
![image](https://github.com/lutris/lutris/assets/40123243/c1acd4fc-d870-4775-b97b-5bcf5f2bddaa)

**Comment by RayJW** [comment]
I have another issue where the new Ubisoft Connect is killing my X11 session completely (black screen and back to login after around half a minute). The problem is however not present with Wayland.

**Comment by strycore** [comment]
Switch to Wayland then.

**Comment by strycore** [comment]
X11 is dead. No one will work on fixing the issues specific to it.

**Comment by RayJW** [comment]
> Switch to Wayland then.

I'm trying to and I have on some devices. At the moment the experience is not usable in my Nvidia machine (the mouse cursor is constantly flickering) and I neither have the time to distrohop nor the money to buy a new graphics card. I've had this card for over 4 years before switching to Linux. 

I'm all for pushing Wayland ASAP but I don't think that's helping anyone.

**Comment by danieljohnson2** [comment]
Well, that crash in the Ubisoft YAML code has nothing to do with X11 or Wayland. I'll adopt @cheetahbyte's fix, more or less.

But if you would, @cheetahbyte, do download the [latest master](https://github.com/lutris/lutris) and try it. Just run the ``bin/lutris`` script included- there is no need to install this.

**Comment by nils-christian** [comment]
Hi @danieljohnson2 ,

I am currently using 0.5.17 of Lutris and encountered the same issue. I wanted to check whether the issue has been solved and tried to clone the current master (fc87c6872951e3572de8baa11fbae27ace264b31). I started the script "bin/lutris", but it crashes with "ModuleNotFoundError: No module named 'lxml'". I installed Lutris beforehand via the package manager, so all dependencies should be available. Any suggestions on how to continue? If necessary I can open another issue ticket for this.

Thank you and best regards

  Nils

**Comment by danieljohnson2** [comment]
That is curious; lxml is indeed a dependency of Lutris, so you should have got it when you installed Lutris from your repo. It's not a new thing.

I wonder if you can install this Python package manually.

**Comment by nils-christian** [comment]
Hi @danieljohnson2,

I installed "python3-lxml" and now the lutris start script runs. I can confirm that the original issue from this ticket no longer occurs. However after logging in, the Ubisoft Connect dialog just keeps blinking and loading without anything happening. No errors or anything. Might be another issue.

Best regards

  Nils
