### ISSUE TITLE
Can't configure game after wrong image

### ISSUE THREAD

**Issue by JosepLlobet** [lutris/lutris#5474]
Hello,

I tried to set an image to a game, but it failed because of format.

Now i can not change it anymore because when i click "Configure" I get the next error message:

```
_gdk-pixbuf-error-quark: No se pudo reconocer el formato de imagen del archivo «/home/josep/.var/app/net.lutris.Lutris/data/lutris/coverart/final-fantasy-xiv.jpg» (3)

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/game_actions.py", line 327, in on_edit_game_configuration
    self.application.show_window(EditGameConfigDialog, game=self.game, parent=self.window)

  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 384, in show_window
    window_inst = window_class(**kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/gui/config/edit_game.py", line 17, in __init__
    self.build_tabs()

  File "/app/lib/python3.11/site-packages/lutris/gui/config/game_common.py", line 101, in build_tabs
    self._build_info_tab()

  File "/app/lib/python3.11/site-packages/lutris/gui/config/game_common.py", line 146, in _build_info_tab
    banner_box = self._get_banner_box()
                 ^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/gui/config/game_common.py", line 287, in _get_banner_box
    self._create_image_button(banner_box, "coverart_big", _("Set custom cover art"), _("Remove custom cover art"))

  File "/app/lib/python3.11/site-packages/lutris/gui/config/game_common.py", line 301, in _create_image_button
    self._set_image(image_type, image_button)

  File "/app/lib/python3.11/site-packages/lutris/gui/config/game_common.py", line 350, in _set_image
    image = ScaledImage.new_from_media_path(media_path, service_media.config_ui_size, scale_factor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/scaled_image.py", line 48, in new_from_media_path
    pixbuf = get_pixbuf_by_path(path, pixbuf_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/utils.py", line 131, in get_pixbuf_by_path
    return GdkPixbuf.Pixbuf.new_from_file_at_size(path, width, height)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

gi.repository.GLib.GError: gdk-pixbuf-error-quark: No se pudo reconocer el formato de imagen del archivo «/home/josep/.var/app/net.lutris.Lutris/data/lutris/coverart/final-fantasy-xiv.jpg» (3)_

```

Any help?

Thank you

**Comment by JosepLlobet** [comment]
> I'm surprised nobody has complained of this one before; a bad media file will actually crash Lutris outright at the main window if you view it there.
> 
> I've put in some handling so you can set a new media in this case.
> 
> Please download [the master branch](https://github.com/lutris/lutris) and run the `bin/lutris` script within; no need to install. You should get a bunch of log spam, but you should now be able to the configuration window and reset or replace the bad media. Better now?

Thank you for answering. 

I'm new at this. Sorry, but i don't know how to do that.

Do you mean only download the code and run "/.editorconfig" ?

Thank you for answering.

**Comment by danieljohnson2** [comment]
No, download the code, unzip if required so you get a directory, and the open up the terminal. Then:

```bash
cd ~/Downloads/extracted-lutris-dir
./bin/lutris
```

Of course, use the directory where your downloaded copy of Lutris was extracted in that first line.
Watch out- if you say just ``lutris`` you will run your installed copy of Lutris, and that won't help a bit.

**Comment by JosepLlobet** [comment]
I fixed it going to "/home/josep/.var/app/net.lutris.Lutris/data/lutris/coverart" and deleting the image.

Thank you.
