### ISSUE TITLE
'Unable to read the DOS Header, possibly a truncated file.'

### ISSUE THREAD

**Issue by chenxiex** [lutris/lutris#5475]
### Reproduce
1. Create a game using runner "wine"
2. Select a bat file as the main exe.
3. Save, and the error occurs.

### Error message
```
'Unable to read the DOS Header, possibly a truncated file.'

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 76, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 694, in on_save
    self.game.runner.extract_icon(self.slug)

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1249, in extract_icon
    extractor = ExtractIcon(self.game_exe)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 28, in __init__
    self.pe = pefile.PE(filepath)
              ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/pefile.py", line 2895, in __init__
    self.__parse__(name, data, fast_load)

  File "/usr/lib/python3.12/site-packages/pefile.py", line 3020, in __parse__
    raise PEFormatError(

pefile.PEFormatError: 'Unable to read the DOS Header, possibly a truncated file.'
```

### Other
This error won't happen if the icon of the game has been configured. So a workaround is to just random select another program with an icon and then back to the bat file. This seems to be a similar issue with #5460 , but bat version.

**Comment by danieljohnson2** [comment]
I've added exception handling so it will log but continue if icon extraction fails. We can live without an icon, and a lot could go wrong trying to read icons like this.

**Comment by danieljohnson2** [comment]
Please download the [latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. Still getting a crash?
