### ISSUE TITLE
The same issue:  could not convert string to float

### ISSUE THREAD

**Issue by tkalfaoglu** [lutris/lutris#5476]
Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/lutriswindow.py", line 532, in update_revealer
    self.game_bar = GameBar(games[0], self.application, self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/widgets/game_bar.py", line 56, in __init__
    self.game = application.get_game_by_id(game_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/application.py", line 839, in get_game_by_id
    return Game(game_id)
           ^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 95, in __init__
    self.playtime = float(game_data.get("playtime") or 0.0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: could not convert string to float: '50.997222222221852.07611111111069'

**Comment by danieljohnson2** [comment]
You've got corrupt data in your game there; that's very much not a legit playtime. I wonder how it got there.

Anyway, I've added some exception handling so that this condition won't hurt so much- it will log and reset the playtime to 0 instead.

Please download the [latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. Still getting a crash?
