### ISSUE TITLE
(Steam OS) I keep trying to connect my EA account to Lutris but it seems like it is broken.

### ISSUE THREAD

**Issue by Vidiot24** [lutris/lutris#5478]
I keep trying to link my Lutris app to my EA account but it seems that it is not working properly. It isn't doing what it it supposed to do, because it just won't link properly. Help.

**Comment by Vidiot24** [comment]
It keeps putting me on the homepage to their website and freezing the window completely, forcing me to shut the window down.

**Comment by TheIDarKIKnight** [comment]
Don't know if it's the exact same error but on nobara 42 each time i try the loggin page crash and give me this error only for EA login.

` 'NoneType' object has no attribute 'find'

Traceback (most recent call last):

  File "/usr/lib/python3.14/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)

  File "/usr/lib/python3.14/site-packages/lutris/services/base.py", line 144, in do_reload
    self.load()
    ~~~~~~~~~^^

  File "/usr/lib/python3.14/site-packages/lutris/services/ea_app.py", line 260, in load
    user_id, _persona_id, _user_name = self.get_identity()
                                       ~~~~~~~~~~~~~~~~~^^

  File "/usr/lib/python3.14/site-packages/lutris/services/ea_app.py", line 255, in get_identity
    persona_id = ea_account_info.find("user").find("personaId").text
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'find'

Lutris log:
[INFO:2025-12-14 19:00:19,774:application]: Starting Lutris 0.5.19
[INFO:2025-12-14 19:00:19,805:startup]: "card1" is AMD Radeon RX 9070 XT (1002:7550 148c:2435 amdgpu) Driver 25.3.1
[WARNING:2025-12-14 19:00:51,961:ea_app]: Refreshing EA access token
[ERROR:2025-12-14 19:00:52,264:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7fc3800cbed0>: <class 'RuntimeError'> User not authenticated to EA
[ERROR:2025-12-14 19:05:33,153:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7fc380ca00f0>: <class 'AttributeError'> 'NoneType' object has no attribute 'find'
[ERROR:2025-12-14 19:06:01,299:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7fc380ca2350>: <class 'AttributeError'> 'NoneType' object has no attribute 'find'
[ERROR:2025-12-14 19:07:08,728:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7fc380ca3110>: <class 'AttributeError'> 'NoneType' object has no attribute 'find'
[ERROR:2025-12-14 19:07:41,875:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7fc380ca2a30>: <class 'AttributeError'> 'NoneType' object has no attribute 'find' `

**Comment by danieljohnson2** [comment]
@TheIDarKIKnight - you're issue looks like a dupe of #6035, fixed by #6220.

You might try the [latest master](https://github.com/lutris/lutris)- download it, and run the script ``bin/lutris`` within. No need to install!

**Comment by TheIDarKIKnight** [comment]
Done, but same error. is it worth to uninstall completely lutris from nobara 42 (installed with the OS out of the box) to reinstall it with the source ?

**Comment by danieljohnson2** [comment]
The EA support has been rewritten in master, so if the error is *exactly* the same, you were not running the master.

A common mistake to run it like this:
```bash
cd lutris-I-extracted/bin
lutris
```

But that run your distro's Lutris. Do it this way:

```bash
cd lutris-I-extracted
./bin/lutris
```

If that's not it, maybe post a new log?

**Comment by TheIDarKIKnight** [comment]
Same error, i'll open a new log thanks for your help and sorry polluting this one i though it might be related...
