### ISSUE TITLE
Cannot Add Game To Lutris

### ISSUE THREAD

**Issue by FeyrisTan** [lutris/lutris#5483]
### Bug description

Lutris refuses to accept this single game.

### How to Reproduce

1. add game to lutris
2. freezes on save

### Expected behavior

let me add the game

### Log output

```shell
Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.runner.extract_icon(self.slug)

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1250, in extract_icon
    icons.append(extractor.export(groups[0], i))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 135, in export
    return Image.open(BytesIO(raw))
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 3323, in open
    im = _open_core(
         ^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 3304, in _open_core
    im = factory(fp, filename)
         ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/PIL/ImageFile.py", line 137, in __init__
    self._open()

  File "/usr/lib/python3.12/site-packages/PIL/IcoImagePlugin.py", line 309, in _open
    self.load()

  File "/usr/lib/python3.12/site-packages/PIL/IcoImagePlugin.py", line 326, in load
    im = self.ico.getimage(self.size)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/PIL/IcoImagePlugin.py", line 195, in getimage
    return self.frame(self.getentryindex(size, bpp))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/PIL/IcoImagePlugin.py", line 236, in frame
    mask = Image.frombuffer(
           ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 3061, in frombuffer
    im = im._new(core.map_buffer(data, size, decoder_name, 0, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: buffer is not large enough
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: CachyOS Linux rolling n/a
Arch: x86_64
Kernel: 6.9.1-4-cachyos
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: 13th Gen Intel(R) Core(TM) i5-13600K
Physical cores: 14
Logical cores: 20
[Memory]
RAM: 31.1 GB
Swap: 31.1 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 17.0.6, DRM 3.57, 6.9.1-4-cachyos)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.0-devel (git-08659a0baa)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.0-devel (git-08659a0baa)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.0-devel (git-08659a0baa)
Vulkan Version: 1.3.285
Vulkan Drivers: AMD Radeon RX 6800 XT (RADV NAVI21) (1.3.285)
```

**Comment by danieljohnson2** [comment]
You might mention which game it is. :smiley: 

Anyhow, looks like icon extraction is failing if I read that right. I've already got handling for that in master, so please try the master branch.

[Download it here](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within; there is no need to install. Try to add your game this way.

**Comment by oXeleis-bzzt** [comment]
> You might mention which game it is. 😃
> 
> Anyhow, looks like icon extraction is failing if I read that right. I've already got handling for that in master, so please try the master branch.
> 
> [Download it here](https://github.com/lutris/lutris) and run the `bin/lutris` script within; there is no need to install. Try to add your game this way.

I tried that but got the exact same error :( any ideas?

**Comment by danieljohnson2** [comment]
Well, that's more than @FeyrisTan did at least! He just disappeared!

So, possibly, you were 'holding it wrong' as they say.

So, here's what you do. [download the master](https://github.com/lutris/lutris) and extract it so you get a folder. Open a terminal and:
```bash
cd ~/Downloads/lutris-I-just-downloaded
./bin/lutris
```
That last line is critical- a path, not just ``lutris``. Just ``lutris`` will run the installed version which isn't working for you. You're not installing anything, your installed Lutris will remain as it was. Instead, you need to run the loose copy of Lutris you downloaded.

If that does not work, please run in debug mode:
```bash
./bin/lutris -d
```

And give us the terminal spam you get. I expect something will have changed in there.

**Comment by oXeleis-bzzt** [comment]
> Well, that's more than @FeyrisTan did at least! He just disappeared!
> 
> So, possibly, you were 'holding it wrong' as they say.
> 
> So, here's what you do. [download the master](https://github.com/lutris/lutris) and extract it so you get a folder. Open a terminal and:
> 
> ```shell
> cd ~/Downloads/lutris-I-just-downloaded
> ./bin/lutris
> ```
> 
> That last line is critical- a path, not just `lutris`. Just `lutris` will run the installed version which isn't working for you. You're not installing anything, your installed Lutris will remain as it was. Instead, you need to run the loose copy of Lutris you downloaded.
> 
> If that does not work, please run in debug mode:
> 
> ```shell
> ./bin/lutris -d
> ```
> 
> And give us the terminal spam you get. I expect something will have changed in there.

this worked like a charm, thank you so much, also i wanna add since im a noob and there are other noobs out there, i was having a hard time figuring out what downloading the "master" meant, you just go to the git page and on the green button that says code you click and then download zip, at least i think that's what it means cause that worked perfectly for me :D

**Comment by danieljohnson2** [comment]
That's right.

I figured you might not know about the ``lutris`` meaning one thing and ``./bin/lutris`` another, but I had not thought about the code button thing. Ah well, you found it.

The next Lutris release should resolve this permanently; you can use this master when you have this problem until that comes out.

**Comment by legluondunet** [comment]
@danieljohnson2 can we close this issue?

**Comment by danieljohnson2** [comment]
Yeah. This one is not going anywhere, but maybe it will be fixed with the new icon extractor code. Maybe not. but @FeyrisTan  is long gone. Closing.
