### ISSUE TITLE
Long .jpg dowload of Battle.Net images and error after

### ISSUE THREAD

**Issue by StellarHarbour** [lutris/lutris#5485]
### Bug description

Long .jpg dowload of Battle.Net images and error after

### How to Reproduce

Activate Battle.Net source
Click update button on it in launcher

### Expected behavior

Battle.Net game list, preferably with WOW Cataclysm Classic

### Log output

```shell
2024-05-26 14:28:26,049: Command 'fluidsynth' not found on your system
2024-05-26 14:28:26,156: Unable to run command, qdbus not found
INFO     2024-05-26 14:28:26,379 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-05-26 14:28:26,429 [startup.run_all_checks:120]:AMD Radeon RX 6800M (1002:73df 1043:16c2 amdgpu) Driver 24.0.8
INFO     2024-05-26 14:28:26,566 [startup.run_all_checks:120]:AMD Radeon Graphics (1002:1638 1043:16c2 amdgpu) Driver 24.0.8
DEBUG    2024-05-26 14:28:26,660 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-05-26 14:28:26,663 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-05-26 14:28:26,696 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-05-26 14:28:26,721 [api.check_stale_runtime_versions:52]:Modified at Sun 26 May 2024 12:30:41 PM , will update after Sun 26 May 2024 06:30:41 PM 
DEBUG    2024-05-26 14:28:26,764 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-05-26 14:28:31,250 [application.show_window:394]:Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7d81c39b1c40 (LutrisWindow at 0x6062584dd720)>}
DEBUG    2024-05-26 14:28:39,860 [application.on_app_window_destroyed:419]:Removed window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7d81c39b1c40 (LutrisWindow at 0x6062584dd720)>}
DEBUG    2024-05-26 14:28:42,002 [base.wipe_game_cache:175]:Deleting games from service-games for battlenet
DEBUG    2024-05-26 14:28:42,225 [http._request:88]:GET https://lutris.net/games/cover/blizzard-arcade-collection.jpg
DEBUG    2024-05-26 14:28:42,226 [http._request:88]:GET https://lutris.net/games/cover/call-of-duty-black-ops-4.jpg
DEBUG    2024-05-26 14:28:42,227 [http._request:88]:GET https://lutris.net/games/cover/call-of-duty-black-ops-cold-war.jpg
DEBUG    2024-05-26 14:28:42,227 [http._request:88]:GET https://lutris.net/games/cover/call-of-duty-modern-warfare.jpg
DEBUG    2024-05-26 14:28:42,229 [http._request:88]:GET https://lutris.net/games/cover/call-of-duty-modern-warfare-2-campaign-remastered.jpg
DEBUG    2024-05-26 14:28:53,174 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/call-of-duty-modern-warfare.jpg
DEBUG    2024-05-26 14:28:53,175 [http._request:88]:GET https://lutris.net/games/cover/call-of-duty-vanguard.jpg
DEBUG    2024-05-26 14:28:56,777 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/call-of-duty-vanguard.jpg
DEBUG    2024-05-26 14:28:56,778 [http._request:88]:GET https://lutris.net/games/cover/crash-bandicoot-4-its-about-time.jpg
DEBUG    2024-05-26 14:28:58,361 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/call-of-duty-black-ops-4.jpg
DEBUG    2024-05-26 14:28:58,362 [http._request:88]:GET https://lutris.net/games/cover/diablo-2-ressurected.jpg
DEBUG    2024-05-26 14:29:01,331 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/crash-bandicoot-4-its-about-time.jpg
DEBUG    2024-05-26 14:29:01,332 [http._request:88]:GET https://lutris.net/games/cover/diablo-ii.jpg
DEBUG    2024-05-26 14:29:07,485 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/diablo-2-ressurected.jpg
DEBUG    2024-05-26 14:29:07,485 [http._request:88]:GET https://lutris.net/games/cover/diablo-ii-lord-of-destruction.jpg
ERROR    2024-05-26 14:29:14,396 [service_media.download:105]:Failed to download https://lutris.net/games/cover/call-of-duty-modern-warfare-2-campaign-remastered.jpg: Unable to connect to server https://lutris.net/games/cover/call-of-duty-modern-warfare-2-campaign-remastered.jpg: <urlopen error _ssl.c:983: The handshake operation timed out>
DEBUG    2024-05-26 14:29:14,397 [http._request:88]:GET https://lutris.net/games/cover/diablo-iii.jpg
ERROR    2024-05-26 14:29:15,493 [service_media.download:105]:Failed to download https://lutris.net/games/cover/call-of-duty-black-ops-cold-war.jpg: Unable to connect to server https://lutris.net/games/cover/call-of-duty-black-ops-cold-war.jpg: <urlopen error _ssl.c:983: The handshake operation timed out>
DEBUG    2024-05-26 14:29:15,493 [http._request:88]:GET https://lutris.net/games/cover/diablo-iv.jpg
ERROR    2024-05-26 14:29:17,846 [service_media.download:105]:Failed to download https://lutris.net/games/cover/blizzard-arcade-collection.jpg: Unable to connect to server https://lutris.net/games/cover/blizzard-arcade-collection.jpg: The read operation timed out
DEBUG    2024-05-26 14:29:17,847 [http._request:88]:GET https://lutris.net/games/cover/hearthstone.jpg
DEBUG    2024-05-26 14:29:20,522 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/diablo-iii.jpg
DEBUG    2024-05-26 14:29:20,523 [http._request:88]:GET https://lutris.net/games/cover/heroes-of-the-storm.jpg
DEBUG    2024-05-26 14:29:31,178 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/diablo-iv.jpg
DEBUG    2024-05-26 14:29:31,179 [http._request:88]:GET https://lutris.net/games/cover/overwatch-2.jpg
ERROR    2024-05-26 14:29:36,891 [media_loader.download_media:26]:'hearthstone' failed: Remote end closed connection without response
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/gui/views/media_loader.py", line 24, in download_media
    path = future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/service_media.py", line 103, in download
    return download_file(url, cache_path, raise_errors=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/http.py", line 184, in download_file
    request = Request(url).get()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/http.py", line 137, in get
    return self._request("GET", data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/http.py", line 97, in _request
    request = urllib.request.urlopen(req, timeout=self.timeout)  # pylint: disable=consider-using-with
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 553, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 745, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 1348, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
DEBUG    2024-05-26 14:29:36,892 [http._request:88]:GET https://lutris.net/games/cover/starcraft.jpg
DEBUG    2024-05-26 14:29:39,414 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/heroes-of-the-storm.jpg
DEBUG    2024-05-26 14:29:39,414 [http._request:88]:GET https://lutris.net/games/cover/starcraft-ii.jpg
DEBUG    2024-05-26 14:29:41,225 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/starcraft.jpg
DEBUG    2024-05-26 14:29:41,226 [http._request:88]:GET https://lutris.net/games/cover/starcraft-remastered.jpg
DEBUG    2024-05-26 14:29:43,600 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/overwatch-2.jpg
DEBUG    2024-05-26 14:29:43,600 [http._request:88]:GET https://lutris.net/games/cover/warcraft-iii-reforged.jpg
ERROR    2024-05-26 14:29:43,989 [service_media.download:105]:Failed to download https://lutris.net/games/cover/diablo-ii-lord-of-destruction.jpg: Request timed out
DEBUG    2024-05-26 14:29:43,990 [http._request:88]:GET https://lutris.net/games/cover/warcraft-iii-reign-of-chaos.jpg
ERROR    2024-05-26 14:29:46,759 [service_media.download:105]:Failed to download https://lutris.net/games/cover/diablo-ii.jpg: Request timed out
DEBUG    2024-05-26 14:29:46,760 [http._request:88]:GET https://lutris.net/games/cover/warcraft-iii-the-frozen-throne.jpg
DEBUG    2024-05-26 14:29:49,271 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/starcraft-ii.jpg
DEBUG    2024-05-26 14:29:49,271 [http._request:88]:GET https://lutris.net/games/cover/world-of-warcraft.jpg
ERROR    2024-05-26 14:30:18,094 [service_media.download:105]:Failed to download https://lutris.net/games/cover/warcraft-iii-reign-of-chaos.jpg: Unable to connect to server https://lutris.net/games/cover/warcraft-iii-reign-of-chaos.jpg: <urlopen error _ssl.c:983: The handshake operation timed out>
DEBUG    2024-05-26 14:30:18,095 [http._request:88]:GET https://lutris.net/games/cover/world-of-warcraft-classic.jpg
ERROR    2024-05-26 14:30:19,490 [service_media.download:105]:Failed to download https://lutris.net/games/cover/warcraft-iii-the-frozen-throne.jpg: Unable to connect to server https://lutris.net/games/cover/warcraft-iii-the-frozen-throne.jpg: The read operation timed out
ERROR    2024-05-26 14:30:21,326 [service_media.download:105]:Failed to download https://lutris.net/games/cover/starcraft-remastered.jpg: Unable to connect to server https://lutris.net/games/cover/starcraft-remastered.jpg: The read operation timed out
DEBUG    2024-05-26 14:30:24,161 [http.write_to_file:147]:Writing to /home/stellarharbour/.cache/lutris/battlenet/coverart/world-of-warcraft-classic.jpg
ERROR    2024-05-26 14:30:26,936 [service_media.download:105]:Failed to download https://lutris.net/games/cover/warcraft-iii-reforged.jpg: Request timed out
ERROR    2024-05-26 14:30:38,789 [service_media.download:105]:Failed to download https://lutris.net/games/cover/world-of-warcraft.jpg: Request timed out
ERROR    2024-05-26 14:30:38,791 [jobs.target:32]:Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7d81d94974c0>: <class 'RuntimeError'> Battle.net is not installed in Lutris
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 144, in do_reload
    self.add_installed_games()
  File "/usr/lib/python3.12/site-packages/lutris/services/battlenet.py", line 124, in add_installed_games
    raise RuntimeError("Battle.net is not installed in Lutris")
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.9.2-arch1-1
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900HX with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 15.0 GB
Swap: 4.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.9.2-arch1-1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.8-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.8-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.8-arch1.1
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 6800M (RADV NAVI22) (1.3.274), AMD Radeon Graphics (RADV RENOIR) (1.3.274)
```

**Comment by danieljohnson2** [comment]
Very strange how it's able to download a bunch of cover art, then suddenly starts timing-out halfway through. You didn't unplug your network cable halfway through, did you?

The later error is simpler though- you need to install Battle.net as if it were a game itself before you can use the Battle.net integration.

**Comment by StellarHarbour** [comment]
Nope, didn't disconnect of course, and what do you mean by install Battle.net? Community supported one? But I won't get help with it

**Comment by danieljohnson2** [comment]
Never said I would *help*. :smile:

But click the [+] in the upper left corner of Lutris, "Search the Lutris website for installers", and find Battle.net, and then install it. You need Battle.net to be installed as if it were a game before you can use the integration properly.

**Comment by StellarHarbour** [comment]
Yep, I tried this and got https://pastebin.com/FmxYRPdn (fixed by installing winetricks package which isn't included in wine-dependencies for some reason) and then this https://pastebin.com/H3U80FTe (lutris don't want to populate runtime for me)

**Comment by danieljohnson2** [comment]
Not getting the runtime is likely to be a problem; evidently you don't have all of it, which may be related to your downloading problems that I don't understand. But maybe you should go to the Preferences window and try to update the runtime and see if that will help.

**Comment by StellarHarbour** [comment]
Let's begin from scratch:
1. I remove .local/share/lutris
2. run lutris -d in Konsole
3. "+", search for Blizzard, install Blizzard Battle.net (https://pastebin.com/JA4AazCf) and get another random error "Unable to connect to server https://lutris.net/api/installers/battlenet: <urlopen error _ssl.c:983: The handshake operation timed out>"
4. Try same again and get "Remote end closed connection without response" during search
5. Again (search is unbearably long this time, maybe even endless, so using site instead)
6. https://lutris.net/games/battlenet/ > Install button
7. Unable to get games from API: Unable to connect to server https://lutris.net/api/games?search=blizzard&with-installers=True: <urlopen error _ssl.c:983: The handshake operation timed out>
8. Lutris crashed
Final logs for now: https://pastebin.com/fzqenkvk

9. lutris -d, "+" Battle.net, still unbearably long search but this time it gave results, but Request timed out again
10. Download script on community page and run, "No path can be generated for DXVK because no version information is available."
11. Preferences > Runtime Updates > Check for updates (only now it download runtime)
12. Now it installs and works, final log: https://pastebin.com/xDxD4aVP (not all I guess because Konsole lost some of it)

When I used Fedora I didn't had any of those problems, also I noticed that lutris.net is very slow, especially yesterday

**Comment by danieljohnson2** [comment]
It looks to me like Lutris is really struggling to connect to Lutris.net. Can you visit that website in your web-browser? Search for games there?

**Comment by StellarHarbour** [comment]
Yes, but it's loading very long

**Comment by danieljohnson2** [comment]
I think you need to sort that out first.

**Comment by StellarHarbour** [comment]
Other sites work fine and WOW Cataclysm Classic downloaded without any issues too, same for gaming...

**Comment by legluondunet** [comment]
can not reproduce.
