### ISSUE TITLE
Syntax error: invalid syntax on latest build

### ISSUE THREAD

**Issue by Star-X555** [lutris/lutris#5491]
### Bug description

Trying to run lutris -d from the program's bin folder on Steam Deck spits out the following error:

> `Traceback (most recent call last):`
>   `File "./lutris", line 61, in <module>`
>      `from lutris.gui.application import Application # pylint: disable=no-name-in-module`
>  `File "/home/deck/Applications/lutris/lutris/gui/application.py", line 365`
>      `def show_window(self, window_class, /, update_function=None, **kwargs):`
>
> `Syntax Error: invalid syntax`

### How to Reproduce

1. Install latest build of lutris in folder on Steam Deck
2. cd lutris-dir/bin
3. ./lutris -d

### Expected behavior

It actually runs

### Log output

```shell
Traceback (most recent call last):
  File "./lutris", line 61, in <module>
      from lutris.gui.application import Application # pylint: disable=no-name-in-module
  File "/home/deck/Applications/lutris/lutris/gui/application.py", line 365
      def show_window(self, window_class, /, update_function=None, **kwargs):

Syntax Error: invalid syntax
```

### System Information

```shell
Technically the flatpak works, but as flatpak significantly impacts battery life I wanted to run it separately.  As the info from the flatpak is likely going to be different from the loose install, I'll just say I'm running the current (as of May 29, 2024) stable SteamOS on a 512gb Steam Deck LCD.
```

**Comment by Star-X555** [comment]
Seems the problem may be lack of dependencies.  Sadly, my usual "hacky" approach of installing all of the dependencies in application-dir/.lib and application-dir/.bin will likely take eons due to how the list of dependencies for Debian is frickin insane (500 libs?!?!).

And all this would be solved by simply releasing a dang appimage.  Wish I could figure out how to make one, as I've been waiting years for such a thing :(

**Comment by strycore** [comment]
> flatpak significantly impacts battery life 

uh? 

> Seems the problem may be lack of dependencies. 

Unlikely, since you have a syntax error.

I remember installing Lutris on Steam Deck before the Flatpak existed. You need to make your OS writable and then install dependencies with pacman (or just install the lutris package that should work too) 
Maybe put the commands in a script you can re-run when SteamOS updates and wipes all changes made on the system partition.

**Comment by Star-X555** [comment]
>> flatpak significantly impacts battery life
> uh?

It's true.  Heroes of Might and Magic 3 should NOT chew up my battery in two hours, but under Flatpak Lutris it does.  By comparison, running it through Proton on Steam as a non-steam game gets the usual 4 hours or more of an old-as-frick game.

It sucks, as Lutris's competition is highly lacking, and Lutris currently lacks appimages, meaning I'm stuck with the battery hog flatpak if I want to actually run games properly without using the incorrect approach of running the game as a nonsteam game.

**Comment by strycore** [comment]
I would be interested in seeing if you can get Lutris installed natively and confirm this battery issue goes away when running outside the Flatpak.

Maybe also try disabling Gamemode for your game in Lutris, it may make the CPU run at higher frequencies than necessary.

**Comment by strycore** [comment]
Wait, what was that slash doing here? What did it do? Is that even valid python? Why?

**Comment by danieljohnson2** [comment]
Well, battery issues aside, that syntax error is my bug. It's a position-only parameter, but they were introduced in Python 3.8, and we support back to 3.7, so that needs to go.

I've reviewed all callers and this did not actually do anything useful; I think I misunderstood what it does in the first place.

**Comment by Star-X555** [comment]
Heads up about the battery life issue, FYI after hours of getting Heroic Games Launcher set up to boot HoMM3, I launched the game and found practically no difference in battery life estimates.  So yeah, never mind about that.  Heroic launcher's other issues, like wine-ge versions past 7.43 being completely nonfunctional, convinced me to stick with lutris.  I think I'm just overestimating the Deck's battery and underestimating how much juice old games can eat up, especially with enhancement mods.  Also likely more due to wine in general, as the only other examples I had were all native vs wine binaries, with native running WAY longer.
