### ISSUE TITLE
Error: DOS Header magic not found

### ISSUE THREAD

**Issue by Mankybus** [lutris/lutris#5496]
### Bug description

Hello, I did report this issue in the Lutris forum but thought I'd also report the problem here as well, in case it's an issue that's yet to be reported as I couldn't find any other threads bug reports on this issue. Recently for the last week or so some games have been unable to have their configurations saved and instead throws up an error saying "Lutris has encountered an error 'DOS Header magic not found'", which in turn doesn't allow me to save these configurations but the application continues to work fine after the error and the games play perfectly fine. The games configurations that have this problem used to be work and be configured without issue (often experimenting with different versions of WINE or changing other settings).

I must stress that this doesn't affect every game, in fact it's only a small minority of GOG games that are affected so far from my testing, namely; Warhammer Chaosbane, Killing Time and XCOM: Enemy Unknown Complete Pack. The issue could affect many other games that I haven't tried yet. Here is the error code that shows up within Lutris:
```
'DOS Header magic not found.'

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.runner.extract_icon(self.slug)

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1243, in extract_icon
    extractor = ExtractIcon(self.game_exe)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 28, in __init__
    self.pe = pefile.PE(filepath)
              ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/pefile.py", line 2895, in __init__
    self.__parse__(name, data, fast_load)

  File "/usr/lib/python3.12/site-packages/pefile.py", line 3031, in __parse__
    raise PEFormatError("DOS Header magic not found.")

pefile.PEFormatError: 'DOS Header magic not found.'
```

### How to Reproduce

1. Go to GOG game that has this specific error (Warhammer Chaosbane, Killing Time or XCOM: Enemy Unknown Complete Pack found to have this problem so far)
2. Click on configure on that specific game and then click save, no changes are necessary for this error to occur
3. Lutris does not save the configuration due to the DOS Header magic not found error and will continue to throw up the error no matter what I change in the config
4. You should see a box show up in Lutris saying "Lutris has encountered an error 'DOS Header magic not found'", with two button at the bottom of the saying "Copy to clipboard" and "OK", as well as a drop down tab that says "Error details"

### Expected behavior

Lutris should simply save the configuration upon clicking save, without any form of error being displayed.

### Log output

```shell
╰─λ lutris -d
2024-05-31 19:43:05,978: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Garuda Linux Soaring BirdOfPrey
Arch: x86_64
Kernel: 6.9.2-zen1-1-zen
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900X 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 62.7 GB
Swap: 62.7 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 17.0.6, DRM 3.57, 6.9.2-zen1-1-zen)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.8-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.8-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.8-arch1.1
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 6800 XT (RADV NAVI21) (1.3.274)
```

### Media (optional)

![Screenshot_20240531_050239](https://github.com/lutris/lutris/assets/171376672/79ca909d-4d4d-4a6c-b58f-e603fe70b415)

**Comment by danieljohnson2** [comment]
This looks just like #5475 to me, and there's a fix in master for that one.

Please download [the latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within; no need to install. Hopefully you will no longer crash like this. Let us know!

**Comment by Mankybus** [comment]
Hey, that didn't work unfortunately, it seems like it might be something separate as there's no mention of truncated file. I did however get a reply in the Lutris forum that gave me another potential lead and have made some progress with my own tinkering and found some interesting results with a possible temporary workaround. I'll copy and paste what I wrote in the forum :)

"Hey there! Thanks for replying, I hope you don’t mind a big reply because what I ended up discovering is quite the doozy. I did download the “python-magic” package and ended up getting an interesting result. Out of the games mentioned, downloading that package did seem to stop the error during configuration for Killing Time, as far as I could tell. However the issue persisted for Warhammer Chaosbane and XCOM, though since I haven’t properly started XCOM yet, I decided to get rid of that whole game’s prefix and redownloaded from scratch and now that game seems to work, leaving only Warhammer with the error.

I did however do more tinkering with the Chaosbane configuration and found a most peculiar solution/workaround; I was testing to see if it was the Lutris entry that was the problem, the prefix or the game folder itself and I believe I may have found the issue… It’s the icon selection in the configuration. For some reason if I leave the configuration with the blank Lutris icon, the error occurs, but if I select any other icon and it can be a completely random one, then the error no longer happens.

However if I revert the icon back to the Lutris icon then the error occurs again and can be a pain to get Lutris to recognise other .ico files, saying it can’t “find a path” to it despite having no issue selecting it before. But upon tinkering selecting a random .png and then going back to the previous .ico file it could be used again. But even then the error seems to be solved even by using a random .png selected as the icon.

Needless to say it’s an extremely weird and bizarre issue I’ve encountered, I’m not sure if this is affecting Lutris as a whole or if it’s something on my end that’s causing Lutris to behave really strangely. But for now, selecting a random icon does seem to be a decent workaround. Just note that the default Lutris icon doesn’t throw an error up for all game entries in Lutris, it only seems to affect certain games, seemingly GOG games especially, creating my own manual entries doesn’t seem to have this issue as far as I can tell.

I must also note all the games mentioned were already on my drive when I was on a different distro, so perhaps that could also be a part of the problem? Nevertheless, I hope the Lutris team looks into this in case it’s a much bigger issue that’s yet to be addressed."

Apologies for the long comment, I just find this error so utterly bizarre and the possible workaround to be even stranger, I'm genuinely not sure if this is a problem affecting Lutris as a whole or if it's something on my end causing it to behave strangely. But nonetheless I really hope this helps the team get to the bottom of the problem!

**Comment by danieljohnson2** [comment]
It's not surprising to me that you can work around this by setting a proper icon. The crash occurs in the code that extracts the Window's .EXE's icon, and if you set an icon Lutris will no longer try to do that, so no crash.

It's not clear to me why your .exe's icons can't be extracted. It's acting like the executables for these games aren't .exe files at all but are (say) .bat files.

It does surprise me that the master branch did not work any better. Can you provide a debug log (ie, ``./bin/lutris -d``) using the master your downloaded? I wonder if the trace-back ha changed.

**Comment by Mankybus** [comment]
What's strange is Lutris doesn't crash upon throwing up the error, it otherwise still functions perfectly fine and with zero issues playing games and such even after clicking ok after the error. Very odd when I'm so used to programs crashing after an error occurs. What's even stranger is Lutris usually has no problem extracting icons for the vast majority of games, so it's a very strange issue all around.

And luckily the debug worked with your way of doing it, before I only got mentioned of Battlenet and Google, but I recreated the error for you, hoping this helps out somehow :)

```
/bin/lutris -d
2024-06-01 01:42:34,557: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-06-01 01:42:34,710 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-06-01 01:42:34,783 [startup.run_all_checks:120]:AMD Radeon RX 6800 XT (1002:73bf 1458:2328 amdgpu) Driver 24.0.8
DEBUG    2024-06-01 01:42:34,921 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-01 01:42:34,923 [xrandr._get_vidmodes:18]:Retrieving 69 video modes from XrandR
DEBUG    2024-06-01 01:42:34,977 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-01 01:42:35,008 [api.check_stale_runtime_versions:52]:Modified at Sat 01 Jun 2024 01:41:57 , will update after Sat 01 Jun 2024 07:41:57 
DEBUG    2024-06-01 01:42:35,052 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-06-01 01:42:49,755 [application.show_window:394]:Showing window EditGameConfigDialog42
DEBUG    2024-06-01 01:42:51,387 [http._request:88]:GET https://lutris.net/api/games/warhammer-chaosbane
ERROR    2024-06-01 01:42:53,209 [exception_backstops.error_wrapper:110]:Error handling signal 'clicked': 'DOS Header magic not found.'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.runner.extract_icon(self.slug)
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1243, in extract_icon
    extractor = ExtractIcon(self.game_exe)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 28, in __init__
    self.pe = pefile.PE(filepath)
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pefile.py", line 2895, in __init__
    self.__parse__(name, data, fast_load)
  File "/usr/lib/python3.12/site-packages/pefile.py", line 3031, in __parse__
    raise PEFormatError("DOS Header magic not found.")
pefile.PEFormatError: 'DOS Header magic not found.'

```

**Comment by danieljohnson2** [comment]
I put a bunch of effort into making Lutris survive errors, and I'm glad it is helping.

I'm not sure what you mean by "luckily the debug worked with your way of doing it"; the new trace-back came from Lutris 0.5.17, not the latest master, so it doesn't have the error handling for this. You need to do something like this:

```bash
cd ~/Downloads/lutris-extracted-here
./bin/lutris -d
```

I believe the latest code would let you save your game configuration.

You seem to be getting also the "Compressed icons are not supported" when (I think) you try to select an .ico file as that .ico contains the icon in PNG form. We're using GDK to convert .ico and PNG, and it doesn't bother to support these newer .ico unfortunately. If you could get the icon out as a plain old PNG we could handle it.

Since GDK does not handle this, so perhaps we should use the Python Imaging Library to do it- that's what we're using to handle extracted icons from .exes and maybe it would work.

Can you provide one of the files that is failing for you?

**Comment by danieljohnson2** [comment]
On further testing, I find GDK can read the PNG encoded icons I have. Your install might be different though, so its possible going to PIL would still help.

**Comment by Mankybus** [comment]
Ah what I meant is people suggested simply inputing `lutris -d` into the terminal before, whereas the method you suggested got the debugging to work just fine :) As for the compressed .ico, I accidentally clicked on that instead of the uncompressed one (testing .ico files in gimp and accidentally saved a compressed one beforehand), that's on me sorry about that!

As for my Lutris install, I'm not sure if the errors have shown that I'm on version 0.5.17-4, but since I'm on Garuda Linux it just uses the version of Lutris found in the standard Arch repos, the extra repo specifically. Would you recommend I use lutris-git instead? It's in the chaotic-aur so that's as easy as swapping out my install with the git version in less than 10 seconds.

But I think there may also be a slight mix up, using a custom icon helped solve the error, whereas the default icon (the Lutris otter icon) is what's causing the problem, but not for all games, only a select few. I'll post a couple of screenshots for you:

Here I used the generic GOG installer .ico and that was the workaround that stopped the error from occurring, seems like any .png or .ico can help though so it's not specific to this icon
![Screenshot_20240601_174819](https://github.com/lutris/lutris/assets/171376672/8a3e1160-1d9a-4d4c-9460-7f9f4b9c573a)

Here I reset the icon to default, which in turn brought up the default Lutris otter icon and that's where the error popped back up. And then the error disappeared when I reset my icon back to the GOG .ico
![Screenshot_20240601_174844](https://github.com/lutris/lutris/assets/171376672/f3274bc5-d1c4-4379-8b68-b70b11f265b4)

Yeah it's a really strange issue, but I hope this clears up a lot of confusion because I'm bad at explaining stuff :smiling_face_with_tear:

**Comment by danieljohnson2** [comment]
Well, the 'default icon' is what you get when you have not selected any icon. Lutris tries to extract an icon from the .exe in that case.

I don't think you should use lutris-git; you have a workaround- set the icon to something explicitly and that prevents the problem.

**Comment by Mankybus** [comment]
I can certainly live with the workaround for now since it is a very minor issue on closer inspection, but would be great to see it fixed in a future update just in case there are people also experiencing this problem and haven't posted about it yet and don't know of this workaround :+1:

**Comment by danieljohnson2** [comment]
It is my belief that this issue is fixed in the master branch, and will be fixed in 0.5.18. I just haven't been able to get a clear confirmation.

**Comment by Mankybus** [comment]
Ah right! Well when 5.18 release goes live I'll be sure to do my usual test and I'll report whether the problem is fixed or if it persists at that point. That'll be the best way for me to help check that :)

**Comment by spiffeeroo** [comment]
Make sure the Executable under Game Options in Lutris is "/GOG Games/Warhammer Chaosbane/Exe/Chaosbane.exe". If it is "/GOG Games/Warhammer Chaosbane/Launch Warhammer - Chaosbane.lnk", you will experience that icon extraction bug in Lutris 0.5.17. If the exectuable file is a script, shortcut link, or something like that, Lutris will fail trying to extract non-existent icons from that file.

**Comment by Mankybus** [comment]
Hey, I did set the executable to the .exe before a couple of days ago and it gave me the same error as before. However upon giving it another try today via your suggestion, Lutris ended up freezing and crashing. But when reopening it and checking the game configuration, Lutris did end up using the .exe's icon. Which of course avoided the DOS header magic error as it doesn't use that default Lutris otter anymore.

I haven't done any system updates or even restarted my system since, very peculiar how it's behaving differently now. But it seems to work in its strange roundabout way as of right now, luckily restarting Lutris is a minor inconvenience.

**Comment by rambo919** [comment]
Another workaround is by manually editing the relevant yml file in /home/user/.config/lutris/games/ with a text editor
