### ISSUE TITLE
[0.5.17] Disabling DXVK breaks umu + GE-Proton globally

### ISSUE THREAD

**Issue by Gamertech** [lutris/lutris#5506]
### Bug description

Running flatpak Lutris using GE-Proton (Latest) runner option with the PROTONPATH-GE-Proton env, which has been working great since 0.5.17 release.

While testing different configurations for a game with an optional Vulkan client, I disabled DXVK and since then Lutris/umu fails to find the GE-Proton runner and games fail to launch globally when using GE-Proton + env, with the button immediately going from stop to play.

Removing the env so Lutris uses umu-proton loads fine as does swapping to wine-ge, but even with DXVK re-enabled I get the below error when trying actual GE-Proton.

I made one change at a time, so it looks like disabling DXVK somehow breaks umu's ability to locate installed GE-Proton runners, but also prevents Lutris from freshly downloading them.

I can't find where the ge-proton runners are stored in Lutris either so I can't remove them manually to test. They aren't stored in Lutris' runners or umu directories.

### How to Reproduce

1. Install a game/app (DX9-11) of your choice using GE-Proton (Latest) runner with the PROTONPATH=GE-Proton env
2. Launch the app once to download GE-Proton and close
3. In the Lutris options for the app, disable DXVK and save
4. Launch app with logs visible and test
5. Re-enable DXVK and attempt to launch again

### Expected behavior

Lutris/umu should continue to be able to correctly locate Proton regardless of DXVK status and shouldn't be rendered unusable afterwards.

### Log output

```shell
gamertech@radium:~$ flatpak run net.lutris.Lutris -d
2024-06-06 17:25:07,105: Command 'fluidsynth' not found on your system
qdbus: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
INFO     2024-06-06 17:25:07,390 [application.do_command_line:479]:Starting Lutris 0.5.17
MESA: error: Use of VkSurfacePresentModeCompatibilityEXT without a VkSurfacePresentModeEXT set. This is an application bug.
MESA: error: Use of VkSurfacePresentModeCompatibilityEXT without a VkSurfacePresentModeEXT set. This is an application bug.
INFO     2024-06-06 17:25:07,447 [startup.run_all_checks:120]:AMD Radeon RX 7900 XT (1002:744c 148c:2423 amdgpu) Driver 24.0.7
DEBUG    2024-06-06 17:25:07,609 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-06 17:25:07,611 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
DEBUG    2024-06-06 17:25:07,669 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-06 17:25:07,698 [api.check_stale_runtime_versions:52]:Modified at Thu 06 Jun 2024 11:32:13, will update after Thu 06 Jun 2024 17:32:13
DEBUG    2024-06-06 17:25:07,710 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-06-06 17:25:12,176 [application.show_window:394]:Showing window EditGameConfigDialog8
DEBUG    2024-06-06 17:25:12,937 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-06 17:25:12,940 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
DEBUG    2024-06-06 17:25:14,730 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-06-06 17:25:14,732 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
DEBUG    2024-06-06 17:25:14,733 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-06-06 17:25:14,735 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
DEBUG    2024-06-06 17:25:14,736 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-06 17:25:14,738 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
DEBUG    2024-06-06 17:25:14,741 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-06 17:25:14,743 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
DEBUG    2024-06-06 17:25:14,745 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-06 17:25:14,747 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
DEBUG    2024-06-06 17:25:17,199 [application.on_app_window_destroyed:419]:Removed window EditGameConfigDialog8
INFO     2024-06-06 17:25:21,084 [runner.use_runtime:413]:Runtime disabled by system configuration
INFO     2024-06-06 17:25:21,085 [runner.use_runtime:413]:Runtime disabled by system configuration
DEBUG    2024-06-06 17:25:21,086 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-06-06 17:25:21,088 [xrandr._get_vidmodes:18]:Retrieving 132 video modes from XrandR
Started initial process 59 from /home/gamertech/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py /mnt/games/Lutris/star-citizen/drive_c/Program Files/Roberts Space Industries/RSI Launcher/RSI Launcher.exe --locale=$INPUT_LOCALE
Start monitoring process.
GE-Proton is up to date
ERROR:  BaseException
Traceback (most recent call last):
  File "/home/gamertech/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py", line 387, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gamertech/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py", line 379, in main
    build_command(env, UMU_LOCAL, command, opts)
  File "/home/gamertech/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py", line 251, in build_command
    raise FileNotFoundError(err)
FileNotFoundError: The following file was not found in PROTONPATH: proton
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
DEBUG    2024-06-06 17:25:22,149 [monitored_command.on_stop:228]:Process 57 has terminated with code 0
DEBUG    2024-06-06 17:25:23,105 [game.beat:924]:Game thread stopped
WARNING  2024-06-06 17:25:23,105 [game.on_game_quit:962]:Game still running (state: running)
INFO     2024-06-06 17:25:23,105 [game.stop:935]:Stopping Star Citizen (wine)
DEBUG    2024-06-06 17:25:23,105 [game.stop_game:891]:Star Citizen (wine) has run for 2 seconds
WARNING  2024-06-06 17:25:23,106 [game.stop_game:893]:The game has run for a very short time, did it crash?
DEBUG    2024-06-06 17:25:23,106 [application.on_game_stopped:794]:Removing 8 from running IDs
DEBUG    2024-06-06 17:25:23,119 [game.stop_game:903]:Playtime: 51 hours 56 minutes
DEBUG    2024-06-06 17:25:23,119 [game.on_game_quit:980]:Star Citizen stopped at Thu, 06 Jun 2024 17:25:23
DEBUG    2024-06-06 17:25:23,178 [path_cache.add_to_path_cache:47]:Adding Star Citizen (wine) to path cache
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: NO
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.8.12-300.fc40.x86_64
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900X 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 31.3 GB
Swap: 46.9 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.8.12-300.fc40.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.7 (git-cc175010c5)
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.7 (git-cc175010c5)
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.7 (git-cc175010c5)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon RX 7900 XT (RADV NAVI31) (1.3.274)
```

**Comment by Gamertech** [comment]
Found the install location. Apparently Lutris installs to .local/share/Steam/compatibilitytools.d/ even using the flatpak.

9-6/9-5 directories are ~1.2GB
9-7 is only 0.6GB

Deleting the 9-7 directory and relaunching a game with GE-Proton (latest) successfully re-downloaded it and launched correctly. So it does look like Lutris grabbed the brand new release too soon and stuck with it.

**Comment by R1kaB3rN** [comment]
Lutris currently delegates the downloading of Proton and the runtime to umu-launcher (RC4), and one case this can happen is if the Proton download had exceeded its timeout. This would make sense as I see GE-Proton was only partially downloaded. However, I don't see anything in the logs that would indicate the request had timed out. 

In any case, the [latest branch of umu launcher](https://github.com/Open-Wine-Components/umu-launcher/tree/dc41d603ceae2d644c274dc94dd40f97d49325d0) has since removed those timeouts and I believe in the future Lutris plans to implement functionality for downloading Proton themselves. At that point, Lutris would be in a position to add the features you asked for.

**Comment by legluondunet** [comment]
obsolete issue
