### ISSUE TITLE
Can't install Escape From Tarkov (EndeavourOS)

### ISSUE THREAD

**Issue by AzyWng** [lutris/lutris#5512]
### Bug description

Whenever I attempt to install Escape From Tarkov on my computer - whenever I attempt to install it using 

### How to Reproduce

1. Use 
2. Try to install Escape From Tarkov through the installer on the Lutris Website (search the website for Lutris installers, type in tarkov).
3. When prompted, choose to download the installer.
4. Get a "File path not found" error after the installer is downloaded. A similar issue occurs when I download the installer personally and select it during installation.

### Expected behavior

I expected to be able to download the Battlestate Games Launcher and from there install Escape From Tarkov.

### Log output

```shell
\2024-06-09 15:09:10,087: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-06-09 15:09:10,234 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-06-09 15:09:10,262 [startup.run_all_checks:120]:Intel UHD Graphics (8086:9bc4 1462:12b9 i915) Driver None
INFO     2024-06-09 15:09:10,325 [startup.run_all_checks:120]:NVIDIA GeForce GTX 1660 Ti (10de:2191 1462:12b9 nvidia) Driver 550.78
DEBUG    2024-06-09 15:09:10,443 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-09 15:09:10,553 [xrandr._get_vidmodes:18]:Retrieving 101 video modes from XrandR
DEBUG    2024-06-09 15:09:10,610 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-09 15:09:10,640 [api.check_stale_runtime_versions:52]:Modified at Sun 09 Jun 2024 02:56:50 PM , will update after Sun 09 Jun 2024 08:56:50 PM 
DEBUG    2024-06-09 15:09:10,650 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
ERROR    2024-06-09 15:09:10,665 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
DEBUG    2024-06-09 15:09:13,469 [application.show_window:394]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x73e0cf5b5fc0 (LutrisWindow at 0x628798ff2e10)>}
DEBUG    2024-06-09 15:09:15,505 [http._request:88]:GET https://lutris.net/api/games?search=tar&with-installers=True
DEBUG    2024-06-09 15:09:20,266 [http._request:88]:GET https://lutris.net/api/games?search=tarkov&with-installers=True
DEBUG    2024-06-09 15:09:41,077 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/escape-from-tarkov
DEBUG    2024-06-09 15:09:41,077 [http._request:88]:GET https://lutris.net/api/installers/escape-from-tarkov
DEBUG    2024-06-09 15:09:41,077 [application.on_app_window_destroyed:419]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x73e0cf5b5fc0 (LutrisWindow at 0x628798ff2e10)>}
DEBUG    2024-06-09 15:09:46,708 [application.show_window:394]:Showing window InstallerWindowescape-from-tarkov
DEBUG    2024-06-09 15:09:48,322 [xrandr._get_vidmodes:18]:Retrieving 101 video modes from XrandR
DEBUG    2024-06-09 15:09:54,957 [installerwindow.on_files_prepared:608]:Game files prepared.
DEBUG    2024-06-09 15:09:54,959 [installerwindow.present_installer_files_page:623]:Presenting installer files page
DEBUG    2024-06-09 15:09:55,932 [downloader.start:60]:⬇ https://prod.escapefromtarkov.com/launcher/download
DEBUG    2024-06-09 15:10:44,354 [downloader.on_download_completed:166]:Finished downloading https://prod.escapefromtarkov.com/launcher/download
INFO     2024-06-09 15:10:44,497 [file_box.on_download_complete:223]:Download completed
DEBUG    2024-06-09 15:10:44,497 [files_box.on_file_available:108]:eft is available
INFO     2024-06-09 15:10:44,498 [files_box.on_file_available:114]:All files available
INFO     2024-06-09 15:10:44,498 [installerwindow.on_files_available:653]:All files are available, continuing install
INFO     2024-06-09 15:10:44,498 [installerwindow.launch_installer_commands:661]:Launching installer commands
DEBUG    2024-06-09 15:10:44,499 [interpreter._iter_commands:315]:Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2024-06-09 15:10:44,559 [wine.create_prefix:108]:Creating a win64 prefix in /run/media/arthurzw/ArthursStuff/Games/EFT
INFO     2024-06-09 15:10:44,571 [wine.create_prefix:126]:Winepath: GE-Proton (Latest)
ERROR    2024-06-09 15:10:44,571 [jobs.target:32]:Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x73e0cf66ee80>: <class 'FileNotFoundError'> [Errno 2] No such file or directory
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 325, in dispatch
    return method(params)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/commands.py", line 432, in task
    command = task(**data)
              ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/commands/wine.py", line 158, in create_prefix
    wineenv["PROTONPATH"] = proton.get_proton_path_from_bin(wine_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/wine/proton.py", line 99, in get_proton_path_from_bin
    return os.path.abspath(os.path.join(os.path.dirname(wine_path), "../../"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 423, in abspath
ERROR    2024-06-09 15:10:44,572 [interpreter._iter_commands:300]:Last install command failed, show error
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: EndeavourOS rolling rolling
Arch: x86_64
Kernel: 6.9.3-arch1-1
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 15.4 GB
Swap: 8.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 550.78
OpenGL Core: 4.6.0 NVIDIA 550.78
OpenGL ES: OpenGL ES 3.2 NVIDIA 550.78
Vulkan Version: 1.3.279
Vulkan Drivers: NVIDIA GeForce GTX 1660 Ti (1.3.277), Intel(R) UHD Graphics (CML GT2) (1.3.278)
```

**Comment by danieljohnson2** [comment]
Well, I think I see what's going on, but I don't understand what @strycore intended here.

You're using "GE-Proton (latest)" as your Wine version, which you've configured in the 'Wine' runner configuration- I think. That's not working; ``get_executable()`` arbitrarily returns "GE-Proton (latest)" if you are using this version, not the path to the Wine executable. That is reporting in your debug log, it's the "Winepath"; but this is not a path.

Lots of things call this method and all would need to detect and handle this. Most don't.

The Tarkov installer is trying to create a Wine prefix, which is one of the things that is broken in this way.

I do not know how this is every supposed to work. I think you should probably change to a non-experimental Wine version to install with at least.

**Comment by AzyWng** [comment]
You're right, I didn't choose the correct Wine version. When I chose wine-9.10-amd64 (from [here](https://github.com/Kron4ek/Wine-Builds/releases)), I managed to get a bit farther - though I still wasn't able to run the BSG launcher or download and install Tarkov.

Here's what the console gave me this time - it's pretty long so I couldn't just paste it into the comment itself.
[lutristarkovlogoutput.txt](https://github.com/user-attachments/files/15755551/lutristarkovlogoutput.txt)

**Comment by danieljohnson2** [comment]
I'm afraid I don't see anything in there that helps; your issue may be a Wine issue, or an issue with the game itself.
