### ISSUE TITLE
EGS Source error

### ISSUE THREAD

**Issue by zefie** [lutris/lutris#5516]
### Bug description

Lutris cannot list my installed Epic Games. Everything works fine if I launch the Epic Store and launch my games through there, but if I click the refresh icon next to "Epic Games Store" under "Sources", I get this error. I have tried with the latest release deb, and the latest master branch code, both produce the issue for me.

### How to Reproduce

1. Log into EGS with Lutris
2. Click on the refresh icon

### Expected behavior

Lutris to list my EGS games

### Log output

```shell
zefie@zefie-desktop:~/dev/git/lutris$ lutris -d
INFO     2024-06-12 11:43:59,159 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-06-12 11:43:59,239 [startup.run_all_checks:120]:NVIDIA GeForce RTX 3060 Ti (10de:2489 1458:405e nvidia) Driver 535.171.04
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/./vulkaninfo.h:458:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-06-12 11:43:59,257 [system.read_process_output:189]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
DEBUG    2024-06-12 11:43:59,257 [system._execute:109]:Executing lspci
INFO     2024-06-12 11:43:59,267 [startup.run_all_checks:120]:No GPU (simple-framebuffer) Driver None
DEBUG    2024-06-12 11:43:59,423 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-12 11:43:59,520 [xrandr._get_vidmodes:18]:Retrieving 28 video modes from XrandR
DEBUG    2024-06-12 11:43:59,567 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-12 11:43:59,596 [api.check_stale_runtime_versions:52]:Modified at Wed 12 Jun 2024 11:34:15 AM , will update after Wed 12 Jun 2024 05:34:15 PM 
DEBUG    2024-06-12 11:43:59,596 [lutriswindow.create_runtime_updater_cb:1249]:Runtime up to date
DEBUG    2024-06-12 11:44:07,410 [base.wipe_game_cache:465]:Deleting egs cache /home/zefie/.cache/lutris/egs-library.json
DEBUG    2024-06-12 11:44:07,410 [base.wipe_game_cache:176]:Deleting games from service-games for egs
ERROR    2024-06-12 11:44:19,281 [jobs.target:33]:Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7dabe09f4860>: <class 'KeyError'> 'appName'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 31, in target
    result = self.function(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 143, in do_reload
    self.load()
  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 301, in load
    egs_game = EGSGame.new_from_api(game)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 131, in new_from_api
    service_game.appid = egs_game["appName"]
                         ~~~~~~~~^^^^^^^^^^^
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 24.04 Noble Numbat
Arch: x86_64
Kernel: 6.8.0-35-generic
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 5600X 6-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 31.3 GB
Swap: 0.5 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 535.171.04
OpenGL Core: 4.6.0 NVIDIA 535.171.04
OpenGL ES: OpenGL ES 3.2 NVIDIA 535.171.04
Vulkan Version: 1.3.275
Vulkan Drivers: NVIDIA GeForce RTX 3060 Ti (1.3.242)
```

**Comment by danieljohnson2** [comment]
That is really strange. I don't know how we can handle a game missing the 'appName' that identifies it.

I've [prepared a branch](https://github.com/lutris/lutris/tree/dj/egs_has_betrayed_you) for you. Please download this branch and run the ``bin/lutris`` script within; no need to install it. Just run it, reload the EGS source again, and give us the log output.

I've added code to continue after this error and also to log some information that may help us understand this. Hopefully we will see what game is causing this.

Also, please let us know if you can get any of your library to show up with this branch.

**Comment by zefie** [comment]
The first time I tried it worked without error, so I hit refresh then it happened. 

```
DEBUG    2024-06-12 19:35:48,808 [base.wipe_game_cache:465]:Deleting egs cache /home/zefie/.cache/lutris/egs-library.json
DEBUG    2024-06-12 19:35:48,808 [base.wipe_game_cache:176]:Deleting games from service-games for egs
ERROR    2024-06-12 19:35:59,852 [egs.load:304]:Unable to interpret EGS game: 'appName'
Traceback (most recent call last):
  File "/home/zefie/dev/git/lutris/lutris/services/egs.py", line 302, in load
    egs_game = EGSGame.new_from_api(game)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zefie/dev/git/lutris/lutris/services/egs.py", line 131, in new_from_api
    service_game.appid = egs_game["appName"]
                         ~~~~~~~~^^^^^^^^^^^
KeyError: 'appName'
INFO     2024-06-12 19:35:59,853 [egs.load:305]:EGS game skipped: {'namespace': 'fn', 'catalogItemId': 'c6cb1a1d11f54fab8e17301f66bc27a4', 'productId': 'prod-fn', 'sandboxName': 'Fortnite', 'sandboxType': 'PUBLIC', 'recordType': 'SUBSCRIPTION', 'acquisitionDate': '2024-05-03T02:42:17.855Z', 'dependencies': [], 'id': 'c6cb1a1d11f54fab8e17301f66bc27a4', 'title': 'Fortnite Crew', 'description': 'Fortnite Crew', 'keyImages': [], 'categories': [{'path': 'points'}], 'status': 'ACTIVE', 'creationDate': '2020-02-11T01:33:36.868Z', 'lastModifiedDate': '2022-11-04T02:27:24.636Z', 'customAttributes': {}, 'entitlementName': 'FN_Crew', 'entitlementType': 'SUBSCRIPTION', 'entitlementStartDate': '2020-02-11T00:00:00.000Z', 'itemType': 'SUBSCRIPTION', 'releaseInfo': [], 'developer': 'Epic Games', 'developerId': 'o-aa83a0a9bc45e98c80c1b1c9d92e9e', 'eulaIds': [], 'installModes': [], 'endOfSupport': False, 'ageGatings': {}, 'applicationId': '', 'unsearchable': True}
INFO     2024-06-12 19:36:00,748 [egs.add_installed_games:348]:EGS detected in /home/zefie/Games/epic-games-store
DEBUG    2024-06-12 19:36:00,749 [egs.install_from_egs:314]:Installing EGS game Puffin
DEBUG    2024-06-12 19:36:00,749 [egs.install_from_egs:314]:Installing EGS game 3017c57256b640519e6b84b44a4ac940
DEBUG    2024-06-12 19:36:00,750 [egs.install_from_egs:314]:Installing EGS game 019b8e62a48c4278ac5ca98d7986cd75
DEBUG    2024-06-12 19:36:00,751 [egs.install_from_egs:314]:Installing EGS game 7458160f5c18450cad7e95844a5dcdff
DEBUG    2024-06-12 19:36:00,751 [egs.add_installed_games:359]:All EGS games imported
```

It looks like my having Fortnite Crew may be confusing it?

**Comment by danieljohnson2** [comment]
Ah, I think that may be it. This thing isn't a game but a subscription, and there's nothing Lutris should be installing. We should just skip this thing, I would imagine.

Did you manage to get your actual games loaded? In particular, did it load Fortnite itself?

**Comment by zefie** [comment]
It seemed to have loaded my entire library, with thumbnails and all, including Fortnite.

**Comment by danieljohnson2** [comment]
I think that's it then. I'll add code to skip appName-less "games" like this to the master for the next release.

If you're willing, give [the master branch](https://github.com/lutris/lutris) a try just like that branch- just to make sure I got it right.

It should silently skip this "game" and not give you the same log spam as the branch had.

**Comment by zefie** [comment]
Works as intended, thanks!
