### ISSUE TITLE
Amazon Prime Gaming installs fail with 'Unable to get game manifest info'

### ISSUE THREAD

**Issue by twingofan** [lutris/lutris#5517]
### Bug description

When attempting to install games through the Amazon Prime installer, Lutris fails with an 'Unable to get game manifest info' error. This doesn't seem to be game-specific, all of 10 randomly-chosen games in my library failed to install with the same error. Additionally, games which are already installed run with no issue.
A similar issue is currently active with the Heroic launcher (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3816) due to an outdated build of Nile. It's possible to override the binary with a fixed version on Heroic, but if there's a similar option under Lutris (or if Lutris even uses Nile) I'm not aware of it.

### How to Reproduce

1. Go to 'Sources -> Amazon Prime'
2. Click on any non-installed game (Planescape Torment: Enhanced Edition was used for the included log output)
3. See 'Lutris has encountered an error: Unable to get game manifest info'

### Expected behavior

Install selected game without any issues.

### Log output

```shell
2024-06-13 19:10:18,473: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-06-13 19:10:18,559 [application.do_command_line:479]:Starting Lutris 0.5.17
WARNING: [Loader Message] Code 0 : loader_scan_for_direct_drivers: The VK_LUNARG_direct_driver_loading extension was enabled but the pNext chain of VkInstanceCreateInfo did not contain the VkDirectDriverLoadingListLUNARG structure.
INFO     2024-06-13 19:10:18,607 [startup.run_all_checks:120]:AMD Radeon RX 6800 (1002:73bf 1002:0e3a amdgpu) Driver 24.1.1
DEBUG    2024-06-13 19:10:18,706 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-13 19:10:18,712 [xrandr._get_vidmodes:18]:Retrieving 25 video modes from XrandR
DEBUG    2024-06-13 19:10:18,772 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-13 19:10:18,808 [api.check_stale_runtime_versions:52]:Modified at Thu 13 Jun 2024 07:08:45 PM , will update after Fri 14 Jun 2024 01:08:45 AM
DEBUG    2024-06-13 19:10:18,849 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-06-13 19:10:32,863 [lutriswindow.on_game_activated:1190]:Looking up amazon game f4c417fe-740b-700c-ca10-c46bb818da0d
DEBUG    2024-06-13 19:10:32,864 [base.install:322]:Installing f4c417fe-740b-700c-ca10-c46bb818da0d from service amazon
DEBUG    2024-06-13 19:10:32,864 [http._request:88]:POST https://lutris.net/api/games/service/amazon
DEBUG    2024-06-13 19:10:33,084 [http._request:88]:POST https://sds.amazon.com/amazon/
ERROR    2024-06-13 19:10:33,221 [amazon.request_sds:417]:Failed http request https://sds.amazon.com/amazon/: HTTP Error 404: Not Found
ERROR    2024-06-13 19:10:33,222 [amazon.get_game_manifest_info:442]:There was an error getting game manifest: f4c417fe-740b-700c-ca10-c46bb818da0d
ERROR    2024-06-13 19:10:33,222 [jobs.target:32]:Error while completing task <bound method BaseService.get_service_installers of <amazon.AmazonService object at 0x7f9f594c2640 (lutris+services+amazon+AmazonService at 0x5557133277c0)>>: <class 'lutris.exceptions.UnavailableGameError'> Unable to get game manifest info
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 300, in get_service_installers
    installer = self.generate_installer(db_game) if not update else None
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/amazon.py", line 642, in generate_installer
    manifest_info = self.get_game_manifest_info(game_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/amazon.py", line 443, in get_game_manifest_info
    raise UnavailableGameError(_("Unable to get game manifest info"))
ERROR    2024-06-13 19:10:33,223 [exception_backstops.error_wrapper:110]:Error handling idle function: Unable to get game manifest info
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 57, in discarding_result
    function(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 339, in on_service_installers_loaded
    raise error  # bounce this error off the backstop for default handling
    ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 300, in get_service_installers
    installer = self.generate_installer(db_game) if not update else None
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/amazon.py", line 642, in generate_installer
    manifest_info = self.get_game_manifest_info(game_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/amazon.py", line 443, in get_game_manifest_info
    raise UnavailableGameError(_("Unable to get game manifest info"))
lutris.exceptions.UnavailableGameError: Unable to get game manifest info
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Void rolling void
Arch: x86_64
Kernel: 6.6.32_1
Desktop: KDE
Display Server: tty
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5800X3D 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 31.3 GB
Swap: 16.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6800 (radeonsi, navi21, LLVM 17.0.6, DRM 3.54, 6.6.32_1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.1
Vulkan Version: 1.3.268
Vulkan Drivers: AMD Radeon RX 6800 (RADV NAVI21) (1.3.278)
```

**Comment by danieljohnson2** [comment]
Not thrilled with the error handling here, but whatever.

The essential message here seems to be "Failed http request https://sds.amazon.com/amazon/: HTTP Error 404: Not Found".

That seems odd; that URL resolves for me (I get face full of youre-not-authorize XML).

Could you visit ``https://sds.amazon.com/amazon/`` with your web-browser. Do you get a 404 or some other error?

**Comment by twingofan** [comment]
I get:
```
<NotAuthorizedException>
  <Message>Request must provide an Amazon OAuth token.</Message>
</NotAuthorizedException>
```

**Comment by danieljohnson2** [comment]
Weird. I get the same result, but that does not look like a 404 to me. But the log says it's a 404.

**Comment by Blkez** [comment]
I'm also getting the same error when trying to install any Amazon game with Lutris. Also getting same XML result when accessing the SDS url on browser

**Comment by GamerWierdo100** [comment]
I am currently experiencing the same issue.

**Comment by wnieuwstraten** [comment]
Exact same message for me

**Comment by danieljohnson2** [comment]
Lots of people having this. Does Amazon Prime Gaming work right for anybody?

**Comment by GamerWierdo100** [comment]
This is a pretty critical issue, I mean, a whole source is borked

**Comment by imLinguin** [comment]
@danieljohnson2 they changed the endpoint and a few calls you can refer to https://github.com/imLinguin/nile/commit/1483b1dc7964af735dc18cbf2ef804ccd777d82f on what needs changes

**Comment by danieljohnson2** [comment]
Thanks for that information, @imLinguin.

I'm afraid that looks like a lot more change that I can handle 'blind'; I have no Amazon Prime Gaming account, so I'd have to to guess at it and hand a branch to you guys for testing. But that'd never work on this scale; someone with an account will have to do it.

**Comment by ralftreu** [comment]
Thanks for the fix! Worked for me too, tried with several games.

**Comment by Para96** [comment]
> Thanks for the fix! Worked for me too, tried with several games.

This might be a stupid question but I see that this was pushed on 2 july but the latest version is from 11 april. How did you install this fix then?

**Comment by ralftreu** [comment]
@Para96 , I just pulled this branch and started lutris from it...

**Comment by legluondunet** [comment]
Is this issue still present?

**Comment by Philantrop** [comment]
> Is this issue still present?

I've experienced this issue consistently before, but couldn't reproduce it today. My testing was limited to the two games I have on Amazon, though.

**Comment by legluondunet** [comment]
I own some games on Amazon:

<img width="883" height="505" alt="Image" src="https://github.com/user-attachments/assets/f2bd6640-73fc-4baa-92e4-c4d8bf89433b" />

I tried to reproduce this issue with Lutris 0.5.20 beta (actual Github code):
- added Amazon source in left Lutris panel: OK
- identify Amazon in Lutris: OK
- Install Figment 2 game: install OK

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d1c127c9-dbd8-47d0-a44f-bed46d6e364e" />
- tried to install other games: Lighmatter, Turok, Zombies hate my neighbours and ghoul patrol, The almost gone...
All OK

I can not reproduce this issue with our latest code, I close this issue.
