### ISSUE TITLE
Fedora 40 - error: 'utf-8' codec can't decode byte 0x8a in position 

### ISSUE THREAD

**Issue by Noczio** [lutris/lutris#5518]
### Bug description

There're some programs from steam that give an error code whenever I execute them from Lutris in a fresh install of Fedora 40

### How to Reproduce

1. Go to 'Lutris.'
2. Click on 'any game/software' Like Aseprite and 3DMark, Sky: Children of the light. 
4. See error: 'utf-8' codec can't decode byte 0x8a in position 6359: invalid start byte (Aseprite) 'utf-8' codec can't decode byte 0x8a in position 4514: invalid start byte (3DMark), utf-8' codec can't decode byte 0x8a in position 3376: invalid start byte (Sky: Children of the light)

### Expected behavior

No message at all, it's an error afterall

### Log output

```shell
'utf-8' codec can't decode byte 0x8a in position 6359: invalid start byte

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 31, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 919, in beat
    game_pids = self.get_game_pids()
                ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 876, in get_game_pids
    uuid_pids = set(pid for pid in new_pids if Process(pid).environ.get("LUTRIS_GAME_UUID") == self.game_uuid)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 876, in <genexpr>
    uuid_pids = set(pid for pid in new_pids if Process(pid).environ.get("LUTRIS_GAME_UUID") == self.game_uuid)
                                               ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/process.py", line 111, in environ
    _environ_text = self._read_content(environ_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/process.py", line 33, in _read_content
    content = proc_file.read()
              ^^^^^^^^^^^^^^^^

  File "<frozen codecs>", line 322, in decode

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 6359: invalid start byte
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Fedora Linux 40 Workstation Edition
Arch: x86_64
Kernel: 6.8.11-300.fc40.x86_64
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 31.2 GB
Swap: 8.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 18.1.6, DRM 3.57, 6.8.11-300.fc40.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.1
Vulkan Version: 1.3.283
Vulkan Drivers: AMD Radeon RX 6700 XT (RADV NAVI22) (1.3.278)
```

**Comment by danieljohnson2** [comment]
I think this is straightforward; it's choking on non UTF-8 encoded data in the environment of another process. Lutris really only cares about it's own env-vars, which are pure ASCII anyway, so we have no need to decode this stuff- but we get the whole environment and have to parse it.

I've tweak it to replace undecodable stuff with placeholders; this should not affect anything we care about.

If you would @Noczio, please download [the latest master](https://github.com/lutris/lutris) and try the ``bin/lutris`` script within. No need to install; see if this will run your game and let us known. Thank you!
