### ISSUE TITLE
Unable to update GOG games

### ISSUE THREAD

**Issue by mintdaniel42** [lutris/lutris#5522]
### Bug description

Lutris doesn't properly update Gog games. Some (linux) games like Sigma Theory: Global Cold War get only suggested updates of the windows version via wine although I installed the linux one while others like Space Haven don't even get **any updates at all**. For them it just always says
```
No updates found

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 57, in discarding_result
    function(*args, **kwargs)

  File "/app/lib/python3.11/site-packages/lutris/game.py", line 378, in on_installers_ready
    raise RuntimeError(_("No updates found"))

RuntimeError: No updates found
```

### How to Reproduce

1. Go to a Linux GOG game like the ones mentioned above
2. Click on 'update'
4. See the error

### Expected behavior

Just update

### Log output

```shell
daniel@Dell-Latitude-e6430:~$ flatpak run net.lutris.Lutris -d
Gtk-Message: 18:19:05.687: Failed to load module "xapp-gtk3-module"
2024-06-25 18:19:05,957: Command 'fluidsynth' not found on your system
INFO     2024-06-25 18:19:07,153 [application.do_command_line:479]:Starting Lutris 0.5.17
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
MESA: error: Use of VkSurfacePresentModeCompatibilityEXT without a VkSurfacePresentModeEXT set. This is an application bug.
INFO     2024-06-25 18:19:07,240 [startup.run_all_checks:120]:Intel HD Graphics 4000 (8086:0166 1028:0534 i915) Driver 24.1.1
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
WARNING  2024-06-25 18:19:07,298 [startup.check_vulkan:84]:Vulkan reports that the 'Intel(R) HD Graphics 4000 (IVB GT2)' device has API version of 1.2.278. 1.3.0 is required for the latest DXVK.
DEBUG    2024-06-25 18:19:07,806 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-25 18:19:07,829 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-06-25 18:19:08,228 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-25 18:19:08,411 [api.check_stale_runtime_versions:52]:Modified at Di 25 Jun 2024 18:12:24 , will update after Mi 26 Jun 2024 00:12:24 
DEBUG    2024-06-25 18:19:08,740 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-06-25 18:19:09,242 [http._request:88]:POST https://lutris.net/api/users/library?since=1719331945
INFO     2024-06-25 18:19:12,704 [gog.get_game_details:284]:Getting game details for 1589675197
DEBUG    2024-06-25 18:19:12,754 [http._request:88]:GET https://api.gog.com/products/1589675197?expand=downloads&locale=de-DE
INFO     2024-06-25 18:19:12,945 [gog.get_update_versions:368]:No patches for {'id': 1589675197, 'title': 'Space Haven', 'purchase_link': 'https://www.gog.com/en/checkout/manual/1589675197', 'slug': 'space_haven', 'content_system_compatibility': {'windows': True, 'osx': True, 'linux': False}, 'languages': {'br': 'Português do Brasil', 'cn': '中文(简体)', 'cz': 'český', 'de': 'Deutsch', 'en': 'English', 'es': 'español', 'fr': 'français', 'it': 'italiano', 'jp': '日本語', 'ko': '한국어', 'pl': 'polski', 'ru': 'русский', 'tr': 'Türkçe'}, 'links': {'purchase_link': 'https://www.gog.com/en/checkout/manual/1589675197', 'product_card': 'https://www.gog.com/en/game/space_haven', 'support': 'https://www.gog.com/support/space_haven', 'forum': 'https://www.gog.com/forum/space_haven'}, 'in_development': {'active': True, 'until': None}, 'is_secret': False, 'is_installable': True, 'game_type': 'game', 'is_pre_order': False, 'release_date': '2020-05-21T19:55:00+0300', 'images': {'background': '//images-3.gog-statics.com/34f7c712002a84e1f3a86d6b2ad8d00c28221ebbbd0ea0354117af2e712db6ec.jpg', 'logo': '//images-2.gog-statics.com/47ba31d8b1bb5c5cc416f2dcacec90d86054ba34f5468c1423cc5bdbf7e8ff78_glx_logo.jpg', 'logo2x': '//images-4.gog-statics.com/47ba31d8b1bb5c5cc416f2dcacec90d86054ba34f5468c1423cc5bdbf7e8ff78_glx_logo_2x.jpg', 'icon': '//images-2.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913.png', 'sidebarIcon': '//images-3.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_sbicon.png', 'sidebarIcon2x': '//images-2.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_sbicon_2x.png', 'menuNotificationAv': '//images-4.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_menu_notification_av.png', 'menuNotificationAv2': '//images-3.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_menu_notification_av2.png'}, 'dlcs': {'products': [{'id': 1123251949, 'link': 'https://api.gog.com/products/1123251949', 'expanded_link': 'https://api.gog.com/products/1123251949?expand=downloads'}], 'all_products_url': 'https://api.gog.com/products?ids=1123251949', 'expanded_all_products_url': 'https://api.gog.com/products?ids=1123251949&expand=downloads'}, 'downloads': {'installers': [{'id': 'installer_windows_en', 'name': 'Space Haven', 'os': 'windows', 'language': 'en', 'language_full': 'English', 'version': '0.19.0.15', 'total_size': 229638144, 'files': [{'id': 'en1installer0', 'size': 229638144, 'downlink': 'https://api.gog.com/products/1589675197/downlink/installer/en1installer0'}]}, {'id': 'installer_mac_en', 'name': 'Space Haven', 'os': 'mac', 'language': 'en', 'language_full': 'English', 'version': '0.19.0.15', 'total_size': 375390208, 'files': [{'id': 'en2installer0', 'size': 375390208, 'downlink': 'https://api.gog.com/products/1589675197/downlink/installer/en2installer0'}]}, {'id': 'installer_linux_en', 'name': 'Space Haven', 'os': 'linux', 'language': 'en', 'language_full': 'English', 'version': '0.19.0.15', 'total_size': 224395264, 'files': [{'id': 'en3installer0', 'size': 224395264, 'downlink': 'https://api.gog.com/products/1589675197/downlink/installer/en3installer0'}]}], 'patches': [], 'language_packs': [], 'bonus_content': []}}
ERROR    2024-06-25 18:19:12,955 [exception_backstops.error_wrapper:110]:Error handling idle function: No updates found
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 57, in discarding_result
    function(*args, **kwargs)
  File "/app/lib/python3.11/site-packages/lutris/game.py", line 378, in on_installers_ready
    raise RuntimeError(_("No updates found"))
RuntimeError: No updates found
```
```


### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.2.0-39-generic
Desktop: X-Cinnamon
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 15.5 GB
Swap: 2.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version: 4.2 (Compatibility Profile) Mesa 24.1.1 (git-6c377358a5)
OpenGL Core: 4.2 (Core Profile) Mesa 24.1.1 (git-6c377358a5)
OpenGL ES: OpenGL ES 3.0 Mesa 24.1.1 (git-6c377358a5)
Vulkan Version: 1.3.261
Vulkan Drivers: Intel(R) HD Graphics 4000 (IVB GT2) (1.2.278)
```

**Comment by danieljohnson2** [comment]
I am not sure why some of your games show no updates; but I see the problem with getting the wrong versions of updates. Lutris simply does not filter the patches at all- you just get them all even if they are not applicable. That seems unsafe.

I'll add a filter so that you get only patches for the OS that corresponds to your runner- the GOG service only supports Windows and Linux, DOS games must be installed in Wine for the patches to work, so if you have installed them in DOSBOX you won't be able to apply them.

**Comment by danieljohnson2** [comment]
@mintdaniel42, please download [the latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within- no need to install. Do you still see it offer inappropriate updates, like Windows updates for Linux installs?

**Comment by ghost** [comment]
1.5 years later: Updates don't work at all. No matter if updates are found or not and independent of the platform this error is shown:

```
Traceback (most recent call last):

  File "/app/lib/python3.13/site-packages/lutris/exception_backstops.py", line 84, in error_wrapper
    return handler(*args, **kwargs)

  File "/app/lib/python3.13/site-packages/lutris/util/jobs.py", line 126, in wrapper
    func(*a, **kw)
    ~~~~^^^^^^^^^^

  File "/app/lib/python3.13/site-packages/lutris/util/busy.py", line 36, in on_completion
    callback(*a, **kw)
    ~~~~~~~~^^^^^^^^^^

  File "/app/lib/python3.13/site-packages/lutris/game.py", line 398, in on_installers_ready
    raise RuntimeError(_("No updates found"))

RuntimeError: No updates found

Lutris log:
[INFO:2026-03-03 12:28:10,722:application]: Starting Lutris 0.5.22
[ERROR:2026-03-03 12:28:10,733:system]: ['/usr/bin/vulkaninfo', '--summary'] command failed: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/usr/bin/vulkaninfo'
[INFO:2026-03-03 12:28:10,937:startup]: "card1" is No GPU (8086:a721 f111:000c i915) Driver 25.3.3
[WARNING:2026-03-03 12:28:13,065:base]: Tried to get auth status while login in progress
[INFO:2026-03-03 12:28:23,797:gog]: Getting game details for 1589675197
[INFO:2026-03-03 12:28:24,376:gog]: No patches for {'id': 1589675197, 'title': 'Space Haven', 'purchase_link': 'https://www.gog.com/en/checkout/manual/1589675197', 'slug': 'space_haven', 'content_system_compatibility': {'windows': True, 'osx': True, 'linux': True}, 'languages': {'br': 'Português do Brasil', 'cn': '中文(简体)', 'cz': 'český', 'de': 'Deutsch', 'en': 'English', 'es': 'español', 'fr': 'français', 'it': 'italiano', 'jp': '日本語', 'ko': '한국어', 'pl': 'polski', 'ru': 'русский', 'tr': 'Türkçe'}, 'links': {'purchase_link': 'https://www.gog.com/en/checkout/manual/1589675197', 'product_card': 'https://www.gog.com/en/game/space_haven', 'support': 'https://www.gog.com/support/space_haven', 'forum': 'https://www.gog.com/forum/space_haven'}, 'in_development': {'active': True, 'until': None}, 'is_secret': False, 'is_installable': True, 'game_type': 'game', 'is_pre_order': False, 'release_date': '2020-05-21T19:55:00+0300', 'images': {'background': '//images-3.gog-statics.com/34f7c712002a84e1f3a86d6b2ad8d00c28221ebbbd0ea0354117af2e712db6ec.jpg', 'logo': '//images-2.gog-statics.com/47ba31d8b1bb5c5cc416f2dcacec90d86054ba34f5468c1423cc5bdbf7e8ff78_glx_logo.jpg', 'logo2x': '//images-4.gog-statics.com/47ba31d8b1bb5c5cc416f2dcacec90d86054ba34f5468c1423cc5bdbf7e8ff78_glx_logo_2x.jpg', 'icon': '//images-2.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913.png', 'sidebarIcon': '//images-3.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_sbicon.png', 'sidebarIcon2x': '//images-2.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_sbicon_2x.png', 'menuNotificationAv': '//images-4.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_menu_notification_av.png', 'menuNotificationAv2': '//images-3.gog-statics.com/728b7f53772679e817eae5a37e381cd740be40fad32cbf7b783ada7df13d7913_menu_notification_av2.png'}, 'dlcs': {'products': [{'id': 1123251949, 'link': 'https://api.gog.com/products/1123251949', 'expanded_link': 'https://api.gog.com/products/1123251949?expand=downloads'}], 'all_products_url': 'https://api.gog.com/products?ids=1123251949', 'expanded_all_products_url': 'https://api.gog.com/products?ids=1123251949&expand=downloads'}, 'downloads': {'installers': [{'id': 'installer_windows_en', 'name': 'Space Haven', 'os': 'windows', 'language': 'en', 'language_full': 'English', 'version': '0.22.0.4', 'total_size': 234881024, 'files': [{'id': 'en1installer0', 'size': 234881024, 'downlink': 'https://api.gog.com/products/1589675197/downlink/installer/en1installer0'}]}, {'id': 'installer_mac_en', 'name': 'Space Haven', 'os': 'mac', 'language': 'en', 'language_full': 'English', 'version': '0.22.0.4', 'total_size': 375390208, 'files': [{'id': 'en2installer0', 'size': 375390208, 'downlink': 'https://api.gog.com/products/1589675197/downlink/installer/en2installer0'}]}, {'id': 'installer_linux_en', 'name': 'Space Haven', 'os': 'linux', 'language': 'en', 'language_full': 'English', 'version': '0.22.0.4', 'total_size': 229638144, 'files': [{'id': 'en3installer0', 'size': 229638144, 'downlink': 'https://api.gog.com/products/1589675197/downlink/installer/en3installer0'}]}], 'patches': [], 'language_packs': [], 'bonus_content': []}}
[ERROR:2026-03-03 12:28:24,377:exception_backstops]: Error handling timeout function: No updates found
Traceback (most recent call last):
  File "/app/lib/python3.13/site-packages/lutris/exception_backstops.py", line 84, in error_wrapper
    return handler(*args, **kwargs)
  File "/app/lib/python3.13/site-packages/lutris/util/jobs.py", line 126, in wrapper
    func(*a, **kw)
    ~~~~^^^^^^^^^^
  File "/app/lib/python3.13/site-packages/lutris/util/busy.py", line 36, in on_completion
    callback(*a, **kw)
    ~~~~~~~~^^^^^^^^^^
  File "/app/lib/python3.13/site-packages/lutris/game.py", line 398, in on_installers_ready
    raise RuntimeError(_("No updates found"))
RuntimeError: No updates found
```

@danieljohnson2 could you please reopen because this is everything but closed / solved

**Comment by ghost** [comment]
The problem is that Lutris tries to fetch patches but ignores games that update the installer only

**Comment by danieljohnson2** [comment]
@mintdaniel42, I don't know if these are really the same issue, but I've made an attempt at addressing #5032. Are you up to giving it a try? If you are not using Flatpak, you should be able to download and run it without installing it- your existing Lutris install will be safe.
