### ISSUE TITLE
Can't open lutris preferences 0.5.17

### ISSUE THREAD

**Issue by manito-manopla** [lutris/lutris#5526]
### Bug description

When I try to open lutris preferences, it fails because of a problem in the python scripts

### How to Reproduce

1. Go to 'lutris'.
2. Click on 'preferences'.

### Expected behavior

The lutris preferences menu should open

### Log output

```shell
'NoneType' object is not subscriptable

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 985, in on_preferences_activate
    self.application.show_window(PreferencesDialog, parent=self)

  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 384, in show_window
    window_inst = window_class(**kwargs)

  File "/usr/lib/python3/dist-packages/lutris/gui/config/preferences_dialog.py", line 67, in __init__
    self.stack.add_named(self.build_scrolled_window(UpdatesBox()), "updates-stack")

  File "/usr/lib/python3/dist-packages/lutris/gui/config/updates_box.py", line 30, in __init__
    update_label_text, update_button_text = self.get_wine_update_texts()

  File "/usr/lib/python3/dist-packages/lutris/gui/config/updates_box.py", line 100, in get_wine_update_texts
    wine_version = f"{wine_version_info['version']}-{wine_version_info['architecture']}"

TypeError: 'NoneType' object is not subscriptable
```

### System Information

```shell
System:    Host: debian Kernel: 5.10.0-30-686 i686 bits: 32 Desktop: i3 4.19.1-non-git Distro: Debian GNU/Linux 11 (bullseye) 
Machine:   Type: Laptop System: Intel product: Intel powered classmate PC v: Clamshell serial: <superuser required> 
           Mobo: Intel model: Intel powered classmate PC v: Clamshell serial: <superuser required> UEFI [Legacy]: Phoenix 
           v: MPSNB10L.10B.0015.2013.0704.2003 date: 07/04/2013 
CPU:       Info: Dual Core model: Intel Celeron 847 bits: 64 type: MCP L2 cache: 2 MiB 
           Speed: 1028 MHz min/max: 800/1100 MHz Core speeds (MHz): 1: 1028 2: 1052 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting unloaded: fbdev,vesa  
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2000 (SNB GT1) v: 3.3 Mesa 20.3.5 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.10.0-30-686
```

**Comment by matis25** [comment]
I'm having exactly the same issue on 0.5.17.

Cannot open preferences when online.

Unwanted internet communication (automatic update checks etc) was previously disabled in settings.

**Comment by danieljohnson2** [comment]
I think this specific crash got a fix back in April. In any case I've made some effort to improve the robustness of the PreferencesDialog.

Please download [the latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within- no need to install. You should be able to open the Preferences dialog and visit the Updates tab without crashing, and change your settings if desired.

Let us know how it goes!

**Comment by matis25** [comment]
Hi, thank you for the information.

I can confirm that the preferences window can be opened in the current `master`.

However, Lutris takes at least 1½ minutes to start. Apparently it's still trying to download something from the internet on startup, and won't open until it times out.

Everything that can be disabled on the "Updates" tab is disabled:
- Wine update channel -> Self-maintained
- Automatically Update the Lutris runtime -> disabled

**Comment by danieljohnson2** [comment]
That is a different issue; you should file that separately, with a full (debug) log. Hopefully we'll be able to tell what it is trying to download.

**Comment by danieljohnson2** [comment]
I think this is fixed.
