### ISSUE TITLE
sqlite3.InterfaceError

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#554]
after this mornings update it throws this to the terminal:

```
  File "/home/user01/src/lutris/lutris/gui/config_dialogs.py", line 396, in on_save
    self.game.save()
  File "/home/user01/src/lutris/lutris/game.py", line 147, in save
    id=self.id
  File "/home/user01/src/lutris/lutris/pga.py", line 213, in add_or_update
    sql.db_update(PGA_DB, "games", params, ('id', game_id))
  File "/home/user01/src/lutris/lutris/util/sql.py", line 75, in db_update
    cursor_execute(cursor, query, field_values + condition_value)
  File "/home/user01/src/lutris/lutris/util/sql.py", line 30, in cursor_execute
    return cursor.execute(query, params)
sqlite3.InterfaceError: Error binding parameter 10 - probably unsupported type.
```

**Comment by telanus** [comment]
Ok Seems one can't save if you modify a game (or just open the game config and choose save), (the one above is just opening a game config and pressing save)

this is the error when changing a game's config:

```
Traceback (most recent call last):
  File "/home/user01/src/lutris/lutris/gui/config_dialogs.py", line 396, in on_save
    self.game.save()
  File "/home/user01/src/lutris/lutris/game.py", line 147, in save
    id=self.id
  File "/home/user01/src/lutris/lutris/pga.py", line 213, in add_or_update
    sql.db_update(PGA_DB, "games", params, ('id', game_id))
  File "/home/user01/src/lutris/lutris/util/sql.py", line 75, in db_update
    cursor_execute(cursor, query, field_values + condition_value)
  File "/home/user01/src/lutris/lutris/util/sql.py", line 30, in cursor_execute
    return cursor.execute(query, params)
sqlite3.InterfaceError: Error binding parameter 8 - probably unsupported type.
```
