### ISSUE TITLE
Can't change runner: ValueError: 14 is not in list

### ISSUE THREAD

**Issue by AlexanderRevo** [lutris/lutris#5540]
### Bug description

Switching the game's runner fails with `14 not in list` error:

```
14 is not in list

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.runner.extract_icon(self.slug)

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1244, in extract_icon
    groups = extractor.get_group_icons()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 67, in get_group_icons
    rt_base_dir = self.find_resource_base("RT_GROUP_ICON")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 31, in find_resource_base
    rt_base_idx = [entry.id for entry in self.pe.DIRECTORY_ENTRY_RESOURCE.entries].index(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: 14 is not in list
```

I used to be able to change runners some time ago, perhaps this is a 0.5.17 regression?

### How to Reproduce

1. Install a game (tested with GOG release of Excessive Speed and retail release of Driver).
2. Go into the game configuration and "Runner options".
3. Try to change from Wine to another runner.
4. Error appears.

### Expected behavior

The runner to change successfully.

### Log output

```shell
2024-07-21 08:13:48,376: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-07-21 08:13:48,480 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-07-21 08:13:48,514 [startup.run_all_checks:120]:AMD Radeon RX 7900 XTX (1002:744c 1eae:7901 amdgpu) Driver 24.1.3
DEBUG    2024-07-21 08:13:48,617 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-21 08:13:48,625 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-07-21 08:13:48,658 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-07-21 08:13:48,681 [api.check_stale_runtime_versions:52]:Modified at nie, 21 lip 2024, 08:08:19, will update after nie, 21 lip 2024, 14:08:19
DEBUG    2024-07-21 08:13:48,744 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-07-21 08:13:57,168 [application.show_window:394]:Showing window EditGameConfigDialog22
DEBUG    2024-07-21 08:13:58,381 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-07-21 08:13:58,389 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-07-21 08:13:58,389 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-07-21 08:13:58,397 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-07-21 08:13:58,398 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-21 08:13:58,406 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-07-21 08:13:58,407 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-21 08:13:58,415 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-07-21 08:13:58,415 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-21 08:13:58,423 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-07-21 08:13:58,831 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-21 08:13:58,839 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
ERROR    2024-07-21 08:14:01,265 [exception_backstops.error_wrapper:110]:Error handling signal 'clicked': 14 is not in list
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.runner.extract_icon(self.slug)
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1244, in extract_icon
    groups = extractor.get_group_icons()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 67, in get_group_icons
    rt_base_dir = self.find_resource_base("RT_GROUP_ICON")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 31, in find_resource_base
    rt_base_idx = [entry.id for entry in self.pe.DIRECTORY_ENTRY_RESOURCE.entries].index(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 14 is not in list
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Manjaro Linux 24.0.4 Wynsdey
Arch: x86_64
Kernel: 6.6.40-1-MANJARO
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 7950X3D 16-Core Processor
Physical cores: 16
Logical cores: 32
[Memory]
RAM: 62.5 GB
Swap: 0.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.1.8, DRM 3.54, 6.6.40-1-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.3-manjaro1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.3-manjaro1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.3-manjaro1.1
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 7900 XTX (RADV NAVI31) (1.3.278)
```

**Comment by danieljohnson2** [comment]
That's a funky error message, but I recognize the trace-back. That looks like #5475. If so, it will trigger whenever you save that game (no matter what you change as long as its not the icon), but may not trigger on other games.

We've got a fix for this in master. Try [downloading the master](https://github.com/lutris/lutris) and running the ``bin/lutris`` script within - no need to install. Does that let you edit that games?

With this bug, you can also work around it by manually choosing the icon for the game, so it stops trying to extract one from the .exe.

**Comment by AlexanderRevo** [comment]
Yes, the master version worked.

On a side note, I've also run into a different error when trying to change the game's icon (present on master as well). I'll create a separate issue for it.

**Comment by danieljohnson2** [comment]
I think we can close this one, then.
