### ISSUE TITLE
Android python interpreter issue

### ISSUE THREAD

**Issue by Jacobw1oo** [lutris/lutris#5542]
### Bug description

i am on Android Chroot, Lutris 5.17. Steam runs using the runner, but not from Lutris. I belive i have core issues with the python to bash script interpreter.  systems call break every installer. 

### How to Reproduce

1. install any app
2. It downloads the files
3. it crashes error code 256

### Expected behavior

i expect it to install. or run app. neither work from Lutris but work fine on native. it has to be a python issue.

### Log output

```shell
gamer@localhost:~/Downloads/lutris$ lutris -d
2024-07-21 22:23:29,086: Unsupported architecture aarch64
MESA-LOADER: failed to open zink: driver not built!)
INFO     2024-07-21 22:23:29,632 [application.do_command_line:479]:Starting Lutris 0.5.17
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/./vulkaninfo.h:458:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-07-21 22:23:29,645 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-07-21 22:23:29,645 [startup.run_all_checks:120]: (msm_drm) Driver 1124403713.1.8
DEBUG    2024-07-21 22:23:29,815 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-21 22:23:29,820 [xrandr._get_vidmodes:18]:Retrieving 3 video modes from XrandR
DEBUG    2024-07-21 22:23:29,875 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2024-07-21 22:23:30,185 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-07-21 22:23:30,245 [api.check_stale_runtime_versions:52]:Modified at Sun Jul 21 18:36:38 2024, will update after Mon Jul 22 00:36:38 2024
ERROR    2024-07-21 22:23:30,281 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
DEBUG    2024-07-21 22:23:30,330 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-07-21 22:23:33,210 [application.show_window:394]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x6fd4ec2680 (LutrisWindow at 0x1bbfd410)>}
DEBUG    2024-07-21 22:23:36,970 [http._request:88]:GET https://lutris.net/api/games?search=2048&with-installers=True
DEBUG    2024-07-21 22:23:38,927 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/2048
DEBUG    2024-07-21 22:23:38,927 [http._request:88]:GET https://lutris.net/api/installers/2048
DEBUG    2024-07-21 22:23:38,928 [application.on_app_window_destroyed:419]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x6fd4ec2680 (LutrisWindow at 0x1bbfd410)>}
DEBUG    2024-07-21 22:23:39,324 [application.show_window:394]:Showing window InstallerWindow2048
DEBUG    2024-07-21 22:23:41,129 [xrandr._get_vidmodes:18]:Retrieving 3 video modes from XrandR
DEBUG    2024-07-21 22:23:42,295 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/love2d
DEBUG    2024-07-21 22:23:42,296 [http._request:88]:GET https://lutris.net/api/installers/love2d
DEBUG    2024-07-21 22:23:42,688 [application.show_window:394]:Showing window InstallerWindowlove2d
DEBUG    2024-07-21 22:23:44,903 [xrandr._get_vidmodes:18]:Retrieving 3 video modes from XrandR
DEBUG    2024-07-21 22:23:46,296 [installerwindow.on_files_prepared:608]:Game files prepared.
DEBUG    2024-07-21 22:23:46,300 [installerwindow.present_installer_files_page:623]:Presenting installer files page
DEBUG    2024-07-21 22:23:48,274 [files_box.on_file_available:108]:file is available
INFO     2024-07-21 22:23:48,274 [files_box.on_file_available:114]:All files available
INFO     2024-07-21 22:23:48,274 [installerwindow.on_files_available:653]:All files are available, continuing install
INFO     2024-07-21 22:23:48,275 [cache.save_to_cache:46]:File /home/gamer/Games/love2d/file/love-11.4-x86_64.AppImage is already cached in /home/gamer/Games/love2d/file
INFO     2024-07-21 22:23:48,291 [installerwindow.launch_installer_commands:661]:Launching installer commands
DEBUG    2024-07-21 22:23:48,293 [interpreter._iter_commands:315]:Installer command: {'move': {'dst': '$GAMEDIR/file.AppImage', 'src': 'file'}}
DEBUG    2024-07-21 22:23:48,298 [commands.move:309]:Moving /home/gamer/Games/love2d/file/love-11.4-x86_64.AppImage to /home/gamer/Games/love2d/file.AppImage
ERROR    2024-07-21 22:23:48,307 [jobs.target:32]:Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x6fd4f8d580>: <class 'FileNotFoundError'> [Errno 2] No such file or directory
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 325, in dispatch
    return method(params)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 331, in move
    self._killable_process(action, src, dst)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 544, in _killable_process
    with multiprocessing.Pool(1) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 346, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 363, in __init__
    self._rlock = ctx.Lock()
                  ^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/synchronize.py", line 169, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.12/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR    2024-07-21 22:23:48,311 [interpreter._iter_commands:300]:Last install command failed, show error
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: NO
[System]
OS: Ubuntu 24.04 Noble Numbat
Arch: None
Kernel: 5.15.104-android13-8-00002-g1f083f1cee62-ab10640417
Desktop: XFCE
Display Server: Not found
[CPU]
Vendor: Vendor unavailable
Model: Model unavailable
Physical cores: Physical cores unavailable
Logical cores: Logical cores unavailable
[Memory]
RAM: 14.9 GB
Swap: 8.0 GB
[Graphics]
Vendor: Mesa
OpenGL Renderer: zink Vulkan 1.3(Turnip Adreno (TM) 740 (MESA_TURNIP))
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3~git2407200600.49144e~oibaf-turnip-kgsl~n (git-49144eb 2024-07
OpenGL Core: 4.6 (Core Profile) Mesa 24.3~git2407200600.49144e~oibaf-turnip-kgsl~n (git-49144eb 2024-07-20 noble
OpenGL ES: OpenGL ES 3.2 Mesa 24.3~git2407200600.49144e~oibaf-turnip-kgsl~n (git-49144eb 2024-07-20 noble-oiba
Vulkan Version: 1.3.275
Vulkan Drivers: Turnip Adreno (TM) 740 (1.3.289)
```

**Comment by Jacobw1oo** [comment]
i believe this to be the answer, i doing a system rebuild.

pip install --upgrade pip
sudo pip install pillow==10.3.0

**Comment by strycore** [comment]
On my phone, I'm using Andronix and it has worked pretty well outside of not being able to run any games which wasn't my intent anyway. 

If I understand correctly, android chroot is a more low level way of doing it?

**Comment by Jacobw1oo** [comment]
If I understand correctly, android chroot is a more low level way of doing it? 
Yes kinda, it will allow for far more apps with automated wine version and install scripts. The native version get one version of wine running and use it for one size fits all. Lutris will allow me  to have 30 version of wine and each prefix willl have wine tricks install needed dl for optimal running.

**Comment by Jacobw1oo** [comment]
i don't really understand but i have found the solution.
before: sudo mount -t tmpfs -o size=256M tmpfs $ROOTFSPATH/dev/shm
after: sudo mount -t tmpfs tmpfs $ROOTFSPATH/dev/shm
