### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str' in lutris/gui/config/boxes.py

### ISSUE THREAD

**Issue by quantenzitrone** [lutris/lutris#5551]
### Bug description

Not a fatal bug, but it still produces a log output, found during testing of #5549

### How to Reproduce

1. Open the 'Preferences'
2. Go to 'Global Options'
2. Go to 'System' to see the error in the logs (or start lutris from a terminal to see them there)

### Expected behavior

no type error in logs

### Log output

```shell
[INFO:2024-07-31 18:25:24,878:application]: Starting Lutris 0.5.17
[ERROR:2024-07-31 18:25:25,002:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-07-31 18:25:25,020:startup]: Intel Corporation HD Graphics 630 (8086:591b 103c:836b i915) Driver 24.1.1
[ERROR:2024-07-31 18:25:25,143:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-07-31 18:25:25,157:startup]: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (10de:1c8d 103c:836b nvidia) Driver 535.183.01
[ERROR:2024-07-31 18:29:57,065:boxes]: Failed to generate option widget for 'gamescope_output_res': unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 179, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 283, in call_widget_generator
    self.generate_combobox(
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 412, in generate_combobox
    self._populate_combobox_choices(liststore, choices, value, default)
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 383, in _populate_combobox_choices
    expanded, tooltip_default = self._expand_combobox_choices(choices, value, default)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 405, in _expand_combobox_choices
    expanded.insert(0, (value + " (invalid)", value))
                        ~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[ERROR:2024-07-31 18:29:57,074:boxes]: Failed to generate option widget for 'gamescope_game_res': unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 179, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 283, in call_widget_generator
    self.generate_combobox(
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 412, in generate_combobox
    self._populate_combobox_choices(liststore, choices, value, default)
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 383, in _populate_combobox_choices
    expanded, tooltip_default = self._expand_combobox_choices(choices, value, default)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yb4hsf95w8j6xplcff1safcjlfwbp5l0-lutris-unwrapped-0.5.16/lib/python3.11/site-packages/lutris/gui/config/boxes.py", line 405, in _expand_combobox_choices
    expanded.insert(0, (value + " (invalid)", value))
                        ~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: NixOS 24.11 Vicuna
Arch: x86_64
Kernel: 6.9.7
Desktop: sway
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Physical cores: 4
Logical cores: 4
[Memory]
RAM: 15.5 GB
Swap: 15.5 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.1
Vulkan Version: 1.3.283
Vulkan Drivers: Intel(R) HD Graphics 630 (KBL GT2) (1.3.278), NVIDIA GeForce GTX 1050 (1.3.242)
```

**Comment by danieljohnson2** [comment]
Another fine @danieljohnson2 bug!

There are some options whose value is missing, because they've unset, and that's not found in the drop-down so this code is trying to provide an item for that missing value. Because this crashes, the entire option is actually left out of the UI!

Just need to check this and not add the item, easy fix.
