### ISSUE TITLE
Installing updates for itch.io raise errors

### ISSUE THREAD

**Issue by 0chroma** [lutris/lutris#5558]
### Bug description

When trying to install updates for an outdated itch.io game, I get an error

### How to Reproduce

1. Right click on an outdated itch.io game
2. Click 'install updates'
3. click 'install'
4. get error

### Expected behavior

Updates install as expected

### Log output

```shell
'list' object has no attribute 'uses_pga_cache'

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 57, in discarding_result
    function(*args, **kwargs)

  File "/app/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 609, in on_files_prepared
    self.installer_files_box.load_installer(self.interpreter.installer)

  File "/app/lib/python3.11/site-packages/lutris/gui/installer/files_box.py", line 38, in load_installer
    installer_file_box = InstallerFileBox(installer_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/gui/installer/file_box.py", line 29, in __init__
    self.cache_to_pga = self.installer_file.uses_pga_cache()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'list' object has no attribute 'uses_pga_cache'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.9.8-amd64
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5700G with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 30.7 GB
Swap: 15.3 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.9.8-amd64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.3 (git-0c49f54c76)
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.3 (git-0c49f54c76)
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.3 (git-0c49f54c76)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon Graphics (RADV RENOIR) (1.3.278), AMD Radeon RX 7900 XTX (RADV NAVI31) (1.3.278)
```

**Comment by danieljohnson2** [comment]
The error message isn't quite what I'd have expected, but there is a bug here that's fixed in master; please try that.

Download [the master here](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within- no need to install. Try to update your game. Is it any better?

**Comment by 0chroma** [comment]
yup! that seemed to do the trick
