### ISSUE TITLE
Failing to install Epic games in Ubuntu 24.04

### ISSUE THREAD

**Issue by george-gca** [lutris/lutris#5568]
Discussed in https://github.com/lutris/lutris/discussions/5559, and probably related to #4497, but apparently this was fixed back then.

Installed Lutris 0.5.17 via dpkg. Running `lutris -d` and trying to install Epic Games:

```log
2024-08-16 16:04:01,626: Command 'wine' not found on your system
2024-08-16 16:04:01,626: Command 'fluidsynth' not found on your system
2024-08-16 16:04:01,821: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'

(lutris:88353): Gtk-WARNING **: 16:04:01.878: Theme directory actions/24 of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:01.878: Theme directory actions/32 of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:01.878: Theme directory actions/16@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:01.878: Theme directory actions/22@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:01.878: Theme directory actions/24@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:01.878: Theme directory actions/32@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:01.878: Theme directory actions/symbolic of theme Dracula has no size field

INFO     2024-08-16 16:04:01,928 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-08-16 16:04:01,954 [startup.run_all_checks:120]:Intel UHD Graphics (8086:9bc4 17aa:3f8d i915) Driver 24.0.9
INFO     2024-08-16 16:04:02,042 [startup.run_all_checks:120]:NVIDIA GeForce RTX 2060 (10de:1f15 17aa:3f8d nvidia) Driver 535.183.01
ERROR    2024-08-16 16:04:02,042 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)

(lutris:88353): Gtk-WARNING **: 16:04:02.192: Theme directory actions/24 of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:02.192: Theme directory actions/32 of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:02.192: Theme directory actions/16@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:02.192: Theme directory actions/22@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:02.192: Theme directory actions/24@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:02.192: Theme directory actions/32@2x of theme Dracula has no size field


(lutris:88353): Gtk-WARNING **: 16:04:02.192: Theme directory actions/symbolic of theme Dracula has no size field

DEBUG    2024-08-16 16:04:02,244 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-08-16 16:04:02,286 [api.check_stale_runtime_versions:52]:Modified at Fri 16 Aug 2024 02:47:15 PM , will update after Fri 16 Aug 2024 08:47:15 PM 
DEBUG    2024-08-16 16:04:02,364 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-08-16 16:04:07,360 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/epic-games-store
DEBUG    2024-08-16 16:04:07,361 [http._request:88]:GET https://lutris.net/api/installers/epic-games-store
DEBUG    2024-08-16 16:04:08,102 [application.show_window:394]:Showing window InstallerWindowepic-games-store
DEBUG    2024-08-16 16:04:10,045 [displayconfig.get_current_resolution:639]:Retrieving current resolution
DEBUG    2024-08-16 16:04:12,493 [wine.get_installer_runner_version:815]:Default wine version is wine-ge-8-26
DEBUG    2024-08-16 16:04:12,544 [installerwindow.on_files_prepared:608]:Game files prepared.
DEBUG    2024-08-16 16:04:12,546 [installerwindow.present_installer_files_page:623]:Presenting installer files page
DEBUG    2024-08-16 16:04:13,615 [downloader.start:60]:⬇ https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
DEBUG    2024-08-16 16:04:13,617 [downloader.start:60]:⬇ https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi
DEBUG    2024-08-16 16:04:19,200 [downloader.on_download_completed:166]:Finished downloading https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
INFO     2024-08-16 16:04:19,622 [file_box.on_download_complete:223]:Download completed
DEBUG    2024-08-16 16:04:19,622 [files_box.on_file_available:108]:uplay is available
DEBUG    2024-08-16 16:04:22,632 [downloader.on_download_completed:166]:Finished downloading https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi
INFO     2024-08-16 16:04:23,129 [file_box.on_download_complete:223]:Download completed
DEBUG    2024-08-16 16:04:23,130 [files_box.on_file_available:108]:epicsetup is available
INFO     2024-08-16 16:04:23,130 [files_box.on_file_available:114]:All files available
INFO     2024-08-16 16:04:23,130 [installerwindow.on_files_available:653]:All files are available, continuing install
INFO     2024-08-16 16:04:23,130 [installerwindow.launch_installer_commands:661]:Launching installer commands
DEBUG    2024-08-16 16:04:23,131 [interpreter.create_game_folder:221]:Creating destination path /home/gca/Games/epic-games-store
DEBUG    2024-08-16 16:04:23,131 [interpreter._iter_commands:315]:Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2024-08-16 16:04:23,197 [wine.create_prefix:108]:Creating a win64 prefix in /home/gca/Games/epic-games-store
INFO     2024-08-16 16:04:23,197 [wine.create_prefix:126]:Winepath: /home/gca/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
DEBUG    2024-08-16 16:04:23,197 [system._execute:109]:Executing /home/gca/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineboot
DEBUG    2024-08-16 16:04:23,198 [system._execute:115]:WINEARCH=win64 WINEPREFIX=/home/gca/Games/epic-games-store WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/gca/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/mono WINE_GECKO_CACHE_DIR=/home/gca/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/gecko
INFO     2024-08-16 16:09:23,737 [wine.create_prefix:175]:win64 Prefix created in /home/gca/Games/epic-games-store
DEBUG    2024-08-16 16:09:23,770 [interpreter._iter_commands:315]:Installer command: {'write_file': {'content': 'overlay:\n  enabled: false\n  forceunhookgame: false\n  fps_enabled: false\n  warning_enabled: false\nuser:\n  closebehavior: CloseBehavior_Close\nuser:\n  start_on_windows_start: false', 'file': '$GAMEDIR/drive_c/users/$USER/Local Settings/Application Data/Ubisoft Game Launcher/settings.yml'}}
DEBUG    2024-08-16 16:09:23,814 [interpreter._iter_commands:315]:Installer command: {'task': {'app': 'corefonts', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
WARNING  2024-08-16 16:09:23,954 [wine.prelaunch:1009]:Wine is not installed on your system; required dependencies may be missing.
Started initial process 88942 from /home/gca/.local/share/lutris/runtime/winetricks/winetricks --unattended corefonts
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20230212-next, latest upstream is winetricks-20240105!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 28
drwxrwxr-x  7 gca gca 4096 Aug 16 16:04 .
drwxrwxr-x  4 gca gca 4096 Aug 16 16:09 ..
drwxrwxr-x  3 gca gca 4096 Aug 16 16:04 ProgramData
drwxrwxr-x  6 gca gca 4096 Aug 16 16:04 Program Files
drwxrwxr-x  3 gca gca 4096 Aug 16 16:04 Program Files (x86)
drwxrwxr-x  4 gca gca 4096 Aug 16 16:09 users
drwxrwxr-x 17 gca gca 4096 Aug 16 16:04 windows

Registry info:
/home/gca/Games/epic-games-store/system.reg:#arch=win64
/home/gca/Games/epic-games-store/user.reg:#arch=win64
/home/gca/Games/epic-games-store/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: /home/gca/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
DEBUG    2024-08-16 16:09:24,265 [monitored_command.on_stop:228]:Process 88940 has terminated with code 256
DEBUG    2024-08-16 16:09:24,997 [commands._monitor_task:444]:Return code: 256
ERROR    2024-08-16 16:09:24,997 [errors.__init__:19]:Command exited with code 256
ERROR    2024-08-16 16:09:24,997 [exception_backstops.error_wrapper:110]:Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 446, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```

**Comment by strycore** [comment]
You don't have wine installed on your system so you're likely missing dependencies

**Comment by george-gca** [comment]
I thought installing Lutris already installed wine as a dependency. Installing wine fixed it.
