### ISSUE TITLE
All launchers fail to install (python dict key error).

### ISSUE THREAD

**Issue by Magicrafter13** [lutris/lutris#5575]
### Bug description

Just installed Lutris on a fairly fresh Arch install, and I'm trying to sign into my accounts, which requires me to download launchers (Epic, EA, etc.). On clicking install it just says "Lutris has encountered an error 'url'" and gives this.

```
'url'

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/installerwindow.py", line 442, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)

  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)

  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(

  File "/usr/lib/python3.12/site-packages/lutris/runners/runner.py", line 489, in install
    self.download_and_extract(runner_version_info["url"], **opts)
                              ~~~~~~~~~~~~~~~~~~~^^^^^^^

KeyError: 'url'
```

### How to Reproduce

1. Add a source such as EGS, EA, or Ubisoft Connect.
2. Click the account button.
3. Select a script and click install.

### Expected behavior

(not have a missing url in the dict prob)

### Log output

```shell
2024-08-23 23:06:53,793: Command 'wine' not found on your system
2024-08-23 23:06:53,880: Unable to run command, qdbus not found
2024-08-23 23:06:53,947: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-08-23 23:06:54,050 [application.do_command_line:479]:Starting Lutris 0.5.17
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:688:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-08-23 23:06:54,066 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-08-23 23:06:54,066 [startup.run_all_checks:120]: (1002:744c 1eae:7905 amdgpu) Driver 24.1.6
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:688:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-08-23 23:06:54,081 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-08-23 23:06:54,081 [startup.run_all_checks:120]: (1002:164e 1849:364e amdgpu) Driver 24.1.6
ERROR    2024-08-23 23:06:54,082 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)
DEBUG    2024-08-23 23:06:54,156 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-08-23 23:06:54,158 [xrandr._get_vidmodes:18]:Retrieving 69 video modes from XrandR
DEBUG    2024-08-23 23:06:54,196 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-08-23 23:06:54,215 [api.check_stale_runtime_versions:52]:Modified at Fri 23 Aug 2024 10:48:52 PM , will update after Sat 24 Aug 2024 04:48:52 AM 
DEBUG    2024-08-23 23:06:54,222 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-08-23 23:06:55,199 [http._request:88]:POST https://lutris.net/api/users/library?since=1724479009
DEBUG    2024-08-23 23:06:58,590 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/epic-games-store
DEBUG    2024-08-23 23:06:58,590 [http._request:88]:GET https://lutris.net/api/installers/epic-games-store
DEBUG    2024-08-23 23:06:58,944 [application.show_window:394]:Showing window InstallerWindowepic-games-store
DEBUG    2024-08-23 23:07:06,157 [xrandr._get_vidmodes:18]:Retrieving 69 video modes from XrandR
INFO     2024-08-23 23:07:14,404 [interpreter.get_runners_to_install:255]:Runner <lutris.runners.wine.wine object at 0x7762781813d0> needs to be installed
DEBUG    2024-08-23 23:07:14,404 [interpreter.install_runner:274]:Installing wine
DEBUG    2024-08-23 23:07:14,409 [runner.install:468]:Installing wine (version=system, callback=<function ScriptInterpreter.install_runner.<locals>.install_more_runners at 0x77627818c900>)
ERROR    2024-08-23 23:07:14,409 [exception_backstops.error_wrapper:110]:Error handling idle function: 'url'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/installerwindow.py", line 442, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(
  File "/usr/lib/python3.12/site-packages/lutris/runners/runner.py", line 489, in install
    self.download_and_extract(runner_version_info["url"], **opts)
                              ~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'url'
WARNING  2024-08-23 23:07:18,034 [system.delete_folder:383]:Non existent path: /home/matthew/.cache/lutris/installer/epic-games-store
DEBUG    2024-08-23 23:07:18,034 [application.on_app_window_destroyed:419]:Removed window InstallerWindowepic-games-store
INFO     2024-08-23 23:07:22,216 [application.do_shutdown:1051]:Shutting down Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: NO
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: EndeavourOS rolling rolling
Arch: x86_64
Kernel: 6.10.6-arch1-1
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 7900X 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 93.4 GB
Swap: 0.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 18.1.8, DRM 3.57, 6.10.6-arch1-1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.6-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.6-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.6-arch1.1
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 7900 XT (1.3.292), AMD Radeon Graphics (1.3.292)
```

**Comment by danieljohnson2** [comment]
I think I see part the problem. You are installing using the system version of Wine but somehow you are tryng to install that version of Wine. That makes no sense- the system Wine is the one your distribution provides, and by definition Lutris can't install it. I'll put a better error message in for this, but why is it happening at all?

**Comment by danieljohnson2** [comment]
OK, @Magicrafter13, I'd like you to try some commands at the command line, just to confirm what I'm seeing.

Try ``which wine``. I think that will say you don't have wine. If it says you do, try just running ``wine`` and lets see what you get.

If I'm right and you do not have wine, you need to install that yourself to use it in Lutris. We'll give a better error in the next version of Lutris, but we can't install this for you.

And we strongly recommend you *do* install your system version of Wine even if you aren't going to use that for your games. I'd recommend that you not use system Wine for your games through; we just want it for its dependencies.

If Lutris hasn't provided its version Wine, you can get it by going into the "Preferences" dialog, "Updates" tab. There's a button in there. It's possible that you just need to click that button and download our default Wine, and it will start working.

**Comment by Magicrafter13** [comment]
> Try `which wine`. I think that will say you don't have wine. If it says you do, try just running `wine` and lets see what you get.

Indeed, "wine not found".

> If I'm right and you do not have wine, you need to install that yourself to use it in Lutris. We'll give a better error in the next version of Lutris, but we can't install this for you.

Installing wine on my end fixed it, thank you. I suppose I assumed it was already installed. This is how the screen looked on Lutris before installing. I probably just needed to click the button :p
![image](https://github.com/user-attachments/assets/3031c2cf-d61a-4c79-bf16-c58900252340)
