### ISSUE TITLE
Cant access User Flatpaks

### ISSUE THREAD

**Issue by Svenum** [lutris/lutris#5581]
### Bug description

I would like to install and add Flatpaks via the user environment (not the system environment). But every flatpak command int he background uses the --system flag.

### How to Reproduce

1. try to install flatpak via lutris
2. See the error:
    ```bash
    Started initial process 75 from /usr/bin/flatpak-spawn --host flatpak install --system --app --noninteractive flathub 
    app/org.prismlauncher.PrismLauncher/x86_64/stable
    Start monitoring process.
    error: No remote refs found for ‘flathub’
    Monitored process exited.
    Initial process has exited (return code: 256)
    All processes have quit
    Exit with return code 256
    ```

### Expected behavior

Can install and view flatpaks from the --user environment

### Log output

```shell
[INFO:2024-09-02 10:00:54,133:application]: Starting Lutris 0.5.17
[INFO:2024-09-02 10:00:56,463:startup]: AMD Radeon 780M (1002:15bf f111:0005 amdgpu) Driver 24.1.3
[INFO:2024-09-02 10:00:56,616:startup]: AMD Radeon RX 7700S (1002:7480 f111:0007 amdgpu) Driver 24.1.3
[INFO:2024-09-02 10:01:52,720:installerwindow]: Launching installer commands
[ERROR:2024-09-02 10:01:53,727:errors]: Command exited with code 256
[ERROR:2024-09-02 10:01:53,727:exception_backstops]: Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 76, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/commands.py", line 444, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
[INFO:2024-09-02 10:03:00,388:interpreter]: Cancelling installation of Prism Launcher
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.10.6
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 30.7 GB
Swap: 35.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon 780M (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.10.6)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.3 (git-0c49f54c76)
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.3 (git-0c49f54c76)
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.3 (git-0c49f54c76)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon RX 7700S (RADV NAVI33) (1.3.278), AMD Radeon 780M (RADV GFX1103_R1) (1.3.278)
```

**Comment by Svenum** [comment]
Yep, I use NixOS btw. 😅
