### ISSUE TITLE
EA App not working

### ISSUE THREAD

**Issue by MichelN86** [lutris/lutris#5591]
### Bug description

After i login i get a error message in Pop! OS 22.04 using latest lutris build from the github. The strange thing is i can see my libary but thats it. Can't install any game nor does the EA App launch.

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()

  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"

http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(

  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)

  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()

  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"

urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 142, in do_reload
    self.load()

  File "/usr/lib/python3/dist-packages/lutris/services/ea_app.py", line 248, in load
    games = self.get_library(user_id)

  File "/usr/lib/python3/dist-packages/lutris/services/ea_app.py", line 260, in get_library
    for entitlement in self.get_entitlements(user_id):

  File "/usr/lib/python3/dist-packages/lutris/services/ea_app.py", line 279, in get_entitlements
    response = self.session.get(url, headers=headers)

  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)

  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)

  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)

  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### How to Reproduce

Just install, login and you will see.

### Expected behavior

Crashing and not launching at all after login.

Trying to install a game i get this 

Started initial process 97487 from /home/michel/.local/share/lutris/runtime/umu/umu_run.py /home/michel/Games/ea-app/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe origin2://game/launch?offerIds=71715&autoDownload=1
Start monitoring process.
[34mProtonFixes[97566] INFO: Running protonfixes[0m
[34mProtonFixes[97566] INFO: Running checks[0m
[34mProtonFixes[97566] INFO: All checks successful[0m
[34mProtonFixes[97566] INFO: Non-steam game UNKNOWN (umu-default)[0m
[34mProtonFixes[97566] INFO: No store specified, using UMU database[0m
[34mProtonFixes[97566] INFO: Using global defaults for UNKNOWN (umu-default)[0m
[34mProtonFixes[97566] INFO: Non-steam game UNKNOWN (umu-default)[0m
[34mProtonFixes[97566] INFO: No store specified, using UMU database[0m
[34mProtonFixes[97566] INFO: No global protonfix found for UNKNOWN (umu-default)[0m

### Log output

```shell
x
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Pop!_OS 22.04 jammy
Arch: x86_64
Kernel: 6.9.3-76060903-generic
Desktop: pop:GNOME
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: 12th Gen Intel(R) Core(TM) i7-12700H
Physical cores: 14
Logical cores: 20
[Memory]
RAM: 62.5 GB
Swap: 20.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 555.58.02
OpenGL Core: 4.6.0 NVIDIA 555.58.02
OpenGL ES: OpenGL ES 3.2 NVIDIA 555.58.02
Vulkan Version: 1.3.280
Vulkan Drivers: Intel(R) Graphics (ADL GT2) (1.3.274), NVIDIA GeForce RTX 3070 Ti Laptop GPU (1.3.278)
```

**Comment by MichelN86** [comment]
Oke for some reason i fixed it. I changed 1 setting

Display:
GPU (Automatic), i changed that setting to the dGPU before i ran the EA App to make sure it uses the dGPU. For some reason it does not want to use the dGPU but the iGPU instead.

**Comment by JassonCordones** [comment]
Is this solved then?

**Comment by danieljohnson2** [comment]
Sounds like this was just a configuration issue. Automatic is the preferred choice here, though I do not know why the EA app would care in the slightest.

Closing this as fixed by the user.
