### ISSUE TITLE
U Boat fails to donwload

### ISSUE THREAD

**Issue by phodina** [lutris/lutris#5599]
### Bug description

I bought on GoG the game [U-boat](https://www.gog.com/en/game/uboat).

It's listed in my account. I wanted to install it so clicked on it, selected Wine install. And then the download started ~24G.

However around 20 GB it stops and throws a dialog.

```
1 parameters needed for signal error; 0 given

Traceback (most recent call last):

  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/gui/widgets/download_collection_progress_box.py", line 161, in _progress
    self.emit("error")

TypeError: 1 parameters needed for signal error; 0 given1 parameters needed for signal error; 0 given
```

### How to Reproduce

1. Go to 'GoG'
2. Click on 'Uboat'
3. Do 'Install'
4. See 'Dialog with exception during download'

### Expected behavior

Game installs

### Log output

```shell
$ lutris -d
Error: unable to open display 
2024-09-12 17:32:40,026: ['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 255.
2024-09-12 17:32:40,026: No available glxinfo output
2024-09-12 17:32:40,027: Invalid glxinfo received
INFO     2024-09-12 17:32:40,826 [application.do_command_line:479]:Starting Lutris 0.5.17
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/source/vulkaninfo/./vulkaninfo.h:458:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-09-12 17:32:40,975 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-09-12 17:32:40,976 [startup.run_all_checks:120]: (1002:163f 1002:0123 amdgpu) Driver None
DEBUG    2024-09-12 17:32:41,254 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-09-12 17:32:41,286 [api.check_stale_runtime_versions:52]:Modified at Thu 12 Sep 2024 05:32:22 PM , will update after Thu 12 Sep 2024 11:32:22 PM 

(lutris:31793): Gtk-WARNING **: 17:32:41.287: Getting screensaver status failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.ScreenShield was not provided by any .service files
DEBUG    2024-09-12 17:32:41,299 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
ERROR    2024-09-12 17:32:41,301 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
DEBUG    2024-09-12 17:32:49,409 [base.install:322]:Installing 1771607985 from service gog
DEBUG    2024-09-12 17:32:49,410 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2024-09-12 17:32:50,083 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/uboat
DEBUG    2024-09-12 17:32:50,083 [http._request:88]:GET https://lutris.net/api/installers/uboat
DEBUG    2024-09-12 17:32:50,637 [application.show_window:394]:Showing window InstallerWindow1771607985
DEBUG    2024-09-12 17:33:13,475 [application.show_window:394]:Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f2737e90540 (LutrisWindow at 0x27e3d040)>}
Error: unable to open display 
ERROR    2024-09-12 17:33:16,438 [system.read_process_output:188]:['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 255.
ERROR    2024-09-12 17:33:16,439 [glxinfo.parse:38]:No available glxinfo output
Error: unable to open display 
ERROR    2024-09-12 17:33:18,701 [system.read_process_output:188]:['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 255.
ERROR    2024-09-12 17:33:18,701 [glxinfo.parse:38]:No available glxinfo output
DEBUG    2024-09-12 17:34:36,359 [application.on_app_window_destroyed:419]:Removed window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f2737e90540 (LutrisWindow at 0x27e3d040)>}
DEBUG    2024-09-12 17:34:39,178 [displayconfig.get_current_resolution:639]:Retrieving current resolution
DEBUG    2024-09-12 17:34:41,193 [wine.get_installer_runner_version:815]:Default wine version is wine-ge-8-26
DEBUG    2024-09-12 17:34:41,218 [gog.get_extras:323]:Download extras for GOG ID 1771607985 and its DLCs
INFO     2024-09-12 17:34:41,218 [gog.get_game_details:284]:Getting game details for 1771607985
DEBUG    2024-09-12 17:34:41,219 [http._request:88]:GET https://auth.gog.com/token?client_id=46899977096215655&client_secret=9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9&grant_type=refresh_token&refresh_token=h7K5Aa8g6NugkVF4WT1sCQ-tqMATReKkaT9HCx_LVw553BfCvsyFlHRIBrYvis3m
DEBUG    2024-09-12 17:34:42,441 [http._request:88]:GET https://api.gog.com/products/1771607985?expand=downloads&locale=en-US
INFO     2024-09-12 17:34:42,601 [gog.get_game_details:284]:Getting game details for 1771607985
DEBUG    2024-09-12 17:34:42,683 [http._request:88]:GET https://api.gog.com/products/1771607985?expand=downloads&locale=en-US
INFO     2024-09-12 17:34:42,746 [installer.prepare_game_files:168]:Getting files for goginstaller
INFO     2024-09-12 17:34:42,747 [gog.get_game_details:284]:Getting game details for 1771607985
DEBUG    2024-09-12 17:34:42,827 [http._request:88]:GET https://api.gog.com/products/1771607985?expand=downloads&locale=en-US
INFO     2024-09-12 17:34:43,104 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer0
DEBUG    2024-09-12 17:34:43,185 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer0
INFO     2024-09-12 17:34:43,747 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer1
DEBUG    2024-09-12 17:34:43,827 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer1
INFO     2024-09-12 17:34:44,361 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer2
DEBUG    2024-09-12 17:34:44,441 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer2
INFO     2024-09-12 17:34:44,771 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer3
DEBUG    2024-09-12 17:34:44,852 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer3
INFO     2024-09-12 17:34:45,139 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer4
DEBUG    2024-09-12 17:34:45,219 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer4
INFO     2024-09-12 17:34:45,795 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer5
DEBUG    2024-09-12 17:34:45,875 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer5
INFO     2024-09-12 17:34:46,773 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer6
DEBUG    2024-09-12 17:34:46,852 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer6
INFO     2024-09-12 17:34:47,913 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer7
DEBUG    2024-09-12 17:34:47,992 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer7
INFO     2024-09-12 17:34:48,211 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1771607985/downlink/installer/en1installer8
DEBUG    2024-09-12 17:34:48,290 [http._request:88]:GET https://api.gog.com/products/1771607985/downlink/installer/en1installer8
DEBUG    2024-09-12 17:34:48,503 [installerwindow.on_files_prepared:608]:Game files prepared.
DEBUG    2024-09-12 17:34:48,508 [installerwindow.present_installer_files_page:623]:Presenting installer files page
DEBUG    2024-09-12 17:35:05,250 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158888~dirs=6~token=01b0edcd8e8fbf8117b19/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-8.bin
DEBUG    2024-09-12 17:35:48,380 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726158888~dirs=6~token=01b0edcd8e8fbf8117b19/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-8.bin
DEBUG    2024-09-12 17:35:48,817 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158888~dirs=6~token=01b0edcd8e8fbf8117b19/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-7.bin
DEBUG    2024-09-12 17:47:21,353 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726158888~dirs=6~token=01b0edcd8e8fbf8117b19/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-7.bin
DEBUG    2024-09-12 17:47:21,716 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158887~dirs=6~token=051f45343811fdfbc1f82/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-6.bin
DEBUG    2024-09-12 17:58:58,440 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726158887~dirs=6~token=051f45343811fdfbc1f82/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-6.bin
DEBUG    2024-09-12 17:58:58,593 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158886~dirs=6~token=0ac51edf098be2156ea4d/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-5.bin
DEBUG    2024-09-12 18:10:34,734 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726158886~dirs=6~token=0ac51edf098be2156ea4d/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-5.bin
DEBUG    2024-09-12 18:10:35,047 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158885~dirs=6~token=08e70e72e3c0c58db118f/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-4.bin
DEBUG    2024-09-12 18:22:04,856 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726158885~dirs=6~token=08e70e72e3c0c58db118f/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-4.bin
DEBUG    2024-09-12 18:22:05,014 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158885~dirs=6~token=08e70e72e3c0c58db118f/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-3.bin
DEBUG    2024-09-12 18:33:35,171 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726158885~dirs=6~token=08e70e72e3c0c58db118f/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-3.bin
DEBUG    2024-09-12 18:33:35,437 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-2.bin
DEBUG    2024-09-12 18:45:03,362 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-2.bin
DEBUG    2024-09-12 18:45:03,821 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
INFO     2024-09-12 18:45:03,891 [downloader.async_download:136]:https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin returned a 403 error
ERROR    2024-09-12 18:45:03,892 [downloader.async_download:149]:Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
Traceback (most recent call last):
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/nix/store/v9vlasx9pvm911cxdmd5fqbical5pjx8-python3.12-requests-2.32.3/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
DEBUG    2024-09-12 18:45:04,322 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
INFO     2024-09-12 18:45:04,384 [downloader.async_download:136]:https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin returned a 403 error
ERROR    2024-09-12 18:45:04,384 [downloader.async_download:149]:Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
Traceback (most recent call last):
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/nix/store/v9vlasx9pvm911cxdmd5fqbical5pjx8-python3.12-requests-2.32.3/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
DEBUG    2024-09-12 18:45:04,823 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
INFO     2024-09-12 18:45:04,881 [downloader.async_download:136]:https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin returned a 403 error
ERROR    2024-09-12 18:45:04,881 [downloader.async_download:149]:Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
Traceback (most recent call last):
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/nix/store/v9vlasx9pvm911cxdmd5fqbical5pjx8-python3.12-requests-2.32.3/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
DEBUG    2024-09-12 18:45:05,324 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
INFO     2024-09-12 18:45:05,384 [downloader.async_download:136]:https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin returned a 403 error
ERROR    2024-09-12 18:45:05,384 [downloader.async_download:149]:Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
Traceback (most recent call last):
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/nix/store/v9vlasx9pvm911cxdmd5fqbical5pjx8-python3.12-requests-2.32.3/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
DEBUG    2024-09-12 18:45:05,824 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
INFO     2024-09-12 18:45:05,893 [downloader.async_download:136]:https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin returned a 403 error
ERROR    2024-09-12 18:45:05,894 [downloader.async_download:149]:Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
Traceback (most recent call last):
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/nix/store/v9vlasx9pvm911cxdmd5fqbical5pjx8-python3.12-requests-2.32.3/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726158884~dirs=6~token=0f42baaf98c41981e22d7/secure/offline/1771607985/1771607985/57899055754673094/3493/setup_uboat_2024.1_%28full_release%29_patch_13_%2864bit%29_%2876089%29-1.bin
ERROR    2024-09-12 18:45:06,325 [exception_backstops.error_wrapper:110]:Error handling timeout function: 1 parameters needed for signal error; 0 given
Traceback (most recent call last):
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/f8ql8n2a075r3rzkd7j1l6m8gha33sgi-lutris-unwrapped-0.5.17/lib/python3.12/site-packages/lutris/gui/widgets/download_collection_progress_box.py", line 161, in _progress
    self.emit("error")
TypeError: 1 parameters needed for signal error; 0 given
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: NixOS 24.11 Vicuna
Arch: x86_64
Kernel: 6.6.49
Desktop: Not found
Display Server: tty
[CPU]
Vendor: AuthenticAMD
Model: AMD Custom APU 0405
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 14.5 GB
Swap: 14.7 GB
[Graphics]
Vendor: Unable to obtain glxinfo
Vulkan Version: 1.3.283
Vulkan Drivers: AMD Custom GPU 0405 (RADV VANGOGH) (1.3.289)
```

### Media (optional)

![Screenshot from 2024-09-12 20-39-28](https://github.com/user-attachments/assets/9c7ba50b-3771-4ba1-93e5-453364ed28ee)

**Comment by danieljohnson2** [comment]
Well, that's a pretty simple bug; that line should, I think, be passing along the error but doesn't. I'll fix that.

The error itself is '403 Client Error'; the GOG servers seems to have cut you off. I don't know why, but it might work if you just retried it. Perhaps.

**Comment by phodina** [comment]
I retried multiple times. Got the error at around the same place. Same happens for Witcher 3 Wild hunt.

If that's from GoG side can I then get a refund as they block the download? How do I play that game?

Is it possible to download it manually or resume?

**Comment by danieljohnson2** [comment]
You can download GoG games manually from their website. Try that.

I also wonder if there are any GoG games that Lutris *will* download for you. Is GoG broken altogether for you?

**Comment by phodina** [comment]
Nope, got most games without any issue. This one is the first case. Also downloaded Witcher 3 for my desktop first without any issue.

Since I got the SteamDeck I wanted to play games there. Part of that is that the desktop is used for work and the games are just black box binaries that I have almost no control about and I just want to enjoy gaming not spending time on patching the game to remove connectivity to vendors server etc.

**Comment by danieljohnson2** [comment]
This is very odd. Witcher 3 is no small game; I don't understand why 'U-Boat' in particular should be failing.

I would like to know if you can download it manually, in case the problem is that the GoG copy on their servers is borked or something. Seems like a long shot, but this is very weird.

**Comment by HenriVDD** [comment]
Same issue (403 error) with Baldur's gate 3 :
The download stops half way through and throws.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/download_collection_progress_box.py", line 161, in _progress
    self.emit("error")

TypeError: 1 parameters needed for signal error; 0 given
