### ISSUE TITLE
Timeout error in installation

### ISSUE THREAD

**Issue by DanBmh** [lutris/lutris#5633]
While installing a game I got an error after downloading the files.

I think I had this (or a similar) error already before. It could be just caused by a timeout somewhere, because I let the computer download the game without supervising it and check the progress about once every hour. 

It can be fixed by aborting the installation and rerunning it again. \
But if the cache is not enabled (by default it's off) one has to download everything again...

<br>

Full error log:
```
[...]

DEBUG    2024-10-04 12:29:32,056 [files_box.on_file_available:108]:goginstaller is available
INFO     2024-10-04 12:29:32,056 [files_box.on_file_available:114]:All files available
INFO     2024-10-04 12:29:32,056 [installerwindow.on_files_available:664]:All files are available, continuing install
INFO     2024-10-04 12:29:32,057 [installerwindow.launch_installer_commands:672]:Launching installer commands

(lutris:17348): Gdk-CRITICAL **: 12:29:32.058: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.058: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.058: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
DEBUG    2024-10-04 12:29:32,062 [interpreter._iter_commands:315]:Installer command: {'autosetup_gog_game': 'goginstaller'}

(lutris:17348): Gdk-CRITICAL **: 12:29:32.403: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.404: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(lutris:17348): Gdk-CRITICAL **: 12:29:32.405: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
Started initial process 28456 from /home/daniel/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/daniel/Downloads/lutris_tmp_installers/baldurs-gate-3/gog/setup_baldurs_gate_3_release_-_v4.1.1.5970269_-_patch_patch7_hotfix2_%2864bit%29_%2876603%29.exe /SP- /NOCANCEL
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  512
  Current serial number in output stream:  512
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  203
  Current serial number in output stream:  203
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  665
  Current serial number in output stream:  665
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  203
  Current serial number in output stream:  203
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
DEBUG    2024-10-04 12:39:19,947 [monitored_command.on_stop:228]:Process 28454 has terminated with code 256
DEBUG    2024-10-04 12:39:20,103 [commands._monitor_task:442]:Return code: 256
ERROR    2024-10-04 12:39:20,104 [errors.__init__:19]:Command exited with code 256
ERROR    2024-10-04 12:39:20,104 [exception_backstops.error_wrapper:78]:Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/home/daniel/Downloads/lutris/lutris/exception_backstops.py", line 76, in error_wrapper
    return handler(*args, **kwargs)
  File "/home/daniel/Downloads/lutris/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
  File "/home/daniel/Downloads/lutris/lutris/installer/commands.py", line 444, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```

**Comment by DanBmh** [comment]
Same with the installation process (I think the game's installer has finished and was waiting for another input):
```
INFO     2024-10-04 12:42:00,623 [installerwindow.launch_installer_commands:672]:Launching installer commands
DEBUG    2024-10-04 12:42:00,624 [interpreter._iter_commands:315]:Installer command: {'autosetup_gog_game': 'goginstaller'}
Started initial process 28643 from /home/daniel/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/daniel/Downloads/lutris_tmp_installers/baldurs-gate-3/gog/setup_baldurs_gate_3_release_-_v4.1.1.5970269_-_patch_patch7_hotfix2_%2864bit%29_%2876603%29.exe /SP- /NOCANCEL
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  205
  Current serial number in output stream:  205
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  205
  Current serial number in output stream:  205
Initial process has exited (return code: 256)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  2309
  Current serial number in output stream:  2309
Monitored process exited.
Exit with return code 256
DEBUG    2024-10-04 13:23:24,097 [monitored_command.on_stop:228]:Process 28641 has terminated with code 256
DEBUG    2024-10-04 13:23:24,104 [commands._monitor_task:442]:Return code: 256
ERROR    2024-10-04 13:23:24,105 [errors.__init__:19]:Command exited with code 256
ERROR    2024-10-04 13:23:24,105 [exception_backstops.error_wrapper:78]:Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/home/daniel/Downloads/lutris/lutris/exception_backstops.py", line 76, in error_wrapper
    return handler(*args, **kwargs)
  File "/home/daniel/Downloads/lutris/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
  File "/home/daniel/Downloads/lutris/lutris/installer/commands.py", line 444, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```

**Comment by strycore** [comment]
This is likely a network glitch and there's not much we can do until we fix the install method for GOG games.
