### ISSUE TITLE
FlatHub source failing to reload due to Python error

### ISSUE THREAD

**Issue by Steffo99** [lutris/lutris#5643]
### Bug description

```python
string indices must be integers, not 'str'

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 142, in do_reload
    self.load()

  File "/usr/lib/python3.12/site-packages/lutris/services/flathub.py", line 92, in load
    flathub_games.append(FlathubGame.new_from_flathub_game(game))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/services/flathub.py", line 42, in new_from_flathub_game
    service_game.appid = flathub_game["flatpakAppId"]
                         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^

TypeError: string indices must be integers, not 'str'
```

Seems like `flathub_game` here is a `str` instead of a `dict`?

### How to Reproduce

Click the Reload button in the FlatHub source.

![](https://github.com/user-attachments/assets/129bcb80-6171-45c8-b25a-8897c5ed6e53)

### Expected behavior

I'm not sure; I clicked the button because I wanted to see what it would do.

I think it definitely shouldn't throw a Python error, though! :laughing: 

### Log output

```shell
2024-10-07 17:45:13,648: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-10-07 17:45:13,938 [application.do_command_line:479]:Starting Lutris 0.5.17
[2024-10-07 17:45:14.030] [MANGOHUD] [error] [overlay_params.cpp:647] Unknown option 'core_load_value'
[2024-10-07 17:45:14.030] [MANGOHUD] [error] [overlay_params.cpp:647] Unknown option 'gpu_load'
[2024-10-07 17:45:14.030] [MANGOHUD] [error] [overlay_params.cpp:647] Unknown option 'cpu_load'
ERROR    2024-10-07 17:45:14,818 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' died with <Signals.SIGSEGV: 11>.
INFO     2024-10-07 17:45:14,818 [startup.run_all_checks:120]: (10de:1b81 10de:119d nvidia) Driver 560.35.03
[2024-10-07 17:45:14.866] [MANGOHUD] [error] [overlay_params.cpp:647] Unknown option 'core_load_value'
[2024-10-07 17:45:14.866] [MANGOHUD] [error] [overlay_params.cpp:647] Unknown option 'gpu_load'
[2024-10-07 17:45:14.866] [MANGOHUD] [error] [overlay_params.cpp:647] Unknown option 'cpu_load'
DEBUG    2024-10-07 17:45:16,139 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-10-07 17:45:16,141 [xrandr._get_vidmodes:18]:Retrieving 81 video modes from XrandR
DEBUG    2024-10-07 17:45:16,229 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-10-07 17:45:16,285 [api.check_stale_runtime_versions:52]:Modified at Mon Oct  7 17:15:45 2024, will update after Mon Oct  7 23:15:45 2024
DEBUG    2024-10-07 17:45:16,536 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-10-07 17:45:17,239 [http._request:88]:POST https://lutris.net/api/users/library?since=1728314146
DEBUG    2024-10-07 17:45:18,073 [base.wipe_game_cache:175]:Deleting games from service-games for flathub
ERROR    2024-10-07 17:45:18,292 [jobs.target:32]:Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7ebefc49cea0>: <class 'TypeError'> string indices must be integers, not 'str'
File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
result = self.function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 142, in do_reload
self.load()
File "/usr/lib/python3.12/site-packages/lutris/services/flathub.py", line 92, in load
flathub_games.append(FlathubGame.new_from_flathub_game(game))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/lutris/services/flathub.py", line 42, in new_from_flathub_game
service_game.appid = flathub_game["flatpakAppId"]
~~~~~~~~~~~~^^^^^^^^^^^^^^^^

(lutris:10977): Gdk-CRITICAL **: 17:45:18.304: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.11.1-zen1-1-zen
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 1600X Six-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 15.5 GB
Swap: 16.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.295
Vulkan Drivers: NVIDIA GeForce GTX 1070 (1.3.280)
```

### Media (optional)

![](https://github.com/user-attachments/assets/dd4bf8da-6f45-4901-983c-0305aa65ba92)

**Comment by Steffo99** [comment]
Updated to the latest version available in the Arch repos, issue persists.

**Comment by danieljohnson2** [comment]
I've added a bit of code for better error handling- but the error is actually that the url ``https://flathub.org/api/v1/apps/category/Games`` is 404ing. Actually, even just ``https://flathub.org/api`` 404s.

I don't know what this means, but without the API we're not going to be able to integrate with FlatHub.

**Comment by strycore** [comment]
Looks like it was moved to https://flathub.org/api/v2/category/game

**Comment by danieljohnson2** [comment]
Right, that wasn't responding for me but now it is, and it has everything we need. Just need to rename some fields and Bob's your uncle!

Works for me now. I'll close this as fixed, but @Steffo99, you might want to [download the master branch](https://github.com/lutris/lutris) and try it too. No need to install- just run the ``bin/lutris`` script within and reload FlatHub. It should work, and you should be able to use it (and install games) with 0.5.17 after reloading.
