### ISSUE TITLE
FIleNotFound battle net installer

### ISSUE THREAD

**Issue by Reynardd** [lutris/lutris#5651]
### Bug description

fail to install battle net

### How to Reproduce

-Add games on lutris
-search the lutris website
-search for battle net
-install , continue , install

### Expected behavior

install battlenet

### Log output

```shell
2024-10-13 02:33:36,616: Download completed
2024-10-13 02:33:36,617: All files available
2024-10-13 02:33:36,617: All files are available, continuing install
2024-10-13 02:33:36,617: Launching installer commands
2024-10-13 02:33:36,660: Creating a win64 prefix in /home/reynard/Games/battlenet
2024-10-13 02:33:36,668: Winepath: GE-Proton (Latest)
2024-10-13 02:33:36,668: Error while completing task <function ScriptInterpreter._iter_commands..dispatch at 0x78900bfee200>: <class 'FileNotFoundError'> [Errno 2] No such file or directory
File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
result = self.function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 325, in dispatch
return method(params)
^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/lutris/installer/commands.py", line 432, in task
command = task(**data)
^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/lutris/runners/commands/wine.py", line 158, in create_prefix
wineenv["PROTONPATH"] = proton.get_proton_path_from_bin(wine_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/lutris/util/wine/proton.py", line 110, in get_proton_path_from_bin
return os.path.abspath(os.path.join(os.path.dirname(wine_path), "../../"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 415, in abspath
2024-10-13 02:33:36,669: Last install command failed, show error
```

### System Information

```shell
trying this on arch linux
Linux 6.11.1-arch1-1
Machine:
  Type: Laptop System: Acer product: Nitro AN515-45 v: V1.11 
CPU:
  Info: 8-core model: AMD Ryzen 7 5800H with Radeon Graphics bits: 64 type: MT MCP smt: enabled
    arch: Zen 3 rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 3241 high: 4405 min/max: 400/4463 cores: 1: 4376 2: 3773 3: 3368 4: 3575
    5: 3999 6: 3516 7: 3697 8: 4368 9: 4235 10: 400 11: 3493 12: 400 13: 3496 14: 400 15: 4367
    16: 4405 bogomips: 102214
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3
```

**Comment by danieljohnson2** [comment]
We've done a lot of work on this area of the code, and I think this won't happen anymore.

Please try [the master branch](https://github.com/lutris/lutris)- download the code and run the ``bin/lutris`` script within; no need to install it. Try the installer again; any better?

**Comment by Reynardd** [comment]
so it doesnt say FileNotFound anymore
it seems that it fails to install battlenet
here's the log
 ➥  ./lutris 
2024-10-16 14:59:46,754: Command 'vulkaninfo' not found on your system
2024-10-16 14:59:47,021: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
2024-10-16 14:59:47,256: Starting Lutris 0.5.18
2024-10-16 14:59:47,268: "card1" is NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (10de:2520 1025:151e nvidia) Driver 560.35.03
2024-10-16 14:59:47,280: "card2" is Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (1002:1638 1025:151e amdgpu) Driver None

(lutris:18930): Gtk-WARNING **: 14:59:47.464: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop
2024-10-16 14:59:47,475: Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/home/reynard/Downloads/lutris/lutris/style_manager.py", line 81, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
2024-10-16 15:00:18,842: Download completed
2024-10-16 15:00:18,842: All files available
2024-10-16 15:00:18,843: All files are available, continuing install
2024-10-16 15:00:18,843: Launching installer commands
2024-10-16 15:00:18,877: Creating a win64 prefix in /home/reynard/Games/battlenet
2024-10-16 15:00:18,877: Winepath: /home/reynard/.local/share/lutris/runtime/umu/umu_run.py
lutris-wrapper: /home/reynard/.local/share/lutris/runtime/umu/umu_run.py
Started initial process 18964 from /home/reynard/.local/share/lutris/runtime/umu/umu_run.py createprefix
Start monitoring process.
[umu_run] DEBUG: Connecting to '1.1.1.1'...
[umu_runtime] DEBUG: Root: /home/reynard/.local/share/lutris/runtime/umu/umu-run/umu
[umu_runtime] DEBUG: Local: /home/reynard/.local/share/umu
[umu_proton] DEBUG: Sending request to 'api.github.com'...
[umu_runtime] DEBUG: Existing install detected
[umu_runtime] DEBUG: Sending request to 'repo.steampowered.com'...
[umu_runtime] DEBUG: Runtime: sniper_platform_0.20241008.104210
[umu_runtime] DEBUG: Codename: sniper
GE-Proton is up to date
[umu_run] DEBUG: steamuser in prefix is link: False
[umu_run] DEBUG: user in prefix is link: True
[umu_run] WARNING: Executable not found: createprefix
[umu_run] INFO: WINEPREFIX=/home/reynard/Games/battlenet
[umu_run] INFO: GAMEID=umu-default
[umu_run] INFO: PROTON_CRASH_REPORT_DIR=/tmp/umu_crashreports
[umu_run] INFO: PROTONPATH=/home/reynard/.local/share/Steam/compatibilitytools.d/GE-Proton9-16
[umu_run] INFO: STEAM_COMPAT_APP_ID=default
[umu_run] INFO: STEAM_COMPAT_TOOL_PATHS=/home/reynard/.local/share/Steam/compatibilitytools.d/GE-Proton9-16:/home/reynard/.local/share/umu
[umu_run] INFO: STEAM_COMPAT_LIBRARY_PATHS=
[umu_run] INFO: STEAM_COMPAT_MOUNTS=/home/reynard/.local/share/Steam/compatibilitytools.d/GE-Proton9-16:/home/reynard/.local/share/umu
[umu_run] INFO: STEAM_COMPAT_INSTALL_PATH=
[umu_run] INFO: STEAM_COMPAT_CLIENT_INSTALL_PATH=
[umu_run] INFO: STEAM_COMPAT_DATA_PATH=/home/reynard/Games/battlenet
[umu_run] INFO: STEAM_COMPAT_SHADER_PATH=/home/reynard/Games/battlenet/shadercache
[umu_run] INFO: FONTCONFIG_PATH=
[umu_run] INFO: EXE=createprefix
[umu_run] INFO: SteamAppId=default
[umu_run] INFO: SteamGameId=default
[umu_run] INFO: STEAM_RUNTIME_LIBRARY_PATH=/usr/lib:/usr/lib/libfakeroot:/usr/lib32
[umu_run] INFO: STORE=
[umu_run] INFO: PROTON_VERB=waitforexitandrun
[umu_run] INFO: UMU_ID=umu-default
[umu_run] INFO: ULWGL_ID=umu-default
[umu_run] INFO: UMU_ZENITY=
[umu_run] INFO: UMU_NO_RUNTIME=
[umu_run] INFO: UMU_RUNTIME_UPDATE=
[umu_runtime] DEBUG: Source: /steamrt-images-sniper/snapshots/latest-container-runtime-public-beta/SteamLinuxRuntime_sniper.VERSIONS.txt?version=a5kt5R_b0WQ12gV-1oRQtw
[umu_runtime] DEBUG: Digest: b'\x8e\xad\x1bU\xda\xb7Q\xfe\xa2\xb7$\xa7H\x16\x1e\xf1\xd7\xfbX3\x8c\x94\xc3\x9d\xf5kV\xe3b\xc8.\x1d'
[umu_runtime] DEBUG: Source: /home/reynard/.local/share/umu/VERSIONS.txt
[umu_runtime] DEBUG: Digest: b'\x8e\xad\x1bU\xda\xb7Q\xfe\xa2\xb7$\xa7H\x16\x1e\xf1\xd7\xfbX3\x8c\x94\xc3\x9d\xf5kV\xe3b\xc8.\x1d'
steamrt is up to date
[umu_run] DEBUG: (PosixPath('/home/reynard/.local/share/umu/umu'), '--verb', 'waitforexitandrun', '--', PosixPath('/home/reynard/.local/share/Steam/compatibilitytools.d/GE-Proton9-16/proton'), 'waitforexitandrun', 'createprefix')
[umu_run] DEBUG: prctl exited with status: 0
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[19026]: W: Container startup will be faster if missing locales are created at OS level
Proton: Upgrading prefix from None to GE-Proton9-16 (/home/reynard/Games/battlenet/)
2024-10-16 15:00:22,379: win64 Prefix created in /home/reynard/Games/battlenet
2024-10-16 15:00:22,435: Winetricks is currently not supported with Proton
2024-10-16 15:00:22,485: Winetricks is currently not supported with Proton
ProtonFixes[19067] INFO: Running protonfixes
ProtonFixes[19067] INFO: Running checks
ProtonFixes[19067] INFO: All checks successful
ProtonFixes[19067] WARN: Game title not found in CSV
ProtonFixes[19067] INFO: Non-steam game UNKNOWN (umu-default)
ProtonFixes[19067] INFO: No store specified, using UMU database
ProtonFixes[19067] INFO: Using global defaults for UNKNOWN (umu-default)
ProtonFixes[19067] INFO: Non-steam game UNKNOWN (umu-default)
ProtonFixes[19067] INFO: No store specified, using UMU database
ProtonFixes[19067] INFO: No global protonfix found for UNKNOWN (umu-default)
Proton: createprefix
Proton: Executable is inside wine prefix, launching normally.
fsync: up and running.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

[umu_run] DEBUG: Child 18968 exited with wait status: 1
send: b'GET /steamrt-images-sniper/snapshots/latest-container-runtime-public-beta/SteamLinuxRuntime_sniper.VERSIONS.txt?version=a5kt5R_b0WQ12gV-1oRQtw HTTP/1.1\r\nHost: repo.steampowered.com\r\nAccept-Encoding: identity\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 16 Oct 2024 11:30:20 GMT
header: Content-Type: text/plain
header: Content-Length: 300
header: Connection: keep-alive
header: Last-Modified: Tue, 08 Oct 2024 12:53:06 GMT
header: ETag: "67052b32-12c"
header: Cache-Control: public
header: CF-Cache-Status: MISS
header: Accept-Ranges: bytes
header: Vary: Accept-Encoding
header: Server: cloudflare
header: CF-RAY: 8d37b7570c49368f-LHR
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2024-10-16 15:00:34,516: Failed to parse JSON from file /home/reynard/Games/battlenet/drive_c/users/reynard/AppData/Roaming/Battle.net/Battle.net.config
lutris-wrapper: /usr/bin/bash
Started initial process 19617 from /usr/bin/bash -c WINEESYNC=1 WINEPREFIX="/home/reynard/Games/battlenet" "/home/reynard/.local/share/lutris/runtime/umu/umu_run.py" "/home/reynard/Games/battlenet/drive_c/Battle.net-Setup.exe"
Start monitoring process.
steamrt is up to date
ERROR: Environment variable not set or is empty: GAMEID
Traceback (most recent call last):
  File "/home/reynard/.local/share/lutris/runtime/umu/umu_run.py/__main__.py", line 14, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/reynard/.local/share/lutris/runtime/umu/umu_run.py/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/home/reynard/.local/share/lutris/runtime/umu/umu_run.py/umu/umu_run.py", line 806, in main
    check_env(env, thread_pool)
  File "/home/reynard/.local/share/lutris/runtime/umu/umu_run.py/umu/umu_run.py", line 145, in check_env
    raise ValueError(err)
ValueError: Environment variable not set or is empty: GAMEID
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
2024-10-16 15:00:41,718: Battle.net (wine) has encountered an error: The file /home/reynard/Games/battlenet/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe could not be found
Traceback (most recent call last):
  File "/home/reynard/Downloads/lutris/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reynard/Downloads/lutris/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reynard/Downloads/lutris/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^
  File "/home/reynard/Downloads/lutris/lutris/runners/wine.py", line 1198, in play
    raise MissingGameExecutableError(filename=game_exe)
lutris.exceptions.MissingGameExecutableError: The file /home/reynard/Games/battlenet/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe could not be found
2024-10-16 15:00:41,719: The game has run for a very short time, did it crash?

**Comment by Reynardd** [comment]
but i must add
the installer was in drive_c folder
so i installed it and its working now and my problem is solved
thanks

**Comment by danieljohnson2** [comment]
Sounds the file really wasn't found, and this has been resolved. So I will close this item.
