### ISSUE TITLE
TypeError: 1 parameters needed for signal error; 0 given

### ISSUE THREAD

**Issue by abdulalalalalala** [lutris/lutris#5670]
### Bug description

Tried to install Cyberpunk from Gog, but failed due to a client error. I'm not sure if it's error from the installer itself or the Lutris client.

### How to Reproduce

1. Start Lutris in debug mode: `flatpak run -d net.lutris.Lutris`
2. Install game
4. Got a client error as shown in the log

### Expected behavior

Install game successfully

### Log output

```shell
2024-10-21 18:05:11,440: ['wine', '--version'] command failed: [Errno 2] No such file or directory: 'wine'
2024-10-21 18:05:11,440: Error reading wine version for wine
2024-10-21 18:53:48,175: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin returned a 403 error
2024-10-21 18:53:48,175: Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
2024-10-21 18:53:48,536: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin returned a 403 error
2024-10-21 18:53:48,536: Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
2024-10-21 18:53:49,057: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin returned a 403 error
2024-10-21 18:53:49,058: Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
2024-10-21 18:53:49,587: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin returned a 403 error
2024-10-21 18:53:49,588: Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
2024-10-21 18:53:50,047: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin returned a 403 error
2024-10-21 18:53:50,048: Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/app/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin
2024-10-21 18:53:50,312: Error handling timeout function: 1 parameters needed for signal error; 0 given
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/download_collection_progress_box.py", line 161, in _progress
    self.emit("error")
TypeError: 1 parameters needed for signal error; 0 given
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.11.3-200.fc40.x86_64
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900X 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 31.3 GB
Swap: 8.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.59, 6.11.3-200.fc40.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.3 (git-b235da6781)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.3 (git-b235da6781)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.3 (git-b235da6781)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon RX 6700 XT (RADV NAVI22) (1.3.289)
```

**Comment by abdulalalalalala** [comment]
the response's error code is 403, maybe token expired? it happens mostly to games with relatively large download size

**Comment by danieljohnson2** [comment]
We've had several reports of this; #5599 for one. We've fixed the broken signal and that improves error reporting, and we'll also do a better job of resuming these large downloads after they fail too.

But we still don't understand why some GOG users get this 403 on some files but not others. I use GOG and have never seen it myself.

I expect you can work around this by manually downloading the files yourself and having Lutris use those.

**Comment by abdulalalalalala** [comment]
thx for pointing me to #5599 @danieljohnson2 
yep, the workaround method with direct downloads solved the problem in terms of me trying to play a game.

since this isn't an isolated incident, i can reach out to gog to see what's going on on their backend. Do you perhaps know which endpoint Lutris is using for download?

is it this web endpoint: 

```
https://www.gog.com/downloads/<game_title>/<file_name>
```

or Lutris use a different API than the web?

**Comment by danieljohnson2** [comment]
You can see the URLs being downloaded in the log; you seem to have failed on ``https://gog-cdn-fastly.gog.com/token=nva=12312312312~dirs=6~token=abcdefghijklmnopqrstuvwxyz/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-14.bin``.
