### ISSUE TITLE
ImportError: No module named 'lutris.services'

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#568]
```
❯ lutris   
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/lutris", line 25, in <module>
    from lutris.gui.application import Application
  File "/usr/lib64/python3.4/site-packages/lutris/gui/application.py", line 31, in <module>
    from lutris.platforms import update_platforms
  File "/usr/lib64/python3.4/site-packages/lutris/platforms.py", line 29, in <module>
    _init_platforms()
  File "/usr/lib64/python3.4/site-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib64/python3.4/site-packages/lutris/runners/__init__.py", line 50, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/usr/lib64/python3.4/site-packages/lutris/runners/__init__.py", line 45, in get_runner_module
    globals(), locals(), [runner_name], 0)
  File "/usr/lib64/python3.4/site-packages/lutris/runners/steam.py", line 12, in <module>
    from lutris.services.steam import get_path_from_appmanifest
ImportError: No module named 'lutris.services'
```

**Comment by strycore** [comment]
Are you running the git version from the Gentoo overlay? `lutris.services` is here but I might not have added it to setup.py which would explain the error.

**Comment by strycore** [comment]
Should be good now.
