### ISSUE TITLE
'mame' object has no attribute 'wine_arch'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#5684]
### Bug description

Updated to the "latest" Git pull and Nothing works anymore. Get the 'runner' object has no attribute 'wine_arch' on all runners

### How to Reproduce

update to https://github.com/lutris/lutris/commit/085f865c481b4ee8ca5a17393f1edbc72244f380

try to run anything

### Expected behavior

Not to think that runner needs wine to run

### Log output

```shell
'mame' object has no attribute 'wine_arch'

Traceback (most recent call last):

  File "/home/te_lanus/src/lutris/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)

  File "/home/te_lanus/src/lutris/lutris/game.py", line 678, in configure_game
    if self.runner.wine_arch == "win32" and proton.is_umu_command(command):

AttributeError: 'mame' object has no attribute 'wine_arch'

Lutris log:
[INFO:2024-10-28 13:11:43,060:application]: Starting Lutris 0.5.18
[DEBUG:2024-10-28 13:11:43,506:system]: Executing lspci
[INFO:2024-10-28 13:11:43,705:startup]: "card0" is NVIDIA Corporation GF108 [GeForce GT 630] (10de:0f00 1458:3543 nvidia) Driver 390.157
[WARNING:2024-10-28 13:11:44,730:startup]: Vulkan reports an API version of 1.2.131. 1.3.0 is required for the latest DXVK.
[DEBUG:2024-10-28 13:11:55,259:xrandr]: Retrieving resolution list
[DEBUG:2024-10-28 13:11:55,348:xrandr]: Retrieving 9 video modes from XrandR
[DEBUG:2024-10-28 13:11:57,779:path_cache]: Checking for missing games
[DEBUG:2024-10-28 13:11:58,978:api]: Modified at Mon 28 Oct 2024 12:55:04, will update after Mon 28 Oct 2024 18:55:04
[DEBUG:2024-10-28 13:11:58,986:lutriswindow]: Runtime up to date
[ERROR:2024-10-28 13:11:59,984:style_manager]: Error reading color-scheme: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
Traceback (most recent call last):
  File "/home/te_lanus/src/lutris/lutris/style_manager.py", line 81, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
[DEBUG:2024-10-28 13:13:39,728:grid]: Item activated: 313
[INFO:2024-10-28 13:13:40,024:runner]: Runtime disabled by system configuration
[ERROR:2024-10-28 13:13:40,024:exception_backstops]: 19XX: The War Against Destiny (mame) has encountered an error: 'mame' object has no attribute 'wine_arch'
Traceback (most recent call last):
  File "/home/te_lanus/src/lutris/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
  File "/home/te_lanus/src/lutris/lutris/game.py", line 678, in configure_game
    if self.runner.wine_arch == "win32" and proton.is_umu_command(command):
AttributeError: 'mame' object has no attribute 'wine_arch'
[DEBUG:2024-10-28 13:13:40,025:game]: 19XX: The War Against Destiny (mame) has run for 0 seconds
[WARNING:2024-10-28 13:13:40,025:game]: The game has run for a very short time, did it crash?
[DEBUG:2024-10-28 13:13:40,025:game]: Playtime: Never played
[DEBUG:2024-10-28 13:13:40,060:application]: Removing 313 from running IDs
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 20.04 focal
Arch: x86_64
Kernel: 5.15.0-124-generic
Desktop: KDE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
Physical cores: 2
Logical cores: 4
[Memory]
RAM: 3.8 GB
Swap: 18.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: GeForce GT 630/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 390.157
OpenGL Core: 4.6.0 NVIDIA 390.157
OpenGL ES: OpenGL ES 3.2 NVIDIA 390.157
Vulkan Version: 1.2.131
Vulkan Drivers:
```

**Comment by danieljohnson2** [comment]
Oh, I recognize that! I made a dumb mistake there. I'll fix that this evening.

**Comment by danieljohnson2** [comment]
OK, dumb mistake fixed. The Wine specific compatibility check needs to be in the wine code (``runners/wine.py``) and not ``game.py``, where every game hits it and non-Wine games don't like it much.

When I did it, I did not even notice which file it was in.

``lutris-git`` saves the day again!
