### ISSUE TITLE
Linux native games no longer run in master branch

### ISSUE THREAD

**Issue by ToRRent1812** [lutris/lutris#5685]
### Bug description

I compiled master branch of the app to test it, and it looks like umu integration doesn't like linux native games since it no longer allows those games to run.

Error message:
'linux' object has no attribute 'wine_arch'

### How to Reproduce

1. Install linux native game
2. Try to launch it

### Expected behavior

launch the game without taking umu into account

### Log output

```shell
Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 678, in configure_game
    if self.runner.wine_arch == "win32" and proton.is_umu_command(command):
       ^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'linux' object has no attribute 'wine_arch'

Lutris log:
[INFO:2024-10-28 21:16:27,161:application]: Starting Lutris 0.5.18
[INFO:2024-10-28 21:16:27,205:startup]: "card1" is AMD Radeon RX 6950 XT (1002:73a5 1da2:441d amdgpu) Driver 24.1.7
[ERROR:2024-10-28 21:17:17,799:game_common]: Unable to load media 'coverart_big': gdk-pixbuf-error-quark: Nie można rozpoznać formatu obrazu w pliku „/home/rabbit/.cache/lutris/coverart/xdefiant.jpg” (3)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/game_common.py", line 357, in _set_image
    image = ScaledImage.new_from_media_path(media_path, service_media.config_ui_size, scale_factor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/scaled_image.py", line 48, in new_from_media_path
    pixbuf = get_pixbuf_by_path(path, pixbuf_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/utils.py", line 136, in get_pixbuf_by_path
    return GdkPixbuf.Pixbuf.new_from_file_at_size(path, width, height)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Nie można rozpoznać formatu obrazu w pliku „/home/rabbit/.cache/lutris/coverart/xdefiant.jpg” (3)
[ERROR:2024-10-28 21:19:38,358:exception_backstops]: Super Mario 64 (linux) has encountered an error: 'linux' object has no attribute 'wine_arch'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 678, in configure_game
    if self.runner.wine_arch == "win32" and proton.is_umu_command(command):
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'linux' object has no attribute 'wine_arch'
[WARNING:2024-10-28 21:19:38,359:game]: The game has run for a very short time, did it crash?
[ERROR:2024-10-28 21:20:04,343:exception_backstops]: Super Mario 64 (linux) has encountered an error: 'linux' object has no attribute 'wine_arch'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 678, in configure_game
    if self.runner.wine_arch == "win32" and proton.is_umu_command(command):
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'linux' object has no attribute 'wine_arch'
[WARNING:2024-10-28 21:20:04,343:game]: The game has run for a very short time, did it crash?
[ERROR:2024-10-28 21:20:14,285:exception_backstops]: Super Mario 64 (linux) has encountered an error: 'linux' object has no attribute 'wine_arch'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 678, in configure_game
    if self.runner.wine_arch == "win32" and proton.is_umu_command(command):
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'linux' object has no attribute 'wine_arch'
[WARNING:2024-10-28 21:20:14,285:game]: The game has run for a very short time, did it crash?
```

### System Information

```shell
Vulkan support: TAK
Esync support: TAK
Fsync support: TAK
Wine installed: TAK
Gamescope: TAK
Mangohud: TAK
Gamemode: TAK
Steam: TAK
In Flatpak: NIE
[System]
OS: openSUSE Tumbleweed 20241025 n/a
Arch: x86_64
Kernel: 6.11.5-1-default
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 3900X 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 15.5 GB
Swap: 15.5 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6950 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.59, 6.11.5-1-default)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.7
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.7
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.7
Vulkan Version: 1.3.296
Vulkan Drivers: AMD Radeon RX 6950 XT (RADV NAVI21) (1.3.278)
```

**Comment by danieljohnson2** [comment]
This is a dupe of #5684; fixed with the same fix.
