### ISSUE TITLE
I cant open Epic Games Launcher

### ISSUE THREAD

**Issue by WxnterYT** [lutris/lutris#5708]
this is the log Started initial process 1091 from gamemoderun /home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py /home/wxnter/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
Waiting for game to start (first non-excluded process started)
gamemodeauto: 
[1mumu-launcher version 1.1.3 (3.11.9 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0])[0m
[1mSetting up Unified Launcher for Windows Games on Linux...[0m
[1mDownloading latest steamrt sniper, please wait...[0m
[1mDownloading UMU-Proton-9.0-3.2.sha512sum...[0m
[1mDownloading UMU-Proton-9.0-3.2.tar.gz...[0m
[1mSteamLinuxRuntime_sniper.tar.xz: SHA256 is OK[0m
[31mERROR: [1m[Errno 28] No space left on device[0m
Traceback (most recent call last):
  File "/home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/__main__.py", line 14, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/umu/umu_run.py", line 847, in main
    check_env(env, thread_pool)
  File "/home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/umu/umu_run.py", line 184, in check_env
    get_umu_proton(env, thread_pool)
  File "/home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/umu/umu_proton.py", line 66, in get_umu_proton
    if _get_latest(env, STEAM_COMPAT, tmpdirs, assets, thread_pool) is env:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/umu/umu_proton.py", line 314, in _get_latest
    _fetch_proton(env, tmpdirs[0], assets)
  File "/home/wxnter/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py/umu/umu_proton.py", line 198, in _fetch_proton
    file.write(view[:size])
OSError: [Errno 28] No space left on device
gamemodeauto: 
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0

**Comment by danieljohnson2** [comment]
Hmmm. This is blowing up inside of Umu, and the error seems to be that your disk is full.

Is your disk full?

**Comment by legluondunet** [comment]
This repository is not a place for requesting support with a game, runner or an installer.
If you have issues installing a game or launching it, make sure you follow our essential guides on [graphics driver installation](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) and [dependencies for the wine runner](https://github.com/lutris/docs/blob/master/WineDependencies.md).
If you followed the guides and the issues persist, try asking for help in our official [Lutris Discord Server](https://discord.com/invite/Pnt5CuY).
