### ISSUE TITLE
Thief problems

### ISSUE THREAD

**Issue by crusader-mike** [lutris/lutris#5720]
### Bug description

`Thief Gold` game has `GOG + NewDark version` installation option -- it is broken. When you use it it presents this screen:
![image](https://github.com/user-attachments/assets/cf09ffce-53fb-401d-9341-a51870770458)

this screen doesn't look right -- it asks for `setup file from GOG` and at the same time indicates it will download it automatically. I assumed it might be asking for `TFix_1.27b.exe` file, but then it runs it before main setup file and it fails (because it can't find a game installation to patch).

Also:
- there are some weird errors in the log
- cutscenes don't work -- looks like smth is missing (smth TFix was supposed to install, maybe?)

### How to Reproduce

1. Select `GOG` in sources, find `Thief Gold`, righ-click, install
2. Select `GOG + NewDark version`
3. observe issues

### Expected behavior

Ideally installation supposed to work with unambiguous dialog boxes and without errors in the log. Plus, working cutscenes would be nice too.

### Log output

```shell
INFO     2024-11-13 14:16:29,315 [application.do_command_line:479]:Starting Lutris 0.5.18
WARNING: [Loader Message] Code 0 : loader_scan_for_direct_drivers: The VK_LUNARG_direct_driver_loading extension was enabled but the pNext chain of VkInstanceCreateInfo did not contain the VkDirectDriverLoadingListLUNARG structure.
INFO     2024-11-13 14:16:29,375 [startup.run_all_checks:120]:"card1" is AMD Radeon Graphics (1002:164e 1043:8877 amdgpu) Driver None
WARNING: [Loader Message] Code 0 : loader_scan_for_direct_drivers: The VK_LUNARG_direct_driver_loading extension was enabled but the pNext chain of VkInstanceCreateInfo did not contain the VkDirectDriverLoadingListLUNARG structure.
INFO     2024-11-13 14:16:29,485 [startup.run_all_checks:120]:"card2" is NVIDIA GeForce RTX 4060 (10de:2882 1462:5161 nvidia) Driver 560.35.03
WARNING: [Loader Message] Code 0 : loader_scan_for_direct_drivers: The VK_LUNARG_direct_driver_loading extension was enabled but the pNext chain of VkInstanceCreateInfo did not contain the VkDirectDriverLoadingListLUNARG structure.
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-11-13 14:16:29,491 [system.read_process_output:189]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
DEBUG    2024-11-13 14:16:29,491 [system._execute:109]:Executing lspci
INFO     2024-11-13 14:16:29,511 [startup.run_all_checks:120]:"card0" is No GPU (simple-framebuffer) Driver None
DEBUG    2024-11-13 14:16:29,732 [path_cache._update_missing_games:114]:Checking for missing games
WARNING  2024-11-13 14:16:29,749 [base.is_authenticated:473]:Tried to get auth status while login in progress
DEBUG    2024-11-13 14:16:29,756 [api.check_stale_runtime_versions:52]:Modified at Wed 13 Nov 2024 02:14:39 PM , will update after Wed 13 Nov 2024 08:14:39 PM 
DEBUG    2024-11-13 14:16:29,757 [lutriswindow.create_runtime_updater_cb:1329]:Runtime up to date
DEBUG    2024-11-13 14:16:30,734 [http._request:88]:POST https://lutris.net/api/users/library?since=1731528879
DEBUG    2024-11-13 14:16:36,125 [base.install:335]:Installing 1207658997 from service gog
DEBUG    2024-11-13 14:16:36,125 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2024-11-13 14:16:36,518 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/thief-gold
DEBUG    2024-11-13 14:16:36,518 [http._request:88]:GET https://lutris.net/api/installers/thief-gold
DEBUG    2024-11-13 14:16:36,952 [application.show_window:395]:Showing window InstallerWindow1207658997
DEBUG    2024-11-13 14:16:38,925 [displayconfig.get_current_resolution:639]:Retrieving current resolution
DEBUG    2024-11-13 14:16:41,399 [wine.get_installer_runner_version:844]:Default wine version is wine-ge-8-26
DEBUG    2024-11-13 14:16:41,416 [gog.get_extras:340]:Download extras for GOG ID 1207658997 and its DLCs
INFO     2024-11-13 14:16:41,416 [gog.get_game_details:289]:Getting game details for 1207658997
DEBUG    2024-11-13 14:16:41,416 [http._request:88]:GET https://auth.gog.com/token?client_id=46899977096215655&client_secret=9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9&grant_type=refresh_token&refresh_token=tS7zE-EVelt7q6KWxTzl30I0zVxKaRws_wcnuPhtUPex7ZIZGABlk6s7rc7zxcYp
DEBUG    2024-11-13 14:16:41,849 [http._request:88]:GET https://api.gog.com/products/1207658997?expand=downloads&locale=en-US
INFO     2024-11-13 14:16:42,154 [gog.get_game_details:289]:Getting game details for 1207658997
DEBUG    2024-11-13 14:16:42,155 [http._request:88]:GET https://api.gog.com/products/1207658997?expand=downloads&locale=en-US
DEBUG    2024-11-13 14:16:42,247 [installerwindow.present_extras_page:533]:Showing extras page
INFO     2024-11-13 14:16:51,711 [installer.prepare_game_files:168]:Getting files for patch
INFO     2024-11-13 14:16:51,711 [gog.get_game_details:289]:Getting game details for 1207658997
DEBUG    2024-11-13 14:16:51,711 [http._request:88]:GET https://api.gog.com/products/1207658997?expand=downloads&locale=en-US
INFO     2024-11-13 14:16:51,799 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658997/downlink/installer/en1installer0
DEBUG    2024-11-13 14:16:51,800 [http._request:88]:GET https://api.gog.com/products/1207658997/downlink/installer/en1installer0
DEBUG    2024-11-13 14:16:52,183 [installerwindow.on_files_prepared:619]:Game files prepared.
DEBUG    2024-11-13 14:16:52,186 [installerwindow.present_installer_files_page:634]:Presenting installer files page
DEBUG    2024-11-13 14:17:03,324 [files_box.on_file_available:108]:setup is available
DEBUG    2024-11-13 14:17:03,324 [files_box.on_file_available:108]:patch is available
INFO     2024-11-13 14:17:03,324 [files_box.on_file_available:114]:All files available
INFO     2024-11-13 14:17:03,324 [installerwindow.on_files_available:664]:All files are available, continuing install
INFO     2024-11-13 14:17:03,325 [cache.save_to_cache:46]:File /home/crusader/Downloads/lutris_cache/thief-gold/gog/setup_thief_gold_1.26_nd_(21948).exe is already cached in /home/crusader/Downloads/lutris_cache/thief-gold/gog
INFO     2024-11-13 14:17:03,326 [installerwindow.launch_installer_commands:672]:Launching installer commands
DEBUG    2024-11-13 14:17:03,327 [interpreter.create_game_folder:221]:Creating destination path /home/crusader/Games/gog/thief-gold
DEBUG    2024-11-13 14:17:03,327 [interpreter._iter_commands:315]:Installer command: {'task': {'arch': 'win32', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2024-11-13 14:17:03,368 [wine.create_prefix:115]:Creating a win32 prefix in /home/crusader/Games/gog/thief-gold
INFO     2024-11-13 14:17:03,368 [wine.create_prefix:134]:Winepath: /home/crusader/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
DEBUG    2024-11-13 14:17:03,368 [system._execute:109]:Executing /home/crusader/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineboot
DEBUG    2024-11-13 14:17:03,368 [system._execute:115]:WINEARCH=win32 WINEPREFIX=/home/crusader/Games/gog/thief-gold WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/crusader/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/mono WINE_GECKO_CACHE_DIR=/home/crusader/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/gecko
INFO     2024-11-13 14:17:08,372 [wine.create_prefix:185]:win32 Prefix created in /home/crusader/Games/gog/thief-gold
DEBUG    2024-11-13 14:17:08,387 [interpreter._iter_commands:315]:Installer command: {'task': {'app': 'vcrun2008', 'arch': 'win32', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
Started initial process 603680 from /home/crusader/.local/share/lutris/runtime/winetricks/winetricks -q vcrun2008
Start monitoring process.
Executing cd /home/crusader/.local/share/lutris/runtime/winetricks
Using winetricks 20240105-next - sha256sum: 65d5aaffa155adcb1883aa71fb7e14a90a899dcac11e66e6ff368de40f3f0a79 with wine-8.0-3001-g39021e609a2 (Staging) and WINEARCH=win32
Executing w_do_call vcrun2008
Executing load_vcrun2008 
Using native,builtin override for following DLLs: atl90 msvcm90 msvcp90 msvcr90 vcomp90
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfcloc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfcloc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfcloc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfcloc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.mfcloc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing rm -rf /home/crusader/Games/gog/thief-gold/dosdevices/c:/windows/winsxs/manifests/x86_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef.manifest
Executing /home/crusader/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
Executing cd /home/crusader/.cache/winetricks/vcrun2008
Executing /home/crusader/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine vcredist_x86.exe /q
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2024-11-13 14:17:13,830 [monitored_command.on_stop:228]:Process 603674 has terminated with code 0
DEBUG    2024-11-13 14:17:14,469 [commands._monitor_task:445]:Return code: 0
DEBUG    2024-11-13 14:17:14,469 [interpreter._iter_commands:315]:Installer command: {'task': {'app': 'directx9', 'arch': 'win32', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
Started initial process 604666 from /home/crusader/.local/share/lutris/runtime/winetricks/winetricks -q directx9
Start monitoring process.
Executing cd /home/crusader/.local/share/lutris/runtime/winetricks
Using winetricks 20240105-next - sha256sum: 65d5aaffa155adcb1883aa71fb7e14a90a899dcac11e66e6ff368de40f3f0a79 with wine-8.0-3001-g39021e609a2 (Staging) and WINEARCH=win32
Executing w_do_call directx9
Executing load_directx9 
------------------------------------------------------
warning: directx9 is deprecated. Please install individual directx components (e.g., `/home/crusader/.local/share/lutris/runtime/winetricks/winetricks d3dx9`) instead.
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2024-11-13 14:17:16,796 [monitored_command.on_stop:228]:Process 604664 has terminated with code 0
DEBUG    2024-11-13 14:17:17,550 [commands._monitor_task:445]:Return code: 0
DEBUG    2024-11-13 14:17:17,550 [interpreter._iter_commands:315]:Installer command: {'task': {'executable': '$setup', 'name': 'wineexec', 'prefix': '$GAMEDIR'}}
Started initial process 605521 from /home/crusader/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/crusader/Downloads/TFix_1.27b.exe
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
DEBUG    2024-11-13 14:17:34,961 [monitored_command.on_stop:228]:Process 605519 has terminated with code 256
DEBUG    2024-11-13 14:17:35,637 [commands._monitor_task:445]:Return code: 256
ERROR    2024-11-13 14:17:35,637 [errors.__init__:19]:Command exited with code 256
ERROR    2024-11-13 14:17:35,637 [exception_backstops.error_wrapper:81]:Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/home/crusader/Games/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/home/crusader/Games/lutris/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
  File "/home/crusader/Games/lutris/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```

### System Information

```shell
[INFO:2024-11-13 14:21:57,872:application]: Starting Lutris 0.5.18
[INFO:2024-11-13 14:21:57,902:startup]: "card1" is AMD Radeon Graphics (1002:164e 1043:8877 amdgpu) Driver None
[INFO:2024-11-13 14:21:58,011:startup]: "card2" is NVIDIA GeForce RTX 4060 (10de:2882 1462:5161 nvidia) Driver 560.35.03
[ERROR:2024-11-13 14:21:58,017:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-11-13 14:21:58,037:startup]: "card0" is No GPU (simple-framebuffer) Driver None
[WARNING:2024-11-13 14:21:58,263:base]: Tried to get auth status while login in progress
```

**Comment by natanox** [comment]
There are multiple problems at play here it seems. 

- That specific install script should ask you for *two* local files, not only one. However it skips the first one.
- Lutris seemingly detected the game to be available via your connected GOG account and offers it (even without the script instructing it to do so), however also attempts to respect the script which tells him to ask for two files but none of them being associated with a GOG ID. Perhaps a bug in the script interpreter.

Regarding the game I'd be more than happy to fix up the installer and take over maintainership for it as I'm a huge fan of the series and well aware of its technical flaws. Regarding the cutscenes, you most likely lack the "Indeo" video codec. Try installing it via winetricks, then manually install TFix 1.27b once again inside the games' prefix.

Posting the offending script in here for further debugging given I might edit the one on lutris.net later.

```
files:
- patch: N/A:Select NewDark (TFix) Patch file
- setup: N/A:Select setup file from GOG
game:
  arch: win32
  exe: $GAMEDIR/drive_c/GOG Games/Thief Gold/THIEF.EXE
  prefix: $GAMEDIR
installer:
- task:
    arch: win32
    name: create_prefix
    prefix: $GAMEDIR
- task:
    app: vcrun2008
    arch: win32
    name: winetricks
    prefix: $GAMEDIR
- task:
    app: directx9
    arch: win32
    name: winetricks
    prefix: $GAMEDIR
- task:
    description: Installing Thief
    executable: $setup
    name: wineexec
    prefix: $GAMEDIR
- task:
    description: Installing NewDark
    executable: $patch
    name: wineexec
    prefix: $GAMEDIR
system:
  pulse_latency: false
wine:
  overrides:
    openal32: b
```

**Comment by natanox** [comment]
@crusader-mike By the Builder, thee wishes of installment shall be fulfilled.
https://codeberg.org/Natanox/lutris-installers/src/branch/main/Thief%20Gold%20-%20The%20Dark%20Project
Do not use the "Install now" button, it will lead to the old install script until the mods green-lit the new revision.


In regards to the Lutris bug, it seems that any file that comes first in the array gets overwritten by the GOG source. I couldn't find any documentation for this behaviour, the example scripts on lutris.net simply expect you to put something across the lines of 
```- installer: N/A:Select GOG Install file``` 
at the beginning of your files list. Since this even happens if you do not mention any `gogid` in the `games` section this is definitely unexpected behaviour.

Something like
```- installer: $GOG:gogid:123456789```
Would be preferable here to respect the existing `$STEAM` notation.

**Comment by crusader-mike** [comment]
@natanox 
Then came the Builder who brought us the Hammer,
And with it we forged a new way of life.

Praise the Builder! It works like a charm, in 4k with cutscenes. :-D

Thank you!

**Comment by legluondunet** [comment]
This repository is not a place for requesting support with a game, runner or an installer.
If you have issues installing a game or launching it, make sure you follow our essential guides on [graphics driver installation](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) and [dependencies for the wine runner](https://github.com/lutris/docs/blob/master/WineDependencies.md).
If you followed the guides and the issues persist, try asking for help in our official [Lutris Discord Server](https://discord.com/invite/Pnt5CuY).
