### ISSUE TITLE
TypeError: 'staticmethod' object is not callable

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#5731]
### Bug description

Trying to open preference and the error occur

### How to Reproduce

![image](https://github.com/user-attachments/assets/44892c98-3d44-45c1-86b2-64a16a5aebf7)

### Expected behavior

not to error out

### Log output

```shell
'staticmethod' object is not callable

Traceback (most recent call last):

  File "/home/te_lanus/src/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)

  File "/home/te_lanus/src/lutris/lutris/gui/lutriswindow.py", line 1067, in on_preferences_activate
    self.application.show_window(PreferencesDialog, parent=self)

  File "/home/te_lanus/src/lutris/lutris/gui/application.py", line 385, in show_window
    window_inst = window_class(**kwargs)

  File "/home/te_lanus/src/lutris/lutris/gui/config/preferences_dialog.py", line 50, in __init__
    self.stack.add_named(self.build_scrolled_window(InterfacePreferencesBox(self.accelerators)), "prefs-stack")

  File "/home/te_lanus/src/lutris/lutris/gui/config/preferences_box.py", line 65, in __init__
    widget = self._create_choice_setting(**option_dict)

  File "/home/te_lanus/src/lutris/lutris/gui/config/preferences_box.py", line 118, in _create_choice_setting
    expanded = _expand_combobox_choices()

TypeError: 'staticmethod' object is not callable

Lutris log:
[INFO:2024-11-19 05:01:58,796:application]: Starting Lutris 0.5.18
[DEBUG:2024-11-19 05:01:58,822:system]: Executing lspci
[INFO:2024-11-19 05:01:58,961:startup]: "card0" is NVIDIA Corporation GF108 [GeForce GT 630] (10de:0f00 1458:3543 nvidia) Driver 390.157
[WARNING:2024-11-19 05:01:59,419:startup]: Vulkan reports an API version of 1.2.131. 1.3.0 is required for the latest DXVK.
[DEBUG:2024-11-19 05:02:02,921:xrandr]: Retrieving resolution list
[DEBUG:2024-11-19 05:02:02,965:xrandr]: Retrieving 9 video modes from XrandR
[DEBUG:2024-11-19 05:02:03,608:path_cache]: Checking for missing games
[DEBUG:2024-11-19 05:02:04,076:api]: Modified at Tue 19 Nov 2024 04:59:02, will update after Tue 19 Nov 2024 10:59:02
[DEBUG:2024-11-19 05:02:04,086:lutriswindow]: Runtime up to date
[ERROR:2024-11-19 05:02:04,777:style_manager]: Error reading color-scheme: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
Traceback (most recent call last):
  File "/home/te_lanus/src/lutris/lutris/style_manager.py", line 74, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
[ERROR:2024-11-19 05:02:14,282:exception_backstops]: Error handling signal 'activate': 'staticmethod' object is not callable
Traceback (most recent call last):
  File "/home/te_lanus/src/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/home/te_lanus/src/lutris/lutris/gui/lutriswindow.py", line 1067, in on_preferences_activate
    self.application.show_window(PreferencesDialog, parent=self)
  File "/home/te_lanus/src/lutris/lutris/gui/application.py", line 385, in show_window
    window_inst = window_class(**kwargs)
  File "/home/te_lanus/src/lutris/lutris/gui/config/preferences_dialog.py", line 50, in __init__
    self.stack.add_named(self.build_scrolled_window(InterfacePreferencesBox(self.accelerators)), "prefs-stack")
  File "/home/te_lanus/src/lutris/lutris/gui/config/preferences_box.py", line 65, in __init__
    widget = self._create_choice_setting(**option_dict)
  File "/home/te_lanus/src/lutris/lutris/gui/config/preferences_box.py", line 118, in _create_choice_setting
    expanded = _expand_combobox_choices()
TypeError: 'staticmethod' object is not callable
```

### System Information

```shell
Lutris: https://github.com/lutris/lutris/commit/7fa3f3bcbbbd0dc2d8cedba170a52703c0c80796

OS Kubuntu 20.04.6
```

**Comment by danieljohnson2** [comment]
I see the problem- ``@staticmethod`` can only be used here in Python 3.10 and later, and that's no good since we support back to 3.8 here. It is not needed, so I will just remove it.
