### ISSUE TITLE
Error when i tried to install league of legends JP server by searching in the search bar, 

### ISSUE THREAD

**Issue by 3ubaidUrRe7man** [lutris/lutris#5735]
### Bug description

just what i just mentioned

### How to Reproduce

1. Go to search
2. search on league of legends
3. choose  jp server
4. installs fine and then choose language.
5. in creating wine prefix fails to do so.

### Expected behavior

install league of legends

### Log output

```shell
Invalid Wine prefix path /league-of-legends, make sure to create the prefix before saving to a registry

Traceback (most recent call last):

  File "/app/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.12/site-packages/lutris/installer/commands.py", line 434, in task
    command = task(**data)
              ^^^^^^^^^^^^

  File "/app/lib/python3.12/site-packages/lutris/runners/commands/wine.py", line 375, in wineexec
    runner.prelaunch()

  File "/app/lib/python3.12/site-packages/lutris/runners/wine.py", line 1037, in prelaunch
    self.set_regedit_keys()

  File "/app/lib/python3.12/site-packages/lutris/runners/wine.py", line 981, in set_regedit_keys
    prefix_manager.clear_registry_subkeys(path, key)

  File "/app/lib/python3.12/site-packages/lutris/util/wine/prefix.py", line 133, in clear_registry_subkeys
    registry.save()

  File "/app/lib/python3.12/site-packages/lutris/util/wine/registry.py", line 156, in save
    raise OSError(

OSError: Invalid Wine prefix path /league-of-legends, make sure to create the prefix before saving to a registry

Lutris log:
[INFO:2024-11-21 20:12:12,220:application]: Starting Lutris 0.5.18
[INFO:2024-11-21 20:12:12,281:startup]: "card1" is Intel UHD Graphics 620 (8086:5917 1028:082c i915) Driver 24.2.6
[ERROR:2024-11-21 20:12:12,282:startup]: i386 libGL.so.1 missing (needed by opengl)
[ERROR:2024-11-21 20:12:12,282:startup]: i386 libvulkan.so.1 missing (needed by vulkan)
[ERROR:2024-11-21 20:12:12,282:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
[ERROR:2024-11-21 20:12:12,465:system]: ['wine', '--version'] command failed: [Errno 2] No such file or directory: 'wine'
[ERROR:2024-11-21 20:12:12,465:wine]: Error reading wine version for wine
[WARNING:2024-11-21 20:12:12,752:base]: Tried to get auth status while login in progress
[INFO:2024-11-21 20:13:06,258:file_box]: Download completed
[INFO:2024-11-21 20:13:06,258:files_box]: All files available
[INFO:2024-11-21 20:13:06,259:installerwindow]: All files are available, continuing install
[INFO:2024-11-21 20:13:06,259:installerwindow]: Launching installer commands
[INFO:2024-11-21 20:15:31,997:wine]: Creating a win64 prefix in /league-of-legends
[INFO:2024-11-21 20:15:31,997:wine]: Winepath: /home/realobaidurrehman/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[WARNING:2024-11-21 20:16:02,522:wine]: Wine prefix creation is taking longer than expected...
[ERROR:2024-11-21 20:23:52,329:wine]: No user.reg found after prefix creation. Prefix might not be valid
[INFO:2024-11-21 20:23:53,055:wine]: Creating a win64 prefix in /league-of-legends
[INFO:2024-11-21 20:23:53,056:wine]: Winepath: /home/realobaidurrehman/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[WARNING:2024-11-21 20:24:23,601:wine]: Wine prefix creation is taking longer than expected...
[ERROR:2024-11-21 20:32:13,424:wine]: No user.reg found after prefix creation. Prefix might not be valid
[ERROR:2024-11-21 20:32:13,537:system]: ['wine', '--version'] command failed: [Errno 2] No such file or directory: 'wine'
[ERROR:2024-11-21 20:32:13,537:wine]: Error reading wine version for wine
[WARNING:2024-11-21 20:32:13,537:wine]: Wine is not installed on your system; required dependencies may be missing.
[WARNING:2024-11-21 20:32:13,537:wine]: No valid prefix detected in /league-of-legends, creating one...
[INFO:2024-11-21 20:32:13,537:wine]: Creating a win64 prefix in /league-of-legends
[INFO:2024-11-21 20:32:13,538:wine]: Winepath: /home/realobaidurrehman/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[WARNING:2024-11-21 20:32:44,096:wine]: Wine prefix creation is taking longer than expected...
[ERROR:2024-11-21 20:40:33,855:wine]: No user.reg found after prefix creation. Prefix might not be valid
[ERROR:2024-11-21 20:40:33,864:registry]: No registry file at /league-of-legends/user.reg
[ERROR:2024-11-21 20:40:33,864:jobs]: Error while completing task <bound method CommandsMixin.task of <interpreter.ScriptInterpreter object at 0x7fad571c0f00 (lutris+installer+interpreter+ScriptInterpreter at 0x55ba69003600)>>: <class 'OSError'> Invalid Wine prefix path /league-of-legends, make sure to create the prefix before saving to a registry
[ERROR:2024-11-21 20:40:33,894:interpreter]: Last install command failed, show error
```

### System Information

```shell
Vulkan support: NO
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
ستيم: NO
In Flatpak: YES
[System]
OS: GNOME 47 Flatpak runtime
Arch: x86_64
Kernel: 6.11.8-300.fc41.x86_64
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 7.6 GB
Swap: 7.6 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.6 (git-c6b3580271)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.6 (git-c6b3580271)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.6 (git-c6b3580271)
Vulkan Version: 1.3.290
Vulkan Drivers: Intel(R) UHD Graphics 620 (KBL GT2) (1.3.289)
```

**Comment by danieljohnson2** [comment]
Looks like Wine prefix creation failed. But it also looks like your system version of Wine is not installed; we recommend you install that to pick up the dependencies Wine needs.

**Comment by strycore** [comment]
League of legends doesn't run on Linux
