### ISSUE TITLE
lutris 0.5.17 not launching on ubuntu 22.04

### ISSUE THREAD

**Issue by Muhammad-Mansour** [lutris/lutris#5741]
### Bug description

lutris is not opening after installing keeps getting the same error 
`AttributeError: 'NoneType' object has no attribute 'present'`

### How to Reproduce

i installed it through
```
sudo apt update 
sudo apt install lutris
```
and launch `lutris'

### Expected behavior

expected to open normally but instead it showed nothing just blank
after that i run `lutris -d` and i got this error

### Log output

```shell
INFO     2024-11-22 09:51:39,648 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-11-22 09:51:39,680 [startup.run_all_checks:120]:Intel UHD Graphics (8086:468b 17aa:3d06 i915) Driver 23.2.1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 343, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 139, in __init__
    self.sidebar.initialize_rows()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 444, in initialize_rows
    self.update_rows()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 563, in update_rows
    service = service_class()
  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 185, in __init__
    self.session_data = json.loads(token_file.read())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 20 column 1 (char 576)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 770, in do_command_line
    self.window.present()
AttributeError: 'NoneType' object has no attribute 'present'

```
```


### System Information

```shell
Linux linux 6.8.0-49-generic #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
and my gpu is rtx2050 for laptops
```

**Comment by danieljohnson2** [comment]
I think I've got this, but I need you to test it.

I think the problem is that you have something invalid in the file ``~/.cache/lutris/.egs.token``. Don't delete that yet!

Please [download the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install anything. This should now generate some log spam, but should be able to start and hopefully you can now use the Epic Games Store.

I'd like to see the console spam it gives you, as well.
