### ISSUE TITLE
Lutris takes long time when press save button and acelerate my fans (CPU supposing)

### ISSUE THREAD

**Issue by Milor123** [lutris/lutris#5749]
### Bug description

Lutris keep stuck for a long time when press save button for add one game o do change in exist game
![image](https://github.com/user-attachments/assets/e6ffaeef-ecab-4c7f-ab98-ccbdc1e0f94a)

looks like python problem.

### How to Reproduce

1. Edit exist game
2. Press save
3. Wait for 1 eternity and my fans go very fast like it overload the CPU

### Expected behavior

Save in 1 o 3 secods

### Log output

```shell
lutris -d
INFO     2024-11-24 15:59:09,995 [application.do_command_line:479]:Starting Lutris 0.5.18
INFO     2024-11-24 15:59:10,022 [startup.run_all_checks:120]:"card1" is Intel UHD Graphics 770 (8086:4680 1043:8694 i915) Driver 24.2.7
DEBUG    2024-11-24 15:59:10,658 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 15:59:10,659 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
DEBUG    2024-11-24 15:59:10,681 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-11-24 15:59:10,699 [api.check_stale_runtime_versions:52]:Modified at Sun 24 Nov 2024 03:58:43 PM , will update after Sun 24 Nov 2024 09:58:43 PM 
DEBUG    2024-11-24 15:59:10,699 [lutriswindow.create_runtime_updater_cb:1355]:Runtime up to date
DEBUG    2024-11-24 15:59:17,554 [application.show_window:395]:Showing window EditGameConfigDialog1
DEBUG    2024-11-24 15:59:19,846 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 15:59:19,847 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
DEBUG    2024-11-24 15:59:20,905 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 15:59:20,906 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
DEBUG    2024-11-24 15:59:20,908 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 15:59:20,909 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
ERROR    2024-11-24 16:00:32,512 [wine.extract_icon:1290]:Unable to extract icon from /mnt/Xafir/Games/Dragons Dogma 2/DD2.exe: 'Data length less than expected header length.'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1267, in extract_icon
    groups = extractor.get_group_icons()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 92, in get_group_icons
    grp_icon_dir.__unpack__(data)
  File "/usr/lib/python3.12/site-packages/pefile.py", line 1026, in __unpack__
    raise PEFormatError("Data length less than expected header length.")
pefile.PEFormatError: 'Data length less than expected header length.'
DEBUG    2024-11-24 16:00:32,513 [game.save:454]:Saving Dragons Dogma II (wine) with config ID dd2-1732193170
DEBUG    2024-11-24 16:00:32,513 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=dd2-1732193170, runner=wine) config to /home/noe/.local/share/lutris/games/dd2-1732193170.yml
DEBUG    2024-11-24 16:00:32,552 [application.on_app_window_destroyed:420]:Removed window EditGameConfigDialog1
DEBUG    2024-11-24 16:00:32,565 [path_cache.add_to_path_cache:47]:Adding Dragons Dogma II (wine) to path cache
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Manjaro Linux rolling Xahea
Arch: x86_64
Kernel: 6.11.9-x64v4-xanmod1
Lutris Version: 0.5.18
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-14500
Physical cores: 14
Logical cores: 20
[Memory]
RAM: 46.4 GB
Swap: 101.6 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 770 (ADL-S GT1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.7-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.7-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.7-arch1.1
Vulkan Version: 1.3.295
Vulkan Drivers: Intel(R) UHD Graphics 770 (ADL-S GT1) (1.3.289)
```

**Comment by danieljohnson2** [comment]
I can think of two things from your logs. One is that this is a failing attempt to extract an icon from the game's exe.

Please try setting the game's icon to something- anything but the Lutris sea-otter logo. Does that help? If so, that was the problem.

If not, maybe it's that invoking ``xrandr`` is slow- you seem to be doing it repeatedly. Try to run ``xrandr`` from your terminal. Any noticeable pause before you get the results?

**Comment by Milor123** [comment]
I think the same, but occurs with anything game, is very weird, I have multigpu, primary is iGPU and dGPPU for the games

```
xrandr
Screen 0: minimum 16 x 16, current 1920 x 1200, maximum 32767 x 32767
DP-1 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     74.85*+
   1600x1200     74.88  
   1440x1080     74.80  
   1400x1050     74.87  
   1280x1024     74.77  
   1280x960      74.86  
   1152x864      74.82  
   1024x768      74.67  
   800x600       74.91  
   640x480       74.77  
   320x240       73.82  
   1680x1050     74.79  
   1440x900      74.85  
   1280x800      74.76  
   1152x720      74.72  
   960x600       74.84  
   928x580       74.58  
   800x500       74.87  
   768x480       74.71  
   720x480       74.51  
   640x400       74.23  
   320x200       73.70  
   1920x1080     74.82  
   1600x900      74.89  
   1368x768      74.73  
   1280x720      74.78  
   1024x576      74.80  
   864x486       74.45  
   720x400       74.23  
   640x350       74.53  
```

if I not select a .exe file, the lutris save very fast like it should. But when it select a exe file, is a eternity, really whatever user think that is stuck

```
(lutris:335644): Gtk-WARNING **: 19:05:05.841: Could not init tracker3 search engine: The name is not activatable
DEBUG    2024-11-24 19:05:12,172 [game.save:454]:Saving Now-With-EXE (wine) with config ID xd-1732482143
DEBUG    2024-11-24 19:05:12,172 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=xd-1732482143, runner=wine) config to /home/noe/.local/share/lutris/games/xd-1732482143.yml
DEBUG    2024-11-24 19:05:12,180 [application.on_app_window_destroyed:420]:Removed window EditGameConfigDialog2
DEBUG    2024-11-24 19:05:12,188 [path_cache.add_to_path_cache:47]:Adding Now-With-EXE (wine) to path cache
DEBUG    2024-11-24 19:05:18,805 [application.show_window:395]:Showing window EditGameConfigDialog1
DEBUG    2024-11-24 19:05:23,286 [http._request:88]:GET https://lutris.net/api/games/dragonsdogmaii
DEBUG    2024-11-24 19:05:28,672 [lutris.download_lutris_media:176]:Unable to load dragonsdogmaii: HTTP Error 404: Not Found
DEBUG    2024-11-24 19:05:29,961 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 19:05:29,963 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
ERROR    2024-11-24 19:06:27,928 [wine.extract_icon:1290]:Unable to extract icon from /mnt/Xafir/Games/Dragons Dogma 2/DD2.exe: 'Data length less than expected header length.'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1267, in extract_icon
    groups = extractor.get_group_icons()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 92, in get_group_icons
    grp_icon_dir.__unpack__(data)
  File "/usr/lib/python3.12/site-packages/pefile.py", line 1026, in __unpack__
    raise PEFormatError("Data length less than expected header length.")
pefile.PEFormatError: 'Data length less than expected header length.'
DEBUG    2024-11-24 19:06:27,930 [game.save:454]:Saving Dragons Dogma II (wine) with config ID dd2-1732193170
DEBUG    2024-11-24 19:06:27,930 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=dd2-1732193170, runner=wine) config to /home/noe/.local/share/lutris/games/dd2-1732193170.yml
DEBUG    2024-11-24 19:06:27,946 [application.on_app_window_destroyed:420]:Removed window EditGameConfigDialog1
DEBUG    2024-11-24 19:06:27,962 [path_cache.add_to_path_cache:47]:Adding Dragons Dogma II (wine) to path cache
DEBUG    2024-11-24 19:07:51,455 [application.show_window:395]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x771d3ac64300 (LutrisWindow at 0x5f7a03af35e0)>}
DEBUG    2024-11-24 19:07:52,994 [application.on_app_window_destroyed:420]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x771d3ac64300 (LutrisWindow at 0x5f7a03af35e0)>}
INFO     2024-11-24 19:07:56,264 [game_common._switch_runner:600]:Creating new configuration with runner wine
WARNING  2024-11-24 19:07:58,544 [runner.game_config:92]:Accessing game config while runner wasn't given one.
WARNING  2024-11-24 19:07:58,544 [runner.game_config:92]:Accessing game config while runner wasn't given one.
ERROR    2024-11-24 19:07:58,544 [wine.game_exe:655]:The game doesn't have an executable
WARNING  2024-11-24 19:07:58,545 [runner.game_config:92]:Accessing game config while runner wasn't given one.
WARNING  2024-11-24 19:07:58,545 [runner.game_config:92]:Accessing game config while runner wasn't given one.
ERROR    2024-11-24 19:07:58,545 [wine.game_exe:655]:The game doesn't have an executable

(lutris:335644): Gtk-WARNING **: 19:08:35.311: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:35.692: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:35.931: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:37.269: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:37.798: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): GLib-GIO-CRITICAL **: 19:08:39.012: GFileInfo created without standard::size

(lutris:335644): GLib-GIO-CRITICAL **: 19:08:39.012: file ../glib/gio/gfileinfo.c: line 1845 (g_file_info_get_size): should not be reached

(lutris:335644): Gtk-WARNING **: 19:08:43.293: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:44.598: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:45.108: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:45.581: Could not init tracker3 search engine: The name is not activatable

(lutris:335644): Gtk-WARNING **: 19:08:46.454: Could not init tracker3 search engine: The name is not activatable
DEBUG    2024-11-24 19:08:59,190 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 19:08:59,192 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
DEBUG    2024-11-24 19:09:01,153 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 19:09:01,156 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
DEBUG    2024-11-24 19:09:01,160 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-24 19:09:01,161 [xrandr._get_vidmodes:18]:Retrieving 32 video modes from XrandR
DEBUG    2024-11-24 19:09:02,084 [http._request:88]:GET https://lutris.net/api/games/hogwarts-legacy
DEBUG    2024-11-24 19:09:15,792 [http._request:88]:GET https://lutris.net/games/banner/hogwarts-legacy.jpg
DEBUG    2024-11-24 19:09:16,217 [http.write_to_file:147]:Writing to /home/noe/.local/share/lutris/banners/hogwarts-legacy.jpg
DEBUG    2024-11-24 19:09:16,279 [http._request:88]:GET https://lutris.net/media/igdb/cover_big/co2gn3.jpg
DEBUG    2024-11-24 19:09:16,793 [http.write_to_file:147]:Writing to /home/noe/.local/share/lutris/coverart/hogwarts-legacy.jpg
DEBUG    2024-11-24 19:09:24,739 [game.save:454]:Saving Hogwarts Legacy (wine) with config ID hogwarts-legacy-1732493342
DEBUG    2024-11-24 19:09:24,739 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=hogwarts-legacy-1732493342, runner=wine) config to /home/noe/.local/share/lutris/games/hogwarts-legacy-1732493342.yml
ERROR    2024-11-24 19:09:24,744 [game.id:150]:The game 'Hogwarts Legacy' has no ID, it is not stored in the database.
DEBUG    2024-11-24 19:09:24,766 [path_cache.add_to_path_cache:47]:Adding Hogwarts Legacy (wine) to path cache
```

**Comment by danieljohnson2** [comment]
I can't make much sense of what you are saying, but looking at your logs my guess would be that the issue is icon extraction being slow. I have no idea *why* it should be slow for you and not others, and you do not seem to have done the experiment I wanted to test this.

I'll say it again- give your game an icon, and see if that helps.

**Comment by Milor123** [comment]
> I can't make much sense of what you are saying, but looking at your logs my guess would be that the issue is icon extraction being slow. I have no idea _why_ it should be slow for you and not others, and you do not seem to have done the experiment I wanted to test this.
> 
> I'll say it again- give your game an icon, and see if that helps.

Ohh excuse me for my english, like your said, the experiment of set icon manually solve temporally the problem

![image](https://github.com/user-attachments/assets/bbc07ee3-60cf-4417-bf6d-ee7ce0b4b050)

if select the icon works, and save fast
the other images dont take effect.

**Comment by danieljohnson2** [comment]
Yes, it's the rightmost one that matters- in the blue arrows. If that's been set, Lutris does not try to extract an icon from the .exe. That tells me the the icon extraction (which fails anyway) is slow for you.

I do not know why. But @strycore has been pretty down on the icon-extraction feature, and I think we could resolve this problem by just ripping it out altogether. It's been troublesome before.

@strycore, if this pushes you over the edge, let me know and I'll just nuke this feature entirely.

**Comment by Milor123** [comment]
> Sí, lo que importa es el que está más a la derecha: en las flechas azules. Si se ha configurado, Lutris no intenta extraer un icono del .exe. Eso me dice que la extracción del ícono (que falla de todos modos) es lenta para ti.
> 
> Yo no sé por qué. Pero @strycore ha estado bastante deprimido con la función de extracción de íconos, y creo que podríamos resolver este problema simplemente eliminándola por completo. Ha sido problemático antes.
> 
> @strycore, si esto te lleva al límite, házmelo saber y destruiré esta función por completo.

Let me take this opportunity to tell you something, I had my lutris full of things, but since this error started to occur, I decided to delete configurations, I deleted all the lutris folder with runners and everything. In other words, I started from 0 because I came to think that maybe my configuration had become obsolete in some lutris update. 

But the error persisted and I think I even compiled a git version, lutris-git with yay. But since nothing solved my problem then I had no choice but to come here.

Although I am glad that they are working with the images and icons, I always found it very frustrating to have to put the images manually, then I discovered that I had to put the same name associated with the lutris database to generate an image.

Thank you very much for your work !

**Comment by legluondunet** [comment]
Hello, is this issue still present in latest Lutris version 0.5.22?
Without answer, this ticket will be closed in 7 days.
