### ISSUE TITLE
Lutris won't install a game if you use ge-proton in an install script

### ISSUE THREAD

**Issue by kasha695** [lutris/lutris#5759]
### Bug description

If you set the following as a version of wine to use in an install script:

` version: ge-proton`

Lutris will attempt retrieve ge-proton-x86_64 as a wine runner and fail.

### How to Reproduce

1. Make an install script and set the wine version to ge-proton
2. Attempt to run the .yml file
3. Receive error

### Expected behavior

Lutris should be able to use ge-proton as is

### Log output

```shell
2024-12-03 11:49:44,779: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-12-03 11:49:44,974 [application.do_command_line:480]:Starting Lutris 0.5.18
INFO     2024-12-03 11:49:45,037 [startup.run_all_checks:120]:"card1" is AMD Radeon RX 5700 XT (1002:731f 1458:2313 amdgpu) Driver 24.2.7
DEBUG    2024-12-03 11:49:45,149 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-12-03 11:49:45,151 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-12-03 11:49:45,209 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-12-03 11:49:45,242 [api.check_stale_runtime_versions:52]:Modified at Tue 03 Dec 2024 11:36:15 , will update after Tue 03 Dec 2024 17:36:15 
DEBUG    2024-12-03 11:49:45,242 [lutriswindow.create_runtime_updater_cb:1358]:Runtime up to date
DEBUG    2024-12-03 11:49:52,277 [application.show_window:396]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x728de1649f40 (LutrisWindow at 0x59c04cde30b0)>}
DEBUG    2024-12-03 11:49:58,519 [__init__.read_script:24]:Loading script(s) from /home/phil/Titan Install.yml
DEBUG    2024-12-03 11:49:58,534 [application.show_window:396]:Showing window InstallerWindowafterfall-insanity-extended-edition
DEBUG    2024-12-03 11:49:58,535 [application.on_app_window_destroyed:421]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x728de1649f40 (LutrisWindow at 0x59c04cde30b0)>}
DEBUG    2024-12-03 11:49:59,529 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
INFO     2024-12-03 11:50:03,060 [interpreter.get_runners_to_install:255]:Runner wine needs to be installed
DEBUG    2024-12-03 11:50:03,060 [interpreter.install_runner:274]:Installing wine
DEBUG    2024-12-03 11:50:03,060 [runner.install:483]:Installing wine (version=ge-proton-x86_64, callback=<function ScriptInterpreter.install_runner.<locals>.install_more_runners at 0x728de16f6ca0>)
DEBUG    2024-12-03 11:50:03,060 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2024-12-03 11:50:03,213 [interpreter.install_runner:282]:Failed to retrieve wine (ge-proton-x86_64) information
ERROR    2024-12-03 11:50:03,213 [errors.__init__:19]:Failed to retrieve wine (ge-proton-x86_64) information
ERROR    2024-12-03 11:50:03,213 [exception_backstops.error_wrapper:81]:Error handling idle function: Failed to retrieve wine (ge-proton-x86_64) information
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(
  File "/usr/lib/python3.12/site-packages/lutris/runners/runner.py", line 495, in install
    raise RunnerInstallationError(_("Failed to retrieve {} ({}) information").format(self.name, version))
lutris.runners.RunnerInstallationError: Failed to retrieve wine (ge-proton-x86_64) information

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/installerwindow.py", line 453, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 283, in install_runner
    raise ScriptingError(ex.message) from ex
lutris.installer.errors.ScriptingError: Failed to retrieve wine (ge-proton-x86_64) information
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.12.1-arch1-1
Lutris Version: 0.5.18
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Physical cores: 4
Logical cores: 4
[Memory]
RAM: 31.3 GB
Swap: 0.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 5700 XT (radeonsi, navi10, LLVM 18.1.8, DRM 3.59, 6.12.1-arch1-1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.7-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.7-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.7-arch1.1
Vulkan Version: 1.3.295
Vulkan Drivers: AMD Radeon RX 5700 XT (RADV NAVI10) (1.3.289)
```

**Comment by strycore** [comment]
Not how it's gonna work

**Comment by danieljohnson2** [comment]
How is it going to work?

Maybe just don't specify a version in the installer at all, and Proton becomes the normal default anyway?

**Comment by strycore** [comment]
Version pinning is already used by wine. We can't mix wine and proton without creating a mess. 

In general, pinning Wine version to installers is a Bad Thing™ and I've written a bunch of code to unpin wine versions from installers.

If we want to do things properly, we need to keep track of regressions.
At the very least we need the following info:
- What broke
- What is the last known working version

I'm really glad we've found a way out of wine version pinning, one of the most cursed and misused lutris features.

**Comment by kasha695** [comment]
I shall forgo applying a wine version to my installers; I only need to apply it to my old games as some of them only work upto lutris-ge-6.19-1-x86_64.

This is for my own use-case, hopefully #4118 will be my saviour.
