### ISSUE TITLE
Lutris will not start

### ISSUE THREAD

**Issue by Kallestofeles** [lutris/lutris#576]
Starting Lutris:

```python
INFO     2017-05-28 19:07:57,719 [lutriswindow]:Connected to lutris.net as Kallestofeles
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 156, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.6/site-packages/lutris/gui/lutriswindow.py", line 152, in __init__
    steamapps_paths = steam.get_steamapps_paths(flat=True)
  File "/usr/lib/python3.6/site-packages/lutris/services/steam.py", line 142, in get_steamapps_paths
    folders = get_steamapps_paths_for_platform(platform)
  File "/usr/lib/python3.6/site-packages/lutris/services/steam.py", line 124, in get_steamapps_paths_for_platform
    return runner.get_steamapps_dirs()
  File "/usr/lib/python3.6/site-packages/lutris/runners/winesteam.py", line 317, in get_steamapps_dirs
    linux_path = self.parse_wine_path(path, self.prefix_path)
  File "/usr/lib/python3.6/site-packages/lutris/runners/winesteam.py", line 154, in prefix_path
    arch=self.game_config.get('arch')
  File "/usr/lib/python3.6/site-packages/lutris/runners/winesteam.py", line 348, in get_or_create_default_prefix
    self.create_prefix(prefix, arch=arch)
  File "/usr/lib/python3.6/site-packages/lutris/runners/winesteam.py", line 335, in create_prefix
    create_prefix(prefix_dir, arch=arch, wine_path=wine_path)
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 119, in create_prefix
    system.execute([wineboot_path], env=env)
  File "/usr/lib/python3.6/site-packages/lutris/util/system.py", line 64, in execute
    env=existing_env, cwd=cwd).communicate()
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1241, in _execute_child
    for k, v in env.items()]
  File "/usr/lib/python3.6/subprocess.py", line 1241, in <listcomp>
    for k, v in env.items()]
  File "/usr/lib/python3.6/os.py", line 798, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

No window appears, nothing happens. Lutris process starts running in the background - no interactable window.

Arch 64bit - XFCE
Any info needed, please ping me.

Thank you!

Kallestofeles

**Comment by Kallestofeles** [comment]
This makes little sense but running it as root, it opens up nicely:
`1 kallestofeles@Shoemaster /home/kallestofeles % sudo lutris                                               :(
[sudo] password for kallestofeles: 

(lutris:19047): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(lutris:19047): GLib-GIO-CRITICAL **: g_dbus_proxy_get_name_owner: assertion 'G_IS_DBUS_PROXY (proxy)' failed`

However, it is not acceptable to run any sort of user-application as root - especially when dealing with wine.

**Comment by Kallestofeles** [comment]
--Workaround--
Had to create the following folder:
/home/<username>/.local/share/lutris/runners/winesteam/**prefix**
Then Lutris started up normally.
Please fix this so that it would be created automatically upon first launch or installation! There was no indication to this in the logs as well. Found the solution here and decided to try as trial-and-error:
https://forums.lutris.net/t/antergos-wont-run-lutris/377/10
