### ISSUE TITLE
Epic games won't launch

### ISSUE THREAD

**Issue by MichelN86** [lutris/lutris#5767]
### Bug description

On the left panel i used epic, logged in and after that i get the prompt (see log output)

### How to Reproduce

See bug description

### Expected behavior

That it works!

### Log output

```shell
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)

  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 145, in do_reload
    self.load_icons()

  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 177, in load_icons
    service_media.render()

  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 87, in render
    self._render_filename(filename)

  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 48, in _render_filename
    thumb_image = thumbnail_image(thumb_image, self.remote_size)

  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 243, in thumbnail_image
    base_image = base_image.resize((width, height), resample=Image.Resampling.BICUBIC)

  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

AttributeError: module 'PIL.Image' has no attribute 'Resampling'

Lutris log:
[INFO:2024-12-05 20:04:49,110:application]: Starting Lutris 0.5.18
[INFO:2024-12-05 20:04:49,132:startup]: "card1" is Intel Graphics (8086:46a6 1462:1333 i915) Driver 24.0.3
[INFO:2024-12-05 20:04:49,366:startup]: "card0" is NVIDIA GeForce RTX 3070 Ti Laptop GPU (10de:24a0 1462:1333 nvidia) Driver 555.58.02
[ERROR:2024-12-05 20:06:47,667:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x75ce305224d0>: <class 'AttributeError'> module 'PIL.Image' has no attribute 'Resampling'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Pop!_OS 22.04 jammy
Arch: x86_64
Kernel: 6.9.3-76060903-generic
Lutris Version: 0.5.18
Desktop: pop:GNOME
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: 12th Gen Intel(R) Core(TM) i7-12700H
Physical cores: 14
Logical cores: 20
[Memory]
RAM: 62.5 GB
Swap: 20.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) Graphics (ADL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
Vulkan Version: 1.3.280
Vulkan Drivers: Intel(R) Graphics (ADL GT2) (1.3.274), NVIDIA GeForce RTX 3070 Ti Laptop GPU (1.3.278)
```

### Media (optional)

System is up to date!

![Schermafdruk van 2024-12-05 20-00-32](https://github.com/user-attachments/assets/0a628bfb-60fb-4e1c-a168-9fecc0834a30)

**Comment by danieljohnson2** [comment]
This looks like a dupe of #5445 - though that item says it's Linux Mint's fault, and you aren't running that.

But there's a workaround in there; check it out and see if that helps.
