### ISSUE TITLE
ubuntu 24.04.1 

### ISSUE THREAD

**Issue by Shauryatwari** [lutris/lutris#5770]
ran into this error while trying to install an exe file

No path can be generated for D3D Extras because no version information is available.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 325, in dispatch
    return method(params)
           ^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 434, in task
    command = task(**data)
              ^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/runners/commands/wine.py", line 355, in wineexec
    baseenv = runner.get_env(disable_runtime=disable_runtime)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 1150, in get_env
    self.dll_overrides.update(dll_manager.get_enabling_dll_overrides())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/wine/dll_manager.py", line 255, in get_enabling_dll_overrides
    if self.dll_exists(dll):
       ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/wine/dll_manager.py", line 132, in dll_exists
    return any(system.path_exists(os.path.join(self.path, arch, dll_name + ".dll")) for arch in self.archs.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/wine/dll_manager.py", line 132, in <genexpr>
    return any(system.path_exists(os.path.join(self.path, arch, dll_name + ".dll")) for arch in self.archs.values())
                                               ^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/wine/dll_manager.py", line 90, in path
    raise RuntimeError(

RuntimeError: No path can be generated for D3D Extras because no version information is available.

Lutris log:
[INFO:2024-12-06 15:41:13,763:application]: Starting Lutris 0.5.18
[INFO:2024-12-06 15:41:13,788:__init__]: Running migration: mess_to_mame
[INFO:2024-12-06 15:41:13,789:__init__]: Running migration: migrate_hidden_ids
[INFO:2024-12-06 15:41:13,789:__init__]: Running migration: migrate_steam_appids
[INFO:2024-12-06 15:41:13,790:__init__]: Running migration: migrate_banners
[INFO:2024-12-06 15:41:13,790:__init__]: Running migration: retrieve_discord_appids
[INFO:2024-12-06 15:41:13,790:retrieve_discord_appids]: Updating Games Discord APP ID's
[INFO:2024-12-06 15:41:13,791:__init__]: Running migration: migrate_sortname
[INFO:2024-12-06 15:41:13,791:migrate_sortname]: Adding blank sortname field to database
[INFO:2024-12-06 15:41:13,791:__init__]: Running migration: migrate_hidden_category
[INFO:2024-12-06 15:41:13,791:migrate_hidden_category]: Moving hidden games to the '.hidden' category
[INFO:2024-12-06 15:41:13,812:startup]: "card1" is Intel Xe Graphics (8086:9a49 17aa:3801 i915) Driver 24.0.9
[ERROR:2024-12-06 15:41:13,813:startup]: i386 libGL.so.1 missing (needed by opengl)
[ERROR:2024-12-06 15:41:13,813:startup]: i386 libvulkan.so.1 missing (needed by vulkan)
[ERROR:2024-12-06 15:41:13,813:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
[ERROR:2024-12-06 15:41:34,102:api]: Unable to get runner information: Unable to connect to server https://lutris.net/api/runners/wine: <urlopen error [Errno -3] Temporary failure in name resolution>
[ERROR:2024-12-06 15:41:34,428:api]: Unable to get runtimes from API: Unable to connect to server https://lutris.net/api/runtimes/versions?pci_ids=8086:9A49%2017AA:3801: <urlopen error [Errno 104] Connection reset by peer>
[INFO:2024-12-06 15:42:52,234:files_box]: All files available
[INFO:2024-12-06 15:42:52,234:installerwindow]: All files are available, continuing install
[INFO:2024-12-06 15:42:52,237:installerwindow]: Launching installer commands
[INFO:2024-12-06 15:42:52,301:wine]: Creating a win64 prefix in /home/shaurya/Games/kreo
[INFO:2024-12-06 15:42:52,301:wine]: Winepath: /usr/bin/wine
[INFO:2024-12-06 15:42:55,533:wine]: win64 Prefix created in /home/shaurya/Games/kreo
[ERROR:2024-12-06 15:42:55,554:jobs]: Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x7076b0a2fce0>: <class 'RuntimeError'> No path can be generated for D3D Extras because no version information is available.
[ERROR:2024-12-06 15:42:55,555:interpreter]: Last install command failed, show error

**Comment by danieljohnson2** [comment]
Looks like this is a network problem. Notice "<urlopen error [Errno -3] Temporary failure in name resolution>"? Seems like a DNS failure, so the version information could not be downloaded.

If this is indeed temporary, you might want to go to the Preferences dialog, Updates tab, and click all the "Check again" buttons you can find. If your networking is working again, this should download the missing files.

**Comment by strycore** [comment]
User support question, not a bug. Closing
