### ISSUE TITLE
error in lutris

### ISSUE THREAD

**Issue by edwinjijo2409** [lutris/lutris#5771]
### Bug description

i cant install a game in lutris

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

i want to downloard games from lutris without any error

### Log output

```shell
2024-12-06 18:57:57,605: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-12-06 18:57:57,886 [application.do_command_line:480]:Starting Lutris 0.5.18
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:688:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-12-06 18:57:57,907 [system.read_process_output:189]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
DEBUG    2024-12-06 18:57:57,907 [system._execute:109]:Executing lspci
INFO     2024-12-06 18:57:57,929 [startup.run_all_checks:120]:"card1" is Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon Vega Series / Radeon Vega Mobile Series] (1002:1636 1043:16cc amdgpu) Driver 24.3.1
WARNING  2024-12-06 18:57:57,974 [startup.check_vulkan:70]:Vulkan is not available or your system isn't Vulkan capable
DEBUG    2024-12-06 18:57:57,975 [path_cache.build_path_cache:42]:Game path cache built in 0.00 seconds
DEBUG    2024-12-06 18:57:58,117 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-12-06 18:57:58,120 [xrandr._get_vidmodes:18]:Retrieving 30 video modes from XrandR
DEBUG    2024-12-06 18:57:58,176 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2024-12-06 18:57:58,465 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-12-06 18:57:58,509 [http._request:88]:GET https://lutris.net/api/runtimes/versions?pci_ids=1002:1636%201043:16CC
DEBUG    2024-12-06 18:57:58,878 [lutriswindow.create_runtime_updater_cb:1358]:Runtime up to date
DEBUG    2024-12-06 18:58:00,329 [application.show_window:396]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x73421d63a480 (LutrisWindow at 0x602f39caf010)>}
DEBUG    2024-12-06 18:58:35,046 [application.show_window:396]:Showing window InstallerWindow1b4db7eb-4057-5ddf-91e0-36dec72071f5
DEBUG    2024-12-06 18:58:35,047 [application.on_app_window_destroyed:421]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x73421d63a480 (LutrisWindow at 0x602f39caf010)>}
DEBUG    2024-12-06 18:58:36,232 [xrandr._get_vidmodes:18]:Retrieving 30 video modes from XrandR
DEBUG    2024-12-06 18:58:41,349 [wine.get_installer_runner_version:844]:Default wine version is wine-ge-8-26
DEBUG    2024-12-06 18:58:41,388 [installerwindow.on_files_prepared:619]:Game files prepared.
DEBUG    2024-12-06 18:58:41,392 [installerwindow.present_installer_files_page:634]:Presenting installer files page
DEBUG    2024-12-06 18:58:50,910 [files_box.on_file_available:108]:setupfile is available
INFO     2024-12-06 18:58:50,910 [files_box.on_file_available:114]:All files available
INFO     2024-12-06 18:58:50,910 [installerwindow.on_files_available:664]:All files are available, continuing install
INFO     2024-12-06 18:58:50,920 [installerwindow.launch_installer_commands:672]:Launching installer commands
DEBUG    2024-12-06 18:58:50,921 [interpreter._iter_commands:315]:Installer command: {'task': {'name': 'wineexec', 'executable': 'setupfile', 'arch': 'win64'}}
lutris-wrapper: /home/edwin/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
Started initial process 21171 from /home/edwin/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/edwin/Downloads/Liars.Bar.v0.884.rar
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
DEBUG    2024-12-06 18:58:52,452 [monitored_command.on_stop:228]:Process 21152 has terminated with code 256
DEBUG    2024-12-06 18:58:53,100 [commands._monitor_task:445]:Return code: 256
ERROR    2024-12-06 18:58:53,101 [errors.__init__:19]:Command exited with code 256
ERROR    2024-12-06 18:58:53,101 [exception_backstops.error_wrapper:81]:Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
```

### System Information

```shell
Vulkan support: NO
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.12.1-zen1-1-zen
Lutris Version: 0.5.18
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 4800H with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 7.2 GB
Swap: 3.6 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.59, 6.12.1-zen1-1-zen)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3.1-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.3.1-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.3.1-arch1.1
Vulkan: Not Supported
```

### Media (optional)

![2024-12-06_19-07 copy](https://github.com/user-attachments/assets/8f6798ed-69d9-4397-a16a-36d37ee13184)

**Comment by danieljohnson2** [comment]
It appears to me that you are trying to install a .rar file as if it were a setup program; that won't work. Perhaps if you decompress the rar file, there's a setup program inside. Look for an "exe" file- one that ends with ``.exe``.
