### ISSUE TITLE
Lutris can not use ScummVM flatpak as runner

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#5776]
### Bug description

Lutris can not use ScummVM flatpak as runner

### How to Reproduce

I installed ScummVM Flatpak, ask Lutris to use it: set scummvm custom executable as "org.scummvm.ScummVM" 
Try to launch a ScummVM game, you obtain a Lutris message error

### Expected behavior

Lutris can fully use ScummVM Flatpak 

### Log output

```shell
The executable 'scummvm/bin/scummvm' could not be found.

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/runners/scummvm.py", line 545, in play
    extra_libs = self.get_extra_libs()
                 ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/runners/scummvm.py", line 487, in get_extra_libs
    if self.get_executable().startswith(base_runner_path):
       ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/runners/runner.py", line 195, in get_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % self.runner_executable)

lutris.exceptions.MissingExecutableError: The executable 'scummvm/bin/scummvm' could not be found.

Lutris log:
[INFO:2024-12-07 19:46:27,168:application]: Starting Lutris 0.5.18
[INFO:2024-12-07 19:46:27,258:startup]: "card1" is AMD Radeon RX 6600M (1002:73ff 1002:0123 amdgpu) Driver 24.2.8
[INFO:2024-12-07 19:46:27,343:startup]: "card0" is AMD Radeon Graphics (1002:1638 1002:0123 amdgpu) Driver 24.2.8
[DEBUG:2024-12-07 19:46:27,503:xrandr]: Retrieving resolution list
[DEBUG:2024-12-07 19:46:27,515:xrandr]: Retrieving 70 video modes from XrandR
[DEBUG:2024-12-07 19:46:27,579:path_cache]: Checking for missing games
[WARNING:2024-12-07 19:46:27,607:base]: Tried to get auth status while login in progress
[DEBUG:2024-12-07 19:46:27,621:api]: Modified at sam. 07 déc. 2024 18:18:05, will update after dim. 08 déc. 2024 00:18:05
[DEBUG:2024-12-07 19:46:27,621:lutriswindow]: Runtime up to date
[WARNING:2024-12-07 19:46:27,623:lutriswindow]: Path cache out of date? (3 IDs missing)
[DEBUG:2024-12-07 19:46:28,584:http]: POST https://lutris.net/api/users/library?since=1733596485
[INFO:2024-12-07 19:46:28,811:library_sync]: Create call-of-cthulhu-shadow-of-the-comet
[DEBUG:2024-12-07 19:46:30,757:grid]: Item activated: 511
[ERROR:2024-12-07 19:46:30,774:exception_backstops]: Indiana Jones and the Fate of Atlantis (scummvm) has encountered an error: The executable 'scummvm/bin/scummvm' could not be found.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/scummvm.py", line 545, in play
    extra_libs = self.get_extra_libs()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/scummvm.py", line 487, in get_extra_libs
    if self.get_executable().startswith(base_runner_path):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/runner.py", line 195, in get_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % self.runner_executable)
lutris.exceptions.MissingExecutableError: The executable 'scummvm/bin/scummvm' could not be found.
[DEBUG:2024-12-07 19:46:30,774:game]: Indiana Jones and the Fate of Atlantis (scummvm) has run for 0 seconds
[WARNING:2024-12-07 19:46:30,774:game]: The game has run for a very short time, did it crash?
[DEBUG:2024-12-07 19:46:30,775:game]: Playtime: 1 minute
[DEBUG:2024-12-07 19:46:30,775:application]: Removing 511 from running IDs
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Manjaro Linux 24.2.0 Yonada
Arch: x86_64
Kernel: 6.6.63-1-MANJARO
Lutris Version: 0.5.18
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900HX with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 30.8 GB
Swap: 16.2 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6600M (radeonsi, navi23, LLVM 18.1.8, DRM 3.54, 6.6.63-1-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.8-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.8-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.8-arch1.1
Vulkan Version: 1.3.295
Vulkan Drivers: AMD Radeon Graphics (RADV RENOIR) (1.3.289), AMD Radeon RX 6600M (RADV NAVI23) (1.3.289)
```

**Comment by danieljohnson2** [comment]
I see the issue; it's trying to find the libraries that come with *our* ScummVM runner, but since it's a flatpak it does not have that directory at all.

I'll change it so when this happens it does not try to load any libraries- Flatpak will handle it. Works for me!

**Comment by legluondunet** [comment]
just tested, it's fixed, thanks.

**Comment by legluondunet** [comment]
This issue is still present in Lutris 0.5.18:
```

The executable 'scummvm/bin/scummvm' could not be found.

Traceback (most recent call last):

  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)

  File "/usr/lib/python3.13/site-packages/lutris/gui/widgets/sidebar.py", line 244, in on_run_runner
    runner.run(self.get_toplevel())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 414, in run
    command_data = self.get_run_data()

  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 519, in get_run_data
    lib_paths = filter(None, self.get_extra_libs() + [env.get("LD_LIBRARY_PATH")])
                             ~~~~~~~~~~~~~~~~~~~^^

  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 487, in get_extra_libs
    if self.get_executable().startswith(base_runner_path):
       ~~~~~~~~~~~~~~~~~~~^^

  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 195, in get_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % self.runner_executable)

lutris.exceptions.MissingExecutableError: The executable 'scummvm/bin/scummvm' could not be found.

Lutris log:
[INFO:2025-02-13 08:50:27,388:application]: Starting Lutris 0.5.18
[INFO:2025-02-13 08:50:27,424:startup]: "card1" is AMD Radeon RX 6600M (1002:73ff 1002:0123 amdgpu) Driver 24.3.4
[INFO:2025-02-13 08:50:27,457:startup]: "card0" is AMD Radeon Graphics (1002:1638 1002:0123 amdgpu) Driver 24.3.4
[DEBUG:2025-02-13 08:50:27,613:xrandr]: Retrieving resolution list
[DEBUG:2025-02-13 08:50:27,625:xrandr]: Retrieving 70 video modes from XrandR
[WARNING:2025-02-13 08:50:27,693:base]: Tried to get auth status while login in progress
[DEBUG:2025-02-13 08:50:27,694:path_cache]: Checking for missing games
[WARNING:2025-02-13 08:50:27,720:base]: Tried to get auth status while login in progress
[DEBUG:2025-02-13 08:50:27,732:api]: Modified at jeu. 13 févr. 2025 08:48:55, will update after jeu. 13 févr. 2025 14:48:55
[DEBUG:2025-02-13 08:50:27,735:lutriswindow]: Runtime up to date
[WARNING:2025-02-13 08:50:27,736:lutriswindow]: Path cache out of date? (7 IDs missing)
[DEBUG:2025-02-13 08:50:28,700:http]: POST https://lutris.net/api/users/library?since=1739432936
[DEBUG:2025-02-13 08:50:46,182:base]: Deleting games from service-games for scummvm
[DEBUG:2025-02-13 08:50:46,183:sidebar]: Service scummvm games loading
[DEBUG:2025-02-13 08:50:46,224:base]: Loading icons...
[DEBUG:2025-02-13 08:50:46,225:base]: 'ScummVM' games reloaded
[DEBUG:2025-02-13 08:50:46,225:base]: Reload callback
[DEBUG:2025-02-13 08:50:46,225:sidebar]: Service scummvm games loaded
[DEBUG:2025-02-13 08:50:51,005:grid]: Item activated: lba-win-fr
[DEBUG:2025-02-13 08:50:51,005:lutriswindow]: Looking up scummvm game lba-win-fr
[ERROR:2025-02-13 08:50:51,016:exception_backstops]: Little Big Adventure (GOG.com Classic Version/Windows/French) (scummvm) has encountered an error: The executable 'scummvm/bin/scummvm' could not be found.
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
  File "/usr/lib/python3.13/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 545, in play
    extra_libs = self.get_extra_libs()
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 487, in get_extra_libs
    if self.get_executable().startswith(base_runner_path):
       ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 195, in get_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % self.runner_executable)
lutris.exceptions.MissingExecutableError: The executable 'scummvm/bin/scummvm' could not be found.
[DEBUG:2025-02-13 08:50:51,017:game]: Little Big Adventure (GOG.com Classic Version/Windows/French) (scummvm) has run for 0 seconds
[WARNING:2025-02-13 08:50:51,017:game]: The game has run for a very short time, did it crash?
[DEBUG:2025-02-13 08:50:51,017:game]: Playtime: 12 minutes
[DEBUG:2025-02-13 08:50:51,018:application]: Removing 707 from running IDs
[ERROR:2025-02-13 08:51:08,345:exception_backstops]: Error handling signal 'clicked': The executable 'scummvm/bin/scummvm' could not be found.
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/gui/widgets/sidebar.py", line 244, in on_run_runner
    runner.run(self.get_toplevel())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 414, in run
    command_data = self.get_run_data()
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 519, in get_run_data
    lib_paths = filter(None, self.get_extra_libs() + [env.get("LD_LIBRARY_PATH")])
                             ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 487, in get_extra_libs
    if self.get_executable().startswith(base_runner_path):
       ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 195, in get_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % self.runner_executable)
lutris.exceptions.MissingExecutableError: The executable 'scummvm/bin/scummvm' could not be found.
[DEBUG:2025-02-13 08:51:12,763:application]: Showing window RunnerConfigDialogscummvm
[DEBUG:2025-02-13 08:51:27,499:xrandr]: Retrieving display outputs
[DEBUG:2025-02-13 08:51:27,511:xrandr]: Retrieving 70 video modes from XrandR
[DEBUG:2025-02-13 08:51:27,513:xrandr]: Retrieving display outputs
[DEBUG:2025-02-13 08:51:27,525:xrandr]: Retrieving 70 video modes from XrandR
[DEBUG:2025-02-13 08:51:27,526:xrandr]: Retrieving resolution list
[DEBUG:2025-02-13 08:51:27,542:xrandr]: Retrieving 70 video modes from XrandR
[DEBUG:2025-02-13 08:51:27,546:xrandr]: Retrieving resolution list
[DEBUG:2025-02-13 08:51:27,558:xrandr]: Retrieving 70 video modes from XrandR
[DEBUG:2025-02-13 08:51:27,560:xrandr]: Retrieving resolution list
[DEBUG:2025-02-13 08:51:27,575:xrandr]: Retrieving 70 video modes from XrandR
[DEBUG:2025-02-13 08:51:33,073:application]: Removed window RunnerConfigDialogscummvm
[DEBUG:2025-02-13 08:51:54,070:grid]: Item activated: 511
[ERROR:2025-02-13 08:51:54,086:exception_backstops]: Indiana Jones and the Fate of Atlantis (scummvm) has encountered an error: The executable 'scummvm/bin/scummvm' could not be found.
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
  File "/usr/lib/python3.13/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 545, in play
    extra_libs = self.get_extra_libs()
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 487, in get_extra_libs
    if self.get_executable().startswith(base_runner_path):
       ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 195, in get_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % self.runner_executable)
lutris.exceptions.MissingExecutableError: The executable 'scummvm/bin/scummvm' could not be found.
[DEBUG:2025-02-13 08:51:54,087:game]: Indiana Jones and the Fate of Atlantis (scummvm) has run for 0 seconds
[WARNING:2025-02-13 08:51:54,087:game]: The game has run for a very short time, did it crash?
[DEBUG:2025-02-13 08:51:54,087:game]: Playtime: 1 minute
[DEBUG:2025-02-13 08:51:54,087:application]: Removing 511 from running IDs
[DEBUG:2025-02-13 08:52:08,664:application]: Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7371adba4bc0 (LutrisWindow at 0x6419f6165c10)>}
[DEBUG:2025-02-13 08:52:25,889:application]: Showing window RunnerConfigDialogscummvm
[DEBUG:2025-02-13 08:52:33,057:application]: Removed window RunnerConfigDialogscummvm
[DEBUG:2025-02-13 08:52:33,864:application]: Removed window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7371adba4bc0 (LutrisWindow at 0x6419f6165c10)>}
[ERROR:2025-02-13 09:01:03,606:exception_backstops]: Error handling signal 'clicked': The executable 'scummvm/bin/scummvm' could not be found.
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/gui/widgets/sidebar.py", line 244, in on_run_runner
    runner.run(self.get_toplevel())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 414, in run
    command_data = self.get_run_data()
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 519, in get_run_data
    lib_paths = filter(None, self.get_extra_libs() + [env.get("LD_LIBRARY_PATH")])
                             ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/scummvm.py", line 487, in get_extra_libs
    if self.get_executable().startswith(base_runner_path):
       ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/lutris/runners/runner.py", line 195, in get_executable
    raise MissingExecutableError(_("The executable '%s' could not be found.") % self.runner_executable)
lutris.exceptions.MissingExecutableError: The executable 'scummvm/bin/scummvm' could not be found.
```

**Comment by legluondunet** [comment]
0.5.18 --> issue still present
Github version --> fixed
