### ISSUE TITLE
Received 'utf-8' codec can't decode byte 0xff in position 12: invalid start byte error on multiple games.

### ISSUE THREAD

**Issue by apennismightier** [lutris/lutris#5779]
### Bug description

I am trying to load up an FG Repack of Shadow of War

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

Install it normally

### Log output

```shell
'utf-8' codec can't decode byte 0xff in position 12: invalid start byte

Traceback (most recent call last):

  File "/app/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.12/site-packages/lutris/gui/addgameswindow.py", line 449, in on_continue_install_from_script_clicked
    installers = get_installers(installer_file=path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.12/site-packages/lutris/installer/__init__.py", line 37, in get_installers
    return [normalize_installer(i) for i in read_script(installer_file)]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.12/site-packages/lutris/installer/__init__.py", line 26, in read_script
    script = yaml.safe_load(local_file.read())
                            ^^^^^^^^^^^^^^^^^

  File "<frozen codecs>", line 322, in decode

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 12: invalid start byte

Lutris log:
[INFO:2024-12-08 18:16:57,660:application]: Starting Lutris 0.5.18
[INFO:2024-12-08 18:16:57,712:startup]: "card0" is AMD Custom GPU 0932 (1002:1435 1002:0123 amdgpu) Driver 24.2.7
[ERROR:2024-12-08 18:17:10,952:exception_backstops]: Error handling signal 'clicked': 'utf-8' codec can't decode byte 0xff in position 12: invalid start byte
Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/gui/addgameswindow.py", line 449, in on_continue_install_from_script_clicked
    installers = get_installers(installer_file=path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/installer/__init__.py", line 37, in get_installers
    return [normalize_installer(i) for i in read_script(installer_file)]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/installer/__init__.py", line 26, in read_script
    script = yaml.safe_load(local_file.read())
                            ^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 12: invalid start byte
[ERROR:2024-12-08 18:17:18,382:exception_backstops]: Error handling signal 'clicked': 'utf-8' codec can't decode byte 0xff in position 12: invalid start byte
Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/gui/addgameswindow.py", line 449, in on_continue_install_from_script_clicked
    installers = get_installers(installer_file=path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/installer/__init__.py", line 37, in get_installers
    return [normalize_installer(i) for i in read_script(installer_file)]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/installer/__init__.py", line 26, in read_script
    script = yaml.safe_load(local_file.read())
                            ^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 12: invalid start byte
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 47 Flatpak runtime
Arch: x86_64
Kernel: 6.5.0-valve22-1-neptune-65-g9a338ed8a75e
Lutris Version: 0.5.18
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Custom APU 0932
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 14.5 GB
Swap: 8.2 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Custom GPU 0932 (radeonsi, vangogh, LLVM 18.1.8, DRM 3.57, 6.5.0-valve22-1-neptune-65-g9a338ed8a75e)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.7 (git-3900828265)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.7 (git-3900828265)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.7 (git-3900828265)
Vulkan Version: 1.3.290
Vulkan Drivers: AMD Custom GPU 0932 (RADV VANGOGH) (1.3.289)
```

**Comment by danieljohnson2** [comment]
It looks like the .yaml file you are trying to use is no good. Where did you get it from?

**Comment by TriMoon** [comment]
@apennismightier make sure your yaml file is utf-8 encoded instead of utf-16 :wink:
