### ISSUE TITLE
Can`t run Farlight84 using Wine.

### ISSUE THREAD

**Issue by FR34DB3R** [lutris/lutris#5783]
### Bug description

Here is the error:

```This game has no executable set. The install process didn't finish properly.

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1223, in play
    raise MissingGameExecutableError(filename=game_exe)

lutris.exceptions.MissingGameExecutableError: This game has no executable set. The install process didn't finish properly.

Lutris log:
[INFO:2024-12-10 18:18:53,740:application]: Starting Lutris 0.5.18
[ERROR:2024-12-10 18:18:53,784:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-12-10 18:18:53,811:startup]: "card1" is Intel Corporation CometLake-U GT2 [UHD Graphics] (8086:9b41 17aa:5078 i915) Driver 24.2.7
[ERROR:2024-12-10 18:18:53,812:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
[WARNING:2024-12-10 18:18:53,816:startup]: Vulkan is not available or your system isn't Vulkan capable
[INFO:2024-12-10 18:19:01,045:runner]: Runtime disabled by system configuration
[WARNING:2024-12-10 18:19:01,046:runner]: Accessing game config while runner wasn't given one.
[WARNING:2024-12-10 18:19:01,046:runner]: Accessing game config while runner wasn't given one.
[INFO:2024-12-10 18:23:30,285:runner]: Runtime disabled by system configuration
[INFO:2024-12-10 18:23:30,289:runner_interpreter]: Do not enable Mangodhud for Steam games in Lutris. Edit the launch options in Steam and set them to mangohud %%command%%
[INFO:2024-12-10 18:23:30,289:runner]: Runtime disabled by system configuration
[WARNING:2024-12-10 18:23:32,408:game]: Game still running (state: running)
[INFO:2024-12-10 18:23:32,408:game]: Stopping Farlight 84 (steam)
[WARNING:2024-12-10 18:23:32,408:game]: The game has run for a very short time, did it crash?
[WARNING:2024-12-10 18:23:32,443:game]: No path found in LutrisConfig(level=game, game_config_id=steam-1928420-1733844200, runner=steam)
[WARNING:2024-12-10 18:23:32,443:path_cache]: No path for Farlight 84 (steam)
[INFO:2024-12-10 18:24:01,693:game_common]: Creating new configuration with runner wine
[ERROR:2024-12-10 18:24:09,613:wine]: The game doesn't have an executable
[WARNING:2024-12-10 18:24:09,652:game]: No path found in LutrisConfig(level=game, game_config_id=farlight-84-1733844249, runner=wine)
[WARNING:2024-12-10 18:24:09,652:path_cache]: No path for Farlight 84 (wine)
[ERROR:2024-12-10 18:24:11,578:wine]: The game doesn't have an executable
[ERROR:2024-12-10 18:24:11,582:exception_backstops]: Farlight 84 (wine) has encountered an error: This game has no executable set. The install process didn't finish properly.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1223, in play
    raise MissingGameExecutableError(filename=game_exe)
lutris.exceptions.MissingGameExecutableError: This game has no executable set. The install process didn't finish properly.
[WARNING:2024-12-10 18:24:11,585:game]: The game has run for a very short time, did it crash?
[ERROR:2024-12-10 18:24:14,300:wine]: The game doesn't have an executable
[ERROR:2024-12-10 18:24:14,304:exception_backstops]: Farlight 84 (wine) has encountered an error: This game has no executable set. The install process didn't finish properly.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1223, in play
    raise MissingGameExecutableError(filename=game_exe)
lutris.exceptions.MissingGameExecutableError: This game has no executable set. The install process didn't finish properly.
[WARNING:2024-12-10 18:24:14,304:game]: The game has run for a very short time, did it crash?```

### How to Reproduce

.

### Expected behavior

.

### Log output

```shell
This game has no executable set. The install process didn't finish properly.

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1223, in play
    raise MissingGameExecutableError(filename=game_exe)

lutris.exceptions.MissingGameExecutableError: This game has no executable set. The install process didn't finish properly.

Lutris log:
[INFO:2024-12-10 18:18:53,740:application]: Starting Lutris 0.5.18
[ERROR:2024-12-10 18:18:53,784:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-12-10 18:18:53,811:startup]: "card1" is Intel Corporation CometLake-U GT2 [UHD Graphics] (8086:9b41 17aa:5078 i915) Driver 24.2.7
[ERROR:2024-12-10 18:18:53,812:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
[WARNING:2024-12-10 18:18:53,816:startup]: Vulkan is not available or your system isn't Vulkan capable
[INFO:2024-12-10 18:19:01,045:runner]: Runtime disabled by system configuration
[WARNING:2024-12-10 18:19:01,046:runner]: Accessing game config while runner wasn't given one.
[WARNING:2024-12-10 18:19:01,046:runner]: Accessing game config while runner wasn't given one.
[INFO:2024-12-10 18:23:30,285:runner]: Runtime disabled by system configuration
[INFO:2024-12-10 18:23:30,289:runner_interpreter]: Do not enable Mangodhud for Steam games in Lutris. Edit the launch options in Steam and set them to mangohud %%command%%
[INFO:2024-12-10 18:23:30,289:runner]: Runtime disabled by system configuration
[WARNING:2024-12-10 18:23:32,408:game]: Game still running (state: running)
[INFO:2024-12-10 18:23:32,408:game]: Stopping Farlight 84 (steam)
[WARNING:2024-12-10 18:23:32,408:game]: The game has run for a very short time, did it crash?
[WARNING:2024-12-10 18:23:32,443:game]: No path found in LutrisConfig(level=game, game_config_id=steam-1928420-1733844200, runner=steam)
[WARNING:2024-12-10 18:23:32,443:path_cache]: No path for Farlight 84 (steam)
[INFO:2024-12-10 18:24:01,693:game_common]: Creating new configuration with runner wine
[ERROR:2024-12-10 18:24:09,613:wine]: The game doesn't have an executable
[WARNING:2024-12-10 18:24:09,652:game]: No path found in LutrisConfig(level=game, game_config_id=farlight-84-1733844249, runner=wine)
[WARNING:2024-12-10 18:24:09,652:path_cache]: No path for Farlight 84 (wine)
[ERROR:2024-12-10 18:24:11,578:wine]: The game doesn't have an executable
[ERROR:2024-12-10 18:24:11,582:exception_backstops]: Farlight 84 (wine) has encountered an error: This game has no executable set. The install process didn't finish properly.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1223, in play
    raise MissingGameExecutableError(filename=game_exe)
lutris.exceptions.MissingGameExecutableError: This game has no executable set. The install process didn't finish properly.
[WARNING:2024-12-10 18:24:11,585:game]: The game has run for a very short time, did it crash?
[ERROR:2024-12-10 18:24:14,300:wine]: The game doesn't have an executable
[ERROR:2024-12-10 18:24:14,304:exception_backstops]: Farlight 84 (wine) has encountered an error: This game has no executable set. The install process didn't finish properly.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1223, in play
    raise MissingGameExecutableError(filename=game_exe)
lutris.exceptions.MissingGameExecutableError: This game has no executable set. The install process didn't finish properly.
[WARNING:2024-12-10 18:24:14,304:game]: The game has run for a very short time, did it crash?
```

### System Information

```shell
CPU: Intel Core I5-10000
GPU: Intel UHD 620
RAM: 8GB
SSD: 268GB
```

**Comment by danieljohnson2** [comment]
It seems to say ``This game has no executable set. The install process didn't finish properly.``

It's possible that all you need to do is assign that executable in the game configuration, if you can find the right .exe file.

**Comment by legluondunet** [comment]
```
[ERROR:2024-12-10 18:18:53,812:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
[WARNING:2024-12-10 18:18:53,816:startup]: Vulkan is not available or your system isn't Vulkan capable
```
You need to install wine dependencies, follow this guide:
https://github.com/lutris/docs/blob/master/WineDependencies.md

To obtain support for game install, do not use Github but our Discord or Lutris forum.
