### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#5784]
### Bug description

When you start a game using the Hatari Runner this error pops up, haven't seen the same problem with the other runners we tried

### How to Reproduce

1. Download the Runner
2. Add a game IE: https://retroracing.itch.io/faster-atari-ste (the one we tried)
3. Start game (We used the 2.05 US STE bios)
4. Lutris crash

### Expected behavior

not to crash

### Log output

```shell
expected str, bytes or os.PathLike object, not NoneType

Traceback (most recent call last):

  File "/home/te_lanus/src/lutris/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)

  File "/home/te_lanus/src/lutris/lutris/game.py", line 733, in configure_game
    self.start_game()

  File "/home/te_lanus/src/lutris/lutris/game.py", line 786, in start_game
    self.game_thread.start()

  File "/home/te_lanus/src/lutris/lutris/monitored_command.py", line 161, in start
    self.game_process = self.execute_process(wrapper_command, env)

  File "/home/te_lanus/src/lutris/lutris/monitored_command.py", line 262, in execute_process
    return subprocess.Popen(  # pylint: disable=consider-using-with

  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(

TypeError: expected str, bytes or os.PathLike object, not NoneType

Lutris log:
[INFO:2024-12-11 07:27:24,206:application]: Starting Lutris 0.5.18
[DEBUG:2024-12-11 07:27:24,308:system]: Executing lspci
[INFO:2024-12-11 07:27:24,426:startup]: "card0" is NVIDIA Corporation GF108 [GeForce GT 630] (10de:0f00 1458:3543 nvidia) Driver 390.157
[WARNING:2024-12-11 07:27:24,870:startup]: Vulkan reports an API version of 1.2.131. 1.3.0 is required for the latest DXVK.
[DEBUG:2024-12-11 07:27:32,406:xrandr]: Retrieving resolution list
[DEBUG:2024-12-11 07:27:32,467:xrandr]: Retrieving 9 video modes from XrandR
[DEBUG:2024-12-11 07:27:33,041:path_cache]: Checking for missing games
[DEBUG:2024-12-11 07:27:33,603:api]: Modified at Tue 10 Dec 2024 22:52:10, will update after Wed 11 Dec 2024 04:52:10
[DEBUG:2024-12-11 07:27:33,604:http]: GET https://lutris.net/api/runtimes/versions?pci_ids=10DE:0F00%201458:3543
[ERROR:2024-12-11 07:27:34,686:style_manager]: Error reading color-scheme: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
Traceback (most recent call last):
  File "/home/te_lanus/src/lutris/lutris/style_manager.py", line 74, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
[DEBUG:2024-12-11 07:27:35,276:runtime]: Runtime icons locally updated on Sat 19 Feb 2022 10:18:30, remote created on Mon 26 Jun 2023 04:34:45)
[DEBUG:2024-12-11 07:27:35,282:http]: GET https://lutris.net/api/runtimes/icons
[DEBUG:2024-12-11 07:27:37,080:grid]: Item activated: 5744
[DEBUG:2024-12-11 07:27:37,168:xrandr]: Retrieving display outputs
[DEBUG:2024-12-11 07:27:37,201:xrandr]: Retrieving 9 video modes from XrandR
[ERROR:2024-12-11 07:27:37,211:exception_backstops]: Faster (hatari) has encountered an error: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/te_lanus/src/lutris/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
  File "/home/te_lanus/src/lutris/lutris/game.py", line 733, in configure_game
    self.start_game()
  File "/home/te_lanus/src/lutris/lutris/game.py", line 786, in start_game
    self.game_thread.start()
  File "/home/te_lanus/src/lutris/lutris/monitored_command.py", line 161, in start
    self.game_process = self.execute_process(wrapper_command, env)
  File "/home/te_lanus/src/lutris/lutris/monitored_command.py", line 262, in execute_process
    return subprocess.Popen(  # pylint: disable=consider-using-with
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
[DEBUG:2024-12-11 07:27:37,261:game]: Faster (hatari) has run for 0 seconds
[WARNING:2024-12-11 07:27:37,261:game]: The game has run for a very short time, did it crash?
[DEBUG:2024-12-11 07:27:37,262:game]: Playtime: 3 minutes
[DEBUG:2024-12-11 07:27:37,263:application]: Removing 5744 from running IDs
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 20.04 focal
Arch: x86_64
Kernel: 5.15.0-125-generic
Lutris Version: 0.5.18
Desktop: KDE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
Physical cores: 2
Logical cores: 4
[Memory]
RAM: 3.8 GB
Swap: 18.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: GeForce GT 630/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 390.157
OpenGL Core: 4.6.0 NVIDIA 390.157
OpenGL ES: OpenGL ES 3.2 NVIDIA 390.157
Vulkan Version: 1.2.131
Vulkan Drivers:
```

**Comment by danieljohnson2** [comment]
I am not getting exactly this error, but I am getting a NoneType error when Disk B is not selected. I've committed a fix for that.

Please try selecting Disk B for the game, even if it's an irrelevant disk. Does that prevent the crash?

**Comment by telanus** [comment]
> Please try selecting Disk B for the game, even if it's an irrelevant disk. Does that prevent the crash?

Yes that fixes the crash :D

**Comment by telanus** [comment]
going to close as this has been fixed by https://github.com/lutris/lutris/commit/8f384d92e73864904a0a0aea70d6cbb70d08604f
