### ISSUE TITLE
Cant Install Epic Games Store, when its installin dependencies stops and says "Error Code 256" Wine: not found

### ISSUE THREAD

**Issue by asferoner** [lutris/lutris#5790]
El comando ha finalizado con código 256

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: El comando ha finalizado con código 256

Lutris log:
[INFO:2024-12-12 13:21:48,160:application]: Starting Lutris 0.5.18
[INFO:2024-12-12 13:21:48,778:__init__]: Running migration: mess_to_mame
[INFO:2024-12-12 13:21:48,780:__init__]: Running migration: migrate_hidden_ids
[INFO:2024-12-12 13:21:48,781:__init__]: Running migration: migrate_steam_appids
[INFO:2024-12-12 13:21:48,782:__init__]: Running migration: migrate_banners
[INFO:2024-12-12 13:21:48,783:__init__]: Running migration: retrieve_discord_appids
[INFO:2024-12-12 13:21:48,784:retrieve_discord_appids]: Updating Games Discord APP ID's
[INFO:2024-12-12 13:21:48,784:__init__]: Running migration: migrate_sortname
[INFO:2024-12-12 13:21:48,785:migrate_sortname]: Adding blank sortname field to database
[INFO:2024-12-12 13:21:48,785:__init__]: Running migration: migrate_hidden_category
[INFO:2024-12-12 13:21:48,786:migrate_hidden_category]: Moving hidden games to the '.hidden' category
[ERROR:2024-12-12 13:21:49,091:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-12-12 13:21:49,149:startup]: "card0" is Advanced Micro Devices, Inc. [AMD/ATI] Juniper XT [Radeon HD 5770] (1002:68b8 106b:00cf radeon) Driver 24.0.9
[ERROR:2024-12-12 13:21:49,150:startup]: i386 libGL.so.1 missing (needed by opengl)
[ERROR:2024-12-12 13:21:49,150:startup]: i386 libvulkan.so.1 missing (needed by vulkan)
[ERROR:2024-12-12 13:21:49,150:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
[WARNING:2024-12-12 13:21:51,273:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/umu
[WARNING:2024-12-12 13:21:51,587:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/winetricks
[WARNING:2024-12-12 13:22:59,579:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/battleye_runtime
[WARNING:2024-12-12 13:22:59,923:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/umu-games
[WARNING:2024-12-12 13:23:00,617:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/eac_runtime
[WARNING:2024-12-12 13:25:03,483:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/innoextract-1.9-linux
[WARNING:2024-12-12 13:25:05,873:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/p7zip
[WARNING:2024-12-12 13:25:06,604:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/gamecontrollerdb
[WARNING:2024-12-12 13:25:07,806:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/network-tools
[WARNING:2024-12-12 13:27:08,485:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/Ubuntu-18.04-i686
[WARNING:2024-12-12 13:29:03,373:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/Ubuntu-18.04-x86_64
[WARNING:2024-12-12 13:29:04,099:system]: Non existent path: /home/desorden/.local/share/lutris/runtime/dxvk-cache-tool
[INFO:2024-12-12 13:48:10,301:file_box]: Download completed
[INFO:2024-12-12 13:48:12,311:file_box]: Download completed
[INFO:2024-12-12 13:48:12,311:files_box]: All files available
[INFO:2024-12-12 13:48:12,311:installerwindow]: All files are available, continuing install
[INFO:2024-12-12 13:48:12,311:installerwindow]: Launching installer commands
[INFO:2024-12-12 13:48:12,516:wine]: Creating a win64 prefix in /home/desorden/Games/epic-games-store
[INFO:2024-12-12 13:48:12,516:wine]: Winepath: /home/desorden/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[WARNING:2024-12-12 13:48:43,028:wine]: Wine prefix creation is taking longer than expected...
[ERROR:2024-12-12 13:56:32,614:wine]: No user.reg found after prefix creation. Prefix might not be valid
[INFO:2024-12-12 13:56:32,985:wine]: Creating a win64 prefix in /home/desorden/Games/epic-games-store
[INFO:2024-12-12 13:56:32,985:wine]: Winepath: /home/desorden/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[WARNING:2024-12-12 13:57:03,497:wine]: Wine prefix creation is taking longer than expected...
[ERROR:2024-12-12 14:04:53,098:wine]: No user.reg found after prefix creation. Prefix might not be valid
[WARNING:2024-12-12 14:04:53,150:wine]: No valid prefix detected in /home/desorden/Games/epic-games-store, creating one...
[INFO:2024-12-12 14:04:53,150:wine]: Creating a win64 prefix in /home/desorden/Games/epic-games-store
[INFO:2024-12-12 14:04:53,150:wine]: Winepath: /home/desorden/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[WARNING:2024-12-12 14:05:23,661:wine]: Wine prefix creation is taking longer than expected...
[ERROR:2024-12-12 14:13:13,254:wine]: No user.reg found after prefix creation. Prefix might not be valid
[ERROR:2024-12-12 14:13:13,255:registry]: No registry file at /home/desorden/Games/epic-games-store/user.reg
[WARNING:2024-12-12 14:13:13,255:prefix]: Couldn't load shell folder name for Desktop
[ERROR:2024-12-12 14:13:13,255:registry]: No registry file at /home/desorden/Games/epic-games-store/user.reg
[WARNING:2024-12-12 14:13:13,256:prefix]: Couldn't load shell folder name for Personal
[ERROR:2024-12-12 14:13:13,256:registry]: No registry file at /home/desorden/Games/epic-games-store/user.reg
[WARNING:2024-12-12 14:13:13,256:prefix]: Couldn't load shell folder name for My Music
[ERROR:2024-12-12 14:13:13,256:registry]: No registry file at /home/desorden/Games/epic-games-store/user.reg
[WARNING:2024-12-12 14:13:13,257:prefix]: Couldn't load shell folder name for My Videos
[ERROR:2024-12-12 14:13:13,257:registry]: No registry file at /home/desorden/Games/epic-games-store/user.reg
[WARNING:2024-12-12 14:13:13,257:prefix]: Couldn't load shell folder name for My Pictures
[ERROR:2024-12-12 14:13:13,257:registry]: No registry file at /home/desorden/Games/epic-games-store/user.reg
[ERROR:2024-12-12 14:13:13,312:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_33.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_33.dll
[ERROR:2024-12-12 14:13:13,312:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_34.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_34.dll
[ERROR:2024-12-12 14:13:13,313:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_35.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_35.dll
[ERROR:2024-12-12 14:13:13,313:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_36.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_36.dll
[ERROR:2024-12-12 14:13:13,313:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_37.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_37.dll
[ERROR:2024-12-12 14:13:13,313:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_38.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_38.dll
[ERROR:2024-12-12 14:13:13,313:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_39.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_39.dll
[ERROR:2024-12-12 14:13:13,314:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_40.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_40.dll
[ERROR:2024-12-12 14:13:13,314:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_41.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_41.dll
[ERROR:2024-12-12 14:13:13,314:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_42.dll
[ERROR:2024-12-12 14:13:13,314:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10_43.dll
[ERROR:2024-12-12 14:13:13,314:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx10.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx10.dll
[ERROR:2024-12-12 14:13:13,315:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx11_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx11_42.dll
[ERROR:2024-12-12 14:13:13,315:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx11_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx11_43.dll
[ERROR:2024-12-12 14:13:13,315:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_24.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_24.dll
[ERROR:2024-12-12 14:13:13,315:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_25.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_25.dll
[ERROR:2024-12-12 14:13:13,315:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_26.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_26.dll
[ERROR:2024-12-12 14:13:13,316:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_27.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_27.dll
[ERROR:2024-12-12 14:13:13,316:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_28.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_28.dll
[ERROR:2024-12-12 14:13:13,316:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_29.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_29.dll
[ERROR:2024-12-12 14:13:13,316:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_30.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_30.dll
[ERROR:2024-12-12 14:13:13,316:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_31.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_31.dll
[ERROR:2024-12-12 14:13:13,317:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_32.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_32.dll
[ERROR:2024-12-12 14:13:13,317:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_33.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_33.dll
[ERROR:2024-12-12 14:13:13,317:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_34.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_34.dll
[ERROR:2024-12-12 14:13:13,317:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_35.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_35.dll
[ERROR:2024-12-12 14:13:13,317:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_36.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_36.dll
[ERROR:2024-12-12 14:13:13,318:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_37.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_37.dll
[ERROR:2024-12-12 14:13:13,318:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_38.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_38.dll
[ERROR:2024-12-12 14:13:13,318:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_39.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_39.dll
[ERROR:2024-12-12 14:13:13,318:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_40.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_40.dll
[ERROR:2024-12-12 14:13:13,318:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_41.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_41.dll
[ERROR:2024-12-12 14:13:13,319:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_42.dll
[ERROR:2024-12-12 14:13:13,319:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dx9_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dx9_43.dll
[ERROR:2024-12-12 14:13:13,319:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_33.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_33.dll
[ERROR:2024-12-12 14:13:13,319:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_34.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_34.dll
[ERROR:2024-12-12 14:13:13,319:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_35.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_35.dll
[ERROR:2024-12-12 14:13:13,320:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_36.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_36.dll
[ERROR:2024-12-12 14:13:13,320:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_37.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_37.dll
[ERROR:2024-12-12 14:13:13,320:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_38.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_38.dll
[ERROR:2024-12-12 14:13:13,320:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_39.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_39.dll
[ERROR:2024-12-12 14:13:13,320:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_40.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_40.dll
[ERROR:2024-12-12 14:13:13,321:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_41.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_41.dll
[ERROR:2024-12-12 14:13:13,321:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_42.dll
[ERROR:2024-12-12 14:13:13,321:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_43.dll
[ERROR:2024-12-12 14:13:13,321:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_46.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_46.dll
[ERROR:2024-12-12 14:13:13,321:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x64/d3dcompiler_47.dll to /home/desorden/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_47.dll
[ERROR:2024-12-12 14:13:13,322:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_33.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_33.dll
[ERROR:2024-12-12 14:13:13,322:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_34.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_34.dll
[ERROR:2024-12-12 14:13:13,322:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_35.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_35.dll
[ERROR:2024-12-12 14:13:13,322:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_36.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_36.dll
[ERROR:2024-12-12 14:13:13,322:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_37.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_37.dll
[ERROR:2024-12-12 14:13:13,322:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_38.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_38.dll
[ERROR:2024-12-12 14:13:13,323:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_39.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_39.dll
[ERROR:2024-12-12 14:13:13,323:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_40.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_40.dll
[ERROR:2024-12-12 14:13:13,323:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_41.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_41.dll
[ERROR:2024-12-12 14:13:13,323:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_42.dll
[ERROR:2024-12-12 14:13:13,323:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_43.dll
[ERROR:2024-12-12 14:13:13,324:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx10.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx10.dll
[ERROR:2024-12-12 14:13:13,324:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx11_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx11_42.dll
[ERROR:2024-12-12 14:13:13,324:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx11_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx11_43.dll
[ERROR:2024-12-12 14:13:13,324:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_24.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_24.dll
[ERROR:2024-12-12 14:13:13,324:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_25.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_25.dll
[ERROR:2024-12-12 14:13:13,325:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_26.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_26.dll
[ERROR:2024-12-12 14:13:13,325:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_27.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_27.dll
[ERROR:2024-12-12 14:13:13,325:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_28.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_28.dll
[ERROR:2024-12-12 14:13:13,325:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_29.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_29.dll
[ERROR:2024-12-12 14:13:13,325:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_30.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_30.dll
[ERROR:2024-12-12 14:13:13,326:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_31.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_31.dll
[ERROR:2024-12-12 14:13:13,326:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_32.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_32.dll
[ERROR:2024-12-12 14:13:13,326:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_33.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_33.dll
[ERROR:2024-12-12 14:13:13,326:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_34.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_34.dll
[ERROR:2024-12-12 14:13:13,326:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_35.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_35.dll
[ERROR:2024-12-12 14:13:13,327:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_36.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_36.dll
[ERROR:2024-12-12 14:13:13,327:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_37.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_37.dll
[ERROR:2024-12-12 14:13:13,327:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_38.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_38.dll
[ERROR:2024-12-12 14:13:13,327:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_39.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_39.dll
[ERROR:2024-12-12 14:13:13,327:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_40.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_40.dll
[ERROR:2024-12-12 14:13:13,328:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_41.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_41.dll
[ERROR:2024-12-12 14:13:13,328:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_42.dll
[ERROR:2024-12-12 14:13:13,328:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dx9_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_43.dll
[ERROR:2024-12-12 14:13:13,328:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_33.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_33.dll
[ERROR:2024-12-12 14:13:13,328:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_34.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_34.dll
[ERROR:2024-12-12 14:13:13,329:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_35.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_35.dll
[ERROR:2024-12-12 14:13:13,329:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_36.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_36.dll
[ERROR:2024-12-12 14:13:13,329:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_37.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_37.dll
[ERROR:2024-12-12 14:13:13,329:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_38.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_38.dll
[ERROR:2024-12-12 14:13:13,329:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_39.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_39.dll
[ERROR:2024-12-12 14:13:13,330:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_40.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_40.dll
[ERROR:2024-12-12 14:13:13,330:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_41.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_41.dll
[ERROR:2024-12-12 14:13:13,330:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_42.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_42.dll
[ERROR:2024-12-12 14:13:13,330:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_43.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_43.dll
[ERROR:2024-12-12 14:13:13,330:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_46.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_46.dll
[ERROR:2024-12-12 14:13:13,331:system]: Failed linking /home/desorden/.local/share/lutris/runtime/d3d_extras/v2/x32/d3dcompiler_47.dll to /home/desorden/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_47.dll
[WARNING:2024-12-12 14:13:13,331:prefix]: Get Registry Key function returned NoneType to variable folder.
[ERROR:2024-12-12 14:13:14,334:errors]: El comando ha finalizado con código 256
[ERROR:2024-12-12 14:13:14,334:exception_backstops]: Error handling timeout function: El comando ha finalizado con código 256
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: El comando ha finalizado con código 256

**Comment by PadTrick** [comment]
same issue for me. but with nearly all installations.
lutris was working fine, updated some packages for my distro (arch) since then i only was able to install epic launcher, all other scripts show this error.
tried elite dangerous installer, war thunder and many other scripts.

**Comment by legluondunet** [comment]
did you install all wine dependencies? follow this guide:
https://github.com/lutris/docs/blob/master/WineDependencies.md

**Comment by PadTrick** [comment]
yes and it was working before. all other stuff works perfect.
seems like some package got updated and some scripts are no longer compatible.

**Comment by PadTrick** [comment]
> ```
> [ERROR:2024-12-12 13:21:49,150:startup]: i386 libGL.so.1 missing (needed by opengl)
> [ERROR:2024-12-12 13:21:49,150:startup]: i386 libvulkan.so.1 missing (needed by vulkan)
> [ERROR:2024-12-12 13:21:49,150:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
> ```
> 
> This errors messages says wine dependencies are not installed, it's not a Lutris issue, you should ask for help on our Discord or Lutris forum.

i havent provided a log yet, my dependencies are fine (followed glorious eggrolls guide).
