### ISSUE TITLE
Error Code 512 while installing Ubisoft Connect

### ISSUE THREAD

**Issue by Huwuzky** [lutris/lutris#5791]
### Bug description

When i try to install Ubisoft Connect, i get error code 512 

Here is the detailed error:
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: Befehl beendet mit dem Code 512

Lutris log:
[INFO:2024-12-13 13:31:12,971:application]: Starting Lutris 0.5.18
[INFO:2024-12-13 13:31:13,135:startup]: "card1" is NVIDIA GeForce GTX 1660 Ti with Max-Q Design (10de:2191 103c:86d6 nvidia) Driver 550.120
[INFO:2024-12-13 13:31:13,214:startup]: "card2" is AMD Radeon Vega 10 Graphics (1002:15d8 103c:86d6 amdgpu) Driver None
[WARNING:2024-12-13 13:31:13,755:base]: Tried to get auth status while login in progress
[WARNING:2024-12-13 13:31:51,869:system]: Non existent path: /home/husky/.local/share/lutris/runners/proton/ge-proton
[INFO:2024-12-13 13:38:56,898:file_box]: Download completed
[INFO:2024-12-13 13:38:56,899:files_box]: All files available
[INFO:2024-12-13 13:38:56,900:installerwindow]: All files are available, continuing install
[INFO:2024-12-13 13:38:56,902:installerwindow]: Launching installer commands
[INFO:2024-12-13 13:38:57,006:wine]: Creating a win64 prefix in /home/husky/Games/ubisoft-connect
[INFO:2024-12-13 13:38:57,006:wine]: Winepath: /home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[INFO:2024-12-13 13:38:58,594:wine]: win64 Prefix created in /home/husky/Games/ubisoft-connect
[ERROR:2024-12-13 13:39:16,315:errors]: Befehl beendet mit dem Code 512
[ERROR:2024-12-13 13:39:16,316:exception_backstops]: Error handling timeout function: Befehl beendet mit dem Code 512
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Befehl beendet mit dem Code 512

### How to Reproduce

1. Click on 'Ubisoft connect'
2. Click on 'Install'
3. Click on 'Continue'
4. Click on 'Install' again

### Expected behavior

Installing Ubisoft Connect

### Log output

```shell
2024-12-13 14:05:55,883: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-12-13 14:05:56,433 [application.do_command_line:480]:Starting Lutris 0.5.18
INFO     2024-12-13 14:05:56,705 [startup.run_all_checks:120]:"card1" is NVIDIA GeForce GTX 1660 Ti with Max-Q Design (10de:2191 103c:86d6 nvidia) Driver 550.120
INFO     2024-12-13 14:05:56,830 [startup.run_all_checks:120]:"card2" is AMD Radeon Vega 10 Graphics (1002:15d8 103c:86d6 amdgpu) Driver None
DEBUG    2024-12-13 14:05:57,360 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-12-13 14:05:57,371 [xrandr._get_vidmodes:18]:Retrieving 13 video modes from XrandR
DEBUG    2024-12-13 14:05:57,498 [path_cache._update_missing_games:114]:Checking for missing games
WARNING  2024-12-13 14:05:57,646 [base.is_authenticated:473]:Tried to get auth status while login in progress
DEBUG    2024-12-13 14:05:57,683 [api.check_stale_runtime_versions:52]:Modified at Fr 13 Dez 2024 13:31:14 , will update after Fr 13 Dez 2024 19:31:14 
DEBUG    2024-12-13 14:05:57,687 [lutriswindow.create_runtime_updater_cb:1358]:Runtime up to date
DEBUG    2024-12-13 14:06:01,529 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/ubisoft-connect
DEBUG    2024-12-13 14:06:01,529 [http._request:88]:GET https://lutris.net/api/installers/ubisoft-connect
DEBUG    2024-12-13 14:06:02,050 [application.show_window:396]:Showing window InstallerWindowubisoft-connect
DEBUG    2024-12-13 14:06:03,775 [xrandr._get_vidmodes:18]:Retrieving 13 video modes from XrandR
DEBUG    2024-12-13 14:06:05,877 [wine.get_installer_runner_version:844]:Default wine version is wine-ge-8-26
DEBUG    2024-12-13 14:06:05,972 [installerwindow.on_files_prepared:619]:Game files prepared.
DEBUG    2024-12-13 14:06:05,978 [installerwindow.present_installer_files_page:634]:Presenting installer files page
DEBUG    2024-12-13 14:06:07,141 [downloader.start:61]:⬇ https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
DEBUG    2024-12-13 14:06:25,347 [downloader.on_download_completed:166]:Finished downloading https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
INFO     2024-12-13 14:06:25,664 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-13 14:06:25,665 [files_box.on_file_available:108]:uplay is available
INFO     2024-12-13 14:06:25,665 [files_box.on_file_available:114]:All files available
INFO     2024-12-13 14:06:25,665 [installerwindow.on_files_available:664]:All files are available, continuing install
INFO     2024-12-13 14:06:25,668 [installerwindow.launch_installer_commands:672]:Launching installer commands
DEBUG    2024-12-13 14:06:25,670 [interpreter._iter_commands:315]:Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2024-12-13 14:06:25,864 [wine.create_prefix:115]:Creating a win64 prefix in /home/husky/Games/ubisoft-connect
INFO     2024-12-13 14:06:25,864 [wine.create_prefix:134]:Winepath: /home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
DEBUG    2024-12-13 14:06:25,865 [system._execute:109]:Executing /home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineboot
DEBUG    2024-12-13 14:06:25,866 [system._execute:115]:WINEARCH=win64 WINEPREFIX=/home/husky/Games/ubisoft-connect WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/mono WINE_GECKO_CACHE_DIR=/home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/gecko
INFO     2024-12-13 14:06:28,107 [wine.create_prefix:185]:win64 Prefix created in /home/husky/Games/ubisoft-connect
DEBUG    2024-12-13 14:06:28,121 [interpreter._iter_commands:315]:Installer command: {'task': {'app': 'd3dcompiler_43', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
Started initial process 23869 from /home/husky/.local/share/lutris/runtime/winetricks/winetricks -q d3dcompiler_43
Start monitoring process.
Executing cd /home/husky/.local/share/lutris/runtime/winetricks
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20240105-next - sha256sum: 65d5aaffa155adcb1883aa71fb7e14a90a899dcac11e66e6ff368de40f3f0a79 with wine-8.0-3001-g39021e609a2 (Staging) and WINEARCH=win64
Executing w_do_call d3dcompiler_43
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
d3dcompiler_43 already installed, skipping
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2024-12-13 14:06:41,755 [monitored_command.on_stop:228]:Process 23867 has terminated with code 0
DEBUG    2024-12-13 14:06:42,472 [commands._monitor_task:445]:Return code: 0
DEBUG    2024-12-13 14:06:42,472 [interpreter._iter_commands:315]:Installer command: {'task': {'app': 'corefonts', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
Started initial process 24842 from /home/husky/.local/share/lutris/runtime/winetricks/winetricks -q corefonts
Start monitoring process.
Executing cd /home/husky/.local/share/lutris/runtime/winetricks
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20240105-next - sha256sum: 65d5aaffa155adcb1883aa71fb7e14a90a899dcac11e66e6ff368de40f3f0a79 with wine-8.0-3001-g39021e609a2 (Staging) and WINEARCH=win64
Executing w_do_call corefonts
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
corefonts already installed, skipping
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2024-12-13 14:06:54,811 [monitored_command.on_stop:228]:Process 24840 has terminated with code 0
DEBUG    2024-12-13 14:06:54,833 [commands._monitor_task:445]:Return code: 0
DEBUG    2024-12-13 14:06:54,833 [interpreter._iter_commands:315]:Installer command: {'write_file': {'content': 'overlay:\n  enabled: false\n  forceunhookgame: false\n  fps_enabled: false\n  warning_enabled: false\nuser:\n  closebehavior: CloseBehavior_Close', 'file': '$GAMEDIR/drive_c/users/$USER/AppData/Local/Ubisoft Game Launcher/settings.yaml'}}
DEBUG    2024-12-13 14:06:54,929 [interpreter._iter_commands:315]:Installer command: {'task': {'args': '/S', 'executable': 'uplay', 'name': 'wineexec', 'prefix': '$GAMEDIR'}}
Started initial process 25813 from /home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/husky/.cache/lutris/installer/ubisoft-connect/uplay/UbisoftConnectInstaller.exe /S
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: could not open working directory L"unix\\home\\husky\\.cache\\lutris\\installer\\ubisoft-connect\\uplay\\", starting in the Windows directory.
Monitored process exited.
Initial process has exited (return code: 512)
Exit with return code 512
DEBUG    2024-12-13 14:06:58,864 [monitored_command.on_stop:228]:Process 25811 has terminated with code 512
DEBUG    2024-12-13 14:06:59,331 [commands._monitor_task:445]:Return code: 512
ERROR    2024-12-13 14:06:59,332 [errors.__init__:19]:Befehl beendet mit dem Code 512
ERROR    2024-12-13 14:06:59,332 [exception_backstops.error_wrapper:81]:Error handling timeout function: Befehl beendet mit dem Code 512
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Befehl beendet mit dem Code 512
INFO     2024-12-13 14:07:10,461 [interpreter.revert:386]:Cancelling installation of Ubisoft Connect
DEBUG    2024-12-13 14:07:10,615 [wine.winekill:210]:Killing all wine processes ([]) in prefix /home/husky/Games/ubisoft-connect: ['/home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineserver', '-k']
DEBUG    2024-12-13 14:07:10,615 [wine.winekill:211]:['/home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineserver', '-k']
DEBUG    2024-12-13 14:07:10,615 [wine.winekill:212]:/home/husky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineserver -k
DEBUG    2024-12-13 14:07:10,618 [wine.winekill:215]:Waiting for wine processes to terminate
DEBUG    2024-12-13 14:07:10,619 [wine.winekill:231]:Done waiting.
DEBUG    2024-12-13 14:07:10,619 [system.delete_folder:390]:Deleting folder /home/husky/.cache/lutris/installer/ubisoft-connect
DEBUG    2024-12-13 14:07:10,714 [application.on_app_window_destroyed:421]:Removed window InstallerWindowubisoft-connect
INFO     2024-12-13 14:07:12,919 [application.do_shutdown:1049]:Shutting down Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Linux Mint 22 Wilma
Arch: x86_64
Kernel: 6.8.0-50-generic
Lutris Version: 0.5.18
Desktop: X-Cinnamon
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 13.5 GB
Swap: 2.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 550.120
OpenGL Core: 4.6.0 NVIDIA 550.120
OpenGL ES: OpenGL ES 3.2 NVIDIA 550.120
Vulkan Version: 1.3.275
Vulkan Drivers: NVIDIA GeForce GTX 1660 Ti with Max-Q Design (1.3.277), AMD Radeon Vega 10 Graphics (RADV RAVEN) (1.3.274)
```

**Comment by Huwuzky** [comment]
I fixed it but you have to install a different wine version like Lutris 7.2.2

**Comment by MichelN86** [comment]
Same error code with EA App, which refuses to install too.

I am running the EA App now from within steam. Such a shame, lutris whas good but becomes shittier by every update that got released.

**Comment by legluondunet** [comment]
To obtain support for game install, do not use Github but our Discord or Lutris forum.
