### ISSUE TITLE
Lutris FLatpak: can not install FLatpak script installer

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#5793]
### Bug description

Using Lutris FLatpak I can not install Flatpak script installer

### How to Reproduce

1) open Lutris Flatpak
2) for example, go to OSU! Lutris game page:
https://lutris.net/games/osu/
3) choose " Flatpak version" and click install
4) the game does not install and you obtain an error message

### Expected behavior

Lutris Flatpak should support installing Flatpak games and script installer that uses FLatpak

### Log output

```shell
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=lutris --file-forwarding net.lutris.Lutris
Gtk-Message: 07:53:31.676: Failed to load module "xapp-gtk3-module"
Gtk-Message: 07:53:31.676: Failed to load module "xapp-gtk3-module"
Gtk-Message: 07:53:31.676: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:53:31.676: Failed to load module "canberra-gtk-module"
2024-12-14 07:53:32,131: Starting Lutris 0.5.18
2024-12-14 07:53:32,195: "card1" is AMD Radeon RX 6600M (1002:73ff 1002:0123 amdgpu) Driver 24.2.5
2024-12-14 07:53:32,258: "card0" is AMD Radeon Graphics (1002:1638 1002:0123 amdgpu) Driver 24.2.5
2024-12-14 07:53:43,932: Launching installer commands
Started initial process 61 from /usr/bin/flatpak-spawn --host flatpak install --user --app --noninteractive flathub app/sh.ppy.osu/x86_64/stable
Start monitoring process.
error: No remote refs found for ‘flathub’
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2024-12-14 07:53:44,937: La commande s'est terminée avec le code 256
2024-12-14 07:53:44,937: Error handling timeout function: La commande s'est terminée avec le code 256
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: La commande s'est terminée avec le code 256
2024-12-14 07:54:34,093: Starting Lutris 0.5.18
2024-12-14 07:54:34,122: "card1" is AMD Radeon RX 6600M (1002:73ff 1002:0123 amdgpu) Driver 24.2.5
2024-12-14 07:54:34,146: "card0" is AMD Radeon Graphics (1002:1638 1002:0123 amdgpu) Driver 24.2.5
2024-12-14 07:54:35,310: Cet installateur requiert flatpak sur votre système
2024-12-14 07:54:35,310: Error handling signal 'installer-selected': Cet installateur requiert flatpak sur votre système
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/installerwindow.py", line 356, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 92, in __init__
    self._check_binary_dependencies()
  File "/app/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 168, in _check_binary_dependencies
    raise ScriptingError(_("This installer requires %s on your system") % dependency)
lutris.installer.errors.ScriptingError: Cet installateur requiert flatpak sur votre système
2024-12-14 07:55:00,138: Cancelling installation of osu!
2024-12-14 07:55:03,050: Shutting down Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 46 Flatpak runtime
Arch: x86_64
Kernel: 6.6.63-1-MANJARO
Lutris Version: 0.5.18
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900HX with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 30.8 GB
Swap: 16.2 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6600M (radeonsi, navi23, LLVM 17.0.6, DRM 3.54, 6.6.63-1-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.5 (git-3b9fcb7e4d)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon RX 6600M (RADV NAVI23) (1.3.289), AMD Radeon Graphics (RADV RENOIR) (1.3.289)
```

**Comment by lfont** [comment]
Hi,

Installing from `Sources > Flathub` should work.  
In the error log there is this error:  
> error: No remote refs found for ‘flathub’

Run this in a terminal:

**Comment by legluondunet** [comment]
Hello @lfont , very interesting, I will get a look, thank you.
