### ISSUE TITLE
Lutris shows error after clicking on Steam

### ISSUE THREAD

**Issue by nem052** [lutris/lutris#5799]
### Bug description

Inside the Lutris App (flatpak) where Steam is listed. As soon as I click on Steam.

GoG under Sources, works!
Games under Library, works!

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

Expecting that steam login window should appear inside Lutris, in the same way GoG worked.

### Log output

```shell
command not found
```

### System Information

```shell
Failed to load games. Check that your profile is set to public during the sync.

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/services/base.py", line 144, in do_reload
    self.load()

  File "/app/lib/python3.11/site-packages/lutris/services/steam.py", line 98, in load
    raise RuntimeError(_("Failed to load games. Check that your profile is set to public during the sync."))

RuntimeError: Failed to load games. Check that your profile is set to public during the sync.

Lutris log:
[INFO:2024-12-15 08:52:02,994:application]: Starting Lutris 0.5.18
[INFO:2024-12-15 08:52:03,070:startup]: "card0" is AMD Radeon Vega 8 Graphics (1002:15d8 1002:0123 amdgpu) Driver 24.3.1
[ERROR:2024-12-15 08:52:03,769:style_manager]: Error reading color-scheme: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/style_manager.py", line 74, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
[INFO:2024-12-15 08:52:09,236:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198102333627&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2024-12-15 08:52:09,237:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f4ad8151f80>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[INFO:2024-12-15 08:53:29,911:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198102333627&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2024-12-15 08:53:29,912:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f4ad8191f80>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[WARNING:2024-12-15 08:55:35,806:system]: Non existent path: /home/andy/.var/app/net.lutris.Lutris/data/lutris/runners/proton/ge-proton
[INFO:2024-12-15 08:56:52,460:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198102333627&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2024-12-15 08:56:52,462:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f4ae8a17ba0>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[INFO:2024-12-15 08:57:38,669:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198102333627&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2024-12-15 08:57:38,669:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f4ad8151da0>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[INFO:2024-12-15 08:57:52,567:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198102333627&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2024-12-15 08:57:52,568:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f4ad8150d60>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
```

### Media (optional)

![Lutris encountered an error ](https://github.com/user-attachments/assets/3597a235-67ec-4747-ab63-6cf68d27ce43)

**Comment by TriMoon** [comment]
1. It worked for me on my system (Kubuntu 24.04), while having a loged-in Steam.
2. Try to upgrade to `Python 3.12` you seem to be out of date compared to my system.
3. It's always a good idea to mention the Linux distribution of your system...

**Comment by kRHYME7** [comment]
```
Failed to load games. Check that your profile is set to public during the sync.

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/services/base.py", line 144, in do_reload
    self.load()

  File "/app/lib/python3.11/site-packages/lutris/services/steam.py", line 98, in load
    raise RuntimeError(_("Failed to load games. Check that your profile is set to public during the sync."))

RuntimeError: Failed to load games. Check that your profile is set to public during the sync.

Lutris log:
[INFO:2024-12-28 00:38:17,998:application]: Starting Lutris 0.5.18
[INFO:2024-12-28 00:38:18,258:startup]: "card1" is NVIDIA GeForce MX250 (10de:1d52 1e83:3e21 nvidia) Driver 565.77
[INFO:2024-12-28 00:38:18,304:startup]: "card0" is Intel UHD Graphics (8086:9b41 1e83:3e21 i915) Driver None
[ERROR:2024-12-28 00:38:19,488:system]: ['/app/bin/xrandr'] command failed: Command '['/app/bin/xrandr']' returned non-zero exit status 1.
[ERROR:2024-12-28 00:38:19,488:xrandr]: Unable to generate resolution list from xrandr output
[INFO:2024-12-28 00:38:41,957:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198307600411&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2024-12-28 00:38:41,958:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7edea33d0a40>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.

```


![image](https://github.com/user-attachments/assets/18e67a8a-2217-41dc-b4e3-281807735167)



---

I have lutris flatpak and steam flatpak.

**Comment by mkalman01** [comment]
It seems that I have the same error.
I'm running on Manjaro 24.2.
As you can see from the below screenshot I have Python 3.12 installed.
`Failed to load games. Check that your profile is set to public during the sync.

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 144, in do_reload
    self.load()

  File "/usr/lib/python3.12/site-packages/lutris/services/steam.py", line 98, in load
    raise RuntimeError(_("Failed to load games. Check that your profile is set to public during the sync."))

RuntimeError: Failed to load games. Check that your profile is set to public during the sync.

Lutris log:
[INFO:2025-01-02 02:16:12,448:application]: Starting Lutris 0.5.18
[INFO:2025-01-02 02:16:12,542:startup]: "card1" is NVIDIA GeForce GTX 1050 Ti (10de:1c82 1043:85c1 nvidia) Driver 550.135
[INFO:2025-01-02 02:16:16,457:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198056702964&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2025-01-02 02:16:16,457:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7bbe8c8e27a0>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[WARNING:2025-01-02 02:16:39,300:system]: Non existent path: /home/sysadmin/.cache/lutris/installer/ea-app
[INFO:2025-01-02 02:16:41,665:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198056702964&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2025-01-02 02:16:41,665:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7bbe775d7600>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[INFO:2025-01-02 02:16:54,447:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198056702964&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2025-01-02 02:16:54,447:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7bbe775f47c0>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[INFO:2025-01-02 02:17:19,703:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198056702964&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2025-01-02 02:17:19,704:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7bbe775f7420>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[INFO:2025-01-02 02:22:40,155:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198056702964&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2025-01-02 02:22:40,155:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7bbe775f71a0>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
[INFO:2025-01-02 02:24:35,166:config]: No games in response of https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=34C9698CEB394AB4401D65927C6B3752&steamid=76561198056702964&format=json&include_appinfo=1&include_played_free_games=1
[ERROR:2025-01-02 02:24:35,167:jobs]: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7bbe775d7600>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.`
![lutris error](https://github.com/user-attachments/assets/4098f7f9-fd72-4bde-944b-669b908205a0)
