### ISSUE TITLE
Unable to install epic games store games  (flatpak)

### ISSUE THREAD

**Issue by LinuxDevloper3D** [lutris/lutris#5803]
### Bug description

When I click install on a game it says epic games store will now open but then it says the command ended with error 256 
Command exited with code 256

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: Command exited with code 256

Lutris log:
[INFO:2024-12-17 12:44:53,405:application]: Starting Lutris 0.5.18
[WARNING:2024-12-17 12:44:55,380:base]: Tried to get auth status while login in progress
[WARNING:2024-12-17 12:45:48,915:base]: Tried to get auth status while login in progress
[WARNING:2024-12-17 12:45:52,020:base]: Tried to get auth status while login in progress
[WARNING:2024-12-17 12:46:14,173:game]: Game still running (state: running)
[INFO:2024-12-17 12:46:14,177:game]: Stopping Epic Games Store (wine)
[INFO:2024-12-17 12:46:52,858:egs]: EGS detected in /home/elliot/Games/epic-games-store
[WARNING:2024-12-17 12:46:52,871:egs_launcher]: No valid path for EGS games manifests in /home/elliot/Games/epic-games-store/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests
[INFO:2024-12-17 12:47:36,687:installerwindow]: Launching installer commands
[ERROR:2024-12-17 12:47:49,861:errors]: Command exited with code 256
[ERROR:2024-12-17 12:47:49,862:exception_backstops]: Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
[INFO:2024-12-17 12:50:32,394:interpreter]: Cancelling installation of Scribble It!
[INFO:2024-12-17 12:51:26,943:installerwindow]: Launching installer commands
[ERROR:2024-12-17 12:51:42,069:errors]: Command exited with code 256
[ERROR:2024-12-17 12:51:42,071:exception_backstops]: Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256

### How to Reproduce

1. Go to A epic store game
2. Click on install
3. Do what it says on screen
4. See 'command ended with error 256

### Expected behavior

it should have downloaded the game

### Log output

```shell
i dont know how since im using flatpak and i github says im not alowed to use the log from flatpak
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 46 Flatpak runtime
Arch: x86_64
Kernel: 6.6.54-05528-gdd4efe62d86b
Lutris Version: 0.5.18
Desktop: X-Generic
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
Physical cores: 1
Logical cores: 1
[Memory]
RAM: 2.7 GB
Swap: 0.0 GB
[Graphics]
Vendor: Mesa
OpenGL Renderer: llvmpipe (LLVM 17.0.6, 128 bits)
OpenGL Version: 4.5 (Compatibility Profile) Mesa 24.3.1 (git-c815d651b8)
OpenGL Core: 4.5 (Core Profile) Mesa 24.3.1 (git-c815d651b8)
OpenGL ES: OpenGL ES 3.2 Mesa 24.3.1 (git-c815d651b8)
Vulkan Version: 1.3.261
Vulkan Drivers:
```

**Comment by LinuxDevloper3D** [comment]
epic seems to have a directory but still not sure

**Comment by LinuxDevloper3D** [comment]
~/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games$ ls
DirectXRedist  Launcher

**Comment by LinuxDevloper3D** [comment]
changed wine verison to system (9.0)
