### ISSUE TITLE
EA app install ends with error code 768

### ISSUE THREAD

**Issue by PimpOfSune** [lutris/lutris#5805]
### Bug description

Command exited with code 768

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: Command exited with code 768

Lutris log:
[INFO:2024-12-18 17:47:52,892:application]: Starting Lutris 0.5.18
[INFO:2024-12-18 17:47:53,584:startup]: "card1" is AMD Radeon Vega 8 Graphics (1002:15d8 17aa:3808 amdgpu) Driver 24.2.3
[INFO:2024-12-18 17:48:21,164:files_box]: All files available
[INFO:2024-12-18 17:48:21,165:installerwindow]: All files are available, continuing install
[INFO:2024-12-18 17:48:21,175:installerwindow]: Launching installer commands
[INFO:2024-12-18 17:48:21,403:wine]: Creating a win64 prefix in /home/ya-nou/Games/ea-app
[INFO:2024-12-18 17:48:21,403:wine]: Winepath: /home/ya-nou/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[INFO:2024-12-18 17:49:48,458:wine]: win64 Prefix created in /home/ya-nou/Games/ea-app
[ERROR:2024-12-18 18:00:12,120:errors]: Command exited with code 768
[ERROR:2024-12-18 18:00:12,447:exception_backstops]: Error handling timeout function: Command exited with code 768
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 768

### How to Reproduce

Use today's apt version of Lutris to install today's version of EA App.
Don't close it upon finishing install, login to your EA account, then fiddle with its preferences a little.
Close it (so it minimizes itself to tray).
Then Exit it from tray.

### Expected behavior

Exit with return code 0 or otherwise successful install.

### Log output

```shell
[INFO:2024-12-18 17:47:52,892:application]: Starting Lutris 0.5.18
[INFO:2024-12-18 17:47:53,584:startup]: "card1" is AMD Radeon Vega 8 Graphics (1002:15d8 17aa:3808 amdgpu) Driver 24.2.3
[INFO:2024-12-18 17:48:21,164:files_box]: All files available
[INFO:2024-12-18 17:48:21,165:installerwindow]: All files are available, continuing install
[INFO:2024-12-18 17:48:21,175:installerwindow]: Launching installer commands
[INFO:2024-12-18 17:48:21,403:wine]: Creating a win64 prefix in /home/ya-nou/Games/ea-app
[INFO:2024-12-18 17:48:21,403:wine]: Winepath: /home/ya-nou/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[INFO:2024-12-18 17:49:48,458:wine]: win64 Prefix created in /home/ya-nou/Games/ea-app
[ERROR:2024-12-18 18:00:12,120:errors]: Command exited with code 768
[ERROR:2024-12-18 18:00:12,447:exception_backstops]: Error handling timeout function: Command exited with code 768
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 768
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 24.10 Oracular Oriole
Arch: x86_64
Kernel: 6.11.0-12-generic
Lutris Version: 0.5.18
Desktop: ubuntu:GNOME
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 5.2 GB
Swap: 4.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Vega 8 Graphics (radeonsi, raven, LLVM 19.1.0, DRM 3.58, 6.11.0-12-generic)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.3-1ubuntu1
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.3-1ubuntu1
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.3-1ubuntu1
Vulkan Version: 1.3.290
Vulkan Drivers: AMD Radeon Vega 8 Graphics (RADV RAVEN) (1.3.289)
```

**Comment by MichelN86** [comment]
EA App works well in steam itself. It runs better compared to lutris

https://forum.zorin.com/t/how-to-how-to-get-the-ea-app-working-into-steam/43016?u=michel

**Comment by danieljohnson2** [comment]
Hopefully the ``ge-proton`` Wine build that the latest Lutris has will be able to do better about this. ``wine-ge-8-26`` is getting a little old.

**Comment by ManVanIran** [comment]
MichelN86 You are a hero my man,

**Comment by esuriddick** [comment]
Not sure why the issue was closed, but the workaround suggested by MichelN86 is still working.

**Comment by strycore** [comment]
locking because still using wine-GE instead of Proton-GE
