### ISSUE TITLE
Error while installing Need for Speed: Underground

### ISSUE THREAD

**Issue by archie-was-taken** [lutris/lutris#5809]
### Bug description

The required file `setup.exe` could not be located.

An unexpected error has occurred while installing the game. The app told me to share the details.

### How to Reproduce

1. Go to '+'
2. Try installing Need for Speed: Underground

### Expected behavior

I expected it to install the app without causing any errors.

### Log output

```shell
The required file 'setup.exe' could not be located.

Traceback (most recent call last):

  File "/usr/lib/python3.13/site-packages/lutris/gui/installerwindow.py", line 796, in wrapped_callback
    callback(*args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.13/site-packages/lutris/installer/commands.py", line 269, in _find_matching_disc
    raise RuntimeError(_("The required file '%s' could not be located.") % requires)

RuntimeError: The required file 'setup.exe' could not be located.

Lutris log:
[INFO:2024-12-19 20:49:27,061:application]: Starting Lutris 0.5.18
[INFO:2024-12-19 20:49:27,095:__init__]: Running migration: mess_to_mame
[INFO:2024-12-19 20:49:27,096:__init__]: Running migration: migrate_hidden_ids
[INFO:2024-12-19 20:49:27,097:__init__]: Running migration: migrate_steam_appids
[INFO:2024-12-19 20:49:27,098:__init__]: Running migration: migrate_banners
[INFO:2024-12-19 20:49:27,099:__init__]: Running migration: retrieve_discord_appids
[INFO:2024-12-19 20:49:27,100:retrieve_discord_appids]: Updating Games Discord APP ID's
[INFO:2024-12-19 20:49:27,100:__init__]: Running migration: migrate_sortname
[INFO:2024-12-19 20:49:27,101:migrate_sortname]: Adding blank sortname field to database
[INFO:2024-12-19 20:49:27,101:__init__]: Running migration: migrate_hidden_category
[INFO:2024-12-19 20:49:27,102:migrate_hidden_category]: Moving hidden games to the '.hidden' category
[INFO:2024-12-19 20:49:27,127:startup]: "card1" is No GPU (8086:9a49 1028:0ab0 i915) Driver 24.2.8
[WARNING:2024-12-19 20:49:29,558:system]: Non existent path: /home/archie/.local/share/lutris/runtime/umu
[WARNING:2024-12-19 20:49:30,020:system]: Non existent path: /home/archie/.local/share/lutris/runtime/winetricks
[WARNING:2024-12-19 20:49:56,634:system]: Non existent path: /home/archie/.local/share/lutris/runtime/battleye_runtime
[WARNING:2024-12-19 20:49:57,210:system]: Non existent path: /home/archie/.local/share/lutris/runtime/umu-games
[WARNING:2024-12-19 20:49:59,032:system]: Non existent path: /home/archie/.local/share/lutris/runtime/eac_runtime
[WARNING:2024-12-19 20:50:16,053:system]: Non existent path: /home/archie/.local/share/lutris/runtime/innoextract-1.9-linux
[WARNING:2024-12-19 20:50:18,436:system]: Non existent path: /home/archie/.local/share/lutris/runtime/p7zip
[WARNING:2024-12-19 20:50:20,197:system]: Non existent path: /home/archie/.local/share/lutris/runtime/gamecontrollerdb
[WARNING:2024-12-19 20:50:22,257:system]: Non existent path: /home/archie/.local/share/lutris/runtime/network-tools
[WARNING:2024-12-19 20:50:50,058:system]: Non existent path: /home/archie/.local/share/lutris/runtime/Ubuntu-18.04-i686
[INFO:2024-12-19 20:51:08,610:interpreter]: Runner wine needs to be installed
[WARNING:2024-12-19 20:51:35,129:system]: Non existent path: /home/archie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64
[WARNING:2024-12-19 20:51:37,402:system]: Non existent path: /home/archie/.local/share/lutris/runtime/dxvk-cache-tool
[INFO:2024-12-19 20:56:19,305:file_box]: Download completed
[INFO:2024-12-19 20:56:19,305:files_box]: All files available
[INFO:2024-12-19 20:56:19,305:installerwindow]: All files are available, continuing install
[INFO:2024-12-19 20:56:19,305:installerwindow]: Launching installer commands
[INFO:2024-12-19 20:56:19,395:wine]: Creating a win32 prefix in /home/archie/.local/opt/need-for-speed-underground
[INFO:2024-12-19 20:56:19,395:wine]: Winepath: /home/archie/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[INFO:2024-12-19 20:56:26,914:wine]: win32 Prefix created in /home/archie/.local/opt/need-for-speed-underground
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: NO
[System]
OS: Fedora Linux 41 Workstation Edition
Arch: x86_64
Kernel: 6.12.4-200.fc41.x86_64
Lutris Version: 0.5.18
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 7.5 GB
Swap: 14.9 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.8
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.8
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.8
Vulkan Version: 1.3.296
Vulkan Drivers: Intel(R) Xe Graphics (TGL GT2) (1.3.289)
```

**Comment by danieljohnson2** [comment]
There's a lot here that I don't understand, like why it's trying to install in ``/home/archie/.local/opt/need-for-speed-underground``- but I think the install script is trying to find the file ``setup.exe`` on your CD. Can you check to see if that file is actually present on the CD?

**Comment by archie-was-taken** [comment]
All right, I see what's the issue now. I've got the `.exe` file, not the CD. I chose the wrong install option. Thank you so much.
