### ISSUE TITLE
Error while installing League of Legends on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by rpaoloo** [lutris/lutris#5810]
No path can be generated for D3D Extras because no version information is available.

Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/installer/interpreter.py", line 325, in dispatch
    return method(params)
           ^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 434, in task
    command = task(**data)
              ^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/runners/commands/wine.py", line 355, in wineexec
    baseenv = runner.get_env(disable_runtime=disable_runtime)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 1150, in get_env
    self.dll_overrides.update(dll_manager.get_enabling_dll_overrides())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/util/wine/dll_manager.py", line 255, in get_enabling_dll_overrides
    if self.dll_exists(dll):
       ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/util/wine/dll_manager.py", line 132, in dll_exists
    return any(system.path_exists(os.path.join(self.path, arch, dll_name + ".dll")) for arch in self.archs.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/util/wine/dll_manager.py", line 132, in <genexpr>
    return any(system.path_exists(os.path.join(self.path, arch, dll_name + ".dll")) for arch in self.archs.values())
                                               ^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/util/wine/dll_manager.py", line 90, in path
    raise RuntimeError(

RuntimeError: No path can be generated for D3D Extras because no version information is available.

Lutris log:
[INFO:2024-12-20 16:11:12,451:application]: Starting Lutris 0.5.18
[INFO:2024-12-20 16:11:12,587:startup]: "card1" is Intel HD Graphics 5500 (8086:1616 103c:806e i915) Driver 24.3.1
[INFO:2024-12-20 16:14:19,587:interpreter]: Runner wine needs to be installed
[INFO:2024-12-20 16:25:29,627:files_box]: All files available
[INFO:2024-12-20 16:25:29,629:installerwindow]: All files are available, continuing install
[INFO:2024-12-20 16:25:29,639:installerwindow]: Launching installer commands
[INFO:2024-12-20 16:25:29,822:wine]: Creating a win64 prefix in /home/ruel/Games/league-of-legends
[INFO:2024-12-20 16:25:29,822:wine]: Winepath: /home/ruel/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[INFO:2024-12-20 16:25:54,854:wine]: win64 Prefix created in /home/ruel/Games/league-of-legends
[ERROR:2024-12-20 16:25:54,981:jobs]: Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x7f1f8b0025c0>: <class 'RuntimeError'> No path can be generated for D3D Extras because no version information is available.
[ERROR:2024-12-20 16:25:55,000:interpreter]: Last install command failed, show error

**Comment by danieljohnson2** [comment]
This looks a bit like #5770, but that one involved a networking error. Was there anything more in your log?

You might want to visit the "Preferences" dialog, "Updates" tab and click some of the "Check Again" button to get it to download the missing version info file. D3D Extras is part of the runtime, so try to download that.

**Comment by mihailim** [comment]
All that being said, to the best of my knowledge (I'm not a LoL player, just butting in) Riot Games added their Vanguard kernel-level anticheat to LoL. That fully prevents playing it on Linux, so this effort may be moot. See

* https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-FAQ-League-of-Legends
* https://old.reddit.com/r/leagueoflinux/ (stickied post)
* https://www.leagueoflegends.com/en-us/news/dev/dev-vanguard-x-lol-retrospective/
