### ISSUE TITLE
error with EA app

### ISSUE THREAD

**Issue by ludo77** [lutris/lutris#5811]
### Bug description

error when install ea app (in linux)

### How to Reproduce

1. Go to + buttom, select installer  write "EA app'
2. Click on install
3. and at the end : error code 256

### Expected behavior

error ea app installation in lutris by wine, perhaps because wine (64 bits) not wine 32 bits

### Log output

```shell
La commande s'est terminée avec le code 256

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: La commande s'est terminée avec le code 256

Lutris log:
[INFO:2024-12-20 16:20:25,687:application]: Starting Lutris 0.5.18
[INFO:2024-12-20 16:20:25,723:startup]: "card1" is NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] (10de:1f95 1043:1e91 nvidia) Driver 535.183.01
[INFO:2024-12-20 16:20:25,739:startup]: "card0" is Intel Corporation CometLake-H GT2 [UHD Graphics] (8086:9bc4 1043:1e91 i915) Driver 22.3.6
[WARNING:2024-12-20 16:20:26,184:base]: Tried to get auth status while login in progress
[WARNING:2024-12-20 16:20:26,209:base]: Tried to get auth status while login in progress
[WARNING:2024-12-20 16:20:28,771:base]: Tried to get auth status while login in progress
[WARNING:2024-12-20 16:20:31,866:base]: Tried to get auth status while login in progress
[INFO:2024-12-20 16:21:17,438:file_box]: Download completed
[INFO:2024-12-20 16:21:17,439:files_box]: All files available
[INFO:2024-12-20 16:21:17,439:installerwindow]: All files are available, continuing install
[INFO:2024-12-20 16:21:17,439:installerwindow]: Launching installer commands
[INFO:2024-12-20 16:21:17,545:wine]: Creating a win64 prefix in /home/ludovic/Games/ea-app
[INFO:2024-12-20 16:21:17,545:wine]: Winepath: /usr/bin/wine
[INFO:2024-12-20 16:21:18,359:wine]: win64 Prefix created in /home/ludovic/Games/ea-app
[ERROR:2024-12-20 16:21:45,138:errors]: La commande s'est terminée avec le code 256
[ERROR:2024-12-20 16:21:45,138:exception_backstops]: Error handling timeout function: La commande s'est terminée avec le code 256
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: La commande s'est terminée avec le code 256
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Debian GNU/Linux 12 bookworm
Arch: x86_64
Kernel: 6.1.0-28-amd64
Lutris Version: 0.5.18
Desktop: MATE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 31.2 GB
Swap: 7.8 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 22.3.6
OpenGL Core: 4.6 (Core Profile) Mesa 22.3.6
OpenGL ES: OpenGL ES 3.2 Mesa 22.3.6
Vulkan Version: 1.3.239
Vulkan Drivers: Intel(R) UHD Graphics (CML GT2) (1.3.230), NVIDIA GeForce GTX 1650 Ti (1.3.242)
```

**Comment by MichelN86** [comment]
Works fine here with latest EA Update

**Comment by legluondunet** [comment]
This repository is not a place for requesting support with a game, runner or an installer.
If you have issues installing a game or launching it, make sure you follow our essential guides on [graphics driver installation](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) and [dependencies for the wine runner](https://github.com/lutris/docs/blob/master/WineDependencies.md).
If you followed the guides and the issues persist, try asking for help in our official [Lutris Discord Server](https://discord.com/invite/Pnt5CuY).
