### ISSUE TITLE
submit-issue window non responsive until I close other lutris windows

### ISSUE THREAD

**Issue by sparr** [lutris/lutris#5814]
### Bug description

I ran `lutris --submit-issue` to attempt to report another bug. The window/dialog for describing the bug opened, but was not responsive to keyboard or mouse input. I closed the still-open game installer failure window and that had no effect. I closed the main lutris window and that made the submit issue window start responding.

### How to Reproduce

1. Launch lutris
2. Try to install a game that produces an install failure error
3. Run `lutris --submit-issue`
4. Try to type into the new issue description dialog

### Expected behavior

Input is accepted

### Log output

```shell
2024-12-21 22:32:11,880: Command 'vulkaninfo' not found on your system
2024-12-21 22:32:12,098: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-12-21 22:32:12,294 [application.do_command_line:480]:Starting Lutris 0.5.18
DEBUG    2024-12-21 22:32:12,296 [system._execute:109]:Executing lspci
INFO     2024-12-21 22:32:12,309 [startup.run_all_checks:120]:"card1" is Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (1002:164c 17aa:5097 amdgpu) Driver 24.3.1
ERROR    2024-12-21 22:32:12,310 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)
DEBUG    2024-12-21 22:32:12,413 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-12-21 22:32:12,418 [xrandr._get_vidmodes:18]:Retrieving 13 video modes from XrandR
DEBUG    2024-12-21 22:32:12,458 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-12-21 22:32:12,495 [api.check_stale_runtime_versions:52]:Modified at Sat 21 Dec 2024 10:19:17 PM , will update after Sun 22 Dec 2024 04:19:17 AM 
DEBUG    2024-12-21 22:32:12,497 [lutriswindow.create_runtime_updater_cb:1358]:Runtime up to date
DEBUG    2024-12-21 22:32:16,834 [base.install:335]:Installing 1207658890 from service gog
DEBUG    2024-12-21 22:32:16,834 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2024-12-21 22:32:17,039 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/neverwinter-nights
DEBUG    2024-12-21 22:32:17,039 [http._request:88]:GET https://lutris.net/api/installers/neverwinter-nights
DEBUG    2024-12-21 22:32:17,322 [application.show_window:396]:Showing window InstallerWindow1207658890
DEBUG    2024-12-21 22:32:18,961 [xrandr._get_vidmodes:18]:Retrieving 13 video modes from XrandR
DEBUG    2024-12-21 22:32:20,460 [gog.get_extras:340]:Download extras for GOG ID 1207658890 and its DLCs
INFO     2024-12-21 22:32:20,460 [gog.get_game_details:289]:Getting game details for 1207658890
DEBUG    2024-12-21 22:32:20,468 [http._request:88]:GET https://api.gog.com/products/1207658890?expand=downloads&locale=en-US
INFO     2024-12-21 22:32:20,745 [gog.get_game_details:289]:Getting game details for 1207658890
DEBUG    2024-12-21 22:32:20,755 [http._request:88]:GET https://api.gog.com/products/1207658890?expand=downloads&locale=en-US
DEBUG    2024-12-21 22:32:20,781 [installerwindow.present_extras_page:533]:Showing extras page
INFO     2024-12-21 22:32:23,159 [installer.prepare_game_files:168]:Getting files for nwinstaller
INFO     2024-12-21 22:32:23,159 [gog.get_game_details:289]:Getting game details for 1207658890
DEBUG    2024-12-21 22:32:23,169 [http._request:88]:GET https://api.gog.com/products/1207658890?expand=downloads&locale=en-US
INFO     2024-12-21 22:32:23,196 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658890/downlink/product_bonus/9153
DEBUG    2024-12-21 22:32:23,204 [http._request:88]:GET https://api.gog.com/products/1207658890/downlink/product_bonus/9153
INFO     2024-12-21 22:32:23,490 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658890/downlink/product_bonus/9173
DEBUG    2024-12-21 22:32:23,504 [http._request:88]:GET https://api.gog.com/products/1207658890/downlink/product_bonus/9173
INFO     2024-12-21 22:32:23,755 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658890/downlink/product_bonus/9183
DEBUG    2024-12-21 22:32:23,765 [http._request:88]:GET https://api.gog.com/products/1207658890/downlink/product_bonus/9183
INFO     2024-12-21 22:32:24,058 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658890/downlink/product_bonus/9193
DEBUG    2024-12-21 22:32:24,068 [http._request:88]:GET https://api.gog.com/products/1207658890/downlink/product_bonus/9193
INFO     2024-12-21 22:32:24,349 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658890/downlink/product_bonus/9163
DEBUG    2024-12-21 22:32:24,358 [http._request:88]:GET https://api.gog.com/products/1207658890/downlink/product_bonus/9163
INFO     2024-12-21 22:32:24,730 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658890/downlink/product_bonus/9203
DEBUG    2024-12-21 22:32:24,740 [http._request:88]:GET https://api.gog.com/products/1207658890/downlink/product_bonus/9203
INFO     2024-12-21 22:32:25,019 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/1207658890/downlink/product_bonus/9213
DEBUG    2024-12-21 22:32:25,030 [http._request:88]:GET https://api.gog.com/products/1207658890/downlink/product_bonus/9213
DEBUG    2024-12-21 22:32:25,316 [installerwindow.on_files_prepared:619]:Game files prepared.
DEBUG    2024-12-21 22:32:25,333 [installerwindow.present_installer_files_page:634]:Presenting installer files page
DEBUG    2024-12-21 22:32:26,308 [downloader.start:61]:⬇ https://lutris.nyc3.digitaloceanspaces.com/tools/innoextract/innoextract.tar.gz
DEBUG    2024-12-21 22:32:26,313 [downloader.start:61]:⬇ https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/nwclientgold.tar.gz
DEBUG    2024-12-21 22:32:26,315 [downloader.start:61]:⬇ https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/nwclienthotu.tar.gz
DEBUG    2024-12-21 22:32:26,483 [downloader.on_download_completed:166]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/tools/innoextract/innoextract.tar.gz
INFO     2024-12-21 22:32:26,809 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:26,809 [files_box.on_file_available:108]:innoextract is available
DEBUG    2024-12-21 22:32:26,810 [downloader.start:61]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1734924745~dirs=3~token=015bd59203c4b2a50170c/secure/neverwinter_nights_diamond/extras/nvn_KingmakerSetup.zip
DEBUG    2024-12-21 22:32:27,372 [downloader.on_download_completed:166]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/nwclienthotu.tar.gz
DEBUG    2024-12-21 22:32:27,590 [downloader.on_download_completed:166]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/nwclientgold.tar.gz
INFO     2024-12-21 22:32:27,814 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:27,814 [files_box.on_file_available:108]:nwclientgold is available
DEBUG    2024-12-21 22:32:27,816 [downloader.start:61]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1734924744~dirs=3~token=051b0d5d20c186f722f2d/secure/neverwinter_nights_diamond/extras/nvn_map.zip
INFO     2024-12-21 22:32:27,818 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:27,818 [files_box.on_file_available:108]:nwclient161 is available
DEBUG    2024-12-21 22:32:27,819 [downloader.start:61]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1734924744~dirs=3~token=051b0d5d20c186f722f2d/secure/neverwinter_nights_diamond/extras/nvn_artworks.zip
DEBUG    2024-12-21 22:32:32,013 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1734924744~dirs=3~token=051b0d5d20c186f722f2d/secure/neverwinter_nights_diamond/extras/nvn_map.zip
DEBUG    2024-12-21 22:32:32,139 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1734924744~dirs=3~token=051b0d5d20c186f722f2d/secure/neverwinter_nights_diamond/extras/nvn_artworks.zip
INFO     2024-12-21 22:32:32,317 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:32,317 [files_box.on_file_available:108]:9203 is available
DEBUG    2024-12-21 22:32:32,319 [downloader.start:61]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1734924744~dirs=3~token=051b0d5d20c186f722f2d/secure/neverwinter_nights_diamond/extras/nvn_avatars.zip
INFO     2024-12-21 22:32:32,321 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:32,321 [files_box.on_file_available:108]:9163 is available
DEBUG    2024-12-21 22:32:32,323 [downloader.start:61]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1734924743~dirs=3~token=073c626eec6fd4c7eb7d4/secure/neverwinter_nights_diamond/extras/nvn_soundtrack.zip
DEBUG    2024-12-21 22:32:32,384 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1734924744~dirs=3~token=051b0d5d20c186f722f2d/secure/neverwinter_nights_diamond/extras/nvn_avatars.zip
INFO     2024-12-21 22:32:32,819 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:32,819 [files_box.on_file_available:108]:9193 is available
DEBUG    2024-12-21 22:32:32,822 [downloader.start:61]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1734924743~dirs=3~token=073c626eec6fd4c7eb7d4/secure/neverwinter_nights_diamond/extras/nvn_wallpapers.zip
DEBUG    2024-12-21 22:32:33,863 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1734924743~dirs=3~token=073c626eec6fd4c7eb7d4/secure/neverwinter_nights_diamond/extras/nvn_wallpapers.zip
INFO     2024-12-21 22:32:34,323 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:34,323 [files_box.on_file_available:108]:9173 is available
DEBUG    2024-12-21 22:32:34,324 [downloader.start:61]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1734924743~dirs=3~token=073c626eec6fd4c7eb7d4/secure/neverwinter_nights_diamond/extras/nvn_manuals.zip
DEBUG    2024-12-21 22:32:34,503 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1734924743~dirs=3~token=073c626eec6fd4c7eb7d4/secure/neverwinter_nights_diamond/extras/nvn_manuals.zip
INFO     2024-12-21 22:32:34,825 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:34,825 [files_box.on_file_available:108]:9153 is available
DEBUG    2024-12-21 22:32:34,827 [downloader.start:61]:⬇ https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/nwnlauncher.tar.gz
DEBUG    2024-12-21 22:32:34,948 [downloader.on_download_completed:166]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/nwnlauncher.tar.gz
INFO     2024-12-21 22:32:35,327 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:35,327 [files_box.on_file_available:108]:nwlauncher is available
DEBUG    2024-12-21 22:32:35,329 [downloader.start:61]:⬇ https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/English_linuxclient169_xp2.tar.gz
DEBUG    2024-12-21 22:32:36,755 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1734924745~dirs=3~token=015bd59203c4b2a50170c/secure/neverwinter_nights_diamond/extras/nvn_KingmakerSetup.zip
INFO     2024-12-21 22:32:36,817 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:36,818 [files_box.on_file_available:108]:9213 is available
DEBUG    2024-12-21 22:32:37,987 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1734924743~dirs=3~token=073c626eec6fd4c7eb7d4/secure/neverwinter_nights_diamond/extras/nvn_soundtrack.zip
INFO     2024-12-21 22:32:38,332 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:38,332 [files_box.on_file_available:108]:9183 is available
DEBUG    2024-12-21 22:32:56,272 [downloader.on_download_completed:166]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/games/neverwinter-nights/English_linuxclient169_xp2.tar.gz
INFO     2024-12-21 22:32:56,337 [file_box.on_download_complete:232]:Download completed
DEBUG    2024-12-21 22:32:56,337 [files_box.on_file_available:108]:nwclient169 is available
INFO     2024-12-21 22:32:56,337 [files_box.on_file_available:114]:All files available
INFO     2024-12-21 22:32:56,337 [installerwindow.on_files_available:664]:All files are available, continuing install
INFO     2024-12-21 22:32:56,337 [installerwindow.launch_installer_commands:672]:Launching installer commands
DEBUG    2024-12-21 22:32:56,338 [interpreter._iter_commands:315]:Installer command: {'extract': {'dst': '$CACHE/tmp/innoextract', 'file': 'innoextract'}}
DEBUG    2024-12-21 22:32:56,339 [commands.extract:207]:Extracting innoextract.tar.gz
DEBUG    2024-12-21 22:32:56,339 [commands.extract:211]:extracting file /home/sparr/.cache/lutris/installer/neverwinter-nights/innoextract/innoextract.tar.gz to /home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/innoextract
DEBUG    2024-12-21 22:32:56,355 [extract.extract_archive:22]:Extracting /home/sparr/.cache/lutris/installer/neverwinter-nights/innoextract/innoextract.tar.gz to /home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/innoextract
DEBUG    2024-12-21 22:32:56,376 [system.delete_folder:390]:Deleting folder /home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/innoextract/.extract-524d0212
DEBUG    2024-12-21 22:32:56,376 [extract.extract_archive:74]:Finished extracting /home/sparr/.cache/lutris/installer/neverwinter-nights/innoextract/innoextract.tar.gz to /home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/innoextract
DEBUG    2024-12-21 22:32:56,376 [commands._killable_process:550]:Process <function extract_archive at 0x7a70da3431a0> returned: ('/home/sparr/.cache/lutris/installer/neverwinter-nights/innoextract/innoextract.tar.gz', '/home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/innoextract')
DEBUG    2024-12-21 22:32:56,383 [commands.extract:213]:Extract done
DEBUG    2024-12-21 22:32:56,384 [interpreter._iter_commands:315]:Installer command: {'execute': {'args': '--extract $nwinstaller --output-dir $CACHE/tmp/nwn/ --gog', 'file': '$CACHE/tmp/innoextract/innoextract'}}
lutris-wrapper: /home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/innoextract/innoextract
Started initial process 354677 from /home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/innoextract/innoextract --extract $nwinstaller --output-dir /home/sparr/.cache/lutris/installer/neverwinter-nights/tmp/nwn/ --gog
Start monitoring process.
Could not open file "$nwinstaller"
Done with 1 error.
Monitored process exited.
Initial process has exited (return code: 512)
All processes have quit
Exit with return code 512
DEBUG    2024-12-21 22:32:56,608 [monitored_command.on_stop:228]:Process 354675 has terminated with code 512
DEBUG    2024-12-21 22:32:57,387 [commands._monitor_task:445]:Return code: 512
ERROR    2024-12-21 22:32:57,387 [errors.__init__:19]:Command exited with code 512
ERROR    2024-12-21 22:32:57,387 [exception_backstops.error_wrapper:81]:Error handling timeout function: Command exited with code 512
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 512

***at this point in the log, I can see the main lutris window and the error report window, then I run `lutris --submit-issue`***

INFO     2024-12-21 22:33:34,891 [application.do_command_line:480]:Starting Lutris 0.5.18
DEBUG    2024-12-21 22:33:34,893 [system._execute:109]:Executing lspci
INFO     2024-12-21 22:33:34,907 [startup.run_all_checks:120]:"card1" is Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (1002:164c 17aa:5097 amdgpu) Driver 24.3.1
ERROR    2024-12-21 22:33:34,908 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)

*** at this point in the log, the submit issue window is now visible, but not responsive to keyboard or mouse input ***

INFO     2024-12-21 22:34:47,330 [interpreter.revert:386]:Cancelling installation of Neverwinter Nights
DEBUG    2024-12-21 22:34:47,331 [system.delete_folder:390]:Deleting folder /home/sparr/.cache/lutris/installer/neverwinter-nights
DEBUG    2024-12-21 22:34:47,514 [application.on_app_window_destroyed:421]:Removed window InstallerWindow1207658890

*** here I have aborted the failed install, and the submit issue window is still non responsive ***

*** here I have closed the error dialog within the main lutris window, which produced no new log output, and the submit issue window is now responsive **
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: EndeavourOS rolling rolling
Arch: x86_64
Kernel: 6.12.1-arch1-1
Lutris Version: 0.5.18
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 5500U with Radeon Graphics
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 14.5 GB
Swap: 15.9 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.59, 6.12.1-arch1-1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3.1-arch1.3
OpenGL Core: 4.6 (Core Profile) Mesa 24.3.1-arch1.3
OpenGL ES: OpenGL ES 3.2 Mesa 24.3.1-arch1.3
Vulkan Version: 1.4.303
Vulkan Drivers: AMD Radeon Graphics (RADV RENOIR) (1.3.296)
```

**Comment by danieljohnson2** [comment]
I can reproduce this easily- start Lutris and show the about box (I think any modal dialog will do the trick).

Then just run ``lutris --submit-issue`` at the terminal. The command is transferred to the running Lutris instance, but the modal dialog locks out the submit-issue dialog until the modal dialog closes.

Not sure how to fix this, though.
