### ISSUE TITLE
battle.net doesnt install Error code: 256

### ISSUE THREAD

**Issue by tomber05** [lutris/lutris#5816]
### Bug description

El comando ha finalizado con código 256

Traceback (most recent call last):

  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)

  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)

  File "/usr/lib/python3.13/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: El comando ha finalizado con código 256

Lutris log:
[INFO:2024-12-22 23:12:04,831:application]: Starting Lutris 0.5.18
[INFO:2024-12-22 23:12:04,887:startup]: "card1" is AMD Radeon RX 580 Series (1002:67df 1682:c580 amdgpu) Driver 24.3.2
[ERROR:2024-12-22 23:12:04,887:startup]: i386 libGL.so.1 missing (needed by opengl)
[ERROR:2024-12-22 23:12:04,887:startup]: i386 libvulkan.so.1 missing (needed by vulkan)
[ERROR:2024-12-22 23:12:04,887:startup]: i386 libgnutls.so.30 missing (needed by gnutls)
[ERROR:2024-12-22 23:12:05,360:style_manager]: Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No existe la interfaz «org.freedesktop.portal.Settings» en el objeto en la ruta /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/style_manager.py", line 74, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No existe la interfaz «org.freedesktop.portal.Settings» en el objeto en la ruta /org/freedesktop/portal/desktop (19)
[ERROR:2024-12-22 23:12:08,659:exception_backstops]: Error handling timeout function: 'NoneType' object has no attribute 'set_cursor'
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 98, in wrapper
    func(*a, **kw)
    ~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/gui/widgets/__init__.py", line 78, in _notify
    callback(*args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/gui/lutriswindow.py", line 199, in on_busy_started
    self.get_window().set_cursor(Gdk.Cursor.new_from_name(display, "progress"))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_cursor'
[ERROR:2024-12-22 23:12:08,853:exception_backstops]: Error handling timeout function: 'NoneType' object has no attribute 'set_cursor'
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 98, in wrapper
    func(*a, **kw)
    ~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/gui/widgets/__init__.py", line 78, in _notify
    callback(*args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/gui/lutriswindow.py", line 199, in on_busy_started
    self.get_window().set_cursor(Gdk.Cursor.new_from_name(display, "progress"))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_cursor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 98, in wrapper
    func(*a, **kw)
    ~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/gui/widgets/__init__.py", line 78, in _notify
    callback(*args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/gui/lutriswindow.py", line 202, in on_busy_stopped
    self.get_window().set_cursor(None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_cursor'
[INFO:2024-12-22 23:18:56,827:file_box]: Download completed
[INFO:2024-12-22 23:18:56,828:files_box]: All files available
[INFO:2024-12-22 23:18:56,828:installerwindow]: All files are available, continuing install
[INFO:2024-12-22 23:18:56,828:installerwindow]: Launching installer commands
[INFO:2024-12-22 23:18:56,907:wine]: Creating a win64 prefix in /home/Tomi/Games/battlenet
[INFO:2024-12-22 23:18:56,907:wine]: Winepath: /home/Tomi/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[INFO:2024-12-22 23:18:58,873:wine]: win64 Prefix created in /home/Tomi/Games/battlenet
[ERROR:2024-12-22 23:19:28,473:errors]: El comando ha finalizado con código 256
[ERROR:2024-12-22 23:19:28,474:exception_backstops]: Error handling timeout function: El comando ha finalizado con código 256
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
  File "/usr/lib/python3.13/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: El comando ha finalizado con código 256

### How to Reproduce

Steps to reproduce the behavior:
1. try to install WoW classic
2.  its tells you to install battle net for it
3.  try to install battle net

### Expected behavior

it should just let me download it and then download WoW classic but it doesnt

### Log output

```shell
2024-12-22 23:29:00,180: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
```


### System Information

```shell
Soporte de Vulkan: NO
Soporte de Esync: SÍ
Soporte de Fsync: SÍ
Wine instalado: SÍ
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: SÍ
En Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.12.6-arch1-1
Lutris Version: 0.5.18
Desktop: Hyprland
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 2600 Six-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 15.5 GB
Swap: 4.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.59, 6.12.6-arch1-1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3.2-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.3.2-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.3.2-arch1.1
Vulkan Version: 1.4.303
Vulkan Drivers: AMD Radeon RX 580 Series (RADV POLARIS10) (1.3.296)
```


### Media (optional)

_No response_

**Comment by legluondunet** [comment]
`[ERROR:2024-12-22 23:12:04,887:startup]: i386 libGL.so.1 missing (needed by opengl)
[ERROR:2024-12-22 23:12:04,887:startup]: i386 libvulkan.so.1 missing (needed by vulkan)
[ERROR:2024-12-22 23:12:04,887:startup]: i386 libgnutls.so.30 missing (needed by gnutls)`

You need to install win32 libraries for your Linux distribution, follow this guide:
https://github.com/lutris/docs/blob/master/WineDependencies.md
