### ISSUE TITLE
getting a slug error on yaml import

### ISSUE THREAD

**Issue by GamerKing122** [lutris/lutris#5819]
### Bug description

yaml importing error

### How to Reproduce

try to import yaml then throws error

### Expected behavior

game should install

### Log output

```shell
'slug'

Traceback (most recent call last):

  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)

  File "/usr/lib/python3.13/site-packages/lutris/gui/installerwindow.py", line 356, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^

  File "/usr/lib/python3.13/site-packages/lutris/installer/interpreter.py", line 82, in __init__
    self.installer = LutrisInstaller(installer, self, service=self.service, appid=_appid)
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.13/site-packages/lutris/installer/installer.py", line 29, in __init__
    self.slug = installer["slug"]
                ~~~~~~~~~^^^^^^^^

KeyError: 'slug'

Lutris log:
[INFO:2024-12-24 02:43:28,138:application]: Starting Lutris 0.5.18
[INFO:2024-12-24 02:43:28,204:startup]: "card1" is AMD Radeon Graphics (1002:1638 1043:10dc amdgpu) Driver 24.3.2
[ERROR:2024-12-24 02:43:28,262:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-12-24 02:43:28,286:startup]: "card0" is NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] (10de:25a0 1043:10dc nvidia) Driver 565.77
[WARNING:2024-12-24 02:43:28,619:base]: Tried to get auth status while login in progress
[ERROR:2024-12-24 02:44:05,803:exception_backstops]: Error handling signal 'installer-selected': 'slug'
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/gui/installerwindow.py", line 356, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/installer/interpreter.py", line 82, in __init__
    self.installer = LutrisInstaller(installer, self, service=self.service, appid=_appid)
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/installer/installer.py", line 29, in __init__
    self.slug = installer["slug"]
                ~~~~~~~~~^^^^^^^^
KeyError: 'slug'
[ERROR:2024-12-24 02:44:08,430:exception_backstops]: Error handling signal 'installer-selected': 'slug'
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/gui/installerwindow.py", line 356, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/installer/interpreter.py", line 82, in __init__
    self.installer = LutrisInstaller(installer, self, service=self.service, appid=_appid)
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/installer/installer.py", line 29, in __init__
    self.slug = installer["slug"]
                ~~~~~~~~~^^^^^^^^
KeyError: 'slug'
[INFO:2024-12-24 02:47:11,130:application]: Starting Lutris 0.5.18
[INFO:2024-12-24 02:47:11,208:startup]: "card1" is AMD Radeon Graphics (1002:1638 1043:10dc amdgpu) Driver 24.3.2
[ERROR:2024-12-24 02:47:11,273:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-12-24 02:47:11,296:startup]: "card0" is NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] (10de:25a0 1043:10dc nvidia) Driver 565.77
[WARNING:2024-12-24 02:47:11,330:base]: Tried to get auth status while login in progress
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Nobara Linux 41 KDE Plasma
Arch: x86_64
Kernel: 6.12.6-200.fsync.fc41.x86_64
Lutris Version: 0.5.18
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5800H with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 15.0 GB
Swap: 24.5 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 19.1.5, DRM 3.59, 6.12.6-200.fsync.fc41.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3.2
OpenGL Core: 4.6 (Core Profile) Mesa 24.3.2
OpenGL ES: OpenGL ES 3.2 Mesa 24.3.2
Vulkan Version: 1.3.296
Vulkan Drivers: AMD Radeon Graphics (RADV RENOIR) (1.4.303)
```

**Comment by danieljohnson2** [comment]
It's complaining about a  missing entry in the .yaml; may I ask what .yaml you are importing? Can we see it?
