### ISSUE TITLE
Installing the Epic Games Store displays a version information error

### ISSUE THREAD

**Issue by JaanusUwU** [lutris/lutris#5823]
### Bug description

Installing the Epic Games Store displays a version information error after install is complete

### How to Reproduce

1. Connect Epic Games
2. Let it automatically install the launcher
3. Click on install
4. Wait for it to finish

### Expected behavior

Epic Games launcher gets installed and connected

### Log output

```shell
ERROR    2024-12-28 01:14:08,867 [jobs.target:32]:Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x7035b1f091c0>: <class 'RuntimeError'> No path can be generated for D3D Extras because no version information is available.
  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*a, **kw)
  File "/usr/lib/python3.13/site-packages/lutris/installer/interpreter.py", line 325, in dispatch
    return method(params)
  File "/usr/lib/python3.13/site-packages/lutris/installer/commands.py", line 434, in task
    command = task(**data)
  File "/usr/lib/python3.13/site-packages/lutris/runners/commands/wine.py", line 460, in winetricks
    return wineexec(
        None,
    ...<10 lines>...
        proton_verb=proton_verb,
    )
  File "/usr/lib/python3.13/site-packages/lutris/runners/commands/wine.py", line 355, in wineexec
    baseenv = runner.get_env(disable_runtime=disable_runtime)
  File "/usr/lib/python3.13/site-packages/lutris/runners/wine.py", line 1150, in get_env
    self.dll_overrides.update(dll_manager.get_enabling_dll_overrides())
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/lutris/util/wine/dll_manager.py", line 255, in get_enabling_dll_overrides
    if self.dll_exists(dll):
       ~~~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/util/wine/dll_manager.py", line 132, in dll_exists
    return any(system.path_exists(os.path.join(self.path, arch, dll_name + ".dll")) for arch in self.archs.values())
  File "/usr/lib/python3.13/site-packages/lutris/util/wine/dll_manager.py", line 132, in <genexpr>
    return any(system.path_exists(os.path.join(self.path, arch, dll_name + ".dll")) for arch in self.archs.values())
                                               ^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/lutris/util/wine/dll_manager.py", line 90, in path
    raise RuntimeError(
        "No path can be generated for %s because no version information is available." % self.component
    )
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.12.6-zen1-1-zen
Lutris Version: 0.5.18
Desktop: Hyprland
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 7800X3D 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 30.5 GB
Swap: 4.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4070 Ti SUPER/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 565.77
OpenGL Core: 4.6.0 NVIDIA 565.77
OpenGL ES: OpenGL ES 3.2 NVIDIA 565.77
Vulkan Version: 1.4.303
Vulkan Drivers: NVIDIA GeForce RTX 4070 Ti SUPER (1.3.289), AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO) (1.3.296)
```

**Comment by danieljohnson2** [comment]
Looks like a part of the Lutris runtime hasn't been downloaded. You might be able to get it to download using the Preferences dialog (Updates tab).

You could also try turning off "D3D Extras" in the game configuration for Epic Games Store and see if that helps.

**Comment by Jaanu5** [comment]
@danieljohnson2 seems you were right, the update did help it start the installation, however a new error occurred:

Command exited with code 256

Traceback (most recent call last):

  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)

  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)

  File "/usr/lib/python3.13/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: Command exited with code 256

Lutris log:
[INFO:2024-12-28 01:32:13,849:application]: Starting Lutris 0.5.18
[INFO:2024-12-28 01:32:13,866:startup]: "card1" is AMD Radeon Graphics (1002:164e 1043:8877 amdgpu) Driver None
[INFO:2024-12-28 01:32:14,010:startup]: "card0" is NVIDIA GeForce RTX 4070 Ti SUPER (10de:2705 19da:4710 nvidia) Driver 565.77
[DEBUG:2024-12-28 01:32:14,127:xrandr]: Retrieving resolution list
[DEBUG:2024-12-28 01:32:14,129:xrandr]: Retrieving 36 video modes from XrandR
[DEBUG:2024-12-28 01:32:14,157:path_cache]: Checking for missing games
[DEBUG:2024-12-28 01:32:14,172:api]: Modified at Sat 28 Dec 2024 01:23:17 AM , will update after Sat 28 Dec 2024 07:23:17 AM 
[DEBUG:2024-12-28 01:32:14,172:lutriswindow]: Runtime up to date
[DEBUG:2024-12-28 01:32:15,158:http]: POST https://lutris.net/api/users/library?since=1735342173
[DEBUG:2024-12-28 01:32:19,082:api]: Fetching installer https://lutris.net/api/installers/epic-games-store
[DEBUG:2024-12-28 01:32:19,082:http]: GET https://lutris.net/api/installers/epic-games-store
[DEBUG:2024-12-28 01:32:19,329:application]: Showing window InstallerWindowepic-games-store
[DEBUG:2024-12-28 01:32:20,621:xrandr]: Retrieving 36 video modes from XrandR
[DEBUG:2024-12-28 01:32:21,762:wine]: Default wine version is wine-ge-8-26
[DEBUG:2024-12-28 01:32:21,789:installerwindow]: Game files prepared.
[DEBUG:2024-12-28 01:32:21,790:installerwindow]: Presenting installer files page
[DEBUG:2024-12-28 01:32:23,723:downloader]: ⬇ https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
[DEBUG:2024-12-28 01:32:23,725:downloader]: ⬇ https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi
[DEBUG:2024-12-28 01:32:41,660:downloader]: Finished downloading https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi
[INFO:2024-12-28 01:32:41,728:file_box]: Download completed
[DEBUG:2024-12-28 01:32:41,728:files_box]: epicsetup is available
[DEBUG:2024-12-28 01:32:50,751:downloader]: Finished downloading https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
[INFO:2024-12-28 01:32:51,227:file_box]: Download completed
[DEBUG:2024-12-28 01:32:51,227:files_box]: uplay is available
[INFO:2024-12-28 01:32:51,227:files_box]: All files available
[INFO:2024-12-28 01:32:51,227:installerwindow]: All files are available, continuing install
[INFO:2024-12-28 01:32:51,227:installerwindow]: Launching installer commands
[DEBUG:2024-12-28 01:32:51,227:interpreter]: Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
[INFO:2024-12-28 01:32:51,256:wine]: Creating a win64 prefix in /home/sander/Games/epic-games-store
[INFO:2024-12-28 01:32:51,256:wine]: Winepath: /home/sander/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
[DEBUG:2024-12-28 01:32:51,256:system]: Executing /home/sander/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineboot
[DEBUG:2024-12-28 01:32:51,256:system]: WINEARCH=win64 WINEPREFIX=/home/sander/Games/epic-games-store WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/sander/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/mono WINE_GECKO_CACHE_DIR=/home/sander/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/gecko
[INFO:2024-12-28 01:32:51,947:wine]: win64 Prefix created in /home/sander/Games/epic-games-store
[DEBUG:2024-12-28 01:32:51,949:interpreter]: Installer command: {'write_file': {'content': 'overlay:\n  enabled: false\n  forceunhookgame: false\n  fps_enabled: false\n  warning_enabled: false\nuser:\n  closebehavior: CloseBehavior_Close\nuser:\n  start_on_windows_start: false', 'file': '$GAMEDIR/drive_c/users/$USER/Local Settings/Application Data/Ubisoft Game Launcher/settings.yml'}}
[DEBUG:2024-12-28 01:32:51,964:interpreter]: Installer command: {'task': {'app': 'corefonts', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
[DEBUG:2024-12-28 01:32:55,593:monitored_command]: Process 100076 has terminated with code 256
[DEBUG:2024-12-28 01:32:56,026:commands]: Return code: 256
[ERROR:2024-12-28 01:32:56,026:errors]: Command exited with code 256
[ERROR:2024-12-28 01:32:56,026:exception_backstops]: Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
  File "/usr/lib/python3.13/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256

**Comment by danieljohnson2** [comment]
Good. We've improved our Proton integration in master, that may be what you need.

First, go into the game config and change the Wine version to ``ge-proton``; see if that gets it working.

If it does not, then [download the latest code](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install, just make sure you shut down Lutris entirely before trying this. Once you have the latest code running, try the store again (still using ``ge-proton`` mind) and see if that does better.

**Comment by TriMoon** [comment]
> First, go into the game config and change the Wine version to ge-proton; see if that gets it working.

Seems i'm running EGS using wine-ge-8-26 just fine...
_(I already had it installed, long time ago though)_
![image](https://github.com/user-attachments/assets/459a13aa-5137-441a-b313-018d45e3d7bd)
