### ISSUE TITLE
[git version] Error on launch

### ISSUE THREAD

**Issue by TriMoon** [lutris/lutris#5825]
```
'NoneType' object has no attribute 'hide'

Traceback (most recent call last):

  File "/home/mainuser/git/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/mainuser/git/lutris/lutris/util/jobs.py", line 98, in wrapper
    func(*a, **kw)

  File "/home/mainuser/git/lutris/lutris/gui/widgets/__init__.py", line 80, in _notify
    callback(*args, **kwargs)

  File "/home/mainuser/git/lutris/lutris/gui/application.py", line 785, in on_game_start
    self.window.hide()  # Hide launcher window
    ^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'hide'

Lutris log:
[INFO:2024-12-29 12:14:32,555:application]: Starting Lutris 0.5.18
[INFO:2024-12-29 12:14:32,597:startup]: "card1" is AMD Radeon RX 7900 XTX (1002:744c 1043:0506 amdgpu) Driver 24.0.9
[ERROR:2024-12-29 12:14:40,755:exception_backstops]: Error handling timeout function: 'NoneType' object has no attribute 'hide'
Traceback (most recent call last):
  File "/home/mainuser/git/lutris/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mainuser/git/lutris/lutris/util/jobs.py", line 98, in wrapper
    func(*a, **kw)
  File "/home/mainuser/git/lutris/lutris/gui/widgets/__init__.py", line 80, in _notify
    callback(*args, **kwargs)
  File "/home/mainuser/git/lutris/lutris/gui/application.py", line 785, in on_game_start
    self.window.hide()  # Hide launcher window
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hide'
```
No idea if this happens on each startup, because i have lutris running at moment.
But the above is what the KDE Crash popup gave as info..

Looks like you need to check for existence of the window before calling the `hide()` function...

**Comment by danieljohnson2** [comment]
I've added checks, but I am not clear on how to trigger this bug. I guess you are doing something like starting a game from the command line.

Could you give a try and see if there are any more of these errors now?

**Comment by TriMoon** [comment]
> Could you give a try and see if there are any more of these errors now?

I tried just a minute after you pushed the change last night by chance, and the error didnt happen anymore, so well done :+1:
