### ISSUE TITLE
I got error message while trying to open car mechanic sim 2021

### ISSUE THREAD

**Issue by Femar01** [lutris/lutris#5831]
I'm new to any kind of Linux usage and gaming and I tryed to open a game thru lutris which is for windows only and it had an error for me with No application specified text included. I'm not that tech savvy that I could solve this on my own so I would appreciate anyone who knows how to fix this kind of error. I'm willing to learn how to fix these kind of things and learn to use linux and lutris

No application specified.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)

  File "/usr/lib/python3/dist-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()

  File "/usr/lib/python3/dist-packages/lutris/runners/flatpak.py", line 140, in play
    raise GameConfigError(_("No application specified."))

lutris.exceptions.GameConfigError: No application specified.

Lutris log:
[INFO:2024-12-30 21:36:33,300:application]: Starting Lutris 0.5.18
[INFO:2024-12-30 21:36:33,404:startup]: "card1" is NVIDIA GeForce GTX 1060 6GB (10de:1c03 1043:85b6 nvidia) Driver 565.57.01
[ERROR:2024-12-30 21:36:33,435:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-12-30 21:36:33,452:startup]: "card0" is No GPU (simple-framebuffer) Driver None
[INFO:2024-12-30 21:57:51,010:runner]: Runtime disabled by system configuration
[WARNING:2024-12-30 21:57:51,011:runner]: Accessing game config while runner wasn't given one.
[WARNING:2024-12-30 21:57:51,011:runner]: Accessing game config while runner wasn't given one.
[ERROR:2024-12-30 21:59:02,414:exception_backstops]: Car Mechanic Simulator 2021 (flatpak) has encountered an error: No application specified.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/flatpak.py", line 140, in play
    raise GameConfigError(_("No application specified."))
lutris.exceptions.GameConfigError: No application specified.
[WARNING:2024-12-30 21:59:02,417:game]: The game has run for a very short time, did it crash?
[ERROR:2024-12-30 22:00:35,375:exception_backstops]: Car Mechanic Simulator 2021 (flatpak) has encountered an error: No application specified.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 672, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 611, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/flatpak.py", line 140, in play
    raise GameConfigError(_("No application specified."))
lutris.exceptions.GameConfigError: No application specified.
[WARNING:2024-12-30 22:00:35,376:game]: The game has run for a very short time, did it crash?

**Comment by danieljohnson2** [comment]
That log suggests to me that you tried to run your game as a Flatpak, which will never work for a Windows game. You need Wine.

First thing, go to the hamburger menu (upper right corner of the window), and use that to go into Preferences. Go to "Updates". In here, click the topmost "Check Again" button- the one that gets you the latest Wine builds.

Once you've got that, close the preferences and head to the upper left corner of the window. Click the plus up there. You get the add-game dialog, and here you can add a game that you already have. But what you need to do here depends on what the game is.

But a good guess would be "Install a Window game from an executable"- that will start with a ``setup.exe`` or the like.
