### ISSUE TITLE
invalid start byte

### ISSUE THREAD

**Issue by joonatoona** [lutris/lutris#589]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 161, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.6/site-packages/lutris/gui/lutriswindow.py", line 152, in __init__
    steamapps_paths = steam.get_steamapps_paths(flat=True)
  File "/usr/lib/python3.6/site-packages/lutris/services/steam.py", line 142, in get_steamapps_paths
    folders = get_steamapps_paths_for_platform(platform)
  File "/usr/lib/python3.6/site-packages/lutris/services/steam.py", line 124, in get_steamapps_paths_for_platform
    return runner.get_steamapps_dirs()
  File "/usr/lib/python3.6/site-packages/lutris/runners/steam.py", line 195, in get_steamapps_dirs
    steam_config = self.get_steam_config()
  File "/usr/lib/python3.6/site-packages/lutris/runners/steam.py", line 128, in get_steam_config
    return read_config(steam_data_dir)
  File "/usr/lib/python3.6/site-packages/lutris/util/steam.py", line 70, in read_config
    config = vdf_parse(steam_config_file, {})
  File "/usr/lib/python3.6/site-packages/lutris/util/steam.py", line 28, in vdf_parse
    line = steam_config_file.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
```

**Comment by strycore** [comment]
There's not a lot I can do without the faulty VDF file in Steam so I just silently catch the error. Please open another bug report if you happen to find out with VDF file causes the error (there will be an error message printed on the console)

**Comment by joonatoona** [comment]
It claims there's an invalid byte in the VDF file, but there isn't.

**Comment by strycore** [comment]
Sometimes, invalid bytes are invisible to the naked eye, have you tried inspecting the file with GHex or another hex editor?

**Comment by joonatoona** [comment]
I moved the file and it still crashes trying to read it...

**Comment by joonatoona** [comment]
I opened all VDF files from every steam folder on my machine and none of them have the bytes it's failing on.

**Comment by strycore** [comment]
That's strange! 

In file /usr/lib/python3.6/site-packages/lutris/util/steam.py before line #70, can you add a `print(config_filename)` statement? that will print out the file at fault here.

**Comment by joonatoona** [comment]
`/home/joonatoona/.local/share/Steam/config/config.vdf`

Ah, I only looked in .steam and my steam lib folder, didn't know steam had files there.

```
"ý7zXZ"
{
        "Software"
        {
                "Valve"
                {
```

Yeah, that doesn't look quite right. So it's totally a problem on my end. Maybe it would be nice to add the file location to that error? Idk.

**Comment by strycore** [comment]
Yeah, I just did that in a later commit. Seems weird that a Steam config file would get corrupted in such a way though.

**Comment by joonatoona** [comment]
My hard disk failed, I copied over my home dir but a lot of files died :( So probably an edge case.

Ah, cool! Well thanks for the help <3

**Comment by strycore** [comment]
You're lucky, I was about to release a new version of Lutris so you should have the fix in the next few minutes :)
