### ISSUE TITLE
Trying to install Wine Steam - Wine is not available for the x86_64 architecture. (Ubuntu 16.04)

### ISSUE THREAD

**Issue by IngeniousDox** [lutris/lutris#652]
Seems the problem is more widespread then first thought. It doesn't just happen with Overwatch, just more people complaining about Overwatch failing to install on Discord.

Error in terninal:

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/lutris/gui/runnersdialog.py", line 165, in on_install_clicked
>     dependency.install()
>   File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 266, in install
>     self.name, self.arch
> lutris.runners.RunnerInstallationError: wine is not available for the x86_64 architecture

**Comment by IngeniousDox** [comment]
Fixed by Strider changing default wine runner.
