### ISSUE TITLE
instant crash on opensuse tumbleweed

### ISSUE THREAD

**Issue by oldkentuckymark** [lutris/lutris#683]
```
Traceback (most recent call last):
  File "/home/mark/Apps/lutris-git/lutris/lutris/gui/application.py", line 161, in do_activate
    self.window = LutrisWindow(application=self)
  File "/home/mark/Apps/lutris-git/lutris/lutris/gui/lutriswindow.py", line 90, in __init__
    self.game_store = GameStore([], self.icon_type, self.filter_installed)
  File "/home/mark/Apps/lutris-git/lutris/lutris/gui/gameviews.py", line 62, in __init__
    self.store = Gtk.ListStore(int, str, str, Pixbuf, str, str, str, str, str, bool)
TypeError: GObject.__init__() takes exactly 0 arguments (10 given)
INFO     2017-11-08 05:08:26,552 [application]:Shutting down Lutris
```

**Comment by negofill** [comment]
The same problem here with lutris 0.4.14 and lutris from git
This can be solved by installing python3-gobject-Gdk
`sudo zypper in python3-gobject-Gdk`
now everything is working like a charm.
Can maintainers specify python3-gobject-Gdk for opensuse TW in the docs?

**Comment by strycore** [comment]
Someone tried sending a patch for lutris.spec and it broke the builds for the other OpenSUSE versions, I'll merge in a patch when the spec file is compatible with all releases.

**Comment by strycore** [comment]
spec file is now updated and the current package should work

**Comment by markehammons** [comment]
it doesn't:

``
Traceback (most recent call last):
  File "/home/mhammons/Downloads/lutris/lutris/gui/application.py", line 161, in do_activate
    self.window = LutrisWindow(application=self)
  File "/home/mhammons/Downloads/lutris/lutris/gui/lutriswindow.py", line 90, in __init__
    self.game_store = GameStore([], self.icon_type, self.filter_installed)
  File "/home/mhammons/Downloads/lutris/lutris/gui/gameviews.py", line 61, in __init__
    self.store = Gtk.ListStore(int, str, str, Pixbuf, str, str, str, str, str, bool)
TypeError: GObject.__init__() takes exactly 0 arguments (10 given)
INFO     2018-04-29 15:02:37,360 [application]:Shutting down Lutris
``
