### ISSUE TITLE
Python >= 3.6 : Missing Parentheses

### ISSUE THREAD

**Issue by takkun324** [lutris/lutris#685]
I've been trying to get the development version of Lutris running on Ubuntu 17.04 and installed Python 3.6.1. When I run ./bin/lutris.py I receive multiple occurrences of "SyntaxError: Missing parentheses in call to 'print'". Seems a new syntax requirement with v3.6.

BTW: Since I am not yet able to launch Lutris from the source, I'll post an issue later regarding corrected directions for Ubuntu 17.04. It has involved a lot of Googling on my part.

**Comment by strycore** [comment]
There are not occurrences of print statements without parenthesis in Lutris. Please provide a stacktrace.

**Comment by takkun324** [comment]
Then perhaps I'm not downloading the latest build? 
1. I'm going to https://github.com/lutris/lutris.
2. Clicking the "Clone or Download" link. I could not figure out where the version would be listed.
3. Extracting and running the command below in a terminal.

Stacktrace:
```
takkun@takkun-EP45-UD3R:~/Downloads/lutris-master$ ./bin/lutris
Traceback (most recent call last):
  File "./bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/home/takkun/Downloads/lutris-master/lutris/gui/application.py", line 25, in <module>
    import gi
  File "/home/takkun/.local/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "./bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/home/takkun/Downloads/lutris-master/lutris/gui/application.py", line 25, in <module>
    import gi
  File "/home/takkun/.local/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by takkun324** [comment]
My apologies, I'm not use to python and I was trying to rush before work. Looks like the GI (GObject) module I installed is the real culprit. Time to go back to the drawing board. I may dig into Ubuntu 14.10's libs tomorrow, since it is suppose to support 3.6.

**Comment by strycore** [comment]
yeah, that's not in Lutris, but it's weird that your PyGI package is installed in ~/.local/lib, and the random `print` statement is even weirder. 
I'd suggest deleting the version of PyGI in ~/.local/lib and use the one from your distribution's packages.

**Comment by asoltysik** [comment]
I've got the same problem @takkun324 
Are you also using `conda` tool for maganing python environments?
