### ISSUE TITLE
AttributeError: 'winesteam' object has no attribute 'get_xinput_path'

### ISSUE THREAD

**Issue by unlimitedbacon** [lutris/lutris#702]
I'm getting this when trying to launch Dark Souls. Running on Arch 64 bit. Lutris 0.4.14. I searched and couldn't find any similar issues. I tried turning on and off the xinput related runner options but it had no effect.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/util/jobs.py", line 38, in <lambda>
    GLib.idle_add(lambda: self.callback(result, error))
  File "/usr/lib/python3.6/site-packages/lutris/game.py", line 198, in do_play
    gameplay_info = self.runner.play()
  File "/usr/lib/python3.6/site-packages/lutris/runners/winesteam.py", line 401, in play
    launch_info['ld_preload'] = self.get_xinput_path()
AttributeError: 'winesteam' object has no attribute 'get_xinput_path'
```

**Comment by soredake** [comment]
Fix is here https://github.com/lutris/lutris/pull/707 @strycore

**Comment by unlimitedbacon** [comment]
cool
