### ISSUE TITLE
Flatpaked Lutris Fails to Start

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#711]
Lutris, as a Flatpak bundled by Tingping, fails to start due to the following:

`flatpak run net.lutris.Lutris/x86_64/master
Gtk-Message: Failed to load module "pk-gtk-module"
WARNING  2017-12-13 17:46:33,351 [winesteam]:wine is not installed
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lutris/gui/application.py", line 161, in do_activate
    self.window = LutrisWindow(application=self)
  File "/app/lib/python3.5/site-packages/lutris/gui/lutriswindow.py", line 154, in __init__
    steamapps_paths = steam.get_steamapps_paths(flat=True)
  File "/app/lib/python3.5/site-packages/lutris/services/steam.py", line 146, in get_steamapps_paths
    folders = get_steamapps_paths_for_platform(platform)
  File "/app/lib/python3.5/site-packages/lutris/services/steam.py", line 128, in get_steamapps_paths_for_platform
    return runner.get_steamapps_dirs()
  File "/app/lib/python3.5/site-packages/lutris/runners/winesteam.py", line 318, in get_steamapps_dirs
    linux_path = self.parse_wine_path(path, self.prefix_path)
  File "/app/lib/python3.5/site-packages/lutris/runners/winesteam.py", line 155, in prefix_path
    arch=self.game_config.get('arch')
  File "/app/lib/python3.5/site-packages/lutris/runners/winesteam.py", line 355, in get_or_create_default_prefix
    self.create_prefix(prefix, arch=arch)
  File "/app/lib/python3.5/site-packages/lutris/runners/winesteam.py", line 338, in create_prefix
    create_prefix(prefix_dir, arch=arch, wine_path=wine_path)
  File "/app/lib/python3.5/site-packages/lutris/runners/wine.py", line 114, in create_prefix
    wineboot_path = os.path.join(os.path.dirname(wine_path), 'wineboot')
  File "/usr/lib/python3.5/posixpath.py", line 148, in dirname
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'`

Afterwards the process just hangs until killed. 

This is the reference bug: https://github.com/TingPing/flatpak-packages/issues/7

**Comment by TingPing** [comment]
@strycore Despite them mentioning Flatpak I doubt it really has much relevance to Flatpak it is just making an incorrect assumption somewhere.

**Comment by strycore** [comment]
Oh, right, I didn't even read the traceback :man_facepalming:
