### ISSUE TITLE
Unable to start lutris

### ISSUE THREAD

**Issue by Zemogiter** [lutris/lutris#741]
I tried to launch lutris via terminal and got this:
Traceback (most recent call last):
  File "/usr/local/bin/lutris", line 4, in <module>
    __import__('pkg_resources').run_script('lutris==0.4.14', 'lutris')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/EGG-INFO/scripts/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/lutris/gui/application.py", line 32, in <module>
    from lutris.platforms import update_platforms
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/lutris/platforms.py", line 29, in <module>
    _init_platforms()
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/lutris/runners/__init__.py", line 50, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/lutris/runners/__init__.py", line 45, in get_runner_module
    globals(), locals(), [runner_name], 0)
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/lutris/runners/web.py", line 12, in <module>
    DEFAULT_ICON = os.path.join(datapath.get(), 'media/default_icon.png')
  File "/usr/local/lib/python3.6/dist-packages/lutris-0.4.14-py3.6.egg/lutris/util/datapath.py", line 22, in get
    raise IOError("data_path can't be found at : %s" % data_path)
OSError: data_path can't be found at : /usr/local/share/lutris

I'm not sure what causes this error. I was able to run Lutris on ubuntu 17.04 but once I updated to 17.10 I cant.

**Comment by cyian-1756** [comment]
I'm running into the same issue on ubuntu 16.04

**Comment by Zemogiter** [comment]
I've reinstalled Lutris (from ubuntu repo) and this is the outupt of lutris -d:
Traceback (most recent call last):
  File "/usr/local/bin/lutris", line 4, in <module>
    __import__('pkg_resources').run_script('lutris==0.4.14', 'lutris')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1495, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'lutris'

**Comment by strycore** [comment]
You apparently used `sudo python setup.py` since I see references to `/usr/local` in the logs. (ex: `OSError: data_path can't be found at : /usr/local/share/lutris`). 

We **HIGHLY** recommend **against** ever using setup.py install, and basically everyone who does that is on their own, losing any chance of getting support from the support team.

Your best chance is to get back to a clean state, remove any reference to lutris you can find in `/usr/local`, remove the apt package, uninstall it and reinstall it.

Our package is a standard python package, it's not broken.
