### ISSUE TITLE
Almost all native Linux games need additional directories in LD_LIBRARY_PATH on Solus

### ISSUE THREAD

**Issue by heldderarbeit** [lutris/lutris#754]
For example,

A clean install of _Hotline Miami_ can not start:

```
./hotline_launcher: symbol lookup error: /usr/lib32/libXrandr.so.2: undefined symbol: _XEatDataWords
```

After i add the /usr/lib32/ directory, it works.

![screenshot from 2018-02-07 14-10-15](https://user-images.githubusercontent.com/4840355/35918073-c3bc9520-0c10-11e8-95ac-f51c689aa74c.png)
 
Another example: **Outlast**

```
Running Outlast

appError called: 
Error: Invalid window

Error: Invalid window

Exiting due to error
support/gog_com.shlib: line 94:  9088 Aborted                 ./"${bin_64}"
```

Here the /usr/lib64/ directory is needed. (/usr/lib32/ doesn't work here).

![screenshot from 2018-02-07 14-20-23](https://user-images.githubusercontent.com/4840355/35918425-14573d22-0c12-11e8-8074-0334d9e052fe.png)

Starting _Blocks That Matter_ like it was installed:

```
Running Blocks That Matter
org.lwjgl.LWJGLException: Could not choose GLX13 config
	at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
	at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
```
and **Rogue Legacy**:

```
Running Rogue Legacy
System.DllNotFoundException: opengl32.dll
```
Again, /usr/lib32/ respectively  /usr/lib64/ fixes these issues!

However... other games such as _Torchlight II_ run just fine out of the box without any tweaks! 

That wouldn't be so bad, but the problem is I can't use any console emulator, because all of them have the option for adding a directory to the LD_LIBRARY_PATH missing (and therefore none of the games i tried would start).

**Comment by logan-arens** [comment]
This error is also occurring for me on Arch Linux with the game Infinifactory, installed through GOG's native Linux setup.
`./infinifactory.x86_64: symbol lookup error: /usr/lib/libXrandr.so.2: undefined symbol: _XEatDataWords`

Adding /usr/lib64/ to the LD_LIBRARY_PATH or disabling the Lutris runtime allows the game to run perfectly.

I've posted a draft installer (which is the basic GOG installer) over here, if you want to test it:
https://lutris.net/games/install/7535/view
