### ISSUE TITLE
Crash on startup (openSUSE Tumbleweed)

### ISSUE THREAD

**Issue by MilkyPL** [lutris/lutris#771]
Here is the error:
```
jakub@linux-f4lz:~> lutris
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 161, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.6/site-packages/lutris/gui/lutriswindow.py", line 90, in __init__
    self.game_store = GameStore([], self.icon_type, self.filter_installed)
  File "/usr/lib/python3.6/site-packages/lutris/gui/gameviews.py", line 61, in __init__
    self.store = Gtk.ListStore(int, str, str, Pixbuf, str, str, str, str, str, bool)
TypeError: GObject.__init__() takes exactly 0 arguments (10 given)
INFO     2018-02-18 13:55:49,308 [application]:Shutting down Lutris
```
Using openSUSE Tumbleweed 20180215

**Comment by fosspill** [comment]
I'm experiencing this issue too.

@strycore fixed it earlier in issue 683, but a new fix might be needed.

**Comment by xanvincent** [comment]
Same issue, but I had to install typelib-1_0-Gtk-3_0 & python3-gobject-Gdk on Tumbleweed to get it working.
