### ISSUE TITLE
Wine does not work

### ISSUE THREAD

**Issue by LeandroStanger** [lutris/lutris#782]
```
INFO     2018-03-04 22:24:17,889 [scummvm]:No ScummVM config found
INFO     2018-03-04 22:24:20,582 [lutriswindow]:Connected to lutris.net as TuiorGames
INFO     2018-03-04 22:25:08,552 [interpreter]:Downloading file 1 of 1
ERROR    2018-03-04 22:27:02,355 [wine]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2018-03-04 22:27:02,646 [thread]:Failed to execute /sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine eject -a: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lutris/thread.py", line 175, in execute_process
    cwd=self.cwd, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
ERROR    2018-03-04 22:27:15,777 [wine]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2018-03-04 22:27:20,968 [wine]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2018-03-04 22:27:21,261 [thread]:Failed to execute /sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine //setup.exe /s /sms /f1/sysroot/home/leandro/.var/app/net.lutris.Lutris/cache/lutris/installer/grand-theft-auto-san-andreas/setup.iss: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lutris/thread.py", line 175, in execute_process
    cwd=self.cwd, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
INFO     2018-03-04 22:28:26,340 [interpreter]:Downloading file 1 of 1
ERROR    2018-03-04 22:29:22,343 [wine]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2018-03-04 22:29:27,527 [wine]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2018-03-04 22:29:27,674 [thread]:Failed to execute /sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine /run/media/leandro/GTA_SA/setup.exe /s /sms /f1/sysroot/home/leandro/.var/app/net.lutris.Lutris/cache/lutris/installer/grand-theft-auto-san-andreas/setup.iss: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lutris/thread.py", line 175, in execute_process
    cwd=self.cwd, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
ERROR    2018-03-04 22:30:37,178 [wine]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2018-03-04 22:30:37,487 [thread]:Failed to execute /sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine eject -a: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lutris/thread.py", line 175, in execute_process
    cwd=self.cwd, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine'
INFO     2018-03-04 22:31:27,719 [application]:Shutting down Lutris
```

**Comment by strycore** [comment]
> /sysroot/home/leandro/.var/app/net.lutris.Lutris/data/lutris/runners/wine/3.0-i386/bin/wine

what the hell.
