### ISSUE TITLE
Lutris crashing without config files

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#783]
I was having an issue on my pc (in starting lutris) and did what I normally do is start by renaming the config dirs (/home/xxx/.config/lutris) and finally the .local/share/lutris, this made lutris sad it seems (problem was another program that died and left python active, thus stopping lutris from starting):

`Traceback (most recent call last):
  File "/src/lutris/lutris/gui/application.py", line 161, in do_activate
    self.window = LutrisWindow(application=self)
  File "/src/lutris/lutris/gui/lutriswindow.py", line 135, in __init__
    self.sidebar_treeview = SidebarTreeView()
  File "/src/lutris/lutris/gui/sidebar.py", line 68, in __init__
    self.update()
  File "/src/lutris/lutris/gui/sidebar.py", line 112, in update
    self.installed_runners = [runner.name for runner in runners.get_installed()]
  File "/src/lutris/lutris/runners/__init__.py", line 69, in get_installed
    if runner.is_installed():
  File "/src/lutris/lutris/runners/winesteam.py", line 311, in is_installed
    steam_path = self.get_steam_path()
  File "/src/lutris/lutris/runners/winesteam.py", line 256, in get_steam_path
    candidates = [self.get_default_prefix(), os.path.expanduser("~/.wine")]
  File "/src/lutris/lutris/runners/winesteam.py", line 371, in get_default_prefix
    return self.runner_config['default_%s_prefix' % arch or self.default_arch]
KeyError: 'default_None_prefix'`

shouldn't there be a nicer way to exit gracefully? something like a info box coming up and saying that "Lutris' startup state no longer reflect that of the last time it ran. Do you want to reset the state and start afresh?"

**Comment by strycore** [comment]
This comes from a bug in the master branch and isn't related to config files
