### ISSUE TITLE
Game adition error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#849]
getting this error trying to add a game with the latest git using Kubuntu 18.04:

```
Traceback (most recent call last):                                                                                                                                                             
  File "~/lutris/lutris/gui/lutriswindow.py", line 639, in on_add_game_button_clicked                                                                                         
    callback=lambda: self.add_game_to_view(dialog.game.id)                                                                                                                                     
  File "~/lutris/lutris/gui/config_dialogs.py", line 443, in __init__                                                                                                         
    self.build_tabs('game')                                                                                                                                                                    
  File "~/lutris/lutris/gui/config_dialogs.py", line 39, in build_tabs                                                                                                        
    self._build_runner_tab(config_level)
  File "~/lutris/lutris/gui/config_dialogs.py", line 239, in _build_runner_tab
    self.runner_box = RunnerBox(self.lutris_config)
  File "~/lutris/lutris/gui/config_boxes.py", line 547, in __init__
    self.generate_widgets('runner')
  File "~/lutris/lutris/gui/config_boxes.py", line 84, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "~/lutris/lutris/gui/config_boxes.py", line 174, in call_widget_generator
    raise ValueError("Unknown widget type %s" % option_type)
ValueError: Unknown widget type boolean
```

**Comment by telanus** [comment]
OK tested it a bit more, it seems it's something to do with the Wine runner, as it only happens when you try to add game from the wine runner entry, adding a game from anywhere else work, but only if you don't select the wine runner, if you do you end up with just the tab where you can select the runner, the other tabs dissapear
