### ISSUE TITLE
build from git fails to install

### ISSUE THREAD

**Issue by nonchip** [lutris/lutris#856]
this procedure still worked last week:
```
$ git pull
Already up to date.

$ python3 setup.py build_clib build_ext build_scripts build_py build
running build_clib
running build_ext
running build_scripts
running build_py
running build

$ sudo python3 setup.py install --prefix=/usr --root=/
running install
running build
running build_py
running build_scripts
running install_lib
copying build/lib/lutris/gui/widgets/download_progress.py -> /usr/lib/python3.6/site-packages/lutris/gui/widgets
copying build/lib/lutris/gui/runnerinstalldialog.py -> /usr/lib/python3.6/site-packages/lutris/gui
copying build/lib/lutris/gui/installgamedialog.py -> /usr/lib/python3.6/site-packages/lutris/gui
copying build/lib/lutris/gui/application.py -> /usr/lib/python3.6/site-packages/lutris/gui
copying build/lib/lutris/runners/mess.py -> /usr/lib/python3.6/site-packages/lutris/runners
copying build/lib/lutris/runners/runner.py -> /usr/lib/python3.6/site-packages/lutris/runners
copying build/lib/lutris/runners/rpcs3.py -> /usr/lib/python3.6/site-packages/lutris/runners
copying build/lib/lutris/runners/steam.py -> /usr/lib/python3.6/site-packages/lutris/runners
copying build/lib/lutris/runners/wine.py -> /usr/lib/python3.6/site-packages/lutris/runners
copying build/lib/lutris/runners/winesteam.py -> /usr/lib/python3.6/site-packages/lutris/runners
copying build/lib/lutris/thread.py -> /usr/lib/python3.6/site-packages/lutris
copying build/lib/lutris/runtime.py -> /usr/lib/python3.6/site-packages/lutris
copying build/lib/lutris/util/downloader.py -> /usr/lib/python3.6/site-packages/lutris/util
copying build/lib/lutris/util/system.py -> /usr/lib/python3.6/site-packages/lutris/util
copying build/lib/lutris/util/dxvk.py -> /usr/lib/python3.6/site-packages/lutris/util
copying build/lib/lutris/util/steam.py -> /usr/lib/python3.6/site-packages/lutris/util
copying build/lib/lutris/util/strings.py -> /usr/lib/python3.6/site-packages/lutris/util
copying build/lib/lutris/util/wineprefix.py -> /usr/lib/python3.6/site-packages/lutris/util
copying build/lib/lutris/services/xdg.py -> /usr/lib/python3.6/site-packages/lutris/services
copying build/lib/lutris/services/steam.py -> /usr/lib/python3.6/site-packages/lutris/services
copying build/lib/lutris/game.py -> /usr/lib/python3.6/site-packages/lutris
copying build/lib/lutris/installer/commands.py -> /usr/lib/python3.6/site-packages/lutris/installer
copying build/lib/lutris/installer/interpreter.py -> /usr/lib/python3.6/site-packages/lutris/installer
byte-compiling /usr/lib/python3.6/site-packages/lutris/gui/widgets/download_progress.py to download_progress.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/gui/runnerinstalldialog.py to runnerinstalldialog.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/gui/installgamedialog.py to installgamedialog.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/gui/application.py to application.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/runners/mess.py to mess.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/runners/runner.py to runner.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/runners/rpcs3.py to rpcs3.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/runners/steam.py to steam.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/runners/wine.py to wine.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/runners/winesteam.py to winesteam.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/thread.py to thread.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/runtime.py to runtime.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/util/downloader.py to downloader.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/util/system.py to system.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/util/dxvk.py to dxvk.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/util/steam.py to steam.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/util/strings.py to strings.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/util/wineprefix.py to wineprefix.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/services/xdg.py to xdg.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/services/steam.py to steam.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/game.py to game.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/installer/commands.py to commands.cpython-36.pyc
byte-compiling /usr/lib/python3.6/site-packages/lutris/installer/interpreter.py to interpreter.cpython-36.pyc
running install_data
copying share/lutris/controllers/dumbxinputemu-win32/xinput9_1_0.dll -> /usr/share/lutris/controllers/dumbxinputemu-win32
copying share/lutris/controllers/dumbxinputemu-win32/xinput1_3.dll -> /usr/share/lutris/controllers/dumbxinputemu-win32
copying share/lutris/controllers/dumbxinputemu-win32/xinput1_4.dll -> /usr/share/lutris/controllers/dumbxinputemu-win32
copying share/lutris/controllers/dumbxinputemu-win64/xinput9_1_0.dll -> /usr/share/lutris/controllers/dumbxinputemu-win64
copying share/lutris/controllers/dumbxinputemu-win64/xinput1_3.dll -> /usr/share/lutris/controllers/dumbxinputemu-win64
running install_egg_info
running egg_info
writing lutris.egg-info/PKG-INFO
writing dependency_links to lutris.egg-info/dependency_links.txt
writing requirements to lutris.egg-info/requires.txt
writing top-level names to lutris.egg-info/top_level.txt
reading manifest file 'lutris.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'data/media'
warning: no files found matching '*' under directory 'data/ui'
warning: no files found matching 'README'
no previously-included directories found matching 'tests'
writing manifest file 'lutris.egg-info/SOURCES.txt'
removing '/usr/lib/python3.6/site-packages/lutris-0.4.14-py3.6.egg-info' (and everything under it)
Copying lutris.egg-info to /usr/lib/python3.6/site-packages/lutris-0.4.14-py3.6.egg-info
running install_scripts
changing mode of /usr/bin/lutris to 755
```

running it fails with:
```
$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 4, in <module>
    __import__('pkg_resources').run_script('lutris==0.4.14', 'lutris')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/lutris' not found in metadata at '/usr/lib/python3.6/site-packages/lutris-0.4.14-py3.6.egg-info'

```

interestingly, `/usr/bin/lutris` contains:
```python
#!/usr/bin/python3
# EASY-INSTALL-SCRIPT: 'lutris==0.4.14','lutris'
__requires__ = 'lutris==0.4.14'
__import__('pkg_resources').run_script('lutris==0.4.14', 'lutris')
```
which is a totally different file from bin/lutris in the repo.

**Comment by nonchip** [comment]
sorry, didn't see the warning (stupid question maybe, but: why is there a setup.py if it's not to be used and randomly breaks?). running from source dir it is then, no problem.

**Comment by strycore** [comment]
the setup.py works, it's used by the packaging scripts. The problem is that the setup.py doesn't fully install Lutris, some parts are left to the distribution's package manager, leaving you with a half working installation. On top of that, there's no clean way to uninstall from a setup.py install. 

The recommended way for lutris is to have the latest stable version installed from the package manager and, if needed, have the git version in a folder for debugging or development purposes. It's easy to run lutris from the local source tree.

I'll still have a look why the setup.py script is having an issue.

**Comment by strycore** [comment]
I've tested this in a VM and the /usr/bin/lutris script came up as expected. Also, the packages are still working so it's likely to be a system specific issue.

You can re-open if you find any additional details.
