### ISSUE TITLE
Can't open Configure window.

### ISSUE THREAD

**Issue by OGMP-Gyrth** [lutris/lutris#863]
**Lutris version:** 0.4.16
**OS:** Ubuntu Linux 18.04

Hi everyone,

I just updated Lutris and can't seem to open up the configure window anymore. I have two games installed. Skyrim and Fallout New Vegas. Both give the same output.

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 708, in on_edit_game_configuration
    dialog = EditGameConfigDialog(self, game, on_dialog_saved)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_dialogs.py", line 471, in __init__
    self.build_tabs('game')
  File "/usr/lib/python3/dist-packages/lutris/gui/config_dialogs.py", line 39, in build_tabs
    self._build_runner_tab(config_level)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_dialogs.py", line 239, in _build_runner_tab
    self.runner_box = RunnerBox(self.lutris_config)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_boxes.py", line 547, in __init__
    self.generate_widgets('runner')
  File "/usr/lib/python3/dist-packages/lutris/gui/config_boxes.py", line 65, in generate_widgets
    option['choices'] = option['choices']()
  File "/usr/lib/python3/dist-packages/lutris/util/display.py", line 66, in get_unique_resolutions
    return sorted(set(get_resolutions()), key=lambda x: int(x.split('x')[0]), reverse=True)
  File "/usr/lib/python3/dist-packages/lutris/util/display.py", line 66, in <lambda>
    return sorted(set(get_resolutions()), key=lambda x: int(x.split('x')[0]), reverse=True)
ValueError: invalid literal for int() with base 10: 'v:'

**Comment by strycore** [comment]
This is fixed in master, guess we have to release 0.4.17
