### ISSUE TITLE
Commit ab17e3bad5ce breaks lutris on Kubuntu

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#871]
The latest [commit](https://github.com/lutris/lutris/commit/ab17e3bad5ce8a951c934425b6455bae9d226575) breaks lutris it seems.

The error I get trying to run it:

```
Traceback (most recent call last):
  File "./bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/home/batapete/src/lutris/lutris/gui/application.py", line 32, in <module>
    from lutris.platforms import update_platforms
  File "/home/batapete/src/lutris/lutris/platforms.py", line 29, in <module>
    _init_platforms()
  File "/home/batapete/src/lutris/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/home/batapete/src/lutris/lutris/runners/__init__.py", line 50, in import_runner
    runner_module = get_runner_module(runner_name)
  File "/home/batapete/src/lutris/lutris/runners/__init__.py", line 45, in get_runner_module
    globals(), locals(), [runner_name], 0)
  File "/home/batapete/src/lutris/lutris/runners/wine.py", line 485, in <module>
    class wine(Runner):
  File "/home/batapete/src/lutris/lutris/runners/wine.py", line 537, in wine
    'default': is_installed_systemwide(),
  File "/home/batapete/src/lutris/lutris/runners/wine.py", line 386, in is_installed_systemwide
    WINE_PATHS['build'] == 'wine' and
KeyError: 'build'
```

**Comment by strycore** [comment]
fixed.
