### ISSUE TITLE
When the donwload ends nothing happens.

### ISSUE THREAD

**Issue by rbtux** [lutris/lutris#907]
OS: Arch Linux
Game to install: EVE Online (Wine)

``Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/installerwindow.py", line 380, in on_download_complete
    self.interpreter.iter_game_files()
  File "/usr/lib/python3.6/site-packages/lutris/installer/interpreter.py", line 268, in iter_game_files
    self._download_file(current_file)
  File "/usr/lib/python3.6/site-packages/lutris/installer/interpreter.py", line 286, in _download_file
    filename = game_file[file_id]['filename']
KeyError: 'filename'``

**Comment by sigmaSd** [comment]
Hi, I updated the installer ,was missing a lot of stuff ,should work now .
To try it hit edit installer than "Test this installer" button .

**Comment by strycore** [comment]
I added some checks that will prevent this sort of crash in future releases.

**Comment by strycore** [comment]
All checks added.
