### ISSUE TITLE
Lutris Fails To Startr On OpenSUSE

### ISSUE THREAD

**Issue by benrob0329** [lutris/lutris#915]
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 26, in <module>
    gi.require_version('Gdk', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gdk not available
```

**Comment by strycore** [comment]
I tried resolving this issue a while back but I don't use OpenSUSE. So now, I'll just let an actual OpenSUSE user fix that so it actually gets fixed.

**Comment by telanus** [comment]
@strycore I get something similar if I switch from the default git clone codebase to the next codebase (via "git checkout next" tried it after @cxf detailed it on discord) . 

```
user@mypc:~/src/lutris$ git checkout next
Branch 'next' set up to track remote branch 'next' from 'origin'.
Switched to a new branch 'next'
user@mypc:~/src/lutris$ ./bin/lutris
Traceback (most recent call last):
  File "./bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "~/src/lutris/lutris/gui/application.py", line 31, in <module>
    from lutris.config import check_config
  File "~/src/lutris/lutris/config.py", line 11, in <module>
    from lutris import pga, settings, sysoptions
  File "~/src/lutris/lutris/sysoptions.py", line 9, in <module>
    from lutris.util import display, system
  File "~/src/lutris/lutris/util/display.py", line 7, in <module>
    gi.require_version('GnomeDesktop', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available
```

I'm on KDE :dancing_women:

**Comment by strycore** [comment]
@telanus install libgnome-desktop

**Comment by telanus** [comment]
@strycore it's already installed

**Comment by strycore** [comment]
Make sure gir1.2-gnomedesktop-3.0 is installed as well

**Comment by egee-irl** [comment]
The reason why this error occurs on openSUSE is because the packager did not make  `python3-gobject-Gdk` a dependency for Lutris. As such, this is a packaging bug, not a Lutris bug.

Needless to say, installing the `python3-gobject-Gdk` package fixes this issue.

**Comment by duhow** [comment]
https://pygobject.readthedocs.io/en/latest/getting_started.html#opensuse-logo-opensuse
`sudo zypper install python-gobject python3-gobject gtk3`

So... Maybe any possibility of setting `python3-gobject-Gdk` **OR** `python3-gobject` ?

**Comment by strycore** [comment]
`Requires: python3-gobject-Gdk | python3-gobject`

Does that work in SUSE? I know it does in Debian…

**Comment by duhow** [comment]
Don't know how you build packages, but assuming this is for the RPM package...

http://rpm.org/user_doc/boolean_dependencies.html (Nov 2016)
> Starting with rpm-4.13, RPM is able to process boolean expressions in all dependencies

`Requires: (pkgA or pkgB)`

**Comment by ahjolinna** [comment]
it seems `typelib-1_0-Gtk-3_0` is also needed, not just `python3-gobject-Gdk` ....(I tested it on fresh install of tumbleweed)

**Comment by RafaelLinux** [comment]
In OpenSUSE 15, I installed 
zypper in mono-core mono-basic python3-gobject-Gdk

So thank you, to all!! Now it works fine (despite some error on console) like these:

```
(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
WARNING  2018-09-02 17:41:17,354 [application]:This version of Gtk doesn't support set_option_context_summary
INFO     2018-09-02 17:41:17,385 [xdg]:Found desktop game "Outlast" (app: redbarrelsgames_com-Outlast_1, slug: outlast)
INFO     2018-09-02 17:41:17,385 [xdg]:Found desktop game "KMines" (app: org.kde.kmines, slug: kmines)
INFO     2018-09-02 17:41:17,385 [xdg]:Found desktop game "KPatience" (app: org.kde.kpat, slug: kpatience)
INFO     2018-09-02 17:41:17,385 [xdg]:Found desktop game "KMahjongg" (app: org.kde.kmahjongg, slug: kmahjongg)
INFO     2018-09-02 17:41:17,385 [xdg]:Found desktop game "KReversi" (app: org.kde.kreversi, slug: kreversi)
INFO     2018-09-02 17:41:17,385 [xdg]:Found desktop game "Winemine" (app: wine-winemine, slug: winemine)
INFO     2018-09-02 17:41:17,385 [xdg]:Found desktop game "KSudoku" (app: org.kde.ksudoku, slug: ksudoku)

(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:18392): Gtk-WARNING **: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

```

**Comment by TomBZombie** [comment]
Does anyone know which package is required on arch?

**Comment by strycore** [comment]
@TomBZombie on Arch, it's called gnome-desktop (and no, it does not install the whole gnome desktop, it's the name of the lib)

**Comment by romulasry** [comment]
It needs typelib-1_0-GnomeDesktop-3_0 on opensuse tumbleweed. That fixed it for me.

**Comment by romulasry** [comment]
I am also missing a webkit dependency on tumbleweed, any know which one. Otherwise I can't install any games. :(

**Comment by romulasry** [comment]
typelib-1_0-WebKit2-4_0 seems to be installed after a restart it works now.
