### ISSUE TITLE
[lutris next] RunnersDialog error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#943]
Get the following error trying to run the manage runners entry:

```
Traceback (most recent call last):
  File "/src/lutris/lutris/gui/lutriswindow.py", line 532, in on_manage_runners
    return RunnersDialog(transient_for=self)
  File "/src/lutris/lutris/gui/runnersdialog.py", line 47, in __init__
    self.populate_runners()
  File "/src/lutris/lutris/gui/runnersdialog.py", line 133, in populate_runners
    hbox = self.get_runner_hbox(runner_name)
  File "/src/lutris/lutris/gui/runnersdialog.py", line 83, in get_runner_hbox
    icon.show()
AttributeError: 'NoneType' object has no attribute 'show'
```

**Comment by daniel-j** [comment]
What commit do you have checked out?

**Comment by telanus** [comment]
I updated to this one tonight and still getting it:
https://github.com/lutris/lutris/commit/e01d3be86cdb10d280fade077ab2505c5bc2858b

**Comment by telanus** [comment]
OK seems something I did, but not sure why. If I run it as is it works, but as soon as I add the TIC-80 runner it throws that error, but it doesn't happen with the master branch O_o

**Comment by daniel-j** [comment]
The TIC-80 runner is not in `next` yet.
